"""_atlas_cards/cards.jsonl  ->  js/spb-ai-cards-data.js  (window.SPB_CARDS_DATA, lazy-loaded by js/spb-ai-cards.js).  GENERATED: never hand-edit.
Compact row per key: [look, analog[], syn[], moodIdx[], eraIdx[], fitIdx[], useIdx[], loud, busy, pair[], avoid[], scaleIdx, vis, appeal, body, accent, hero, risk, deep]   (deep = null or {c:look_close,f:look_far,l:light,s:stack,n:not,p:placement,w:with_numbers,q:confidence}, DEEP-SHIP 2026-10-03; scaleIdx 0 none / 1 fine / 2 medium / 3 broad)
Usage: python scripts/ai_atlas/build_cards_js.py"""
import os, sys, json, time
sys.path.insert(0, os.path.dirname(__file__))
from annotate_cards import MOODS, ERAS, FITS, USES, SCALES, CARDS, ROOT, OUT

SC = {'': 0, 'fine': 1, 'medium': 2, 'broad': 3}


def idx(vals, vocab):
    return [vocab.index(v) for v in vals if v in vocab]


DEEP_MAP = (('c', 'look_close'), ('f', 'look_far'), ('l', 'light'), ('s', 'stack'), ('n', 'not'), ('p', 'placement'), ('w', 'with_numbers'), ('q', 'confidence'))


def pack_deep(c):
    d = c.get('deep')
    if not isinstance(d, dict):
        return None
    o = {}
    for sk, lk in DEEP_MAP:
        v = d.get(lk)
        if v not in (None, '', [], {}):
            o[sk] = v
    return o or None


def load_ratings():
    rt = {}
    p = os.path.join(OUT, 'ratings.jsonl')
    if os.path.exists(p):
        for l in open(p, encoding='utf-8'):
            try:
                r = json.loads(l); rt[r['k']] = [int(r.get('appeal', 3)), int(r.get('body', 3)), int(r.get('accent', 3)), int(r.get('hero', 3)), int(r.get('risk', 3))]
            except Exception:
                pass
    return rt


def main():
    rows = {}
    rt = load_ratings()
    for l in open(CARDS, encoding='utf-8'):
        try:
            c = json.loads(l)
        except Exception:
            continue
        if not c.get('look'):
            continue
        rows[c['k']] = [c['look'], c.get('analog') or [], c.get('syn') or [], idx(c.get('mood') or [], MOODS), idx(c.get('era') or [], ERAS), idx(c.get('fit') or [], FITS),
                        idx(c.get('use') or [], USES), int(c.get('loud', 3)), int(c.get('busy', 3)), c.get('pair') or [], c.get('avoid') or [], SC.get(c.get('scale') or '', 0), 1 if c.get('vis') else 0] + rt.get(c['k'], [3, 3, 3, 3, 3]) + [pack_deep(c)]
    data = {'v': time.strftime('%Y-%m-%d'), 'moods': MOODS, 'eras': ERAS, 'uses': USES, 'fits': FITS, 'n': len(rows), 'cards': rows}
    js = '/* GENERATED by scripts/ai_atlas/build_cards_js.py from _atlas_cards/cards.jsonl (LLM-written finish cards, one per catalogue item). Do not edit by hand. */\nwindow.SPB_CARDS_DATA = ' + json.dumps(data, ensure_ascii=False, separators=(',', ':')) + ';\n'
    dst = os.path.join(ROOT, 'js', 'spb-ai-cards-data.js')
    tmp = dst + '.tmp'
    open(tmp, 'w', encoding='utf-8', newline='\n').write(js)
    for _ in range(8):
        try:
            os.replace(tmp, dst); break
        except OSError:
            time.sleep(0.5)
    print('cards %d, %d bytes -> %s' % (len(rows), len(js.encode('utf-8')), dst))
    # the latent-semantic index is learned from these cards: keep it in step (a stale file still works, keys it does not know just get no latent score)
    try:
        import subprocess; subprocess.run([sys.executable, os.path.join(os.path.dirname(__file__), 'build_lsa.py')], check=True)
    except Exception as e:
        print('WARNING: could not rebuild js/spb-lsa-data.js (%s): run python scripts/ai_atlas/build_lsa.py' % e)


if __name__ == '__main__':
    main()
