"""Build the offline LATENT-SEMANTIC index for the finish cards (js/spb-lsa-data.js).

Why: the BM25F card search only finds cards that share a WORD with the ask. LSA learns, from the 4,800 cards themselves, which words live together (lava ~ molten ~ magma ~ ember,
velvet ~ plush ~ suede, ...) so a described ask reaches finishes that never use the painter's word. Fused with BM25 in js/spb-ai-cards.js (search()).

  python scripts/ai_atlas/build_lsa.py [--k 96]  # runs scripts/ai_atlas/lsa_dump_tf.js first (per-card unigram weights from the REAL js tokenizer / stemmer / field weights ->
                                                 # _atlas_cards/lsa_tf.json) then writes js/spb-lsa-data.js (+ _atlas_cards/lsa_check.txt: nearest terms for a few words)

The projection is tiny: vocab x k int8 term vectors (per-term scale) + n x k int8 unit document vectors, base64 inside one JS file. Rebuild after the cards change; keys not in the file simply
get no latent score (the lexical search still works)."""
import os, sys, json, base64, argparse, subprocess
import numpy as np
from scipy import sparse
from sklearn.decomposition import TruncatedSVD
ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
ap = argparse.ArgumentParser(); ap.add_argument('--k', type=int, default=96); ap.add_argument('--mindf', type=int, default=2); ap.add_argument('--no-dump', action='store_true'); a = ap.parse_args()
if not a.no_dump:
    subprocess.run(['node', os.path.join(ROOT, 'scripts', 'ai_atlas', 'lsa_dump_tf.js')], check=True)
d = json.load(open(os.path.join(ROOT, '_atlas_cards', 'lsa_tf.json'), encoding='utf-8'))
keys, docs = d['keys'], d['docs']; N = len(keys)
df = {}
for row in docs:
    for t, w in row:
        df[t] = df.get(t, 0) + 1
vocab = sorted(t for t, c in df.items() if c >= a.mindf and c <= 0.4 * N)
vi = {t: i for i, t in enumerate(vocab)}
idf = np.array([np.log(1 + (N - df[t] + 0.5) / (df[t] + 0.5)) for t in vocab], dtype=np.float64)
rows, cols, vals = [], [], []
for r, row in enumerate(docs):
    for t, w in row:
        j = vi.get(t)
        if j is not None:
            rows.append(r); cols.append(j); vals.append(np.log1p(w) * idf[j])
X = sparse.csr_matrix((vals, (rows, cols)), shape=(N, len(vocab)))
nr = np.sqrt(X.multiply(X).sum(axis=1)).A1; nr[nr == 0] = 1
X = sparse.diags(1.0 / nr) @ X
svd = TruncatedSVD(n_components=a.k, random_state=7, n_iter=7); svd.fit(X)
V = svd.components_.T                                  # vocab x k
D = X @ V                                              # docs in latent space
dn = np.linalg.norm(D, axis=1); dn[dn == 0] = 1; Dn = D / dn[:, None]
print('docs', N, 'vocab', len(vocab), 'k', a.k, 'explained variance %.1f%%' % (100 * svd.explained_variance_ratio_.sum()))
# int8 quantisation: term vectors with a per-term scale (float32), document unit vectors with a global 127 scale
ts = np.abs(V).max(axis=1); ts[ts == 0] = 1e-9
Vq = np.round(V / ts[:, None] * 127).astype(np.int8)
Dq = np.round(Dn * 127).astype(np.int8)
b64 = lambda arr: base64.b64encode(arr.tobytes()).decode()
out = {'k': a.k, 'vocab': vocab, 'idf': [round(float(x), 3) for x in idf], 'ts': b64(ts.astype(np.float32)), 'V': b64(Vq), 'keys': keys, 'D': b64(Dq)}
js = '/* GENERATED by scripts/ai_atlas/build_lsa.py from the finish cards - do not edit by hand. (SPB-AI 2026-10-02) */\nwindow.SPB_LSA_DATA = ' + json.dumps(out, separators=(',', ':')) + ';\n'
open(os.path.join(ROOT, 'js', 'spb-lsa-data.js'), 'w', encoding='utf-8', newline='\n').write(js)
print('wrote js/spb-lsa-data.js %.0f KB' % (len(js) / 1024))
# sanity: nearest terms (cosine in term-vector space) for a few painter words
Vn = V / np.maximum(np.linalg.norm(V, axis=1), 1e-9)[:, None]
lines = []
for w in ['lava', 'velvet', 'moss', 'confetti', 'retro', 'stealth', 'luxury', 'weave', 'sparkl', 'molten', 'ocean', 'rust', 'neon', 'jewel']:
    if w in vi:
        s = Vn @ Vn[vi[w]]; top = [vocab[i] for i in np.argsort(-s)[1:9]]
        lines.append(w + ' -> ' + ', '.join(top))
open(os.path.join(ROOT, '_atlas_cards', 'lsa_check.txt'), 'w', encoding='utf-8').write('\n'.join(lines))
print('\n'.join(lines))
