"""Build js/spb-colours-ext.js: extra colour NAMES for the finish advisor's colour parser (the Codex L4 colour proposals: 91 exact CSS keywords + 209 racing / car-paint colours).
   python scripts/ai_atlas/build_colour_ext.py
   Names that are also ordinary words / finish-name tokens are left out (peru, snow, tomato ...); names the Pro designer already knows are left to it (the advisor asks SpbProDesign.COLOURS first)."""
import os, sys, json, re
sys.stdout.reconfigure(encoding='utf-8')
ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
SRC = os.path.join(ROOT, '_codex_work', 'finish_intel', 'l4_vocab', 'colour_proposals.json')
SKIP = set('peru snow tomato orchid wheat linen sienna thistle bisque honeydew cornsilk seashell moccasin gainsboro lavenderblush mistyrose oldlace papayawhip peachpuff navajowhite blanchedalmond'.split())
rows = json.load(open(SRC, encoding='utf-8'))
out = {}
for r in rows:
    names = [r['name']] + list(r.get('aliases') or [])
    hx = str(r.get('hex') or '').lower()
    if not re.match(r'^#[0-9a-f]{6}$', hx):
        continue
    for n in names:
        n = re.sub(r'\s+', ' ', n.lower().replace('-', ' ')).strip()
        if len(n) < 4 or n in SKIP or n.replace(' ', '') in SKIP:
            continue
        out.setdefault(n, hx)
js = '/* generated by scripts/ai_atlas/build_colour_ext.py (do not edit): extra colour names for the finish advisor */\nwindow.SPB_COLOUR_EXT = ' + json.dumps(out, separators=(',', ':'), sort_keys=True) + ';\n'
p = os.path.join(ROOT, 'js', 'spb-colours-ext.js'); open(p, 'w', encoding='utf-8', newline='').write(js)
print('wrote', p, len(out), 'names,', len(js), 'bytes')
