#!/usr/bin/env python
"""ideas batch 05 (2026-10-05): night/neon, military, emergency, high-vis, carbon, two-tone, fades, camo."""
from enc_ideas_build import *

X = lambda t, g, s, r, screen=None: dict(title=t, goal=g, settings=s, result=r, **({'screen': screen} if screen else {}))
D = lambda h, b: dict(heading=h, body=b)
Q = lambda q, a: dict(q=q, a=a)
M = lambda s, c, f: dict(symptom=s, cause=c, fix=f)
FAM = doc(DOC_LIVERY, 'Classic scheme families')
READ = doc(DOC_DESIGN, 'Readability first')
THEMES = doc(DOC_DESIGN, 'Themes -> where to look')

if todo('neon_night'):
    art('neon_night', 'Neon night: a dark car with glowing accents',
        'A neon night car is a near-black body with one or two glowing colours in thin lines and panels. Use dark satin plus a Neon Underground finish or bright solid accents.',
        'Neon works because of contrast: very dark ground, very bright small areas. Pick one or two glow colours (cyan and magenta is the classic pair) and keep them to edges, slashes and the lower body.',
        'beginner',
        [S_ZONE, S_BASE % 'Satin (metal 0, roughness 95, coat 70)' + ' with Use solid color #07080d.',
         'Add glow lines: ' + S_BOX + ' Thin boxes along the beltline and rocker, Gloss with #00e5ff or #ff2bd6.',
         'For ready-made neon, pick Neon Underglow, Split Underglow, Puddle Neon or Tokyo Rain in Base Material on a box over the lower body, BASE COLOR on Use finish\'s own color.',
         S_RENDER],
        [X('Cyan line on black', 'Minimal neon', {'Body': 'Satin, #07080d', 'Line zone': 'Thin box on the beltline, Gloss, #00e5ff'}, 'A black car with a thin cyan glow line.', 'cat_neon_underground'),
         X('Split underglow', 'Cyan and magenta', {'Zone': 'Draw box over the lower third', 'Base Material': 'Split Underglow', 'BASE COLOR': "Use finish's own color"}, 'Cyan and magenta ground light splitting a smoked body.', 'cat_neon_underground'),
         X('Wet city', 'Rain on neon', {'Base Material': 'Puddle Neon', 'Strength': '70'}, 'Cyan, pink and orange ripples on dark blue.', 'cat_cyberpunk')],
        [D('Dark ground', 'The darker the body, the brighter the neon feels. Keep the body under about 10 percent brightness.'), D('Two colours', 'Cyan and magenta, or lime and purple. A third colour starts to look like a mess.'), D('Judge in the sim', 'Glow shows best at night in the sim; check the preview on a dark background.')],
        [Q('How do I make a neon car?', 'Near-black body and one or two bright thin accents.'), Q('Which finishes glow?', 'Neon Underglow, Split Underglow, Puddle Neon, Tokyo Rain, Midnight Drift.'), Q('Is it too bright for day races?', 'Neon looks dark in daylight; pick it for night.')],
        [M('Neon looks washed out', 'Body is mid-grey', 'Make the body near-black.'), M('Too many colours', 'Three glow colours', 'Use two.')],
        ['Wet Apex and Midnight Drift add reflective-road feel under the glow.'],
        ['neon night', 'neon look', 'neon car', 'night look', 'glow in the dark look', 'underglow look', 'neon glow', 'cyan and magenta', 'night racer', 'blacklight look', 'club look', 'glowing accents'],
        fin=['base::satin', 'base::neon_electric_blue', 'base::neon_dual_glow', 'base::cbp_puddle_neon', 'monolithic::neon2_rain', 'monolithic::neon2_torque_scar'],
        related=['ideas.cyberpunk_synthwave', 'ideas.jdm', 'ideas.make_it_pop'], combos=[('ideas.make_it_pop', 'Neon on dark is the strongest contrast.')],
        screens=['cat_neon_underground', 'cat_cyberpunk'], quick=True, extra_src=[THEMES])

if todo('cyberpunk_synthwave'):
    art('cyberpunk_synthwave', 'Cyberpunk and synthwave: purple dusk, grids and chrome',
        'Synthwave is a purple-to-pink dusk, a neon grid and chrome; cyberpunk is dark enamel with magenta and cyan signage. Use a Cyberpunk finish plus the Neon Grid pattern.',
        'Both looks are 1980s futures. Synthwave uses sunset gradients and grid lines; cyberpunk uses rainy street signage and circuit patterns. The catalogue has dedicated finishes for each.',
        'intermediate',
        [S_ZONE, S_BASE % 'Gloss (metal 0, roughness 30, coat 16)' + ' with Use solid color #1b0f3a (deep purple).',
         'Add a sunset fade: set BASE COLOR to Custom gradient from #ff2bd6 to #1b0f3a on the hood or roof, or add a zone using Amber Night.',
         'Add the grid: ' + S_BOX + ' PATTERN Neon Grid, Paint mode Blend, Scale (pattern) 0.6, on the lower body.',
         'For cyberpunk, pick Neon Sign Enamel, Neon Capillary or Quantum Violet in Base Material. ' + S_RENDER],
        [X('Synthwave dusk', 'Grid and gradient', {'Body': 'Gloss, #1b0f3a', 'Hood zone': 'BASE COLOR Custom gradient #ff2bd6 to #1b0f3a', 'Lower': 'PATTERN Neon Grid, Blend, 0.6'}, 'A purple car with a pink dusk fade and a glowing grid.', 'cat_cyberpunk'),
         X('Neon sign enamel', 'Cyberpunk street', {'Base Material': 'Neon Sign Enamel', 'BASE COLOR': "Use finish's own color"}, 'Layered magenta and scarlet sign strokes with cyan borders.', 'cat_cyberpunk'),
         X('Quantum violet', 'Net-run', {'Base Material': 'Quantum Violet'}, 'A deep violet with digital glow.', 'cat_cyberpunk')],
        [D('Gradient limits', 'A gradient runs across the whole flat sheet and does not line up across panels, so use a zone per panel.'), D('Palette', 'Purple, pink and cyan on black is the core.')],
        [Q('How do I make synthwave?', 'Purple body, pink fade, neon grid.'), Q('Cyberpunk?', 'Neon Sign Enamel and Netrun finishes.'), Q('Retro 80s?', 'See the 80s article.')],
        [M('Gradient breaks at the doors', 'Sheet-wide gradient', 'One zone per panel.'), M('Grid too fine', 'Scale low', 'Raise Scale (pattern) to 0.6.')],
        ['Black-on-purple with one cyan line reads best.'],
        ['synthwave', 'synthwave look', 'cyberpunk', 'cyberpunk look', 'outrun look', 'vaporwave', 'retrowave', 'miami vice look', 'sunset gradient', 'grid look', 'cyber look', 'futuristic neon', '80s neon'],
        fin=['base::gloss', 'monolithic::grad_amber_night', 'base::cbp_kanji_signage', 'base::cbp_neon_tube', 'base::cbp_quantum_violet'], pat=['decade_80s_neon_grid'],
        related=['ideas.neon_night', 'ideas.retro_80s', 'ideas.fade_gradient'], combos=[('ideas.retro_80s', 'Same era palette.')],
        screens=['cat_cyberpunk', 'cat_gradients'], extra_src=[THEMES])

if todo('fighter_jet'):
    art('fighter_jet', 'Fighter jet: grey on grey, soft shine and panel edges',
        'A fighter-jet look is low-contrast greys with a slightly worn, matte finish and darker panel edges. Use Cerakote Grey or Parkerised with a faint sandblast overlay.',
        'Military aircraft are painted to disappear: two or three close greys, no gloss, small stencil-style details. The shine is flat with a faint metal glint where paint wears.',
        'intermediate',
        [S_ZONE, S_BASE % 'Matte (metal 0, roughness 200, coat 160)' + ' with Use solid color #6b7078.',
         'Make a second grey: ' + S_BOX + ' Draw big shapes on the wings area or lower body, Matte with #565b63, for the low-contrast two-tone.',
         'Add wear: open BASE > SPEC OVERLAYS > + ADD SPEC OVERLAY, choose Sandblast Strip, Strength 25.',
         'For a one-click version pick Cerakote Grey, Parkerised or Battle Worn in Base Material. ' + S_RENDER],
        [X('Two-grey jet', 'Low visibility', {'Body': 'Matte, #6b7078', 'Shapes': 'Matte, #565b63', 'SPEC OVERLAY': 'Sandblast Strip, 25'}, 'Soft grey on grey with faint wear.', 'cat_tactical_field'),
         X('Parkerised', 'Metal-treated', {'Base Material': 'Parkerised', 'BASE COLOR': "Use finish's own color"}, 'A dark phosphate finish with a faint metal glint.', 'cat_tactical_field'),
         X('Worn edges', 'Combat worn', {'Base Material': 'Battle Worn', 'Base Strength': '60'}, 'Cerakote worn through to metal at the edges.', 'spec_wear')],
        [D('Low contrast on purpose', 'Greys within 10 to 15 percent of each other keep the jet look.'), D('Numbers', 'Use a dark outline number with low-contrast fill, or a white one if it must be readable on TV.')],
        [Q('How do I make a fighter jet livery?', 'Two greys, matte finish, faint wear.'), Q('Gloss?', 'No, matte or satin.'), Q('Stealth?', 'See the stealth article.')],
        [M('Looks like a flat grey car', 'One grey only', 'Add a second close grey in big shapes.'), M('Too clean', 'No wear', 'Add Sandblast Strip at 25.')],
        ['Keep the roof and wing shapes in a slightly darker grey.'],
        ['fighter jet', 'fighter jet look', 'like a fighter jet', 'jet look', 'military jet', 'air force look', 'aircraft grey', 'stealth jet', 'fighter plane paint', 'grey on grey', 'military grey', 'gunship grey', 'raptor look'],
        fin=['base::matte', 'base::tac_cerakote_grey', 'base::tac_parkerised', 'base::tac_battle_worn', 'base::tac_nitride_black'], spc=['spec_sandblast_strip'],
        related=['ideas.stealth_murdered_out', 'ideas.military_tactical'], combos=[('ideas.stealth_murdered_out', 'Darker cousin.')],
        screens=['cat_tactical_field', 'spec_wear'], quick=True, extra_src=[THEMES])

if todo('military_tactical'):
    art('military_tactical', 'Military and tactical: flat earth tones and hardware finishes',
        'Military style is flat olive, tan or grey with a matte finish and hardware textures. Use the Tactical finishes (Hardware and Night shelves) for a one-click look.',
        'Tactical looks are about no shine and no loud colours: olive drab, desert tan, coyote, black. The catalogue has Hardware, Night and Camo shelves that bring the right surface feel.',
        'beginner',
        [S_ZONE, S_BASE % 'Matte (metal 0, roughness 200, coat 160)' + ' with Use solid color #4b5a3a (olive) or #b39b72 (tan).',
         'Add hardware trim: ' + S_BOX + ' on the roof and lower body, Base Material FDE Polymer or Anodised Hard.',
         'Optional camo on the lower body: see the camo articles.',
         S_RENDER],
        [X('Olive drab', 'Classic flat', {'Body': 'Matte, #4b5a3a', 'Trim zone': 'FDE Polymer on lower body'}, 'Flat olive car with tan trim.', 'cat_tactical_field'),
         X('Desert tan', 'Sandy look', {'Body': 'Matte, #b39b72', 'Base Material': 'Cerakote Grey on roof'}, 'Sand car with a grey roof panel.', 'cat_tactical_field'),
         X('Night ops', 'Dark', {'Base Material': 'Blackout Curtain'}, 'A very dark flat finish.', 'cat_tactical_field')],
        [D('Colours', 'Olive, tan, coyote, grey and black.'), D('Hardware shelf', 'Cerakote Grey, Parkerised, Nitride Black and Gun Blue are finish-like looks.')],
        [Q('How do I do a military look?', 'Flat olive or tan with hardware trim.'), Q('Gloss?', 'No.'), Q('Camo?', 'See the camo articles.')],
        [M('Looks like a toy', 'Too saturated green', 'Use a duller olive.'), M('Too shiny', 'Gloss body', 'Use Matte.')],
        ['Use matte for body, satin only on small trim.'],
        ['military look', 'military style', 'tactical look', 'army look', 'army green', 'olive drab', 'desert tan', 'coyote tan', 'tactical livery', 'soldier look', 'war machine', 'marine look', 'special forces look'],
        fin=['base::matte', 'base::tac_fde_polymer', 'base::tac_anodised_hard', 'base::tac_cerakote_grey', 'base::tac_blackout_curtain'],
        related=['ideas.fighter_jet', 'ideas.camo_woodland_desert', 'ideas.stealth_murdered_out'], combos=[('ideas.camo_woodland_desert', 'Add camo on the lower body.')],
        screens=['cat_tactical_field'], extra_src=[THEMES])

if todo('police_emergency'):
    art('police_emergency', 'Police and emergency: black and white, bold stripe, reflective trim',
        'A generic emergency look is a two-tone body (black and white, or white and a bold colour), a bright stripe and retroreflective trim. No real department names or badges needed.',
        'Patrol cars use high-contrast two-tones so they read at night and in the mirror. Build a black lower or upper half, a white body, a bright stripe, and add the Retroreflective spec overlay on the stripe for night glint.',
        'beginner',
        [S_ZONE, S_BASE % 'Gloss (metal 0, roughness 30, coat 16)' + ' with Use solid color #f4f4f4.',
         'Add the black panels: ' + S_BOX + ' Doors, hood and trunk in Gloss, #0b0b0e, leaving fenders white (a classic split).',
         'Add the stripe: a thin box along the beltline in Gloss with #0a3fd0 or #c8102e. Open BASE > SPEC OVERLAYS > + ADD SPEC OVERLAY and choose Retroreflective, Strength 60, on this zone.',
         'Keep door centres plain for numbers. ' + S_RENDER],
        [X('Black and white', 'Classic patrol', {'Body': 'Gloss, #f4f4f4', 'Door and hood zone': 'Gloss, #0b0b0e', 'Stripe': 'Gloss, #0a3fd0 + Retroreflective 60'}, 'Two-tone car with a reflective blue stripe.', 'cat_signal'),
         X('Hazard accent', 'Warning chevrons', {'Zone': 'Rear bumper box', 'Base Material': 'Wasp Signal'}, 'Yellow-black chevron cuticle on the bumper.', 'cat_signal')],
        [D('Keep it generic', 'Use colour and layout; do not copy real agency names or badges.'), D('Retroreflective is spec', 'It changes the glint, not the colour, so the stripe keeps your colour.')],
        [Q('How do I make a police car?', 'Black and white two-tone with a bright stripe.'), Q('Reflective trim?', 'Retroreflective spec overlay.'), Q('Lights?', 'Roof lights are not paintable here.')],
        [M('Looks like a taxi', 'Yellow and black', 'Use black and white.'), M('Stripe too thin', 'Hard to see', 'Make it about a tenth of the door height.')],
        ['Use stripes and colour blocks rather than text; real agency names and badges are not needed.'],
        ['police car', 'police livery', 'police look', 'cop car', 'cop car look', 'patrol car', 'emergency vehicle', 'emergency look', 'black and white cruiser', 'cruiser look', 'sheriff look', 'ambulance look', 'fire truck look'],
        fin=['base::gloss', 'base::wasp_warning', 'base::cbp_hazard_stripe'], spc=['spec_retroreflective'],
        related=['ideas.high_vis', 'ideas.two_tone', 'ideas.readable_on_tv'], combos=[('ideas.high_vis', 'Bright warning colours.')],
        screens=['cat_signal'], quick=True, extra_src=[READ])

if todo('high_vis'):
    art('high_vis', 'High-vis: safety yellow, orange and reflective stripes',
        'High-vis is a fluorescent yellow-green or orange body with bold black or silver bands. Use plain gloss with bright solid colours plus the Retroreflective spec overlay on the bands.',
        'Safety colours are chosen to be seen from far away and at night: lime-yellow, blaze orange, and a stripe in black or reflective silver. Keep the layout simple and the colours very saturated.',
        'beginner',
        [S_ZONE, S_BASE % 'Gloss (metal 0, roughness 30, coat 16)' + ' with Use solid color #d7ff00 (lime) or #ff6a00 (orange).',
         'Add bands: ' + S_BOX + ' Chevrons or horizontal bands in Gloss, #0b0b0e. For orange you can pick Blaze Orange in Base Material instead.',
         'Add reflective glint: BASE > SPEC OVERLAYS > + ADD SPEC OVERLAY, choose Retroreflective, Strength 60, on the bands.',
         S_RENDER],
        [X('Lime with black bands', 'Roadworks', {'Body': 'Gloss, #d7ff00', 'Band zone': 'Gloss, #0b0b0e, thin boxes', 'SPEC OVERLAY': 'Retroreflective 60'}, 'A lime car with black bands that glint at night.', 'cat_signal'),
         X('Blaze orange', 'Hunting and rescue', {'Base Material': 'Blaze Orange', 'Check': 'about metal 16, roughness 51, coat 48'}, 'A fluorescent-feel orange with a high shine.', 'cat_signal'),
         X('Wasp warning', 'Hazard chevrons', {'Zone': 'Draw box on the lower body', 'Base Material': 'Wasp Signal'}, 'Yellow and black chevron plates.', 'cat_signal')],
        [D('Gloss, not matte', 'Fluorescent colours look strongest with gloss.'), D('Not a finish', 'There is no separate high-vis finish; plain Gloss with a bright solid colour is right.')],
        [Q('How do I make high-vis?', 'Lime or orange gloss with black bands.'), Q('Reflective?', 'Retroreflective spec overlay.'), Q('Readable on TV?', 'Yes, it is among the most readable.')],
        [M('Colour looks dull', 'Matte base', 'Use Gloss.'), M('Bands hard to see', 'Bands same brightness', 'Use black on lime.')],
        ['Black number on lime is the highest contrast pair.'],
        ['high vis', 'high visibility', 'hi vis', 'safety yellow', 'safety orange', 'safety colours', 'reflective stripes', 'construction look', 'roadwork look', 'neon yellow look', 'lime look', 'fluorescent look', 'visible from far'],
        fin=['base::gloss', 'base::tac_blaze_orange', 'base::wasp_warning'], spc=['spec_retroreflective'],
        related=['ideas.police_emergency', 'ideas.readable_on_tv', 'ideas.stand_out_in_pack'], combos=[('ideas.readable_on_tv', 'Same goal.')],
        screens=['cat_signal'], extra_src=[READ])

if todo('carbon_race_bare'):
    art('carbon_race_bare', 'Carbon and race-bare: exposed weave, clear coat and matte black',
        'Carbon looks come from a weave pattern plus a spec that catches light along the fibres. Use a Carbon finish for full body, or carbon on splitter, roof and mirrors only.',
        'Bare carbon says "built for speed, not paint". Use it on the roof, hood and trim, keep the rest in a solid colour, and leave the weave large enough to read at a distance.',
        'intermediate',
        [S_ZONE, 'Choose a gloss or matte body in your colour.',
         'Trim zones: ' + S_BOX + ' Roof, hood and mirrors. Open Base Material and search Carbon Twill Weave, or use PATTERN Carbon Fiber, Paint mode Blend, Scale (pattern) 0.5.',
         'Add fibre glint: BASE > SPEC OVERLAYS > + ADD SPEC OVERLAY, choose Carbon Weave (Spec), Strength 70.',
         S_RENDER],
        [X('Carbon roof and hood', 'Race trim', {'Body': 'Gloss, #c8102e', 'Trim zone': 'Draw box on roof and hood, PATTERN Carbon Fiber, Blend, 0.5', 'SPEC OVERLAY': 'Carbon Weave (Spec) 70'}, 'A red car with carbon on top.', 'spec_carbon'),
         X('Full carbon', 'Race-bare', {'Base Material': 'Carbon Twill Weave', 'BASE COLOR': "Use finish's own color"}, 'A true 2x2 twill carbon with a diagonal rib.', 'spec_carbon'),
         X('Kevlar accent', 'Yellow weave', {'Base Material': 'Kevlar Aramid Weave', 'Zone': 'Lower body'}, 'A golden woven aramid look.', 'spec_carbon')],
        [D('Weave scale', 'Scale (pattern) 0.5 reads as weave from a distance; smaller looks like grey noise.'), D('Spec carries it', 'The fibre glint comes from the spec overlay, so the colour stays dark.')],
        [Q('How do I make carbon fibre?', 'Carbon pattern plus spec overlay.'), Q('Where?', 'Roof, hood, mirrors.'), Q('All over?', 'Full body works but can look flat.')],
        [M('Looks like a grey blur', 'Weave too fine', 'Scale 0.5 or larger.'), M('No glint', 'No spec overlay', 'Add the Carbon Weave (Spec) overlay.')],
        ['Twill (2x2) is more readable than plain weave at distance.'],
        ['carbon fibre', 'carbon fiber', 'carbon look', 'carbon race', 'race bare', 'bare carbon', 'raw carbon', 'carbon hood', 'carbon roof', 'kevlar look', 'forged carbon look', 'exposed weave', 'weave look'],
        fin=['monolithic::materials2_carbon', 'monolithic::materials2_kevlar', 'base::gloss'], pat=['carbon_fiber', 'hex_carbon'], spc=['spec_carbon_weave', 'spec_kevlar_weave'],
        related=['ideas.hex_tech', 'ideas.le_mans_endurance', 'ideas.aggressive_mean'], combos=[('ideas.le_mans_endurance', 'Carbon trim on a clean body.')],
        screens=['spec_carbon'], quick=True, extra_src=[THEMES])

if todo('two_tone'):
    art('two_tone', 'Two-tone: one split, two colours, a clean line',
        'A two-tone car is two colours divided by a clean line: top and bottom, hood and body, or front and rear. Use two zones and a thin separator pinline.',
        'Two-tone is the easiest style that looks designed. The rule is a clear dominant colour (about two thirds), a contrasting second colour, and a thin line between them to hide the join.',
        'beginner',
        [S_ZONE, S_BASE % 'Gloss (metal 0, roughness 30, coat 16)' + ' with Use solid color for the main colour.',
         'Add the second colour: ' + S_BOX + ' Draw the lower third, or the roof, in the second colour.',
         'Add a separator: a very thin box on the join in white, gold or black.',
         S_RENDER],
        [X('Cream over teal', 'Classic wagon', {'Body': 'Gloss, #e8dfc4', 'Lower zone': 'Gloss, #1f7a73', 'Pinline': 'Gloss, #f4f4f4, thin box'}, 'A soft two-tone with a clean join.', 'cat_sock_hop'),
         X('Black roof', 'Modern', {'Body': 'Gloss, #c8102e', 'Roof zone': 'Gloss, #0b0b0e'}, 'Red body with a gloss-black roof.', 'cat_color_clash'),
         X('Matte over gloss', 'Spec contrast', {'Body': 'Gloss, #1f4fa8', 'Hood zone': 'Matte, #1f4fa8'}, 'Same colour, different shine.', 'spec_matte')],
        [D('Proportion', 'About two thirds main to one third second.'), D('Matte over gloss', 'Same colour in two finishes is a subtle two-tone.')],
        [Q('How do I do two-tone?', 'Two zones and a pinline.'), Q('Where to split?', 'Beltline, roof, or hood.'), Q('Same colour?', 'Matte on gloss.')],
        [M('Messy join', 'No separator', 'Add a thin pinline.'), M('50/50 looks dull', 'Equal halves', 'Make it two thirds to one third.')],
        ['A white pinline lifts almost any pair.'],
        ['two tone', 'two tone paint', 'two colour car', 'duo tone', 'split colour', 'black roof', 'two toned', 'bicolor', 'colour block', 'top and bottom colours'],
        fin=['base::gloss', 'base::matte'], pat=['pinstripe'],
        related=['ideas.fade_gradient', 'ideas.touring_car', 'ideas.clean_classy'], combos=[('ideas.clean_classy', 'Restraint.')],
        screens=['cat_color_clash', 'spec_matte'], extra_src=[FAM])

if todo('fade_gradient'):
    art('fade_gradient', 'Fade and gradient: one colour melting into another',
        'A fade is one colour melting into another along the body. Use Custom gradient in BASE COLOR, or a ready-made gradient finish like Black Gold, Arctic Dawn or Amber Night.',
        'Fades look rich but break if the gradient crosses panel seams. Use a separate zone per panel, set the start and end colours close in value, and choose a direction (front to back, or bottom to top).',
        'intermediate',
        [S_ZONE, S_BASE % 'Gloss (metal 0, roughness 30, coat 16)',
         'Set BASE COLOR to Custom gradient, pick the start colour (for example #1b0f3a) and the end colour (#ff2bd6), and choose the angle.',
         'Repeat for each panel (side, hood, roof) in its own zone so the fade matches on each.',
         S_RENDER],
        [X('Purple to pink', 'Sunset fade', {'Zone per panel': 'Custom gradient #1b0f3a to #ff2bd6', 'Angle': 'bottom to top'}, 'A smooth dusk fade.', 'cat_gradients'),
         X('Black gold', 'Ready-made', {'Base Material': 'Black Gold', 'BASE COLOR': "Use finish's own color"}, 'Black melting to warm gold.', 'cat_gradients'),
         X('Arctic Dawn', 'Cool fade', {'Base Material': 'Arctic Dawn'}, 'Pale blue to white.', 'cat_gradients')],
        [D('Per-panel zones', 'A gradient across the sheet does not line up across panels; per-panel zones fix it.'), D('Close values', 'Pick two colours of similar brightness for a smooth fade.')],
        [Q('How do I do a fade?', 'Custom gradient per panel.'), Q('Ready-made?', 'Black Gold, Arctic Dawn, Amber Night.'), Q('Which direction?', 'Bottom to top is classic.')],
        [M('Fade jumps at the door', 'One sheet-wide gradient', 'One zone per panel.'), M('Muddy middle', 'Complementary colours', 'Pick neighbours on the colour wheel.')],
        ['Add a gloss clear Spec overlay (Fresnel Gradient) for a depth fade.'],
        ['fade', 'fade paint', 'gradient paint', 'gradient look', 'colour fade', 'ombre', 'ombre look', 'sunset fade', 'melting colours', 'blend colours', 'fade from black', 'candy fade', 'colour blend'],
        fin=['base::gloss', 'monolithic::grad_black_gold', 'monolithic::grad_arctic_dawn', 'monolithic::grad_amber_night'], spc=['spec_fresnel_gradient'],
        related=['ideas.two_tone', 'ideas.colour_shift', 'ideas.cyberpunk_synthwave'], combos=[('ideas.two_tone', 'The hard version.')],
        screens=['cat_gradients', 'pair_zone_added'], quick=True, extra_src=[THEMES])

if todo('camo_woodland_desert'):
    art('camo_woodland_desert', 'Woodland and desert camo: earth-tone blotches',
        'Woodland and desert camo are four earth colours in organic blotches. Use M81 Woodland, Multicam, Flecktarn or Desert DPM in the catalogue, then keep numbers on a plain area.',
        'Camo hides shapes, which is the opposite of readability. Use it on the lower body or roof, keep the number panel plain, and choose one family so the pattern reads as camouflage.',
        'beginner',
        [S_ZONE, S_BASE % 'Matte (metal 0, roughness 200, coat 160)' + ' with an earth colour (#4b5a3a, #b39b72).',
         'Add camo: ' + S_BOX + ' Body panels, Base Material M81 Woodland, Flecktarn, Multicam Transition or Desert DPM.',
         'Leave BASE COLOR on Use finish\'s own color.',
         'Reduce Base Scale if the blotches look huge. ' + S_RENDER],
        [X('M81 Woodland', 'Classic', {'Base Material': 'Camo: M81 Woodland', 'Check': 'about metal 6, roughness 138, coat 121'}, 'Green, brown and black blotches.', 'cat_tactical_field'),
         X('Desert DPM', 'Sand', {'Base Material': 'Camo: Desert DPM'}, 'Two-colour disruptive sand pattern.', 'cat_tactical_field'),
         X('Flecktarn', 'Spots', {'Base Material': 'Camo: Flecktarn', 'Base Scale': '0.8'}, 'Dense spots that dither into each other.', 'cat_tactical_field')],
        [D('Scale', 'Base Scale 0.6 to 0.8 keeps blotches car-sized instead of poster-sized.'), D('Number panel', 'Draw a plain box on the door and put the number there.')],
        [Q('How do I do camo?', 'Pick a Camo finish and scale it down.'), Q('Which?', 'M81, Multicam, Flecktarn, Desert DPM.'), Q('Gloss?', 'No, matte.')],
        [M('Blotches too big', 'Scale 1.0', 'Lower Base Scale.'), M('Number lost', 'Camo under number', 'Plain box over the door.')],
        ['Tiger Stripe and Bark Camo are the other families.'],
        ['camo', 'camo look', 'camouflage', 'woodland camo', 'desert camo', 'army camo', 'hunting camo', 'green camo', 'sand camo', 'multicam', 'camo paint', 'camo car', 'jungle camo'],
        fin=['base::matte', 'base::tac_m81_woodland', 'base::tac_multicam_transition', 'base::tac_flecktarn', 'base::tac_desert_dpm', 'base::tac_tiger_stripe'], pat=['camo'],
        related=['ideas.camo_digital_urban', 'ideas.camo_ghost_blackout', 'ideas.military_tactical'], combos=[('ideas.military_tactical', 'Flat trim.')],
        screens=['cat_tactical_field'], quick=True, extra_src=[THEMES])

if todo('camo_digital_urban'):
    art('camo_digital_urban', 'Digital and urban camo: pixels, greys and snow',
        'Digital camo is square-pixel patterns at two scales; urban and snow camo use greys and whites. Use MARPAT Digital, Urban Grey Digital or Snow Overwhite.',
        'Modern camo uses pixels for close and far break-up, and city or winter camo drops the greens. These suit tech, stealth and winter looks.',
        'beginner',
        [S_ZONE, S_BASE % 'Matte (metal 0, roughness 200, coat 160)',
         'Pick Base Material Camo: MARPAT Digital, Camo: Urban Grey Digital or Camo: Snow Overwhite, BASE COLOR on Use finish\'s own color.',
         'Set Base Scale 0.7 so the pixels are fine enough to read.',
         S_RENDER],
        [X('MARPAT', 'Digital', {'Base Material': 'Camo: MARPAT Digital'}, 'Pixels at two scales.', 'cat_tactical_field'),
         X('Urban grey', 'City', {'Base Material': 'Camo: Urban Grey Digital'}, 'A mixed grey pixel pattern.', 'cat_tactical_field'),
         X('Winter', 'Snow', {'Base Material': 'Camo: Snow Overwhite'}, 'White with grey tears.', 'cat_tactical_field')],
        [D('Digital scale', 'Pixels too big look like a game texture; 0.7 is a good start.'), D('Urban', 'Greys are very forgiving next to numbers.')],
        [Q('How do I do digital camo?', 'MARPAT Digital at Base Scale 0.7.'), Q('Urban?', 'Urban Grey Digital.'), Q('Winter?', 'Snow Overwhite.')],
        [M('Pixels too big', 'Scale 1.0', 'Lower it.'), M('Flat look', 'Single zone', 'Add a darker second zone.')],
        ['Ghost Camo hides the pattern in clearcoat only.'],
        ['digital camo', 'urban camo', 'snow camo', 'winter camo', 'grey camo', 'pixel camo', 'city camo', 'marpat', 'arctic camo', 'pixelated camo'],
        fin=['base::matte', 'base::tac_marpat_digital', 'base::tac_urban_grey_digital', 'base::tac_snow_overwhite'],
        related=['ideas.camo_woodland_desert', 'ideas.camo_ghost_blackout', 'ideas.fighter_jet'], combos=[('ideas.camo_ghost_blackout', 'Subtle camo.')],
        screens=['cat_tactical_field'], extra_src=[THEMES])

if todo('camo_ghost_blackout'):
    art('camo_ghost_blackout', 'Ghost and blackout camo: hidden pattern in the shine',
        'Ghost camo is a black car whose camo pattern appears only in reflections. Use Ghost Camo (clearcoat-only pattern) or Tigerstripe Night for a dark, subtle result.',
        'When you want camo without colour, the pattern lives in the spec. The paint stays black, the shine changes in blotches, and the effect shows in sun and at angles.',
        'intermediate',
        [S_ZONE, S_BASE % 'Flat Black (metal 0, roughness 250, coat 255)' + ' with Use solid color #0b0b0e.',
         'Add the ghost: ' + S_BOX + ' Whole body, Base Material Ghost Camo, Base Strength 100, BASE COLOR on Use source paint (spec only).',
         'Or try Tigerstripe Night for a visible dark camo.',
         S_RENDER],
        [X('Ghost camo', 'Hidden pattern', {'Body': 'Flat Black', 'Base Material': 'Ghost Camo', 'BASE COLOR': 'Use source paint (spec only)', 'Check': 'about metal 224, roughness 80, coat 151'}, 'A black car with a camo that only shows in light.', 'spec_astra'),
         X('Tigerstripe Night', 'Dark camo', {'Base Material': 'Camo: Tigerstripe Night'}, 'Dark stripes on near-black.', 'cat_tactical_field')],
        [D('Judge in the sim', 'Ghost patterns are hard to see in the preview; check in the sim.'), D('Source paint', 'Use source paint keeps your colour and changes only the shine.')],
        [Q('How do I do ghost camo?', 'Ghost Camo with source paint.'), Q('Will it show?', 'In sun and angles.'), Q('Visible dark camo?', 'Tigerstripe Night.')],
        [M('Cannot see it', 'Preview too flat', 'Judge in the sim.'), M('Car turns metallic', 'Used own colour', 'Use source paint.')],
        ['Pair with Flat Black or Matte for the stealth look.'],
        ['ghost camo', 'blackout camo', 'hidden camo', 'subtle camo', 'black camo', 'dark camo', 'stealth camo', 'tonal camo', 'night camo', 'invisible pattern'],
        fin=['base::flat_black', 'monolithic::ghost_camo', 'base::tac_tigerstripe_night'],
        related=['ideas.camo_woodland_desert', 'ideas.stealth_murdered_out', 'ideas.fighter_jet'], combos=[('ideas.stealth_murdered_out', 'Same family.')],
        screens=['spec_astra', 'cat_tactical_field'], extra_src=[THEMES])
