#!/usr/bin/env python
"""ideas batch 06 (2026-10-05): flames, tribal, geometry, hex, marble, holographic, colour shift, pastel, mono, flake, pearl, liquid metal."""
from enc_ideas_build import *

X = lambda t, g, s, r, screen=None: dict(title=t, goal=g, settings=s, result=r, **({'screen': screen} if screen else {}))
D = lambda h, b: dict(heading=h, body=b)
Q = lambda q, a: dict(q=q, a=a)
M = lambda s, c, f: dict(symptom=s, cause=c, fix=f)
FAM = doc(DOC_LIVERY, 'Classic scheme families')
THEMES = doc(DOC_DESIGN, 'Themes -> where to look')

if todo('flames'):
    art('flames', 'Flames: hot rod, tribal, ghost and true fire',
        'Flames are one of the oldest custom looks. Pick a Flame finish (Hot Rod, True Fire, Ghost, Tribal, Inferno) and put it on the hood and front fenders, running front to back.',
        'Flames work when they sweep from the front toward the rear on a dark or bright body, with a light-to-dark core. The catalogue has a whole Flames shelf with many colours, so you rarely need to draw one.',
        'beginner',
        [S_ZONE, S_BASE % 'Gloss (metal 0, roughness 30, coat 16)' + ' with Use solid color #0b0b0e (black) or a strong colour.',
         'Add the flames: ' + S_BOX + ' Cover the hood and the front half of each side.',
         'Set Base Material to Hot Rod Flames, True Fire, Ghost Flames or Tribal Flame, BASE COLOR on Use finish\'s own color.',
         'Keep Base Scale near 1.0; lower it for smaller licks. ' + S_RENDER],
        [X('Classic hot rod flames', 'Retro custom', {'Body': 'Gloss, #0b0b0e', 'Flame zone': 'Draw box, Hot Rod Flames', 'Base Strength': '100'}, 'Orange-yellow licks on black.', 'cat_flames'),
         X('Ghost flames', 'Subtle', {'Body': 'Gloss, #1a1c20', 'Flame zone': 'Ghost Flames, Base Strength 50'}, 'Flames that only half show in the dark paint.', 'cat_flames'),
         X('Blue flames', 'Cool look', {'Flame zone': 'Blue Flame or Plasma Fire', 'Body': 'Gloss, #f4f4f4'}, 'Blue fire on white.', 'cat_flames')],
        [D('Direction', 'Flames flow back from the grille, so cover the front and fade out toward the doors.'), D('Dark body', 'Fire colours pop most on black or deep blue.')],
        [Q('How do I add flames?', 'Draw a box on the front and pick a Flame finish.'), Q('Which colours?', 'Hot Rod, True Fire, Blue Flame, Purple Flame, Green Fire.'), Q('Subtle?', 'Ghost Flames.')],
        [M('Flames cover the whole car', 'Box too big', 'Draw the box on the front half.'), M('Flames lost', 'Same colour body', 'Use a dark or contrasting body.')],
        ['Candy Flame on a candy body gives the classic custom look.'],
        ['flames', 'flame look', 'flames on hood', 'flame paint', 'hot rod flames', 'real fire', 'fire look', 'ghost flames', 'blue flames', 'flame job', 'add flames', 'on fire look'],
        fin=['base::gloss', 'base::flame_hotrod', 'base::flame_true_fire', 'base::flame_ghost', 'base::flame_tribal', 'base::flame_blue', 'base::flame_inferno'],
        related=['ideas.hot_rod_kustom', 'ideas.aggressive_mean', 'ideas.tribal'], combos=[('ideas.hot_rod_kustom', 'Flames are its signature.')],
        screens=['cat_flames', 'cat_fractured_flames'], quick=True, extra_src=[THEMES])

if todo('tribal'):
    art('tribal', 'Tribal: sharp swirls, spikes and tattoo-style shapes',
        'Tribal graphics are bold black swirls and spikes. Use Tribal Flame or the Tribal Tattoo, Celtic Spiral and Norse Runes patterns on the hood and sides.',
        'Tribal was big in the 90s and 2000s: thick black shapes, sharp points and mirrored swooshes. Use it as a bold single-colour graphic over a bright body.',
        'beginner',
        [S_ZONE, S_BASE % 'Gloss (metal 0, roughness 30, coat 16)' + ' with a bright colour, #e8631a or #00a3ff.',
         'Add tribal: ' + S_BOX + ' Hood and rear quarters, open PATTERN and choose Tribal Tattoo, Celtic Spiral or Norse Runes.',
         'Set Paint mode to Overlay and Scale (pattern) to 0.8; pick the pattern colour in black.',
         S_RENDER],
        [X('Black tribal on orange', '90s custom', {'Body': 'Gloss, #e8631a', 'PATTERN': 'Tribal Tattoo, Overlay, Scale (pattern) 0.8'}, 'Thick black swirls.', 'cat_flames'),
         X('Celtic knot', 'Spirals', {'PATTERN': 'Celtic Spiral, Blend, Scale (pattern) 0.6'}, 'Fine knotwork over a base colour.', 'cat_foundation'),
         X('Tribal fire', 'Hybrid', {'Base Material': 'Tribal Flame'}, 'Sharp flame-shaped tribal swirls.', 'cat_flames')],
        [D('One colour graphic', 'Keep the tribal in a single dark colour on a bright body.'), D('Symmetry', 'Mirror shapes left to right.')],
        [Q('How do I make tribal?', 'Tribal Tattoo pattern in black on a bright body.'), Q('Celtic?', 'Celtic Spiral or Norse Runes.'), Q('Fire?', 'Tribal Flame.')],
        [M('Looks like wallpaper', 'Scale too small', 'Raise Scale (pattern).'), M('Hard to see', 'Dark on dark', 'Use a bright body.')],
        ['Add a thin white outline for sticker contrast.'],
        ['tribal', 'tribal look', 'tribal graphics', 'tribal tattoo', 'tattoo look', 'celtic look', 'norse look', 'viking look', 'swirl graphics', 'tribal flames', 'spiky graphics'],
        fin=['base::gloss', 'base::flame_tribal'], pat=['decade_90s_tribal_tattoo', 'tribal_celtic_spiral', 'tribal_norse_runes'],
        related=['ideas.flames', 'ideas.retro_90s', 'ideas.aggressive_mean'], combos=[('ideas.retro_90s', 'Era look.')],
        screens=['cat_flames', 'cat_foundation'], extra_src=[THEMES])

if todo('geometric'):
    art('geometric', 'Geometric: triangles, chevrons, diamonds and grids',
        'Geometric designs are flat shapes in two or three colours: chevrons, argyle, houndstooth, triangles. Use a pattern at moderate Scale on a solid base.',
        'Hard-edged shapes read fast and photograph well. Choose one pattern, two colours and a clean base; use scale so the shapes are the size of a hand on a real car.',
        'beginner',
        [S_ZONE, S_BASE % 'Gloss (metal 0, roughness 30, coat 16)' + ' with a base colour.',
         'Open PATTERN and choose Chevron, Art Deco Chevron, Argyle, Houndstooth, Sierpinski Triangle or Star Tile Mosaic.',
         'Set Paint mode to Blend and Scale (pattern) to 0.8.',
         'Limit it with Draw box to the lower body or one side. ' + S_RENDER],
        [X('Chevron arrows', 'Forward motion', {'Body': 'Gloss, #0b0b0e', 'PATTERN': 'Chevron Stack, Blend, 0.8'}, 'Arrows pointing forward.', 'cat_signal'),
         X('Argyle', 'Preppy', {'Body': 'Gloss, #1f4fa8', 'PATTERN': 'Argyle, Blend, 0.8'}, 'A diamond pattern.', 'cat_foundation'),
         X('Triangle fractal', 'Math', {'PATTERN': 'Sierpinski Triangle, Blend, 0.6'}, 'Nested triangles.', 'cat_paradigm')],
        [D('Two colours', 'Two colours and a neutral are enough.'), D('Scale', 'Keep shapes large enough to read at 50 metres.')],
        [Q('How do I do geometric?', 'A pattern at Scale 0.8 on a solid base.'), Q('Which patterns?', 'Chevron, Argyle, Houndstooth.'), Q('Gloss?', 'Yes.')],
        [M('Busy', 'Pattern covers everything', 'Limit to the lower body.'), M('Tiny shapes', 'Low scale', 'Raise Scale (pattern).')],
        ['Combine one geometric pattern with plain panels for balance.'],
        ['geometric', 'geometric look', 'geometric pattern', 'shapes look', 'triangles', 'diamonds', 'chevrons', 'houndstooth', 'argyle', 'abstract shapes', 'modern pattern', 'angular design'],
        fin=['base::gloss'], pat=['chevron_stack', 'art_deco_chevron', 'argyle', 'houndstooth', 'geo_fractal_triangle', 'star_tile_mosaic'],
        related=['ideas.hex_tech', 'ideas.two_tone', 'ideas.clean_classy'], combos=[('ideas.hex_tech', 'Hex is a geometry.')],
        screens=['cat_signal', 'cat_foundation'], extra_src=[THEMES])

if todo('hex_tech'):
    art('hex_tech', 'Hex and tech: honeycomb, circuits and carbon',
        'Tech looks are hexagon honeycombs and circuit traces. Use Hex Mesh, Hex Carbon, Hex Circuit or Graphene Hex patterns, with the Hex Cells spec overlay for shine.',
        'Hex patterns say engineering. They look best on dark bodies in a single bright accent colour, with the cell structure also in the shine so it glints at angles.',
        'intermediate',
        [S_ZONE, S_BASE % 'Satin (metal 0, roughness 95, coat 70)' + ' with Use solid color #0d1117.',
         'Open PATTERN and choose Hex Mesh, Hex Circuit or Graphene Hex, Paint mode Blend, Scale (pattern) 0.6.',
         'Add glint: BASE > SPEC OVERLAYS > + ADD SPEC OVERLAY, choose Hex Cells, Strength 50.',
         S_RENDER],
        [X('Hex mesh on black', 'Tech', {'Body': 'Satin, #0d1117', 'PATTERN': 'Hex Mesh, Blend, 0.6', 'SPEC OVERLAY': 'Hex Cells 50'}, 'A dark car with honeycomb glints.', 'spec_ghost_hex'),
         X('Circuit cyan', 'Electronics', {'PATTERN': 'Hex Circuit, Overlay, 0.6', 'Colour': '#00e5ff'}, 'Cyan circuit traces on hex cells.', 'cat_cyberpunk')],
        [D('Pattern plus spec', 'The pattern gives colour; Hex Cells gives glint. Use both.'), D('Dark ground', 'Bright hex on dark reads clearly.')],
        [Q('How do I do hex?', 'Hex Mesh pattern plus Hex Cells spec.'), Q('Circuits?', 'Hex Circuit.'), Q('Carbon hex?', 'Hex Carbon.')],
        [M('Looks grey', 'No accent colour', 'Colour the pattern.'), M('Cells too small', 'Low scale', 'Raise to 0.6.')],
        ['Keep hex to the lower half so the upper body stays clean.'],
        ['hex', 'hex look', 'hexagon', 'honeycomb', 'honeycomb look', 'tech look', 'techy look', 'circuit look', 'circuit board look', 'sci fi look', 'futuristic look', 'graphene look'],
        fin=['base::satin'], pat=['hex_mesh', 'hex_circuit', 'graphene_hex', 'hex_carbon'], spc=['hex_cells'],
        related=['ideas.geometric', 'ideas.carbon_race_bare', 'ideas.cyberpunk_synthwave'], combos=[('ideas.carbon_race_bare', 'Hex carbon trim.')],
        screens=['spec_ghost_hex', 'cat_cyberpunk'], extra_src=[THEMES])

if todo('marble_stone'):
    art('marble_stone', 'Marble and stone: veined, polished and natural',
        'Marble and stone looks come from ready-made stone finishes (Marble, Banded Agate, Ebru Marble, Moonstone) or the Marble Veining pattern. They suit clean, premium builds.',
        'Stone finishes give a veined, slightly translucent depth. Use them over the whole body for a showpiece, or in a zone for a hood or roof panel.',
        'beginner',
        [S_ZONE, 'Under BASE press Base Material and search for Marble, Banded Agate or Moonstone Adular.',
         'Leave BASE COLOR on Use finish\'s own color, or use Hue Shift to move it toward white, black or green.',
         'Or use PATTERN Marble Veining on a solid white or black body, Paint mode Blend, Scale (pattern) 0.8.',
         S_RENDER],
        [X('Marble', 'Showpiece', {'Base Material': 'Marble', 'Base Scale': '1.0'}, 'Dense turbulent veining in amber tones.', 'cat_fractured_cosmos'),
         X('Black marble', 'Luxe', {'Body': 'Gloss, #0b0b0e', 'PATTERN': 'Marble Veining, Blend, 0.8'}, 'Pale veins across a black body.', 'cat_materials_physics'),
         X('Moonstone', 'Subtle glow', {'Base Material': 'Moonstone Adular'}, 'A floating blue-white glow over fine silver.', 'cat_glass_surface')],
        [D('Hue shift', 'Hue Shift can change a finish\'s colour while keeping its structure.'), D('Scale', 'Lower Base Scale for finer veins and raise it for bold, wide veins.')],
        [Q('How do I do marble?', 'Marble finish or Marble Veining pattern.'), Q('White marble?', 'White gloss with Marble Veining.'), Q('Granite?', 'Search Troll Granite.')],
        [M('Looks like noise', 'Scale too small', 'Raise the scale.'), M('Colour wrong', 'Own palette', 'Use Hue Shift.')],
        ['A thin gold pinline makes marble look expensive.'],
        ['marble', 'marble look', 'marble paint', 'stone look', 'granite look', 'agate', 'veined look', 'natural stone', 'polished stone', 'onyx look', 'rock look', 'moonstone'],
        fin=['monolithic::ff_marble', 'monolithic::ff_banded_agate', 'monolithic::fmo_moonstone_adular', 'monolithic::fm_ebru_marble', 'monolithic::mo_marble_current', 'base::gloss'], pat=['marble_veining'],
        related=['ideas.look_expensive', 'ideas.glass_crystal', 'ideas.pearl_white'], combos=[('ideas.look_expensive', 'Stone reads premium.')],
        screens=['cat_fractured_cosmos', 'cat_materials_physics'], extra_src=[THEMES])

if todo('holographic_iridescent'):
    art('holographic_iridescent', 'Holographic and iridescent: rainbow shine that moves',
        'Holographic and iridescent looks shift colour as the light moves. Use Holo Flake, Holographic Drift or Chameleon finishes, or the Holo Prism Shift spec overlay on your own colour.',
        'Two routes: choose a holographic finish that brings its own colours, or keep your paint and add a holographic spec overlay so only the shine moves. Both look best on dark bodies.',
        'intermediate',
        [S_ZONE, 'Dark route: BASE Base Material Holo Flake or Holographic Drift, BASE COLOR on Use finish\'s own color.',
         'Keep-my-paint route: BASE COLOR on Use source paint (spec only), then open BASE > SPEC OVERLAYS > + ADD SPEC OVERLAY and choose Holo Prism Shift or Iridescent Film, Strength 60.',
         'Optional pattern: PATTERN Holographic or Iridescent Fog Overlay, Blend, Scale (pattern) 0.8.',
         S_RENDER],
        [X('Holo flake', 'Full rainbow', {'Base Material': 'Holo Flake', 'Check': 'about metal 204, roughness 12, coat 26'}, 'A mirror finish with rainbow flake.', 'cat_prizm'),
         X('Keep my paint', 'Spec-only', {'BASE COLOR': 'Use source paint (spec only)', 'SPEC OVERLAY': 'Holo Prism Shift 60'}, 'Your colour with a rainbow glint.', 'cat_light_optics'),
         X('Iridescent film', 'Soap bubble', {'SPEC OVERLAY': 'Iridescent Film 50', 'Body': 'Gloss, #0b0b0e'}, 'A thin-film rainbow over black.', 'cat_iridescent_insects')],
        [D('Dark bodies', 'Rainbow shows best over black or deep blue.'), D('Judge in sim', 'Shift effects look flatter in the preview than in the sim.')],
        [Q('How do I do holographic?', 'Holo Flake or the Holo Prism Shift overlay.'), Q('Keep my colours?', 'Use source paint plus overlay.'), Q('Iridescent?', 'Iridescent Film.')],
        [M('No rainbow', 'Pale body', 'Use a dark body.'), M('Looks noisy', 'Overlay too strong', 'Lower Strength to 40.')],
        ['Chameleon Flake is a spec version of colour-shift flake.'],
        ['holographic', 'holo look', 'holographic look', 'iridescent', 'iridescent look', 'rainbow shine', 'oil slick look', 'oil slick', 'soap bubble look', 'prism look', 'hologram', 'rainbow flake'],
        fin=['base::efx_holo_flake', 'base::efx_holographic_drift', 'base::gloss'], pat=['holographic', 'iridescent_fog'], spc=['holo_prism_shift', 'spec_iridescent_film', 'spec_chameleon_flake'],
        related=['ideas.colour_shift', 'ideas.metal_flake_sparkle', 'ideas.make_it_pop'], combos=[('ideas.colour_shift', 'Chameleon route.')],
        screens=['cat_prizm', 'cat_light_optics'], quick=True, extra_src=[THEMES])

if todo('colour_shift'):
    art('colour_shift', 'Colour shift: chameleon paint that changes with the angle',
        'Colour-shift paint changes hue as you move around it. Use a Chameleon finish (Amethyst, Fire, Galaxy, Ocean, Phoenix) for a ready-made shift.',
        'Chameleon finishes bring a two- or three-colour shift: for example purple to blue to white, or green to gold. They look best on smooth body panels and on a dark base.',
        'beginner',
        [S_ZONE, 'Under BASE press Base Material and search Chameleon, then choose Amethyst, Fire, Galaxy, Ocean, Phoenix or Neon.',
         'Leave BASE COLOR on Use finish\'s own color.',
         'Set Color Flip if the shift looks too flat; try values 0 to 100.',
         S_RENDER],
        [X('Galaxy shift', 'Purple to blue', {'Base Material': 'Chameleon Galaxy'}, 'Deep purple, blue and star-white.', 'cat_spectrum_shift'),
         X('Neon shift', 'Sign glow', {'Base Material': 'Chameleon Neon'}, 'Green, yellow and pink.', 'cat_spectrum_shift'),
         X('Fire shift', 'Warm', {'Base Material': 'Chameleon Fire'}, 'Orange to red.', 'cat_spectrum_shift')],
        [D('Angle', 'The shift is angle-based, so the same panel looks different from the front and side.'), D('Dark base', 'Keep the body dark.')],
        [Q('How do I make chameleon paint?', 'A Chameleon finish.'), Q('Which?', 'Galaxy, Ocean, Phoenix, Amethyst.'), Q('Black-gold?', 'Cs Black Gold.')],
        [M('Looks flat', 'No contrast', 'Try Color Flip.'), M('Looks muddy', 'Light body', 'Dark base.')],
        ['Colour Shift shelves hold many other two-tone shifts.'],
        ['colour shift', 'color shift', 'chameleon paint', 'chameleon look', 'changes colour', 'color changing', 'flip paint', 'color flip', 'two colour flip', 'duochrome', 'angle shift'],
        fin=['monolithic::chameleon_galaxy', 'monolithic::chameleon_neon', 'monolithic::chameleon_fire', 'monolithic::chameleon_ocean', 'monolithic::chameleon_amethyst'],
        related=['ideas.holographic_iridescent', 'ideas.fade_gradient', 'ideas.make_it_pop'], combos=[('ideas.holographic_iridescent', 'The rainbow route.')],
        screens=['cat_spectrum_shift', 'cat_prizm'], extra_src=[THEMES])

if todo('pastel'):
    art('pastel', 'Pastel: soft mint, peach, baby blue and pink',
        'Pastel cars use soft, light colours with a gentle satin finish. Use Gloss or Satin with a pastel solid colour, or the Miami Pastel and Pastel Argyle finishes.',
        'Pastels look fresh and retro-modern. Keep the colours pale, add one deeper accent for contrast, and prefer satin to gloss for a soft feel.',
        'beginner',
        [S_ZONE, S_BASE % 'Satin (metal 0, roughness 95, coat 70)' + ' with Use solid color #bfe8d8 (mint) or #f4c6c0 (peach).',
         'Add an accent: ' + S_BOX + ' A stripe or lower panel in a deeper tone, Gloss #2a6f64.',
         'Optional: pick Miami Pastel or Pastel Argyle in Base Material on a box.',
         S_RENDER],
        [X('Mint and cream', 'Soft retro', {'Body': 'Satin, #bfe8d8', 'Accent': 'Gloss, #e8dfc4'}, 'A mint car with a cream band.', 'cat_sock_hop'),
         X('Miami pastel', '80s', {'Base Material': 'Miami Pastel'}, 'Pink and teal grid feel.', 'cat_bad_rad'),
         X('Pastel argyle', 'Preppy', {'Base Material': 'Pastel Argyle'}, 'Matte pastel diamonds.', 'cat_foundation')],
        [D('Accent', 'One deeper accent stops pastel from looking washed out.'), D('Satin', 'Satin reads softer than gloss.')],
        [Q('How do I make pastel?', 'Pale solid colours in satin.'), Q('Readable?', 'Add a dark number.'), Q('Which colours?', 'Mint, peach, baby blue, lilac.')],
        [M('Washed out', 'No accent', 'Add one deeper colour.'), M('Number unreadable', 'Light on light', 'Black number.')],
        ['Pastel plus chrome trim looks retro 50s.'],
        ['pastel', 'pastel look', 'pastel colours', 'soft colours', 'baby blue', 'mint green', 'peach colour', 'lilac', 'cute look', 'candy colours', 'soft and cute', 'light colours'],
        fin=['base::satin', 'base::rad_miami_pastel', 'base::argyle_pastel'],
        related=['ideas.vintage_diner_50s', 'ideas.clean_classy', 'ideas.retro_80s'], combos=[('ideas.vintage_diner_50s', 'Pastel era.')],
        screens=['cat_sock_hop', 'cat_bad_rad'], extra_src=[FAM])

if todo('monochrome'):
    art('monochrome', 'Monochrome: one colour in many finishes',
        'A monochrome car is one hue in different finishes: gloss body, matte hood, satin stripes. The contrast comes from shine, not colour.',
        'Same-colour designs look sophisticated. Use one colour code for every zone and vary the finish, so matte sits beside gloss and metal beside non-metal.',
        'beginner',
        [S_ZONE, S_BASE % 'Gloss (metal 0, roughness 30, coat 16)' + ' with Use solid color #1f4fa8.',
         'Add a second zone: ' + S_BOX + ' Hood or roof in Matte (metal 0, roughness 200, coat 160), same colour.',
         'Add a third: lower body in Metallic (metal 200, roughness 50, coat 16), same colour.',
         S_RENDER],
        [X('Blue on blue', 'Finish contrast', {'Body': 'Gloss, #1f4fa8', 'Hood': 'Matte, #1f4fa8', 'Lower': 'Metallic, #1f4fa8'}, 'One colour, three shines.', 'spec_matte'),
         X('Grey scale', 'Neutral', {'Body': 'Satin, #6b7078', 'Stripe': 'Gloss, #6b7078'}, 'A subtle tonal stripe.', 'cat_foundation')],
        [D('Spec contrast', 'Matte next to gloss, metal next to non-metal.'), D('Same hex', 'Use exactly one colour code.')],
        [Q('How do I do monochrome?', 'One colour, several finishes.'), Q('Not boring?', 'Finish contrast pops.'), Q('Black?', 'See the stealth article.')],
        [M('Looks flat', 'One finish', 'Add matte and gloss.'), M('Slight colour mismatch', 'Different hex', 'Use the same code.')],
        ['Add a thin gloss pinline to separate zones.'],
        ['monochrome', 'monochrome look', 'single colour', 'one colour', 'tonal', 'tonal look', 'all one colour', 'same colour different finish', 'tone on tone', 'subtle stripes'],
        fin=['base::gloss', 'base::matte', 'base::f_metallic'],
        related=['ideas.stealth_murdered_out', 'ideas.make_it_pop', 'ideas.two_tone'], combos=[('ideas.stealth_murdered_out', 'Tonal black.')],
        screens=['spec_matte', 'cat_foundation'], extra_src=[THEMES])

if todo('metal_flake_sparkle'):
    art('metal_flake_sparkle', 'Metal flake and sparkle: glitter in the sun',
        'Metalflake adds glitter that catches the sun. Use Chunky Metalflake, Holo Flake or a flake finish, or add Gold Flake, Holographic Flake or Metallic Sand as a spec overlay.',
        'Flake works best in bright light on deep colours. Chunky flake is the classic 70s custom look; fine micro-flake is modern. The effect is mostly in the shine, so your paint colour stays.',
        'beginner',
        [S_ZONE, 'Choose your base colour (deep red, blue or black work best).',
         'Under BASE choose Base Material Chunky Metalflake or Metalflake Red, or add a spec overlay.',
         'Open BASE > SPEC OVERLAYS > + ADD SPEC OVERLAY, choose Gold Flake, Metallic Sand or Holographic Flake, Strength 50.',
         S_RENDER],
        [X('Chunky flake', '70s custom', {'Base Material': 'Chunky Metalflake', 'BASE COLOR': 'Use solid color #0a3fd0'}, 'Big blue sparkles.', 'cat_bad_rad'),
         X('Gold flake', 'Premium', {'Body': 'Gloss, #0b0b0e', 'SPEC OVERLAY': 'Gold Flake 50'}, 'Black paint with gold sparkle.', 'cat_materials_physics'),
         X('Holo flake', 'Rainbow', {'SPEC OVERLAY': 'Holographic Flake 50'}, 'Rainbow sparkle.', 'cat_prizm')],
        [D('Flake size', 'Chunky flake is visible from far; micro-flake needs close up.'), D('Judge in sim', 'Flake does not show well in the preview.')],
        [Q('How do I do metalflake?', 'Chunky Metalflake or a flake spec overlay.'), Q('Subtle sparkle?', 'Pearl Micro or Stardust Fine.'), Q('Gold?', 'Gold Flake.')],
        [M('No sparkle', 'Preview only', 'Check in the sim.'), M('Looks grainy', 'Too strong', 'Lower Strength.')],
        ['Pink Metalflake and Turquoise Metalflake are ready-made colours.'],
        ['metal flake', 'metalflake', 'sparkle', 'glitter', 'glitter paint', 'sparkly look', 'flake paint', 'bass boat look', 'sparkle in the sun', 'glittery', 'shimmer look'],
        fin=['base::efx_chunky_flake', 'base::efx_holo_flake', 'base::fo_metalflake_red', 'base::pink_fleck', 'base::turquoise_fleck'], spc=['gold_flake', 'metallic_sand', 'holographic_flake', 'pearl_micro', 'stardust_fine'],
        related=['ideas.candy_lowrider', 'ideas.holographic_iridescent', 'ideas.pearl_white'], combos=[('ideas.candy_lowrider', 'Flake under candy.')],
        screens=['cat_bad_rad', 'cat_materials_physics'], extra_src=[THEMES])

if todo('pearl_white'):
    art('pearl_white', 'Pearl white and pearl colours: a soft glow',
        'Pearl is a gentle metallic glow under the colour. Use Pearl (metal 100, roughness 40, coat 16) with a pale colour for a pearl white, or Satin Pearl for a softer one.',
        'Pearl adds depth without the glitter of flake. It suits white, champagne and pale colours, and photographs very clean. Use it as the main body or on the hood only.',
        'beginner',
        [S_ZONE, S_BASE % 'Pearl (metal 100, roughness 40, coat 16)' + ' with Use solid color #f4f1ea.',
         'For a softer look use Satin Pearl (metal 100, roughness 90, coat 60).',
         'Optional: BASE > SPEC OVERLAYS > + ADD SPEC OVERLAY, choose Pearl Micro or Mother of Pearl Inlay, Strength 30.',
         S_RENDER],
        [X('Pearl white', 'Premium', {'Base': 'Pearl, #f4f1ea', 'Check': 'metal 100, roughness 40, coat 16'}, 'A soft white glow.', 'spec_candy'),
         X('Champagne', 'Warm', {'Base': 'Pearl, #e8d8b0'}, 'A pale gold pearl.', 'cat_materials_physics'),
         X('Satin pearl', 'Soft', {'Base': 'Satin Pearl, #f4f1ea'}, 'A calm pearly sheen.', 'spec_matte')],
        [D('Pale colours', 'Pearl is most visible on pale colours.'), D('Judge in sim', 'Pearl shifts with the sun.')],
        [Q('How do I do pearl white?', 'Pearl base with an off-white colour.'), Q('Satin?', 'Satin Pearl.'), Q('Sparkle?', 'Add Pearl Micro.')],
        [M('Looks grey', 'Pure white colour', 'Use a slightly warm off-white.'), M('Too shiny', 'Pearl on matte base', 'Use Satin Pearl.')],
        ['Champagne pearl with black trim is a classic.'],
        ['pearl white', 'pearl paint', 'pearl look', 'pearlescent', 'pearlescent white', 'champagne look', 'soft glow', 'mica', 'tri coat white', 'pearl finish'],
        fin=['base::f_pearl', 'base::f_satin_pearl'], spc=['pearl_micro', 'mother_of_pearl_inlay'],
        related=['ideas.clean_classy', 'ideas.look_expensive', 'ideas.metal_flake_sparkle'], combos=[('ideas.look_expensive', 'Pearl reads premium.')],
        screens=['spec_candy', 'cat_materials_physics'], extra_src=[THEMES])

if todo('liquid_metal'):
    art('liquid_metal', 'Liquid metal: flowing mirror, mercury and PVD',
        'Liquid metal looks like molten silver. Use Mercury, Chrome or the Liquid Metal spec overlay; use PVD Coating for a tinted mirror metal.',
        'Mirror metals show their surroundings, so they look wet and heavy. Use them on a single panel or the whole car, and expect the reflections to be dramatic at low roughness.',
        'intermediate',
        [S_ZONE, 'For full mirror use Base Material Chrome (metal 255, roughness 2, coat 16), colour near white for silver.',
         'For flowing metal add BASE > SPEC OVERLAYS > + ADD SPEC OVERLAY, choose Liquid Metal, Strength 60.',
         'For a tinted metal choose PVD Coating overlay and a colour.',
         S_RENDER],
        [X('Silver mirror', 'Show chrome', {'Base': 'Chrome, #f4f4f4', 'Check': 'metal 255, roughness 2, coat 16'}, 'A full mirror.', 'spec_chrome'),
         X('Liquid metal', 'Flowing', {'Base Material': 'Mercury', 'SPEC OVERLAY': 'Liquid Metal 60'}, 'A silver with flowing ripples.', 'cat_materials_physics'),
         X('Dark chrome', 'Gunmetal', {'Base': 'Dark Chrome, #1a1c20', 'Check': 'metal 250, roughness 15, coat 40'}, 'A dark mirror.', 'spec_chrome')],
        [D('Show car', 'See the chrome article for the full show setup.'), D('Dark chrome', 'Dark Chrome is softer and hides less.')],
        [Q('How do I do liquid metal?', 'Mercury or Liquid Metal overlay.'), Q('Chrome?', 'Chrome base.'), Q('Gunmetal?', 'Dark Chrome.')],
        [M('Looks like grey paint', 'Roughness high', 'Use roughness near 0.'), M('Black patches', 'Reflections', 'Judge in the sim.')],
        ['Satin Chrome is the calm cousin of mirror.'],
        ['liquid metal', 'liquid metal look', 'mercury look', 'molten silver', 'mirror metal', 'melted chrome', 'terminator look', 'pvd look', 'tinted chrome', 'silver liquid', 'metallic flow'],
        fin=['base::f_chrome', 'base::f_dark_chrome', 'base::mercury'], spc=['spec_liquid_metal', 'spec_pvd_coating'],
        related=['ideas.chrome_show_car', 'ideas.look_wet', 'ideas.matte_chrome_accents'], combos=[('ideas.chrome_show_car', 'Show setup.')],
        screens=['spec_chrome', 'cat_materials_physics'], extra_src=[THEMES])
