#!/usr/bin/env python
"""ideas batch 07 (2026-10-05): glass, space, scales, patriotic, Japanese art, surf, heritage green, grunge, team colours, numbers, sponsors, style menu."""
from enc_ideas_build import *

X = lambda t, g, s, r, screen=None: dict(title=t, goal=g, settings=s, result=r, **({'screen': screen} if screen else {}))
D = lambda h, b: dict(heading=h, body=b)
Q = lambda q, a: dict(q=q, a=a)
M = lambda s, c, f: dict(symptom=s, cause=c, fix=f)
FAM = doc(DOC_LIVERY, 'Classic scheme families')
ERA = doc(DOC_LIVERY, 'Where things go on a side panel')
READ = doc(DOC_DESIGN, 'Readability first')
THEMES = doc(DOC_DESIGN, 'Themes -> where to look')
SIXTY = doc(DOC_LIVERY, 'One dominant colour (about 60%)')

if todo('glass_crystal'):
    art('glass_crystal', 'Glass and crystal: ice, shards and sea glass',
        'Glass and crystal looks come from finishes with facets, frost or translucency: Crystal Shards, Cryogenic Bloom, Sea Glass Confessional. Use them on a hood, roof or the whole body.',
        'Crystal looks catch light in many small facets. Use a pale or dark base to let them show, keep the rest of the car calm, and judge the shine in the sim.',
        'beginner',
        [S_ZONE, 'Under BASE press Base Material and search Crystal Shards, Cryogenic Bloom or Sea Glass.',
         'Leave BASE COLOR on Use finish\'s own color.',
         'For frost on your own paint, add BASE > SPEC OVERLAYS > + ADD SPEC OVERLAY, Prismatic Shatter, Strength 40.',
         S_RENDER],
        [X('Crystal shards', 'Faceted', {'Base Material': 'Anime Crystal Shards', 'Check': 'about metal 194, roughness 43, coat 92'}, 'Voronoi crystal shards with prism edges.', 'cat_glass_surface'),
         X('Ice bloom', 'Frozen', {'Base Material': 'Cryogenic Bloom'}, 'Ice dendrites over frosted rime.', 'cat_glass_surface'),
         X('Sea glass', 'Beachy', {'Base Material': 'Sea Glass Confessional'}, 'Frosted pebbles in strong colours.', 'cat_glass_surface')],
        [D('Facets', 'Small facets give sparkle; large facets look like shattered paint.'), D('Calm surroundings', 'Keep the rest of the car simple.')],
        [Q('How do I do crystal?', 'Crystal Shards or Cryogenic Bloom.'), Q('Ice?', 'Cryogenic Bloom.'), Q('Subtle?', 'Prismatic Shatter overlay.')],
        [M('Too busy', 'Over the whole car', 'Limit to one zone.'), M('Looks dull', 'Preview only', 'Check in the sim.')],
        ['Pair crystal with pearl white for a luxury look.'],
        ['glass look', 'crystal look', 'crystal', 'ice look', 'icy look', 'frozen look', 'frosted', 'shattered glass', 'diamond look', 'sea glass', 'translucent look', 'facets'],
        fin=['base::anime_crystal_facet', 'base::astra_cryogenic_bloom', 'base::astra_sea_glass_confessional'], spc=['prismatic_shatter'],
        related=['ideas.marble_stone', 'ideas.pearl_white', 'ideas.holographic_iridescent'], combos=[('ideas.pearl_white', 'Luxe pairing.')],
        screens=['cat_glass_surface', 'cat_light_optics'], extra_src=[THEMES])

if todo('matte_chrome_accents'):
    art('matte_chrome_accents', 'Matte with chrome accents: flat body, bright trim lines',
        'A modern retro look is a flat matte body with thin chrome or satin-chrome lines. The matte hides reflections and the chrome pops by contrast.',
        'This is the classic spec-contrast trick: matte next to mirror. Keep the body matte, add thin chrome pinlines and a chrome roof or mirrors, and nothing else.',
        'beginner',
        [S_ZONE, S_BASE % 'Matte (metal 0, roughness 200, coat 160)' + ' with Use solid color #3a4a5a.',
         'Add chrome lines: ' + S_BOX + ' Thin boxes along the beltline and rocker. Choose Chrome (metal 255, roughness 2, coat 16) or Satin Chrome (metal 250, roughness 45, coat 40).',
         'Set BASE COLOR to Use solid color #f4f4f4 on the chrome zones.',
         S_RENDER],
        [X('Matte with chrome line', 'Modern retro', {'Body': 'Matte, #3a4a5a', 'Line': 'Chrome, #f4f4f4, thin box'}, 'A flat car with a mirror pinline.', 'spec_chrome'),
         X('Satin chrome roof', 'Subtle', {'Body': 'Matte, #1a1c20', 'Roof': 'Satin Chrome, #f4f4f4'}, 'A dark car with a brushed-metal roof.', 'spec_matte')],
        [D('Contrast is spec', 'Matte next to chrome pops more than saturated colour.'), D('Keep lines thin', 'Wide chrome looks like foil.')],
        [Q('How do I do matte with chrome?', 'Matte body, thin chrome zones.'), Q('Satin chrome?', 'Softer.'), Q('Gloss body?', 'Loses contrast.')],
        [M('Chrome shows black', 'Dark reflection', 'Judge in the sim.'), M('No pop', 'Satin everywhere', 'Use matte.')],
        ['Flat paint with chrome trim lines is the modern retro look.'],
        ['matte with chrome', 'matte and chrome', 'chrome accents', 'chrome trim', 'chrome pinstripe', 'flat with chrome', 'chrome delete reverse', 'satin chrome accents', 'chrome lines', 'chrome stripe'],
        fin=['base::matte', 'base::f_chrome', 'base::f_satin_chrome'],
        related=['ideas.chrome_show_car', 'ideas.make_it_pop', 'ideas.clean_classy'], combos=[('ideas.make_it_pop', 'Spec contrast.')],
        screens=['spec_chrome', 'spec_matte'], extra_src=[SIXTY])

if todo('space_galaxy'):
    art('space_galaxy', 'Space and galaxy: nebula, star field and deep colour',
        'Space looks are deep blue-purple bodies with star sparkle. Use Nebula, Stardust Coat or Chameleon Galaxy, with the Stardust pattern and Galaxy Swirl or Stardust Fine overlays.',
        'A galaxy paint is dark with bright points. Start from near-black or deep violet, add micro sparkle for stars, and a colour cloud in magenta or cyan.',
        'beginner',
        [S_ZONE, S_BASE % 'Gloss (metal 0, roughness 30, coat 16)' + ' with Use solid color #0a0720.',
         'Add stars: BASE > SPEC OVERLAYS > + ADD SPEC OVERLAY, choose Stardust Fine, Strength 50; open PATTERN and choose Stardust, Blend, Scale (pattern) 0.6.',
         'For a ready-made nebula pick Nebula, Stardust Coat or Chameleon Galaxy in Base Material.',
         S_RENDER],
        [X('Stardust coat', 'Subtle', {'Base Material': 'Stardust Coat', 'Check': 'about metal 27, roughness 97, coat 77'}, 'Dark paint with sparkle and a few bright stars.', 'cat_fractured_cosmos'),
         X('Nebula', 'Colourful', {'Base Material': 'Nebula'}, 'A magenta and cyan ion cloud.', 'cat_fractured_cosmos'),
         X('Galaxy shift', 'Colour shift', {'Base Material': 'Chameleon Galaxy'}, 'Purple to blue to white.', 'cat_spectrum_shift')],
        [D('Stars are spec', 'Micro sparkle in the shine looks more like stars than coloured dots.'), D('Dark ground', 'The darker the base, the more stars show.')],
        [Q('How do I do galaxy?', 'Dark base plus Stardust.'), Q('Nebula?', 'Nebula finish.'), Q('Sparkle only?', 'Stardust Fine overlay.')],
        [M('Looks like confetti', 'Too strong', 'Lower Strength.'), M('No stars', 'Light base', 'Use near-black.')],
        ['Galaxy Swirl adds a spiral of sparkle.'],
        ['galaxy', 'galaxy look', 'space look', 'space paint', 'nebula look', 'stars', 'star field', 'cosmic look', 'night sky', 'universe look', 'outer space', 'astronaut look'],
        fin=['base::gloss', 'monolithic::ff_nebula', 'base::efx_stardust_coat', 'monolithic::chameleon_galaxy'], pat=['stardust'], spc=['stardust_fine', 'galaxy_swirl'],
        related=['ideas.colour_shift', 'ideas.metal_flake_sparkle', 'ideas.neon_night'], combos=[('ideas.metal_flake_sparkle', 'Sparkle family.')],
        screens=['cat_fractured_cosmos', 'cat_spectrum_shift'], extra_src=[THEMES])

if todo('dragon_snake_scales'):
    art('dragon_snake_scales', 'Dragon and snake scales: reptile skin and armour',
        'Scales come from the Dragon Scale and Snake Skin patterns, or finishes like Duality Scales and Snakeskin Boot. Use them on the lower body, hood or whole car.',
        'Scale looks suit aggressive and exotic builds. Choose a small scale for skin and a larger one for armour, and keep a calm colour so the pattern shows.',
        'beginner',
        [S_ZONE, S_BASE % 'Gloss (metal 0, roughness 30, coat 16)' + ' with a deep colour, #0f3d2e (green) or #2a0a0a.',
         'Open PATTERN and choose Dragon Scale, Snake Skin or Snake Skin 3, Paint mode Blend, Scale (pattern) 0.7.',
         'For a ready-made version pick Duality Scales or Dragon Ascent in Base Material.',
         S_RENDER],
        [X('Dragon armour', 'Fantasy', {'Body': 'Gloss, #2a0a0a', 'PATTERN': 'Dragon Scale, Blend, 0.7'}, 'Overlapping dark red scales.', 'cat_forbidden_dragon'),
         X('Snakeskin', 'Exotic', {'Body': 'Gloss, #0f3d2e', 'PATTERN': 'Snake Skin 3, Blend, 0.6'}, 'A green reptile skin.', 'cat_forbidden_dragon'),
         X('Dragon Ascent', 'Gold', {'Base Material': 'MS Dragon Ascent'}, 'Dragon gold with flame trails.', 'cat_forbidden_dragon')],
        [D('Scale size', 'Smaller scale reads as snake, larger as dragon armour.'), D('Colour', 'Deep colour keeps the scales readable.')],
        [Q('How do I do scales?', 'Dragon Scale or Snake Skin pattern.'), Q('Which snake?', 'Snake Skin 1-4.'), Q('Gold dragon?', 'Dragon Ascent.')],
        [M('Looks like fabric', 'Scale too small', 'Raise it.'), M('Pattern hidden', 'Busy base', 'Plain base.')],
        ['Add a wet gloss for a fresh-skin look.'],
        ['scales', 'scale look', 'dragon scales', 'snake skin', 'snakeskin', 'reptile look', 'lizard look', 'cobra look', 'python look', 'dragon look', 'armour look', 'crocodile look'],
        fin=['base::gloss', 'base::astra_duality_scales', 'base::ms_dragon_ascent', 'base::fo_snakeskin_boot'], pat=['dragon_scale', 'snake_skin', 'snake_skin_3'],
        related=['ideas.aggressive_mean', 'ideas.japanese_art', 'ideas.flames'], combos=[('ideas.aggressive_mean', 'Mean builds.')],
        screens=['cat_forbidden_dragon'], extra_src=[THEMES])

if todo('patriotic_rwb'):
    art('patriotic_rwb', 'Patriotic red, white and blue: stars, stripes and fireworks',
        'Red, white and blue schemes use stars and stripes. Use the Let Freedom Ring finishes and patterns (Stencil Stars, Star Lattice, Stripe Drift) for a polished version without a flag.',
        'A good patriotic car is two of the three colours dominant and the third as accent. Stars go on the blue field; stripes run front to back.',
        'beginner',
        [S_ZONE, S_BASE % 'Gloss (metal 0, roughness 30, coat 16)' + ' with Use solid color #0a2a6b (navy).',
         'Add stripes: ' + S_BOX + ' Thin red #c8102e and white #f4f4f4 stripes along the hood and roof.',
         'Add stars: PATTERN Stencil Stars or Star Lattice, Blend, Scale (pattern) 0.7, on the roof or rear.',
         S_RENDER],
        [X('Navy with stripes', 'Classic', {'Body': 'Gloss, #0a2a6b', 'Stripes': 'Gloss, #c8102e and #f4f4f4', 'PATTERN': 'Stencil Stars, 0.7'}, 'A navy car with stars and stripes.', 'cat_let_freedom_ring'),
         X('Old Glory Flux', 'Colour shift', {'Base Material': 'Old Glory Flux'}, 'Navy with red-white star flecks.', 'cat_let_freedom_ring'),
         X('Rockets Red Glare', 'Fireworks', {'Base Material': 'Rockets Red Glare'}, 'Firework bursts on a black field.', 'cat_let_freedom_ring')],
        [D('Proportion', 'Two dominant, one accent.'), D('Stars on blue', 'Stars read best on the darkest colour.')],
        [Q('How do I do red white and blue?', 'Navy body, stripes, stars.'), Q('Fireworks?', 'Rockets Red Glare.'), Q('Subtle?', 'Midnight Militia.')],
        [M('Too busy', 'Stars everywhere', 'Limit to one panel.'), M('Colours fight', 'Equal amounts', 'One dominant.')],
        ['Distressed Patina is a weathered flag pattern.'],
        ['patriotic', 'red white and blue', 'usa look', 'american look', 'stars and stripes', 'america look', 'fourth of july', 'flag look', 'freedom look', 'old glory', 'patriot look'],
        fin=['base::gloss', 'monolithic::lfr_old_glory_flux', 'monolithic::lfr_rockets_red_glare', 'monolithic::lfr_midnight_militia'], pat=['lfr_stencil_stars', 'lfr_star_lattice', 'lfr_stripe_drift', 'lfr_distressed_flag'],
        related=['ideas.team_colours', 'ideas.racing_stripes', 'ideas.old_school_muscle'], combos=[('ideas.old_school_muscle', 'American muscle.')],
        screens=['cat_let_freedom_ring'], extra_src=[THEMES])

if todo('japanese_art'):
    art('japanese_art', 'Japanese art: waves, cranes, sunbursts and lacquer',
        'Japanese-inspired art uses lacquer finishes and wave patterns: Fuji Dawn, Hakuryu Ice, Indigo Tsunami with Japanese Wave and Seigaiha Scales. Keep it calm with one focal area.',
        'Traditional motifs are waves, cranes, sunbursts and blossoms. The Rising Sun collection holds many lacquers, and wave patterns add structure. Use ink colours: indigo, vermilion, gold, white.',
        'intermediate',
        [S_ZONE, S_BASE % 'Gloss (metal 0, roughness 30, coat 16)' + ' with Use solid color #1b2a5a (indigo).',
         'Add wave texture: PATTERN Japanese Wave or Seigaiha Scales, Blend, Scale (pattern) 0.6, on the lower body.',
         'Add a sun accent: ' + S_BOX + ' A circle-like box on the hood in #c8102e.',
         'Or pick a Rising Sun lacquer in Base Material. ' + S_RENDER],
        [X('Indigo wave', 'Hokusai feel', {'Body': 'Gloss, #1b2a5a', 'PATTERN': 'Japanese Wave, Blend, 0.6'}, 'Deep blue waves.', 'cat_rising_sun'),
         X('Fuji Dawn', 'Lacquer', {'Base Material': 'Fuji Dawn'}, 'A Japanese-inspired lacquer.', 'cat_rising_sun'),
         X('Bosozoku', 'Street', {'Base Material': 'Bosozoku Riot'}, 'Red rising-sun street chrome with black speed stripes.', 'cat_rising_sun')],
        [D('Palette', 'Indigo, vermilion, gold and white.'), D('Calm', 'One focal area only.')],
        [Q('How do I do Japanese art?', 'Indigo body, wave pattern, red sun.'), Q('Street style?', 'Bosozoku Riot.'), Q('Lacquer?', 'Rising Sun finishes.')],
        [M('Cluttered', 'Too many motifs', 'One motif.'), M('Colour wrong', 'Own palette', 'Use Hue Shift.')],
        ['Hakuryu Ice is a cool white lacquer.'],
        ['japanese art', 'japanese design', 'japanese wave', 'great wave', 'ukiyo e', 'sunburst', 'rising sun', 'lacquer look', 'kimono look', 'samurai look', 'zen look', 'crane look', 'sakura look'],
        fin=['base::gloss', 'monolithic::rs_fuji_dawn', 'monolithic::rs_hakuryu_ice', 'monolithic::rs_bosozoku_riot', 'monolithic::rs_indigo_tsunami'], pat=['japanese_wave', 'seigaiha_scales'],
        related=['ideas.jdm', 'ideas.dragon_snake_scales', 'ideas.clean_classy'], combos=[('ideas.jdm', 'Street cousin.')],
        screens=['cat_rising_sun'], extra_src=[THEMES])

if todo('surf_beach_summer'):
    art('surf_beach_summer', 'Surf and beach: sea colours, boardwalk and summer pastels',
        'Surf looks use turquoise, coral and cream with a sun-faded finish. Try Pipeline Royale, Boardwalk Pinlines or Surf Wax, or a pastel body with a wave pattern.',
        'Beach schemes feel relaxed: soft ocean colours, a pale body, and a little sun fade. Keep the finish satin rather than gloss, and add one warm accent such as coral.',
        'beginner',
        [S_ZONE, S_BASE % 'Satin (metal 0, roughness 95, coat 70)' + ' with Use solid color #7fd6d0 (turquoise).',
         'Add a coral accent: ' + S_BOX + ' Lower body or a stripe in Satin, #ff7a6b.',
         'For ready-made pick Pipeline Royale, Boardwalk Pinlines or Surf Wax in Base Material.',
         S_RENDER],
        [X('Turquoise and coral', 'Beach', {'Body': 'Satin, #7fd6d0', 'Accent': 'Satin, #ff7a6b'}, 'A soft ocean car.', 'cat_sock_hop'),
         X('Pipeline Royale', 'Surf barrels', {'Base Material': 'Pipeline Royale'}, 'Rows of peeling surf barrels with foam.', 'cat_astra'),
         X('Surf Wax', 'Retro', {'Base Material': 'Extreme: Surf Wax'}, 'Cream, mint and coral wax shavings.', 'cat_astra')],
        [D('Satin', 'Satin reads sun-washed.'), D('Warm accent', 'Coral or yellow stops it looking cold.')],
        [Q('How do I do surf?', 'Turquoise satin plus coral.'), Q('Which finishes?', 'Pipeline Royale, Boardwalk Pinlines, Surf Wax.'), Q('Faded?', 'Add Sun Faded.')],
        [M('Too cold', 'No warm colour', 'Add coral.'), M('Too glossy', 'Gloss body', 'Use satin.')],
        ['Sun Faded under the roof gives a sun-baked board feel.'],
        ['surf', 'surf look', 'beach look', 'beach car', 'summer look', 'ocean colours', 'tropical look', 'sunny look', 'surfer look', 'boardwalk', 'sea colours', 'wave look'],
        fin=['base::satin', 'base::astra_pipeline_royale', 'base::astra_boardwalk_pinlines', 'base::at_surf_wax', 'base::efx_sun_faded'],
        related=['ideas.pastel', 'ideas.retro_90s', 'ideas.fade_gradient'], combos=[('ideas.pastel', 'Soft colours.')],
        screens=['cat_astra', 'cat_sock_hop'], extra_src=[THEMES])

if todo('racing_green_heritage'):
    art('racing_green_heritage', 'Racing green and heritage: deep green, cream and gold',
        'Heritage racing is deep British green with a cream stripe, gold lining and a simple roundel for the number. Gloss, calm and classy.',
        'This is the 1950s-60s European look: one deep colour, a cream or white number disc, a thin gold line. Use gloss green, keep trim minimal, and avoid modern effects.',
        'beginner',
        [S_ZONE, S_BASE % 'Gloss (metal 0, roughness 30, coat 16)' + ' with Use solid color #0d3b2a.',
         'Add the stripe: ' + S_BOX + ' A cream stripe #e8dfc4 down the hood and roof.',
         'Add gold lining: thin boxes beside the stripe in #d4a017.',
         'Keep a cream disc for the number on the door. ' + S_RENDER],
        [X('Green and cream', 'Heritage', {'Body': 'Gloss, #0d3b2a', 'Stripe': 'Gloss, #e8dfc4', 'Lining': 'Gloss, #d4a017'}, 'A deep green car with a cream stripe.', 'cat_sock_hop'),
         X('Brass edge', 'Rich', {'Zone': 'Thin boxes', 'Base Material': 'Brass Night'}, 'Warm brass trim lines.', 'cat_money_shokk')],
        [D('Palette', 'Deep green, cream and gold.'), D('Restraint', 'No pattern, no neon.')],
        [Q('How do I do racing green?', 'Gloss deep green, cream stripe.'), Q('Gold?', 'Thin lines only.'), Q('Number?', 'Cream disc.')],
        [M('Looks modern', 'Metallic green', 'Plain gloss.'), M('Lining too thick', 'Wide gold', 'Thin boxes.')],
        ['Pair with a tan interior look: leave the roof cream.'],
        ['racing green', 'british racing green', 'heritage look', 'heritage racing', 'classic racer', 'vintage racing', 'green and cream', 'green and gold', 'old british look', 'brg', 'classic green', 'green livery'],
        fin=['base::gloss', 'monolithic::dkc_brass_night'],
        related=['ideas.clean_classy', 'ideas.martini_style', 'ideas.black_gold_luxury'], combos=[('ideas.clean_classy', 'Restraint.')],
        screens=['cat_sock_hop', 'cat_money_shokk'], extra_src=[FAM])

if todo('punk_grunge_street'):
    art('punk_grunge_street', 'Punk, grunge and street: spray, splatter and rough edges',
        'Street looks are rough on purpose: spray splatter, tag-style marks, and worn edges. Use Grunge Splatter, a worn finish and a dark body.',
        'The aim is attitude, not polish. Use a flat dark body, add splatter or tag marks in one bright colour, and let wear show at edges.',
        'beginner',
        [S_ZONE, S_BASE % 'Flat Black (metal 0, roughness 250, coat 255)' + ' with Use solid color #14141a.',
         'Add splatter: PATTERN Grunge Splatter or Beanie Tag, Overlay, Scale (pattern) 0.8, colour #ff2bd6 or #d7ff00.',
         'Add wear: BASE > SPEC OVERLAYS > + ADD SPEC OVERLAY, Sandblast Strip, Strength 30.',
         S_RENDER],
        [X('Splatter on black', 'Street', {'Body': 'Flat Black, #14141a', 'PATTERN': 'Grunge Splatter, Overlay, 0.8', 'Colour': '#d7ff00'}, 'A black car with lime splatter.', 'cat_grunge_fun'),
         X('Rough edges', 'Worn', {'Base Material': 'Die-Back Patina', 'Base Strength': '50'}, 'Faded clearcoat patches.', 'cat_flaw_lab')],
        [D('One bright colour', 'Lime, pink or orange on black.'), D('Wear', 'Sandblast Strip and Die-Back give rough edges.')],
        [Q('How do I do punk?', 'Dark base, splatter, wear.'), Q('Tag look?', 'Beanie Tag.'), Q('Clean?', 'This is the opposite.')],
        [M('Too neat', 'No wear', 'Add overlay.'), M('Colour fights', 'Two bright colours', 'One.')],
        ['Keep splatter off the number panel.'],
        ['punk look', 'grunge look', 'grunge', 'street look', 'graffiti look', 'spray paint look', 'splatter look', 'tag look', 'rough look', 'urban look', 'skater look', 'gritty look'],
        fin=['base::flat_black', 'base::bth_die_back'], pat=['decade_90s_grunge_splatter', 'decade_90s_beanie_tag'], spc=['spec_sandblast_strip'],
        related=['ideas.worn_patina', 'ideas.retro_90s', 'ideas.aggressive_mean'], combos=[('ideas.worn_patina', 'Rough cousins.')],
        screens=['cat_grunge_fun', 'cat_flaw_lab'], extra_src=[THEMES])

if todo('team_colours'):
    art('team_colours', 'Team colours: one palette across car, helmet and gear',
        'Team colours mean a fixed palette used the same way on every car: a main colour, an accent and a trim, repeated on all panels. Use exact hex codes and copy zones.',
        'A team identity is consistency. Pick three hex colours, use the 60-30-10 rule, and reuse the same zones on each car so the fleet matches.',
        'beginner',
        [S_ZONE, S_BASE % 'Gloss (metal 0, roughness 30, coat 16)' + ' with Use solid color for your main colour (60 percent).',
         'Add the accent (30 percent): ' + S_BOX + ' Lower body and roof.',
         'Add a trim (10 percent): thin pinlines.',
         'Write the three hex codes down and reuse them. ' + S_RENDER],
        [X('Red, white, black', 'Classic', {'Main': 'Gloss, #c8102e (60%)', 'Accent': 'Gloss, #f4f4f4 (30%)', 'Trim': 'Gloss, #0b0b0e (10%)'}, 'A balanced team palette.', 'cat_color_clash'),
         X('Blue, orange, white', 'Contrast', {'Main': 'Gloss, #0a3fd0', 'Accent': 'Gloss, #ff7a00', 'Trim': 'Gloss, #f4f4f4'}, 'Complementary pair.', 'cat_signal')],
        [D('60-30-10', 'About 60 percent dominant, 30 accent, 10 trim.'), D('Reuse', 'Copy zones with the duplicate icon.')],
        [Q('How do I match team colours?', 'Same hex codes everywhere.'), Q('How many colours?', 'Three.'), Q('Which?', 'Your own.')],
        [M('Colours drift', 'Different hex', 'Copy codes.'), M('Too many colours', 'Five colours', 'Three.')],
        ['Complementary neighbours (blue and orange) pop most.'],
        ['team colours', 'team colors', 'team livery', 'team scheme', 'match team', 'fleet look', 'same colours as my team', 'matching cars', 'team paint', 'club colours', 'school colours', 'brand colours'],
        fin=['base::gloss'],
        related=['ideas.sponsor_friendly_bases', 'ideas.numbers_match_body', 'ideas.make_it_pop'], combos=[('ideas.sponsor_friendly_bases', 'Room for logos.')],
        screens=['cat_color_clash', 'cat_signal'], extra_src=[SIXTY])

if todo('numbers_match_body'):
    art('numbers_match_body', 'Matching numbers to the body: contrast and calm panels',
        'Numbers must contrast with the paint behind them. Keep the door centre calm, pick a number colour opposite in brightness, and never run a busy stripe behind it.',
        'The app leaves numbers untouched unless you ask: whole-car looks only change the body paint layers. Your job is to make the paint behind them calm and light or dark enough.',
        'beginner',
        [S_ZONE, 'Under RESTRICT TO LAYERS tick Car Paint so numbers and sponsors stay as they are.',
         'On the door centre (side height roughly 0.30 to 0.65) use a plain colour with no pattern.',
         'Check contrast: dark number on a light panel, or the reverse.',
         S_RENDER],
        [X('White number on dark', 'Safe', {'Door zone': 'Gloss, #14284b', 'Number': 'White'}, 'High contrast.', 'ui_zone_apply_area'),
         X('Calm door panel', 'Busy body', {'Body': 'Pattern', 'Door zone': 'Draw box, Gloss, #0b0b0e'}, 'A plain panel inside a busy design.', 'cat_signal')],
        [D('Door centre', 'The number lives at 0.30 to 0.65 of the side height.'), D('Layers', 'Car Paint only protects numbers.')],
        [Q('How do I keep my number readable?', 'Plain panel and contrast.'), Q('Will the app paint over it?', 'Not with Car Paint ticked.'), Q('Which colours?', 'Black on yellow or white on navy.')],
        [M('Number lost', 'Pattern behind it', 'Plain panel.'), M('Number repainted', 'Layer not ticked', 'Tick Car Paint.')],
        ['Black on yellow is the highest contrast pair.'],
        ['numbers match body', 'match the number', 'number colour', 'readable number', 'number contrast', 'door number', 'keep number', 'number on door', 'number panel', 'number readable', 'number clash'],
        fin=['base::gloss'],
        related=['ideas.readable_on_tv', 'ideas.team_colours', 'ideas.sponsor_friendly_bases'], combos=[('ideas.readable_on_tv', 'Same rule.')],
        screens=['ui_zone_apply_area', 'cat_signal'], extra_src=[ERA, READ])

if todo('sponsor_friendly_bases'):
    art('sponsor_friendly_bases', 'Sponsor-friendly bases: plain areas for logos',
        'Sponsor logos need quiet, high-contrast areas. Use a solid gloss or satin body, keep patterns to the lower body, and leave doors, hood and rear plain.',
        'Logos on a busy finish are unreadable. Choose a calm base and put your style in the margins: a stripe, a lower band, or the roof.',
        'beginner',
        [S_ZONE, S_BASE % 'Gloss (metal 0, roughness 30, coat 16)' + ' with a solid colour.',
         'Put style in the margins: ' + S_BOX + ' Lower body band and roof.',
         'Leave the door and hood plain; a logo sits on a quiet area.',
         S_RENDER],
        [X('Plain with band', 'Sponsor ready', {'Body': 'Gloss, #f4f4f4', 'Band': 'Gloss, #0a3fd0 on the lower body'}, 'A white car with a blue lower band.', 'cat_signal'),
         X('Dark with roof', 'Dark', {'Body': 'Satin, #14284b', 'Roof': 'Gloss, #ffd400'}, 'A navy car with a yellow roof.', 'cat_signal')],
        [D('Quiet zones', 'Doors, hood and quarter panels.'), D('Contrast', 'Logos are mostly dark or white.')],
        [Q('How do I leave room for sponsors?', 'Plain body, style on the edges.'), Q('Gloss?', 'Yes.'), Q('Will logos be painted over?', 'No, with Car Paint ticked.')],
        [M('Logo unreadable', 'Pattern behind', 'Plain base.'), M('Looks boring', 'No accent', 'Add band.')],
        ['White and navy bases suit nearly any sponsor.'],
        ['sponsor friendly', 'sponsor look', 'leave room for sponsors', 'room for logos', 'logo space', 'sponsor panels', 'sponsor base', 'plain base', 'simple base', 'sponsors on car', 'clean base for decals'],
        fin=['base::gloss', 'base::satin'],
        related=['ideas.team_colours', 'ideas.numbers_match_body', 'ideas.oval_stock_car'], combos=[('ideas.numbers_match_body', 'Same quiet-panel rule.')],
        screens=['cat_signal', 'cat_foundation'], extra_src=[READ])

if todo('style_menu'):
    art('style_menu', 'Pick a style: a menu of looks you can build',
        'A quick menu of the looks the encyclopedia can build: retro eras, racing, street, luxury, military, neon, nature and materials. Pick one and the guide will show the exact steps.',
        'When you only know the mood, start here. Each style has a short recipe with real finishes and settings, and you can mix two (for example matte with chrome plus a neon accent).',
        'beginner',
        ['Decide the mood in one word: pop, mean, classy, retro, stealth, neon, military, luxury.',
         'Open the matching style article from Related and follow its steps.',
         'Mix at most two styles; keep one dominant colour.',
         S_RENDER],
        [X('Loud', 'Stand out', {'Style': 'Make it pop, Neon night, High-vis'}, 'Strong contrast looks.', 'cat_signal'),
         X('Quiet', 'Understated', {'Style': 'Clean and classy, Stealth, Monochrome'}, 'Calm looks.', 'cat_foundation'),
         X('Retro', 'Era looks', {'Style': '60s, 70s, 80s, 90s, Gulf-style, Muscle'}, 'Vintage palettes.', 'cat_sock_hop')],
        [D('Mix carefully', 'Two styles is plenty.'), D('Colour first', 'Decide the colours before the finish.')],
        [Q('I do not know what style I want', 'Pick a mood word and open its article.'), Q('Make it look cool', 'Try Make it pop or Look aggressive.'), Q('Can I mix?', 'Yes, two styles.')],
        [M('Looks messy', 'Four styles mixed', 'Keep two.'), M('Looks bland', 'No contrast', 'Open Make it pop.')],
        ['Search a word like retro, stealth or neon to jump straight to a recipe.'],
        ['pick a style', 'style menu', 'what styles', 'design ideas', 'ideas for my car', 'give me ideas', 'what should i paint', 'help me choose a look', 'i do not know what style', 'style ideas', 'inspire me', 'surprise me', 'make it cool', 'make it look good', 'make it look cool', 'looks cool'],
        related=['ideas.make_it_pop', 'ideas.aggressive_mean', 'ideas.clean_classy', 'ideas.stealth_murdered_out', 'ideas.neon_night', 'ideas.retro_70s', 'ideas.jdm', 'ideas.fighter_jet', 'ideas.look_expensive'],
        combos=[('ideas.make_it_pop', 'Most-asked.')], screens=['cat_signal', 'cat_foundation'], quick=True, extra_src=[THEMES])
