#!/usr/bin/env python
"""ideas batch 02 (2026-10-05): finish-character styles - wet, satin OEM, chrome show car, candy lowrider, patina, rat rod."""
from enc_ideas_build import *

X = lambda t, g, s, r, screen=None: dict(title=t, goal=g, settings=s, result=r, **({'screen': screen} if screen else {}))
D = lambda h, b: dict(heading=h, body=b)
Q = lambda q, a: dict(q=q, a=a)
M = lambda s, c, f: dict(symptom=s, cause=c, fix=f)
SPEC_DOC = doc('docs/ai_knowledge/02_spec_and_finishes.md', 'The spec map in iRacing')
CHOICE_DOC = doc('docs/ai_knowledge/02_spec_and_finishes.md', 'How to choose')

if todo('look_wet'):
    art('look_wet', 'Make it look wet: razor gloss and deep colour',
        'A wet look is the tightest highlight a plain paint can have: Wet Look (metal 0, roughness 15, coat 16), a deep dark colour, and dull neighbours so the shine reads by contrast.',
        'Buyers say "make it look wet", "freshly waxed", "glossy" or "show shine". Wet comes from the lowest roughness a non-metal paint allows, the deepest coat, a dark or saturated colour that gives the reflections something to sit on, and a matte or satin area nearby that makes the gloss obvious.',
        'beginner',
        [S_ZONE, S_BASE % 'Wet Look (metal 0, roughness 15, coat 16)' + ' with BASE COLOR on Use solid color.',
         'Pick a deep colour: black #0b0b0e, oxblood #5a0a14 or midnight #0a1a3a. Dark grounds show reflections best.',
         'Optional: open BASE > SPEC OVERLAYS, + ADD SPEC OVERLAY, choose CC Wet Zone, Strength 30 to 40, for slightly uneven glossy clear patches.',
         'Put a Matte or Satin zone beside it (for example the roof or a lower band) so the wet area reads by contrast. ' + S_CHECK + ' ' + S_RENDER],
        [X('Black wet gloss', 'Deep piano-black shine',
           {'BASE': 'Foundation Bases > Wet Look', 'BASE COLOR': 'Use solid color #0b0b0e', 'Roof zone': 'Draw box, Matte, #0b0b0e'},
           'Mirror-black body with a dead-flat roof that makes the gloss obvious.', 'spec_candy'),
         X('Candy wet red', 'Wet and rich',
           {'BASE': 'Candy (metal 200, roughness 15, coat 16)', 'BASE COLOR': 'Use solid color #8a0a1c', 'Color Depth': '65', 'SPEC OVERLAY': 'CC Wet Zone, Strength 35'},
           'Red glass with uneven wet-looking clear.', 'cat_glass_surface')],
        [D('The numbers', 'Wet Look is metal 0, roughness 15, coat 16: the tightest highlight a dielectric paint can have. Gloss is roughness 30, so Wet Look is twice as tight. Coat 16 is the deepest clearcoat; larger values are duller.'),
         D('Contrast makes wet', 'Gloss only reads against something duller. A car that is all gloss looks plain; the same gloss beside a matte roof looks wet.')],
        [Q('How do I make the paint glossier?', 'Switch to Wet Look and keep a dark colour; check G ROUGH is near black and B COAT is at its darkest.'),
         Q('Wet look or candy?', 'Wet Look is a clear shine over any colour; candy adds metal depth under the colour.'),
         Q('Does it show in the preview?', 'Only as a bright highlight; judge it in the sim with a bright sky.')],
        [M('Looks the same as Gloss', 'Both are very low roughness', 'Add a Matte neighbour and a darker colour.'),
         M('Highlights look blown out', 'Pale colour on Wet Look', 'Use a deeper colour.')],
        ['A dark colour plus a matte neighbour beats any extra effect.'],
        ['wet look', 'make it look wet', 'wet paint look', 'freshly waxed', 'just waxed', 'make it glossy', 'high gloss', 'make it shiny', 'mirror shine', 'liquid look', 'fresh paint look', 'show car shine', 'concours finish', 'piano black', 'looks wet'],
        fin=['base::wet_look', 'base::gloss', 'base::f_candy', 'base::matte'], spc=['cc_wet_zone'],
        related=['recipes.wet_glass', 'ideas.chrome_show_car', 'ideas.candy_lowrider', 'ideas.make_it_pop'], combos=[('recipes.wet_glass', 'Step-by-step version.')],
        screens=['spec_candy', 'cat_glass_surface'], extra_src=[SPEC_DOC])

if todo('satin_modern_oem'):
    art('satin_modern_oem', 'Satin and modern OEM: soft sheen, no hard reflections',
        'Modern factory and wrap looks live on Satin (metal 0, roughness 95, coat 70) or Semi-Gloss (roughness 55, coat 40): a soft broad highlight in a grey, white or deep colour.',
        'Satin reads as a premium factory or vinyl-wrap finish. It hides small surface flaws, never looks cheap, and works under sponsors. The step down from gloss is Semi-Gloss, then Satin, then Eggshell, then Matte.',
        'beginner',
        [S_ZONE, S_BASE % 'Satin (metal 0, roughness 95, coat 70)' + ' with BASE COLOR on Use solid color.',
         'Pick a modern colour: slate grey #6b6f76, cement #a0a3a8, deep green #123524, or a pearl white #e9e9e6.',
         'For a metallic satin choose Satin Pearl (metal 100, roughness 90, coat 60) instead; for a flat metal choose Matte Metallic (metal 225, roughness 140, coat 100).',
         'Add a single gloss detail (trim or lower splitter) in Gloss so the satin reads. ' + S_CHECK + ' ' + S_RENDER],
        [X('Cement grey satin', 'Modern supercar wrap',
           {'BASE': 'Satin', 'BASE COLOR': 'Use solid color #a0a3a8', 'Trim zone': 'Gloss, #0b0b0e on mirrors and lip'}, 'Soft grey with black gloss trim.', 'spec_matte'),
         X('Pearl satin green', 'Subtle shimmer',
           {'BASE': 'Satin Pearl', 'BASE COLOR': 'Use solid color #123524', 'SPEC OVERLAY': 'Pearl Micro, Strength 30'}, 'Dark green with a faint silk shimmer.', 'cat_foundation')],
        [D('The ladder', 'Gloss roughness 30, Semi-Gloss 55, Satin 95, Eggshell 140, Matte 200, Primer 215, Flat Black 250. Each step rubs the highlight out wider and flatter.'),
         D('Why it is forgiving', 'Broad soft highlights hide panel flaws and do not blow out under sun, so satin suits both clean and busy liveries.')],
        [Q('What is the difference between satin and matte?', 'Satin keeps a soft sheen (roughness 95); matte absorbs light (roughness 200).'),
         Q('Satin or gloss under sponsors?', 'Either; satin is more forgiving on TV.'),
         Q('How do I get a wrap look?', 'Satin plus a Gloss trim hairline.')],
        [M('Looks flat grey', 'No gloss detail anywhere', 'Add a gloss hairline or trim.'),
         M('Too shiny', 'Semi-Gloss chosen', 'Step down to Satin.')],
        ['Satin Pearl is the quickest premium-feel upgrade of plain satin.'],
        ['satin finish', 'satin look', 'make it satin', 'modern look', 'oem look', 'oem plus', 'factory look', 'wrap look', 'vinyl wrap look', 'supercar wrap', 'semi gloss', 'eggshell look', 'frozen finish', 'nardo grey', 'cement grey'],
        fin=['base::satin', 'base::semi_gloss', 'base::eggshell', 'base::f_satin_pearl', 'base::f_matte_metallic', 'base::gloss'], spc=['pearl_micro'],
        related=['ideas.clean_classy', 'ideas.stealth_murdered_out', 'ideas.monochrome'], combos=[('ideas.clean_classy', 'Satin is the default clean finish.')],
        screens=['spec_matte', 'cat_foundation'], extra_src=[SPEC_DOC])

if todo('chrome_show_car'):
    art('chrome_show_car', 'Chrome and show car: mirror metal done right',
        'Chrome is metal 255, roughness 2, coat 16: near-white colour gives silver, dark colour gives dark chrome. Use it all over only for a deliberate show car.',
        'A full-chrome car is the loudest look there is and shows every flaw. Used as trim, numbers or accents it reads as jewellery. When a buyer wants a show car, pick the chrome tier that matches the mood: mirror, dark or satin.',
        'intermediate',
        [S_ZONE, S_BASE % 'Chrome (metal 255, roughness 2, coat 16)' + ' for mirror silver, Dark Chrome (metal 250, roughness 15, coat 40) for smoked, or Satin Chrome (metal 250, roughness 45, coat 40) for a softer highlight.',
         'Set BASE COLOR to Use solid color: near white #f4f4f4 for silver, any hue for tinted chrome.',
         'To keep your own colours and only add metal, set BASE COLOR to Use source paint (spec only). Dark source colours give dark chrome.',
         'Keep numbers readable: put a gloss plate behind them. ' + S_CHECK + ' R METAL should be bright, G ROUGH near black. ' + S_RENDER],
        [X('Full mirror chrome', 'Show car', {'BASE': 'Chrome', 'BASE COLOR': 'Use solid color #f4f4f4', 'Numbers': 'Gloss plate, #101216'}, 'Mirror silver that reflects the whole sim sky.', 'spec_chrome'),
         X('Black chrome', 'Smoked and mean', {'BASE': 'Dark Chrome', 'BASE COLOR': 'Use solid color #1a1a1e'}, 'Gunmetal mirror with a slightly weaker coat.', 'cat_materials_physics'),
         X('Chrome trim on a matte car', 'The safe chrome', {'Body': 'Matte', 'Trim zone': 'Satin Chrome, Use source paint (spec only)'}, 'Flat body with metal hairlines.')],
        [D('Three tiers', 'Chrome 255/2/16 is a perfect mirror. Dark Chrome 250/15/40 is slightly broader. Satin Chrome 250/45/40 has a wide soft highlight and is the easiest to live with.'),
         D('Chrome shows the world', 'Metal reflects the track and sky in the sim, so the same chrome looks different in every corner. A dark colour under it gives dark chrome.')],
        [Q('Can I chrome the whole car?', 'Yes, but it is loud and unforgiving. Trim and numbers are safer.'),
         Q('Why is my chrome dark?', 'The colour under it is dark; use a near-white colour or Satin Chrome.'),
         Q('Does chrome keep my sponsors?', 'Use Car Paint restriction so logos stay on their own layer.')],
        [M('Chrome looks grey and dull', 'Dark source colour', 'Lighten the colour or pick Satin Chrome.'),
         M('Numbers unreadable', 'Chrome flips light and dark', 'Gloss plate behind them.')],
        ['Satin Chrome is the usable one: it never flashes pure white or black.'],
        ['chrome car', 'full chrome', 'mirror finish', 'mirror chrome', 'show car', 'show car look', 'chrome wrap', 'silver chrome', 'black chrome', 'chrome paint', 'liquid chrome', 'make it chrome', 'chrome look', 'shiny metal'],
        fin=['base::f_chrome', 'base::f_dark_chrome', 'base::f_satin_chrome', 'base::matte'],
        related=['recipes.chrome_source', 'ideas.liquid_metal', 'ideas.matte_chrome_accents', 'ideas.look_wet'], combos=[('recipes.chrome_source', 'Chrome that keeps your colours.')],
        screens=['spec_chrome', 'cat_materials_physics'], extra_src=[CHOICE_DOC])

if todo('candy_lowrider'):
    art('candy_lowrider', 'Candy and lowrider: deep colour, metalflake and fine lines',
        'The classic lowrider look is candy colour over metal, big metalflake, fine pinstripes and ornate scroll panels. Candy is metal 200, roughness 15, coat 16 under a colour you choose.',
        'Candy colours glow because a polished metal sits under a transparent colour. Lowrider and custom-show builds add heavy metalflake, hand-drawn pinstripes and scrollwork. Choose a strong colour and keep the layout symmetrical.',
        'intermediate',
        [S_ZONE, S_BASE % 'Candy (metal 200, roughness 15, coat 16)' + ' with BASE COLOR on Use solid color. Rich choices: candy apple #8a0a1c, cobalt #0a3fd0, emerald #0b6b3a.',
         'Set Color Depth to 65 for rich or 100 for the deepest tint.',
         'Add flake: BASE > SPEC OVERLAYS > + ADD SPEC OVERLAY, choose Gold Flake, Strength 40. Or pick Chunky Metalflake in Base Material for big bass-boat flake.',
         'Add pinstripes: a zone with PATTERN Pinstripe at Scale (pattern) 0.5, or Gothic Scroll or Fleur-de-Lis on the hood panel, Paint mode Blend. ' + S_RENDER],
        [X('Candy apple red', 'Show-car red', {'BASE': 'Candy', 'BASE COLOR': 'Use solid color #8a0a1c', 'Color Depth': '100', 'SPEC OVERLAY': 'Gold Flake, Strength 40'}, 'Deep red with gold sparkle.', 'spec_candy'),
         X('Blue flake scroll hood', 'Custom show', {'Body': 'Base Material: Chunky Metalflake (search it), Use finish\'s own color', 'Hood zone': 'Draw box, PATTERN Gothic Scroll, Paint mode Blend, Scale (pattern) 0.6', 'Pinstripe': 'PATTERN Pinstripe on the doors'}, 'Heavy flake with a scrolled hood panel.', 'cat_flames')],
        [D('Why candy glows', 'Candy is metal 200, roughness 15, coat 16: a polished metal response under your colour. Over bright metal it glows; over black it looks black.'),
         D('Flake scale', 'Big flake (Chunky Metalflake) is a bass-boat look; fine flake at low Scale reads premium. Flake shows in the sim at an angle to the sun, not in the small preview.')],
        [Q('How do I get candy paint?', 'Candy base, a deep solid colour, Color Depth 65 to 100.'),
         Q('Can I add metalflake?', 'Yes: Gold Flake overlay or the Chunky Metalflake finish.'),
         Q('Where do pinstripes go?', 'On a thin Draw box with the Pinstripe pattern in Blend mode.')],
        [M('Candy looks black', 'Dark ground', 'Choose a brighter colour.'), M('Pinstripes too thick', 'Scale too large', 'Lower Scale (pattern) to 0.4.')],
        ['Mirror the panel artwork on both sides so the car looks hand-built.'],
        ['lowrider', 'low rider', 'candy paint', 'candy apple', 'custom show car', 'metalflake', 'metal flake paint', 'pinstripes', 'scroll work', 'kustom', 'custom paint', 'cruiser look', 'cholo style', 'bass boat flake'],
        fin=['base::f_candy', 'base::efx_chunky_flake', 'base::fo_candy_apple'], pat=['pinstripe', 'gothic_scroll', 'fleur_de_lis'], spc=['gold_flake'],
        related=['recipes.candy', 'ideas.hot_rod_kustom', 'ideas.metal_flake_sparkle', 'ideas.look_expensive'], combos=[('recipes.candy', 'Candy basics.')],
        screens=['spec_candy', 'cat_flames'], extra_src=[CHOICE_DOC])

if todo('worn_patina'):
    art('worn_patina', 'Worn and patina: faded paint, rust and honest wear',
        'Weathering is roughness up, coat down, colour faded, with wear at edges and the lower body. Lower Base Strength so your own colours show through.',
        'Barn-find, race-worn or sun-faded looks come from finishes that fade and pit the paint, plus a restrained amount of rust. Put wear where real wear happens (front, lower panels, roof) and keep it fine.',
        'intermediate',
        ['Make a zone on the area to weather (Draw box on the lower half or roof) or Remaining on Car Paint.',
         'Under BASE press Base Material and search Sun Faded (bleached), Surface Rust, Die-Back Patina, Chalked Paint or Hardware: Battle Worn.',
         'Lower Base Strength to 50 to 70 so your own paint shows through (0 is your paint, 100 is the full finish).',
         'Add detail: BASE > SPEC OVERLAYS > Salt Spray Corrosion or Galvanic Corrosion at Strength 30 to 40.',
         'Check at 100 percent zoom: wear should read as fine detail, not blotches. ' + S_RENDER],
        [X('Sun-faded roof and hood', 'Bleached top surfaces', {'APPLY AREA': 'Draw box on roof and hood', 'Base Material': 'Sun Faded', 'Base Strength': '70'}, 'Colour bleached to chalk with a dusty skin.', 'cat_flaw_lab'),
         X('Salt-eaten lower body', 'Rust on the rocker', {'APPLY AREA': 'Draw box along the rocker', 'Base Material': 'Surface Rust', 'Base Strength': '60', 'SPEC OVERLAY': 'Salt Spray Corrosion, Strength 35'}, 'Orange bloom and dark scabs on the lowest panels.', 'cat_foundation_efx')],
        [D('The spec of wear', 'Worn finishes push roughness up and coat down: Sun Faded is about metal 2, roughness 168, coat 137; Surface Rust about metal 83, roughness 131, coat 104 (catalogue averages).'),
         D('Where wear sits', 'Edges, lower panels, front and roof. Matte and low-metal finishes look more weathered than chrome.')],
        [Q('How do I make the paint look old?', 'Sun Faded or Chalked Paint, Base Strength about 60.'),
         Q('Can I keep my colours?', 'Yes, lower Base Strength.'),
         Q('Is rust realistic?', 'In small areas at the bottom, yes.')],
        [M('Looks like dirt blobs', 'Whole-car wear at large scale', 'Lower Base Scale; use a box.'), M('Colour lost', 'Base Strength 100', 'Lower it.')],
        ['Wear at the front and lower edges first; roofs fade evenly.'],
        ['worn paint', 'patina', 'weathered', 'faded paint', 'sun faded', 'make it look old', 'aged paint', 'rusty', 'rust look', 'barn find', 'distressed', 'vintage worn', 'oxidized paint', 'chalky paint', 'beat up look'],
        fin=['base::efx_sun_faded', 'base::efx_surface_rust', 'base::bth_die_back', 'base::chalky_base', 'base::tac_battle_worn'], spc=['salt_spray_corrosion', 'spec_galvanic_corrosion'],
        related=['recipes.weathered', 'ideas.rat_rod', 'ideas.vintage_diner_50s'], combos=[('recipes.weathered', 'Step-by-step weathering.')],
        screens=['cat_flaw_lab', 'spec_wear'], extra_src=[CHOICE_DOC])

if todo('rat_rod'):
    art('rat_rod', 'Rat rod: primer, rust and hand-painted scrap',
        'A rat rod is deliberately unfinished: Primer (metal 0, roughness 215, coat 200), rust-through patches, flat black bits and a few hand-painted details.',
        'Rat rod style celebrates raw, mismatched panels. Build it from primer grey as the body, rust-through patches in a few boxes, flat black panels, hand lettering and one bright flame or pinstripe for contrast.',
        'intermediate',
        [S_ZONE, S_BASE % 'Primer (metal 0, roughness 215, coat 200)' + ' with Use solid color #5a5650 as the body.',
         'Add rust patches as separate zones: Draw box on a fender and the door, Base Material Rust-Through.',
         'Add a Flat Black panel (the hood) with Use solid color #0a0a0c.',
         'Add one hand-painted accent: Hot Rod Flames in a box on the door or Pinstripe pattern. Keep it small. ' + S_RENDER],
        [X('Primer and rust', 'Raw rod', {'Body': 'Primer, #5a5650', 'Fender and door': 'Rust-Through, Draw box', 'Hood': 'Flat Black, #0a0a0c'}, 'Mismatched panels in grey, rust and flat black.', 'cat_grunge_fun'),
         X('Flame accent', 'A hand-painted pop', {'Door zone': 'Draw box, Base Material Hot Rod Flames', 'Trim': 'Pinstripe pattern, Scale (pattern) 0.5'}, 'Orange flames on a rough body.', 'cat_flames')],
        [D('Primer is flatter than matte', 'Primer is metal 0, roughness 215, coat 200; Flat Black is roughness 250, coat 255. Both look unfinished next to a single gloss detail.'),
         D('Mismatch is the point', 'Different finishes in neighbouring panels read as swapped parts.')],
        [Q('What makes a rat rod?', 'Primer, rust, mismatched panels.'), Q('Should it be dirty?', 'Rust and dust, yes; keep numbers clean.'), Q('One bright accent?', 'Yes, one flame or stripe is enough.')],
        [M('Looks like a mess', 'Too many rust zones', 'Keep to 2 or 3 patches.'), M('No contrast', 'All dull', 'Add one gloss detail.')],
        ['Keep the number panel clean and hand-lettered style.'],
        ['rat rod', 'ratrod', 'rat rod look', 'primer look', 'rusty hot rod', 'junkyard look', 'scrap built', 'beater look', 'rough look', 'unfinished look', 'gasser', 'barn find rod'],
        fin=['base::primer', 'base::efx_rust_through', 'base::flat_black', 'base::flame_hotrod'], pat=['pinstripe'],
        related=['ideas.worn_patina', 'ideas.hot_rod_kustom', 'ideas.flames'], combos=[('ideas.worn_patina', 'Gentler weathering.')],
        screens=['cat_grunge_fun', 'cat_flames'], extra_src=[CHOICE_DOC])
