"""Part VIII - The spec map (lane B). Run: python scripts/ai_atlas/enc_B_part8.py  (append-safe)."""
import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from enc_B_lib import *

D = 'spec'
ENG = 'shokker_engine_v2.py'
ZONES = 'paint-booth-2-state-zones.js'
WIKI = 'SPB_WIKI.html#spec_guide'
SK = [ENG + ':20-45', WIKI]

add(D, id='spec.what_is_spec_map', title='What the spec map is',
    summary='Every paint file comes with a second picture, the spec map. It tells iRacing how shiny, how metallic and how rough each spot of the car is.',
    what='The colour file says what colour each spot is. The spec map says what each spot is made of. Four values per pixel carry that: R for metallic, G for roughness, B for clearcoat and A for the lighting mask. The paint can be a perfect red and still look like cheap plastic if the spec map is wrong, and the reverse is just as true. Shokker Paint Booth builds both files for you, one pair per car, at 2048 by 2048 pixels covering the whole car laid flat.',
    when=['You wonder why two paints with the same colour look different on track', 'You want a chrome, a matte or a candy look and need to know what is really changing', 'You are about to touch any SPEC slider and want to know what it does'],
    how=['Pick a finish for a zone. The finish already carries its own spec values.', 'Look at the finish card or use the Spec Map Inspector to see its R, G and B numbers.', 'Move SPEC STRENGTH or the R METAL, G ROUGH and B COAT sliders to push the look.', 'Render. The paint and the spec map are written together.'],
    controls=[{'label': 'SPEC STRENGTH', 'range': '0-100%', 'default': '100%', 'effect': 'Fades the finish spec toward neutral.', 'inv': 'zone.spec_strength'}],
    tips=['Think in two layers: colour is what you see head on, spec is how light plays across it.', 'A small spec change often moves the look more than a big colour change.'],
    pitfalls=['A spec map is not a second colour image. Do not expect it to show colour on the car.', 'Strong specs on dark paint can look nearly the same as strong specs on light paint. Metal takes its colour from the paint.'],
    related=['spec.reading_by_colour', 'spec.channel_r_metallic', 'spec.paint_spec_marriage'],
    actions=[{'do': 'finish', 'id': 'base::f_chrome'}, {'do': 'finish', 'id': 'base::f_soft_matte'}, {'do': 'control', 'id': 'zone.spec_strength'}],
    figures=['g01_spec_channels', 'r13_spec_channel_views'],
    covers=['doc.02.the_spec_map_in_iracing_what_spec_means', 'wiki.start_here.what_spb_actually_is_in_one_paragraph', 'wiki.spec_guide.1_the_coordinate_system_every_possible_c', 'wiki.start_here.spec_map_channels_memorise_the_inversion'],
    sources=SK + ['docs/ai_knowledge/02_spec_and_finishes.md:1'],
    aliases=['spec map', 'what is a spec map', 'what is spec', 'specular map', 'spec file', 'spec tga', 'car spec', 'how specs work', 'how do specs work', 'spec explained'])

add(D, id='spec.channel_r_metallic', title='R channel: metallic',
    summary='Red is how metal a spot is. 0 is plain paint, plastic or glass, and 255 is solid mirror metal.',
    what='Metal reflects light with the colour of the paint under it. Plain paint reflects a white highlight on top of its colour. Turn red up and the surface takes more of the first behaviour: richer colour in the highlights, no flat white sheen. A real chrome needs a very light paint colour under it, because metal shows the paint colour. A dark paint with high metal reads as a deliberate dark mirror.',
    when=['You want to move a finish toward or away from metal', 'You are choosing between pearl, metallic and chrome'],
    how=['Open a zone and expand the SPEC sliders section.', 'Move R METAL right to add metal or left to remove it. Each tick is 5.', 'Check the Spec Map Inspector to see the resulting number.'],
    controls=[{'label': 'R METAL', 'range': '-127 to 127', 'default': '0', 'effect': 'Adds or removes metallic on top of the finish.', 'inv': 'zone.r_metal'}],
    tips=['Rough bands for metal: 0-15 plain paint, 16-63 carbon or subtle flake, 64-127 pearl, 128-175 strong pearl or anodized, 176-239 metallic, 240-255 chrome tier.', 'Foundation values to remember: Pearl 100, Metallic 200, Chrome 255.'],
    pitfalls=['High metal on a dark paint hides the colour. That is by design, but surprises people.', 'Chrome tier (240-255) is the only band allowed to use roughness below 15.'],
    related=['spec.channel_g_roughness', 'spec.metal_rough_grid', 'spec.iron_rules'],
    actions=[{'do': 'finish', 'id': 'base::f_pearl'}, {'do': 'finish', 'id': 'base::f_metallic'}, {'do': 'finish', 'id': 'base::f_chrome'}],
    figures=['g01_spec_channels', 'g04_metal_rough_grid'],
    covers=['spec.ch_r', 'wiki.spec_guide.3_the_four_channels_byte_by_byte', 'zone.r_metal'],
    sources=[ENG + ':20-45', 'SPB_WIKI.html#spec_guide', ZONES + ':2143'],
    aliases=['r channel', 'red channel', 'metallic channel', 'what is metallic', 'metal value', 'm value', 'make it more metallic'])

add(D, id='spec.channel_g_roughness', title='G channel: roughness',
    summary='Green is how rough a spot is. 0 is a perfect mirror and 255 is dead flat.',
    what='Roughness decides how sharp or how smeared a highlight is. Low green gives a tight, bright reflection like wet paint. High green spreads the reflection into a soft glow, which reads as satin, matte or flat. Roughness is the biggest single lever for how a finish feels.',
    when=['You want sharper or softer reflections', 'You want to go from gloss to satin to matte'],
    how=['Open a zone and expand the SPEC sliders section.', 'Move G ROUGH left for glossier, right for rougher.', 'Render and look at the highlights on the car, not on the flat template.'],
    controls=[{'label': 'G ROUGH', 'range': '-127 to 127', 'default': '0', 'effect': 'Adds or removes roughness on top of the finish.', 'inv': 'zone.g_rough'}],
    tips=['Roughness bands: 0-14 mirror (chrome only), 15-29 wet gloss, 30-59 high gloss, 60-99 satin gloss, 100-129 satin or eggshell, 130-159 semi-matte, 160-199 matte, 200-229 flat, 230-255 dead flat.', 'Foundation values to remember: Gloss 30, Satin Chrome 45, Brushed 75, Soft Matte 200.'],
    pitfalls=['Smooth gradients in roughness tend to smear highlights across the car. Steps between a few roughness levels give crisper, more controlled reflections.', 'Roughness under 15 is floored on anything that is not chrome-tier metal.'],
    related=['spec.channel_r_metallic', 'spec.metal_rough_grid', 'spec.iron_rules'],
    actions=[{'do': 'finish', 'id': 'base::gloss'}, {'do': 'finish', 'id': 'base::f_brushed'}, {'do': 'finish', 'id': 'base::f_soft_matte'}],
    figures=['g02_roughness_scale', 'r03_roughness_sweep'],
    covers=['spec.ch_g', 'zone.g_rough'],
    sources=[ENG + ':20-45', 'SPB_WIKI.html#spec_guide', ZONES + ':2143'],
    aliases=['g channel', 'green channel', 'roughness channel', 'what is roughness', 'rough value', 'make it glossier', 'make it more matte'])

add(D, id='spec.channel_b_clearcoat', title='B channel: clearcoat (it runs backwards)',
    summary='Blue is the clear layer on top of the paint, and it is backwards. 16 is the strongest, shiniest coat and bigger numbers make it duller.',
    what='Most people expect a bigger number to mean more clearcoat. In an iRacing spec map the opposite is true. Values 0 to 15 mean no clearcoat. 16 is full clearcoat reflectivity, the wettest look. From 16 up to 255 the coat fades toward nothing. In a normal render Shokker Paint Booth raises every blue value to at least 16, so the coat is never in the 1 to 15 dead band that whitewashes in the iRacing shader. Only a spec you imported yourself, or a pattern whose own spec amount is on, may keep an exact 0.',
    when=['You want a wetter or a drier top layer', 'A finish looks washed out and you suspect the coat value'],
    how=['Open a zone and expand the SPEC sliders section.', 'Move B COAT left (a negative number) for a glossier coat, right for a duller one. The number is added straight to the coat value, and 16 is the glossiest.', 'A coat that is already at 16 cannot get glossier, so only the right side does anything there.'],
    controls=[{'label': 'B COAT', 'range': '-127 to 127', 'default': '0', 'effect': 'Added straight to the coat value: left is glossier, right is duller. Cannot go below 16.', 'inv': 'zone.b_coat'}],
    tips=['Coat bands: 16 maximum, 17-31 very strong, 32-63 strong to medium, 64-127 satin, 128-191 dull, 192-254 almost none, 255 none.', 'Foundation values to remember: Gloss 16, Candy 52, Brushed 64, Soft Matte 158.'],
    pitfalls=['Old notes that call 255 the maximum coat are wrong. 255 is the raw maximum but the coat-effect minimum.', 'Never author values 1 to 15. Resizing a file can create them by accident, and the app raises them to 16.'],
    related=['spec.iron_rules', 'spec.channel_g_roughness', 'spec.reading_by_colour'],
    actions=[{'do': 'finish', 'id': 'base::wet_look'}, {'do': 'finish', 'id': 'base::candy'}, {'do': 'finish', 'id': 'base::f_soft_matte'}],
    figures=['g03_clearcoat_scale', 'r02_clearcoat_sweep'],
    covers=['spec.ch_b', 'zone.b_coat', 'ctl.zone_cc_quality', 'spec.cc_floor'],
    sources=[ENG + ':20-45', ENG + ':267', 'SPB_WIKI.html#spec_guide', ZONES + ':2143'],
    aliases=['b channel', 'blue channel', 'clearcoat channel', 'clear coat channel', 'clearcoat backwards', 'why is clearcoat inverted', 'cc value', 'what is cc', 'clearcoat 16'])

add(D, id='spec.channel_a_mask', title='A channel: the lighting mask',
    summary='Alpha switches iRacing lighting on or off for each spot. 255 is normal, 128 is reduced and 0 is lighting killed.',
    what='Alpha is not transparency of the paint. It controls how much of the sky reflection and sun glint iRacing applies. At 255 the spot behaves normally. At 128 the shine is weaker, which can fake shadow or depth. At 0 there is no lighting response at all, which is useful for fake holes or unlit shapes and risky as a normal material tool.',
    when=['You are making an unlit shape such as a fake hole or a glowing decal', 'You want to flatten shine over a sponsor area'],
    how=['Open SPEC TOOLS and choose Lighting Mask.', 'Pick Use Source Alpha, Full Lighting A255, Reduced Lighting A128 or Kill Lighting A0.', 'Apply it to the zone and render.'],
    controls=[],
    tips=['Keep normal body paint at 255.', 'The edge between zones blends alpha as well as colour, so a soft edge gives a soft lighting fade.'],
    pitfalls=['Alpha 0 over a big area makes the car look like a flat sticker on track.', 'Alpha stays at 255 unless you set a lighting mask or override, so do not expect holes you did not make.'],
    related=['spec.material_override_remap_lighting', 'spec.iron_rules', 'spec.reading_by_colour'],
    actions=[],
    figures=['g01_spec_channels'],
    covers=['spec.ch_a', 'pro.spec_tools.a_mask'],
    sources=[ENG + ':20-45', 'paint-booth-v2.html:4148', 'SPB_WIKI.html#spec_guide'],
    aliases=['a channel', 'alpha channel', 'specular mask', 'alpha 255', 'kill lighting', 'spec alpha'])

add(D, id='spec.reading_by_colour', title='Reading a spec picture by colour',
    summary='If you open a spec map as a normal picture the colours tell you the material. Red is metal, green is roughness and blue is the clear layer, mixed together.',
    what='The spec map holds R, G and B in one picture, so you can read a material by its colour. A pixel that is red with no green means pure mirror-like metal. A green pixel is a very rough non-metal. White is a rough metal with no coat. Nearly black is smooth plain paint. Blue is the strange one because its meaning is backwards, so a blue-heavy pixel is a dull coat, not a glossy one.',
    when=['You open a spec file in an image viewer and want to make sense of it', 'You compare two finishes and want to see what differs'],
    how=['Open the Spec Map Inspector from SPEC TOOLS.', 'Click ALL to see the combined map, or R, G, B and A to see one channel alone.', 'Use the Sample point to read exact numbers.'],
    controls=[],
    tips=['Anchors to learn: plain gloss is 0, 30, 16. Chrome is 255, 2, 16. Pure red is uncoated mirror metal. Pure green is maximally rough plain paint. Magenta is mirror metal with the coat suppressed.', 'Black does not mean empty. It means smooth, non-metal, glossy coat.'],
    pitfalls=['A very dark spec map is not a dull car. Glossy plain paint is nearly black in R, low in G and low in B.', 'Do not read the blue channel like brightness.'],
    related=['spec.what_is_spec_map', 'spec.inspector', 'spec.metal_rough_grid'],
    actions=[{'do': 'finish', 'id': 'base::gloss'}, {'do': 'finish', 'id': 'base::f_chrome'}],
    figures=['g01_spec_channels', 'r13_spec_channel_views'],
    covers=['wiki.spec_guide.2_read_the_literal_combined_map_color_co', 'wiki.spec_guide.4_fast_navigator_name_any_part_of_the_ma', 'wiki.spec_guide.the_owner_s_shorthand_confirmed_with_the'],
    sources=['SPB_WIKI.html#spec_guide', ENG + ':20-45', 'paint-booth-v2.html:3980'],
    aliases=['read spec map', 'spec map colors', 'spec map colours', 'spec colours', 'what do the spec colors mean', 'spec map colour chart', 'rgb spec'])

add(D, id='spec.metal_rough_grid', title='The metal and roughness grid',
    summary='Plot metal across and roughness down and every finish has a home. Chrome sits at high metal and low roughness, matte at low metal and high roughness.',
    what='Most looks come from just two numbers. Metal says what the surface is. Roughness says how sharp it reflects. The four corners are easy: low metal and low roughness is wet paint, high metal and low roughness is chrome, low metal and high roughness is flat paint, and high metal and high roughness is chalky raw metal. Everything else, pearl, satin chrome, brushed metal, is a point between them. The clear layer then adds or removes gloss on top.',
    when=['You want to place a finish on a map of looks', 'You are building a custom look and need target numbers'],
    how=['Choose the corner closest to the look you want.', 'Pick a Foundation finish near that corner.', 'Nudge R METAL and G ROUGH in steps of 5 and compare.'],
    controls=[{'label': 'R METAL', 'range': '-127 to 127', 'default': '0', 'effect': 'Moves the finish along the metal axis.', 'inv': 'zone.r_metal'}, {'label': 'G ROUGH', 'range': '-127 to 127', 'default': '0', 'effect': 'Moves the finish along the roughness axis.', 'inv': 'zone.g_rough'}],
    tips=['Measured Foundation points (metal, roughness, coat): Gloss 0, 30, 16. Wet Look 0, 15, 16. Pearl 100, 40, 16. Metallic 200, 50, 16. Brushed 180, 75, 64. Satin Chrome 250, 45, 39. Chrome 254, 2, 16. Soft Matte 0, 200, 158.'],
    pitfalls=['High metal with high roughness gives a chalky look, not a silver one.', 'Metal below 240 cannot go under roughness 15.'],
    related=['spec.channel_r_metallic', 'spec.channel_g_roughness', 'spec.iron_rules'],
    actions=[{'do': 'finish', 'id': 'base::f_pearl'}, {'do': 'finish', 'id': 'base::f_metallic'}, {'do': 'finish', 'id': 'base::f_satin_chrome'}, {'do': 'finish', 'id': 'base::f_brushed'}],
    figures=['g04_metal_rough_grid', 'r01_spec_sweep_RxG'],
    covers=['wiki.spec_guide.5_exact_production_paint_cards', 'wiki.spec_guide.10_car_integration_guide_choose_paint_an'],
    sources=['SPB_WIKI.html#spec_guide', ENG + ':20-45'],
    aliases=['metal roughness grid', 'metallic roughness chart', 'spec cube', 'material cube', 'finish map', 'where does chrome sit'])

add(D, id='spec.iron_rules', title='The three iron rules',
    summary='Three rules are always enforced so the spec map never breaks in iRacing: coat never below 16, roughness at 15 or more unless chrome, and alpha at full lighting unless you change it.',
    what='These guard rails run on every render. Rule one: the coat value is raised to at least 16 everywhere, so it never sits in the 1 to 15 band that whitewashes in iRacing. Only imported or pattern-driven specs may keep an exact 0. Rule two: roughness is at least 15 wherever metal is under 240. Only mirror chrome, with metal 240 or more, may go lower. Rule three: alpha starts at 255 everywhere, full lighting, and only a lighting mask, a material override or an imported spec changes it. You never have to apply them yourself, but they explain why a slider seems to stop.',
    when=['A slider will not go further than you expect', 'You edit a spec outside the app and need the safe limits'],
    how=['Stay inside the limits when you hand edit a spec map: blue at 16 or more.', 'Keep roughness at 15 or more unless metal is 240 or more.', 'Let the app handle alpha.'],
    controls=[],
    tips=['The Spec Sculpt Lab always exports iron-safe maps.'],
    pitfalls=['A hand-edited blue value of 1 to 15 will look washed out in the sim.', 'Resizing a spec picture can create forbidden values. Re-render instead of resizing.'],
    related=['spec.channel_b_clearcoat', 'spec.channel_g_roughness', 'spec.channel_a_mask'],
    actions=[],
    figures=['g18_iron_rules'],
    covers=['spec.iron1', 'spec.iron2', 'spec.iron3', 'spec.cc_floor'],
    sources=[ENG + ':267', ENG + ':301', 'SPB_WIKI.html#spec_guide'],
    aliases=['iron rules', 'iron rule', 'spec rules', 'clearcoat floor', 'why cant i go lower', 'cc 16 rule', 'whitewash'])

add(D, id='spec.paint_spec_marriage', title='Paint and spec work together',
    summary='A finish looks good when the paint and the spec disagree in the right way. Pair a warm matte with a cool metal, and give neighbours contrast.',
    what='Paint is colour and spec is surface. The finishes that pop most are the ones where they pull against each other. Put a warm, matte area next to a cool, shiny one, and the eye reads two materials even if both are similar in brightness. A spec that is the colour-opposite of the paint also works. And since iRacing shows the car small and moving, one loud hero area plus fine texture beats a dozen competing effects. Keep numbers and sponsors on calm, readable areas.',
    when=['Your car looks flat even though the colours are right', 'You want to choose finishes for neighbouring zones'],
    how=['Choose a hero zone and give it your boldest finish.', 'Give the neighbouring zones a finish with the opposite character: matte beside gloss, warm beside cool.', 'Render and judge the car at a distance, not the flat template.'],
    controls=[],
    tips=['Complementary contrast between neighbouring zones beats raw saturation.', 'Fine texture of 8 to 32 pixels on the 2048 canvas looks rich at speed. Large blobs look like smeared paint.'],
    pitfalls=['A spec that matches the paint character everywhere reads as a plain car.', 'More effects is not better. One hero area wins.'],
    related=['spec.what_is_spec_map', 'spec.metal_rough_grid', 'spec.how_layers_combine'],
    actions=[{'do': 'finish', 'id': 'base::f_chrome'}, {'do': 'finish', 'id': 'base::f_soft_matte'}],
    figures=['g19_scale_on_car', 'r04_foundation_before_after'],
    covers=['doc.05.what_makes_a_finish_pop_owner_s_proven_winners', 'wiki.finish_doctrine.paint_spec_marriage', 'doc.05.readability_first_iracing_is_seen_at_speed_and_at_distance', 'wiki.finish_doctrine.2048_car_canvas_scale_law'],
    sources=['docs/ai_knowledge/05_design_and_taste.md:1', 'SPB_WIKI.html#finish_doctrine', 'SPB_WIKI.html#spec_guide'],
    aliases=['what makes a finish pop', 'make it pop', 'finish pop', 'paint spec contrast', 'complementary contrast', 'why does my car look flat', 'make car look better'])

add(D, id='spec.how_layers_combine', title='How base, pattern and spec combine in a zone',
    summary='In every zone the base finish gives the starting paint and spec, the pattern adds shape on top, and the spec overlays add surface detail last.',
    what='Think of a zone as a short stack. First the base finish sets colour and spec. Then a pattern, up to five per zone, is laid over the paint. Pattern spec amount, if set, also carries the pattern into the spec map. Then up to five spec overlays add surface detail only to the spec, with no colour change. Finally the spec sliders, strength and blends tune the end result. Zones with lower numbers win where they overlap.',
    when=['You are not sure which control changes colour and which changes shine', 'Two settings seem to fight each other'],
    how=['Set the base finish and its colour first.', 'Add a pattern and set its paint mode, opacity and scale.', 'Add a spec overlay if you want texture without colour.', 'Finish with SPEC STRENGTH and the R, G and B sliders.'],
    controls=[{'label': 'SPEC STRENGTH', 'range': '0-100%', 'default': '100%', 'effect': 'Fades the base spec toward neutral.', 'inv': 'zone.spec_strength'}],
    tips=['Overlay mode for a pattern hides the base colour with the pattern own colours. Use Blend to keep the paint colour.', 'Spec overlays never change the colour, so they are the safe way to add texture to a colour you like.'],
    pitfalls=['A pattern with spec amount at 0 does not touch the spec map. This is on purpose.', 'The lower-numbered zone wins an overlap.'],
    related=['spec.overlays_stack', 'spec.strength_and_independent', 'spec.blend_modes'],
    actions=[{'do': 'control', 'id': 'zone.pattern_spec_amount'}, {'do': 'control', 'id': 'zone.add_spec_overlay'}],
    figures=['g13_four_kinds_of_look', 'g16_foundation_spec_only'],
    covers=['doc.02.four_kinds_of_finish_in_shokker', 'wiki.spec_guide.7_construction_grammar_how_fine_patterns', 'zone.pattern_spec_amount'],
    sources=[ZONES + ':1851', ZONES + ':2258-2335', 'js/spec-overlays/picker.js:60-85', 'SPB_WIKI.html#spec_guide'],
    aliases=['layer order', 'how layers combine', 'base pattern spec', 'what is on top', 'stacking order', 'how zones combine'])

add(D, id='spec.colour_space_and_files', title='Colour space, files and preview truth',
    summary='The paint file is an ordinary colour picture and the spec file is raw data. iRacing builds its own version from them, so a stale build can hide your newest file.',
    what='Shokker Paint Booth writes two files per car: a 24-bit paint TGA and a 32-bit spec TGA with an alpha channel, both 2048 by 2048. The paint is read as normal screen colour. The spec is read as straight numbers, with no colour correction. That is why a pretty spec picture on screen only matters as data. iRacing then compiles the TGAs into a faster .mip file, and an old .mip can show instead of your new TGA until it is rebuilt.',
    when=['Your car looks old in the sim after a fresh export', 'You open the spec TGA in an image editor'],
    how=['Export or deploy the car.', 'If the sim shows an old look, delete the stale .mip for that car so iRacing rebuilds it.', 'Never apply colour management or sharpening to a spec file.'],
    controls=[],
    tips=['Judge finishes on the car preview or in the sim, not on the flat template.', 'The preview is a close guide, not a perfect copy of the sim shader.'],
    pitfalls=['Saving the spec through a photo editor can shift values and break the iron rules.', 'Wireframe and mask overlays in the preview can hide the real finish. Turn them off before judging.'],
    related=['spec.what_is_spec_map', 'spec.iron_rules', 'spec.inspector'],
    actions=[],
    figures=['g01_spec_channels'],
    covers=['spec.colorspace', 'spec.reference', 'wiki.spec_guide.12_export_and_preview_truth', 'wiki.finish_doctrine.iracing_spec_map_truth'],
    sources=['SPB_WIKI.html#spec_guide', 'engine/SPEC_MAP_REFERENCE.md:1', ENG + ':20-45'],
    aliases=['colour space', 'color space', 'srgb linear', 'tga export', 'mip file', 'stale mip', 'car not updating', 'old paint showing in sim', 'preview vs sim'])

add(D, id='spec.strength_and_independent', title='Spec strength and independent spec',
    summary='SPEC STRENGTH fades a finish spec toward neutral. INDEPENDENT SPEC lets the spec have its own scale and rotation instead of following the base.',
    what='SPEC STRENGTH runs from 0 to 100 percent. At 100 you get the finish as designed. Lower it and metal drifts toward 0, roughness toward 128 and coat toward 16, so the look softens without changing colour. INDEPENDENT SPEC unlocks SPEC SCALE and SPEC ROTATION so the spec texture can be bigger, smaller or turned differently from the base.',
    when=['A finish is too loud and you want it calmer', 'You want the shine texture to run in a different direction from the paint'],
    how=['Open the zone and find SPEC STRENGTH. Drag it in steps of 5.', 'Tick INDEPENDENT SPEC to unlock SPEC SCALE and SPEC ROTATION.', 'Render and compare.'],
    controls=[{'label': 'SPEC STRENGTH', 'range': '0-100%, step 5', 'default': '100%', 'effect': 'Scales metal, roughness and coat toward neutral.', 'inv': 'zone.spec_strength'}, {'label': 'INDEPENDENT SPEC', 'range': 'on or off', 'default': 'off', 'effect': 'Frees spec scale and rotation from the base.', 'inv': 'zone.independent_spec'}],
    tips=['Behind the slider: metal times strength, roughness moves toward 128 and coat toward 16.'],
    pitfalls=['Strength 0 is neutral, not dull: coat goes to 16, the glossiest value.', 'Spec strength does not change colour.'],
    related=['spec.scale_rotation', 'spec.channel_sliders', 'spec.blend_modes'],
    actions=[{'do': 'control', 'id': 'zone.spec_strength'}, {'do': 'control', 'id': 'zone.independent_spec'}],
    figures=['r01_spec_sweep_RxG'],
    covers=['zone.spec_strength', 'zone.independent_spec', 'wiki.spec_guide.11_spb_controls_that_mutate_a_paint_card'],
    sources=[ZONES + ':2111-2115', 'SPB_WIKI.html#spec_guide'],
    aliases=['spec strength', 'spec intensity', 'independent spec', 'spec too strong', 'reduce shine', 'soften spec'])

add(D, id='spec.scale_rotation', title='Spec scale and rotation',
    summary='SPEC SCALE resizes the texture in the spec map and SPEC ROTATION turns it. Both work on the spec only.',
    what='Where a finish has a texture in its spec, such as brushed grain or a weave, scale makes it bigger or smaller and rotation turns it. Scale runs from 0.05 to 5 times, with 1.00 as the finish default. Rotation goes from 0 to 355 degrees in steps of 5. Because the canvas covers a whole car, a small scale usually looks richer than the default.',
    when=['Brushed grain looks too coarse or runs the wrong way', 'A weave or flake needs to be finer'],
    how=['Tick INDEPENDENT SPEC in the zone.', 'Drag SPEC SCALE below 1.00 for finer detail.', 'Drag SPEC ROTATION to turn the grain.'],
    controls=[{'label': 'SPEC SCALE', 'range': '0.05x-5x', 'default': '1.00x', 'effect': 'Resizes spec texture.', 'inv': 'zone.spec_scale'}, {'label': 'SPEC ROTATION', 'range': '0-355 degrees, step 5', 'default': '0', 'effect': 'Turns spec texture.', 'inv': 'zone.spec_rotation'}],
    tips=['Features of 8 to 32 pixels read as fine detail on the car.'],
    pitfalls=['The controls stay inactive until INDEPENDENT SPEC is ticked.', 'Large scale on a whole car looks like big smears.'],
    related=['spec.strength_and_independent', 'spec.overlays_stack', 'spec.paint_spec_marriage'],
    actions=[{'do': 'control', 'id': 'zone.spec_scale'}, {'do': 'control', 'id': 'zone.spec_rotation'}],
    figures=['g19_scale_on_car'],
    covers=['zone.spec_scale', 'zone.spec_rotation'],
    sources=[ZONES + ':2111-2115', 'SPB_WIKI.html#spec_guide'],
    aliases=['spec scale', 'spec rotation', 'spec size', 'rotate brushed grain', 'finer spec', 'brushed direction'])

add(D, id='spec.channel_sliders', title='R, G and B channel sliders',
    summary='The R METAL, G ROUGH and B COAT sliders nudge the finish spec. They add or subtract under the zone and then the app clips to safe limits.',
    what='These three sliders shift each channel by up to 127 either way, in steps of 5. The shift is added to the finish spec under the zone shape, then clipped at the floors: 0 for metal, 15 for roughness and 16 for coat. They are the fine-tuning tool after you pick a finish. The built-in Feels set them in one click.',
    when=['A finish is almost right but a touch too dull or too rough', 'You want a consistent tweak across several zones'],
    how=['Open the zone and expand the SPEC sliders.', 'Move R METAL, G ROUGH and B COAT.', 'Use the Feel picker or the save icon for presets.'],
    controls=[{'label': 'R METAL', 'range': '-127 to 127, step 5', 'default': '0', 'effect': 'Metal shift.', 'inv': 'zone.r_metal'}, {'label': 'G ROUGH', 'range': '-127 to 127, step 5', 'default': '0', 'effect': 'Roughness shift.', 'inv': 'zone.g_rough'}, {'label': 'B COAT', 'range': '-127 to 127, step 5', 'default': '0', 'effect': 'Coat shift, added to the coat value. Left is glossier, right is duller.', 'inv': 'zone.b_coat'}],
    tips=['For a wetter look, lower G ROUGH, and lower B COAT if the finish coat is above 16.', 'The B COAT slider tooltip in the app says higher is a stronger mirror. The number is really added to the coat value, where bigger means duller, so judge by eye in the preview.'],
    pitfalls=['Shifts that reach a floor stop having an effect.', 'Large shifts can cancel the finish character.'],
    related=['spec.presets_feels', 'spec.auto_pop', 'spec.iron_rules'],
    actions=[{'do': 'control', 'id': 'zone.spec_sliders'}],
    figures=['r01_spec_sweep_RxG', 'r02_clearcoat_sweep'],
    covers=['zone.spec_sliders', 'wiki.spec_guide.8_mixing_and_gradients_without_destroyin'],
    sources=[ZONES + ':2143', ENG + ':20231', 'SPB_WIKI.html#spec_guide'],
    aliases=['spec sliders', 'rgb sliders', 'metal rough coat sliders', 'channel shift', 'tweak spec'])

add(D, id='spec.material_override_remap_lighting', title='Material override, remap and lighting mask',
    summary='SPEC TOOLS has three power tools: copy a material onto a zone, squeeze a channel into a new range, and set how much lighting each area gets.',
    what='Material Sampler lets you sample a spot on an existing spec and apply that material to a zone. Material Range Remapper re-maps each channel into a low and high range. A source value of 0 goes to Low and 255 goes to High, so you can calm or intensify a whole spec. Lighting Mask sets alpha: use the source, full lighting, reduced lighting or kill lighting. A Decal Rescue Kit also fixes decals that came in shiny.',
    when=['You like the shine of one part of a spec and want it elsewhere', 'You need a quick overall change to an imported spec', 'Decals look glassy and need to go flat'],
    how=['Open SPEC TOOLS in the top bar.', 'Choose Material Range Remapper, set Low and High for M, R and CC, then apply. Restore Original puts it back.', 'Choose Lighting Mask and pick a mode.', 'Choose Decal Rescue Kit for Flat Vinyl and similar fixes.'],
    controls=[{'label': 'Remap Low and High', 'range': '0-255 per channel', 'default': 'Original', 'effect': 'Squeezes a channel into a new range.', 'inv': 'ctl.zone_spec_material_override_remap_lightingmask'}],
    tips=['Remap presets: Original, Metallic Texture, Printed Vinyl, Matte Texture, Gloss Texture.'],
    pitfalls=['Remapping can push the coat into the forbidden 1 to 15 band; the app raises it back to 16.'],
    related=['spec.inspector', 'spec.channel_a_mask', 'spec.iron_rules'],
    actions=[{'do': 'control', 'id': 'ctl.zone_spec_material_override_remap_lightingmask'}],
    figures=['r13_spec_channel_views'],
    covers=['ctl.zone_spec_material_override_remap_lightingmask', 'specRemapMLow', 'specRemapMHigh', 'specRemapRLow', 'specRemapRHigh', 'specRemapCCLow', 'specRemapCCHigh', 'pro.spec_tools.decal_flat_vinyl', 'pro.spec_tools.decal_satin'],
    sources=['paint-booth-v2.html:2391', 'paint-booth-v2.html:4196', 'paint-booth-v2.html:4105', ENG + ':20231'],
    aliases=['material remap', 'decal rescue', 'spec tools', 'flat vinyl decals', 'decals too shiny'])

add(D, id='spec.blend_modes', title='Spec blend modes',
    summary='SPEC BLEND decides how a spec overlay mixes with the base spec. The named modes, Ghost Carve and friends, are made for racing finishes.',
    what='The dropdown offers Normal, Ghost Carve, Chrome Inlay, Frost Etch, Angle Flip, Ember Gate and Depth Press, plus the classic Multiply, Screen, Overlay, Hard Light and Soft Light. Each named mode has a one-line help text in the dropdown. Use Normal while learning. Try Chrome Inlay when you want an overlay to cut a mirror shape into the surface.',
    when=['An overlay hides the base spec instead of working with it', 'You want the texture to cut in, glow or flip at angles'],
    how=['Open the zone and find SPEC BLEND.', 'Pick a mode and read its help line.', 'Render and judge at car scale.'],
    controls=[{'label': 'SPEC BLEND', 'range': 'Normal, Ghost Carve, Chrome Inlay, Frost Etch, Angle Flip, Ember Gate, Depth Press, Multiply, Screen, Overlay, Hard Light, Soft Light', 'default': 'Normal', 'effect': 'Chooses how the overlay mixes with the base spec.', 'inv': 'zone.spec_blend'}],
    tips=['Compare Normal and the named mode side by side before you commit.'],
    pitfalls=['A strong overlay with a classic blend can wash out a finish.'],
    related=['spec.overlays_stack', 'spec.strength_and_independent', 'spec.how_layers_combine'],
    actions=[{'do': 'control', 'id': 'zone.spec_blend'}],
    figures=['r13_spec_channel_views'],
    covers=['zone.spec_blend'],
    sources=[ZONES + ':2118-2140', 'SPB_WIKI.html#spec_guide'],
    aliases=['spec blend', 'ghost carve', 'chrome inlay', 'frost etch', 'angle flip', 'ember gate', 'depth press'])

add(D, id='spec.overlays_stack', title='Spec patterns and overlay stacks',
    summary='Spec patterns add texture to the shine only. Stack up to five per zone and tune each one.',
    what='A spec pattern is a texture for the spec map, such as brushed grain, carbon weave, hex cells or micro sparkle. It changes how light plays, never the colour. The catalogue has 301 of them in 25 groups. In a zone, expand the SPEC OVERLAYS section and click Add Spec Overlay. You can stack up to five. Each layer has move up and down, Duplicate, Mute, Solo and Inspect, plus its own Strength, M, R and C channel ticks, Size, Rotation, X and Y position, Blend and a Coverage box.',
    when=['You want carbon, brushed or sparkle texture without touching the colour', 'You want a unique surface on one part of the car'],
    how=['Open the zone and expand SPEC OVERLAYS.', 'Click Add Spec Overlay and pick a pattern.', 'Set Strength (default 50) and the channels M, R and C that it should touch.', 'Use Mute and Solo to compare layers.'],
    controls=[{'label': 'Add Spec Overlay', 'range': 'up to 5 per zone', 'default': 'none', 'effect': 'Adds a spec texture layer.', 'inv': 'zone.add_spec_overlay'}, {'label': 'SPEC OVERLAYS section', 'range': 'Strength 0-100, Size 0.25-1, Rotation 0-359', 'default': 'Strength 50', 'effect': 'Per layer tuning.', 'inv': 'zone.section_spec_overlays'}],
    tips=['Solo one layer at a time when you debug a busy look.', 'Pick M, R or C on purpose: texture on roughness only is the safest.'],
    pitfalls=['Five layers at full strength fight each other.', 'Spec overlays change shine only. If you want visible shapes on the paint, use a pattern.'],
    related=['spec.blend_modes', 'spec.scale_rotation', 'spec.how_layers_combine'],
    actions=[{'do': 'spec', 'id': 'metallic_sand'}, {'do': 'spec', 'id': 'holographic_flake'}, {'do': 'spec', 'id': 'spec_carbon_weave'}, {'do': 'control', 'id': 'zone.add_spec_overlay'}],
    figures=['r13_spec_channel_views'],
    covers=['zone.add_spec_overlay', 'zone.section_spec_overlays', 'catalog.spec_patterns'],
    sources=['js/spec-overlays/picker.js:60-85', ZONES + ':12292', 'docs/ai_knowledge/02_spec_and_finishes.md:1'],
    aliases=['spec overlay', 'spec overlays', 'spec patterns', 'spec pattern', 'add spec overlay', 'spec texture', 'stack spec patterns'])

add(D, id='spec.presets_feels', title='Spec presets and Feels',
    summary='Feels are one-click spec tweaks. Wet Candy, Track Flash, Chrome Mirror, Deep Gloss, Soft Pearl and Satin Matte are built in.',
    what='A Feel sets the three channel sliders at once. The built-in Feels are, as metal, rough and coat shifts: Wet Candy 30, -55, 45. Track Flash 55, -35, 60. Chrome Mirror 80, -80, 70. Deep Gloss 25, -45, 85. Soft Pearl 15, 25, 10. Satin Matte -25, 65, -15. The disk icon saves your own Feel on this computer.',
    when=['You want a quick consistent shine change across zones', 'You found a combination you want to reuse'],
    how=['Open the SPEC sliders section of a zone.', 'Pick a Feel from the preset list.', 'To keep your own, set the sliders and click the save icon.'],
    controls=[{'label': 'Spec preset', 'range': '6 built in plus saved', 'default': 'none', 'effect': 'Applies metal, rough and coat shifts at once.', 'inv': 'zone.spec_preset'}, {'label': 'Save preset', 'range': 'one click', 'default': '', 'effect': 'Saves your slider settings as a Feel.', 'inv': 'zone.save_spec_preset'}],
    tips=['Apply a Feel, then fine tune by 5.'],
    pitfalls=['Feels stack on top of the finish, so a Feel on a matte finish will not make it chrome.', 'The coat part of a Feel is a positive number, and a bigger coat number is a duller coat, so these Feels soften the coat. Judge the result by eye.'],
    related=['spec.channel_sliders', 'spec.auto_pop', 'spec.strength_and_independent'],
    actions=[{'do': 'control', 'id': 'zone.spec_preset'}],
    figures=[],
    covers=['zone.spec_preset', 'zone.save_spec_preset'],
    sources=[ZONES + ':9969-9975'],
    aliases=['spec presets', 'feels', 'wet candy', 'track flash', 'chrome mirror feel', 'deep gloss', 'soft pearl', 'satin matte feel', 'save spec preset'])

add(D, id='spec.auto_pop', title='Auto-Pop',
    summary='Auto-Pop gives a zone a small, safe boost of shine in one click and can be undone in a single step.',
    what='Auto-Pop looks at the zone average and nudges only what is weak. It adds up to 15 metal if the zone metal averages under 70. It lowers roughness by up to 45 if the roughness averages above 70. It lowers the coat value by up to 45 if the coat averages above 55, which makes it glossier. All steps are multiples of 5. If the zone is already glossy it says so and changes nothing.',
    when=['A zone looks dull and you want a quick lift', 'You want a safe starting point before hand tuning'],
    how=['Open the zone SPEC sliders section.', 'Click Auto-Pop.', 'Press Undo if you do not like it. It is a single step.'],
    controls=[{'label': 'Auto-Pop', 'range': 'one click', 'default': '', 'effect': 'Adds a small shine boost to weak channels.', 'inv': 'zone.auto_pop'}],
    tips=['Repeat clicks keep boosting until the limits are reached.'],
    pitfalls=['It will not turn a matte finish into chrome.'],
    related=['spec.presets_feels', 'spec.channel_sliders', 'spec.paint_spec_marriage'],
    actions=[{'do': 'control', 'id': 'zone.auto_pop'}],
    figures=[],
    covers=['zone.auto_pop'],
    sources=[ZONES + ':9919'],
    aliases=['auto pop', 'autopop', 'make it shinier', 'auto shine', 'quick shine boost'])

add(D, id='spec.inspector', title='The Spec Map Inspector',
    summary='The Inspector lets you look at the spec channels one at a time and read exact values from any spot.',
    what='Open SPEC TOOLS and choose Material Sampler. The channel buttons ALL, R, G, B and A switch the view. Sample modes are Point, 3 by 3 Median and 5 by 5 Median. A table shows the minimum, maximum and mean of each channel. Copy M, R, CC and A copy the sampled numbers. Select Connected and Select All Similar find matching areas, using a Material tolerance from 0 to 64 (default 12). Apply to Active Zone and Clear Zone Override finish the job.',
    when=['You want to read exactly what a finish is doing', 'You want to copy a material from one place to another'],
    how=['Open SPEC TOOLS then Material Sampler.', 'Pick a channel view and a sample size.', 'Click the car or the template to sample.', 'Use Select Connected or Select All Similar, then Apply to Active Zone.'],
    controls=[{'label': 'Material tolerance', 'range': '0-64', 'default': '12', 'effect': 'How close a match must be.', 'inv': 'specMaterialSelectTolerance'}, {'label': 'Sample size', 'range': 'Point, 3x3 Median, 5x5 Median', 'default': 'Point', 'effect': 'Averages around the click.', 'inv': 'specMaterialSampleSize'}],
    tips=['Use Median sampling on noisy textures.'],
    pitfalls=['Point sampling on grain gives a random value. Use the median.'],
    related=['spec.reading_by_colour', 'spec.material_override_remap_lighting', 'spec.what_is_spec_map'],
    actions=[],
    figures=['r13_spec_channel_views'],
    covers=['pro.spec_tools.all', 'pro.spec_tools.r_metallic', 'pro.spec_tools.g_roughness', 'pro.spec_tools.b_clearcoat', 'pro.spec_tools.a_mask', 'btnCopySpecSample', 'btnSelectConnectedMaterial', 'btnSelectAllMaterial', 'btnApplySpecSample', 'pro.spec_tools.clear_zone_override', 'specMaterialSelectTolerance', 'specMaterialSampleSize'],
    sources=['paint-booth-v2.html:3980', 'paint-booth-v2.html:2391'],
    aliases=['material sampler', 'inspect spec', 'sample spec', 'copy material', 'select similar material'])

add(D, id='spec.angle_reveal', title='Colour shift and angle reveal',
    summary='iRacing cannot truly change hue with the viewing angle, so colour shift looks are built by hiding colour in dark paint and revealing it with fine spec detail.',
    what='A true colour-flip paint is not possible with the sim shader. The trick is to bury the colours in a near-black base and add fine spec pins, 8 to 32 pixels wide, that catch the light at certain angles. As the car turns, those pins flash and the colour appears to move. Foundation EFX, Prizm, Spectrum Shift and the Fractured shelves use this idea. It needs very fine detail to work, and it needs a deep, dark base.',
    when=['You want a chameleon or flip look', 'A shift finish looks flat head on'],
    how=['Pick a Prizm, Spectrum Shift or Fractured Nightshift finish.', 'Keep the base dark.', 'Do not scale the pattern up. Fine detail is the point.'],
    controls=[{'label': 'COLOR FLIP', 'range': '0-355', 'default': '0', 'effect': 'Rotates the flip colour: 90 is the neighbour hue and 180 the opposite.', 'inv': 'zone.color_flip'}],
    tips=['Check the look at a distance and turned on the car.'],
    pitfalls=['A bright base kills the effect.', 'Large pins read as sparkle, not shift.'],
    related=['spec.paint_spec_marriage', 'spec.overlays_stack', 'spec.metal_rough_grid'],
    actions=[{'do': 'control', 'id': 'zone.color_flip'}],
    figures=['g13_four_kinds_of_look'],
    covers=['wiki.finish_doctrine.color_shift_angle_reveal_doctrine', 'wiki.spec_guide.6_advanced_cards_fractured_night_flip_an', 'wiki.spec_guide.9_worked_master_recipe_fractured_gradien'],
    sources=['docs/COLORSHOXX_ANGLE_REVEAL.md:1', 'SPB_WIKI.html#finish_doctrine', 'SPB_WIKI.html#spec_guide'],
    aliases=['angle reveal', 'colour shift', 'color shift', 'chameleon', 'hue shift with angle', 'colorshoxx'])

add(D, id='spec.pattern_groups', title='The spec pattern groups',
    summary='The 301 spec patterns are sorted into groups such as sparkle, brushed metal, carbon weave, clearcoat, weather and wear, and animal skins.',
    what='The original 181 sit in 25 groups: Sparkle and Micro-Metal 8, Optical and Interference 7, Directional Metal and Brush 4, Carbon and Composite Weave 9, Clearcoat and Coating 4, Structure and Geometry 10, Surface and Spray Texture 4, Organic and Natural 4, Weather, Wear and Track 6, Racing and Livery Story 3, Mechanical and Industrial 1, Exotic and Kinetic 3, Precision and Guilloche 6, Artistic and Abstract 1, Predator Skins 8, Dangerous Animals 10, Gothic and Horror 4, Voodoo Inspired 10, Rising Sun Spec 9, Engine-Turn and Machined 1, Fire and Heat 1, Holographic and Color-Shift 1, Source Pattern Plates 24, Definitive Spec Replacements 33 and Let Freedom Ring 10. A newer set of 120 overlays adds more machined, crystal and surface textures. Every spec pattern changes the shine only.',
    when=['You want a texture family, such as carbon weave or brushed metal', 'You want a themed surface, such as predator skin or gothic'],
    how=['Open SPEC OVERLAYS in a zone and click Add Spec Overlay.', 'Pick a group.', 'Click a pattern, then set Strength and the M, R and C channels.'],
    controls=[],
    tips=['Sparkle and Micro-Metal and Carbon and Composite Weave are the safest first picks.', 'Source Pattern Plates match the plate finishes of the same name.'],
    pitfalls=['A themed group may be loud. Lower Strength before you stack a second layer.'],
    related=['spec.overlays_stack', 'spec.blend_modes', 'spec.scale_rotation'],
    actions=[{'do': 'spec', 'id': 'metallic_sand'}, {'do': 'spec', 'id': 'spec_carbon_weave'}, {'do': 'spec', 'id': 'holographic_flake'}],
    figures=['r13_spec_channel_views'],
    covers=inv_ids(kinds=['spec_pattern_group'], domains=['spec']),
    sources=['js/spb-ai-atlas-data.js:2', 'js/spec-overlays/picker.js:60-85'],
    aliases=['spec pattern groups', 'spec pattern categories', 'types of spec patterns', 'carbon weave spec', 'brushed metal spec'])

assemble(D)
