"""Curated links from a short help_* Q&A page to the full article / worked recipe that goes deeper (lane C, 2026-10-04).
Key = "kind:slug" (kind is howto | topics | support | guide; slug is the page slug). Every target id is a hand-written article that exists."""
WORKED = 'A complete worked build with exact settings.'
FIX = 'The full troubleshooting article: every cause, the fix steps and how to confirm.'

HAND_REL = {
 'howto:make_chrome': [('recipes.chrome_source', WORKED)], 'howto:make_matte': [('recipes.matte_black', WORKED)],
 'howto:gradient': [('recipes.three_colour_gradient', WORKED), ('recipes.gradient_roof_rocker', WORKED)],
 'howto:not_in_iracing': [('support.not_in_iracing', FIX)], 'howto:zone_not_showing': [('support.zone_no_show', FIX)],
 'howto:numbers_look_wrong': [('support.numbers_vanished', FIX)], 'howto:protect_sponsors': [('recipes.change_body_keep_numbers', WORKED)],
 'howto:finish_numbers': [('recipes.finish_on_numbers', WORKED)], 'howto:recolour_numbers': [('recipes.finish_on_numbers', WORKED)],
 'howto:make_pop': [('recipes.make_it_pop', WORKED)], 'howto:start_over': [('recipes.undo_start_over', WORKED)],
 'howto:look_differs': [('support.colours_differ', FIX)], 'howto:pattern_finer': [('support.smeared_blobby', FIX)],
 'howto:preview_not_changing': [('support.preview_render_mismatch', FIX)], 'howto:fix_preview': [('support.preview_render_mismatch', FIX)],
 'howto:left_vs_right': [('recipes.mirror_side', WORKED)], 'howto:save_template': [('recipes.team_liveries', WORKED)],
 'howto:share_recipe': [('recipes.team_liveries', WORKED)], 'howto:export_iracing': [('recipes.psd_to_iracing', WORKED), ('support.not_in_iracing', FIX)],
 'howto:load_psd': [('support.psd_wont_open', FIX)], 'howto:loaded_nothing': [('support.psd_wont_open', FIX)],
 'howto:old_render': [('preview_render.render_history_stats', 'Where your earlier renders are kept and how to bring one back.')],
 'howto:spec_only_shine': [('recipes.chrome_source', WORKED)], 'howto:spec_overlay': [('recipes.flake_pearl', WORKED)],
 'howto:add_pattern': [('recipes.carbon_hood', WORKED), ('recipes.camo', WORKED)], 'howto:randomise': [('recipes.make_it_pop', WORKED)],
 'howto:copy_picture': [('recipes.match_photo', WORKED)], 'howto:design_from_words': [('recipes.retro_stripes', WORKED)],
 'howto:gloss_level': [('support.flat_or_shiny', FIX)], 'howto:colour_not_applying': [('support.flat_or_shiny', FIX)],
 'howto:restrict_to_layer': [('recipes.edit_one_thing', WORKED)], 'howto:finish_one_part': [('recipes.rear_accents', WORKED)],
 'howto:make_zone': [('recipes.two_tone', WORKED)], 'howto:undo': [('recipes.undo_start_over', WORKED)],
 'howto:render_wont_start': [('support.render_slow_or_fails', FIX)], 'howto:decal_rescue': [('support.numbers_vanished', FIX)],
 'topics:render': [('support.render_slow_or_fails', FIX)], 'topics:iracing': [('support.not_in_iracing', FIX)],
 'topics:start_over': [('recipes.undo_start_over', WORKED)], 'topics:undo': [('recipes.undo_start_over', WORKED)],
 'topics:numbers': [('recipes.finish_on_numbers', WORKED)], 'topics:keep_paint': [('recipes.edit_one_thing', WORKED)],
 'topics:matte_gloss': [('recipes.matte_black', WORKED)], 'topics:gradient': [('recipes.three_colour_gradient', WORKED)],
 'topics:pattern_size': [('support.tiny_or_huge', FIX)], 'topics:refresh': [('support.preview_render_mismatch', FIX)],
 'support:chrome_dark': [('recipes.chrome_source', WORKED), ('support.colours_differ', FIX)], 'support:preview_vs_sim': [('support.preview_render_mismatch', FIX)],
 'support:glass_black': [('support.not_in_iracing', FIX)], 'support:output_folder': [('support.not_in_iracing', FIX)],
 'support:need_id': [('support.not_in_iracing', FIX)], 'support:push_failed': [('support.render_slow_or_fails', FIX)],
 'support:memory': [('support.render_slow_or_fails', FIX)], 'support:render_busy': [('support.render_slow_or_fails', FIX)],
 'support:engine_offline': [('support.wont_start_or_update', FIX)], 'support:version_drift': [('support.wont_start_or_update', FIX)],
 'support:no_zones': [('support.zone_no_show', FIX)], 'support:layer_zone': [('support.zone_no_show', FIX)],
 'support:size_2048': [('support.tiny_or_huge', 'Tiny or huge textures are a scale problem, not a canvas-size problem.')],
 'support:helmet_suit': [('recipes.helmet_suit', WORKED)], 'support:recipe': [('recipes.team_liveries', WORKED)],
 'support:others_see': [('support.trading_paints', FIX)], 'support:mip': [('support.trading_paints', FIX)],
 'support:shokker_file': [('support.lost_files', FIX)], 'support:where_files': [('support.lost_files', FIX)],
 'support:job_gone': [('support.lost_files', FIX)], 'support:open_psd': [('support.psd_wont_open', FIX)],
 'support:template_layers': [('support.colours_differ', FIX)], 'support:autosave_off': [('support.lost_files', FIX)],
 'guide:setting_up_iracing_the_part_everyone_fumbles_once': [('support.not_in_iracing', FIX)],
 'guide:gotchas_in_one_place': [('support.not_in_iracing', FIX), ('support.colours_differ', FIX)],
 'guide:render_amp_see_it_in_iracing': [('recipes.psd_to_iracing', WORKED)],
 'guide:quick_start_a_real_finish_in_five_minutes': [('recipes.psd_to_iracing', WORKED)],
}
