#!/usr/bin/env python
"""ideas batch 01 (2026-10-05): the vague asks - pop, aggressive, classy, expensive, fast, stand out, TV, stealth. Resume-safe (todo())."""
from enc_ideas_build import *

X = lambda t, g, s, r, screen=None: dict(title=t, goal=g, settings=s, result=r, **({'screen': screen} if screen else {}))
D = lambda h, b: dict(heading=h, body=b)
Q = lambda q, a: dict(q=q, a=a)
M = lambda s, c, f: dict(symptom=s, cause=c, fix=f)

POP_DOC = doc(DOC_DESIGN, 'What makes a finish POP')
PRO_DOC = doc(DOC_DESIGN, 'Palettes that work')
LIV_DOC = doc(DOC_LIVERY, 'Composition rules')
RCP_DOC = doc(DOC_RECIPES, 'Recipe: "make it pop"')

if todo('make_it_pop'):
    art('make_it_pop', 'Make it pop: contrast of colour AND shine',
        'Pop comes from neighbours that differ: a complementary colour pair, plus a shine difference such as candy or metal beside matte, with one loud hero panel. Saturation alone does not do it.',
        'When a buyer says "make it pop", "pop more" or "it looks flat", the cure is contrast between neighbours, not more colour. Put a deep glossy candy or metal next to a flat matte of the opposite colour, keep one hero area loud (hood, roof or the big side) and let everything else stay calm so the eye has somewhere to land.',
        'beginner',
        ['Pick the hero area (the hood, roof or the biggest side panel) and the two colours that sit opposite each other: blue and orange, black and hot pink, white and red.',
         S_ZONE,
         S_BASE % 'Candy (metal 200, roughness 15, coat 16)' + ' Set BASE COLOR to Use solid color and choose a deep colour for the hero. Candy is the glossy one.',
         'Add a second zone for the neighbouring area. Choose Matte from the same shelf (metal 0, roughness 200, coat 160) with the opposite colour. Drag the hero zone above the matte zone in the left column so it wins where they meet.',
         'Add trim as a third zone: PICK COLOR FROM CAR on the stripe or accent colour, choose Satin Chrome (metal 250, roughness 45, coat 40) and set BASE COLOR to Use source paint (spec only).',
         S_CHECK,
         'Judge it small. If the car reads as a clear two-value picture at arm\'s length, stop. ' + S_RENDER],
        [X('Cobalt candy hood beside orange matte', 'A hero hood that explodes against a calm body',
           {'Hero zone': '+ Add Zone, APPLY AREA > Draw box over the hood', 'BASE': 'Foundation Bases shelf > Candy', 'BASE COLOR': 'Use solid color #0a3fd0 (deep cobalt)', 'Color Depth': '65',
            'Body zone': 'COLOR: Remaining, RESTRICT TO LAYERS: Car Paint', 'Body BASE': 'Matte', 'Body colour': 'Use solid color #e8761c', 'List order': 'Hood zone above the body zone'},
           'Cobalt glass beside chalky orange: opposite colours and opposite shine (roughness 15 against 200).', 'cat_color_clash'),
         X('Black body with hot pink chrome accents', 'A dark car whose accents flash',
           {'Body zone': 'Remaining, Car Paint only, BASE: Satin, Use solid color #0d0d10', 'Accent zone': 'PICK COLOR FROM CAR on the stripe colour (paint it #ff2bd6 first)', 'Accent BASE': 'Satin Chrome',
            'Accent BASE COLOR': 'Use source paint (spec only)', 'Check': 'R METAL bright on the stripes only'},
           'Soft satin black with pink stripes that flash like chrome when the sun hits them.', 'spec_chrome'),
         X('One click more flash', 'Pop a finish you already like without touching the colour',
           {'Zone': 'Click the zone card, then BASE > Spec Sliders', 'Button': 'Auto-Pop', 'Or': 'Spec preset: Track Flash'},
           'The three spec sliders move toward glossier: more metal flash, less roughness, deeper coat. Colours stay as they are.')],
        [D('Why saturation alone fails', 'The owner\'s favourite finish out of 50 measured shelf entries did not win on saturation, which was only mid-pack. It won because neighbouring bands were a true colour opposite and the shine layer was the colour-opposite of the paint. Plain saturation just makes a louder blob.'),
         D('Shine contrast is half of pop', 'Candy is metal 200, roughness 15, coat 16; Matte is metal 0, roughness 200, coat 160. In the sim the candy mirrors the sky while the matte soaks it up, so the pair separates even if the two colours were close. A zone with one shine everywhere reads as one flat blob however bright.'),
         D('Pop must survive distance', 'Many mid-tones (browns, dull teals, greys) turn to mud when the car is small. Two or three clear values with one accent hold up from far away; five colours look cheap.')],
        [Q('How do I make my livery pop?', 'Put one deep glossy candy or metal area next to a matte area of the opposite colour, and keep the rest calm. Add chrome only as trim.'),
         Q('It looks flat, what is missing?', 'Usually one shine everywhere. Make one area matte and one glossy or metal, then check the G ROUGH view for two clearly different greys.'),
         Q('Will more saturation help?', 'Rarely. A bigger colour jump between neighbours and a shine difference helps far more than turning saturation up.'),
         Q('How many colours should a popping car have?', 'Two or three plus one accent. White or black works as the quiet colour that lets the accents sing.')],
        [M('Everything is glossy and still looks flat', 'One shine across the whole car gives the sim nothing to separate', 'Make the neighbour matte or satin; keep gloss for the hero.'),
         M('Chrome trim looks dark and dull', 'Chrome with Use source paint takes the paint underneath: a dark colour gives dark chrome', 'Lighten the stripe colour first, or choose Satin Chrome or Candy instead.'),
         M('The hero zone has no effect', 'A zone above it claims the same pixels (the upper zone wins)', 'Drag the hero zone to the top of the left column.')],
        ['Warm paint on a matte surface next to cool paint on metal reads richer than the same colours on one shine.',
         'Keep the door centre calm: the number must stay readable, so the pop belongs on the hood, roof and lower body.',
         'Compare with the SOURCE view often; if your change barely differs from it at arm\'s length, push the contrast, not the saturation.'],
        ['make it pop', 'pop more', 'make my car pop', 'make the colors pop', 'colors pop', 'make it stand out more', 'looks flat', 'it looks flat', 'my livery looks boring', 'needs more contrast', 'more punch', 'add punch', 'make it vibrant', 'make it look better', 'wow factor', 'add wow', 'pop the paint', 'make it jump out'],
        fin=['base::f_candy', 'base::matte', 'base::f_satin_chrome', 'base::f_chrome', 'base::satin'], spc=['gold_flake', 'pearl_micro'],
        related=['recipes.make_it_pop', 'ideas.stand_out_in_pack', 'ideas.readable_on_tv', 'ideas.two_tone', 'ideas.look_expensive', 'ideas.matte_chrome_accents'],
        combos=[('ideas.two_tone', 'The classic way to apply the contrast: matte body, gloss accents.'), ('ideas.readable_on_tv', 'Pop on the hood but calm on the door so the number stays readable.')],
        screens=['cat_color_clash', 'spec_candy'], quick=True,
        when=['The car looks flat or boring in the preview.', 'A buyer asks for more punch without changing the colours.'],
        extra_src=[POP_DOC, RCP_DOC, LIV_DOC])

if todo('aggressive_mean'):
    art('aggressive_mean', 'Aggressive and mean: dark, sharp, one hot accent',
        'An aggressive car is dark and mostly flat, with sharp-edged graphics (chevrons, razor lines) and one hot accent that looks like a warning. Shine belongs only on the sharp parts.',
        'Buyers who type "look mean", "more aggressive" or "badass" want menace: a deep black or gunmetal body with low shine, angular shapes that point forward, and a single hot colour (red, orange, toxic green) used sparingly like a warning light. Menace comes from restraint and sharp geometry, not from piling on effects.',
        'beginner',
        ['Make the body dark and flat. ' + S_ZONE,
         S_BASE % 'Flat Black (metal 0, roughness 250, coat 255) or Matte (metal 0, roughness 200, coat 160)' + ' with BASE COLOR set to Use solid color #0c0d10 (a near-black keeps a little shape).',
         'Add the sharp graphics as their own zone: ' + S_BOX + ' Open PATTERN and choose Chevron Stack or Razor Wire, set Paint mode to Blend and Scale (pattern) to 0.5 so the points read fine across the whole car.',
         'Give the graphics zone a gloss edge against the flat body: choose Gloss (metal 0, roughness 30, coat 16) with Use solid color in your hot accent, for example #d8141c.',
         'Keep the accent small: lower lip, mirrors, a thin line along the beltline. Everything else stays dark.',
         S_CHECK + ' The accent should be the only loud thing.'],
        [X('Black with a red blade', 'Menacing and minimal',
           {'Body zone': 'Remaining, Car Paint only, BASE: Flat Black, Use solid color #0c0d10', 'Blade zone': 'Draw box along the lower side', 'Blade BASE': 'Gloss, Use solid color #d8141c',
            'PATTERN': 'Chevron Stack, Paint mode Blend, Scale (pattern) 0.5'},
           'A flat black car with a glossy red cutting edge along the rocker.', 'cat_dark_city'),
         X('Gunmetal with razor lines', 'A predator feel without colour',
           {'Body': 'Dark Chrome (metal 250, roughness 15, coat 40), Use solid color #23262c', 'Lines': 'PATTERN: Razor Wire, Paint mode Blend, Scale (pattern) 0.4', 'Accent': 'Gloss, #ff6a00 on mirrors and splitter'},
           'Dark liquid-metal body with fine sharp lines and an orange warning accent.', 'spec_chrome'),
         X('Toxic green threat', 'Aggressive in a non-red palette',
           {'Body': 'Matte, Use solid color #101312', 'Accent zone': 'Gloss, Use solid color #7cff1a, drawn on the front quarter only', 'Overlay': 'SPEC Hazard Chevron Weave, Strength 40'},
           'Dead black with an acid-green nose that reads as danger.')],
        [D('Why dark and flat reads mean', 'Low shine hides soft reflections, so the shape looks like one solid mass. Roughness 200 to 250 with coat 160 to 255 absorbs light; a thin gloss accent (roughness 30, coat 16) then looks wet by comparison.'),
         D('Angles beat curves', 'Chevrons, razor lines and hard diagonals point the eye forward and read as speed and attitude. Round, soft patterns (swirls, florals) read friendly. Keep the pattern fine (Scale (pattern) 0.4 to 0.6) so it does not turn into a big blob on the car.'),
         D('One accent rule', 'A single hot colour on about a tenth of the car looks like a warning. Two accents look like a toy.')],
        [Q('How do I make my car look mean?', 'Dark flat body, sharp chevron or razor graphics, and one hot accent colour in a small area.'),
         Q('What colour is most aggressive?', 'Black or gunmetal with red, orange or acid green. White bodies can work if the graphics are black and sharp.'),
         Q('Can I do aggressive without black?', 'Yes: any deep colour on a matte finish with black angular graphics and one contrasting accent.'),
         Q('Should it be glossy or matte?', 'Mostly matte or satin. Keep gloss for the accent so it flashes.')],
        [M('It looks cartoonish', 'Too many accent colours or soft round patterns', 'One accent, sharp angular pattern, black ground.'),
         M('The pattern turns into big blotches', 'Scale (pattern) left at 1.0 on a whole-car zone', 'Lower it to 0.4 to 0.6.'),
         M('Numbers disappear', 'Dark number on a dark body', 'Keep the number plate area light or outlined; see readable on TV.')],
        ['A near-black like #0c0d10 keeps a little shape; pure black on a flat finish looks like a hole.', 'Put the hot accent low (rocker, splitter) so it reads as a base of danger rather than a stripe.'],
        ['make it aggressive', 'more aggressive', 'aggressive look', 'look mean', 'make it look mean', 'mean looking', 'mean look', 'make it badass', 'badass look', 'menacing', 'intimidating', 'sinister', 'angry car', 'predator look', 'brutal look', 'dark and aggressive', 'evil looking', 'villain car'],
        fin=['base::flat_black', 'base::matte', 'base::gloss', 'base::f_dark_chrome'], pat=['chevron_stack', 'razor_wire'], spc=['spec_hazard_chevron_weave'],
        related=['ideas.stealth_murdered_out', 'ideas.make_it_pop', 'ideas.look_fast', 'ideas.military_tactical'],
        combos=[('ideas.stealth_murdered_out', 'Aggressive is stealth plus one warning colour.'), ('ideas.look_fast', 'Forward-pointing chevrons add speed to menace.')],
        screens=['cat_dark_city', 'spec_matte'], quick=True, extra_src=[POP_DOC])

if todo('clean_classy'):
    art('clean_classy', 'Clean and classy: two colours, one stripe, calm finish',
        'Classy is restraint: one dominant colour, one accent, white or black as the quiet colour, a single fine line, and a soft gloss or satin finish with no busy texture.',
        'When someone asks for clean, classy, elegant or "less busy", the answer is subtraction. Use a limited palette (about 60 percent one colour, 30 percent an accent, 10 percent trim), keep the shapes simple and aligned across the car, and pick a finish with a soft sheen instead of loud effects.',
        'beginner',
        ['Choose the palette first: one dominant colour, one accent, and white or black as the quiet colour (for example #f2f2f2 white with #c8102e red, or #0d0d10 near-black with #d4a017 gold).',
         S_ZONE,
         S_BASE % 'Gloss (metal 0, roughness 30, coat 16) for a showroom look, or Satin (metal 0, roughness 95, coat 70) for a modern one' + ' and set BASE COLOR to Use solid color.',
         'Add one stripe as its own zone: ' + S_BOX + ' Give it the accent colour with Gloss, or Satin Chrome with Use source paint for a fine metal line.',
         'Line things up: the stripe on the side should continue the colour of the bumper or hood; check the left and right sides match.',
         'Leave numbers and sponsors on clean areas with strong contrast. ' + S_RENDER],
        [X('White, red stripe', 'Clean performance look',
           {'Body': 'Remaining, Car Paint only, BASE: Gloss, Use solid color #f2f2f2', 'Stripe zone': 'Draw box along the beltline, Gloss, Use solid color #c8102e', 'Numbers': 'Black on the white door centre'},
           'Crisp white with one red line, the classic clean race look.', 'cat_foundation'),
         X('Near-black with a gold line', 'Premium dark',
           {'Body': 'Satin, Use solid color #0d0d10', 'Line zone': 'Draw box thin band, Satin Chrome, Use solid color #d4a017', 'Numbers': 'White'},
           'Soft black with a gold hairline; reads expensive.', 'spec_matte'),
         X('Pearl blue and silver', 'Soft and modern',
           {'Body': 'Pearl (metal 100, roughness 40, coat 16), Use solid color #1c3f7a', 'Trim': 'Satin Chrome on the lower band, Use source paint (spec only)'},
           'Deep pearl blue with a silver lower edge; gentle shimmer, nothing busy.')],
        [D('The 60-30-10 rule', 'About 60 percent one dominant colour, 30 percent an accent and 10 percent trim looks designed. Five colours look cheap. White or black as the quiet colour lets the accent carry the look.'),
         D('Finish choice sets the mood', 'Gloss (roughness 30, coat 16) is crisp and traditional. Satin (roughness 95, coat 70) is modern and forgiving. Pearl (metal 100, roughness 40, coat 16) adds soft light. Avoid heavy flake or holographic effects when the goal is calm.'),
         D('Alignment is the polish', 'Lines that continue across panels (side band into bumper, hood stripe over roof and trunk) read as one design. A stripe that breaks at a seam reads amateur.')],
        [Q('How do I make it look clean?', 'Cut it down to two colours and one stripe, use gloss or satin, and align every line.'),
         Q('What colours look classy?', 'White with red, near-black with gold, navy with white, or silver with one deep accent.'),
         Q('It looks too busy, what do I remove?', 'Remove the pattern layers first, then any third colour, then extra stripes.'),
         Q('Gloss or satin for classy?', 'Either. Gloss is traditional, satin is modern. Do not mix both on the same body area.')],
        [M('Looks cheap', 'Too many colours or a loud texture on a big area', 'Reduce to two colours plus trim and remove the pattern.'),
         M('Stripes do not line up', 'Zones drawn separately on the flat sheet', 'Check both sides and each panel on the CAR view; use mirror copies.'),
         M('Flat and boring', 'Everything one finish and one colour', 'Make the stripe a different shine from the body.')],
        ['A fine line (thin box) reads more expensive than a fat stripe.', 'Satin black with a chrome hairline is the safest premium combination.'],
        ['clean and classy', 'classy', 'make it classy', 'clean look', 'clean livery', 'simple and clean', 'simple livery', 'elegant', 'make it elegant', 'minimal', 'minimalist', 'tasteful', 'understated', 'sophisticated', 'refined look', 'less busy', 'too busy', 'simplify my design', 'timeless look', 'professional look'],
        fin=['base::gloss', 'base::satin', 'base::f_pearl', 'base::f_satin_chrome'],
        related=['ideas.look_expensive', 'ideas.two_tone', 'ideas.monochrome', 'ideas.black_gold_luxury', 'recipes.two_tone'],
        combos=[('ideas.look_expensive', 'Clean and classy is the base of every expensive look.'), ('ideas.sponsor_friendly_bases', 'Calm bodies carry sponsors well.')],
        screens=['cat_foundation', 'spec_matte'], quick=True, extra_src=[LIV_DOC, PRO_DOC])

if todo('look_expensive'):
    art('look_expensive', 'Make it look expensive',
        'Expensive is depth and restraint: a deep candy or pearl on the big areas, a fine metal line, a limited palette and no cheap texture. Chrome is for accents, not the whole car.',
        'Buyers say "make it look expensive", "premium" or "high end". The tells are a deep wet colour (candy over metal), a soft pearl or satin, a hairline of real metal and a very short colour list. Cheap looks come from flat primaries, five colours and big chrome areas that show every flaw.',
        'intermediate',
        [S_ZONE,
         S_BASE % 'Candy (metal 200, roughness 15, coat 16)' + ' Set BASE COLOR to Use solid color and pick a deep colour: oxblood #5a0a14, midnight #0a1a3a or emerald #0b4a32. Set Color Depth to 65 or 100 for the deepest glaze.',
         'Add depth with a spec overlay: BASE > SPEC OVERLAYS, + ADD SPEC OVERLAY, choose Pearl Micro or Gold Flake, Strength 30 to 50. It changes shine only.',
         'Add one hairline of metal: draw a thin box along the beltline or lower edge, choose Satin Chrome (metal 250, roughness 45, coat 40) and BASE COLOR Use source paint (spec only).',
         'Keep numbers crisp white or gold on a clean door area.',
         S_CHECK + ' Candy should read low roughness and coat 16. ' + S_RENDER],
        [X('Oxblood candy with gold flake', 'Deep wet luxury',
           {'BASE': 'Foundation Bases shelf > Candy', 'BASE COLOR': 'Use solid color #5a0a14', 'Color Depth': '100', 'SPEC OVERLAY': 'Gold Flake, Strength 35', 'Trim': 'Satin Chrome hairline, Use source paint'},
           'Dark red glass with a gold shimmer when the sun hits.', 'spec_candy'),
         X('Midnight pearl with a silver line', 'Subtle and modern',
           {'BASE': 'Pearl, Use solid color #0a1a3a', 'SPEC OVERLAY': 'Pearl Micro, Strength 30', 'Line': 'Draw box thin band, Satin Chrome, Use source paint'},
           'Navy that shifts to soft violet-blue in light.', 'cat_foundation'),
         X('Black and gold from the catalogue', 'A ready-made luxury look',
           {'Base Material': 'Brass Night (search it)', 'BASE COLOR': "Use finish's own color", 'Check': 'About metal 199, roughness 38, coat 58'},
           'A dark brass finish that reads warm and aged-expensive.')],
        [D('Depth is the tell', 'Candy is a polished metal response (metal 200, roughness 15, coat 16) under a colour you choose, which is what gives that look-into-it depth. Colour Depth runs 0 (no tint), 15 (glaze), 65 (rich), 100 (deepest).'),
         D('Chrome goes small', 'Large mirror areas show every panel flaw and flare in the sim. A hairline or trim of chrome reads as jewellery; the whole car reads as a prop.'),
         D('Fewer colours', 'A limited palette (two or three plus an accent) is the single strongest expensive signal. Gold, silver or white as the one accent.')],
        [Q('How do I make my car look expensive?', 'Deep candy or pearl on the body, one fine metal line, two or three colours, no busy patterns.'),
         Q('Which colours look luxury?', 'Oxblood, midnight blue, emerald, black with gold, white pearl with silver.'),
         Q('Is chrome expensive looking?', 'As trim, yes. As the whole car it looks like a show prop and shows every flaw.'),
         Q('Candy over black looks black, why?', 'Candy tints what is under it; with a black ground there is nothing to glow. Use a brighter metallic ground or a lighter candy colour.')],
        [M('Candy looks black', 'Dark colour on a dark ground', 'Choose a richer, lighter candy colour and raise Color Depth only until it glows.'),
         M('Looks glittery and cheap', 'Flake strength too high', 'Keep overlays at 30 to 50 and Scale small.'),
         M('Gold looks yellow plastic', 'Flat gold colour on gloss', 'Use Satin Chrome with a gold source colour so it picks metal.')],
        ['Hairlines beat stripes: a one-pixel-feeling line along the beltline lifts the whole car.', 'Check the G ROUGH view: premium surfaces show smooth dark greens, not noisy ones.'],
        ['make it look expensive', 'expensive look', 'luxury look', 'make it luxurious', 'premium look', 'make it look premium', 'high end look', 'high end', 'looks cheap', 'make it look rich', 'upscale', 'boutique look', 'show quality', 'high class', 'bespoke', 'supercar look', 'looks like a million dollars'],
        fin=['base::f_candy', 'base::f_pearl', 'base::f_satin_chrome', 'monolithic::dkc_brass_night'], spc=['gold_flake', 'pearl_micro'],
        related=['ideas.clean_classy', 'ideas.black_gold_luxury', 'ideas.candy_lowrider', 'ideas.pearl_white', 'recipes.candy'],
        combos=[('ideas.clean_classy', 'Restraint plus depth is the whole recipe.'), ('ideas.chrome_show_car', 'The loud cousin: use chrome only if the buyer wants a show car.')],
        screens=['spec_candy', 'cat_money_shokk'], quick=True, extra_src=[POP_DOC, PRO_DOC])

if todo('look_fast'):
    art('look_fast', 'Make it look fast: direction, taper and low colour',
        'Speed reads from forward-pointing lines, tapered stripes, a darker lower body and sharp contrast at the nose. Soft, round, centred patterns slow the car down.',
        'Buyers say "make it look fast", "look quick" or "sense of speed". A car looks fast when lines lead the eye forward, shapes taper toward the rear, the lower body is dark so the car looks planted, and the nose carries the strongest contrast. A static car cannot move, but it can point.',
        'intermediate',
        [S_ZONE,
         'Set the body calm: ' + S_BASE % 'Gloss (metal 0, roughness 30, coat 16)' + ' with a solid colour.',
         'Add speed lines: ' + S_BOX + ' Open PATTERN and choose Chevron, Lightning or Pinstripe, set Paint mode to Blend, Rotation so the lines run front to back, and Scale (pattern) to 0.5.',
         'Darken the lower body in its own zone (a Draw box along the rocker) with Matte and a deep colour, so the car looks lower and planted.',
         'Put the strongest contrast at the nose: a bright hood stripe or splitter colour, fading toward the rear.',
         S_CHECK + ' ' + S_RENDER],
        [X('Forward chevrons on a white car', 'Arrow the car forward',
           {'Body': 'Gloss, Use solid color #f2f2f2', 'PATTERN': 'Chevron, Paint mode Blend, Scale (pattern) 0.5', 'Pattern zone': 'Draw box on the front half of each side', 'Rocker': 'Matte, Use solid color #1a1c20'},
           'Arrow shapes that point at the nose and a dark rocker.', 'cat_signal'),
         X('Pinstripe taper', 'Quiet speed',
           {'Body': 'Satin, Use solid color #0d0d10', 'PATTERN': 'Pinstripe, Paint mode Blend, Scale (pattern) 0.4', 'Stripe colour': 'Use solid color #e8e8ea'},
           'Fine lengthwise lines that stretch the car.', 'spec_matte'),
         X('Lightning on the sides', 'Loud and fast',
           {'Body': 'Candy, Use solid color #0a3fd0', 'PATTERN': 'Lightning, Paint mode Blend, Scale (pattern) 0.4', 'Placement': 'Draw box on the doors only'},
           'Bolts that streak toward the rear on a deep blue candy.')],
        [D('What the eye reads as speed', 'Lines that run lengthwise, shapes that narrow to the rear, and a visual weight low on the car. Centred circles, flowers and swirls read static.'),
         D('Keep patterns fine', 'Whole-car patterns at Scale (pattern) 1.0 look like big stickers. Between 0.4 and 0.6 they read as streaks.'),
         D('Contrast at the nose', 'Strong contrast near the front pulls the eye toward the direction of travel.')],
        [Q('How do I make the car look fast?', 'Forward-pointing lines or chevrons, a dark lower body and the strongest contrast at the nose.'),
         Q('Do stripes make a car look faster?', 'Lengthwise stripes do; vertical or round shapes do not.'),
         Q('Does the finish matter?', 'Gloss or candy looks quicker than a flat primary; matte gives a stealthier speed.'),
         Q('Can I add motion blur?', 'Not as a real effect, but fine tapered streaks with a speed-line pattern at small scale are the nearest honest look.')],
        [M('Looks like stickers', 'Pattern scale too large', 'Lower Scale (pattern) to about 0.5.'),
         M('Stripes sit crooked', 'Pattern rotation not matched to the car direction', 'Rotate the pattern so lines run front to back and check on the CAR view.'),
         M('The pattern hits the numbers', 'Zone covers the door centre', 'Restrict the box to the front quarter and rear quarter.')],
        ['A dark rocker makes the whole body look lower, which reads faster.', 'Use the same direction on both sides: the left and right panels are mirrored on the flat sheet.'],
        ['make it look fast', 'look fast', 'fast looking', 'looks quick', 'look quick', 'sense of speed', 'speed look', 'give it a sense of speed', 'look like it is moving', 'looks fast standing still', 'dynamic look', 'sporty look', 'make it look speedy', 'speedy', 'looks quick sitting still'],
        fin=['base::gloss', 'base::satin', 'base::matte', 'base::f_candy'], pat=['chevron', 'lightning', 'pinstripe'],
        related=['ideas.speed_lines_motion', 'ideas.racing_stripes', 'ideas.aggressive_mean', 'ideas.fade_gradient'],
        combos=[('ideas.speed_lines_motion', 'The pattern side of the same idea.'), ('ideas.racing_stripes', 'Classic lengthwise stripes.')],
        screens=['cat_signal', 'pair_base_scale'], extra_src=[LIV_DOC])

if todo('stand_out_in_pack'):
    art('stand_out_in_pack', 'Stand out in a pack: be seen from far away',
        'To be found in a field of 40 cars, use a colour nobody else has, a bold two-colour split and one bright accent, and avoid mid-tones that blend into the track and sky.',
        'Cars at distance are a few pixels wide. Colour and value decide recognition, not detail. Pick a hue that is rare on track (hot pink, cyan, lime, orange on white), use big blocks instead of fine texture, and make the roof and hood readable from the chase camera.',
        'beginner',
        ['Choose a colour pair that is rare on track and strongly different in value: black with hot pink, white with orange, dark blue with lime.',
         S_ZONE,
         S_BASE % 'Gloss (metal 0, roughness 30, coat 16)' + ' for the dominant colour with Use solid color.',
         'Make the roof and hood a big block of the second colour: ' + S_BOX,
         'Put the contrast on the nose and roof, because the chase camera and overhead views see those most.',
         'Check small: zoom out until the car is a few pixels. If you can still tell it from the others, it works. ' + S_RENDER],
        [X('Black with pink roof and hood', 'Unmistakable at distance',
           {'Body': 'Gloss, Use solid color #0d0d10', 'Roof and hood zone': 'Draw box, Gloss, Use solid color #ff2bd6', 'Number plate area': 'Keep white on black'},
           'A black car with a pink cap that pops from the chase camera.', 'cat_neon_underground'),
         X('White with orange split', 'High-value split',
           {'Body': 'Gloss, #f4f4f4', 'Lower half zone': 'Draw box on the lower side, Gloss, #ff6a00'},
           'A clean split that reads from any angle.', 'cat_signal'),
         X('Colour-shift nose', 'Different every look',
           {'Body': 'Matte, Use solid color #101216', 'Nose': 'Search Chameleon Fire on a zone box over the hood'},
           'A dark car with a hood that changes with angle.')],
        [D('Distance is value, not detail', 'At pack distance fine detail averages to grey mud. What survives is large blocks with a strong light-versus-dark split and a hue that does not match its neighbours.'),
         D('Rare hues beat bright hues', 'Red and blue are the commonest on track. Hot pink, cyan, lime and orange on white are rare, so they get noticed first.'),
         D('Roof and hood', 'The chase camera and overhead views show the roof and hood most; give them the loudest block.')],
        [Q('How do I make my car easier to spot?', 'A rare hue, a two-colour split with strong light and dark, big blocks.'),
         Q('Does chrome help me stand out?', 'Chrome flashes in sun but turns dark in shade; a bright colour is more reliable.'),
         Q('Should I use a pattern?', 'Only a bold, big one. Fine patterns vanish at distance.'),
         Q('What if my sponsor colours clash?', 'Keep their logos on their own layer and put the loud block on the roof and hood.')],
        [M('Blends in with the track', 'Mid-tone grey or brown with fine texture', 'Switch to a strong value split and a rare hue.'),
         M('Pretty up close, invisible far away', 'Detail-based design', 'Zoom out in the preview and simplify until it reads.'),
         M('Neon looks dirty', 'Flake or noisy pattern over a bright colour', 'Use a clean gloss and no overlay.')],
        ['Test at one fifth size; if the car is one blob of two clear colours you are done.', 'Avoid colours that match the asphalt (mid-grey) and the sky (pale blue).'],
        ['stand out in a pack', 'stand out on track', 'stand out from the field', 'be seen', 'easy to spot', 'visible in traffic', 'make my car stand out', 'get noticed', 'unique look', 'not blend in', 'blend in less', 'recognizable', 'recognisable car', 'spot my car', 'spot my car easily', 'different from everyone else', 'make it unique', 'look different'],
        fin=['base::gloss', 'base::matte', 'monolithic::chameleon_fire'],
        related=['ideas.make_it_pop', 'ideas.high_vis', 'ideas.neon_night', 'ideas.readable_on_tv'],
        combos=[('ideas.high_vis', 'Highest visibility colours.'), ('ideas.readable_on_tv', 'The same distance test for numbers.')],
        screens=['cat_neon_underground', 'cat_signal'], extra_src=[POP_DOC])

if todo('readable_on_tv'):
    art('readable_on_tv', 'Readable on TV: numbers and sponsors that survive distance',
        'Put strong light-on-dark or dark-on-light contrast behind every number and logo, keep the door centre calm, and avoid sparkle, chameleon or busy pattern directly behind them.',
        'iRacing is seen at speed and at distance. Numbers and sponsors need a clear value split from whatever sits behind them. This is the discipline that makes a design usable: the number plate area is quiet, and the loud finishes live on other panels.',
        'beginner',
        ['Decide the number area first: the door centre is where the number lives (roughly 0.30 to 0.65 of the side height, front 22 percent being the fender).',
         'Make a calm base behind it: ' + S_ZONE,
         S_BASE % 'Gloss (metal 0, roughness 30, coat 16) or Satin (metal 0, roughness 95, coat 70)' + ' with a flat solid colour.',
         'Put loud effects (flake, chrome, candy, patterns) on the hood, roof, lower body and bumpers, never on the number area. Use RESTRICT TO LAYERS so the numbers and sponsors layers stay untouched.',
         'Check contrast: white on dark or black on light. If your number is mid-grey on mid-grey, change the plate colour, not the number.',
         'Zoom out in the preview until the car is tiny and read the number. ' + S_RENDER],
        [X('Dark body, white plate area', 'A number that reads at a glance',
           {'Body': 'Satin, Use solid color #101216', 'Number panel zone': 'Draw box over the door centre, Gloss, Use solid color #f2f2f2', 'Number colour': '#101216'},
           'A clean white plate on the dark door with a black number.', 'ui_zone_apply_area'),
         X('Loud hood, quiet doors', 'Pop without hurting legibility',
           {'Hood zone': 'Draw box, Candy, Use solid color #0a3fd0', 'Doors': 'Matte, Use solid color #f2f2f2', 'RESTRICT TO LAYERS': 'Car Paint'},
           'The hood explodes while the doors stay readable.', 'cat_foundation'),
         X('Fix a busy design', 'Rescue an unreadable number',
           {'Problem': 'Chrome flake behind the number', 'Fix': 'Add a zone over the door centre, Gloss, solid colour, ABOVE the flake zone'},
           'The flake stays everywhere else; the number now has a quiet background.')],
        [D('Value contrast, not hue', 'The camera is not colour-picky; it needs lighter-versus-darker. Red on blue can vibrate and still be unreadable because both are mid-value.'),
         D('Why effects hurt', 'Sparkle, chameleon and pattern change brightness every few pixels, which breaks the edges of letters. A flat finish keeps the edges sharp.'),
         D('Layers protect your art', 'On a layered template, a body zone limited to Car Paint leaves the numbers and sponsors layers exactly as they are.')],
        [Q('Why can nobody read my number?', 'Mid-value on mid-value, or an effect behind it. Add a flat plate colour with strong light-dark contrast.'),
         Q('Can I use chrome behind the number?', 'Better not; chrome flips light and dark with the sky.'),
         Q('Where does the number go?', 'The door centre, around 0.30 to 0.65 of the side height.'),
         Q('Do sponsors need the same?', 'Yes, give logos a clean background; a calm base carries them.')],
        [M('Number vanishes in sunlight', 'Reflective finish behind it', 'Use gloss or satin with a flat colour.'),
         M('A new zone repainted my numbers', 'Zone not restricted to the body layer', 'Tick Car Paint under RESTRICT TO LAYERS.'),
         M('Looks fine up close only', 'Detail based', 'Zoom out and test at tiny size.')],
        ['Black outline on a white number lifts it off any ground.',],
        ['readable on tv', 'tv readable', 'broadcast readable', 'show up on tv', 'visible on broadcast', 'readable at speed', 'readable from far', 'readable from a distance', 'numbers hard to read', 'cant read my number', 'legible numbers', 'number contrast', 'numbers readable', 'distance readability', 'make numbers stand out', 'sponsor readability'],
        fin=['base::gloss', 'base::satin', 'base::matte', 'base::f_candy'],
        related=['ideas.numbers_match_body', 'ideas.sponsor_friendly_bases', 'recipes.change_body_keep_numbers', 'ideas.stand_out_in_pack'],
        combos=[('ideas.numbers_match_body', 'Matching the number to the body without losing contrast.'), ('ideas.sponsor_friendly_bases', 'Calm bases for logos.')],
        screens=['ui_zone_apply_area', 'cat_foundation'], quick=True, extra_src=[doc(DOC_DESIGN, 'Readability first'), LIV_DOC])

if todo('stealth_murdered_out'):
    art('stealth_murdered_out', 'Stealth and murdered-out: black on black',
        'Murdered-out is flat black on every surface with only a whisper of shine difference. Use Flat Black or Matte for the body, a satin trim and a near-black pattern so detail shows only in the sun.',
        'A stealth look wants no colour at all: matte black body, black wheels, black trim. The art is in the subtle shine differences (flat against satin against a gloss hairline) so the shape still reads in the sim.',
        'beginner',
        [S_ZONE,
         S_BASE % 'Flat Black (metal 0, roughness 250, coat 255) for the deadest body, or Matte (metal 0, roughness 200, coat 160)' + ' and set BASE COLOR to Use solid color #0a0a0c.',
         'Add a hidden layer of detail: a second zone over the lower body or hood with Satin (metal 0, roughness 95, coat 70) in #0d0d10. In the sim the satin catches light while the flat stays dead.',
         'Optional pattern: open PATTERN, choose Carbon Fiber or Hex Carbon, Paint mode Blend, low Opacity (about 15 to 25), Scale (pattern) 0.5. It shows only in sunlight.',
         'Keep numbers and sponsors readable: leave them on their own layer or use a pale grey number (#e8e8ea).',
         S_CHECK + ' Matte reads bright in G ROUGH and B COAT should not be at 16. ' + S_RENDER],
        [X('Deadest flat black', 'No reflections at all',
           {'RESTRICT TO LAYERS': 'Car Paint', 'BASE': 'Foundation Bases shelf > Flat Black', 'BASE COLOR': 'Use solid color #0a0a0c'},
           'A dead flat car with no visible highlights.', 'spec_matte'),
         X('Black with satin ghost panels', 'Murdered-out with shape',
           {'Body': 'Matte, #0a0a0c', 'Panels zone': 'Draw box on hood and roof, Satin, Use solid color #0d0d10', 'Trim zone': 'Gloss hairline, #050506'},
           'Flat body with satin hood and roof that shows the shape only in the light.', 'cat_dark_city'),
         X('Stealth carbon', 'Hidden weave',
           {'Body': 'Flat Black, #0a0a0c', 'PATTERN': 'Carbon Fiber, Paint mode Blend, Opacity 20, Scale (pattern) 0.5'},
           'From a distance pure black; in the sun a fine weave appears.', 'spec_carbon')],
        [D('Flat is a spec, not a colour', 'Flat Black is metal 0, roughness 250, coat 255, the deadest foundation; Matte is roughness 200, coat 160; Satin is roughness 95, coat 70. A dark body made of all three levels reads as black from far and shows form up close.'),
         D('Colour stays near black', 'Pure #000000 on a flat finish looks like a hole. A very dark grey (#0a0a0c to #1a1c20) keeps edges and creases visible.'),
         D('Quiet textures', 'A low-opacity carbon or hex pattern adds depth without breaking the stealth. Use Blend mode so the pattern keeps the dark base.')],
        [Q('How do I do a murdered-out car?', 'Flat Black or Matte body, very dark grey colour, satin panels, no accents.'),
         Q('Will it look too flat?', 'Add satin hood and roof panels or a subtle carbon pattern so shape shows in the sun.'),
         Q('Can I keep my sponsors?', 'Yes, limit the zone to Car Paint, or keep logos pale grey.'),
         Q('Black or very dark grey?', 'Very dark grey like #0a0a0c, so edges stay readable.')],
        [M('It looks like a hole', 'Pure black on a flat finish', 'Use #0a0a0c to #1a1c20.'),
         M('The black is shiny', 'Zone finish is Gloss or Candy', 'Choose Flat Black or Matte; check B COAT is not at 16.'),
         M('Pattern too visible', 'Opacity too high', 'Drop Opacity to 15 to 25.')],
        ['A one-pixel gloss hairline along the beltline shows the shape in the sun.', 'Use Flat Black only where you want nothing; keep Matte for areas that should read a little shape.'],
        ['stealth', 'stealth look', 'stealth mode', 'stealth bomber look', 'spy plane', 'ninja look', 'black on black', 'blacked out', 'all black everything', 'dark stealth', 'dead flat black', 'no shine', 'ghost black', 'shadow car'],
        fin=['base::flat_black', 'base::matte', 'base::satin', 'base::gloss', 'base::tac_blackout_curtain'], pat=['carbon_fiber', 'hex_carbon'],
        related=['recipes.matte_black', 'ideas.aggressive_mean', 'ideas.camo_ghost_blackout', 'ideas.satin_modern_oem', 'ideas.carbon_race_bare'],
        combos=[('recipes.matte_black', 'The step-by-step version of flat black.'), ('ideas.camo_ghost_blackout', 'Ghost camo is the stealth cousin with pattern.')],
        screens=['spec_matte', 'cat_dark_city'], quick=True, extra_src=[PRO_DOC])
