// A/B every proposed painter-vocabulary entry on its OWN example ask: top 6 without vs with the expansion.  Only asks whose top 6 CHANGE go to the picture judge.
//   node scripts/ai_atlas/vocab_ab.js build      -> _easy_claude_work/gold/results_vocabA.json / results_vocabB.json  (+ vocab_cases.json)
//   python scripts/ai_atlas/gold_judge.py vocabA vocabB
//   node scripts/ai_atlas/vocab_ab.js decide     -> js/spb-lexicon-ext.js  (accepted entries)  + _easy_claude_work/gold/vocab_decisions.json
const vm = require('vm'), fs = require('fs'), path = require('path');
const ROOT = path.join(__dirname, '..', '..'); const w = { console, atob: s => Buffer.from(s, 'base64').toString('binary') }; vm.createContext(w); w.window = w; w.document = {};
function run(f) { vm.runInContext(fs.readFileSync(path.join(ROOT, f), 'utf8'), w, { filename: f }); }
run('js/spb-ai-atlas-data.js'); run('js/spb-ai-atlas.js'); run('js/spb-ai-cards-data.js'); run('js/spb-lsa-data.js'); run('js/spb-ai-cards.js'); run('js/spb-pro-rank.js');
w.SpbAIAtlas._install(w.SPB_ATLAS_DATA); w.SpbAICards._install(w.SPB_CARDS_DATA);
const R = w.SpbProRank, C = w.SpbAICards, GOLD = path.join(ROOT, '_easy_claude_work', 'gold');
const props = JSON.parse(fs.readFileSync(path.join(ROOT, '_codex_work/finish_intel/l4_vocab/lexicon_proposals.json'), 'utf8'));
const mode = process.argv[2] || 'build';
function entryFor(p) { const term = p.term.toLowerCase().replace(/\s+/g, ' ').trim(), exp = (p.expands_to || []).join(' '); return (/[\s\-]/.test(term)) ? { words: {}, phrases: { [term]: exp, [term.replace(/-/g, ' ')]: exp } } : { words: { [term]: exp }, phrases: {} }; }
if (mode === 'build') {
  const A = [], B = [], cases = [];
  props.forEach((p, i) => {
    const ask = p.example_ask; C.setLexExt({}); const ka = R.search(ask, { limit: 6 }).map(r => r.key);
    C.setLexExt(entryFor(p)); const kb = R.search(ask, { limit: 6 }).map(r => r.key); C.setLexExt({});
    const same = ka.join('|') === kb.join('|');
    cases.push({ i, term: p.term, ask, changed: !same });
    if (!same) { A.push({ ask: '[' + i + '] ' + ask, cat: p.term, keys: ka }); B.push({ ask: '[' + i + '] ' + ask, cat: p.term, keys: kb }); }
  });
  fs.writeFileSync(path.join(GOLD, 'results_vocabA.json'), JSON.stringify(A)); fs.writeFileSync(path.join(GOLD, 'results_vocabB.json'), JSON.stringify(B)); fs.writeFileSync(path.join(GOLD, 'vocab_cases.json'), JSON.stringify(cases));
  console.log('proposals', props.length, '| top 6 changed for', A.length, '| unchanged', props.length - A.length);
} else {
  const ja = JSON.parse(fs.readFileSync(path.join(GOLD, 'judged_vocabA.json'), 'utf8')), jb = JSON.parse(fs.readFileSync(path.join(GOLD, 'judged_vocabB.json'), 'utf8'));
  const cases = JSON.parse(fs.readFileSync(path.join(GOLD, 'vocab_cases.json'), 'utf8')), dec = [], mean = r => r && r.scores && r.scores.length ? r.scores.reduce((a, b) => a + b, 0) / r.scores.length : null;
  const byI = {}; ja.forEach((r, k) => { const m = /^\[(\d+)\]/.exec(r.ask); if (m) byI[+m[1]] = { a: mean(r), b: mean(jb[k]) }; });
  const words = {}, phrases = {}; let acc = 0, rej = 0, same = 0;
  cases.forEach(c => {
    const p = props[c.i]; let verdict = 'same';
    if (c.changed) { const x = byI[c.i]; verdict = (x && x.a != null && x.b != null && x.b >= x.a + 0.25 && (p.false_match_risk !== 'high' || x.b >= x.a + 0.5)) ? 'accept' : 'reject'; dec.push({ term: p.term, a: x && x.a, b: x && x.b, verdict }); }
    if (verdict === 'accept') { const e = entryFor(p); Object.assign(words, e.words); Object.assign(phrases, e.phrases); acc++; } else if (verdict === 'reject') rej++; else same++;
  });
  fs.writeFileSync(path.join(GOLD, 'vocab_decisions.json'), JSON.stringify(dec, null, 1));
  const js = '/* generated by scripts/ai_atlas/vocab_ab.js (do not edit): painter vocabulary that measurably improved results on the picture judge */\nwindow.SPB_LEX_EXT = ' + JSON.stringify({ words, phrases }) + ';\n';
  fs.writeFileSync(path.join(ROOT, 'js', 'spb-lexicon-ext.js'), js);
  console.log('accepted', acc, '(words', Object.keys(words).length, ', phrases', Object.keys(phrases).length, ') | rejected', rej, '| no change', same, '| js bytes', js.length);
}
