import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from enc_write_C import A, C, F

E = 'ai_copilot'
P = 'ai_copilot'

# ------------------------------------------------------------------ chat / helper articles (moved here from the hidden easy_mode domain, 2026-10-04)
A(E, 'chat_mode', 'Chat mode: tell Shokker what you want',
  'CHAT opens a studio with the helper on the left and a big live preview on the right. Say what you want in plain words and the car changes, with Undo for every step.',
  'Chat is the easy front door to the same booth. It works on the same paint, zones and spec as PRO, so nothing is a second copy. The helper on the left builds on what is on the car, and the car on the right updates as it goes. Tabs show the Paint, the Shine (spec) or the Car parts Shokker knows. A view strip under the car mirrors the Full Editor views, and a layer bar on the right lets you lock the helper to one layer. Every step is saved under Versions, and Compare slides between before and after. It works with no key at all: the built-in helper has a guided builder, a design library of 74 themes, and Surprise me. An AI key or Claude through MCP adds free-form chat.',
  ['You would rather describe the look than set sliders.',
   'You want four quick design ideas to react to.',
   'You are editing a finished livery ("make the black matte").'],
  ['Load your template or paint, then click CHAT in the mode switch (or the AI button, bottom right).',
   'Type what you want, for example "make the hood matte black", "retro red white and blue stripes", or "numbers gold chrome", and press Enter.',
   'Look at the preview. Press Undo under that answer if it is not right, or Another take for a different idea.',
   'Press Surprise me for four complete ideas tried on your car, or Colours from a picture to design in a logo\'s colours.',
   'Press Render & save when you like it, or Full editor to continue in PRO.'],
  [C('Surprise me', 'button', '', 'Four complete designs for your car; tap the one you like.', 'ai.panel'),
   C('Colours from a picture', 'button', '', 'Reads the three strongest colours of a logo, photo or flag and designs in them.', 'ai.panel'),
   C('Compare', 'button', '', 'A slider between before and after.', 'ai.panel'),
   C('Versions', 'filmstrip', '', 'Every step is saved; click one to go back.', 'ai.panel'),
   C('Lock to layer', 'chip', 'off', 'Limits the helper to one layer, so a request such as "make it red" changes only that layer.', 'ai.panel')],
  ['Be as specific as you like about the part: "the rear half of the left side" works once the car\'s parts are known.',
   'Chat never touches numbers, sponsors or logos unless you name them.',
   'Say "undo" to take back the last step, or "start over" to begin again.'],
  ['Chat changes zones and layer settings only. It does not open files, import a paint, save or export; do those in PRO.',
   'If the helper says it does not know the car, show it the parts once (see the car parts articles).'],
  ['ai_copilot.offline_vs_ai', 'ai_copilot.edit_existing', 'ai_copilot.picking_colours_in_words', 'cars.teach_parts', 'workflows.pro_chat_easy'],
  [F('control', 'ai.panel'), F('control', 'ai.input')], [], ['ai.fab', 'ai.input', 'ai.undo', 'ai.another', 'hdi.use_chat'],
  ['paint-booth-v2.html:1923-1932', 'js/spb-chat-studio.js:3-8', 'js/spb-chat-studio.js:31-45', 'js/spb-pro-ai.js:3594-3608', 'scripts/ai_atlas/ui_map.json:13778'],
  quick=True,
  aliases=['chat mode', 'chat studio', 'talk to shokker', 'ai panel', 'the copilot', 'copilot', 'surprise me', 'compare slider', 'versions', 'lock to layer', 'full editor'],
  )

A(E, 'offline_vs_ai', 'Offline helper, AI key or Claude: what each does',
  'The built-in helper is free and works offline as a guided builder. For free-form chat, add a key (DeepSeek through OpenRouter) or connect Claude or ChatGPT through MCP.',
  'There are three ways to talk to Shokker. 1. The built-in helper needs no key and no internet. It is a guided builder: you choose what to change (a colour found on the car, a named part, a layer, numbers or sponsors, the whole car), then what to do (recolour, add a finish, add a pattern, change the shine) and which look, picked from real catalogue thumbnails, with Run and Undo. If you type a sentence, it pre-fills the builder with what it understood and asks about the rest. Known words in your text are highlighted and open a short card from the Encyclopedia. 2. Free chat with the AI key: the Ask DeepSeek instead button sends the same text to the model chosen in the gear (DeepSeek v4.1 Flash is recommended, about a half cent per request). 3. MCP: connect Claude or ChatGPT/Codex on your own plan and talk to them; they drive the booth. Every AI change has an Undo, and numbers, sponsors and logos are not touched unless you name them.',
  ['You are deciding whether you need an AI key.',
   'The built-in helper did not understand a sentence and you want to know what to do.'],
  ['Start with the built-in helper. Type the request, check how it read it, and press Run.',
   'If it cannot understand part of it, an open step with choices shows; pick one, or press Ask DeepSeek instead.',
   'For open-ended chat, add an OpenRouter key in the Chat gear (see the key article), or connect Claude or ChatGPT (see the MCP article).',
   'Press Undo under any answer to take it back.'],
  [C('Ask DeepSeek instead', 'button', '', 'Sends the same text to the online model chosen in the gear. Needs a key.', 'ai.panel')],
  ['Most buyers never need a key; the builder, the 74 themes and Surprise me work free.',
   'The built-in helper never guesses: what it cannot read becomes an open question with choices.'],
  ['The online model costs a little per request and is capped per day; the built-in helper costs nothing.',
   'An outside assistant (Claude or ChatGPT) and the in-app copilot should not both edit at once; use Take over in SPB to switch.'],
  ['ai_copilot.gear_key_model', 'ai_copilot.mcp_claude_chatgpt', 'ai_copilot.what_ai_sees', 'ai_copilot.chat_mode', 'ai_copilot.picking_colours_in_words'],
  [], [], ['hdi.ai_key', 'hdi.use_claude_mcp', 'hdi.use_chatgpt'],
  ['js/spb-offline-builder.js:1-14', 'docs/ai_knowledge/04_limits_and_app_map.md:25-30', 'js/spb-ai-core.js:131-137', 'scripts/ai_atlas/ui_map.json:13949'],
  aliases=['offline helper', 'guided builder', 'do i need an ai key', 'free vs paid', 'ask deepseek instead', 'three ways to talk', 'works without a key', 'without internet', 'built in designer'],
  )

A(E, 'edit_existing', 'Changing what is already on the car',
  'Most people start from a finished livery. Tell Shokker "make the black matte" or "numbers purple metallic" and it finds that colour on the car and changes only that.',
  'Shokker reads the real colours in your paint (not the template\'s dead space), so "the black", "all the red" or "the dark blue" point at pixels that are actually there. It then changes only those: a look alone (matte, satin, chrome, powder coat, wet look) changes the shine and keeps your colour; a new colour repaints exactly those pixels; both together do both. Words such as "a bit glossier" or "darker" are understood too. If you name a colour that is not on the car (say pink when the car has red), it asks rather than guessing. A second request on the same colour edits the zone it made, so changes stack instead of resetting. Numbers, sponsors and logos are changed only when you name them.',
  ['You loaded a finished paint and want to change one colour or a look.',
   'You want a matte or satin version of a livery.',
   'You want numbers or stripes a different colour.'],
  ['Load the finished paint (PSD with layers is best, or a flat TGA).',
   'In Chat type for example "make the black matte", "numbers purple and metallic", "everything that is white, make it satin", or "powder coat the yellow".',
   'Check how it read the request in the builder, then press Run.',
   'Not right? Press Undo under that answer. Say "a bit more" or "do the same for the roof" to keep going.'],
  [],
  ['A look word alone (matte, satin, chrome) keeps your colours exactly; it changes only the shine. Add a colour word to change the colour too.',
   'Say "except the numbers" or "but leave the numbers alone" to protect them.'],
  ['On a flat paint (no layers), numbers, sponsors and stripes are not known; Shokker asks you to show them first.',
   '"Red matte" may include a dark-red tail-light lens because it matches by colour.'],
  ['ai_copilot.chat_mode', 'ai_copilot.what_ai_sees', 'recipes.edit_one_thing', 'recipes.matte_black', 'support.numbers_vanished'],
  [], [], [],
  ['docs/EDIT_EXISTING_HELPER.md:1-35', 'docs/EDIT_EXISTING_HELPER.md:48-58'],
  quick=True,
  aliases=['change what is on the car', 'make the black matte', 'recolour existing', 'edit a finished livery', 'make the numbers purple', 'powder coat the yellow', 'change one colour'],
  )

# ------------------------------------------------------------------ ai_copilot
A(P, 'picking_colours_in_words', 'Picking colours and looks in plain words',
  'Chat understands everyday colour words, hex codes, parts, "the black on the hood", slang like "powder coat", and even "same shade as the hood".',
  'You do not need a painter\'s vocabulary. The helper reads colour words (including shades such as powder blue or charcoal), hex codes, and phrases such as "all the red", "the dark blue" or "the black on the hood". It maps spoken looks to real catalogue finishes: powder coat, plasti dip, cerakote, matte, satin, gloss, wet look, chrome, satin chrome, dark chrome, metallic, pearl, candy and more. Compound sentences ("make the hood and the roof powder coat, then the stripes gold") are split into steps. If a word is ambiguous it asks with buttons instead of guessing.',
  ['You are not sure how to name a colour or a look.',
   'You want to be precise about which part or colour changes.'],
  ['Type the request in plain words, or use a hex code like #ff7eb6.',
   'To match a colour on your car say "same shade as the hood".',
   'Name a part or a colour on the car: "the roof", "all the red", "the black on the hood".',
   'Answer any question it asks by clicking a button.'],
  [],
  ['Add a look and a colour in one go: "matte metallic purple on the left side".',
   '"A bit glossier" or "darker" nudges what is there rather than replacing it.'],
  ['Colour names are read by family; "pink" on a car with only red will be asked about, not forced.',
   'Spelling mistakes in common words are understood, but made-up looks are asked about.'],
  ['ai_copilot.edit_existing', 'ai_copilot.chat_mode', 'zones.named_parts', 'recipes.candy'],
  [], [], [],
  ['docs/EDIT_EXISTING_HELPER.md:12-20', 'docs/EDIT_EXISTING_HELPER.md:24-26', 'js/spb-pro-ai.js:3594-3608'],
  aliases=['colour words', 'color words', 'hex codes in chat', 'same shade as', 'plain words', 'how to name a colour', 'plasti dip', 'cerakote', 'wet look', 'powder coat'],
  )

A(P, 'gear_key_model', 'The AI gear: key, model and daily cap',
  'In the Chat gear you paste an OpenRouter key and use one model (DeepSeek v4.1 Flash is recommended). A daily spending cap stops runaway costs.',
  'The gear (cog) in the AI panel is where you add an online key. Paste your OpenRouter key and press Save; it is stored on this computer, encrypted for your Windows account. The Model line shows the one model the helper will use. DeepSeek v4.1 Flash is recommended: it is the cheapest that works well, around half a cent per request. If you pick a different model the gear warns that it usually costs more and offers Use the recommended model. The Daily cap (default $2 per day) is checked before every request, and Test connection and Check credit are there too. The When switch chooses Auto (AI only when the built-in helper is not sure), Always, or Off. A private option runs a model on your own PC through Ollama or LM Studio. A key is optional.',
  ['You want free-form chat, not just the built-in builder.',
   'You want to control how much you spend.',
   'The helper says the daily cap has been reached.'],
  ['Open the AI panel and click the gear.',
   'Get a key at openrouter.ai/keys, add a few dollars of credit, and paste it in the Key line. Press Save.',
   'Leave the Model on the recommended one.',
   'Set the Daily cap you are comfortable with, and keep When on Auto.',
   'Press Test connection to check it.'],
  [C('Key', 'text (hidden)', '', 'Your OpenRouter key, kept on this computer.', 'ai.gear'),
   C('Model', 'one model', 'deepseek/deepseek-v4.1-flash', 'The only model the helper uses. The studio shows it but has no second picker.', 'ai.gear'),
   C('Daily cap', '$0.05 to $500 per day', '$2.00', 'Stops requests once the day\'s spend passes the cap. Raise it in the gear to continue.', 'ai.gear'),
   C('When', 'Auto | Always | Off', 'Auto', 'Auto uses the AI only when the built-in helper is not sure.', 'ai.gear')],
  ['Set a spending limit on the key at OpenRouter as well.',
   'You never need a key to use the built-in helper, Surprise me or the 74 themes.'],
  ['Do not paste your key in chat or into support messages.',
   'A higher-priced model costs more per request. The gear shows a warning when you are on one.',
   'Without a key, picture-based finish naming and the open-ended AI answers are unavailable.'],
  ['ai_copilot.offline_vs_ai', 'ai_copilot.what_ai_sees', 'ai_copilot.mcp_claude_chatgpt', 'settings.overview'],
  [F('control', 'ai.gear')], [], ['ai.gear', 'hdi.ai_key', 'hdi.ai_limits'],
  ['js/spb-ai-core.js:121-146', 'server_routes/ai_copilot_routes.py:9', 'server_routes/ai_copilot_routes.py:358', 'server_routes/ai_copilot_routes.py:487-489', 'scripts/ai_atlas/ui_map.json:13949'],
  quick=True,
  aliases=['openrouter key', 'api key', 'deepseek', 'copilot model', 'daily cap', 'spending cap', 'ai cost', 'ai gear', 'add an ai key', 'ollama', 'local model'],
  )

A(P, 'mcp_claude_chatgpt', 'Using Claude or ChatGPT through MCP',
  'Connect Claude Desktop or ChatGPT/Codex on your own plan and ask them to design your livery. No key is needed in Shokker and every change shows in the AI panel with Undo.',
  'MCP is a way for an outside assistant to drive the booth. In the AI gear, switch on the control option (Let an AI assistant control Shokker Paint Booth), then press Install in Claude Desktop and restart Claude Desktop. With Shokker open, ask Claude for example: Using Shokker Paint Booth, give me a Gulf-style livery. For ChatGPT or Codex, open the bridge settings, choose Connect ChatGPT / Codex, review it, press Add SPB to Codex settings, restart Codex and sign in with ChatGPT. Your own plan limits apply. The assistant sees the same car knowledge, finishes (about 4,800) and named parts as the in-app helper, and changes the same zones. Only one assistant should edit at a time: use Take over in SPB before asking the in-app helper while an outside assistant has control.',
  ['You already pay for Claude or ChatGPT and want to use that.',
   'You want the smartest free-form designing without an OpenRouter key.'],
  ['Open the AI panel > gear and switch on the control option.',
   'Press Install in Claude Desktop, then restart Claude Desktop (or use the Codex steps above).',
   'Keep Shokker open and ask the assistant what you want.',
   'Watch the AI panel: each change appears with an Undo button.'],
  [C('Control option', 'on / off', 'off', 'Lets Claude or ChatGPT/Codex control the booth. Off means no outside access.', 'mcp.claude'),
   C('Connect ChatGPT / Codex', 'bridge settings', '', 'Adds Shokker to Codex settings; restart Codex and sign in.', 'mcp.chatgpt'),
   C('Take over in SPB', 'button', '', 'Gets editing back for the in-app helper when an outside assistant has control.', 'ai.gear')],
  ['Ask for a whole livery at once ("a Gulf style livery") and then refine.',
   'Shine-only requests ("only the chrome, keep my colours") use foundation finishes that leave your paint untouched.'],
  ['Changes by an outside assistant can appear while you are working; Undo takes them back.',
   'Only the page that is open and connected receives the changes, so close extra Shokker windows you are not using.'],
  ['ai_copilot.offline_vs_ai', 'ai_copilot.gear_key_model', 'ai_copilot.what_ai_sees'],
  [F('control', 'mcp.claude'), F('control', 'mcp.chatgpt')], [], ['mcp.claude', 'mcp.chatgpt', 'hdi.use_claude_mcp', 'hdi.use_chatgpt'],
  ['scripts/ai_atlas/ui_map.json:13914-13950', 'docs/ai_knowledge/04_limits_and_app_map.md:19-33', 'js/spb-pro-ai.js:2790'],
  quick=True,
  aliases=['mcp', 'claude desktop', 'chatgpt', 'codex', 'use claude', 'use my claude plan', 'let ai control shokker', 'take over in spb', 'bridge settings', 'install in claude desktop'],
  )

A(P, 'what_ai_sees', 'What the helper can see and what it never touches',
  'The helper reads your zones, the colours actually on your paint and a preview picture. It does not change numbers, sponsors or logos unless you name them, and cannot save, export or delete.',
  'To help, the helper reads your zones, your layers, the real colours in your paint (with how much of the car each covers), and the preview. The online model can also look at a picture of your paint when it needs to, such as to name a finish from a photo or check its own result; only the provider you chose sees it. The built-in helper does none of that online. What it will do: change zones and layer settings, set finishes and colours, aim at named parts. What it will not do: delete zones, open or save files, import a paint, export to iRacing, change your car folder or User ID, draw by hand or add text. Numbers, sponsors and logos are left alone unless you name them, and Chat\'s whole-car looks stay in the body paint layers. Every change has Undo.',
  ['You are worried the helper will change your numbers or sponsors.',
   'You want to know what leaves your computer.'],
  ['To change numbers on purpose, name them: "make the numbers gold chrome".',
   'After a change, check the preview; press Undo under the answer if you do not like it.',
   'If you do not want pictures sent out, use the built-in helper only, or skip the key.'],
  [],
  ['The helper tells you what it changed and what it assumed. Read that line.',
   'To lock work to one layer, use Lock to layer in the Chat studio.'],
  ['The online model sees your requests and, when needed, a picture of your paint. That is why a key is optional.',
   'Do not expect it to save or export; use PRO\'s Render for that.'],
  ['ai_copilot.edit_existing', 'ai_copilot.gear_key_model', 'support.numbers_vanished', 'ai_copilot.chat_mode'],
  [], [], ['hdi.ai_limits'],
  ['docs/ai_knowledge/04_limits_and_app_map.md:3-12', 'js/spb-pro-ai.js:3623-3626', 'js/spb-pro-ai.js:3594-3608', 'docs/EDIT_EXISTING_HELPER.md:1-6'],
  quick=True,
  aliases=['what can the ai see', 'will it change my numbers', 'what the ai cannot do', 'ai limits', 'privacy', 'numbers sponsors untouched', 'is my paint sent online'],
  )

A(P, 'car_learning', 'How the helper learns your car',
  'Known cars are recognised from the sheet layout and the car folder. A car that is new to Shokker is taught once, remembered on your computer, and confirmed before use.',
  'The helper climbs a ladder when you ask for "the hood". First it looks for a match in the shipped car library, by sheet layout or iRacing car folder. If the sheet is at least 78% like a known car, it proposes that car\'s layout fitted to your sheet and waits for one click; it never applies a look-alike silently. If nothing is close, it shows your sheet and asks you to draw each part. Everything you confirm or teach is stored on this computer and recognised next time, including other paints of the same car. If your paint has lost its template dead space, the helper can still recognise many cars from where panel edges fall, but treats that as a proposal to confirm.',
  ['Chat asks you to show it the parts.',
   'You want to know why it recognises some cars without asking.'],
  ['Ask Chat for something on a part.',
   'If it proposes a car ("looks like..."), press Yes only if it is right.',
   'If it asks, draw a box round each part once.',
   'Next time it recognises the car by itself.'],
  [],
  ['Teach only the parts you need; you can add more later.'],
  ['A wrong Yes teaches a wrong map; use the gear to load or save a corrected car map.'],
  ['cars.teach_parts', 'cars.supported_cars', 'cars.reading_sheet'],
  [], [], [],
  ['docs/CAR_LEARNING.md:5-9', 'docs/CAR_LEARNING.md:11-13', 'js/spb-pro-carmap.js:372-386'],
  aliases=['car learning', 'how it learns', 'it remembers my car', 'recognises my car', 'look alike layout'],
  )
print('ok')
