import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from enc_write_C import A, C, F

D = 'cars'

A(D, 'supported_cars', 'Which cars Shokker knows (the car library)',
  'Shokker ships hand-checked part layouts for 31 iRacing templates and 7 draft cars: hood, roof, sides, bumpers and more, so Chat can aim at a named part.',
  'The car library lists 38 entries. 31 are checked layouts for stock cars (NASCAR Cup Gen 4, Gen 6 and Next Gen, ARCA, Class B and Xfinity, Late Model and Super Late Model, Street Stock, Mini Stock), trucks (Silverado, F-150), and a Dirt Late Model. Seven more (dirt mod, dirt sprint winged, legends, pro trucks, SK modified, and similar) are drafts: Shokker may suggest their layout, but asks you to confirm it before using it. For a known car, Chat and the AI helper already know where the hood, roof, left and right sides, front and rear bumper, trunk and spoiler are. A car that is not on the list still works: you teach the parts once and Shokker remembers them. The library is about named parts only; any template still opens and renders.',
  ['You want to know if your car is on the list, so Chat can say "the hood" without asking.',
   'Before teaching a car, to check whether it is already known.'],
  ['Open your car\'s template (PSD, XCF or ORA) and set the iRacing Car Folder.',
   'Open Chat and ask for something on a part, such as "make the roof black".',
   'If the car is known, the helper says it recognises it and aims the zone. If not, it asks you to show the parts once.',
   'Look at the preview to confirm the zone is on the right panel.'],
  [],
  ['The car folder name and the shape of the paintable area on the sheet are both used to recognise a car. If one is missing, the other is still tried.',
   'If the helper says it recognises a "draft" car, check the preview and confirm; it is a proposal until you say yes.'],
  ['Being in the library does not mean the template is special: the render, the files and the colours work the same for every car.',
   'A sheet that looks like a known car (78% or more) is only proposed, never applied silently, because two cars can share a similar layout.'],
  ['cars.teach_parts', 'cars.reading_sheet', 'cars.choose_template', 'zones.named_parts'],
  [], [],
  ['car.nascar-gen6-camaro', 'car.chevy-silverado-truck', 'car.dirt-late-model', 'car.f150-2019', 'car.mini-stock', 'car.street-stock-casino', 'car.super-late-model'],
  ['js/spb-car-atlas-data.js:1', 'js/spb-pro-carmap.js:372-386', 'docs/CAR_LEARNING.md:5-9'],
  quick=True,
  aliases=['supported cars', 'which cars', 'car library', 'is my car supported', 'car list', 'car atlas', 'known cars', 'my car is not on the list', 'does it work with my car'],
  )

A(D, 'reading_sheet', 'Reading the flat sheet: which panel is which',
  'The paint is one 2048 square picture of the whole car cut open. Knowing the usual layout tells you where the hood, sides, roof and bumpers sit.',
  'On a typical iRacing stock-car sheet the long upper band is the right side and the long lower band is the left side. Across the middle run the trunk, roof and hood. The front bumper is at the top left, the rear bumper next to it, and the spoiler is far right. Small strips (rockers, splitters, mirrors) and wheels fill the gaps. One side panel may be drawn upside down, so up on the sheet is not up on the car. Cars like trucks, dirt cars and sprint cars arrange panels differently, so do not assume the stock-car pattern. The template\'s Wire layer outlines each panel and its Mask layer shows what is paintable.',
  ['You are placing a zone by hand and need to know which part of the sheet to draw on.',
   'A stripe looks upside down or backwards on the car.',
   'You want to check that Chat picked the right panel.'],
  ['Turn on the template\'s Wire layer to see each panel outline (and turn it off again before you render).',
   'For a stock car: right side = the upper long band, left side = the lower band, hood / roof / trunk across the middle, bumpers top left, spoiler far right.',
   'Use the Car parts tab in Chat to see the parts Shokker knows drawn over your sheet.',
   'Check the front and up directions for side panels: some sheets run a side from the rear to the front, or flip it.'],
  [],
  ['This layout is a convention that held for 13 measured stock-car families; trucks and dirt cars differ, so check the Car parts view.',
   'When a stripe runs the wrong way, the panel direction is the reason, not the paint. Mirror or flip the placement.'],
  ['Do not rely on a picture-reading AI to name panels. Measured on real sheets, vision models name them wrongly most of the time. Shokker takes names from the library or from what you teach.',
   'Wire, Mask and Car_Mandatory layers must be off when you render.'],
  ['cars.teach_parts', 'cars.safe_areas', 'ui_shell.template_layer_views', 'tools.mirror_symmetry', 'workflows.one_flat_sheet'],
  [], [], [],
  ['docs/CAR_LEARNING.md:29-31', 'docs/ai_knowledge/06_layers_panels_and_export.md:7-8', 'js/spb-pro-carmap.js:9-12'],
  aliases=['read the sheet', 'which panel is which', 'upside down side', 'where is the hood on the sheet', 'uv sheet', 'sheet layout', 'which side is left', 'front bumper top left'],
  )

A(D, 'teach_parts', 'Teaching Shokker where the parts are',
  'When Shokker does not know your car, it asks you once to show the hood, roof, sides and so on, and remembers them for every paint on that car.',
  'If you ask Chat for something on a part (say, "make the roof black") and the car is not in the library, Shokker shows your sheet and asks. You tap the panel or draw a box around it, one part at a time, and tell it which part it is. You can also confirm a guess ("Yes, that is right") or say the paint has none ("There are none on this paint") for things like numbers. The answer is remembered for this car layout, so another paint of the same car is recognised next time. In the Chat gear you can also copy, save or load a car map. If your sheet looks at least 78% like a known car, Shokker proposes that car\'s boxes fitted to your sheet and waits for one click.',
  ['Chat says it does not know your car.',
   'A part is aimed at the wrong panel and you want to fix the map.',
   'You are working on a car that is not in the library.'],
  ['Open Chat and ask for something on a part, for example "make the roof black".',
   'When it shows your sheet, draw a box around ONE part (not several) and say which part it is.',
   'Repeat for any other part you will use, or let it ask again when needed.',
   'To fix a mistake, open the Chat gear, load or save a car map, or teach the part again.'],
  [C('Yes, that is right', 'button', '', 'Confirms the app\'s guess of a part (or a proposed car) and remembers it.', 'ai.panel'),
   C('No, I will show you', 'button', '', 'Lets you draw a box around the real part.', 'ai.panel')],
  ['Draw tight around one single part. A box around two parts teaches the wrong thing.',
   'For numbers, draw around ONE number, not the whole panel; Shokker finds the rest.'],
  ['What you teach is stored on this computer. It is not sent to other users.',
   'Parts are named, not guessed from a picture; if you skip teaching, the helper will keep asking.'],
  ['cars.supported_cars', 'cars.reading_sheet', 'zones.named_parts', 'ai_copilot.car_learning'],
  [F('control', 'ai.panel')], [], ['hdi.teach_parts', 'hdi.teach_numbers'],
  ['scripts/ai_atlas/ui_map.json:12532-12560', 'docs/CAR_LEARNING.md:5-9', 'js/spb-pro-carmap.js:489-496'],
  quick=True,
  aliases=['teach the parts', 'teach shokker my car', 'show shokker where the hood is', 'draw the parts', 'car map', 'it does not know my car', 'learned cars', 'remembers my car'],
  )

A(D, 'choose_template', 'Choosing the right template for your car',
  'Open the template made for the SAME car you drive in iRacing. A template for another car paints the wrong places.',
  'Each iRacing car has its own paint template with its own layout. Shokker needs that car\'s template (PSD, XCF or ORA) or a finished paint of that car to work on. Use the car menu in the iRacing Car Folder section so the files land in the right folder. Do not resize the picture: iRacing accepts only 2048 by 2048 or 1024 by 1024 and ignores any other size, showing your paint-shop colours instead. Shokker renders at the template\'s own size.',
  ['You are starting a new car.',
   'Your paint shows in iRacing on the wrong parts, or not at all.'],
  ['Download the paint template for your car from iRacing (or your trusted source).',
   'In Shokker click the PSD/XCF/ORA button next to Source Paint and open it; use the TGA/PNG/JPEG button for a flat paint.',
   'Set the iRacing Car Folder to your car\'s folder using the car menu.',
   'Check the preview: the panels should look like your car\'s sheet, with the Wire layer showing the outlines.'],
  [],
  ['A twin folder (same layout for two cars) still needs the right folder name, because that is the folder iRacing reads from.',
   'If you only have a finished paint (no template), open it as a flat TGA; layers will not exist.'],
  ['Do not open another car\'s template to "borrow" its look; the panels will not match.',
   'Do not resize the canvas.'],
  ['layers.open_psd', 'ui_shell.car_folder', 'support.tiny_or_huge', 'workflows.loading_paint'],
  [], [], [],
  ['js/spb-support-answers.js:16', 'js/spb-support-answers.js:62-63'],
  aliases=['which template', 'choose a template', 'wrong template', 'template for my car', 'download a template', 'get the template', 'use another cars template'],
  )

A(D, 'safe_areas', 'Safe areas: what is car and what is dead space',
  'Only part of the sheet is actual car. Paint outside the paintable area never reaches the car, and some blocks are reserved for number and sponsor stamps.',
  'The 2048 square sheet contains the car\'s panels and a lot of dead space between them. The template\'s Mask layer marks which is which: transparent is paintable, opaque is dead space. Shokker uses the same idea to decide where a whole-car look may go. The dead space on templates is a brown tone, which the app uses to find the car shape. Guide layers (Wire, Mask, Car_Mandatory and the group Turn Off Before Exporting TGA) show you the panels and reserved stamp blocks but are not paint; they must be off when you render or lines will appear on the car. For a car that gets stamped numbers and sponsors, keep the stamp blocks clear if you want the sim to place them.',
  ['A stripe or logo stops at an invisible edge.',
   'You see template lines or blocks on the car in iRacing.',
   'You wonder where it is safe to put artwork.'],
  ['Show the Mask and Wire views to see the paintable area (see the template layer views).',
   'Keep artwork inside the transparent area of the Mask; anything outside is thrown away.',
   'Before rendering, turn off Wire, Mask, Car_Mandatory and the Turn Off Before Exporting TGA group.',
   'Render and check the Car view.'],
  [],
  ['Chat\'s whole-car looks stay inside the body paint layers, so numbers, sponsors and logos are untouched unless you ask.'],
  ['Wire and Mask visible at render time print lines on the car.',
   'iRacing wants a 24-bit TGA. A TGA that carries an alpha channel from the template can make parts disappear or turn black, so re-export as 24-bit if you export by hand.'],
  ['layers.paintable_area', 'layers.wire_mask_mandatory', 'layers.turn_off_before_export', 'cars.reading_sheet', 'support.numbers_vanished'],
  [], [], [],
  ['docs/ai_knowledge/06_layers_panels_and_export.md:8', 'docs/CAR_LEARNING.md:29', 'js/spb-support-answers.js:40', 'js/spb-support-answers.js:66'],
  aliases=['safe area', 'safe areas', 'dead space', 'paintable area', 'outside the mask', 'what area can i paint', 'reserved blocks', 'sponsor blocks'],
  )
print('ok')
