import sys, json
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from enc_write_C import A, C, F

ROOT = Path(__file__).resolve().parents[3]
_INV = [r['id'] for r in json.loads((ROOT / 'scripts' / 'ai_atlas' / 'enc_inventory.json').read_text(encoding='utf-8'))['records']]


def I(*prefixes):
    """Resolve inventory ids by unique prefix, so a typo in a long id fails loudly."""
    out = []
    for p in prefixes:
        m = [i for i in _INV if i.startswith(p)]
        assert len(m) == 1, (p, m)
        out.append(m[0])
    return out


PB = 'playbook'
CN = 'concepts'
KB = 'docs/ai_knowledge/'

# ------------------------------------------------------------------ playbook: how a zone gets its colour
A(PB, 'colour_modes', 'Colour modes: what colour a finish paints',
  'A zone can keep your own paint colour, paint one solid colour, paint a gradient, or let the finish bring its own colour. Choosing the mode is the first decision for any zone.',
  'BASE COLOR is the dropdown that decides where a finish gets its colour. Use source paint keeps the car\'s own colour and changes only the shine, which is perfect for gloss, matte, satin, pearl or candy over an existing livery. Solid paints the whole zone one colour. Gradient blends 2 to 10 colours across the whole flat sheet in a direction. Finish colour lets chrome, carbon, holographic and similar finishes bring their own.',
  ['You are not sure whether to repaint or only change the shine.',
   'A finish changed the colour of your livery and you did not want that.'],
  ['Open the zone and look at BASE COLOR.',
   'Pick Use source paint when the colours must stay and only the shine changes.',
   'Pick a solid colour when the zone should be one new colour.',
   'Pick the custom gradient for a fade, then add the stops.',
   'Leave it on the finish\'s own colour when you want the chrome or carbon look itself.'],
  [C('BASE COLOR', 'dropdown', '', 'Where the finish takes its colour from.', 'zone.base_color_mode'),
   C('Solid colour', 'swatch', '', 'One flat colour for the whole zone.', 'zone.solid_color'),
   C('Custom gradient', '2 to 10 stops', '', 'A fade across the flat sheet in a direction.', 'zone.gradient')],
  ['A gradient runs across the entire flat sheet, so a horizontal fade follows the sheet columns, not the length of the car.'],
  ['A finish that brings its own colour replaces your colour. Use a coating base with source paint instead.'],
  ['recipes.three_colour_gradient', 'recipes.chrome_source', 'playbook.strengths_adjustments', 'zones.what_is_a_zone'],
  [F('control', 'zone.base_color_mode')], [],
  I('doc.01.colour_modes'),
  [KB + '01_how_pro_works.md:18-23'],
  quick=True,
  aliases=['colour modes', 'color modes', 'base color modes', 'use source paint', 'source paint mode', 'solid colour mode'])

A(PB, 'strengths_adjustments', 'Strengths and adjustments on a zone',
  'Four groups of sliders tune a zone: how strong it is overall, how much of the finish replaces your paint, how shiny or metal the spec is, and the colour tweaks hue, saturation and brightness.',
  'Intensity runs 0 to 100 and sets the overall strength of the zone. Base Strength runs 0 to 200 percent: 100 replaces your paint fully and lower values let more of the original show. Spec Strength runs 0 to 200 percent and scales the shine map. Hue (-180 to 180), Saturation (-100 to 100) and Brightness (-100 to 200) tweak the base colour. Scale and Rotation change the size and angle of the finish\'s own texture. The three spec sliders push metal, roughness and clearcoat up or down for the whole zone.',
  ['A finish is too strong, too weak, too coarse or the wrong tint.',
   'You want to nudge a finish instead of hunting for another one.'],
  ['Open the zone and change one slider at a time.',
   'For a weaker look lower Base Strength; for a shinier or flatter look use Spec Strength and the three spec sliders.',
   'For colour, use Hue, Saturation and Brightness.',
   'For size, use Base Scale (0.05 to 5, 1.00 is normal).',
   'Judge it in Render, since fine detail does not show well in the small preview.'],
  [C('Base Strength', '0 to 200%', '100%', 'How much of the finish replaces the original paint.', 'zone.base_strength'),
   C('Spec Strength', '0 to 200%', '100%', 'How strong the shine map is.', 'zone.spec_strength'),
   C('Base Scale', '0.05 to 5', '1.00', 'Size of the finish texture in this zone.', 'zone.base_scale'),
   C('Hue Shift', '-180 to 180', '0', 'Rotates every colour around the colour wheel.', 'zone.hue_shift'),
   C('Saturation', '-100 to 100', '0', 'How vivid or grey the colour is.', 'zone.saturation'),
   C('Brightness', '-100 to 200', '0', 'Lighter or darker.', 'zone.brightness')],
  ['The sliders in the popout show percentages; the saved value is the same number.',
   'Large spec slider moves can cancel the finish; pick a better finish instead.'],
  ['"Crushed down to 50 percent" means texture scale, not strength.'],
  ['playbook.hsb_sliders', 'playbook.buyer_words', 'support.tiny_or_huge', 'spec.strength_and_independent'],
  [F('control', 'zone.base_strength'), F('control', 'zone.base_scale')], [],
  I('doc.01.strengths_and_adjustments'),
  [KB + '01_how_pro_works.md:24-31'],
  quick=False,
  aliases=['strengths', 'adjustments', 'intensity', 'zone sliders', 'base strength spec strength'])

A(PB, 'hsb_sliders', 'Steer a finish\'s colour with hue, saturation and brightness',
  'Most finishes that bring their own palette can be steered with Hue, Saturation and Brightness on the zone, so you do not need to search for a different finish.',
  'If a finish is almost right, move the three colour sliders instead of changing finish. Too dark or navy: Brightness up 30 to 40. Leaning violet: Hue down about 15 toward sky blue. Grey looking tinted: Saturation down about 10. Flecks gone grey after darkening: Saturation up. One worked example took a blue-white glow finish with Brightness plus 35, Hue minus 15 and Saturation minus 10 to a light ice blue and steel grey with no gradient.',
  ['A finish is nearly right but the colour is off.',
   'You want a two-colour look without a gradient.'],
  ['Open the zone with the finish.',
   'Move Brightness first, then Hue, then Saturation, a little at a time.',
   'Check the preview after each move, then Render for the real result.',
   'If you cannot get there, try another finish and tune that one.'],
  [C('Hue Shift', '-180 to 180', '0', 'Rotates every colour around the wheel.', 'zone.hue_shift'),
   C('Saturation', '-100 to 100', '0', 'How vivid or grey.', 'zone.saturation'),
   C('Brightness', '-100 to 200', '0', 'Lighter or darker.', 'zone.brightness')],
  ['Small steps; the effect depends on the finish.'],
  ['Hue rotates every colour in the finish, not just one.'],
  ['playbook.strengths_adjustments', 'playbook.colour_modes'],
  [F('control', 'zone.hue_shift')], [],
  I('doc.09.playbook_adjust_a_finish_s_colour'),
  [KB + '09_field_playbook.md:24-26'],
  quick=True,
  aliases=['hue saturation brightness', 'hsb sliders', 'adjust finish colour', 'finish too dark', 'finish too purple'])

A(PB, 'gradients_and_flake', 'Gradients, and a touch of colour in black',
  'A gradient is laid over the whole flat sheet, so it will not line up from panel to panel. For a little colour coming into black, use a coloured flake or sparkle finish instead of a fade.',
  'Because the car is unwrapped, one fade does not continue from the side onto the bumper or the other side, and buyers notice. Use a gradient only for a deliberate whole-sheet effect, or give each panel its own zone and its own fade. A touch of colour in a dark area means sparkles or flecks of that colour, not a gradient. A deep-space flake finish does this: black with blue, purple and silver flake, steered to blue with Brightness about minus 45, Hue about minus 20 and Saturation about plus 60, gave roughly 55 percent pure black with blue flecks. Paint patterns cannot take a colour, so they do not do this job.',
  ['You want blue in the black without a fade.',
   'A gradient does not line up across the car.'],
  ['For a fade, use one zone per panel and give each its own gradient.',
   'For colour in black, choose a flake finish whose flecks are already the colour you want.',
   'Steer it with Brightness, Hue and Saturation on the zone.',
   'Add a spec pattern on top for texture without changing the colour.',
   'Check the result in Render at full size.'],
  [C('Custom gradient', '2 to 10 stops', '', 'A fade across the flat sheet.', 'zone.gradient')],
  ['Flake finishes keep their flecks readable when Saturation is raised after darkening.'],
  ['Patterns with strong opacity flood the area with the colour instead of sparkling.'],
  ['recipes.three_colour_gradient', 'playbook.hsb_sliders', 'recipes.flake_pearl'],
  [], [],
  I('doc.09.playbook_gradients_run_across', 'doc.09.playbook_a_touch_of_colour'),
  [KB + '09_field_playbook.md:18-23'],
  quick=False,
  aliases=['blue in the black', 'coloured flake in black', 'gradient does not line up', 'touch of colour'])

A(PB, 'buyer_words', 'What common buyer words mean in the app',
  'Everyday words such as crushed down to 50 percent, a touch of colour, the same shade and keep the strokes each have a precise meaning in the app: scale, sparkles, a sampled colour and a fill-only recolour.',
  'People describe changes in everyday words, and a few of them have a precise meaning here. Pattern size or crushed down means the zone\'s texture scale (0.05 to 5) and the spec pattern scale, not spec strength or overall intensity. A touch of colour in a dark area means flecks, not a fade. Only the yellow in the logo means pick that colour, with a tolerance, on that art\'s layer inside a small box. Same shade means sample the colour from the car instead of guessing a name. Keep the strokes means recolour only the fill colour with a tight tolerance and leave the outline colours alone. Starting from the base file means clean zones: reset them rather than undoing many steps.',
  ['You are describing a change to the helper or to support.',
   'A reply changed the wrong thing.'],
  ['For size use Base Scale or the pattern Scale; leave strength alone unless you mean strength.',
   'For a colour from the car use PICK COLOR FROM CAR.',
   'To recolour only a fill, keep Tolerance low.',
   'To begin from the base file, use Reset All Zones.'],
  [C('Base Scale', '0.05 to 5', '1.00', 'The size words map here.', 'zone.base_scale'),
   C('PICK COLOR FROM CAR', 'eyedropper', '', 'Samples the real colour.', 'zone.pick_color_from_car')],
  ['Words like thinner, bigger or smaller about a pattern are scale.'],
  ['Changing strength when you meant size makes the finish weaker, not smaller.'],
  ['playbook.strengths_adjustments', 'playbook.recolour_art_part', 'zones.tolerance', 'support.tiny_or_huge'],
  [], [],
  I('doc.09.playbook_buyer_words'),
  [KB + '09_field_playbook.md:12-14'],
  quick=False,
  aliases=['crushed down to', 'pattern smaller', 'same shade as', 'keep the strokes', 'buyer words'])

A(PB, 'recolour_art_part', 'Recolour only part of a piece of art',
  'To change just a number fill or one colour in a logo, make a zone limited to that art\'s layer, pick the exact fill colour and keep the tolerance tight so the outline survives.',
  'Use a zone limited to the Numbers layer and the fill colour. Sample the real fill first: dark fills are often close to a black outline, so keep the tolerance around 10 to 16. For a colour inside one logo, combine the colour with a small box around the logo and limit the layers to the decal layers. Without the layer limit the box also grabs body paint whose original colour matches. Then zoom the preview to confirm the outline and drop stroke survived.',
  ['You want a different number fill but the same outline.',
   'You want to recolour one colour of a logo.'],
  ['Add a zone and use PICK COLOR FROM CAR on the fill colour.',
   'Tick only the art\'s layer under RESTRICT TO LAYERS.',
   'Keep the tolerance low (about 10 to 16), and draw a small box around a logo if needed.',
   'Choose the new colour and finish, then zoom the preview to check the outline.'],
  [C('RESTRICT TO LAYERS', 'checkboxes', '', 'Keeps the zone on the art layer.', 'zone.restrict_layers'),
   C('Colour tolerance', 'slider', '', 'How close a colour must be to be taken.', 'zone.tolerance')],
  ['Check the zone\'s footprint shows only the art zone as the source of its pixels.'],
  ['A wide tolerance eats the outline.'],
  ['recipes.finish_on_numbers', 'zones.tolerance', 'zones.restrict_layers'],
  [F('control', 'zone.restrict_layers')], [],
  I('doc.09.playbook_recolour_only_part'),
  [KB + '09_field_playbook.md:15-17'],
  quick=True,
  aliases=['recolour number fill', 'logo colour only', 'change number colour keep outline'])

A(PB, 'session_start', 'Start of every design session',
  'Turn the template layers Wire, Mask and Car Mandatory off before judging the preview, read the zones, and make sure only one Shokker page is open.',
  'Template layers can be on by default to show the panels, and they draw grids, outlines and fake headlights over the preview you are judging. With Mask off, the empty space between panels shows the base colour: that is not on the car, and iRacing never shows it. Zone numbers move when zones are added on top, so read the zone list before editing and use names. If two different designs show on consecutive reads, two Shokker pages are open: close the other one first.',
  ['You start a new design on a layered template.',
   'The preview shows grids or outlines.'],
  ['Open the Layers tab and switch off Wire, Mask and Car Mandatory (the group named Turn Off Before Exporting).',
   'Read the zone list top to bottom before adding or changing anything.',
   'Close any second Shokker window or tab.',
   'Then make your changes and check each one in the preview.'],
  [],
  ['The template layers are for placing things; they are off for the final.'],
  ['The empty space between panels is not part of the car, whatever colour it shows.'],
  ['layers.turn_off_before_export', 'layers.wire_mask_mandatory', 'layers.paintable_area', 'zones.priority'],
  [], [],
  I('doc.09.playbook_start_of_every_design_session'),
  [KB + '09_field_playbook.md:9-11'],
  quick=True,
  aliases=['start of session', 'turn off wire mask', 'before you design', 'wire mask car mandatory off'])

A(PB, 'preview_cannot_show', 'Effects the preview cannot show',
  'The live preview is much smaller than the real 2048 paint, so fine sparkle, micro-flake and small-scale patterns average out. Candy, chrome and metal twists show in the spec views and in Render.',
  'Do not conclude a finish did nothing from the small picture. Zoom a crop, read the spec views, or Render. In the spec views red is metal, green is roughness and blue is clearcoat, where high means dull. In one test a holographic drift finish at a small scale looked flat green in the spec view, yet measured clearly metal against plain gloss. Candy, chrome and metal twists are invisible in the flat colour preview, so confirm them on the spec views.',
  ['A fine effect seems to have done nothing.',
   'You are judging sparkle or holographic shimmer.'],
  ['Open the spec views and look at R METAL, G ROUGH and B COAT.',
   'Zoom into a crop of the preview.',
   'Render and judge at full size.',
   'Compare with the plain gloss version of the same zone if unsure.'],
  [],
  ['The spec views tell you what iRacing will light, even when the colour picture looks the same.'],
  ['Do not remove a finish because the small picture looks flat.'],
  ['preview_render.preview_vs_render', 'ui_shell.preview_channel_views', 'spec.reading_by_colour', 'concepts.preview_vs_truth'],
  [], [],
  I('doc.09.playbook_checking_effects'),
  [KB + '09_field_playbook.md:30-32'],
  quick=True,
  aliases=['preview cannot show', 'fine effect invisible', 'sparkle not showing in preview'])

A(PB, 'things_to_avoid', 'Things that went wrong before: avoid them',
  'Do not undo many steps after resetting by hand, do not expect lightning on matte black to read as bolts, and remember the empty space between panels keeps the old colour.',
  'These are lessons from real sessions. Undoing many steps after you reset zones by hand can bring back an old state with dozens of zones; mute or edit back instead, or reset. The lightning paint pattern on matte black reads as grey cracked glass, not bolts, at any scale. The base colour of a scheme is limited to the paintable area, so once Mask is hidden, the empty space keeps the old colour; that is harmless in iRacing. The zone list does not show scale or spec strength, so if you set a value by hand keep it in mind before a helper overwrites it. On some cars a part such as the spoiler has no body paint pixels, so schemes skip it.',
  ['Something odd came back after an undo.',
   'A pattern looks wrong on black.'],
  ['To go back, mute the zone or edit it back instead of many undo steps.',
   'To start clean, press Reset All Zones.',
   'Try a different pattern on matte black than lightning.',
   'Check the car\'s parts article if a part seems to be skipped.'],
  [],
  [],
  ['Many undo steps after a manual reset can bring back an older state.'],
  ['recipes.undo_start_over', 'cars.safe_areas', 'layers.paintable_area'],
  [], [],
  I('doc.09.playbook_things_that_went_wrong'),
  [KB + '09_field_playbook.md:33-39'],
  quick=False,
  aliases=['things that went wrong', 'known problems to avoid', 'lightning on matte black'])

A(PB, 'artwork_reveal', 'Make artwork appear when light hits it',
  'Use two spec-only zones on the art with your picture left unchanged: matte on the whole art layer, then satin chrome on the art\'s light tones above it. The shape then flashes silver as the light sweeps.',
  'The picture never changes, only the shine map. The whole art layer gets a soft matte base so shadows absorb light. Above it, a second zone takes only the art\'s light tones (colours such as light grey, with a tolerance near 40) and gets a satin chrome. In the sim the light parts flash silver as the sun or track lights sweep, and the dark parts stay dead, so the shape appears out of the paint. Check the spec view: chrome should sit only on highlights, matte on shadows.',
  ['You want a face, mask or logo to light up on the track.',
   'You want a hidden image that shows only in the light.'],
  ['Add a zone limited to the art layer with a soft matte foundation finish and BASE COLOR on your own paint.',
   'Add a second zone above it, same layer, picking the light tones with a tolerance around 40, with a satin chrome foundation finish.',
   'Open the spec view: chrome (red) should sit on highlights only.',
   'Use mirror chrome instead of satin for a harder flash.'],
  [C('Use source paint', 'option', '', 'Keeps the picture exactly as it is.', 'zone.base_color_mode')],
  ['Check that the same layer does not also hold light text, which would get chrome too.'],
  ['The upper zone must be above the matte one, because the top zone wins.'],
  ['recipes.chrome_source', 'spec.paint_spec_marriage', 'zones.priority', 'playbook.spec_only_changes'],
  [], [],
  I('doc.09.playbook_make_artwork_reveal'),
  [KB + '09_field_playbook.md:40-41'],
  quick=False,
  aliases=['reveal artwork', 'light up logo in light', 'hidden image in the sun', 'artwork reveal'])

A(PB, 'spec_only_changes', 'Change only the shine and keep the paint exactly',
  'Use a Foundation finish with the base colour set to source paint. It changes the shine map and leaves the colour exactly as it is; ordinary chrome, metallic or candy bases repaint the car.',
  'Spec-only looks are the safest way to change shine on a finished livery. Foundation finishes (the ones named Foundation or starting with f) are made to do this. On real templates the paint changed 0 percent with Foundation finishes, and about 78 to 85 percent of a hood changed with ordinary chrome, metallic or candy. Looks: mirror chrome, satin chrome, dark chrome, polished metal, matte metal, pearl, satin pearl, candy, brushed metal, frosted, matte, satin and gloss. A finish that brings its own pattern can also be given a solid colour: you then keep the colour flat and get only its texture in the shine map.',
  ['You said "only the shine" or "keep my colours".',
   'You want numbers or sponsors to stay pixel for pixel.'],
  ['Add or open a zone that covers the area.',
   'Under BASE choose a Foundation finish for the look (for example Chrome (mirror) or Soft Matte).',
   'Set BASE COLOR to Use source paint.',
   'Compare the preview before and after: the colours should be identical.',
   'Refine with the three spec sliders if needed.'],
  [C('BASE COLOR', 'dropdown', '', 'Use source paint keeps the colours.', 'zone.base_color_mode'),
   C('Base Material', 'picker', '', 'Foundation Bases are the spec-only family.', 'zone.base_material')],
  ['When stacking a chrome fill over gloss decals, keep the special fill zone above the decal gloss zone.'],
  ['Never use the ordinary chrome, metallic or candy bases for spec-only work.'],
  ['recipes.chrome_source', 'spec.paint_spec_marriage', 'playbook.artwork_reveal', 'playbook.colour_modes'],
  [F('control', 'zone.base_material')], [],
  I('doc.08.spec_only_changes', 'doc.09.playbook_spec_only_looks'),
  [KB + '08_livery_design.md:21-23', KB + '09_field_playbook.md:27-29'],
  quick=True,
  aliases=['spec only', 'only the shine', 'keep my colours', 'change shine not colour', 'foundation finish source'])

# ------------------------------------------------------------------ playbook: livery design
A(PB, 'livery_parts', 'How a livery is built from parts',
  'A paint scheme is a base colour, one or two accents and a trim colour, laid on the car\'s named parts. Work part by part, not with boxes across the sheet.',
  'The car lies flat on the sheet: two side panels, hood, roof, trunk, front and rear bumper and spoiler. On a side panel, height is measured from the roof-line down to the rocker. 0.00 to 0.12 is the window edge; 0.10 to 0.25 the beltline, where a thin stripe separates body from glass; 0.30 to 0.65 the door centre where the number lives, so keep it calm; 0.64 to 0.70 a pinstripe above the lower band; 0.68 to 1.00 the lower body and rocker band, the classic place for the second colour. The front 22 percent of the length is the front fender and the rear 24 percent the rear quarter. Sides mirror each other, so one region can take both.',
  ['You are planning a livery from scratch.',
   'You are not sure where on the sheet a stripe should go.'],
  ['Decide the base colour, one accent and a trim colour.',
   'Place each by named part (left side, hood, roof), then by a band within it.',
   'Keep the door centre calm for the number.',
   'Put the second colour in the lower band, and mirror to the other side.',
   'Check the preview and fix anything off.'],
  [],
  ['The built-in design recipes already know these proportions; use them for any scheme or throwback.'],
  ['The outside assistants refuse very large boxes; name the part instead.'],
  ['cars.reading_sheet', 'zones.named_parts', 'playbook.scheme_families', 'playbook.composition_rules'],
  [], [],
  I('doc.08.how_a_livery_is_built', 'doc.08.where_things_go_on_a_side_panel'),
  [KB + '08_livery_design.md:3-8'],
  quick=False,
  aliases=['how a livery is built', 'where things go on a side', 'roof line to rocker', 'livery proportions'])

A(PB, 'scheme_families', 'Classic scheme families and era palettes',
  'Retro lower band, classic twin stripes, two-tone, colour block, bookends and stealth are the common families. Each era has its own palette of colours.',
  'Retro lower band: body colour, a bold lower band, a thin trim line above it, bumpers and spoiler in the band colour (Pepsi-style, Sunoco-style, Gulf-style). Classic twin stripes: two parallel stripes along the sides continuing as a centre stripe over hood, roof and trunk. Two-tone: second colour from the belt down plus hood and bumpers. Colour block: hood, roof and rear quarters in different colours. Bookends: contrasting front and rear ends with a quiet body. Stealth: dark on dark with one thin accent. Eras: 1960s to 70s powder blue and orange, navy and white, harvest orange, rust brown, mustard; 1970s to 80s red, white and blue with chrome trim, black and gold, blue and yellow; 1980s hot pink, cyan and purple on black or white; 1990s teal, purple and magenta splashes; modern is matte black with one accent, or white with one strong colour.',
  ['You want a throwback or a specific style.',
   'You need a palette for an era.'],
  ['Pick the family that matches the look you want.',
   'Pick the era palette.',
   'Lay the colours on the parts as in the parts article.',
   'Use the design recipes in Chat to lay a whole scheme in one go, then adjust.'],
  [],
  ['A twist on a retro scheme is one unexpected element: a candy or pearl panel, a flipped colour, a metallic roof.'],
  ['More than one twist makes the scheme look busy.'],
  ['playbook.livery_parts', 'playbook.composition_rules', 'recipes.retro_stripes', 'recipes.two_tone'],
  [], [],
  I('doc.08.classic_scheme_families', 'doc.08.era_palettes'),
  [KB + '08_livery_design.md:9-14'],
  quick=False,
  aliases=['scheme families', 'era palettes', 'gulf style', 'retro lower band', 'twin stripes', 'stealth livery'])

A(PB, 'composition_rules', 'What makes a scheme look professional',
  'Use one dominant colour (about 60 percent), one accent (about 30) and one trim (about 10). Keep the number calm, line the blocks up across the car and never paint over numbers or sponsors.',
  'White or black as the quiet colour lets the accents sing. The side band continues the bumper colour, and the hood stripe continues over the roof and trunk. Keep contrast between the number and its background, and do not run a busy stripe behind the numbers. Matte paint with chrome trim lines is the modern retro look; gloss everywhere is the showroom look. Finish choices: matte for flat paint, gloss for showroom, satin in between, chrome for trim lines (a chrome pinstripe on a matte car reads as real chrome), and metallic or candy blocks beside flat blocks create the pop through opposite colour and opposite shine.',
  ['A scheme looks amateur or crowded.',
   'You are choosing finishes for each part.'],
  ['Choose one dominant colour, one accent, one trim.',
   'Line up the bands across the car.',
   'Choose finishes: matte or satin for the body, chrome for trim, candy or metallic for one hero block.',
   'Check the number area has contrast.'],
  [],
  ['A chrome pinstripe on matte reads as real chrome.'],
  ['Never paint over numbers, sponsors or tape; use the body paint layers only.'],
  ['playbook.livery_parts', 'playbook.scheme_families', 'recipes.make_it_pop', 'recipes.two_tone'],
  [], [],
  I('doc.08.composition_rules', 'doc.08.finish_choices_for_schemes'),
  [KB + '08_livery_design.md:15-20'],
  quick=False,
  aliases=['composition rules', 'professional livery', '60 30 10', 'finish choices for schemes'])

A(PB, 'placement_wrong', 'The placement looks wrong: fix it by part and band',
  'Do not guess new coordinates. Name the part and its band, compare to what the zone really covers, and fix the part, portion or band.',
  'When a stripe or block is in the wrong place, say which part and band you mean, such as the lower third of the left side. Compare with the zone\'s covers text and its visible share, and change the part, portion or band. If a part of the car is not known, show it to Shokker once and it remembers. Say plainly which part you changed.',
  ['A stripe is too high, too low, or on the wrong side.',
   'The helper put something in the wrong place.'],
  ['Name the part and the band you want.',
   'Check what the zone covers in its card.',
   'Change the part, portion or band.',
   'If the part is unknown, show it once in the AI panel.'],
  [],
  [],
  ['Guessing coordinates makes it worse.'],
  ['cars.teach_parts', 'zones.named_parts', 'playbook.livery_parts'],
  [], [],
  I('doc.08.when_the_buyer_says_the_placement'),
  [KB + '08_livery_design.md:24-25'],
  quick=False,
  aliases=['placement is wrong', 'stripe in the wrong place', 'wrong part'])

# ------------------------------------------------------------------ playbook: Smart Separate status
A(PB, 'smart_separate_status', 'Smart Separate and Auto-build layers: status in this build',
  'Smart Separate finds numbers, sponsors, logos and the car template on a flat paint and builds layers from them. In this customer build its scripts are not loaded, so the Auto-build layers button does not appear.',
  'The idea is for a flat paint with no layers: the app works out what is a number, a sponsor, a logo, the fixed car template and the base paint, then builds real layers so you can restrict a zone to them. A text-reading engine finds numbers and sponsor words, and a stored template for about 67 known cars helps. It was judged not reliable enough to ship, so the page does not load it. Spec Sculpt has its own related Auto-Separate for protecting decals. For layers today use a layered file.',
  ['A guide mentions Auto-build layers.',
   'You have a flat paint and want the numbers separate.'],
  ['Use a layered PSD template when you want real layers.',
   'In Spec Sculpt use Auto-Separate to protect decals while you sculpt the shine.',
   'On a flat paint, select numbers by their colour with a zone, and give the zone a medium tolerance.',
   'Check the result in the preview.'],
  [],
  [],
  ['Do not expect a Smart Separate button in the main window.'],
  ['spec_sculpt.smart_separate', 'layers.open_psd', 'recipes.finish_on_numbers', 'cars.supported_cars'],
  [], [],
  I('wiki.smart_separate.1_', 'wiki.smart_separate.4_'),
  ['SPB_WIKI.html:4806-4860', 'paint-booth-v2.html:4721-4725'],
  quick=False,
  aliases=['smart separate', 'auto build layers', 'separate numbers and sponsors', 'auto layers'])

# ------------------------------------------------------------------ concepts (wiki lessons in plain words)
A(CN, 'green_is_not_good', 'A good score is not the same as a good look',
  'Shokker\'s own checks can say a finish is fine when it looks poor. Always judge a finish at full size on the car with your own eyes; the eye wins over a number.',
  'Every finish is checked by scripts for sameness, size of detail and spec. These checks are necessary but not enough: a check that cannot see a flaw will certify it, and a score can reward the wrong thing, such as big blobby detail when the house rule is fine detail. A wall of green ticks has also hidden a sheet of confetti. The rule is to look at every finish at 1:1, and when a score and your eye disagree, the eye wins.',
  ['You are choosing a finish and want to trust your eyes.',
   'You wonder why a finish with a good rating looks wrong.'],
  ['Open the finish on your car in Render and look at it at full size.',
   'Zoom into a patch, not just the whole car.',
   'Compare with a plain gloss version if unsure.',
   'Go with what looks right.'],
  [],
  ['Fine detail of 8 to 32 pixels over the whole sheet is the target look.'],
  ['Do not trust a rating over your own eye.'],
  ['concepts.what_makes_a_finish_good', 'concepts.preview_vs_truth', 'preview_render.preview_vs_render'],
  [], [],
  I('wiki.lessons.traps_of_the_it_s_green'),
  ['SPB_WIKI.html:540-559'],
  quick=False,
  aliases=['green check', 'ratings and scores', 'trust your eyes', 'score vs look'])

A(CN, 'nothing_changed', 'When a change seems to do nothing',
  'Most often the picture is stale, a zone above is covering the area, or an older copy of the app is running. Check those before assuming the change was wrong.',
  'The app shows files that it caches, and the preview can lag, so a correct change can be invisible. Another cause is that a finish exists in the engine but is not listed in the picker, or that a restart or update is pending. Work through them in order: press F5 to refresh the preview, check the zone is not muted or covered by a zone above, and check you are on the latest version.',
  ['You changed something and the car looks the same.',
   'A finish you read about is not in the picker.'],
  ['Press F5 to refresh the preview.',
   'Check the zone is not muted and not covered by a zone above.',
   'Check the update banner and restart the app.',
   'If it is still wrong, send a problem report.'],
  [],
  [],
  ['A different finish in the picker than on a friend\'s computer usually means an older version.'],
  ['support.zone_no_show', 'zones.not_showing', 'workflows.install_update', 'support.reporting_problem'],
  [], [],
  I('wiki.lessons.traps_of_the_my_change'),
  ['SPB_WIKI.html:560-583'],
  quick=True,
  aliases=['change did nothing', 'nothing changed', 'no effect', 'stale preview'])

A(CN, 'preview_vs_truth', 'The preview can look fine and still not be the result',
  'The live preview is smaller than the final paint, so size-based effects can look different, and a preview does not prove the saved file is right. Check the Render and the sim.',
  'The preview draws smaller than the final 2048 paint, so patterns drawn in fixed pixel sizes can look bigger or smaller than they will. A placement that looks right in the preview is not a guarantee for the saved result: judge the saved file. Rendering at both sizes matters, since some problems only appear at one. Fine effects can also average out and look flat in the preview.',
  ['The render differs from the preview.',
   'A pattern looks bigger or smaller in the preview.'],
  ['Make your last check in Render at full size.',
   'Look at the spec views.',
   'Check the result in iRacing with Ctrl+R after a render.',
   'Report differences with your project attached.'],
  [],
  [],
  ['The preview is a design aid; the saved file is the product.'],
  ['preview_render.preview_vs_render', 'support.preview_render_mismatch', 'playbook.preview_cannot_show'],
  [], [],
  I('wiki.lessons.traps_of_the_the_preview'),
  ['SPB_WIKI.html:584-602'],
  quick=False,
  aliases=['preview vs result', 'preview looked fine', 'preview different from render'])

A(CN, 'reporting_with_evidence', 'Reporting a problem so it can be fixed',
  'Change one thing at a time, keep the project, and send the real settings rather than a description. A fix starts from your actual file.',
  'Problems are found by reproducing them from the real settings of a real render, changing one field at a time, and reading the actual values rather than quoting remembered numbers. For you this means: send the diagnostics from Report a Problem, add your car and number mode, and say which single change made it happen. In one past case the cause turned out to be one value applied twice, which was found only by sweeping one field at a time.',
  ['You found a bug.',
   'Support asked what you changed.'],
  ['Go back to the last good state and change one thing.',
   'Save your project.',
   'Press Report a Problem in the Settings gear and paste the report.',
   'Add what you see in the sim, your User ID and number mode.'],
  [],
  [],
  ['A screenshot alone rarely shows the cause.'],
  ['support.reporting_problem', 'workflows.user_id_and_folder', 'ui_shell.save_open_projects'],
  [], [],
  I('wiki.lessons.traps_of_the_reasoning'),
  ['SPB_WIKI.html:603-624'],
  quick=False,
  aliases=['report a bug', 'reproduce a problem', 'one change at a time'])

A(CN, 'what_makes_a_finish_good', 'What makes a finish good',
  'A good finish is a fine-grained field across the whole car, not a poster. Each collection has one idea, hidden details are small and turned, and the shine map follows the paint.',
  'Finishes are fields: 8 to 32 pixel micro-texture across the whole sheet, never a big picture. Each collection should have one arc instead of a grid of colour times pattern, which feels samey. Hidden features should be small (70 to 225 pixels) and turned and mirrored so they do not read as decals. Physics-only ideas read boring or like confetti; effects that fire in the sim have mostly dark cells with a few strong colour states. The shine map should be composed against the rendered paint so the two work together. Spec decks that come in two families, rise and fall in roughness, or drift toward one colour are faults.',
  ['You are choosing between finishes.',
   'You wonder why the catalogue is arranged by idea.'],
  ['Look for fine detail across the whole car, not one big shape.',
   'Check the spec views: the shine map should follow the paint.',
   'Prefer collections that feel like a story over colour swaps.',
   'Trust your eye at full size.'],
  [],
  [],
  ['A colour swap of an existing finish is not a new finish.'],
  ['concepts.green_is_not_good', 'finishes.what_makes_a_finish_pop', 'spec.paint_spec_marriage'],
  [], [],
  I('wiki.lessons.design_lessons'),
  ['SPB_WIKI.html:625-642'],
  quick=False,
  aliases=['what makes a finish good', 'finish quality', 'finishes are fields', 'fine detail'])
print('ok p2b')
