import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from enc_write_C import A, C, F

R = 'recipes'
P = 'ai_copilot'
V = 'preview_render'

# ------------------------------------------------------------------ recipes (doc.03)
A(R, 'three_colour_gradient', 'A gradient from blue to gold to white',
  'Put the gradient on the zone that owns the big body area: BASE COLOR, Custom gradient, then three colour stops and a direction. Remember the fade runs across the whole flat sheet, not along the car.',
  'A zone can fade between 2 to 10 colours. The fade is laid over the entire flat paint sheet in one direction, so left to right on the sheet is not always front to back on the car, and each side of the car sits in its own part of the sheet. If the zone only covers some colours of the paint, the gradient shows only there.',
  ['You want a fade from one colour through a second into a third, such as blue to gold to white.',
   'You want a sunset, fade-out or ombre look on the body.'],
  ['Pick or create the zone that owns the body area, and give it a coating finish such as Gloss, Pearl or Candy under BASE.',
   'Set BASE COLOR to the custom gradient option.',
   'Add three stops: deep blue at 0, gold at 50 and white at 100 (the stop positions run from 0 to 100).',
   'Choose the direction that matches the flat layout: horizontal runs left to right across the sheet, vertical top to bottom, or one of the diagonal and radial options.',
   'Look at the preview. If one side of the car fades the wrong way, give each side its own zone with its own gradient.'],
  [C('Custom gradient', '2 to 10 stops', '', 'Colour stops fading across the zone in a chosen direction.', 'zone.gradient'),
   C('BASE COLOR', 'dropdown', '', 'Chooses where the finish gets its colour: your own paint, one solid colour, or a gradient.', 'zone.base_color_mode')],
  ['True colours help: deep blue, a warm gold such as #d4a017, and pure white.',
   'Use a gradient for a deliberate whole-sheet effect. For a touch of colour coming into black, a coloured flake finish works better than a fade.'],
  ['The fade does not line up from the side panel over the bumper or onto the other side. That is how a flat unwrapped sheet works, not a fault.',
   'A finish that brings its own colour (chrome, carbon, holographic) ignores the gradient; use a coating base.'],
  ['recipes.gradient_roof_rocker', 'zones.what_is_a_zone', 'playbook.gradients_and_flake', 'playbook.colour_modes'],
  [F('control', 'zone.gradient')], [],
  ['doc.03.recipe_a_gradient_from_blue_to_gold_to_white'],
  ['docs/ai_knowledge/03_recipes.md:5-7', 'docs/ai_knowledge/09_field_playbook.md:18-19', 'docs/ai_knowledge/01_how_pro_works.md:18-23'],
  quick=True,
  aliases=['blue gold white gradient', 'three colour gradient', 'gradient stops', 'ombre', 'fade colours', 'sunset fade'])

A(R, 'holographic', 'A reflective holographic finish',
  'Make the base reflective (Pearl, Metallic or Chrome), then add a holographic spec overlay on top. The colour you chose stays; the rainbow shimmer rides in the shine map.',
  'Holographic here means a rainbow shimmer that changes with the light. It lives in the spec map, so it needs a reflective base underneath. If you also pick a finish that brings its own holographic colour, that finish replaces your colour, so choose base plus spec overlay when you want a specific colour.',
  ['You want a prism or rainbow shimmer on a body, an accent or a whole car.',
   'You want to keep your colour and add the shimmer on top.'],
  ['Open the zone that covers the area, or add one with + Add Zone.',
   'Under BASE press Base Material and choose a reflective finish: Pearl, Metallic or Chrome.',
   'Press + ADD SPEC OVERLAY and choose a holographic pattern from the list.',
   'Set its opacity to about 80 and look at the preview, then the spec views.',
   'Use Render to judge it at full size, because fine shimmer is hard to see in the small live preview.'],
  [C('+ ADD SPEC OVERLAY', 'button', '', 'Adds a shine-map pattern on top of the finish.', 'zone.add_spec_overlay'),
   C('Base Material', 'picker', '', 'Chooses the finish under the shimmer.', 'zone.base_material')],
  ['A monolithic holographic finish is the quick all-in-one option when you do not need a specific colour.',
   'Check the spec views: the shimmer shows as variation in the red metal view.'],
  ['Fine shimmer averages out in the live preview and can look flat. That does not mean it did nothing.'],
  ['recipes.colour_shift', 'recipes.flake_pearl', 'spec.what_is_spec_map', 'playbook.preview_cannot_show'],
  [F('control', 'zone.add_spec_overlay')], [],
  ['doc.03.recipe_reflective_holographic_finish'],
  ['docs/ai_knowledge/03_recipes.md:8-10', 'engine/spec_patterns.py:32095'],
  quick=True,
  aliases=['holographic', 'holographic finish', 'hologram', 'holo', 'rainbow shimmer', 'prism'])

A(R, 'rear_accents', 'Matching accents on the rear of each side',
  'Make a zone that takes the accent colour but only on the rear part of the sides, then give it the chrome-flake look. Read the real accent colour from the front first rather than guessing a blue.',
  'The front and rear accents share a colour, so a normal colour pick would catch both. You limit the new zone to the rear with a box or a named part, and put it above the zone that already owns the accent so it wins that area.',
  ['The livery has accent stripes front and rear and only the rear ones should change.',
   'You want a metal-flake look on part of a shape that has the same colour elsewhere.'],
  ['Pick the accent colour with PICK COLOR FROM CAR on the front accent so the zone matches it exactly.',
   'Under APPLY AREA, use Draw box around the rear of the left side. Repeat on the right side, or use a car part if the car is known.',
   'Choose a chrome or metallic finish under BASE, and keep the BASE COLOR on your own paint or the same blue.',
   'Add a flake spec overlay with + ADD SPEC OVERLAY, with opacity about 70.',
   'Move the zone to the top of the list, because the top zone wins overlaps, and check the preview.'],
  [C('PICK COLOR FROM CAR', 'eyedropper', '', 'Takes the exact accent colour from the paint.', 'zone.pick_color_from_car'),
   C('Draw box', 'tool', '', 'Limits the zone to the rear area.', 'zone.draw_box')],
  ['Never guess "the same blue". Sample the accent that is already on the car.',
   'Chat can do this too: name the part and the look, then check the preview.'],
  ['If the new zone sits below the zone that owns the accent colour, it will not show. Drag it up.'],
  ['zones.priority', 'zones.regions', 'zones.named_parts', 'recipes.flake_pearl'],
  [F('control', 'zone.draw_box')], [],
  ['doc.03.recipe_accents_on_the_rear_of_each_side_the_same_blue_as_the'],
  ['docs/ai_knowledge/03_recipes.md:11-16'],
  quick=True,
  aliases=['rear accents', 'accents on the rear', 'chrome flake accents', 'rear stripes only'])

A(R, 'finish_on_numbers', 'Give the numbers, sponsors or stripes their own finish',
  'Use the layer that holds them. Make a zone restricted to that layer, then choose the finish; with no layers, select them by their colour with a medium tolerance.',
  'A layered template keeps numbers, sponsors and stripes on their own layers, so a zone can be told to touch only that layer. A flat paint has no layers, so you select the colour of the numbers instead, with the tolerance wide enough to catch their soft edges.',
  ['You want the numbers gold chrome, the sponsors satin, or the stripes candy.',
   'You want sponsors to look like vinyl rather than shiny paint.'],
  ['In the Layers tab find the layer, for example Numbers, and press the button that creates a zone restricted to that layer.',
   'Open the new zone and choose the finish under BASE.',
   'No layers? Add a zone, use PICK COLOR FROM CAR on the number colour and set the tolerance to about 30 to 45.',
   'Check the preview. If a nearby colour is also taken, tighten the tolerance.'],
  [C('Create a zone restricted to this layer', 'button', '', 'One click makes a zone that only covers that layer.', 'layer.make_zone'),
   C('RESTRICT TO LAYERS', 'checkboxes', '', 'Limits a zone to the ticked layers.', 'zone.restrict_layers')],
  ['In Chat, name them: "make the numbers gold chrome". Numbers are only touched when you name them.'],
  ['Without a layer limit, a finish that brings its own colour paints over everything under the same colour.'],
  ['recipes.edit_one_thing', 'layers.lock_zone_to_layer', 'layers.decal_rescue', 'zones.restrict_layers'],
  [F('control', 'layer.make_zone')], [],
  ['doc.03.recipe_make_the_numbers_sponsors_stripes_chrome_or_any_finis'],
  ['docs/ai_knowledge/03_recipes.md:17-19'],
  quick=True,
  aliases=['chrome numbers', 'numbers chrome', 'sponsors chrome', 'finish on numbers', 'stripes chrome'])

A(R, 'make_it_pop', 'Make it pop',
  'Find the biggest flat area and the strongest pair of colours. Push one to a deep glossy candy or pearl of its own colour, keep the other matte, satin or chrome, and add a faint flake.',
  'A livery pops when neighbouring areas differ in both colour and shine, not when everything gets more saturated. One glossy deep area beside a flat area reads as depth on the car, and a light flake across the body adds sparkle in the sun.',
  ['The car looks flat or samey.',
   'You want one clear change that lifts the whole design.'],
  ['Find the biggest area and the two colours that contrast most.',
   'Give one of them a deep, glossy candy or pearl of its own colour with BASE COLOR set to use your paint.',
   'Keep the other area matte or satin, or give it a chrome trim.',
   'Add a subtle flake overlay on the body with + ADD SPEC OVERLAY, opacity 30 to 50.',
   'Compare with the SOURCE view and stop when it reads clearly at arm\'s length.'],
  [C('+ ADD SPEC OVERLAY', 'button', '', 'A faint flake adds sparkle without changing the colour.', 'zone.add_spec_overlay')],
  ['Opposite colour and opposite shine beside each other is the strongest contrast.',
   'Change one thing at a time so you can undo it cleanly.'],
  ['Too many glossy areas cancel each other out. Keep one hero area.'],
  ['recipes.candy', 'recipes.two_tone', 'recipes.flake_pearl'],
  [], [],
  ['doc.03.recipe_make_it_pop'],
  ['docs/ai_knowledge/03_recipes.md:23-25', 'docs/ai_knowledge/08_livery_design.md:18-20'],
  quick=True,
  aliases=['make it pop', 'pop', 'looks flat make it better', 'more contrast'])

A(R, 'undo_start_over', 'Undo, go back and start over',
  'Ctrl+Z takes back the last step, and every helper change has its own Undo button. To start the whole look over use Reset All Zones, or the Undo History panel to jump back several steps.',
  'There are three levels. One step back: Ctrl+Z or the Undo button under a helper answer. Several steps: press Undo more than once, with the Undo History list of recent actions to see where you are. A clean slate: Reset All Zones, which returns the list to the default five zones. The helper cannot delete zones itself; it mutes them and tells you where to delete.',
  ['The last change was wrong.',
   'You want the base file back and clear zones.'],
  ['Press Ctrl+Z, or press Undo under the helper\'s answer, to take back one step.',
   'Open Undo History to see the list of recent actions.',
   'To begin again, press Reset All Zones in the zones list.',
   'Never mute every zone: a render needs at least one zone.',
   'Save a project first if you might want the current look back.'],
  [C('Undo', 'Ctrl+Z', '', 'Takes back the last step.', 'pro.history.undo'),
   C('Reset All Zones', 'button', '', 'Back to the default five zones.', 'pro.zones.reset_all_zones')],
  ['Undo History lists your recent actions.'],
  ['Undoing many steps after you reset by hand can bring back an old state. When you want the base file, reset instead.'],
  ['tools.undo_redo', 'history.panel', 'workflows.first_paint'],
  [F('control', 'pro.zones.reset_all_zones')], [],
  ['doc.03.recipe_undo_go_back', 'doc.03.recipe_start_over_reset'],
  ['docs/ai_knowledge/03_recipes.md:29-31', 'docs/ai_knowledge/03_recipes.md:35-36'],
  quick=True,
  aliases=['undo', 'go back', 'start over', 'reset everything', 'begin again'])

A(R, 'change_body_keep_numbers', 'Change the whole car and keep the numbers and sponsors',
  'Put the change on the body paint layer only, such as Car Paint, so numbers, tape and logos sit on other layers and stay exactly as they are.',
  'On a layered template the body and the decals are separate layers. A zone limited to the body layer cannot touch the decals. A whole-car finish that brings its own colour (colour shift, candy, holographic) with no layer limit paints over every number and logo.',
  ['You want a new body colour or finish with the decals unchanged.',
   'A previous whole-car look wiped the numbers.'],
  ['In the Layers tab find the body layer (named like Car Paint or Body).',
   'Add or edit the zone that covers the car and tick only that layer under RESTRICT TO LAYERS.',
   'Give it the colour and finish you want.',
   'Check the numbers and sponsors are still crisp in the preview. If you actually want them changed too, include their layers.'],
  [C('RESTRICT TO LAYERS', 'checkboxes', '', 'Limits a zone to the ticked layers.', 'zone.restrict_layers')],
  ['Chat does this by default and says it kept your numbers and sponsors.'],
  ['A flat paint has no layers; use the colour pick instead, and check the numbers after.'],
  ['recipes.edit_one_thing', 'support.numbers_vanished', 'layers.lock_zone_to_layer'],
  [F('control', 'zone.restrict_layers')], [],
  ['doc.03.recipe_change_the_car_the_body_the_whole_car_keep_the_number'],
  ['docs/ai_knowledge/03_recipes.md:32-34'],
  quick=True,
  aliases=['change the body keep numbers', 'whole car keep sponsors', 'recolour the car keep the numbers'])

# ------------------------------------------------------------------ ai_copilot
A(P, 'panel_tour', 'The Shokker AI panel, step by step',
  'The Shokker AI panel is the chat window at the bottom right of PRO and the left side of CHAT. Type what you want, see the car change, and press Undo under any answer you do not like.',
  'The panel works on the same zones and layers as PRO. It shows what it changed, keeps each step so you can go back, and lets you choose how it thinks: the free built-in guided builder, the online model with your key, or an outside assistant over MCP. It never touches numbers, sponsors or logos unless you name them.',
  ['You want to describe a change instead of setting sliders.',
   'You are not sure what the helper can see or change.'],
  ['Open the panel with the AI button at the bottom right of PRO, or click CHAT at the top.',
   'Pick what to change, what to do and which look in the guided builder, or type a sentence and let it pre-fill the builder.',
   'Press Run and look at the preview.',
   'Press Undo under the answer to take it back, or Another take for a different idea.',
   'Open the gear in the panel for the key, model and outside assistant connection.'],
  [C('Another take', 'button', '', 'A different version of the same request.', 'ai.panel'),
   C('Undo', 'button', '', 'Takes back that one helper step.', 'ai.panel')],
  ['Typing a sentence works without any key; known words in your text are highlighted and open a short card.',
   'The helper can read the preview and your zones, so you can say "the hood" or "the yellow".'],
  ['It cannot import files, save, export or draw by hand; it tells you where to click instead.'],
  ['ai_copilot.chat_mode', 'ai_copilot.offline_vs_ai', 'ai_copilot.gear_key_model', 'ai_copilot.what_ai_sees', 'ai_copilot.can_and_cannot', 'ai_copilot.mcp_claude_chatgpt'],
  [F('control', 'ai.panel')], [],
  ['ai.panel'],
  ['js/spb-pro-ai.js:1611', 'js/spb-chat-studio.js:3-8'],
  quick=True,
  aliases=['shokker ai panel', 'ai panel', 'ai button', 'copilot window', 'chat window'])

A(P, 'can_and_cannot', 'What the helper can do, what it cannot, and how it talks',
  'It can change zones, finishes, colours, patterns, layer settings and named car parts, and look at your preview. It cannot delete zones, open or save files, export, draw by hand or add text.',
  'The helper changes what the zones and layers hold. It reads every zone, knows the whole finish catalogue, can aim at named parts of the car, offers whole designs to pick from and undoes its own work step by step. It cannot do file jobs or hand painting; it says so plainly and tells you where to click. It talks in plain words, says what it changed, and asks one short question when it is unsure.',
  ['You want to know whether to ask the helper or do it yourself.',
   'The helper answered "I cannot do that".'],
  ['Ask for looks and placement: colours, finishes, patterns, strength, a part of the car, a layer.',
   'Do file jobs yourself: open, import, save, Render, export, Auto-deploy and the User ID and car folder.',
   'Do hand painting with the toolbar: brush, lasso, fill, text.',
   'If it cannot delete a zone, it mutes it and tells you to delete it in the zones list.',
   'Check each change in the preview; Undo is always there.'],
  [],
  ['The helper cannot see how iRacing lights the car on track. It sets values only.',
   'Say one short thing at a time; the answers are kept short.'],
  ['Do not expect it to render the final full-size paint.'],
  ['ai_copilot.what_ai_sees', 'ai_copilot.offline_vs_ai', 'ai_copilot.panel_tour', 'recipes.undo_start_over'],
  [], [],
  ['doc.04.the_copilot_can_pro_mode', 'doc.04.the_copilot_cannot_say_so_plainly_then_give_the_manual_steps', 'doc.04.talking_style'],
  ['docs/ai_knowledge/04_limits_and_app_map.md:3-11', 'docs/ai_knowledge/04_limits_and_app_map.md:19-21', 'js/spb-pro-ai.js:3623-3626'],
  quick=False,
  aliases=['what can the ai do', 'ai limits', 'helper cannot', 'copilot limits', 'ai can do'])

A(P, 'mcp_tool_list', 'What Claude can do in Shokker: the tools it uses',
  'When you connect Claude or ChatGPT over MCP it gets a small set of tools. It checks the setup, reads zones, looks at the preview, asks you to show car parts, makes changes, and can undo them.',
  'These tools are what the outside assistant calls, and each matches something you can do by hand. The status check comes first and reports the car, its named parts, any missing parts, the layers and the zone count. The zone reader lists each zone, what it covers and how much of the paint it really wins. The preview returns the flat paint picture and, on request, the shine-map picture. A request-parts tool asks you to show Shokker the parts of a car it does not know. Undo takes back the last changes. A look tool shows the whole flat paint with a ruler so positions can be read. All changes also appear in the Shokker AI panel with an Undo button.',
  ['You connected Claude or ChatGPT and want to know what it is doing.',
   'The assistant asked you to show it the car parts.'],
  ['Connect from the gear in the panel (see the MCP article).',
   'Ask the assistant for a look; it first checks the setup.',
   'If it asks for car parts, drag a box around each part in the panel once per car.',
   'Watch the panel: every change shows there with Undo.',
   'Say "undo" to take back the last change, or press the button.'],
  [C('Status check', 'tool', '', 'Is Shokker connected, which car, which parts are known, how many zones.', 'mcp.spb_status'),
   C('Read zones', 'tool', '', 'Every zone, what it covers and how much of the paint it wins.', 'mcp.spb_get_zones'),
   C('Preview', 'tool', '', 'The flat paint as a picture, and the shine map on request.', 'mcp.spb_preview'),
   C('Request parts', 'tool', '', 'Asks you to show the car parts, once per car.', 'mcp.spb_request_parts'),
   C('Undo', 'tool', '1 step', 'Takes back the last changes.', 'mcp.spb_undo'),
   C('Look at paint', 'tool', '', 'The whole flat paint with a 0.1 ruler.', 'mcp.spb_look_at_paint')],
  ['Only one thing edits at a time; you can take over in the panel.',
   'If the assistant cannot see pictures it works from measured colour shares and zone visibility.'],
  ['The assistant does not touch numbers, sponsors or logos unless you name them.'],
  ['ai_copilot.mcp_claude_chatgpt', 'ai_copilot.panel_tour', 'cars.teach_parts', 'ai_copilot.what_ai_sees'],
  [], [],
  ['mcp.spb_status', 'mcp.spb_get_zones', 'mcp.spb_preview', 'mcp.spb_request_parts', 'mcp.spb_undo', 'mcp.spb_look_at_paint'],
  ['mcp/server/index.js:37-41', 'js/spb-pro-ai.js:2806'],
  quick=False,
  aliases=['mcp tools', 'spb tools', 'what claude can do', 'status check tool', 'look at paint'])

# ------------------------------------------------------------------ preview_render
A(V, 'render_stats_overlay', 'The Render Statistics overlay',
  'A small Render Statistics window exists in the page: total renders, average time, cache hits and GPU. In this build nothing opens it, so you will not find a button.',
  'The overlay shows total renders, the average and total render time, how often the cache answered, the graphics card in use, per-zone times and how long the session has run. It refreshes every three seconds while open. No button in this build opens it, so it cannot be reached from the screen.',
  ['A guide mentions Render Stats.',
   'You wonder why a render is slow.'],
  ['Do not look for a button: nothing in the top bar opens it.',
   'To judge speed, time the Render yourself and read the article on why a render is slow.',
   'If you need numbers for a problem, send a problem report.'],
  [],
  [],
  ['Do not hunt for a chart icon in the top bar; this build has none.'],
  ['preview_render.render_history_stats', 'preview_render.render_slow', 'support.reporting_problem'],
  [], [],
  ['render.stats'],
  ['paint-booth-v2.html:5143-5152', 'paint-booth-v2.html:5303-5345', 'paint-booth-v2.html:2481'],
  quick=False,
  aliases=['render stats', 'render statistics', 'render timing', 'gpu info'])
print('ok p2a')
