import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from enc_write_C import A, C, F

S = 'settings'

A(S, 'overview', 'The Settings gear: what is in it',
  'The gear at the top right opens a drop-down with your licence, the look of the app, options such as Export ZIP, Training Wheels and File Picker, quick tools, spec-map import and Auto-deploy.',
  'The Settings gear (top right) opens one drop-down. From top to bottom: License (shows your licence status), LOOKS (the visual theme of the booth), Options (Export ZIP Package, Training Wheels, a light or dark toggle, the File Picker choice, and a Report a Problem button that copies a diagnostic report without your licence key), Quick Tools (Keyboard Shortcuts), Import Spec Map (merge mode) with a Clear button, and Auto-Deploy to iRacing. This is different from the gear inside the AI panel, which holds your AI key, model and Claude/ChatGPT connection.',
  ['You want to turn Auto-deploy on or off.',
   'You want a different look for the app, or the Windows file chooser.',
   'You need to report a problem or see the shortcuts.'],
  ['Click the gear at the top right of the booth.',
   'Scroll to the section you want, change it, and click outside the drop-down (or press the gear again) to close it.',
   'Settings are remembered on this computer.'],
  [C('Export ZIP Package', 'on / off', 'off', 'Bundles paint TGA, spec TGA and preview into one ZIP on every render, in your output folder.', 'exportZipCheckbox'),
   C('Training Wheels', 'on / off', 'off until you choose', 'Quests and a next-move hint chip that teach the app while you use it.', 'trainingWheelsCheckbox'),
   C('Auto-deploy after render', 'on / off', 'off', 'Copies each render to your iRacing car folder automatically.', 'liveLinkCheckbox'),
   C('Import Spec Map', 'button', '', 'Merges an existing spec TGA under your zones; Clear removes it.', 'pro.settings.import_tga')],
  ['Keep Auto-deploy off while experimenting and turn it on when you are happy, to avoid overwriting a paint you like in iRacing.',
   'The gear in the AI panel is separate: that one has the AI key and the Claude/ChatGPT connection.'],
  ['An imported spec map stays under every render until you press Clear.',
   'Report a Problem makes text for you to paste to support; it does not send anything by itself.'],
  ['settings.file_picker', 'settings.looks_training_wheels', 'settings.activation_license', 'ai_copilot.gear_key_model', 'preview_render.auto_deploy', 'support.reporting_problem'],
  [F('control', 'liveLinkCheckbox')], [], ['exportZipCheckbox', 'trainingWheelsCheckbox', 'liveLinkCheckbox', 'pro.settings.import_tga', 'btnClearSpecMap', 'pro.settings.keyboard_shortcuts'],
  ['paint-booth-v2.html:1951', 'paint-booth-v2.html:1985-2020', 'paint-booth-v2.html:2189-2260'],
  quick=True,
  aliases=['settings', 'settings gear', 'gear', 'options', 'export zip', 'zip package', 'import spec map', 'where are the settings', 'cog'],
  )

A(S, 'file_picker', 'File Picker: Shokker Browser or Windows File Explorer',
  'Choose which file chooser opens for Source Paint, layered paint and the iRacing Car Folder: the Shokker Browser with image previews, or the normal Windows File Explorer.',
  'In Settings > Options, the File Picker setting decides how the Source Paint, Open Layered and iRacing Folder buttons let you pick things. Shokker Browser is the default and shows image previews, which is handy for TGA artwork. Windows File Explorer opens the standard Windows chooser, which some people find more familiar. The choice is saved on this computer. It works in the desktop app and also when you run the booth in a browser tab, because the server runs on the same machine and opens the Windows dialog for you.',
  ['You prefer the Windows chooser, or need a network drive that the Shokker Browser does not show.',
   'The chooser looks wrong or you cannot find a folder.'],
  ['Click the Settings gear > Options.',
   'Open the File Picker list and pick Shokker Browser or Windows File Explorer.',
   'Click Source Paint (or Open Layered, or the iRacing Folder button) to try it.'],
  [C('File Picker', 'Shokker Browser | Windows File Explorer', 'Shokker Browser', 'Which chooser opens for Source Paint, layered paint and the iRacing folder.')],
  ['Use Windows File Explorer if you need to type or paste a path, or browse to a folder on another drive.'],
  ['The picker setting does not change the files themselves, only how you choose them.',
   'The Windows chooser may open behind the booth window; Alt+Tab to find it.'],
  ['settings.overview', 'ui_shell.car_folder', 'layers.open_psd'],
  [], [], [],
  ['js/spb-native-file-dialogs.js:4-13', 'js/spb-native-file-dialogs.js:66-77'],
  aliases=['file picker', 'file chooser', 'file explorer', 'browse for a file', 'shokker browser', 'windows file explorer', 'cannot find my folder'],
  )

A(S, 'looks_training_wheels', 'Looks, light or dark, and Training Wheels',
  'Settings lets you change the look of the app (Classic plus 15 themes), switch between dark and light, and turn the Training Wheels quests on or off.',
  'LOOKS in the Settings drop-down changes the colours and shapes of the booth: Classic Mode is the default, and 15 more looks include Pro Dark, Linear, Nord, Dracula, Monokai, Solarized Dark, Carbon, OLED Black, Graphite, Studio Warm, Midnight Navy, Emerald Pro, Copper, High Contrast and Compact Pro. Switching is instant and the choice is remembered. A Light button next to it switches between dark and light. Training Wheels is the switch for the quest engine: step-by-step quests and a next-move hint chip that teach you the app as you work. Finishing the Core Loop offers to turn it off. None of this changes your paint.',
  ['The booth is hard to read on your monitor.',
   'You are new and want guidance, or experienced and want the hints gone.'],
  ['Open the Settings gear.',
   'Under LOOKS, click a look; it applies at once.',
   'Use the Light button if you need a light theme.',
   'Under Options, switch Training Wheels off when you no longer want hints.'],
  [C('Look', 'Classic + 15 themes', 'Classic Mode', 'Changes the booth\'s colours and shapes only.'),
   C('Training Wheels', 'on / off', '', 'Quests and hint chip that teach the app.', 'trainingWheelsCheckbox')],
  ['High Contrast is the easiest to read.',
   'If the booth looks cramped, try Compact Pro or check the UI size in the panels article.'],
  ['The white modes (Pro Light, Paper, Spacious) were retired; a saved choice of a retired look falls back to Classic.'],
  ['settings.overview', 'workflows.tutorial_quests', 'ui_shell.panels_and_ui_size'],
  [], [], [],
  ['paint-booth-v2.html:2015-2060', 'paint-booth-v2.html:2189-2210'],
  aliases=['looks', 'themes', 'dark mode', 'light mode', 'high contrast', 'change the look of the app', 'training wheels', 'hint chip', 'turn off hints'],
  )

A(S, 'activation_license', 'Your licence: activating, offline and a new PC',
  'Your licence key is entered when the desktop app starts. The app checks it online, saves it for this PC, and asks again if you move to another PC or Windows account.',
  'When you first start the desktop app a licence window asks for your key. The app checks the key with the seller\'s licence service and, if it is good, saves an encrypted licence file for this computer. If the service cannot be reached, the app saves an offline activation instead and lets you in. The saved licence is tied to this PC and Windows user, so on another PC, or if the Windows account changes, the app asks for your key again. After that, the Settings gear shows your licence status; in current builds it shows License Active and the key box is hidden because activation already happened at start-up. If you cannot activate, check the key for typos and your internet, and use Report a Problem.',
  ['First start after installing.',
   'You moved to a new PC or reinstalled Windows.',
   'The app keeps asking for a key.'],
  ['Start the app. In the licence window, paste your key and click Activate.',
   'Wait for Verifying. If your internet is down, the app says it saved an offline activation.',
   'On a new PC, enter the same key again. If it is refused as already used, contact support and say which PC the key was used on.',
   'No key yet? The same window has a Buy License button.'],
  [C('License key', 'text', '', 'Your purchased key. Pasted at start-up.', 'licenseKeyInput'),
   C('Activate', 'button', '', 'Checks the key and saves it for this PC.', 'pro.settings.activate'),
   C('Deactivate', 'button', '', 'Removes the activation from this PC so the key can be used elsewhere.', 'pro.settings.deactivate')],
  ['Keep the message or receipt that has your key.',
   'Type or paste the key without extra spaces.'],
  ['Activation is per PC and Windows user. A reinstall that keeps your Windows account does not need a new key, but a different PC does.',
   'Do not share your key in screenshots or support text; Report a Problem never includes it.'],
  ['settings.overview', 'workflows.install_update', 'support.reporting_problem'],
  [F('control', 'licenseKeyInput')], [], ['licenseKeyInput', 'pro.settings.activate', 'pro.settings.deactivate'],
  ['electron-app/license.html:160-205', 'electron-app/main.js:206-209', 'electron-app/main.js:330-346', 'electron-app/main.js:700-727', 'paint-booth-v2.html:4911-4978'],
  quick=True,
  aliases=['license', 'licence', 'license key', 'licence key', 'activate', 'activation', 'new pc', 'deactivate', 'key already used', 'payhip', 'offline activation', 'it asks for my key again'],
  )
print('ok')
