import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from enc_write_C import A, C, F

D = 'shokk_drop'

A(D, 'what_is_shokk_drop', 'Shokk Drop: turn any picture into a finish',
  'Shokk Drop is a separate window where you drop in a PNG, JPG or WebP and it becomes a finish you can use in the booth, with a matching shine built for it.',
  'Shokk Drop is a side window of the booth, opened from the SHOKK DROP button in the top bar. You give it an image (or a paint plus your own shine maps) and pick what the image should become: a paint finish, a pattern, a shine-only overlay, an exact paint-and-shine set, or a whole-car template. The image is resized to fill the 2048 by 2048 flat car sheet. After you Commit, the result shows up in a SHOKK DROP group inside the booth, ready to put on a zone like any other finish. It is the quickest way to get your own artwork, a photo texture or a brand pattern onto the car with a proper metal and gloss behind it.',
  ['You have a texture, pattern or artwork and want it as a finish you can reuse on any zone.',
   'You want several shine variations of one picture to choose from (SHOKK THE WORLD).',
   'You already have your own metallic, roughness and clearcoat maps and want them used exactly as you made them.'],
  ['In the booth top bar, click SHOKK DROP. A second window opens (click Guide in it for the built-in welcome steps).',
   'Pick a Type on the left. If you are unsure, leave it on Paint finish.',
   'Drop a PNG, JPG or WebP on the window, or choose a file. It is auto-sized to the 2048 square car sheet.',
   'Look at the preview, then click Commit drop. Or click SHOKK THE WORLD to get 20 shine variations of the same picture and keep the ones you like.',
   'Go back to the booth. Your drops are in the SHOKK DROP group, ready to put on a zone.'],
  [C('Type', 'Paint finish | Pattern | Spec overlay | Paint + spec maps (exact) | Car template (whole car)', 'Paint finish', 'Decides what your image becomes. Paint finish: the image is the colour and a matching shine is made for it. Pattern: a repeating design that keeps its transparency. Spec overlay: shine only, no colour. Paint + spec maps: both supplied by you, used exactly. Car template: a whole-car paint and shine as one zone.', 'drop.userImportKind'),
   C('SHOKK THE WORLD', 'button', '', 'Turns one picture into 20 shine variations: 8 standard, 7 that mix two styles and 5 extreme four-way blends. Keep your favourites.', 'drop.btnShokkTheWorld'),
   C('Commit drop', 'button', '', 'Saves the previewed drop into your library so it appears in the booth.', 'drop.commit_drop.270')],
  ['Not sure what to choose? Paint finish with the default shine is the best starting point.',
   'Shift while dropping an image runs SHOKK THE WORLD straight away.',
   'No art handy? Use Try a sample in the window to run the real process on a built-in test picture.',
   'Drops can be shared with friends as .spbdrop files; drag a friend\'s .spbdrop file onto the gallery to import it.'],
  ['The Shokk Drop window is separate from the booth. If your pop-up blocker stops it, the booth itself navigates to Shokk Drop; use the Paint Booth link at its top to come back.',
   'Drops are finishes, not zones. After importing you still have to put the finish on a zone in the booth.',
   'Only PNG, JPG and WebP are accepted.'],
  ['shokk_drop.shokk_library_files', 'shokk_drop.fracture_this_paint', 'spec.what_is_spec_map', 'zones.what_is_a_zone'],
  [F('control', 'pro.header.shokk_drop')], [],
  ['pro.header.shokk_drop'],
  ['paint-booth-v2.html:1936', 'paint-booth-6-ui-boot.js:5359-5365', 'shokk-drop.html:137-175', 'shokk-drop.html:286-310'],
  quick=True,
  aliases=['shokk drop', 'shokkdrop', 'drop an image', 'import an image as a finish', 'shokk the world', 'spbdrop', 'import my own texture', 'use my own picture as a finish', 'sample plate'],
  )

A(D, 'import_exact_set', 'Importing your own paint and shine maps (exact)',
  'If you already made a paint picture and its metallic, roughness and clearcoat maps, Shokk Drop can import them as one exact finish with no automatic shine added.',
  'Besides turning one picture into a finish, Shokk Drop has an Import a set section for people who author their own shine. You give it the colour art plus a spec: either one combined RGB picture, or three separate black-and-white plates. In the combined picture red is metallic, green is roughness and blue is clearcoat. The set is saved word for word, with no automatic bake, so it renders exactly the way you made it. You can save it as a paint finish or as a pattern, and choose how strong the metal and clearcoat come out.',
  ['You have your own M/R/CC maps from Photoshop or another tool.',
   'You want the shine to be exactly yours instead of auto-generated.',
   'You are matching a shine across several finishes and cannot afford surprises.'],
  ['In Shokk Drop, scroll to Import a set - exact finish.',
   'Choose Save as: Paint finish or Pattern.',
   'Add the colour art, then choose the spec form: No spec (auto-generate), FRACTURE the spec, Combined spec (one RGB image), or separate R, G and B plates.',
   'Click Import set (exact finish), preview it, then Commit drop.',
   'Find it in the SHOKK DROP group in the booth and put it on a zone.'],
  [C('Save as', 'Paint finish | Pattern', 'Paint finish', 'Whether the imported art becomes a colour finish or a stamp-on pattern.', 'drop.userImportSetTarget'),
   C('Combined spec (RGB)', 'one picture', '', 'One image where red is metallic, green is roughness and blue is clearcoat.', 'drop.userImportSetSpecCombined'),
   C('R / G / B plates', 'three pictures', '', 'Separate Metallic, Roughness and Clearcoat plates, if you do not have a combined picture.', 'drop.userImportSetSpecR'),
   C('Import set (exact finish)', 'button', '', 'Brings the set in exactly as authored, with no automatic shine bake.', 'drop.btnImportSet')],
  ['Remember blue is clearcoat: low blue values are a strong clearcoat (16 is maximum gloss in the game) and high blue is dull. Check the clearcoat article before painting the blue plate.',
   'Leave a plate empty and Shokk fills it for you if the "any plate left empty" option is on.'],
  ['A combined spec is read as colour channels, so keep it a normal RGB picture; do not save it with a colour profile that shifts values.',
   'An exact set will not be rescued by auto-shine: if your roughness plate is flat, the car will look flat.'],
  ['spec.channel_b_clearcoat', 'spec.what_is_spec_map', 'shokk_drop.what_is_shokk_drop'],
  [F('control', 'drop.btnImportSet')], [], [],
  ['shokk-drop.html:170-232', 'shokk-drop.html:302-311'],
  aliases=['import a set', 'exact finish import', 'paint plus spec maps', 'import my own spec maps', 'combined spec rgb', 'bring my own shine'],
  )

A(D, 'shokk_library_files', 'The SHOKK library: saving and loading .shokk files',
  'A .shokk file saves your whole current set-up (zones and finishes) as a reusable recipe you can load later or share.',
  'SHOKK Library is the booth\'s saved-recipes shelf. SAVE SHOKK writes your current session as a .shokk file with a name, author, short description and tags. LOAD SHOKK FILE opens the library window, where you search, select a recipe, and open it. By default the library lives in your Documents folder under Shokker Paint Booth > SHOKK Library. Do not mix this up with Shokk Drop, which makes finishes out of pictures, or with a project file, which is your working session with its layers.',
  ['You want to keep a finished look as a recipe and reuse it on another car.',
   'You want to share a look with a friend.',
   'You want to inspect what a saved recipe is made of as PNG channel files.'],
  ['Open the Zones panel More menu and click SAVE SHOKK.',
   'Type a name (required). Add an author, a short description and any tags (for example Pearl, Candy, Neon, Dark, Pattern-Based, Multi-Layer, Full Scheme).',
   'Leave Include paint on if you want the file to carry the paint picture and open the same on another machine, then click Save.',
   'To use one later: More > LOAD SHOKK FILE, search by name, author or tag, select a file and click Open Selected (double-click also loads it).'],
  [C('Include paint', 'on / off', 'on', 'Packs the paint picture into the .shokk file so it is fully portable. The file is larger, but opens the same everywhere.', 'shokkIncludePaint'),
   C('Search', 'text', '', 'Finds saved recipes by name, author or tag.', 'shokkSearchInput'),
   C('Channel PNG Export', 'button', '', 'Extracts a selected recipe\'s paint and spec to PNG files for looking at in Photoshop. It does not make final iRacing files.', 'shokkPsExportBtn')],
  ['Put the car and the look in the name, for example "Gulf stripes on 718 GT3". You will search for it later.',
   'Turn Include paint on when sending a file to anyone else.'],
  ['Channel PNG Export is for inspection only; it does not produce the iRacing TGA files.',
   'A .shokk recipe is not your layered work. For layers use Save project.'],
  ['preview_render.saving_projects', 'zones.presets_templates', 'ui_shell.zones_more_menu', 'shokk_drop.what_is_shokk_drop'],
  [F('control', 'pro.zones_more.save_shokk')], [], [],
  ['paint-booth-v2.html:2651-2666', 'paint-booth-v2.html:4996-5021', 'paint-booth-v2.html:5076', 'server.py:13774-13787', 'config.py:203-205'],
  aliases=['shokk file', 'dot shokk', 'shokk library', 'save shokk', 'load shokk file', 'shokker file', 'save a recipe', 'saved looks'],
  )

A(D, 'fracture_this_paint', 'FRACTURE THIS PAINT: the one-click fractured look',
  'One button swaps the selected zone to the Soul Core Emerald finish, whose shine has the pink-flash fractured look the owner uses as a standard.',
  'FRACTURE THIS PAINT is a shortcut button in the top bar. It sets the finish of your selected zone (or the first zone, if none is selected) to Soul Core Emerald, which gives the broken-glass style shine with pink flashes. If the zone\'s colour is locked, the finish changes but your colour is kept, and the on-screen message says so. If there are no zones yet, it asks you to add one first. Think of it as a quick way to see how a fractured finish looks on your car, not a separate tool.',
  ['You want a fast, striking fractured look on one part.',
   'You are testing how a zone looks with a heavy fractured finish.'],
  ['Add a zone (and select the one you want to fracture).',
   'Click FRACTURE THIS PAINT in the top bar.',
   'Read the message: it names the zone it changed and says if your colour was kept because the lock is on.',
   'Not happy? Use Undo (Ctrl+Z).'],
  [C('FRACTURE THIS PAINT', 'button', '', 'Applies Soul Core Emerald to the selected zone.', 'btnFractureThisPaint')],
  ['Lock the colour first if you want to keep your own colour and take only the fractured shine.'],
  ['It changes only one zone. It does nothing and warns you if no zone exists.',
   'It replaces that zone\'s current finish, so Undo is your way back.'],
  ['zones.what_is_a_zone', 'tools.undo_redo', 'finishes.colorshoxx_and_shift', 'shokk_drop.what_is_shokk_drop'],
  [F('control', 'btnFractureThisPaint')], [],
  ['btnFractureThisPaint'],
  ['paint-booth-v2.html:1937-1940', 'paint-booth-2-state-zones.js:7805-7835'],
  quick=True,
  aliases=['fracture this paint', 'fractured look', 'soul core emerald', 'pink flash', 'fracture button', 'fractured paint'],
  )

A(D, 'tools_not_in_booth', 'Image Forge, Auto Painter and other tools you may hear about',
  'A few tools in old notes are not part of the booth you installed: Auto Painter (Shokk Trace) is removed from the top bar, Image Forge is a builder-side guide, and the experimental tab is hidden.',
  'If you read old posts or notes you may see names that do not match what is on your screen. Auto Painter, also called Shokk Trace, had its top-bar button removed in this build because it was not working well; it is not something you can click. Image Forge is a drop-a-picture-into-a-folder way for the finish authors to replace or add finishes; its guide is a table of finish ids, and it is not a buyer feature. The experimental tab (Design It, Photo to Livery, Shokker-ize) is hidden in this build. What you do have for pictures is Shokk Drop and, in the chat helper, attaching a picture for colours to match.',
  ['You saw a feature name in a video or old post and cannot find it.',
   'You are choosing between Shokk Drop and a tool that does not exist in your booth.'],
  ['For your own picture as a finish, use Shokk Drop.',
   'For a look similar to a photo, use the chat helper and attach the picture (see the match-a-photo recipe).',
   'For the exact shine you authored, use Import a set in Shokk Drop.'],
  [], ['If you cannot find a button, check the top bar help and the window tour before assuming something is broken.'],
  ['Do not look for a Shokk Trace or Auto Painter button; there is not one in this build.',
   'The Image Forge guide is for authors, and dropping files into its folder does nothing for a normal installed booth.'],
  ['shokk_drop.what_is_shokk_drop', 'recipes.match_photo', 'ui_shell.top_bar_buttons'],
  [], [], [],
  ['paint-booth-v2.html:1979', 'paint-booth-v2.html:4725-4729', 'IMAGE_FORGE_GUIDE.html:14-19'],
  aliases=['image forge', 'shokk trace', 'auto painter', 'experimental features', 'design it', 'photo to livery', 'shokkerize'],
  )
print('ok')
