"""v3 depth for the ai_copilot domain (lane C, 2026-10-04). Current owner decision: offline helper = guided builder + Encyclopedia; free chat = online (gear model, DeepSeek via OpenRouter) or MCP via Claude/OpenAI;
numbers/sponsors/logos untouched unless named; every AI change has Undo. Facts: docs/EDIT_EXISTING_HELPER.md, docs/CAR_LEARNING.md, docs/ai_knowledge/04_limits_and_app_map.md, js/spb-ai-core.js, mcp/server/index.js."""
V3 = {
 'ai_copilot.chat_mode': {
  'level': 'beginner',
  'deep': [
   {'heading': 'Same booth, different front door',
    'body': 'Chat works on the same paint, zones and shine as PRO, so nothing is a second copy. The helper is on the left, the live car on the right. Tabs show the Paint, the Shine (spec) or the Car parts Shokker knows. A view strip under the car mirrors the Full Editor views, and a layer bar on the right lets you lock the helper to one layer so "make it red" changes only that layer.'},
   {'heading': 'Every step is kept',
    'body': 'Each change is saved under Versions; click one to go back. Compare slides between before and after. Under each answer, Undo takes that one step back and Another take gives a different idea. You can also say "undo" or "start over".'},
   {'heading': 'It works with no key',
    'body': 'The built-in helper is a guided builder with a library of 74 design themes and Surprise me, which tries four complete ideas on your car. Adding an AI key or connecting Claude through MCP adds free-form chat on top.'},
   {'heading': 'What it will not do',
    'body': 'Chat changes zones and layer settings only. It does not open files, import a paint, save or export; do those in PRO. Numbers, sponsors and logos are not touched unless you name them.'}],
  'examples': [
   {'title': 'Start from a plain request', 'goal': 'Get a first look without touching a slider',
    'settings': {'Mode': 'CHAT', 'Message': 'make the hood matte black', 'Then': 'Look at the preview and press Undo if it is wrong'},
    'result': 'The hood zone gets a matte black finish and the car on the right updates.'},
   {'title': 'Four ideas at once', 'goal': 'React to complete designs instead of building one',
    'settings': {'Button': 'Surprise me', 'Pick': 'Tap the one you like', 'Finish': 'Render & save or Full editor'},
    'result': 'Four complete designs tried on your car; the one you tap stays.'},
   {'title': 'Design in a logo\'s colours', 'goal': 'Use the colours of a sponsor picture',
    'settings': {'Button': 'Colours from a picture', 'Picture': 'A logo, photo or flag'},
    'result': 'The three strongest colours are read and the design uses them.'}],
  'faq': [
   {'q': 'Is Chat a different program from PRO?', 'a': 'No. It edits the same paint, zones and spec. Full editor takes you back to PRO.'},
   {'q': 'Do I need an AI key?', 'a': 'No. The guided builder, the 74 themes and Surprise me work free.'},
   {'q': 'Will Chat change my numbers?', 'a': 'Not unless you name them.'},
   {'q': 'How do I go back a step?', 'a': 'Press Undo under the answer, say "undo", or click an earlier step in Versions.'},
   {'q': 'Can Chat save my paint?', 'a': 'No. Press Render & save, or use PRO.'}],
  'mistakes': [
   {'symptom': 'Chat says it does not know your car', 'cause': 'The car is not in the library yet', 'fix': 'Show it the parts once; it remembers them.'},
   {'symptom': 'You asked Chat to open a file and nothing happened', 'cause': 'Chat does not do file jobs', 'fix': 'Open the file in PRO, then come back to Chat.'}],
  'protips': ['Lock to layer is the safest way to edit a layered livery: the helper then cannot reach anything outside that layer.',
              'Be specific about the part: "the rear half of the left side" works once the car\'s parts are known.'],
 },
 'ai_copilot.offline_vs_ai': {
  'level': 'beginner',
  'deep': [
   {'heading': 'Three ways to talk',
    'body': 'One: the built-in helper needs no key and no internet. It is a guided builder: you choose what to change, what to do, and which look from real catalogue thumbnails, then Run and Undo. Two: free chat with the AI key, where Ask DeepSeek instead sends the same text to the model chosen in the gear. Three: MCP, where Claude or ChatGPT/Codex on your own plan drive the booth.'},
   {'heading': 'What "what to change" means',
    'body': 'You pick a colour found on the car, a named part, a layer, numbers or sponsors, or the whole car. Then you pick what to do (recolour, add a finish, add a pattern, change the shine). If you type a sentence the builder is pre-filled with what it understood and asks about the rest. Known words in your text are highlighted and open a short card from the Encyclopedia.'},
   {'heading': 'The built-in helper never guesses',
    'body': 'What it cannot read becomes an open question with choices. That is why it is safe to try first.'},
   {'heading': 'Cost and limits',
    'body': 'The online model costs a little per request (DeepSeek v4.1 Flash is about a half cent) and is capped per day. The built-in helper costs nothing. An outside assistant and the in-app copilot should not both edit at once; use Take over in SPB to switch.'}],
  'examples': [
   {'title': 'Try the free helper first', 'goal': 'Get a change done without a key',
    'settings': {'Type': 'make the stripes gold', 'Check': 'How it read the request', 'Press': 'Run'},
    'result': 'The stripes change. If part of the sentence was unclear, an open step with choices appears.'},
   {'title': 'Hand a hard sentence to the online model', 'goal': 'Get free-form help when the builder cannot read a request',
    'settings': {'Needs': 'A key in the Chat gear', 'Button': 'Ask DeepSeek instead'},
    'result': 'The same text goes to the model chosen in the gear.'}],
  'faq': [
   {'q': 'Do I need a key?', 'a': 'Most buyers never do. The builder, the themes and Surprise me work free.'},
   {'q': 'Does the free helper send my paint anywhere?', 'a': 'No. It works on your computer.'},
   {'q': 'How much does the online model cost?', 'a': 'DeepSeek v4.1 Flash, the recommended one, is about half a cent per request, and a daily cap protects you.'},
   {'q': 'Can Claude and the in-app helper edit together?', 'a': 'They should not. Use Take over in SPB to switch who is editing.'}],
  'mistakes': [
   {'symptom': 'You type a long sentence and get a question back', 'cause': 'The built-in helper asks rather than guessing', 'fix': 'Answer the question by clicking a choice, or press Ask DeepSeek instead.'},
   {'symptom': 'Changes from Claude appear while you work in the panel', 'cause': 'An outside assistant has control', 'fix': 'Press Take over in SPB.'}],
  'protips': ['Say the part and the look in the same sentence; the builder pre-fills both and you only confirm.'],
 },
 'ai_copilot.edit_existing': {
  'level': 'beginner',
  'deep': [
   {'heading': 'It reads the real colours',
    'body': 'Shokker reads the real colours in your paint, not the template\'s dead space, so "the black", "all the red" or "the dark blue" point at pixels that are actually there, and it changes only those.'},
   {'heading': 'Look word, colour word, or both',
    'body': 'A look alone (matte, satin, chrome, powder coat, wet look) changes only the shine and keeps your colour exactly. A new colour repaints exactly those pixels. Both together do both. Words such as "a bit glossier" or "darker" nudge what is there. A second request on the same colour edits the zone it made, so changes stack instead of resetting.'},
   {'heading': 'It asks instead of guessing',
    'body': 'If you name a colour that is not on the car (say pink when the car has only red), it asks. On a flat paint with no layers, numbers, sponsors and stripes are not known, so it asks you to show them first.'},
   {'heading': 'Protecting numbers',
    'body': 'Numbers, sponsors and logos change only when named. Say "except the numbers" or "but leave the numbers alone" to protect them explicitly.'}],
  'examples': [
   {'title': 'Matte version of a livery', 'goal': 'Make every black area matte and keep the colours',
    'settings': {'Message': 'make the black matte', 'Check': 'How it read the request', 'Press': 'Run'},
    'result': 'Only the shine of the black changes; the colour stays the same. Undo takes it back.'},
   {'title': 'Recolour the numbers', 'goal': 'Change the numbers to metallic purple',
    'settings': {'Message': 'numbers purple and metallic', 'Paint': 'A layered PSD works best'},
    'result': 'The numbers get purple with a metallic shine.'},
   {'title': 'Stack a second change', 'goal': 'Add more to what you just did',
    'settings': {'Message': 'a bit more', 'or': 'do the same for the roof'},
    'result': 'The helper adjusts the same zone or repeats the change on the roof.'}],
  'faq': [
   {'q': 'Does "make it matte" change my colours?', 'a': 'No. A look word alone changes only the shine.'},
   {'q': 'Why did "red matte" touch my tail-light lens?', 'a': 'It matches by colour, so a dark-red lens can be included. Undo and name the part.'},
   {'q': 'Does it work on a flat TGA?', 'a': 'Yes, but a layered PSD is best. On a flat paint it asks you to show numbers, sponsors and stripes.'},
   {'q': 'How do I protect the numbers?', 'a': 'Say "except the numbers" or "leave the numbers alone".'}],
  'mistakes': [
   {'symptom': 'A colour you named is not changing', 'cause': 'That colour is not actually on the car, or is a different shade', 'fix': 'Answer the helper\'s question to point it at the right colour.'},
   {'symptom': 'Numbers changed along with everything else', 'cause': 'You named a colour the numbers also use', 'fix': 'Undo and add "except the numbers".'}],
  'protips': ['For best results load the layered PSD. Layers let the helper tell stripes, numbers and sponsors apart, which a flat TGA cannot.'],
 },
 'ai_copilot.picking_colours_in_words': {
  'level': 'beginner',
  'deep': [
   {'heading': 'Words it understands',
    'body': 'Everyday colour words (including shades such as powder blue or charcoal), hex codes such as #ff7eb6, and phrases like "all the red", "the dark blue" or "the black on the hood". "Same shade as the hood" copies a colour from the car.'},
   {'heading': 'Looks mapped to real finishes',
    'body': 'Spoken looks map to real catalogue finishes: powder coat, plasti dip, cerakote, matte, satin, gloss, wet look, chrome, satin chrome, dark chrome, metallic, pearl, candy and more.'},
   {'heading': 'Long sentences are split',
    'body': 'A compound sentence such as "make the hood and the roof powder coat, then the stripes gold" is split into steps. Ambiguous words are asked about with buttons.'},
   {'heading': 'Colour families',
    'body': 'Names are read by family. "Pink" on a car with only red will be asked about, not forced. Spelling mistakes in common words are understood, but made-up looks are asked about.'}],
  'examples': [
   {'title': 'Look plus colour', 'goal': 'Set both at once',
    'settings': {'Message': 'matte metallic purple on the left side'},
    'result': 'The left side is repainted purple with a matte metallic look.'},
   {'title': 'Exact colour from a code', 'goal': 'Use a specific shade',
    'settings': {'Message': 'make the roof #ff7eb6'},
    'result': 'The roof takes that exact pink.'},
   {'title': 'Match a colour on the car', 'goal': 'Make one part the same as another',
    'settings': {'Message': 'make the roof the same shade as the hood'},
    'result': 'The roof copies the hood colour.'}],
  'faq': [
   {'q': 'Can I type a hex code?', 'a': 'Yes, such as #ff7eb6.'},
   {'q': 'What does "a bit glossier" do?', 'a': 'It nudges what is there instead of replacing it.'},
   {'q': 'Which looks does it know?', 'a': 'Powder coat, plasti dip, cerakote, matte, satin, gloss, wet look, chrome, satin chrome, dark chrome, metallic, pearl, candy and more.'},
   {'q': 'What if it does not know my word?', 'a': 'It asks with buttons instead of guessing.'}],
  'mistakes': [
   {'symptom': 'It asks which pink you mean', 'cause': 'There is no pink on the car, only red', 'fix': 'Pick from the buttons, or use a hex code.'},
   {'symptom': 'The wrong part changed', 'cause': 'The part was not named', 'fix': 'Name it: "the black on the hood" or "the left side".'}],
  'protips': ['A hex code is the most precise way to say a colour when a name is ambiguous.'],
 },
 'ai_copilot.gear_key_model': {
  'level': 'intermediate',
  'deep': [
   {'heading': 'The gear in the AI panel',
    'body': 'Paste your OpenRouter key and press Save. It is stored on this computer, encrypted for your Windows account. A key is optional. The Model line shows the one model the helper uses. DeepSeek v4.1 Flash is recommended because it is the cheapest that works well, about half a cent per request. Pick a different model and the gear warns that it usually costs more, with a Use the recommended model button.'},
   {'heading': 'The daily cap',
    'body': 'The cap defaults to $2 per day and can be set from $0.05 to $500. It is checked before every request. When it is reached the helper says so, and you raise it in the gear to continue. Test connection and Check credit are there too.'},
   {'heading': 'The When switch',
    'body': 'Auto uses the AI only when the built-in helper is not sure. Always uses it every time. Off never uses it. A private option runs a model on your own PC through Ollama or LM Studio.'},
   {'heading': 'Without a key',
    'body': 'The builder, Surprise me and the 74 themes all work free. Picture-based finish naming and open-ended AI answers are unavailable.'}],
  'examples': [
   {'title': 'Set up with a small budget', 'goal': 'Use the online model safely',
    'settings': {'Key': 'OpenRouter key from openrouter.ai/keys with a few dollars of credit', 'Model': 'DeepSeek v4.1 Flash (recommended)', 'Daily cap': '$2.00', 'When': 'Auto'},
    'result': 'The AI is used only when the built-in helper is unsure, and spend stops at $2 a day.'},
   {'title': 'Check it works', 'goal': 'Confirm the key is good',
    'settings': {'Button': 'Test connection', 'Then': 'Check credit'},
    'result': 'You see that the connection works and how much credit is left.'}],
  'faq': [
   {'q': 'Where do I get a key?', 'a': 'At openrouter.ai/keys. Add a few dollars of credit.'},
   {'q': 'Is my key stored safely?', 'a': 'It is stored on this computer, encrypted for your Windows account. Never paste it in chat or in a support message.'},
   {'q': 'The helper says the daily cap was reached.', 'a': 'Raise the Daily cap in the gear to continue.'},
   {'q': 'Can I use a model on my own PC?', 'a': 'Yes, through the private option with Ollama or LM Studio.'}],
  'mistakes': [
   {'symptom': 'Costs are higher than expected', 'cause': 'A higher-priced model is selected', 'fix': 'Press Use the recommended model.'},
   {'symptom': 'You cannot find the key box', 'cause': 'You opened the booth Settings gear', 'fix': 'Open the gear inside the AI panel.'}],
  'protips': ['Also set a spending limit on the key at OpenRouter. Two limits are better than one.'],
 },
 'ai_copilot.mcp_claude_chatgpt': {
  'level': 'intermediate',
  'deep': [
   {'heading': 'Setting up Claude Desktop',
    'body': 'In the AI gear, switch on Let an AI assistant control Shokker Paint Booth, then press Install in Claude Desktop and restart Claude Desktop. With Shokker open, ask for a whole livery, for example: Using Shokker Paint Booth, give me a Gulf-style livery.'},
   {'heading': 'Setting up ChatGPT or Codex',
    'body': 'Open the bridge settings, choose Connect ChatGPT / Codex, review it, press Add SPB to Codex settings, restart Codex and sign in with ChatGPT. Your own plan limits apply.'},
   {'heading': 'What the assistant knows',
    'body': 'It sees the same car knowledge, the finishes (about 4,800) and the named parts as the in-app helper, and changes the same zones. Every change shows in the AI panel with an Undo button.'},
   {'heading': 'One editor at a time',
    'body': 'Use Take over in SPB before asking the in-app helper while an outside assistant has control. Only the page that is open and connected receives changes, so close extra Shokker windows you are not using.'}],
  'examples': [
   {'title': 'A full livery by request', 'goal': 'Let Claude design the whole car',
    'settings': {'Gear': 'Control option on', 'Setup': 'Install in Claude Desktop, then restart it', 'Ask': 'Using Shokker Paint Booth, give me a Gulf-style livery'},
    'result': 'Claude checks the setup, reads the zones and builds the scheme. Each change appears in the panel with Undo.'},
   {'title': 'Shine only', 'goal': 'Change the gloss and keep your colours',
    'settings': {'Ask': 'only the chrome, keep my colours'},
    'result': 'A foundation finish is used, which leaves the paint untouched.'}],
  'faq': [
   {'q': 'Do I need an AI key in Shokker for this?', 'a': 'No. Your own Claude or ChatGPT plan is used.'},
   {'q': 'Can I undo what Claude did?', 'a': 'Yes. Every change has an Undo button in the AI panel, or say "undo".'},
   {'q': 'Claude is changing things while I work.', 'a': 'That is an outside assistant with control. Use Take over in SPB to switch back.'},
   {'q': 'How many finishes can it use?', 'a': 'About 4,800, the same catalogue as the booth.'}],
  'mistakes': [
   {'symptom': 'Claude cannot reach Shokker', 'cause': 'Shokker is closed, or Claude Desktop was not restarted after Install', 'fix': 'Keep Shokker open and restart Claude Desktop.'},
   {'symptom': 'Two assistants fight over the car', 'cause': 'The in-app helper and an outside assistant both edit', 'fix': 'Use Take over in SPB and let one work at a time.'}],
  'protips': ['Ask for the whole livery first, then refine with small requests. Big first, then details gets the best results.'],
 },
 'ai_copilot.what_ai_sees': {
  'level': 'intermediate',
  'deep': [
   {'heading': 'What it reads',
    'body': 'Your zones, your layers, the real colours in your paint with how much of the car each covers, and the preview. The online model can also look at a picture of your paint when it needs to, for example to name a finish from a photo or check its own result; only the provider you chose sees it. The built-in helper does none of that online.'},
   {'heading': 'What it will do and not do',
    'body': 'It will change zones and layer settings, set finishes and colours and aim at named parts. It will not delete zones, open or save files, import a paint, export to iRacing, change your car folder or User ID, draw by hand or add text.'},
   {'heading': 'Numbers, sponsors, logos',
    'body': 'They are left alone unless you name them, and Chat\'s whole-car looks stay in the body paint layers. Every change has Undo.'}],
  'examples': [
   {'title': 'Change the numbers on purpose', 'goal': 'Make numbers gold chrome',
    'settings': {'Message': 'make the numbers gold chrome'},
    'result': 'Only the numbers change, because you named them.'},
   {'title': 'Keep everything on your computer', 'goal': 'Avoid sending pictures out',
    'settings': {'Use': 'The built-in helper only', 'Key': 'Do not add one'},
    'result': 'Nothing is sent out; picture-based naming and open-ended answers are unavailable.'}],
  'faq': [
   {'q': 'Does the helper see my paint picture?', 'a': 'The online model can when it needs to; only the provider you chose sees it. The built-in helper works on your computer.'},
   {'q': 'Will it change my sponsors?', 'a': 'Not unless you name them.'},
   {'q': 'Can it save my work?', 'a': 'No. Use PRO\'s Render for saving and exporting.'},
   {'q': 'Does it know how iRacing lights the car?', 'a': 'No. It sets values only.'}],
  'mistakes': [
   {'symptom': 'You expected it to export', 'cause': 'File jobs are not part of the helper', 'fix': 'Use Render and save yourself.'},
   {'symptom': 'You pasted your key in chat', 'cause': 'It looked like a normal text box', 'fix': 'Change the key at OpenRouter and keep it only in the gear.'}],
  'protips': ['Read the helper\'s "what I changed and assumed" line. It tells you exactly where it guessed.'],
 },
 'ai_copilot.car_learning': {
  'level': 'intermediate',
  'deep': [
   {'heading': 'The ladder',
    'body': 'First the helper looks for a match in the shipped car library, by sheet layout or by the iRacing car folder. If the sheet is at least 78% like a known car, it proposes that car\'s layout fitted to your sheet and waits for one click; it never applies a look-alike silently. If nothing is close, it shows your sheet and asks you to draw each part.'},
   {'heading': 'Memory',
    'body': 'Everything you confirm or teach is stored on this computer and recognised next time, including other paints of the same car.'},
   {'heading': 'Paints without the template',
    'body': 'If your paint has lost its template dead space, the helper can still recognise many cars from where the panel edges fall, but treats that as a proposal to confirm.'}],
  'examples': [
   {'title': 'First time with a car', 'goal': 'Get Chat to understand "the hood"',
    'settings': {'Message': 'make the hood red', 'If it proposes a car': 'Press Yes only if it is right', 'If it asks': 'Draw a box round the hood once'},
    'result': 'The hood is stored and recognised next time.'},
   {'title': 'Repair a wrong map', 'goal': 'Correct a wrong Yes',
    'settings': {'Where': 'Chat gear', 'Action': 'Load a corrected car map, or save one'},
    'result': 'The wrong lesson is replaced.'}],
  'faq': [
   {'q': 'Why did it recognise my car without asking?', 'a': 'It matched the car folder or the sheet layout against the shipped library.'},
   {'q': 'Is what I teach shared?', 'a': 'No. It stays on this computer.'},
   {'q': 'Should I teach every part?', 'a': 'No, only the ones you need. You can add more later.'}],
  'mistakes': [
   {'symptom': 'Zones land on the wrong panel for a car it "recognised"', 'cause': 'A wrong Yes taught a wrong map', 'fix': 'Load or save a corrected car map in the gear.'},
   {'symptom': 'It asks again every time', 'cause': 'The part was never confirmed or taught', 'fix': 'Teach it once with a box.'}],
  'protips': ['Check the preview before pressing Yes on a proposed car. The 78% match is a good guess, not proof.'],
 },
 'ai_copilot.panel_tour': {
  'level': 'beginner',
  'deep': [
   {'heading': 'Where the panel is',
    'body': 'It is the chat window at the bottom right of PRO (the AI button) and the left side of CHAT. It works on the same zones and layers as PRO, shows what it changed and keeps each step so you can go back.'},
   {'heading': 'Pick how it thinks',
    'body': 'You choose the free built-in guided builder, the online model with your key, or an outside assistant over MCP. Open the gear in the panel for the key, model and outside-assistant connection.'},
   {'heading': 'The rhythm',
    'body': 'Pick what to change, what to do and which look (or type a sentence and let it pre-fill the builder), press Run, look at the preview, then Undo or Another take if needed. Known words in your text are highlighted and open a short card.'}],
  'examples': [
   {'title': 'A first change', 'goal': 'Try the panel safely',
    'settings': {'Open': 'AI button, bottom right', 'Type': 'make the roof white', 'Press': 'Run, then Undo to compare'},
    'result': 'You see the change and the undo restores the earlier look.'},
   {'title': 'A different idea', 'goal': 'Get another version of the same request',
    'settings': {'Button': 'Another take'},
    'result': 'The helper tries a different version of the request.'}],
  'faq': [
   {'q': 'Where is the AI panel?', 'a': 'Click the AI button at the bottom right of PRO, or click CHAT at the top.'},
   {'q': 'Can it import or export files?', 'a': 'No. It tells you where to click instead.'},
   {'q': 'What is Another take?', 'a': 'A different version of the same request.'}],
  'mistakes': [
   {'symptom': 'You cannot find the key box', 'cause': 'It is in the gear inside this panel', 'fix': 'Open the panel and click its gear.'},
   {'symptom': 'You expect the panel to save', 'cause': 'It cannot save or export', 'fix': 'Use Render in PRO.'}],
  'protips': ['You can say "the hood" or "the yellow" because the helper reads your zones and the preview.'],
 },
 'ai_copilot.can_and_cannot': {
  'level': 'beginner',
  'deep': [
   {'heading': 'Ask for looks and placement',
    'body': 'Colours, finishes, patterns, strength, a part of the car, a layer. The helper reads every zone, knows the whole finish catalogue, offers whole designs to pick from and undoes its own work step by step.'},
   {'heading': 'Do these yourself',
    'body': 'Open, import, save, Render, export, Auto-deploy and the User ID and car folder. Hand painting with the toolbar (brush, lasso, fill, text) is also yours. The helper says so plainly and tells you where to click.'},
   {'heading': 'Deleting',
    'body': 'It cannot delete a zone. It mutes it and tells you to delete it in the zones list.'},
   {'heading': 'Lighting',
    'body': 'The helper cannot see how iRacing lights the car on track. It sets values only.'}],
  'examples': [
   {'title': 'Ask the right thing', 'goal': 'Know whether to ask or do it yourself',
    'settings': {'Ask': 'make the left side pearl white', 'Do yourself': 'Render and Save to iRacing'},
    'result': 'The helper does the look; you do the file job.'},
   {'title': 'Remove a zone', 'goal': 'Get rid of a zone you no longer want',
    'settings': {'Helper': 'Mutes it', 'You': 'Delete it in the zones list'},
    'result': 'The zone is gone for good.'}],
  'faq': [
   {'q': 'Can the helper render my final paint?', 'a': 'No. Press RENDER in PRO.'},
   {'q': 'Can it add text?', 'a': 'No. Use the Text tool.'},
   {'q': 'Why did it say "I cannot do that"?', 'a': 'It is a file job or hand painting. It tells you where to click.'}],
  'mistakes': [
   {'symptom': 'You keep asking it to save', 'cause': 'Saving is outside what it can do', 'fix': 'Press Render and save in PRO.'},
   {'symptom': 'A "deleted" zone is still in the list', 'cause': 'It only mutes zones', 'fix': 'Delete it from the zones list.'}],
  'protips': ['Say one short thing at a time. Short requests get short, accurate answers and are easy to undo.'],
 },
 'ai_copilot.mcp_tool_list': {
  'level': 'pro',
  'deep': [
   {'heading': 'The tools',
    'body': 'Status check reports the car, its named parts, any missing parts, the layers and the zone count. Read zones lists each zone, what it covers and how much of the paint it really wins. Preview returns the flat paint and, on request, the shine-map picture. Request parts asks you to show Shokker the parts of a car it does not know. Undo takes back the last changes. Look at paint shows the whole flat paint with a 0.1 ruler so positions can be read.'},
   {'heading': 'What the assistant does first',
    'body': 'It checks the setup before designing. If parts are missing it asks you to show them (once per car). Every change also appears in the Shokker AI panel with an Undo button.'},
   {'heading': 'Without pictures',
    'body': 'If the assistant cannot see pictures it works from measured colour shares and zone visibility.'}],
  'examples': [
   {'title': 'What you see in a request', 'goal': 'Follow what Claude is doing',
    'settings': {'Step 1': 'Status check', 'Step 2': 'Read zones', 'Step 3': 'Make changes', 'Step 4': 'Preview'},
    'result': 'Each change shows in the panel with Undo.'},
   {'title': 'Show the car parts', 'goal': 'Answer a request for parts',
    'settings': {'Where': 'AI panel', 'Do': 'Drag a box around each part once per car'},
    'result': 'The assistant can aim at named parts.'}],
  'faq': [
   {'q': 'Can the assistant touch my numbers?', 'a': 'Not unless you name them.'},
   {'q': 'Can I stop it?', 'a': 'Say "undo" or press Undo, and use Take over in SPB.'},
   {'q': 'What is Look at paint?', 'a': 'The whole flat paint with a ruler so the assistant can read positions.'}],
  'mistakes': [
   {'symptom': 'The assistant says parts are missing', 'cause': 'The car is not in the library yet', 'fix': 'Show the parts in the panel once.'},
   {'symptom': 'Changes seem to go nowhere', 'cause': 'More than one Shokker window is open', 'fix': 'Close extra windows; only the connected page receives changes.'}],
  'protips': ['If the assistant seems confused about the car, ask it to run the status check again. It reports exactly which parts are known.'],
 },
}
