"""Prototype disguise construction contracts, including intentionally quiet film."""
FORD='https://media.ford.com/content/fordmedia/feu/at/en/news/2016/10/03/honey--where_d-you-park-the-car--how-an-optical-illusion-helps-s.html'
RETRO='https://www.3m.com/3M/en_US/road-safety-us/resources/road-transportation-safety-center-blog/full-story/~/road-signs-retroreflectivity/?storyid=328c8880-941b-4adc-a9f9-46a1cd79e637'
FILM='https://multimedia.3m.com/mws/media/2398179O/3m-protection-wrap-film-product-bulletin-rev-a.pdf'

def entry(name,desc,carrier,spec,marks,neighbors,chapter='Optical Deception',source=FORD):
    return ('optical',name,chapter,desc,carrier,spec,marks,source,neighbors)

TABLE={
'mul_erlkonig_swirl':entry('Erlkonig Swirl',
 'Opposed black-and-ivory camouflage curls splice through fine foil seams, with broken ink bridges, copper register ticks and etched pearl pockets.',
 'Two oppositely wound nonlinear ink phases interfere and splice across a wandering film plane; negative ivory curls and positive black bridges share connected print boundaries, not isolated coil stamps.',
 'Black print matte dielectric, ivory pockets pearl-coated, foil seams exposed graded metal, register ticks copper and curl etching locally rough.',
 [('positive_curl','positive black camouflage curl'),('negative_curl','ivory counter-curl pocket'),('ink_bridge','broken connecting ink bridge'),('foil_seam','fine exposed film boundary'),('register_tick','small copper printing register'),('curl_etch','fine rough cut inside a printed curl')],
 [('lsk_tesla_streamer','exposed conductor coils rather than opposed printed ink phases'),('mul_confusion_blob','amorphous masks rather than counterwound curls')]),
'mul_confusion_blob':entry('Confusion Blob',
 'Interlocking amorphous print masks erase panel cues: chalk islands, graphite channels, inner copper keylines and differently coated pigment pockets.',
 'Two independent fine amorphous pigment fields interlock with different thresholds; inner keylines, bridge voids and clipped print grain create masks across the whole surface rather than stamped blobs.',
 'Chalk islands rough dielectric, graphite channels partly coated, copper keylines graded metal, bridge voids matte and pigment pockets locally pearl-coated.',
 [('chalk_island','fine positive amorphous print mask'),('graphite_channel','connected negative mask channel'),('copper_keyline','inner registered metal keyline'),('bridge_void','small erased joining pocket'),('pigment_pocket','second print field within a mask'),('print_grain','fine grain clipped to its own printed material')],
 [('lsk_static_creep','doubled conductor contour maze rather than filled two-field print masks'),('mul_erlkonig_swirl','paired winding curls rather than amorphous threshold masks')]),
'mul_shutline_fake':entry('Fake Shutline',
 'Contradictory tiny panel gaps cut a false body surface into bevelled jigsaw planes, with offset hinge ticks, stamped seam numbers and coated false shadows.',
 'Irregular hierarchical rectangular panel partitions are cut by contradictory oblique false gaps; short hinge registrations, split seam intersections and differently shaded printed planes defeat a single coherent body reading.',
 'False gap ink matte nonmetal, printed panels coated pearl, bevel witness edges graded metal, hinge ticks polished and seam stamps subdued dielectric.',
 [('false_gap','printed contradictory panel gap'),('jigsaw_plane','fine independent fake body plane'),('bevel_witness','fine registered bevel highlight'),('hinge_tick','offset printed hinge registration'),('seam_stamp','small seam identifier engraving'),('false_shadow','coated shadow printed beside a fake gap')],
 [('mul_edge_chamfer','nested contradictory bevels rather than jigsaw panel-gap partitions'),('wrap_panel_seam','actual applied panel steps rather than printed contradictory gaps')]),
'mul_foam_clad':entry('Foam Cladding',
 'Fine strapped protective foam has crowded closed-cell cushions, porous compression rims, dark strap roots and small exposed fastening seats.',
 'Crowded irregular closed-cell cushion blocks carry rooted micro-pores and flattened compression shoulders; crossing fine straps seat into the foam and expose tiny fastening contacts.',
 'Foam deliberately stays nonmetal and mostly matte; compressed shoulders and straps have distinct roughness/coat tiers, pores remain dry and small fasteners are exposed metal.',
 [('foam_cushion','fine closed-cell protective block'),('compression_rim','flattened cushion shoulder'),('foam_pore','small rooted closed-cell pore'),('holding_strap','fine strap across protective foam'),('strap_root','dark compression beside a strap'),('fastening_seat','small exposed attachment contact')],
 [('mul_bubble_clad','sealed smooth air sheet rather than porous compressible foam'),('wrap_microbubble','small trapped air under film rather than padded protective cladding')],chapter='Filmcraft',source=FILM),
'mul_bubble_clad':entry('Bubble Cladding',
 'Dense protective air quilts press against translucent cover film, with sealed cells, doubled weld seams, flattened contact crescents and tiny taped witness edges.',
 'Staggered inflated air cells physically overlap an independent cover film; double weld seams, flattened contact crescents and small tape witnesses define a protective cushion sheet rather than isolated surface blisters.',
 'Air cell film nonmetal glossy dielectric, sealed welds rougher, flattened contacts partly matte, witness tape subdued and cover film graded clearcoat.',
 [('air_quilt','inflated protective air cell'),('double_weld','paired sealed cell boundary'),('contact_crescent','flattened cell contact against cover film'),('cover_film','continuous translucent outer film'),('tape_witness','fine holding-tape contact'),('cell_root','dark seated cushion root')],
 [('wrap_microbubble','trapped small film defects rather than manufactured protective cushions'),('mul_foam_clad','porous foam blocks rather than sealed smooth air cells')],chapter='Filmcraft',source=FILM),
'mul_countershade':entry('Countershade',
 'Backwards shading cancels tiny barrel forms: inverted light belts, dark false crowns, pale underside lips and independently coated registration cuts.',
 'Fine bent barrel plates carry inverted printed shading against their own geometric shoulder; offset underside lips, clipped axial cuts and opposing registration marks make the countershading visible without colour.',
 'Dark false crowns matte print, pale undersides coated pearl, plate shoulders graded foil, axial cuts rough and register contacts polished.',
 [('barrel_plate','fine bent apparent barrel face'),('false_crown','dark printed highlight reversal'),('underside_lip','pale printed underside'),('plate_shoulder','geometric edge of the false barrel'),('axial_cut','fine clipped registration cut'),('register_contact','small opposing registration witness')],
 [('mul_false_shadow','invented crossing creases rather than inverted barrel shading'),('mul_edge_chamfer','nested edge bevels rather than cancelled barrel form')]),
'mul_false_shadow':entry('False Shadow',
 'Impossible shadow ribbons cross folded print planes: offset cast-shadow wedges, erasure lips, fine hatch pockets and polished witness vertices.',
 'Independent diagonal shadow ribbons pass across an opposing network of curved false folds; their offset lips and contradictory cast wedges create impossible occlusion, with hatches clipped to the printed shadow.',
 'Shadow ink rough dielectric, erased lips pearl-coated, fold planes graded foil, hatch pockets partly matte and witness vertices exposed metal.',
 [('shadow_ribbon','invented dark crossing shadow'),('cast_wedge','contradictory printed cast shadow'),('erasure_lip','pale edge erasing the implied crease'),('fold_plane','coated opposing false fold face'),('hatch_pocket','fine registration inside shadow ink'),('witness_vertex','small polished printed corner witness')],
 [('mul_countershade','inverted barrel illumination rather than contradictory cast-shadow crossings'),('astra_causal_origami','physical fold tessellation rather than incompatible printed occlusion')]),
'mul_qr_scramble':entry('QR Scramble Matrix',
 'Scrambled sensor-style matrices interlock finder assemblies, broken timing rails, foil data modules and matte erased windows across a fine digital skin.',
 'Fine 8px data modules build larger finder assemblies and broken timing rails; interlocking matrix windows and independent registration notches create intentionally scrambled decorative code, not a valid scan promise.',
 'Data ink matte nonmetal, finder rails graded foil, timing cells coated pearl, erased windows rough dielectric and register notches polished; each module owns its material state.',
 [('data_module','fine 8px binary print module'),('finder_assembly','nested assembly of fine finder modules'),('timing_rail','broken alternating module rail'),('erased_window','small removed matrix region'),('foil_cell','exposed foil behind an erased data cell'),('register_notch','fine polished matrix registration notch')],
 [('mul_pixel_break','unequal hierarchical rectangles rather than finder/timing code grammar'),('wrap_print_band','continuous printer passes rather than sensor-style binary modules')]),
'mul_wireframe':entry('Wireframe Print',
 'A projected impossible truss floats across fine coated facets, with foreshortened cross braces, copper vertex seats, dark mesh voids and clipped dashed occlusion.',
 'Two differently projected fine wire lattices intersect through skewed local facets; cross braces, seated vertices and dashed occlusion distinguish printed false geometry from a regular flat grid.',
 'Wire rails graded exposed metal, mesh voids matte dielectric, facet fill coated pearl, copper vertices polished and occluded dashed rails rougher printed ink.',
 [('wire_rail','fine projected main truss'),('cross_brace','foreshortened diagonal structural print'),('vertex_seat','small copper truss node'),('mesh_void','dark apparent opening in the mesh'),('facet_fill','coated false surface behind the wire'),('occluded_dash','fine dashed rail disappearing behind a false facet')],
 [('lsk_jacobs_ladder','paired electrodes and climbing arcs rather than projected braces'),('mul_moire_defeat','crossed optical rulings rather than discrete truss nodes')]),
'mul_matte_cover':entry('Matte Cover Cloth',
 'A deliberately quiet charcoal disguise cloth carries fine crossed yarn, compressed seam lips, dry abrasion sweeps, small pores and uneven tension creases.',
 'Fine crinkled crossed polymer yarn is interrupted by compressed seam lips and short tension creases; abrasion sweeps and pores belong to the actual cloth structure, not a random spec deck.',
 'Cloth stays nonmetal and matte by design; yarn, seam compression and abrasion have different dry roughness/coat tiers, while pores remain coat-reflection-minimized and dark.',
 [('crossed_yarn','fine crinkled polymer cloth weave'),('compressed_lip','pressed seam compression'),('tension_crease','short rooted cloth tension fold'),('abrasion_sweep','fine dry wear aligned to yarn'),('cloth_pore','small gap between yarn'),('matte_fibre','individually tiered dry polymer filament')],
 [('wrap_twill_film','decorative diagonal twill rather than crinkled matte protective cloth'),('mul_decoy_blackout','erased badge/lamp masks rather than crossed cloth anatomy')],chapter='Filmcraft',source=FILM),
'mul_retro_patch':entry('Retroreflective Patch',
 'Fine glass-bead patches expose pale lens hearts, dark return cups, printed patch seams and minute foil backings beneath a clear binder.',
 'Crowded fine enclosed glass-bead lenses have offset return cups and pale hearts; independent patch seams, reflective backings and binder menisci form a lens sheet, not vintage graphics.',
 'Glass lenses glossy dielectric, backing foil graded metal, return cups rougher, binder menisci coated and patch seams matte; existing shader approximates the material without claiming a retroreflection shader.',
 [('glass_lens','fine enclosed glass bead'),('return_cup','dark seated lens return cavity'),('pale_heart','small bright lens centre'),('foil_backing','exposed reflective lens backing'),('binder_meniscus','clear binder at a lens edge'),('patch_seam','fine applied reflective-sheet boundary')],
 [('wrap_lens_array','large optical microlens ruling rather than packed glass-bead sheet'),('mul_bubble_clad','inflated air cushions rather than enclosed bead reflectors')],source=RETRO),
'mul_tape_seam':entry('Gaffer Tape Seam',
 'Crossing fine gaffer strips hold the disguise: torn yarn edges, pressed adhesive lips, folded tape creases, witness fibres and dark overlap counts.',
 'Independent crossing tape passes have varying overlap order; torn yarn edges, adhesive undercuts and short compression creases follow each strip, with witness fibres rooted in actual tape tears.',
 'Gaffer cloth matte nonmetal, pressed adhesive smoother dielectric, torn fibres dry, overlap roots rough and sparse witness print partly pearl-coated.',
 [('gaffer_strip','fine crossing cloth tape'),('torn_yarn','ragged exposed tape edge'),('adhesive_lip','pressed adhesive below a tape edge'),('fold_crease','short compressed fold inside a strip'),('overlap_root','dark multi-pass tape overlap'),('witness_fibre','small fibre drawn from a tear')],
 [('bth_tape_ridge','cured paint ridge rather than removable cloth tape passes'),('wrap_overlap_ghost','transparent film overlap rather than torn cloth strips')],chapter='Filmcraft',source=FILM),
'mul_pixel_break':entry('Pixel Break Grid',
 'Unequal fine digital rectangles break depth cues through foil planes, black erasure slots, bevelled pixel edges and tiny segmented scan rails.',
 'Hierarchical guillotine partitions stop at 8–32px rectangles; each pixel has a separately registered erasure slot, edge bevel and clipped scan-rail segment, rather than uniform binary modules.',
 'Foil pixels graded metal, ink pixels matte dielectric, erased slots rough, bevel edges polish and scan rails partly coated; material tiers belong to pixel identity.',
 [('foil_pixel','unequal fine exposed foil rectangle'),('ink_pixel','matte printed rectangle'),('erasure_slot','small registered missing pixel strip'),('pixel_bevel','fine polished digital edge'),('scan_rail','segmented fine scan line'),('register_corner','small pixel-corner witness')],
 [('mul_qr_scramble','finder and timing code rather than unequal rectangle partitions'),('wrap_hex_ppf','hexagonal material tesserae rather than hierarchical digital rectangles')]),
'mul_decoy_blackout':entry('Decoy Blackout',
 'Fine badge and lamp masks disappear into charcoal: soft blackout fields, gloss witness rims, torn adhesive teeth and hidden coated false-light apertures.',
 'Irregular overlapping black badge/lamp masks are crossed by fine torn adhesive teeth and deliberately hidden gloss apertures; witness rims and small erase cuts create material-only false geometry in restrained paint.',
 'Blackout bodies matte nonmetal, hidden apertures deliberately glossy dielectric, torn adhesive rough, witness rims pearl-polished and erase cuts coat-reflection-minimized; restrained paint is intentional.',
 [('blackout_mask','fine overlapped black badge/lamp mask'),('hidden_aperture','deliberate gloss-only false light'),('witness_rim','fine polished mask edge'),('adhesive_tooth','small ragged adhesive contact'),('erase_cut','fine coat-reflection-minimized erase incision'),('overlap_field','dark separately tiered overlap')],
 [('mul_matte_cover','woven dry cloth rather than deliberately hidden false lights'),('mul_false_shadow','visible printed shadow ribbons rather than blackout masks')]),
'mul_edge_chamfer':entry('Edge Chamfer',
 'Nested impossible bevels divide tiny octagonal plates into silver lips, dark recess claims, copper counter-edges and coated centre windows.',
 'Fine truncated octagonal plates contain contradictory inner and outer chamfers; offset counter-edges, centre windows and clipped corner cuts produce ambiguous printed depth with a unique nested topology.',
 'Silver outer lips high metal, copper counter-edges graded metal, dark recess print matte, centre windows coated pearl and corner cuts rougher dielectric.',
 [('octagonal_plate','fine truncated apparent plate'),('outer_chamfer','polished outer false bevel'),('inner_recess','dark contradictory recess claim'),('counter_edge','offset copper inner bevel'),('centre_window','coated central printed face'),('corner_cut','fine clipped corner registration cut')],
 [('mul_shutline_fake','contradictory jigsaw panel gaps rather than nested octagonal bevels'),('astra_cobalt_guillotine','cut facet fields rather than nested printed chamfer claims')])
}
