// ===== FINISH DATA =====
// ===== 24K ARSENAL: 155 Bases × 155 Patterns + 155 Specials =====
// 155 bases × 155 patterns = 24025 base+pattern combos + 155 specials = 24,180 total
const BASES = [
    {id: "gloss", name: "Gloss", desc: "Standard glossy clearcoat", swatch: "#44aa44"},
    {id: "matte", name: "Matte", desc: "Flat matte zero shine", swatch: "#666666"},
    {id: "satin", name: "Satin", desc: "Soft satin partial clearcoat", swatch: "#888888"},
    {id: "flat_black", name: "Flat Black", desc: "Dead flat zero-sheen — no reflection at all", swatch: "#111111"},
    {id: "primer", name: "Primer", desc: "Raw flat primer gray zero sheen", swatch: "#808080"},
    {id: "clear_matte", name: "Clear Matte", desc: "Matte clearcoat — flat but protected", swatch: "#666666"},
    {id: "wet_look", name: "Wet Look", desc: "Deep wet clearcoat show shine", swatch: "#888888"},
    {id: "silk", name: "Silk", desc: "Silky smooth fabric-like sheen", swatch: "#888888"},
    {id: "eggshell", name: "Eggshell", desc: "Soft low-sheen like eggshell wall paint", swatch: "#ddddcc"},
    {id: "semi_gloss", name: "Semi-Gloss", desc: "Between satin and gloss — utility finish", swatch: "#44aa44"},
    {id: "metallic", name: "Metallic", desc: "Standard metallic with visible flake", swatch: "#aabbcc"},
    {id: "pearl", name: "Pearl", desc: "Pearlescent iridescent sheen", swatch: "#dde0e8"},
    {id: "candy", name: "Candy", desc: "Deep wet candy transparent glass", swatch: "#cc2244"},
    {id: "satin_metal", name: "Satin Metal", desc: "Subtle brushed satin metallic", swatch: "#888888"},
    {id: "gunmetal", name: "Gunmetal", desc: "Dark aggressive blue-gray metallic", swatch: "#888888"},
    {id: "copper", name: "Copper", desc: "Warm oxidized copper metallic", swatch: "#cc7744"},
    {id: "pearlescent_white", name: "Pearl White", desc: "Tri-coat pearlescent white deep sparkle", swatch: "#dde0e8"},
    {id: "metal_flake_base", name: "Metal Flake", desc: "Heavy visible metal flake base coat", swatch: "#888888"},
    {id: "candy_apple", name: "Candy Apple", desc: "Classic candy apple red-style transparent tint", swatch: "#cc2244"},
    {id: "midnight_pearl", name: "Midnight Pearl", desc: "Deep dark pearlescent with hidden sparkle", swatch: "#dde0e8"},
    {id: "champagne", name: "Champagne", desc: "Warm gold-silver champagne metallic", swatch: "#888888"},
    {id: "pewter", name: "Pewter", desc: "Dark gray aged pewter metallic", swatch: "#888888"},
    {id: "chrome", name: "Chrome", desc: "Pure mirror chrome", swatch: "#e8e8ee"},
    {id: "satin_chrome", name: "Satin Chrome", desc: "BMW silky satin chrome", swatch: "#e8e8ee"},
    {id: "dark_chrome", name: "Dark Chrome", desc: "Smoked dark chrome black mirror", swatch: "#e8e8ee"},
    {id: "surgical_steel", name: "Surgical Steel", desc: "Medical grade mirror surgical steel", swatch: "#888888"},
    {id: "mirror_gold", name: "Mirror Gold", desc: "Pure mirror gold chrome", swatch: "#ddddee"},
    {id: "candy_chrome", name: "Candy Chrome", desc: "Candy-tinted chrome — deep color over mirror", swatch: "#e8e8ee"},
    {id: "black_chrome", name: "Black Chrome", desc: "Near-black highly reflective chrome", swatch: "#e8e8ee"},
    {id: "blue_chrome", name: "Blue Chrome", desc: "Tinted blue mirror chrome", swatch: "#e8e8ee"},
    {id: "red_chrome", name: "Red Chrome", desc: "Tinted red mirror chrome", swatch: "#e8e8ee"},
    {id: "antique_chrome", name: "Antique Chrome", desc: "Slightly aged imperfect chrome", swatch: "#e8e8ee"},
    {id: "spectraflame", name: "Spectraflame", desc: "Hot Wheels candy-over-chrome deep sparkle", swatch: "#888888"},
    {id: "chameleon", name: "Chameleon", desc: "Dual-tone color-shift angle-dependent", swatch: "#888888"},
    {id: "iridescent", name: "Iridescent", desc: "Rainbow angle-shift iridescent wrap", swatch: "#888888"},
    {id: "tinted_clear", name: "Tinted Clear", desc: "Deep tinted clearcoat over base color", swatch: "#888888"},
    {id: "candy_burgundy", name: "Candy Burgundy", desc: "Deep burgundy candy transparent coat", swatch: "#cc2244"},
    {id: "candy_emerald", name: "Candy Emerald", desc: "Rich emerald green candy coat", swatch: "#cc2244"},
    {id: "candy_cobalt", name: "Candy Cobalt", desc: "Deep cobalt blue candy transparent", swatch: "#cc2244"},
    {id: "tri_coat_pearl", name: "Tri-Coat Pearl", desc: "Three-stage pearl base+mid+clear", swatch: "#dde0e8"},
    {id: "moonstone", name: "Moonstone", desc: "Soft translucent milky shimmer", swatch: "#888888"},
    {id: "opal", name: "Opal", desc: "Fire opal multi-color depth", swatch: "#888888"},
    {id: "satin_wrap", name: "Satin Wrap", desc: "Vinyl wrap satin non-metallic sheen", swatch: "#888888"},
    {id: "liquid_wrap", name: "Liquid Wrap", desc: "Liquid rubber peel coat textured matte", swatch: "#777788"},
    {id: "frozen_matte", name: "Frozen Matte", desc: "BMW Individual frozen matte metallic", swatch: "#666666"},
    {id: "matte_wrap", name: "Matte Wrap", desc: "Dead-flat vinyl wrap zero sheen", swatch: "#666666"},
    {id: "color_flip_wrap", name: "Color Flip Wrap", desc: "Wrap film that shifts color at angles", swatch: "#777788"},
    {id: "chrome_wrap", name: "Chrome Wrap", desc: "Mirror chrome vinyl wrap — slightly textured", swatch: "#e8e8ee"},
    {id: "gloss_wrap", name: "Gloss Wrap", desc: "High-gloss smooth vinyl wrap finish", swatch: "#44aa44"},
    {id: "textured_wrap", name: "Textured Wrap", desc: "Orange-peel textured vinyl wrap", swatch: "#777788"},
    {id: "brushed_wrap", name: "Brushed Wrap", desc: "Brushed metal vinyl wrap film", swatch: "#777788"},
    {id: "stealth_wrap", name: "Stealth Wrap", desc: "Ultra-matte radar-absorbing stealth look", swatch: "#777788"},
    {id: "cerakote", name: "Cerakote", desc: "Mil-spec ceramic tactical coating", swatch: "#888888"},
    {id: "duracoat", name: "Duracoat", desc: "Tactical epoxy durable coating", swatch: "#888888"},
    {id: "powder_coat", name: "Powder Coat", desc: "Thick industrial powder coat finish", swatch: "#888888"},
    {id: "blackout", name: "Blackout", desc: "Stealth murdered-out ultra dark", swatch: "#111111"},
    {id: "sandblasted", name: "Sandblasted", desc: "Raw sandblasted metal rough texture", swatch: "#888888"},
    {id: "vantablack", name: "Vantablack", desc: "Absolute void zero reflection", swatch: "#111111"},
    {id: "mil_spec_od", name: "Mil-Spec OD", desc: "Olive drab military standard coating", swatch: "#888888"},
    {id: "mil_spec_tan", name: "Mil-Spec Tan", desc: "Desert tan flat tactical coat", swatch: "#888888"},
    {id: "armor_plate", name: "Armor Plate", desc: "Heavy rolled steel armor plating", swatch: "#889988"},
    {id: "submarine_black", name: "Sub Black", desc: "Anechoic submarine hull coating", swatch: "#111111"},
    {id: "gunship_gray", name: "Gunship Gray", desc: "Military aircraft flat gray", swatch: "#888888"},
    {id: "battleship_gray", name: "Battleship Gray", desc: "Naval warship haze gray coating", swatch: "#888888"},
    {id: "ceramic", name: "Ceramic", desc: "Ultra-smooth ceramic coating deep wet shine", swatch: "#5588aa"},
    {id: "piano_black", name: "Piano Black", desc: "Deep piano black ultra-gloss mirror finish", swatch: "#111111"},
    {id: "porcelain", name: "Porcelain", desc: "White porcelain enamel glassy finish", swatch: "#eeeeff"},
    {id: "obsidian", name: "Obsidian", desc: "Volcanic glass deep black mirror sheen", swatch: "#111115"},
    {id: "crystal_clear", name: "Crystal Clear", desc: "Optically clear crystal glass coat", swatch: "#888888"},
    {id: "tempered_glass", name: "Tempered Glass", desc: "Safety glass smooth hard surface", swatch: "#aaddee"},
    {id: "ceramic_matte", name: "Ceramic Matte", desc: "Matte ceramic nano-coating", swatch: "#666666"},
    {id: "enamel", name: "Enamel", desc: "Hard baked enamel glossy traditional paint", swatch: "#4488aa"},
    {id: "race_day_gloss", name: "Race Day Gloss", desc: "Fresh-from-the-trailer showroom glossy", swatch: "#44aa44"},
    {id: "stock_car_enamel", name: "Stock Car Enamel", desc: "Traditional thick NASCAR enamel paint", swatch: "#4488aa"},
    {id: "sprint_car_chrome", name: "Sprint Car Chrome", desc: "Sprint car bright polished chrome", swatch: "#e8e8ee"},
    {id: "dirt_track_satin", name: "Dirt Track Satin", desc: "Slightly dusty satin from dirt track use", swatch: "#888888"},
    {id: "endurance_ceramic", name: "Endurance Ceramic", desc: "24hr endurance race ceramic protection", swatch: "#5588aa"},
    {id: "rally_mud", name: "Rally Mud", desc: "Partially mud-splattered rally coating", swatch: "#776644"},
    {id: "drag_strip_gloss", name: "Drag Strip Gloss", desc: "Ultra-polished quarter-mile show finish", swatch: "#44aa44"},
    {id: "victory_lane", name: "Victory Lane", desc: "Champagne-soaked celebration metallic sparkle", swatch: "#ccaa55"},
    {id: "barn_find", name: "Barn Find", desc: "Decades-old stored car faded paint", swatch: "#887766"},
    {id: "rat_rod_primer", name: "Rat Rod Primer", desc: "Intentionally rough unfinished primer", swatch: "#808080"},
    {id: "pace_car_pearl", name: "Pace Car Pearl", desc: "Official pace car triple-pearl coat", swatch: "#dde0e8"},
    {id: "heat_shield", name: "Heat Shield", desc: "Exhaust heat-wrap reflective coating", swatch: "#cc8844"},
    {id: "pit_lane_matte", name: "Pit Lane Matte", desc: "Working pit lane matte with slight grime", swatch: "#666666"},
    {id: "asphalt_grind", name: "Asphalt Grind", desc: "Rough asphalt-ground surface texture", swatch: "#555555"},
    {id: "checkered_chrome", name: "Checkered Chrome", desc: "Polished chrome with checkered reflection", swatch: "#e8e8ee"},
    {id: "brushed_titanium", name: "Brushed Titanium", desc: "Heavy directional titanium grain", swatch: "#8899aa"},
    {id: "anodized", name: "Anodized", desc: "Gritty matte anodized aluminum", swatch: "#888888"},
    {id: "frozen", name: "Frozen", desc: "Frozen icy matte metal", swatch: "#888888"},
    {id: "rose_gold", name: "Rose Gold", desc: "Pink-gold metallic warm shimmer", swatch: "#ccaa55"},
    {id: "diamond_coat", name: "Diamond Coat", desc: "Diamond dust ultra-fine sparkle coat", swatch: "#888888"},
    {id: "raw_aluminum", name: "Raw Aluminum", desc: "Bare unfinished aluminum sheet metal", swatch: "#888888"},
    {id: "titanium_raw", name: "Titanium Raw", desc: "Raw unpolished titanium industrial", swatch: "#8899aa"},
    {id: "brushed_aluminum", name: "Brushed Aluminum", desc: "Brushed natural aluminum directional grain", swatch: "#888888"},
    {id: "liquid_titanium", name: "Liquid Titanium", desc: "Molten titanium pooling mirror", swatch: "#8899aa"},
    {id: "tungsten", name: "Tungsten", desc: "Ultra-dense dark gray tungsten", swatch: "#667788"},
    {id: "platinum", name: "Platinum", desc: "Pure platinum bright white metal", swatch: "#ddddee"},
    {id: "cobalt_metal", name: "Cobalt Metal", desc: "Blue-gray cobalt metallic sheen", swatch: "#4466aa"},
    {id: "patina_bronze", name: "Patina Bronze", desc: "Aged oxidized bronze with green patina", swatch: "#668855"},
    {id: "rugged", name: "Rugged", desc: "Rugged off-road tactical rough coating", swatch: "#888888"},
    {id: "galvanized", name: "Galvanized", desc: "Hot-dip galvanized zinc crystalline", swatch: "#888888"},
    {id: "heat_treated", name: "Heat Treated", desc: "Heat-treated titanium blue-gold zones", swatch: "#cc8844"},
    {id: "sun_baked", name: "Sun Baked", desc: "UV-damaged sun-faded peeling clear", swatch: "#888888"},
    {id: "salt_corroded", name: "Salt Corroded", desc: "Coastal salt air corroded metal", swatch: "#888888"},
    {id: "desert_worn", name: "Desert Worn", desc: "Sand-blasted desert weathered surface", swatch: "#998877"},
    {id: "acid_rain", name: "Acid Rain", desc: "Chemical rain etched paint damage", swatch: "#888888"},
    {id: "oxidized_copper", name: "Oxidized Copper", desc: "Fully green-oxidized copper (Statue of Liberty)", swatch: "#cc7744"},
    {id: "vintage_chrome", name: "Vintage Chrome", desc: "1950s chrome with cloudy oxidation spots", swatch: "#e8e8ee"},
    {id: "smoked", name: "Smoked", desc: "Smoked tinted darkened clearcoat", swatch: "#888888"},
    {id: "factory_basecoat", name: "Factory Basecoat", desc: "Standard OEM factory metallic basecoat", swatch: "#888888"},
    {id: "showroom_clear", name: "Showroom Clear", desc: "Freshly detailed concours clearcoat", swatch: "#888888"},
    {id: "fleet_white", name: "Fleet White", desc: "Government/fleet plain white gloss", swatch: "#eeeeee"},
    {id: "taxi_yellow", name: "Taxi Yellow", desc: "NYC taxi cab bright yellow gloss", swatch: "#ccaa00"},
    {id: "school_bus", name: "School Bus", desc: "National school bus chrome yellow", swatch: "#ccaa22"},
    {id: "fire_engine", name: "Fire Engine", desc: "Deep wet fire apparatus red gloss", swatch: "#cc2222"},
    {id: "ambulance_white", name: "Ambulance White", desc: "High-visibility emergency white reflective", swatch: "#ffffff"},
    {id: "police_black", name: "Police Black", desc: "Law enforcement glossy black", swatch: "#111111"},
    {id: "dealer_pearl", name: "Dealer Pearl", desc: "Dealer premium tri-coat pearl upgrade", swatch: "#dde0e8"},
    {id: "carbon_base", name: "Carbon Base", desc: "Raw exposed carbon fiber base material", swatch: "#333333"},
    {id: "kevlar_base", name: "Kevlar Base", desc: "Ballistic kevlar aramid fiber base", swatch: "#998844"},
    {id: "fiberglass", name: "Fiberglass", desc: "Raw fiberglass gelcoat semi-gloss", swatch: "#aaddee"},
    {id: "carbon_ceramic", name: "Carbon Ceramic", desc: "Brake rotor carbon-ceramic composite", swatch: "#333333"},
    {id: "aramid", name: "Aramid", desc: "Woven aramid fiber natural gold-tan", swatch: "#888888"},
    {id: "graphene", name: "Graphene", desc: "Single-layer graphene ultra-thin metallic", swatch: "#889999"},
    {id: "forged_composite", name: "Forged Composite", desc: "Lamborghini-style forged carbon composite", swatch: "#555555"},
    {id: "hybrid_weave", name: "Hybrid Weave", desc: "Carbon-kevlar hybrid bi-weave material", swatch: "#666655"},
    {id: "satin_gold", name: "Satin Gold", desc: "Satin gold metallic warm sheen", swatch: "#888888"},
    {id: "bentley_silver", name: "Bentley Silver", desc: "Rolls-Royce/Bentley ultra-fine silver", swatch: "#ccccdd"},
    {id: "ferrari_rosso", name: "Ferrari Rosso", desc: "Ferrari Rosso Corsa deep wet red", swatch: "#cc1111"},
    {id: "lamborghini_verde", name: "Lambo Verde", desc: "Lamborghini Verde Mantis electric green", swatch: "#44cc22"},
    {id: "porsche_pts", name: "Porsche PTS", desc: "Porsche Paint-to-Sample custom deep coat", swatch: "#888844"},
    {id: "mclaren_orange", name: "McLaren Orange", desc: "McLaren Papaya Spark vivid orange", swatch: "#ff6600"},
    {id: "bugatti_blue", name: "Bugatti Blue", desc: "Bugatti Bleu de France deep two-tone", swatch: "#2244aa"},
    {id: "koenigsegg_clear", name: "Koenigsegg Clear", desc: "Clear carbon visible weave (Koenigsegg style)", swatch: "#333333"},
    {id: "pagani_tricolore", name: "Pagani Tricolore", desc: "Pagani chameleon tricolore shift paint", swatch: "#8844aa"},
    {id: "maybach_two_tone", name: "Maybach Two-Tone", desc: "Mercedes-Maybach duo-tone luxury split", swatch: "#aabbcc"},
    {id: "plasma_metal", name: "Plasma Metal", desc: "Electric plasma purple-blue metallic shift", swatch: "#8844ff"},
    {id: "burnt_headers", name: "Burnt Headers", desc: "Exhaust header heat-treated gold-blue oxide", swatch: "#888888"},
    {id: "mercury", name: "Mercury", desc: "Liquid mercury pooling desaturated chrome flow", swatch: "#888888"},
    {id: "electric_ice", name: "Electric Ice", desc: "Icy electric blue metallic cold neon shimmer", swatch: "#888888"},
    {id: "volcanic", name: "Volcanic", desc: "Volcanic ash dark gritty desaturated matte", swatch: "#888888"},
    {id: "shokk_pulse", name: "SHOKK Pulse", desc: "Electric pulse wave metallic — Shokker signature", swatch: "#ff4400"},
    {id: "shokk_venom", name: "SHOKK Venom", desc: "Toxic acid green-yellow metallic reactive", swatch: "#ff4400"},
    {id: "shokk_blood", name: "SHOKK Blood", desc: "Deep arterial red metallic with dark edge", swatch: "#ff4400"},
    {id: "shokk_void", name: "SHOKK Void", desc: "Near-vantablack with subtle edge shimmer", swatch: "#ff4400"},
    {id: "shokk_static", name: "SHOKK Static", desc: "Crackling static interference metallic", swatch: "#ff4400"},
    {id: "quantum_black", name: "Quantum Black", desc: "Near-perfect light absorption ultra-black", swatch: "#111111"},
    {id: "neutron_star", name: "Neutron Star", desc: "Impossibly bright compressed mirror", swatch: "#ffffff"},
    {id: "plasma_core", name: "Plasma Core", desc: "Glowing plasma reactor core metallic", swatch: "#8844ff"},
    {id: "dark_matter", name: "Dark Matter", desc: "Ultra-dark with hidden angle-dependent reveal", swatch: "#111122"},
    {id: "superconductor", name: "Superconductor", desc: "Perfect zero-resistance mirror surface", swatch: "#eeeeee"},
    {id: "bioluminescent", name: "Bioluminescent", desc: "Deep sea organism soft glow finish", swatch: "#22cc88"},
    {id: "solar_panel", name: "Solar Panel", desc: "Photovoltaic solar cell dark blue-black", swatch: "#334466"},
    {id: "holographic_base", name: "Holographic Base", desc: "Full holographic rainbow prismatic base", swatch: "#ff88cc"},
];

const PATTERNS = [
    {id: "none", name: "None (Base Only)", desc: "Pure base material — no texture overlay", swatch: "transparent"},
    {id: "carbon_fiber", name: "Carbon Fiber", desc: "Woven 2x2 twill weave", swatch: "#667788"},
    {id: "forged_carbon", name: "Forged Carbon", desc: "Chopped irregular carbon chunks", swatch: "#667788"},
    {id: "carbon_4x4", name: "Carbon 4x4", desc: "Larger 4-harness satin weave carbon", swatch: "#667788"},
    {id: "carbon_spread_tow", name: "Spread Tow", desc: "Flat spread tow ultra-thin carbon tape", swatch: "#667788"},
    {id: "carbon_uni", name: "Uni-Directional", desc: "All fibers running one direction", swatch: "#667788"},
    {id: "tweed_weave", name: "Tweed Weave", desc: "Loose irregular tweed textile pattern", swatch: "#667788"},
    {id: "basket_weave", name: "Basket Weave", desc: "Over-under basket weave pattern", swatch: "#667788"},
    {id: "chainlink", name: "Chain Link", desc: "Chain-link fence diagonal wire grid", swatch: "#999999"},
    {id: "kevlar_weave", name: "Kevlar Weave", desc: "Tight aramid fiber golden weave", swatch: "#667788"},
    {id: "nanoweave", name: "Nanoweave", desc: "Microscopic tight-knit nano fiber pattern", swatch: "#667788"},
    {id: "diamond_plate", name: "Diamond Plate", desc: "Industrial raised diamond tread", swatch: "#aaaaaa"},
    {id: "hex_mesh", name: "Hex Mesh", desc: "Honeycomb wire grid", swatch: "#888899"},
    {id: "hammered", name: "Hammered", desc: "Hand-hammered dimple pattern", swatch: "#667788"},
    {id: "chainmail", name: "Chainmail", desc: "Interlocking metal ring mesh", swatch: "#999999"},
    {id: "metal_flake", name: "Metal Flake", desc: "Coarse visible metallic flake", swatch: "#667788"},
    {id: "mega_flake", name: "Mega Flake", desc: "Large hex glitter flake facets", swatch: "#667788"},
    {id: "rivet_grid", name: "Rivet Grid", desc: "Evenly spaced industrial rivet dots", swatch: "#556677"},
    {id: "corrugated", name: "Corrugated", desc: "Corrugated sheet metal parallel ridges", swatch: "#667788"},
    {id: "perforated", name: "Perforated", desc: "Evenly punched round hole grid", swatch: "#667788"},
    {id: "expanded_metal", name: "Expanded Metal", desc: "Stretched diamond-shape expanded mesh", swatch: "#999999"},
    {id: "grating", name: "Grating", desc: "Industrial floor grating parallel bars", swatch: "#667788"},
    {id: "knurled", name: "Knurled", desc: "Machine knurling diagonal cross-hatch grip pattern", swatch: "#667788"},
    {id: "wood_grain", name: "Wood Grain", desc: "Natural flowing wood grain texture", swatch: "#8a6633"},
    {id: "marble", name: "Marble", desc: "Soft noise veins like polished marble", swatch: "#ddccbb"},
    {id: "lava_flow", name: "Lava Flow", desc: "Flowing molten rock with hot cracks", swatch: "#cc4411"},
    {id: "rain_drop", name: "Rain Drop", desc: "Water droplet beading on surface", swatch: "#667788"},
    {id: "frost_crystal", name: "Frost Crystal", desc: "Ice crystal branching fractals", swatch: "#99ccee"},
    {id: "topographic", name: "Topographic", desc: "Elevation contour map lines", swatch: "#667788"},
    {id: "tree_bark", name: "Tree Bark", desc: "Rough furrowed tree bark texture", swatch: "#667788"},
    {id: "coral_reef", name: "Coral Reef", desc: "Organic branching coral growth structure", swatch: "#cc6644"},
    {id: "river_stone", name: "River Stone", desc: "Smooth rounded river pebble mosaic", swatch: "#4488aa"},
    {id: "glacier_crack", name: "Glacier Crack", desc: "Deep blue-white glacial ice fissure network", swatch: "#667788"},
    {id: "chevron", name: "Chevron", desc: "Repeating V/arrow stripe pattern", swatch: "#667788"},
    {id: "houndstooth", name: "Houndstooth", desc: "Classic houndstooth check textile", swatch: "#667788"},
    {id: "plaid", name: "Plaid", desc: "Overlapping tartan plaid bands", swatch: "#667788"},
    {id: "crosshatch", name: "Crosshatch", desc: "Overlapping diagonal pen stroke lines", swatch: "#886644"},
    {id: "celtic_knot", name: "Celtic Knot", desc: "Interwoven flowing band knot pattern", swatch: "#667788"},
    {id: "pinstripe", name: "Pinstripe", desc: "Thin parallel racing stripes", swatch: "#556688"},
    {id: "herringbone", name: "Herringbone", desc: "V-shaped zigzag brick/tile pattern", swatch: "#778899"},
    {id: "argyle", name: "Argyle", desc: "Diamond/rhombus overlapping argyle pattern", swatch: "#667788"},
    {id: "greek_key", name: "Greek Key", desc: "Continuous right-angle meander border", swatch: "#667788"},
    {id: "art_deco", name: "Art Deco", desc: "1920s geometric fan/sunburst motif", swatch: "#667788"},
    {id: "tessellation", name: "Tessellation", desc: "Interlocking M.C. Escher-style tile shapes", swatch: "#667788"},
    {id: "yin_yang", name: "Yin Yang", desc: "Repeating yin-yang circular duality symbol grid", swatch: "#888888"},
    {id: "tire_tread", name: "Tire Tread", desc: "Directional V-groove rubber tread", swatch: "#444444"},
    {id: "checkered_flag", name: "Checkered Flag", desc: "Classic racing checkered flag grid", swatch: "#ddddee"},
    {id: "racing_stripe", name: "Racing Stripe", desc: "Bold dual center racing stripes", swatch: "#556688"},
    {id: "starting_grid", name: "Starting Grid", desc: "Grid slot number positions track layout", swatch: "#556677"},
    {id: "tire_smoke", name: "Tire Smoke", desc: "Burnout tire smoke wisps and haze", swatch: "#444444"},
    {id: "skid_marks", name: "Skid Marks", desc: "Black rubber tire skid marks streaks", swatch: "#667788"},
    {id: "asphalt_texture", name: "Asphalt", desc: "Road surface aggregate texture", swatch: "#667788"},
    {id: "pit_lane_marks", name: "Pit Lane", desc: "Pit lane boundary lines and markings", swatch: "#555555"},
    {id: "lap_counter", name: "Lap Counter", desc: "Repeating tally/hash mark lap counter", swatch: "#cc2222"},
    {id: "sponsor_fade", name: "Sponsor Fade", desc: "Gradient fade zones typical of sponsor areas", swatch: "#667788"},
    {id: "rooster_tail", name: "Rooster Tail", desc: "Dirt spray rooster tail splash pattern", swatch: "#667788"},
    {id: "victory_confetti", name: "Victory Confetti", desc: "Scattered celebration confetti and streamers", swatch: "#667788"},
    {id: "trophy_laurel", name: "Trophy Laurel", desc: "Victory laurel wreath repeating motif", swatch: "#667788"},
    {id: "rpm_gauge", name: "RPM Gauge", desc: "Tachometer arc needle sweep pattern", swatch: "#667788"},
    {id: "finish_line", name: "Finish Line", desc: "Bold start/finish line checkered band", swatch: "#667788"},
    {id: "snake_skin", name: "Snake Skin", desc: "Elongated overlapping reptile scales", swatch: "#667788"},
    {id: "leopard", name: "Leopard", desc: "Organic leopard rosette spots", swatch: "#667788"},
    {id: "fishnet", name: "Fishnet", desc: "Diamond mesh fishnet grid", swatch: "#44aa88"},
    {id: "denim", name: "Denim", desc: "Blue jean diagonal twill weave", swatch: "#667788"},
    {id: "leather_grain", name: "Leather Grain", desc: "Natural grain leather pebble texture", swatch: "#667788"},
    {id: "quilted", name: "Quilted", desc: "Diamond-stitched quilted padding pattern", swatch: "#667788"},
    {id: "velvet", name: "Velvet", desc: "Soft pile velvet nap direction texture", swatch: "#667788"},
    {id: "burlap", name: "Burlap", desc: "Coarse loose-weave burlap/hessian cloth", swatch: "#cc2222"},
    {id: "lace", name: "Lace", desc: "Delicate ornamental lace lacework pattern", swatch: "#667788"},
    {id: "silk_weave", name: "Silk Weave", desc: "Fine lustrous silk satin weave sheen", swatch: "#667788"},
    {id: "circuit_board", name: "Circuit Board", desc: "PCB trace lines with pads and vias", swatch: "#226633"},
    {id: "hologram", name: "Hologram", desc: "Horizontal scanline projection", swatch: "#667788"},
    {id: "holographic_flake", name: "Holographic Flake", desc: "Rainbow prismatic micro-grid flake", swatch: "#667788"},
    {id: "tron", name: "Tron", desc: "Neon 48px grid with 2px light lines", swatch: "#667788"},
    {id: "static_noise", name: "Static Noise", desc: "TV static blocky pixel noise grain", swatch: "#667788"},
    {id: "binary_code", name: "Binary Code", desc: "Streaming 0s and 1s binary data columns", swatch: "#667788"},
    {id: "matrix_rain", name: "Matrix Rain", desc: "Falling green character rain columns", swatch: "#667788"},
    {id: "qr_code", name: "QR Code", desc: "Dense QR code-style square block grid", swatch: "#667788"},
    {id: "pixel_grid", name: "Pixel Grid", desc: "Retro 8-bit pixel block mosaic pattern", swatch: "#556677"},
    {id: "data_stream", name: "Data Stream", desc: "Flowing horizontal data packet streams", swatch: "#ff3366"},
    {id: "wifi_waves", name: "WiFi Waves", desc: "Concentric signal broadcast wave arcs", swatch: "#4488bb"},
    {id: "glitch_scan", name: "Glitch Scan", desc: "Horizontal glitch scanline displacement bands", swatch: "#ff3366"},
    {id: "lightning", name: "Lightning", desc: "Forked lightning bolt paths", swatch: "#667788"},
    {id: "plasma", name: "Plasma", desc: "Branching electric plasma veins", swatch: "#667788"},
    {id: "wave", name: "Wave", desc: "Smooth flowing sine wave ripples", swatch: "#4488bb"},
    {id: "ripple", name: "Ripple", desc: "Concentric water drop rings", swatch: "#4488aa"},
    {id: "shockwave", name: "Shockwave", desc: "Expanding concentric blast rings", swatch: "#4488bb"},
    {id: "tornado", name: "Tornado", desc: "Spiraling funnel vortex rotation", swatch: "#667788"},
    {id: "sandstorm", name: "Sandstorm", desc: "Dense blowing sand particle streaks", swatch: "#ccaa77"},
    {id: "hailstorm", name: "Hailstorm", desc: "Dense scattered impact crater dimples", swatch: "#667788"},
    {id: "aurora_bands", name: "Aurora Bands", desc: "Northern lights wavy curtain bands", swatch: "#667788"},
    {id: "solar_flare", name: "Solar Flare", desc: "Erupting coronal mass ejection tendrils", swatch: "#667788"},
    {id: "mosaic", name: "Mosaic", desc: "Irregular Voronoi stained glass tiles", swatch: "#aa6688"},
    {id: "damascus", name: "Damascus", desc: "Flowing damascus steel wavy grain", swatch: "#667788"},
    {id: "brick", name: "Brick", desc: "Offset brick blocks with mortar lines", swatch: "#aa5533"},
    {id: "dragon_scale", name: "Dragon Scale", desc: "Overlapping hex reptile scales", swatch: "#44aa66"},
    {id: "fleur_de_lis", name: "Fleur-de-Lis", desc: "New Orleans royal French lily repeating motif", swatch: "#ccaa44"},
    {id: "tribal_flame", name: "Tribal Flame", desc: "Flowing tribal tattoo flame curves", swatch: "#667788"},
    {id: "japanese_wave", name: "Japanese Wave", desc: "Kanagawa-style great wave curling crests", swatch: "#4488bb"},
    {id: "aztec", name: "Aztec", desc: "Angular stepped Aztec/Mayan geometric blocks", swatch: "#667788"},
    {id: "mandala", name: "Mandala", desc: "Radial symmetry mandala flower pattern", swatch: "#667788"},
    {id: "paisley", name: "Paisley", desc: "Teardrop curved paisley ornamental pattern", swatch: "#667788"},
    {id: "steampunk_gears", name: "Steampunk Gears", desc: "Interlocking clockwork gear wheel array", swatch: "#667788"},
    {id: "norse_rune", name: "Norse Rune", desc: "Elder Futhark rune symbol repeating grid", swatch: "#667788"},
    {id: "battle_worn", name: "Battle Worn", desc: "Scratched weathered damage", swatch: "#667788"},
    {id: "acid_wash", name: "Acid Wash", desc: "Corroded acid-etched surface", swatch: "#667788"},
    {id: "cracked_ice", name: "Cracked Ice", desc: "Frozen crack network", swatch: "#667788"},
    {id: "magma_crack", name: "Magma Crack", desc: "Voronoi boundary cracks with orange lava glow", swatch: "#667788"},
    {id: "razor", name: "Razor", desc: "Diagonal aggressive slash marks", swatch: "#889999"},
    {id: "bullet_holes", name: "Bullet Holes", desc: "Scattered impact penetration holes with stress cracks", swatch: "#667788"},
    {id: "shrapnel", name: "Shrapnel", desc: "Irregular shrapnel damage fragment gouges", swatch: "#667788"},
    {id: "road_rash", name: "Road Rash", desc: "Sliding contact abrasion scrape marks", swatch: "#667788"},
    {id: "rust_bloom", name: "Rust Bloom", desc: "Expanding rust spot corrosion blooms", swatch: "#667788"},
    {id: "peeling_paint", name: "Peeling Paint", desc: "Curling paint peel flake patches", swatch: "#667788"},
    {id: "skull", name: "Skull", desc: "Repeating skull mesh array", swatch: "#444444"},
    {id: "spiderweb", name: "Spiderweb", desc: "Radial + concentric web crack lines", swatch: "#667788"},
    {id: "barbed_wire", name: "Barbed Wire", desc: "Twisted wire with barb spikes", swatch: "#777788"},
    {id: "razor_wire", name: "Razor Wire", desc: "Coiled helical wire with barbed loops", swatch: "#777788"},
    {id: "gothic_cross", name: "Gothic Cross", desc: "Ornate gothic cathedral cross repeating grid", swatch: "#886644"},
    {id: "iron_cross", name: "Iron Cross", desc: "Bold Iron Cross/Maltese cross motif array", swatch: "#886644"},
    {id: "skull_wings", name: "Skull Wings", desc: "Affliction-style winged skull ornamental spread", swatch: "#444444"},
    {id: "gothic_scroll", name: "Gothic Scroll", desc: "Flowing dark ornamental scroll filigree", swatch: "#667788"},
    {id: "thorn_vine", name: "Thorn Vine", desc: "Twisted thorny vine dark botanical", swatch: "#667788"},
    {id: "pentagram", name: "Pentagram", desc: "Five-pointed star geometric array", swatch: "#667788"},
    {id: "ekg", name: "EKG", desc: "Heartbeat EKG monitor line pulse (THE SHOKKER SIGNATURE)", swatch: "#667788"},
    {id: "dna_helix", name: "DNA Helix", desc: "Double-helix DNA strand spiral pattern", swatch: "#667788"},
    {id: "molecular", name: "Molecular", desc: "Ball-and-stick molecular bond diagram grid", swatch: "#667788"},
    {id: "atomic_orbital", name: "Atomic Orbital", desc: "Electron cloud probability orbital rings", swatch: "#ff3366"},
    {id: "fingerprint", name: "Fingerprint", desc: "Swirling concentric fingerprint ridge lines", swatch: "#667788"},
    {id: "neuron_network", name: "Neuron Network", desc: "Branching neural dendrite connection web", swatch: "#778899"},
    {id: "pulse_monitor", name: "Pulse Monitor", desc: "Multi-line vital signs monitor waveforms", swatch: "#667788"},
    {id: "biohazard", name: "Biohazard", desc: "Repeating biohazard trefoil warning symbol", swatch: "#44cc22"},
    {id: "camo", name: "Camo", desc: "Digital splinter camouflage blocks", swatch: "#556644"},
    {id: "multicam", name: "Multicam", desc: "5-layer organic Perlin camo pattern", swatch: "#667788"},
    {id: "dazzle", name: "Dazzle", desc: "Bold Voronoi B/W dazzle camo patches", swatch: "#888888"},
    {id: "zebra", name: "Zebra", desc: "Bold black-white zebra stripe pattern", swatch: "#667788"},
    {id: "tiger_stripe", name: "Tiger Stripe", desc: "Organic tiger stripe broken bands", swatch: "#556688"},
    {id: "giraffe", name: "Giraffe", desc: "Irregular polygon giraffe spot patch network", swatch: "#667788"},
    {id: "crocodile", name: "Crocodile", desc: "Deep embossed crocodile hide square scales", swatch: "#667788"},
    {id: "feather", name: "Feather", desc: "Layered overlapping bird feather barb pattern", swatch: "#667788"},
    {id: "ember_mesh", name: "Ember Mesh", desc: "Glowing hot wire grid with ember nodes", swatch: "#888899"},
    {id: "turbine", name: "Turbine", desc: "Radial fan blade spiral from center", swatch: "#667788"},
    {id: "shokk_bolt", name: "SHOKK Bolt", desc: "Jagged lightning bolt Shokker logo strike pattern", swatch: "#ff4400"},
    {id: "shokk_pulse_wave", name: "SHOKK Pulse Wave", desc: "Radiating EKG-style pulse expanding outward", swatch: "#4488bb"},
    {id: "shokk_fracture", name: "SHOKK Fracture", desc: "Impact point with radiating fracture cracks", swatch: "#ff4400"},
    {id: "shokk_hex", name: "SHOKK Hex", desc: "Hexagonal cells with electric edge glow", swatch: "#ff4400"},
    {id: "shokk_scream", name: "SHOKK Scream", desc: "Sound wave distortion from center blast", swatch: "#ff4400"},
    {id: "shokk_grid", name: "SHOKK Grid", desc: "Perspective-warped digital grid tunnel", swatch: "#556677"},
    {id: "stardust", name: "Stardust", desc: "Sparse bright star pinpoints", swatch: "#ccaa44"},
    {id: "interference", name: "Interference", desc: "Flowing rainbow wave bands", swatch: "#ff44ff"},
    {id: "sound_wave", name: "Sound Wave", desc: "Audio waveform amplitude oscillation", swatch: "#4488bb"},
    {id: "morse_code", name: "Morse Code", desc: "Dots and dashes Morse code band lines", swatch: "#667788"},
    {id: "fractal", name: "Fractal", desc: "Self-similar Mandelbrot/Julia fractal branching", swatch: "#667788"},
    {id: "optical_illusion", name: "Optical Illusion", desc: "Moiré interference impossible geometry", swatch: "#667788"},
    {id: "biomechanical", name: "Biomechanical", desc: "H.R. Giger-style organic-mechanical hybrid surface", swatch: "#44cc22"},
    {id: "voronoi_shatter", name: "Voronoi Shatter", desc: "Clean voronoi cell shatter with sharp edges", swatch: "#778866"},
];

const MONOLITHICS = [
    {id: "chameleon_midnight", name: "Chameleon Midnight", desc: "Deep purple → blue → teal midnight shift", swatch: "#6633aa"},
    {id: "chameleon_phoenix", name: "Chameleon Phoenix", desc: "Red → orange → gold fire phoenix shift", swatch: "#6633aa"},
    {id: "chameleon_ocean", name: "Chameleon Ocean", desc: "Teal → blue → purple deep ocean shift", swatch: "#6633aa"},
    {id: "chameleon_venom", name: "Chameleon Venom", desc: "Green → yellow → lime toxic venom shift", swatch: "#6633aa"},
    {id: "chameleon_copper", name: "Chameleon Copper", desc: "Copper → bronze → gold warm metal shift", swatch: "#6633aa"},
    {id: "chameleon_arctic", name: "Chameleon Arctic", desc: "Ice blue → white → silver arctic shift", swatch: "#6633aa"},
    {id: "mystichrome", name: "Mystichrome", desc: "Ford SVT Cobra classic purple-green-gold", swatch: "#886644"},
    {id: "chameleon_amethyst", name: "Chameleon Amethyst", desc: "Purple → pink → magenta amethyst shift", swatch: "#6633aa"},
    {id: "chameleon_emerald", name: "Chameleon Emerald", desc: "Emerald → teal → cyan jewel shift", swatch: "#6633aa"},
    {id: "chameleon_obsidian", name: "Chameleon Obsidian", desc: "Black → deep purple → dark blue stealth shift", swatch: "#6633aa"},
    {id: "cs_warm", name: "CS Warm", desc: "Warm analog shift (reads paint → shifts warm)", swatch: "#4488cc"},
    {id: "cs_cool", name: "CS Cool", desc: "Cool analog shift (reads paint → shifts cool)", swatch: "#4488cc"},
    {id: "cs_rainbow", name: "CS Rainbow", desc: "Full rainbow spread from paint base", swatch: "#4488cc"},
    {id: "cs_subtle", name: "CS Subtle", desc: "Gentle ±15° hue nudge from base", swatch: "#4488cc"},
    {id: "cs_extreme", name: "CS Extreme", desc: "Aggressive ±90° wild color push", swatch: "#4488cc"},
    {id: "cs_complementary", name: "CS Complementary", desc: "Shifts toward complementary color", swatch: "#4488cc"},
    {id: "cs_triadic", name: "CS Triadic", desc: "Three-way color triangle shift from base", swatch: "#4488cc"},
    {id: "cs_split", name: "CS Split Complement", desc: "Split complementary dual shift", swatch: "#4488cc"},
    {id: "cs_emerald", name: "CS Emerald", desc: "Forest → emerald → lime ramp", swatch: "#4488cc"},
    {id: "cs_inferno", name: "CS Inferno", desc: "Black → red → orange → yellow fire ramp", swatch: "#4488cc"},
    {id: "cs_nebula", name: "CS Nebula", desc: "Deep purple → magenta → pink space ramp", swatch: "#4488cc"},
    {id: "cs_deepocean", name: "CS Deep Ocean", desc: "Navy → cerulean → teal ocean ramp", swatch: "#4488cc"},
    {id: "cs_supernova", name: "CS Supernova", desc: "White → gold → orange → red explosion ramp", swatch: "#4488cc"},
    {id: "cs_solarflare", name: "CS Solar Flare", desc: "Yellow → orange → red → black solar eruption", swatch: "#4488cc"},
    {id: "cs_mystichrome", name: "CS Mystichrome", desc: "Purple → green → gold Mystichrome ramp", swatch: "#4488cc"},
    {id: "cs_neon_dreams", name: "CS Neon Dreams", desc: "Hot pink → electric blue → neon green neon ramp", swatch: "#4488cc"},
    {id: "cs_twilight", name: "CS Twilight", desc: "Orange → purple → navy sunset twilight ramp", swatch: "#4488cc"},
    {id: "cs_toxic", name: "CS Toxic", desc: "Black → acid green → yellow toxic waste ramp", swatch: "#4488cc"},
    {id: "prizm_holographic", name: "Prizm Holographic", desc: "Full spectrum rainbow holographic panel shift", swatch: "#ff66aa"},
    {id: "prizm_midnight", name: "Prizm Midnight", desc: "Deep purple → blue → teal panel mapping", swatch: "#ff66aa"},
    {id: "prizm_phoenix", name: "Prizm Phoenix", desc: "Red → orange → gold fire panel mapping", swatch: "#ff66aa"},
    {id: "prizm_oceanic", name: "Prizm Oceanic", desc: "Teal → blue → navy ocean panel mapping", swatch: "#ff66aa"},
    {id: "prizm_ember", name: "Prizm Ember", desc: "Dark red → orange → amber ember panel mapping", swatch: "#ff66aa"},
    {id: "prizm_arctic", name: "Prizm Arctic", desc: "Ice blue → white → silver arctic panel mapping", swatch: "#ff66aa"},
    {id: "prizm_solar", name: "Prizm Solar", desc: "Gold → white → platinum solar panel mapping", swatch: "#ff66aa"},
    {id: "prizm_venom", name: "Prizm Venom", desc: "Green → lime → yellow venom panel mapping", swatch: "#ff66aa"},
    {id: "prizm_mystichrome", name: "Prizm Mystichrome", desc: "Purple → green → gold panel Mystichrome", swatch: "#ff66aa"},
    {id: "prizm_black_rainbow", name: "Prizm Black Rainbow", desc: "Near-black with hidden rainbow angle reveal", swatch: "#ff66aa"},
    {id: "prizm_duochrome", name: "Prizm Duochrome", desc: "Two-color flip panel shift", swatch: "#ff66aa"},
    {id: "prizm_iridescent", name: "Prizm Iridescent", desc: "Full iridescent oil-slick panel mapping", swatch: "#ff66aa"},
    {id: "prizm_adaptive", name: "Prizm Adaptive", desc: "Paint-reading adaptive panel color shift", swatch: "#ff66aa"},
    {id: "prizm_neon", name: "Prizm Neon", desc: "Electric neon color panel mapping", swatch: "#ff66aa"},
    {id: "prizm_blood_moon", name: "Prizm Blood Moon", desc: "Dark red → black → crimson blood moon panels", swatch: "#ff66aa"},
    {id: "phantom", name: "Phantom", desc: "Semi-transparent ghostly fade with depth", swatch: "#334455"},
    {id: "glitch", name: "Glitch", desc: "Digital glitch RGB channel displacement", swatch: "#ff3366"},
    {id: "cel_shade", name: "Cel Shade", desc: "Cartoon cel-shading hard shadow bands", swatch: "#886644"},
    {id: "holographic_wrap", name: "Holographic Wrap", desc: "Full holographic rainbow surface wrap", swatch: "#ff88cc"},
    {id: "aurora", name: "Aurora", desc: "Northern lights flowing color curtains", swatch: "#886644"},
    {id: "thermochromic", name: "Thermochromic", desc: "Heat-sensitive color-change zones", swatch: "#44ccff"},
    {id: "x_ray", name: "X-Ray", desc: "Ghostly translucent X-ray negative effect", swatch: "#886644"},
    {id: "infrared", name: "Infrared", desc: "Thermal camera heat-map color zones", swatch: "#886644"},
    {id: "uv_blacklight", name: "UV Blacklight", desc: "Blacklight reactive neon glow reveal", swatch: "#8844ff"},
    {id: "double_exposure", name: "Double Exposure", desc: "Photography double-exposure overlay ghost", swatch: "#886644"},
    {id: "depth_map", name: "Depth Map", desc: "3D depth perception grayscale mapping", swatch: "#886644"},
    {id: "polarized", name: "Polarized", desc: "Polarized lens rainbow stress pattern bands", swatch: "#886644"},
    {id: "victory_burnout", name: "Victory Burnout", desc: "Tire smoke + confetti + champagne splash celebration", swatch: "#886644"},
    {id: "photo_finish", name: "Photo Finish", desc: "Motion-blur speed streaks from finish line camera", swatch: "#886644"},
    {id: "heat_haze", name: "Heat Haze", desc: "Radiating heat distortion from hot engine/exhaust", swatch: "#886644"},
    {id: "race_worn", name: "Race Worn", desc: "500-mile race wear — rubber marks, stone chips, brake dust", swatch: "#886644"},
    {id: "pace_lap", name: "Pace Lap", desc: "Yellow caution flag color-bleed warm glow", swatch: "#886644"},
    {id: "green_flag", name: "Green Flag", desc: "Electric green start energy radiating outward", swatch: "#886644"},
    {id: "black_flag", name: "Black Flag", desc: "Ominous dark penalty shadow creeping inward", swatch: "#886644"},
    {id: "white_flag", name: "White Flag", desc: "Final lap bright white intensity flash", swatch: "#886644"},
    {id: "under_lights", name: "Under Lights", desc: "Night race artificial lighting glow with shadow", swatch: "#886644"},
    {id: "dawn_patrol", name: "Dawn Patrol", desc: "Early morning sunrise golden hour warm gradient", swatch: "#886644"},
    {id: "rain_race", name: "Rain Race", desc: "Wet surface with visible water droplets and splash", swatch: "#886644"},
    {id: "tunnel_run", name: "Tunnel Run", desc: "Le Mans tunnel lighting transition dark → light", swatch: "#886644"},
    {id: "drafting", name: "Drafting", desc: "Aerodynamic draft pressure visualization zones", swatch: "#886644"},
    {id: "pole_position", name: "Pole Position", desc: "#1 qualifier electric confidence metallic", swatch: "#886644"},
    {id: "last_lap", name: "Last Lap", desc: "Desperate intensity — heightened contrast + aggression", swatch: "#cc2222"},
    {id: "frost_bite", name: "Frost Bite", desc: "Icy frozen crystalline surface coating", swatch: "#886644"},
    {id: "ember_glow", name: "Ember Glow", desc: "Smoldering hot ember with bright crack glow", swatch: "#22ff88"},
    {id: "liquid_metal", name: "Liquid Metal", desc: "T-1000 mercury pooling liquid metal flow", swatch: "#886644"},
    {id: "oil_slick", name: "Oil Slick", desc: "Rainbow oil-on-water iridescent surface", swatch: "#886644"},
    {id: "tornado_alley", name: "Tornado Alley", desc: "Rotating debris-filled violent storm finish", swatch: "#889999"},
    {id: "volcanic_glass", name: "Volcanic Glass", desc: "Obsidian volcanic glass with magma veins", swatch: "#553322"},
    {id: "frozen_lake", name: "Frozen Lake", desc: "Thick ice layer with trapped bubbles and cracks", swatch: "#aaddee"},
    {id: "desert_mirage", name: "Desert Mirage", desc: "Heat shimmer wavering distortion over sand", swatch: "#ccaa77"},
    {id: "ocean_floor", name: "Ocean Floor", desc: "Deep sea bioluminescent dark with scattered glow", swatch: "#224488"},
    {id: "meteor_shower", name: "Meteor Shower", desc: "Streaking bright meteor trails across dark surface", swatch: "#ff8844"},
    {id: "worn_chrome", name: "Worn Chrome", desc: "Aged pitted chrome with rust spots", swatch: "#886644"},
    {id: "rust", name: "Rust", desc: "Heavy orange-brown oxidation corrosion", swatch: "#886644"},
    {id: "weathered_paint", name: "Weathered Paint", desc: "Peeling cracking sun-damaged old paint", swatch: "#886644"},
    {id: "voodoo", name: "Voodoo", desc: "Dark mystical New Orleans voodoo sigil glow", swatch: "#442244"},
    {id: "reaper", name: "Reaper", desc: "Death shadow gradient with scythe edge gleam", swatch: "#222222"},
    {id: "possessed", name: "Possessed", desc: "Demonic red-black pulsing inner glow", swatch: "#cc2222"},
    {id: "wraith", name: "Wraith", desc: "Ghostly transparent dark smoke wisp", swatch: "#334455"},
    {id: "cursed", name: "Cursed", desc: "Cracked ancient dark surface with green poison seep", swatch: "#332244"},
    {id: "eclipse", name: "Eclipse", desc: "Solar eclipse corona glow ring around black void", swatch: "#111122"},
    {id: "nightmare", name: "Nightmare", desc: "Distorted dark reality — shifted hues + hard shadows", swatch: "#220022"},
    {id: "galaxy", name: "Galaxy", desc: "Deep space nebula with star field", swatch: "#886644"},
    {id: "black_diamond", name: "Black Diamond", desc: "Deep black with scattered diamond sparkle points", swatch: "#111122"},
    {id: "liquid_gold", name: "Liquid Gold", desc: "Flowing molten gold pooling metallic", swatch: "#ccaa44"},
    {id: "silk_road", name: "Silk Road", desc: "Flowing silk fabric drape with metallic thread", swatch: "#886644"},
    {id: "venetian_glass", name: "Venetian Glass", desc: "Murano glass multi-color translucent layers", swatch: "#44aaaa"},
    {id: "mother_of_pearl", name: "Mother of Pearl", desc: "Nacre shell iridescent layered shimmer", swatch: "#ddeeff"},
    {id: "sapphire", name: "Sapphire", desc: "Deep blue gemstone with internal fire sparkle", swatch: "#2244aa"},
    {id: "ruby", name: "Ruby", desc: "Blood red gemstone with pigeon blood depth", swatch: "#cc1122"},
    {id: "alexandrite", name: "Alexandrite", desc: "Color-change gemstone green-in-day red-in-night", swatch: "#448844"},
    {id: "stained_glass", name: "Stained Glass", desc: "Cathedral window colored light panel zones", swatch: "#aa4466"},
    {id: "champagne_toast", name: "Champagne Toast", desc: "Golden effervescent rising bubble sparkle", swatch: "#ccaa77"},
    {id: "velvet_crush", name: "Velvet Crush", desc: "Deep crushed velvet texture with pile direction shift", swatch: "#662244"},
    {id: "neon_glow", name: "Neon Glow", desc: "Bright neon tube edge-glow effect", swatch: "#22ff88"},
    {id: "radioactive", name: "Radioactive", desc: "Toxic green nuclear glow radiation", swatch: "#886644"},
    {id: "static", name: "Static", desc: "Electric static discharge sparking surface", swatch: "#886644"},
    {id: "scorched", name: "Scorched", desc: "Charred burnt surface with hot spots", swatch: "#886644"},
    {id: "neon_vegas", name: "Neon Vegas", desc: "Las Vegas strip multi-color neon sign glow", swatch: "#22ff88"},
    {id: "laser_grid", name: "Laser Grid", desc: "Bright laser beam grid projection on surface", swatch: "#ff2222"},
    {id: "plasma_globe", name: "Plasma Globe", desc: "Plasma ball tendrils reaching from center points", swatch: "#8844ff"},
    {id: "firefly", name: "Firefly", desc: "Scattered bioluminescent moving glow points", swatch: "#ccaa44"},
    {id: "led_matrix", name: "LED Matrix", desc: "Dense RGB LED dot grid display surface", swatch: "#44ddff"},
    {id: "cyber_punk", name: "Cyberpunk", desc: "Neon pink-blue on dark with rain-wet reflection", swatch: "#ff44ff"},
    {id: "crocodile_leather", name: "Croc Leather", desc: "Full crocodile hide emboss with glossy lacquer", swatch: "#556644"},
    {id: "hammered_copper", name: "Hammered Copper", desc: "Hand-hammered warm copper bowl dimple surface", swatch: "#cc7744"},
    {id: "brushed_steel_dark", name: "Dark Brushed Steel", desc: "Heavy directional dark steel grain", swatch: "#888899"},
    {id: "etched_metal", name: "Etched Metal", desc: "Chemical-etched artistic metal surface relief", swatch: "#aabbcc"},
    {id: "sandstone", name: "Sandstone", desc: "Natural sandstone rough mineral grain", swatch: "#ccaa77"},
    {id: "petrified_wood", name: "Petrified Wood", desc: "Fossilized wood-to-stone grain preservation", swatch: "#887744"},
    {id: "forged_iron", name: "Forged Iron", desc: "Blacksmith hammer-forged hot iron texture", swatch: "#555555"},
    {id: "acid_etched_glass", name: "Acid Etched Glass", desc: "Frosted acid-etched decorative glass surface", swatch: "#aabbcc"},
    {id: "concrete", name: "Concrete", desc: "Raw poured concrete industrial surface", swatch: "#999999"},
    {id: "cast_iron", name: "Cast Iron", desc: "Heavy cast iron rough pour with scale marks", swatch: "#555555"},
    {id: "barn_find", name: "Barn Find", desc: "Complete barn find — dust, cobwebs, mouse-chewed, faded", swatch: "#887766"},
    {id: "patina_truck", name: "Patina Truck", desc: "Classic pickup patina — sun fade + surface rust + character", swatch: "#668855"},
    {id: "hot_rod_flames", name: "Hot Rod Flames", desc: "Traditional hot rod flowing flame paint job effect", swatch: "#ff4400"},
    {id: "woodie_wagon", name: "Woodie Wagon", desc: "1940s wood-panel station wagon sides", swatch: "#8a6633"},
    {id: "drive_in", name: "Drive-In", desc: "1950s neon drive-in diner glow + chrome reflection", swatch: "#ff6688"},
    {id: "muscle_car_stripe", name: "Muscle Car Stripe", desc: "Classic 1970 GTO/Chevelle bold hood stripe effect", swatch: "#2255cc"},
    {id: "pin_up", name: "Pin-Up Nose Art", desc: "WWII bomber nose art painted-over-primer look", swatch: "#ff6688"},
    {id: "vinyl_record", name: "Vinyl Record", desc: "Concentric groove record spiral with label zone", swatch: "#222222"},
    {id: "portal", name: "Portal", desc: "Swirling dimensional portal vortex energy", swatch: "#8844ff"},
    {id: "time_warp", name: "Time Warp", desc: "Temporal distortion — clock-melt + spiral warp", swatch: "#44ddff"},
    {id: "antimatter", name: "Antimatter", desc: "Inverted reality — negative image color flip", swatch: "#111122"},
    {id: "singularity", name: "Singularity", desc: "Black hole gravity well — light bending inward", swatch: "#050505"},
    {id: "dreamscape", name: "Dreamscape", desc: "Surreal soft-focus floating color cloud landscape", swatch: "#8866cc"},
    {id: "acid_trip", name: "Acid Trip", desc: "Psychedelic flowing morphing rainbow fractal", swatch: "#ff44ff"},
    {id: "mirage", name: "Mirage", desc: "Desert heat shimmer — surface appears to waver", swatch: "#ccaa77"},
    {id: "fourth_dimension", name: "4th Dimension", desc: "Tesseract/hypercube geometric impossibility", swatch: "#4444ff"},
    {id: "glitch_reality", name: "Glitch Reality", desc: "Reality-breaking pixel scatter + noise displacement", swatch: "#ff3366"},
    {id: "phantom_zone", name: "Phantom Zone", desc: "Superman Phantom Zone crystalline prison dimension", swatch: "#334455"},
    {id: "shokk_ekg", name: "SHOKK EKG", desc: "Full EKG flatline-to-pulse dramatic spec + paint effect", swatch: "#ff4400"},
    {id: "shokk_defib", name: "SHOKK Defib", desc: "Electric defibrillator shock burst radiating from impact point", swatch: "#ff4400"},
    {id: "shokk_overload", name: "SHOKK Overload", desc: "System overload — sparking circuits + warning red zones", swatch: "#ff4400"},
    {id: "shokk_blackout", name: "SHOKK Blackout", desc: "Complete power failure — dark void with flickering remnants", swatch: "#ff4400"},
    {id: "shokk_resurrection", name: "SHOKK Resurrection", desc: "Rising from darkness — light breaking through black cracks", swatch: "#ff4400"},
    {id: "shokk_voltage", name: "SHOKK Voltage", desc: "High-voltage warning — electric arc between contact points", swatch: "#ff4400"},
    {id: "shokk_flatline", name: "SHOKK Flatline", desc: "Flatline EKG — matte dead zone with one bright pulse", swatch: "#ff4400"},
    {id: "shokk_adrenaline", name: "SHOKK Adrenaline", desc: "Heart-racing red surge — veins of energy through metal", swatch: "#ff4400"},
    {id: "shokk_aftermath", name: "SHOKK Aftermath", desc: "Post-impact aftermath — cracked + smoldering + surviving", swatch: "#ff4400"},
    {id: "shokk_unleashed", name: "SHOKK Unleashed", desc: "Maximum everything — the ultimate chaotic energy explosion", swatch: "#ff4400"},
    {id: "lafleur", name: "Lafleur", desc: "New Orleans Fleur-de-lis + Mardi Gras gold-purple-green regal finish", swatch: "#ccaa44"},
    {id: "affliction", name: "Affliction", desc: "Full Affliction-style ornamental cross + wings + scroll dark luxury", swatch: "#cc2222"},
    {id: "samurai", name: "Samurai", desc: "Japanese lacquerware urushi — deep black-red with gold kintsugi cracks", swatch: "#cc2222"},
    {id: "dia_de_muertos", name: "Día de Muertos", desc: "Mexican Day of Dead — marigold + sugar skull + deep purple celebration", swatch: "#ff8844"},
    {id: "northern_soul", name: "Northern Soul", desc: "Keep-the-faith fist + soul music energy — warm gold on midnight vinyl", swatch: "#ccaa44"},
];

// ===== GROUP MAPS for sub-tab navigation =====
const BASE_GROUPS = {
    "Foundation": ["gloss", "matte", "satin", "flat_black", "primer", "clear_matte", "wet_look", "silk", "eggshell", "semi_gloss"],
    "Metallic Standard": ["metallic", "pearl", "candy", "satin_metal", "gunmetal", "copper", "pearlescent_white", "metal_flake_base", "candy_apple", "midnight_pearl", "champagne", "pewter"],
    "Chrome & Mirror": ["chrome", "satin_chrome", "dark_chrome", "surgical_steel", "mirror_gold", "candy_chrome", "black_chrome", "blue_chrome", "red_chrome", "antique_chrome"],
    "Candy & Pearl": ["spectraflame", "chameleon", "iridescent", "tinted_clear", "candy_burgundy", "candy_emerald", "candy_cobalt", "tri_coat_pearl", "moonstone", "opal"],
    "Satin & Wrap": ["satin_wrap", "liquid_wrap", "frozen_matte", "matte_wrap", "color_flip_wrap", "chrome_wrap", "gloss_wrap", "textured_wrap", "brushed_wrap", "stealth_wrap"],
    "Industrial & Tactical": ["cerakote", "duracoat", "powder_coat", "blackout", "sandblasted", "vantablack", "mil_spec_od", "mil_spec_tan", "armor_plate", "submarine_black", "gunship_gray", "battleship_gray"],
    "Ceramic & Glass": ["ceramic", "piano_black", "porcelain", "obsidian", "crystal_clear", "tempered_glass", "ceramic_matte", "enamel"],
    "Racing Heritage": ["race_day_gloss", "stock_car_enamel", "sprint_car_chrome", "dirt_track_satin", "endurance_ceramic", "rally_mud", "drag_strip_gloss", "victory_lane", "barn_find", "rat_rod_primer", "pace_car_pearl", "heat_shield", "pit_lane_matte", "asphalt_grind", "checkered_chrome"],
    "Exotic Metal": ["brushed_titanium", "anodized", "frozen", "rose_gold", "diamond_coat", "raw_aluminum", "titanium_raw", "brushed_aluminum", "liquid_titanium", "tungsten", "platinum", "cobalt_metal"],
    "Weathered & Aged": ["patina_bronze", "rugged", "galvanized", "heat_treated", "sun_baked", "salt_corroded", "desert_worn", "acid_rain", "oxidized_copper", "vintage_chrome"],
    "Oem Automotive": ["smoked", "factory_basecoat", "showroom_clear", "fleet_white", "taxi_yellow", "school_bus", "fire_engine", "ambulance_white", "police_black", "dealer_pearl"],
    "Carbon & Composite": ["carbon_base", "kevlar_base", "fiberglass", "carbon_ceramic", "aramid", "graphene", "forged_composite", "hybrid_weave"],
    "Premium Luxury": ["satin_gold", "bentley_silver", "ferrari_rosso", "lamborghini_verde", "porsche_pts", "mclaren_orange", "bugatti_blue", "koenigsegg_clear", "pagani_tricolore", "maybach_two_tone"],
    "Shokk Series": ["plasma_metal", "burnt_headers", "mercury", "electric_ice", "volcanic", "shokk_pulse", "shokk_venom", "shokk_blood", "shokk_void", "shokk_static"],
    "Extreme & Experimental": ["quantum_black", "neutron_star", "plasma_core", "dark_matter", "superconductor", "bioluminescent", "solar_panel", "holographic_base"],
};

const PATTERN_GROUPS = {
    "Carbon & Weave": ["carbon_fiber", "forged_carbon", "carbon_4x4", "carbon_spread_tow", "carbon_uni", "tweed_weave", "basket_weave", "chainlink", "kevlar_weave", "nanoweave"],
    "Metal & Industrial": ["diamond_plate", "hex_mesh", "hammered", "chainmail", "metal_flake", "mega_flake", "rivet_grid", "corrugated", "perforated", "expanded_metal", "grating", "knurled"],
    "Nature & Organic": ["wood_grain", "marble", "lava_flow", "rain_drop", "frost_crystal", "topographic", "tree_bark", "coral_reef", "river_stone", "glacier_crack"],
    "Geometric": ["chevron", "houndstooth", "plaid", "crosshatch", "celtic_knot", "pinstripe", "herringbone", "argyle", "greek_key", "art_deco", "tessellation", "yin_yang"],
    "Racing & Motorsport": ["tire_tread", "checkered_flag", "racing_stripe", "starting_grid", "tire_smoke", "skid_marks", "asphalt_texture", "pit_lane_marks", "lap_counter", "sponsor_fade", "rooster_tail", "victory_confetti", "trophy_laurel", "rpm_gauge", "finish_line"],
    "Textile & Fabric": ["snake_skin", "leopard", "fishnet", "denim", "leather_grain", "quilted", "velvet", "burlap", "lace", "silk_weave"],
    "Tech & Digital": ["circuit_board", "hologram", "holographic_flake", "tron", "static_noise", "binary_code", "matrix_rain", "qr_code", "pixel_grid", "data_stream", "wifi_waves", "glitch_scan"],
    "Weather & Elements": ["lightning", "plasma", "wave", "ripple", "shockwave", "tornado", "sandstorm", "hailstorm", "aurora_bands", "solar_flare"],
    "Artistic & Cultural": ["mosaic", "damascus", "brick", "dragon_scale", "fleur_de_lis", "tribal_flame", "japanese_wave", "aztec", "mandala", "paisley", "steampunk_gears", "norse_rune"],
    "Damage & Wear": ["battle_worn", "acid_wash", "cracked_ice", "magma_crack", "razor", "bullet_holes", "shrapnel", "road_rash", "rust_bloom", "peeling_paint"],
    "Gothic & Dark": ["skull", "spiderweb", "barbed_wire", "razor_wire", "gothic_cross", "iron_cross", "skull_wings", "gothic_scroll", "thorn_vine", "pentagram"],
    "Medical & Science": ["ekg", "dna_helix", "molecular", "atomic_orbital", "fingerprint", "neuron_network", "pulse_monitor", "biohazard"],
    "Animal & Wildlife": ["camo", "multicam", "dazzle", "zebra", "tiger_stripe", "giraffe", "crocodile", "feather"],
    "Shokk Series": ["ember_mesh", "turbine", "shokk_bolt", "shokk_pulse_wave", "shokk_fracture", "shokk_hex", "shokk_scream", "shokk_grid"],
    "Abstract & Experimental": ["stardust", "interference", "sound_wave", "morse_code", "fractal", "optical_illusion", "biomechanical", "voronoi_shatter"],
};

const SPECIAL_GROUPS = {
    "Chameleon Classic": ["chameleon_midnight", "chameleon_phoenix", "chameleon_ocean", "chameleon_venom", "chameleon_copper", "chameleon_arctic", "mystichrome", "chameleon_amethyst", "chameleon_emerald", "chameleon_obsidian"],
    "Color Shift Adaptive": ["cs_warm", "cs_cool", "cs_rainbow", "cs_subtle", "cs_extreme", "cs_complementary", "cs_triadic", "cs_split"],
    "Color Shift Preset": ["cs_emerald", "cs_inferno", "cs_nebula", "cs_deepocean", "cs_supernova", "cs_solarflare", "cs_mystichrome", "cs_neon_dreams", "cs_twilight", "cs_toxic"],
    "Prizm Series": ["prizm_holographic", "prizm_midnight", "prizm_phoenix", "prizm_oceanic", "prizm_ember", "prizm_arctic", "prizm_solar", "prizm_venom", "prizm_mystichrome", "prizm_black_rainbow", "prizm_duochrome", "prizm_iridescent", "prizm_adaptive", "prizm_neon", "prizm_blood_moon"],
    "Effect & Visual": ["phantom", "glitch", "cel_shade", "holographic_wrap", "aurora", "thermochromic", "x_ray", "infrared", "uv_blacklight", "double_exposure", "depth_map", "polarized"],
    "Racing Legend": ["victory_burnout", "photo_finish", "heat_haze", "race_worn", "pace_lap", "green_flag", "black_flag", "white_flag", "under_lights", "dawn_patrol", "rain_race", "tunnel_run", "drafting", "pole_position", "last_lap"],
    "Weather & Element": ["frost_bite", "ember_glow", "liquid_metal", "oil_slick", "tornado_alley", "volcanic_glass", "frozen_lake", "desert_mirage", "ocean_floor", "meteor_shower"],
    "Dark & Gothic": ["worn_chrome", "rust", "weathered_paint", "voodoo", "reaper", "possessed", "wraith", "cursed", "eclipse", "nightmare"],
    "Luxury & Exotic": ["galaxy", "black_diamond", "liquid_gold", "silk_road", "venetian_glass", "mother_of_pearl", "sapphire", "ruby", "alexandrite", "stained_glass", "champagne_toast", "velvet_crush"],
    "Neon & Glow": ["neon_glow", "radioactive", "static", "scorched", "neon_vegas", "laser_grid", "plasma_globe", "firefly", "led_matrix", "cyber_punk"],
    "Texture & Surface": ["crocodile_leather", "hammered_copper", "brushed_steel_dark", "etched_metal", "sandstone", "petrified_wood", "forged_iron", "acid_etched_glass", "concrete", "cast_iron"],
    "Vintage & Retro": ["barn_find", "patina_truck", "hot_rod_flames", "woodie_wagon", "drive_in", "muscle_car_stripe", "pin_up", "vinyl_record"],
    "Surreal & Fantasy": ["portal", "time_warp", "antimatter", "singularity", "dreamscape", "acid_trip", "mirage", "fourth_dimension", "glitch_reality", "phantom_zone"],
    "Shokk Series": ["shokk_ekg", "shokk_defib", "shokk_overload", "shokk_blackout", "shokk_resurrection", "shokk_voltage", "shokk_flatline", "shokk_adrenaline", "shokk_aftermath", "shokk_unleashed"],
    "One-Of-A-Kind": ["lafleur", "affliction", "samurai", "dia_de_muertos", "northern_soul"],
};
