"""finish_colors_lookup.py - Resolve finish colors for swatch/thumbnail rendering.

Looks up finish colors (``c1``, ``c2``, ``c3``, ``ghost``) for gradient / mirror /
3c / ghost / MC finishes. Used by the server swatch endpoint and by
``rebuild_thumbnails`` so the generated thumbnails show accurate colors.

Data source
-----------
``finish_colors.json`` is generated by ``scripts/extract_finish_colors.py`` from
``paint-booth-1-data.js``. It maps finish IDs to colour-name references that are
then resolved against ``shokker_color_monolithics.COLOR_PALETTE``.

Color-space notes
-----------------
* ``COLOR_PALETTE`` entries are stored as 0..1 float RGB triples (linear-ish
  sRGB as authored in the JS bible).
* :func:`_rgb_to_hex` quantises to the standard 8-bit hex form ``#RRGGBB``
  expected by the UI.
* The palette itself is authoritative -- callers must never pass float RGB
  through another colour-space transform before hex conversion.

Thread safety
-------------
The lazy-loaded JSON and hex caches are guarded by a module-level lock so this
is safe to call from Flask's threaded handlers.

Public API
----------
* :func:`get_finish_colors` -- primary lookup.
* :func:`clear_cache`       -- invalidate caches (e.g. after a data rebuild).
* :func:`preload`           -- eager load from disk (optional perf warm-up).
"""

from __future__ import annotations

import json
import logging
import math
import os
import threading
from typing import Any, Dict, Optional, Tuple

__all__ = [
    "get_finish_colors",
    "clear_cache",
    "preload",
    "FINISH_COLORS_VERSION",
]

#: Module version for diagnostics.
FINISH_COLORS_VERSION: str = "1.1.0"

#: Name of the JSON data file colocated with this module.
_DATA_FILENAME: str = "finish_colors.json"

#: Keys that map to palette color names.
_COLOR_KEYS: Tuple[str, ...] = ("c1", "c2", "c3")

#: Minimum set of keys a valid result must contain.
_REQUIRED_OUT_KEYS: Tuple[str, ...] = ("c1", "c2")

#: 8-bit channel ceiling -- used for quantisation.
_RGB_MAX: int = 255

logger = logging.getLogger("shokker.finish_colors")

# Lazy-loaded state -- guarded by ``_lock``.
_LOOKUP: Optional[Dict[str, Any]] = None
_HEX_CACHE: Dict[str, Optional[str]] = {}
_FINISH_CACHE: Dict[str, Optional[Dict[str, str]]] = {}
_lock = threading.RLock()


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _clamp_channel(value: float) -> int:
    """Quantise a 0..1 float channel to 0..255 int, clamping and handling NaN.

    Args:
        value: A floating-point channel value (expected 0..1).

    Returns:
        An int in ``[0, 255]``. NaN/Inf values collapse to 0.
    """
    if value is None or not isinstance(value, (int, float)):
        return 0
    if isinstance(value, float) and (math.isnan(value) or math.isinf(value)):
        return 0
    return max(0, min(_RGB_MAX, int(round(value * _RGB_MAX))))


def _rgb_to_hex(r: float, g: float, b: float) -> str:
    """Convert a 0..1 float RGB triple to a ``#RRGGBB`` hex string.

    Args:
        r: Red channel (0..1).
        g: Green channel (0..1).
        b: Blue channel (0..1).

    Returns:
        A lowercase ``#RRGGBB`` hex string. Channels outside 0..1 are clamped;
        NaN/Inf become 0.
    """
    return "#" + "".join(format(_clamp_channel(x), "02x") for x in (r, g, b))


def _get_palette() -> Dict[str, Tuple[float, float, float]]:
    """Return ``COLOR_PALETTE`` from the monolithics module, lazily.

    The import is deferred to avoid a circular import at module load -- the
    monolithics module itself imports tools that may touch this file.

    Returns:
        The palette dict (possibly empty if the monolithics module is absent).
    """
    try:
        from shokker_color_monolithics import COLOR_PALETTE  # type: ignore
        return COLOR_PALETTE  # type: ignore[return-value]
    except ImportError as e:
        # Log once per session is acceptable at DEBUG.
        logger.debug("[finish_colors] COLOR_PALETTE unavailable: %s", e)
        return {}


def _name_to_hex(name: str) -> Optional[str]:
    """Resolve a palette color name to ``#RRGGBB``.

    Args:
        name: The palette key (e.g. ``"electric_blue"``).

    Returns:
        The hex string, or ``None`` if the name isn't in the palette or is
        malformed.
    """
    if not isinstance(name, str) or not name:
        return None
    # Fast path -- cache hit.
    with _lock:
        if name in _HEX_CACHE:
            return _HEX_CACHE[name]
    pal = _get_palette()
    value = pal.get(name)
    if value is None:
        with _lock:
            _HEX_CACHE[name] = None
        return None
    try:
        r, g, b = value
    except (TypeError, ValueError):
        logger.warning(
            "[finish_colors] palette entry %r has bad shape %r", name, value
        )
        with _lock:
            _HEX_CACHE[name] = None
        return None
    hex_val = _rgb_to_hex(r, g, b)
    with _lock:
        _HEX_CACHE[name] = hex_val
    return hex_val


def _data_path() -> str:
    """Return the absolute path to the bundled ``finish_colors.json``."""
    return os.path.join(
        os.path.dirname(os.path.abspath(__file__)), _DATA_FILENAME
    )


def _load_lookup() -> Dict[str, Any]:
    """Load and memoise ``finish_colors.json``.

    Returns:
        The parsed JSON dict, or an empty dict if the file is missing or
        unreadable. Subsequent calls return the cached instance.
    """
    global _LOOKUP
    with _lock:
        if _LOOKUP is not None:
            return _LOOKUP
        path = _data_path()
        if not os.path.isfile(path):
            logger.info(
                "[finish_colors] %s not present -- finish lookups will all miss",
                _DATA_FILENAME,
            )
            _LOOKUP = {}
            return _LOOKUP
        try:
            with open(path, "r", encoding="utf-8") as fh:
                data = json.load(fh)
        except (OSError, json.JSONDecodeError) as e:
            logger.error(
                "[finish_colors] Failed to load %s (%s); using empty lookup",
                path, e,
            )
            _LOOKUP = {}
            return _LOOKUP
        if not isinstance(data, dict):
            logger.error(
                "[finish_colors] %s root must be an object, got %s",
                _DATA_FILENAME, type(data).__name__,
            )
            _LOOKUP = {}
            return _LOOKUP
        _LOOKUP = data
        return _LOOKUP


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def get_finish_colors(finish_id: str) -> Optional[Dict[str, str]]:
    """Return a dict of hex colors for the requested finish.

    Args:
        finish_id: The canonical finish ID as used throughout the UI
            (e.g. ``"gradient_violet_rose"``).

    Returns:
        A dict with keys ``c1``, ``c2``, optionally ``c3`` and ``ghost``; or
        ``None`` if the finish is unknown or references a palette entry that
        the monolithics module couldn't supply.

    Notes:
        Results are cached per finish ID (including negative lookups) so
        repeat calls are O(1). Call :func:`clear_cache` after rebuilding
        ``finish_colors.json`` or reloading the palette.
    """
    if not finish_id or not isinstance(finish_id, str):
        return None

    # Fast-path cache.
    with _lock:
        if finish_id in _FINISH_CACHE:
            return _FINISH_CACHE[finish_id]

    data = _load_lookup()
    raw = data.get(finish_id)
    if raw is None or not isinstance(raw, dict):
        with _lock:
            _FINISH_CACHE[finish_id] = None
        return None

    out: Dict[str, str] = {}
    for key in _COLOR_KEYS:
        color_name = raw.get(key)
        if color_name is None:
            continue
        hex_val = _name_to_hex(color_name)
        if hex_val is None:
            # One missing colour invalidates the whole entry -- caller needs all
            # referenced channels to render correctly.
            logger.debug(
                "[finish_colors] finish %r references missing palette colour %r",
                finish_id, color_name,
            )
            with _lock:
                _FINISH_CACHE[finish_id] = None
            return None
        out[key] = hex_val

    if "ghost" in raw and isinstance(raw["ghost"], str):
        out["ghost"] = raw["ghost"]

    if any(k not in out for k in _REQUIRED_OUT_KEYS):
        with _lock:
            _FINISH_CACHE[finish_id] = None
        return None

    with _lock:
        _FINISH_CACHE[finish_id] = out
    return out


def clear_cache() -> None:
    """Invalidate all memoised lookups.

    Call after rebuilding ``finish_colors.json`` or when the monolithics
    palette has been reloaded. Safe to call concurrently with lookups.
    """
    global _LOOKUP
    with _lock:
        _LOOKUP = None
        _HEX_CACHE.clear()
        _FINISH_CACHE.clear()


def preload() -> int:
    """Eagerly load the JSON data and warm the palette.

    Returns:
        The number of finish IDs available after loading. Useful as a startup
        diagnostic (``logger.info`` from caller).
    """
    data = _load_lookup()
    # Touching the palette primes the monolithics import -- surfaces import
    # failures early rather than on the first swatch request.
    _get_palette()
    return len(data)
