/* Generated from the canonical overlay catalog. */
globalThis.SPB_SPEC_OVERLAY_V2 = {
  "schema": "spb-spec-overlay-catalog/2",
  "version": "2026-09-06-v2",
  "families": [
    {
      "id": "machine",
      "name": "Machined & Brushed",
      "desc": "Interrupted tool cuts, engraved grain and compact weld pools. Hard lands, dull recesses and polished edges each receive their own material response."
    },
    {
      "id": "weave",
      "name": "Weave & Composite",
      "desc": "Crossing fibers, braided joints and layered composites. Follow the over-under construction through resin pockets, stitches and fine bundle detail."
    },
    {
      "id": "crystal",
      "name": "Crystal & Mineral",
      "desc": "Crystal growth interpreted as small terraces, twin boundaries and mineral inclusions. Distinct faces carry distinct material states."
    },
    {
      "id": "skin",
      "name": "Skin & Cellular",
      "desc": "Biological surface structures: protective plates, porous shells and cellular membranes. Fine ribs, keels and pores create the material detail."
    },
    {
      "id": "liquid",
      "name": "Liquid & Coating",
      "desc": "Contact lines, beads and coating deposits, captured as static fine surfaces. Wet-looking islands and dried residue respond differently to light."
    },
    {
      "id": "crack",
      "name": "Crack & Weather",
      "desc": "Fine weathered surfaces with protected recesses, broken coats and exposed edges. Damage is assembled from many small features."
    },
    {
      "id": "optical",
      "name": "Optical & Interference",
      "desc": "Fine arrangements of contrasting material facets and interference-inspired geometry. These are static M/R/Cc constructions; response depends on the simulator lighting."
    },
    {
      "id": "engraved",
      "name": "Engraved & Ornamental",
      "desc": "Interlaced engraving, rosettes and ornamental relief interpreted through material channels. Recessed cuts and burnished crests reveal the fine geometry."
    },
    {
      "id": "track",
      "name": "Track & Motorsport",
      "desc": "Motorsport details reduced to fine material patterns: check packets, witness marks and wear. Built to layer into a livery without adding painted artwork."
    },
    {
      "id": "experimental",
      "name": "Experimental Structures",
      "desc": "Unusual mathematical arrangements and invented material structures. Every construction has its own feature layout and material assignment."
    }
  ],
  "items": [
    {
      "id": "spov2_toolpath_reversal",
      "name": "Toolpath Reversal",
      "desc": "Alternating interrupted cuts with entry crescents, exit scallops, protected lands and compact burrs.",
      "category": "Machined & Brushed",
      "family": "machine",
      "tags": [
        "directional",
        "metal contrast"
      ],
      "defaults": {},
      "defaultOpacity": 100,
      "defaultBlendMode": "normal",
      "defaultRange": 40,
      "defaultChannels": "MRC",
      "render_version": 2,
      "seed": 42,
      "intent": "spec_driven",
      "legacy": false
    },
    {
      "id": "spov2_braided_junction",
      "name": "Braided Junction",
      "desc": "Crossing tow bundles, raised overpasses, recessed underpasses, resin pockets and stitch collars.",
      "category": "Weave & Composite",
      "family": "weave",
      "tags": [
        "woven",
        "metal contrast"
      ],
      "defaults": {},
      "defaultOpacity": 100,
      "defaultBlendMode": "normal",
      "defaultRange": 40,
      "defaultChannels": "MRC",
      "render_version": 2,
      "seed": 42,
      "intent": "spec_driven",
      "legacy": false
    },
    {
      "id": "spov2_crystal_front",
      "name": "Crystal Front",
      "desc": "Competing square growth terraces surround nuclei, twin seams, interstitial pockets and chipped tips.",
      "category": "Crystal & Mineral",
      "family": "crystal",
      "tags": [
        "crystal",
        "dense"
      ],
      "defaults": {},
      "defaultOpacity": 100,
      "defaultBlendMode": "normal",
      "defaultRange": 40,
      "defaultChannels": "MRC",
      "render_version": 2,
      "seed": 42,
      "intent": "spec_driven",
      "legacy": false
    },
    {
      "id": "spov2_denticle_armor",
      "name": "Denticle Armor",
      "desc": "Pointed plates carry split keels, root collars, worn patches and separate between-plate pores.",
      "category": "Skin & Cellular",
      "family": "skin",
      "tags": [
        "directional",
        "organic"
      ],
      "defaults": {},
      "defaultOpacity": 100,
      "defaultBlendMode": "normal",
      "defaultRange": 40,
      "defaultChannels": "MRC",
      "render_version": 2,
      "seed": 42,
      "intent": "spec_driven",
      "legacy": false
    },
    {
      "id": "spov2_tidal_meniscus",
      "name": "Tidal Meniscus",
      "desc": "Wet islands recede inside contact arcs, leaving pinning points, beads and residue rings.",
      "category": "Liquid & Coating",
      "family": "liquid",
      "tags": [
        "coat detail",
        "wet"
      ],
      "defaults": {},
      "defaultOpacity": 100,
      "defaultBlendMode": "normal",
      "defaultRange": 40,
      "defaultChannels": "MRC",
      "render_version": 2,
      "seed": 42,
      "intent": "spec_driven",
      "legacy": false
    },
    {
      "id": "spov2_crazed_porcelain",
      "name": "Crazed Porcelain",
      "desc": "A warped quadrilateral glaze fracture network contains secondary arrested checks, glaze lips, tiny pore clusters and exposed corner chips.",
      "category": "Crack & Weather",
      "family": "crack",
      "tags": [
        "fractured",
        "matte/gloss"
      ],
      "defaults": {},
      "defaultOpacity": 100,
      "defaultBlendMode": "normal",
      "defaultRange": 40,
      "defaultChannels": "MRC",
      "render_version": 2,
      "seed": 42,
      "intent": "spec_driven",
      "legacy": false
    },
    {
      "id": "spov2_paired_facet_lattice",
      "name": "Paired Facet Lattice",
      "desc": "Paired platelets alternate material response around bevels, junctions, etched notches and polished tips.",
      "category": "Optical & Interference",
      "family": "optical",
      "tags": [
        "optical",
        "metal contrast"
      ],
      "defaults": {},
      "defaultOpacity": 100,
      "defaultBlendMode": "normal",
      "defaultRange": 40,
      "defaultChannels": "MRC",
      "render_version": 2,
      "seed": 42,
      "intent": "spec_driven",
      "legacy": false
    },
    {
      "id": "spov2_security_guilloche",
      "name": "Security Guilloche",
      "desc": "Two independently placed engraving passes interlace fine figure-eight arclets, partial secondary arcs, recessed knots, beads and burnished crests. No isolated medallion lattice.",
      "category": "Engraved & Ornamental",
      "family": "engraved",
      "tags": [
        "engraved",
        "dense"
      ],
      "defaults": {},
      "defaultOpacity": 100,
      "defaultBlendMode": "normal",
      "defaultRange": 40,
      "defaultChannels": "MRC",
      "render_version": 2,
      "seed": 42,
      "intent": "spec_driven",
      "legacy": false
    },
    {
      "id": "spov2_pit_lane_ghost",
      "name": "Pit Lane Ghost",
      "desc": "Fine pit-stall corners and service-box outlines combine with independently placed lane ticks, corner tabs, worn scuffs and witness dots.",
      "category": "Track & Motorsport",
      "family": "track",
      "tags": [
        "subtle reveal",
        "racing"
      ],
      "defaults": {},
      "defaultOpacity": 100,
      "defaultBlendMode": "normal",
      "defaultRange": 40,
      "defaultChannels": "MRC",
      "render_version": 2,
      "seed": 42,
      "intent": "spec_driven",
      "legacy": false
    },
    {
      "id": "spov2_aperiodic_alloy",
      "name": "Aperiodic Alloy",
      "desc": "Unequal inset tiles meet interrupted bridges, multiway junctions and locally scarred corners.",
      "category": "Experimental Structures",
      "family": "experimental",
      "tags": [
        "aperiodic",
        "experimental"
      ],
      "defaults": {},
      "defaultOpacity": 100,
      "defaultBlendMode": "normal",
      "defaultRange": 40,
      "defaultChannels": "MRC",
      "render_version": 2,
      "seed": 42,
      "intent": "spec_driven",
      "legacy": false
    },
    {
      "id": "spov2_diatom_sieve",
      "name": "Diatom Sieve",
      "desc": "Bilateral pennate frustules contain an axial raphe, repeated pore rows, terminal plugs and separate valve rims.",
      "category": "Skin & Cellular",
      "family": "skin",
      "tags": [
        "cellular",
        "organic"
      ],
      "defaults": {},
      "defaultOpacity": 100,
      "defaultBlendMode": "normal",
      "defaultRange": 40,
      "defaultChannels": "MRC",
      "render_version": 2,
      "seed": 42,
      "intent": "spec_driven",
      "legacy": false
    },
    {
      "id": "spov2_weld_pool_archive",
      "name": "Weld-Pool Archive",
      "desc": "Three-sided corner seams contain overlapping scalloped weld beads, heat-affected toes, spatter and interrupted polished breaks.",
      "category": "Machined & Brushed",
      "family": "machine",
      "tags": [
        "metal contrast",
        "directional"
      ],
      "defaults": {},
      "defaultOpacity": 100,
      "defaultBlendMode": "normal",
      "defaultRange": 40,
      "defaultChannels": "MRC",
      "render_version": 2,
      "seed": 42,
      "intent": "spec_driven",
      "legacy": false
    },
    {
      "id": "spov2_crossed_hone",
      "name": "Crossed Hone",
      "desc": "Crossed Hone assembles abrasive lands, forward grooves, return grooves, crossing burrs and trapped grit.",
      "family": "machine",
      "defaults": {},
      "defaultOpacity": 100,
      "defaultBlendMode": "normal",
      "defaultRange": 40,
      "defaultChannels": "MRC",
      "render_version": 2,
      "seed": 42,
      "surfaceIntent": "spec_driven",
      "legacy": false
    },
    {
      "id": "spov2_peen_crater_cluster",
      "name": "Peen Crater Cluster",
      "desc": "Peen Crater Cluster assembles impact bowls, raised crater lips, secondary strikes, radial tears and flattened crest.",
      "family": "machine",
      "defaults": {},
      "defaultOpacity": 100,
      "defaultBlendMode": "normal",
      "defaultRange": 40,
      "defaultChannels": "MRC",
      "render_version": 2,
      "seed": 42,
      "surfaceIntent": "spec_driven",
      "legacy": false
    },
    {
      "id": "spov2_lapped_chevrons",
      "name": "Lapped Chevrons",
      "desc": "Lapped Chevrons assembles lap faces, lapping edges, return scrapes, keystone pits and feathered tails.",
      "family": "machine",
      "defaults": {},
      "defaultOpacity": 100,
      "defaultBlendMode": "normal",
      "defaultRange": 40,
      "defaultChannels": "MRC",
      "render_version": 2,
      "seed": 42,
      "surfaceIntent": "spec_driven",
      "legacy": false
    },
    {
      "id": "spov2_micro_broach",
      "name": "Micro Broach",
      "desc": "Micro Broach assembles stepped cut floors, tooth shoulders, chip curls, recessed stops and runout tabs.",
      "family": "machine",
      "defaults": {},
      "defaultOpacity": 100,
      "defaultBlendMode": "normal",
      "defaultRange": 40,
      "defaultChannels": "MRC",
      "render_version": 2,
      "seed": 42,
      "surfaceIntent": "spec_driven",
      "legacy": false
    },
    {
      "id": "spov2_fan_cut_lathe",
      "name": "Fan Cut Lathe",
      "desc": "Fan Cut Lathe assembles radial cut faces, hub collars, blade edges, peripheral chips and tool witness arcs.",
      "family": "machine",
      "defaults": {},
      "defaultOpacity": 100,
      "defaultBlendMode": "normal",
      "defaultRange": 40,
      "defaultChannels": "MRC",
      "render_version": 2,
      "seed": 42,
      "surfaceIntent": "spec_driven",
      "legacy": false
    },
    {
      "id": "spov2_chisel_ledger",
      "name": "Chisel Ledger",
      "desc": "Chisel Ledger assembles chisel facets, strike heads, lifted shavings, tail splits and corner gouges.",
      "family": "machine",
      "defaults": {},
      "defaultOpacity": 100,
      "defaultBlendMode": "normal",
      "defaultRange": 40,
      "defaultChannels": "MRC",
      "render_version": 2,
      "seed": 42,
      "surfaceIntent": "spec_driven",
      "legacy": false
    },
    {
      "id": "spov2_slotted_knurl",
      "name": "Slotted Knurl",
      "desc": "Slotted Knurl assembles knurl teeth, relief slots, tooth bevels, corner punches and worn bridges.",
      "family": "machine",
      "defaults": {},
      "defaultOpacity": 100,
      "defaultBlendMode": "normal",
      "defaultRange": 40,
      "defaultChannels": "MRC",
      "render_version": 2,
      "seed": 42,
      "surfaceIntent": "spec_driven",
      "legacy": false
    },
    {
      "id": "spov2_polish_comet",
      "name": "Polish Comet",
      "desc": "Polish Comet assembles polish heads, trailing fans, second fan, compound residue and tail witnesses.",
      "family": "machine",
      "defaults": {},
      "defaultOpacity": 100,
      "defaultBlendMode": "normal",
      "defaultRange": 40,
      "defaultChannels": "MRC",
      "render_version": 2,
      "seed": 42,
      "surfaceIntent": "spec_driven",
      "legacy": false
    },
    {
      "id": "spov2_foil_scarf",
      "name": "Foil Scarf",
      "desc": "Foil Scarf assembles scarfed laps, fold crests, sheared tabs, recessed punches and peel curls.",
      "family": "machine",
      "defaults": {},
      "defaultOpacity": 100,
      "defaultBlendMode": "normal",
      "defaultRange": 40,
      "defaultChannels": "MRC",
      "render_version": 2,
      "seed": 42,
      "surfaceIntent": "spec_driven",
      "legacy": false
    },
    {
      "id": "spov2_etched_gear",
      "name": "Etched Gear",
      "desc": "Etched Gear assembles gear annuli, etched teeth, hub spokes, index keyway and witness dimples.",
      "family": "machine",
      "defaults": {},
      "defaultOpacity": 100,
      "defaultBlendMode": "normal",
      "defaultRange": 40,
      "defaultChannels": "MRC",
      "render_version": 2,
      "seed": 42,
      "surfaceIntent": "spec_driven",
      "legacy": false
    },
    {
      "id": "spov2_triaxial_basket",
      "name": "Triaxial Basket",
      "desc": "Triaxial Basket assembles horizontal tows, ascending tows, descending tows, triangular resin pockets and bundle frays.",
      "family": "weave",
      "defaults": {},
      "defaultOpacity": 100,
      "defaultBlendMode": "normal",
      "defaultRange": 40,
      "defaultChannels": "MRC",
      "render_version": 2,
      "seed": 42,
      "surfaceIntent": "spec_driven",
      "legacy": false
    },
    {
      "id": "spov2_leno_lock",
      "name": "Leno Lock",
      "desc": "Leno Lock assembles countertwisted warp pairs, locking weft passes, underpass resin slots, twist contact shoulders and short loose filaments.",
      "family": "weave",
      "defaults": {},
      "defaultOpacity": 100,
      "defaultBlendMode": "normal",
      "defaultRange": 40,
      "defaultChannels": "MRC",
      "render_version": 2,
      "seed": 42,
      "surfaceIntent": "spec_driven",
      "legacy": false
    },
    {
      "id": "spov2_satin_float",
      "name": "Satin Float",
      "desc": "Satin Float assembles long float caps, buried weft, binding knots, resin channels and raised fiber tips.",
      "family": "weave",
      "defaults": {},
      "defaultOpacity": 100,
      "defaultBlendMode": "normal",
      "defaultRange": 40,
      "defaultChannels": "MRC",
      "render_version": 2,
      "seed": 42,
      "surfaceIntent": "spec_driven",
      "legacy": false
    },
    {
      "id": "spov2_needle_felt",
      "name": "Needle Felt",
      "desc": "Needle Felt assembles compressed fiber pads, tangled fibers, needle punctures, fiber loops and raised nap.",
      "family": "weave",
      "defaults": {},
      "defaultOpacity": 100,
      "defaultBlendMode": "normal",
      "defaultRange": 40,
      "defaultChannels": "MRC",
      "render_version": 2,
      "seed": 42,
      "surfaceIntent": "spec_driven",
      "legacy": false
    },
    {
      "id": "spov2_chopped_tow",
      "name": "Chopped Tow",
      "desc": "Chopped Tow assembles angular tow chips, split bundle edges, epoxy windows, crossing offcuts and torn fiber ends.",
      "family": "weave",
      "defaults": {},
      "defaultOpacity": 100,
      "defaultBlendMode": "normal",
      "defaultRange": 40,
      "defaultChannels": "MRC",
      "render_version": 2,
      "seed": 42,
      "surfaceIntent": "spec_driven",
      "legacy": false
    },
    {
      "id": "spov2_knitted_loop",
      "name": "Knitted Loop",
      "desc": "Knitted Loop assembles loop shoulders, crossed loop legs, underpass knots, loop inner filaments and loose stitch tails.",
      "family": "weave",
      "defaults": {},
      "defaultOpacity": 100,
      "defaultBlendMode": "normal",
      "defaultRange": 40,
      "defaultChannels": "MRC",
      "render_version": 2,
      "seed": 42,
      "surfaceIntent": "spec_driven",
      "legacy": false
    },
    {
      "id": "spov2_chain_stitch",
      "name": "Chain Stitch",
      "desc": "Chain Stitch assembles forward chain links, return chain links, locking bars, needle eyelets and tension scars.",
      "family": "weave",
      "defaults": {},
      "defaultOpacity": 100,
      "defaultBlendMode": "normal",
      "defaultRange": 40,
      "defaultChannels": "MRC",
      "render_version": 2,
      "seed": 42,
      "surfaceIntent": "spec_driven",
      "legacy": false
    },
    {
      "id": "spov2_spacer_mesh",
      "name": "Spacer Mesh",
      "desc": "Spacer Mesh assembles spacer crowns, vertical pillars, buried diagonals, open window rims and resin bridge drops.",
      "family": "weave",
      "defaults": {},
      "defaultOpacity": 100,
      "defaultBlendMode": "normal",
      "defaultRange": 40,
      "defaultChannels": "MRC",
      "render_version": 2,
      "seed": 42,
      "surfaceIntent": "spec_driven",
      "legacy": false
    },
    {
      "id": "spov2_ply_delamination",
      "name": "Ply Delamination",
      "desc": "Ply Delamination assembles lifted ply shingles, peeled lips, exposed underlayers, bridging filaments and epoxy blisters.",
      "family": "weave",
      "defaults": {},
      "defaultOpacity": 100,
      "defaultBlendMode": "normal",
      "defaultRange": 40,
      "defaultChannels": "MRC",
      "render_version": 2,
      "seed": 42,
      "surfaceIntent": "spec_driven",
      "legacy": false
    },
    {
      "id": "spov2_resin_fray",
      "name": "Resin Fray",
      "desc": "Resin Fray assembles resin islands, frayed fiber fans, bundle collars, dry fiber knots and fractured resin tips.",
      "family": "weave",
      "defaults": {},
      "defaultOpacity": 100,
      "defaultBlendMode": "normal",
      "defaultRange": 40,
      "defaultChannels": "MRC",
      "render_version": 2,
      "seed": 42,
      "surfaceIntent": "spec_driven",
      "legacy": false
    },
    {
      "id": "spov2_stitched_hex",
      "name": "Stitched Hex",
      "desc": "Stitched Hex assembles quilted panels, seam stitches, buttoned centers, tension pleats and thread return loops.",
      "family": "weave",
      "defaults": {},
      "defaultOpacity": 100,
      "defaultBlendMode": "normal",
      "defaultRange": 40,
      "defaultChannels": "MRC",
      "render_version": 2,
      "seed": 42,
      "surfaceIntent": "spec_driven",
      "legacy": false
    },
    {
      "id": "spov2_conchoidal_obsidian",
      "name": "Conchoidal Obsidian",
      "desc": "Conchoidal Obsidian assembles shell fracture faces, arrest ridges, impact bulbs, hackle forks and sharp chips.",
      "family": "crystal",
      "defaults": {},
      "defaultOpacity": 100,
      "defaultBlendMode": "normal",
      "defaultRange": 40,
      "defaultChannels": "MRC",
      "render_version": 2,
      "seed": 42,
      "surfaceIntent": "spec_driven",
      "legacy": false
    },
    {
      "id": "spov2_basalt_prisms",
      "name": "Basalt Prisms",
      "desc": "Basalt Prisms assembles broken column caps, prismatic column sides, bundle joint recesses, vesicle socket pairs and fractured root chips.",
      "family": "crystal",
      "defaults": {},
      "defaultOpacity": 100,
      "defaultBlendMode": "normal",
      "defaultRange": 40,
      "defaultChannels": "MRC",
      "render_version": 2,
      "seed": 42,
      "surfaceIntent": "spec_driven",
      "legacy": false
    },
    {
      "id": "spov2_tourmaline_spindles",
      "name": "Tourmaline Spindles",
      "desc": "Tourmaline Spindles assembles elongate prism faces, longitudinal flutes, termination facets, broken roots and crosswise inclusions.",
      "family": "crystal",
      "defaults": {},
      "defaultOpacity": 100,
      "defaultBlendMode": "normal",
      "defaultRange": 40,
      "defaultChannels": "MRC",
      "render_version": 2,
      "seed": 42,
      "surfaceIntent": "spec_driven",
      "legacy": false
    },
    {
      "id": "spov2_pyrite_cuboids",
      "name": "Pyrite Cuboids",
      "desc": "Pyrite Cuboids assembles cubic twin roof faces, penetrant cube sidewalls, intergrowth contact grooves, growth face striations and crumbled sulfide corners.",
      "family": "crystal",
      "defaults": {},
      "defaultOpacity": 100,
      "defaultBlendMode": "normal",
      "defaultRange": 40,
      "defaultChannels": "MRC",
      "render_version": 2,
      "seed": 42,
      "surfaceIntent": "spec_driven",
      "legacy": false
    },
    {
      "id": "spov2_mica_books",
      "name": "Mica Books",
      "desc": "Mica Books assembles cleavage leaves, book edges, lifted leaf corners, dark interleaf pockets and fracture pinholes.",
      "family": "crystal",
      "defaults": {},
      "defaultOpacity": 100,
      "defaultBlendMode": "normal",
      "defaultRange": 40,
      "defaultChannels": "MRC",
      "render_version": 2,
      "seed": 42,
      "surfaceIntent": "spec_driven",
      "legacy": false
    },
    {
      "id": "spov2_dendrite_fern",
      "name": "Dendrite Fern",
      "desc": "Dendrite Fern assembles primary growth stems, lateral dendrite arms, branch tip plates, interarm deposits and stem growth nodes.",
      "family": "crystal",
      "defaults": {},
      "defaultOpacity": 100,
      "defaultBlendMode": "normal",
      "defaultRange": 40,
      "defaultChannels": "MRC",
      "render_version": 2,
      "seed": 42,
      "surfaceIntent": "spec_driven",
      "legacy": false
    },
    {
      "id": "spov2_salt_hoppers",
      "name": "Salt Hoppers",
      "desc": "Salt Hoppers assembles hopper terraces, raised square rims, hollow growth centers, corner bridges and salt satellites.",
      "family": "crystal",
      "defaults": {},
      "defaultOpacity": 100,
      "defaultBlendMode": "normal",
      "defaultRange": 40,
      "defaultChannels": "MRC",
      "render_version": 2,
      "seed": 42,
      "surfaceIntent": "spec_driven",
      "legacy": false
    },
    {
      "id": "spov2_quartz_clusters",
      "name": "Quartz Clusters",
      "desc": "Quartz Clusters assembles splayed crystal prisms, central intergrowth faces, pyramidal termination edges, root inclusion matrix and healed prism fractures.",
      "family": "crystal",
      "defaults": {},
      "defaultOpacity": 100,
      "defaultBlendMode": "normal",
      "defaultRange": 40,
      "defaultChannels": "MRC",
      "render_version": 2,
      "seed": 42,
      "surfaceIntent": "spec_driven",
      "legacy": false
    },
    {
      "id": "spov2_spherulite_frost",
      "name": "Spherulite Frost",
      "desc": "Spherulite Frost assembles radiating crystal fans, frozen growth fronts, nucleation pits, fan boundary clefts and satellite ice tabs.",
      "family": "crystal",
      "defaults": {},
      "defaultOpacity": 100,
      "defaultBlendMode": "normal",
      "defaultRange": 40,
      "defaultChannels": "MRC",
      "render_version": 2,
      "seed": 42,
      "surfaceIntent": "spec_driven",
      "legacy": false
    },
    {
      "id": "spov2_botryoidal_buds",
      "name": "Botryoidal Buds",
      "desc": "Botryoidal Buds assembles merged mineral buds, growth layer rings, bud junction valleys, satellite nodules and fractured bud windows.",
      "family": "crystal",
      "defaults": {},
      "defaultOpacity": 100,
      "defaultBlendMode": "normal",
      "defaultRange": 40,
      "defaultChannels": "MRC",
      "render_version": 2,
      "seed": 42,
      "surfaceIntent": "spec_driven",
      "legacy": false
    },
    {
      "id": "spov2_barite_petals",
      "name": "Barite Petals",
      "desc": "Barite Petals assembles tabular petal faces, crossing crystal blades, petal growth rims, matrix pockets and cleaved petal tips.",
      "family": "crystal",
      "defaults": {},
      "defaultOpacity": 100,
      "defaultBlendMode": "normal",
      "defaultRange": 40,
      "defaultChannels": "MRC",
      "render_version": 2,
      "seed": 42,
      "surfaceIntent": "spec_driven",
      "legacy": false
    },
    {
      "id": "spov2_pangolin_shingles",
      "name": "Pangolin Shingles",
      "desc": "Pangolin Shingles assembles keratin shingles, scale overlap rims, growth furrows, protected scale roots and polished scale tips.",
      "family": "skin",
      "defaults": {},
      "defaultOpacity": 100,
      "defaultBlendMode": "normal",
      "defaultRange": 40,
      "defaultChannels": "MRC",
      "render_version": 2,
      "seed": 42,
      "surfaceIntent": "spec_driven",
      "legacy": false
    },
    {
      "id": "spov2_feather_barbules",
      "name": "Feather Barbules",
      "desc": "Feather Barbules assembles barb shafts, hooked barbules, interlocking slots, barbule hook heads and abraded shaft nodes.",
      "family": "skin",
      "defaults": {},
      "defaultOpacity": 100,
      "defaultBlendMode": "normal",
      "defaultRange": 40,
      "defaultChannels": "MRC",
      "render_version": 2,
      "seed": 42,
      "surfaceIntent": "spec_driven",
      "legacy": false
    },
    {
      "id": "spov2_crocodile_scutes",
      "name": "Crocodile Scutes",
      "desc": "Crocodile Scutes assembles scute plates, raised dorsal keels, flexible sutures, sensory pits and growth corner rings.",
      "family": "skin",
      "defaults": {},
      "defaultOpacity": 100,
      "defaultBlendMode": "normal",
      "defaultRange": 40,
      "defaultChannels": "MRC",
      "render_version": 2,
      "seed": 42,
      "surfaceIntent": "spec_driven",
      "legacy": false
    },
    {
      "id": "spov2_wing_scale_sockets",
      "name": "Wing Scale Sockets",
      "desc": "Wing Scale Sockets assembles scale blades, longitudinal ribs, socket cups, cross rib windows and serrated blade ends.",
      "family": "skin",
      "defaults": {},
      "defaultOpacity": 100,
      "defaultBlendMode": "normal",
      "defaultRange": 40,
      "defaultChannels": "MRC",
      "render_version": 2,
      "seed": 42,
      "surfaceIntent": "spec_driven",
      "legacy": false
    },
    {
      "id": "spov2_coral_polyps",
      "name": "Coral Polyps",
      "desc": "Coral Polyps assembles polyp septa, calice walls, central mouths, connecting coenosteum and budding sockets.",
      "family": "skin",
      "defaults": {},
      "defaultOpacity": 100,
      "defaultBlendMode": "normal",
      "defaultRange": 40,
      "defaultChannels": "MRC",
      "render_version": 2,
      "seed": 42,
      "surfaceIntent": "spec_driven",
      "legacy": false
    },
    {
      "id": "spov2_cell_division",
      "name": "Cell Division",
      "desc": "Cell Division assembles daughter cell membranes, contractile furrows, membrane lips, paired nuclei and vesicle chains.",
      "family": "skin",
      "defaults": {},
      "defaultOpacity": 100,
      "defaultBlendMode": "normal",
      "defaultRange": 40,
      "defaultChannels": "MRC",
      "render_version": 2,
      "seed": 42,
      "surfaceIntent": "spec_driven",
      "legacy": false
    },
    {
      "id": "spov2_leaf_stomata",
      "name": "Leaf Stomata",
      "desc": "Leaf Stomata assembles guard cell pairs, stomatal apertures, raised pore lips, cuticle folds and wax platelets.",
      "family": "skin",
      "defaults": {},
      "defaultOpacity": 100,
      "defaultBlendMode": "normal",
      "defaultRange": 40,
      "defaultChannels": "MRC",
      "render_version": 2,
      "seed": 42,
      "surfaceIntent": "spec_driven",
      "legacy": false
    },
    {
      "id": "spov2_mushroom_gills",
      "name": "Mushroom Gills",
      "desc": "Mushroom Gills assembles radial lamella blades, short intercalary gills, gill attachment roots, spore print clusters and torn lamella tips.",
      "family": "skin",
      "defaults": {},
      "defaultOpacity": 100,
      "defaultBlendMode": "normal",
      "defaultRange": 40,
      "defaultChannels": "MRC",
      "render_version": 2,
      "seed": 42,
      "surfaceIntent": "spec_driven",
      "legacy": false
    },
    {
      "id": "spov2_trabecular_pores",
      "name": "Trabecular Pores",
      "desc": "Trabecular Pores assembles porous bone walls, load bearing struts, marrow recesses, pore neck rims and remodeling pits.",
      "family": "skin",
      "defaults": {},
      "defaultOpacity": 100,
      "defaultBlendMode": "normal",
      "defaultRange": 40,
      "defaultChannels": "MRC",
      "render_version": 2,
      "seed": 42,
      "surfaceIntent": "spec_driven",
      "legacy": false
    },
    {
      "id": "spov2_retinal_mosaic",
      "name": "Retinal Mosaic",
      "desc": "Retinal Mosaic assembles cone receptor bodies, elongate rod pairs, receptor membrane lips, synaptic contact bridges and pigment granule pockets.",
      "family": "skin",
      "defaults": {},
      "defaultOpacity": 100,
      "defaultBlendMode": "normal",
      "defaultRange": 40,
      "defaultChannels": "MRC",
      "render_version": 2,
      "seed": 42,
      "surfaceIntent": "spec_driven",
      "legacy": false
    },
    {
      "id": "spov2_dew_lenses",
      "name": "Dew Lenses",
      "desc": "Dew Lenses assembles convex dew lenses, pinned contact rims, coalescence necks, dry dust islands and satellite bead collars.",
      "family": "liquid",
      "defaults": {},
      "defaultOpacity": 100,
      "defaultBlendMode": "normal",
      "defaultRange": 40,
      "defaultChannels": "MRC",
      "render_version": 2,
      "seed": 42,
      "surfaceIntent": "spec_driven",
      "legacy": false
    },
    {
      "id": "spov2_capillary_rivulets",
      "name": "Capillary Rivulets",
      "desc": "Capillary Rivulets assembles branching wet channels, asymmetric wetting lobes, receded channel edges, junction reservoir pits and detached capillary beads.",
      "family": "liquid",
      "defaults": {},
      "defaultOpacity": 100,
      "defaultBlendMode": "normal",
      "defaultRange": 40,
      "defaultChannels": "MRC",
      "render_version": 2,
      "seed": 42,
      "surfaceIntent": "spec_driven",
      "legacy": false
    },
    {
      "id": "spov2_marangoni_fans",
      "name": "Marangoni Fans",
      "desc": "Marangoni Fans assembles fan flow lobes, flow separatrices, source meniscus, deposit fan fronts and bead pinning clusters.",
      "family": "liquid",
      "defaults": {},
      "defaultOpacity": 100,
      "defaultBlendMode": "normal",
      "defaultRange": 40,
      "defaultChannels": "MRC",
      "render_version": 2,
      "seed": 42,
      "surfaceIntent": "spec_driven",
      "legacy": false
    },
    {
      "id": "spov2_drying_fronts",
      "name": "Drying Fronts",
      "desc": "Drying Fronts assembles wet remnant bands, receding front lips, dried residue islands, arrested drop tails and contact line beads.",
      "family": "liquid",
      "defaults": {},
      "defaultOpacity": 100,
      "defaultBlendMode": "normal",
      "defaultRange": 40,
      "defaultChannels": "MRC",
      "render_version": 2,
      "seed": 42,
      "surfaceIntent": "spec_driven",
      "legacy": false
    },
    {
      "id": "spov2_foam_raft",
      "name": "Foam Raft",
      "desc": "Foam Raft assembles bubble film faces, plateau borders, thinning film windows, drainage necks and burst film tabs.",
      "family": "liquid",
      "defaults": {},
      "defaultOpacity": 100,
      "defaultBlendMode": "normal",
      "defaultRange": 40,
      "defaultChannels": "MRC",
      "render_version": 2,
      "seed": 42,
      "surfaceIntent": "spec_driven",
      "legacy": false
    },
    {
      "id": "spov2_fisheye_crater",
      "name": "Fisheye Crater",
      "desc": "Fisheye Crater assembles dewetting crater slopes, raised coating rings, contaminant cores, radial coat tears and residue splashes.",
      "family": "liquid",
      "defaults": {},
      "defaultOpacity": 100,
      "defaultBlendMode": "normal",
      "defaultRange": 40,
      "defaultChannels": "MRC",
      "render_version": 2,
      "seed": 42,
      "surfaceIntent": "spec_driven",
      "legacy": false
    },
    {
      "id": "spov2_orange_peel_film",
      "name": "Orange Peel Film",
      "desc": "Orange Peel Film assembles coating hillocks, valley polish arcs, solvent pop pores, flow leveling saddles and dust nib collars.",
      "family": "liquid",
      "defaults": {},
      "defaultOpacity": 100,
      "defaultBlendMode": "normal",
      "defaultRange": 40,
      "defaultChannels": "MRC",
      "render_version": 2,
      "seed": 42,
      "surfaceIntent": "spec_driven",
      "legacy": false
    },
    {
      "id": "spov2_spray_coalescence",
      "name": "Spray Coalescence",
      "desc": "Spray Coalescence assembles merged spray islands, scalloped island edges, three drop junctions, satellite mist drops and dry spray necks.",
      "family": "liquid",
      "defaults": {},
      "defaultOpacity": 100,
      "defaultBlendMode": "normal",
      "defaultRange": 40,
      "defaultChannels": "MRC",
      "render_version": 2,
      "seed": 42,
      "surfaceIntent": "spec_driven",
      "legacy": false
    },
    {
      "id": "spov2_varnish_lace",
      "name": "Varnish Lace",
      "desc": "Varnish Lace assembles varnish lace webs, thickened web junctions, broken film apertures, edge curl tabs and dust trapped beads.",
      "family": "liquid",
      "defaults": {},
      "defaultOpacity": 100,
      "defaultBlendMode": "normal",
      "defaultRange": 40,
      "defaultChannels": "MRC",
      "render_version": 2,
      "seed": 42,
      "surfaceIntent": "spec_driven",
      "legacy": false
    },
    {
      "id": "spov2_rheology_combs",
      "name": "Rheology Combs",
      "desc": "Rheology Combs assembles viscous fingers, finger tip caps, trailing furrows, side comb teeth and recoil meniscus loops.",
      "family": "liquid",
      "defaults": {},
      "defaultOpacity": 100,
      "defaultBlendMode": "normal",
      "defaultRange": 40,
      "defaultChannels": "MRC",
      "render_version": 2,
      "seed": 42,
      "surfaceIntent": "spec_driven",
      "legacy": false
    },
    {
      "id": "spov2_ink_reticulation",
      "name": "Ink Reticulation",
      "desc": "Ink Reticulation assembles reticulated film banks, rupture network, retained ink pools, short drying feathers and pigment aggregate islets.",
      "family": "liquid",
      "defaults": {},
      "defaultOpacity": 100,
      "defaultBlendMode": "normal",
      "defaultRange": 40,
      "defaultChannels": "MRC",
      "render_version": 2,
      "seed": 42,
      "surfaceIntent": "spec_driven",
      "legacy": false
    },
    {
      "id": "spov2_mud_crackle",
      "name": "Mud Crackle",
      "desc": "Mud Crackle assembles dry mud platelets, shrinkage fissures, curled plate edges, secondary dry checks and crumbled grit pockets.",
      "family": "crack",
      "defaults": {},
      "defaultOpacity": 100,
      "defaultBlendMode": "normal",
      "defaultRange": 40,
      "defaultChannels": "MRC",
      "render_version": 2,
      "seed": 42,
      "surfaceIntent": "spec_driven",
      "legacy": false
    },
    {
      "id": "spov2_wrinkled_lacquer",
      "name": "Wrinkled Lacquer",
      "desc": "Wrinkled Lacquer assembles compressed lacquer ridges, fold crest splits, polished wrinkle shoulders, cross fold creases and trapped coat bubbles.",
      "family": "crack",
      "defaults": {},
      "defaultOpacity": 100,
      "defaultBlendMode": "normal",
      "defaultRange": 40,
      "defaultChannels": "MRC",
      "render_version": 2,
      "seed": 42,
      "surfaceIntent": "spec_driven",
      "legacy": false
    },
    {
      "id": "spov2_corrosion_blisters",
      "name": "Corrosion Blisters",
      "desc": "Corrosion Blisters assembles lifted blister caps, ruptured radial flaps, corrosion halos, exposed core windows and oxide satellite grains.",
      "family": "crack",
      "defaults": {},
      "defaultOpacity": 100,
      "defaultBlendMode": "normal",
      "defaultRange": 40,
      "defaultChannels": "MRC",
      "render_version": 2,
      "seed": 42,
      "surfaceIntent": "spec_driven",
      "legacy": false
    },
    {
      "id": "spov2_spall_islands",
      "name": "Spall Islands",
      "desc": "Spall Islands assembles retained coating flakes, spalled substrate windows, undercut flake edges, shear bridge filaments and detached chip triads.",
      "family": "crack",
      "defaults": {},
      "defaultOpacity": 100,
      "defaultBlendMode": "normal",
      "defaultRange": 40,
      "defaultChannels": "MRC",
      "render_version": 2,
      "seed": 42,
      "surfaceIntent": "spec_driven",
      "legacy": false
    },
    {
      "id": "spov2_stress_star_crazing",
      "name": "Stress Star Crazing",
      "desc": "Stress Star Crazing assembles stress field platelets, radial star fissures, impact center chips, arrest branch segments and fissure tip tabs.",
      "family": "crack",
      "defaults": {},
      "defaultOpacity": 100,
      "defaultBlendMode": "normal",
      "defaultRange": 40,
      "defaultChannels": "MRC",
      "render_version": 2,
      "seed": 42,
      "surfaceIntent": "spec_driven",
      "legacy": false
    },
    {
      "id": "spov2_scuffed_enamel",
      "name": "Scuffed Enamel",
      "desc": "Scuffed Enamel assembles enamel witness pads, abrasion sweeps, embedded road grit, chipped scuff starts and burnished exit hooks.",
      "family": "crack",
      "defaults": {},
      "defaultOpacity": 100,
      "defaultBlendMode": "normal",
      "defaultRange": 40,
      "defaultChannels": "MRC",
      "render_version": 2,
      "seed": 42,
      "surfaceIntent": "spec_driven",
      "legacy": false
    },
    {
      "id": "spov2_freeze_thaw",
      "name": "Freeze Thaw",
      "desc": "Freeze Thaw assembles frost lifted wedges, ice jacking splits, fresh fracture faces, stepped frost lenses and friable grain clusters.",
      "family": "crack",
      "defaults": {},
      "defaultOpacity": 100,
      "defaultBlendMode": "normal",
      "defaultRange": 40,
      "defaultChannels": "MRC",
      "render_version": 2,
      "seed": 42,
      "surfaceIntent": "spec_driven",
      "legacy": false
    },
    {
      "id": "spov2_oxide_pitting",
      "name": "Oxide Pitting",
      "desc": "Oxide Pitting assembles oxidized pit slopes, undercut pit lips, deep corrosion pores, oxide growth needles and passivated bridge islets.",
      "family": "crack",
      "defaults": {},
      "defaultOpacity": 100,
      "defaultBlendMode": "normal",
      "defaultRange": 40,
      "defaultChannels": "MRC",
      "render_version": 2,
      "seed": 42,
      "surfaceIntent": "spec_driven",
      "legacy": false
    },
    {
      "id": "spov2_creased_foil",
      "name": "Creased Foil",
      "desc": "Creased Foil assembles crumpled foil facets, fold intersections, fatigue crease splits, pinched corner tabs and crease scuff lozenges.",
      "family": "crack",
      "defaults": {},
      "defaultOpacity": 100,
      "defaultBlendMode": "normal",
      "defaultRange": 40,
      "defaultChannels": "MRC",
      "render_version": 2,
      "seed": 42,
      "surfaceIntent": "spec_driven",
      "legacy": false
    },
    {
      "id": "spov2_alligator_coat",
      "name": "Alligator Coat",
      "desc": "Alligator Coat assembles aged coating blocks, deep coat channels, curled block shoulders, secondary cross checks and exposed corner chips.",
      "family": "crack",
      "defaults": {},
      "defaultOpacity": 100,
      "defaultBlendMode": "normal",
      "defaultRange": 40,
      "defaultChannels": "MRC",
      "render_version": 2,
      "seed": 42,
      "surfaceIntent": "spec_driven",
      "legacy": false
    },
    {
      "id": "spov2_micro_chipping",
      "name": "Micro Chipping",
      "desc": "Micro Chipping assembles stone chip craters, bare chip centers, fractured enamel rims, impact comet scars and detached paint specks.",
      "family": "crack",
      "defaults": {},
      "defaultOpacity": 100,
      "defaultBlendMode": "normal",
      "defaultRange": 40,
      "defaultChannels": "MRC",
      "render_version": 2,
      "seed": 42,
      "surfaceIntent": "spec_driven",
      "legacy": false
    },
    {
      "id": "spov2_fresnel_segments",
      "name": "Fresnel Segments",
      "desc": "Fresnel Segments assembles stepped lens segments, facet reset edges, segment separator slots, lens center tabs and truncated facet corners.",
      "family": "optical",
      "defaults": {},
      "defaultOpacity": 100,
      "defaultBlendMode": "normal",
      "defaultRange": 40,
      "defaultChannels": "MRC",
      "render_version": 2,
      "seed": 42,
      "surfaceIntent": "spec_driven",
      "legacy": false
    },
    {
      "id": "spov2_moire_packets",
      "name": "Moire Packets",
      "desc": "Moire Packets assembles crossed grating packets, grating beat nodes, packet separation gutters, registration tick clusters and etched aperture windows.",
      "family": "optical",
      "defaults": {},
      "defaultOpacity": 100,
      "defaultBlendMode": "normal",
      "defaultRange": 40,
      "defaultChannels": "MRC",
      "render_version": 2,
      "seed": 42,
      "surfaceIntent": "spec_driven",
      "legacy": false
    },
    {
      "id": "spov2_prism_herringbone",
      "name": "Prism Herringbone",
      "desc": "Prism Herringbone assembles prismatic ribbons, ridge breaks, end face sockets, cross prism notches and polished terminal facets.",
      "family": "optical",
      "defaults": {},
      "defaultOpacity": 100,
      "defaultBlendMode": "normal",
      "defaultRange": 40,
      "defaultChannels": "MRC",
      "render_version": 2,
      "seed": 42,
      "surfaceIntent": "spec_driven",
      "legacy": false
    },
    {
      "id": "spov2_coded_apertures",
      "name": "Coded Apertures",
      "desc": "Coded Apertures assembles coded opaque platelets, milled aperture windows, polished window chamfers, registration diamonds and interrupted support tabs.",
      "family": "optical",
      "defaults": {},
      "defaultOpacity": 100,
      "defaultBlendMode": "normal",
      "defaultRange": 40,
      "defaultChannels": "MRC",
      "render_version": 2,
      "seed": 42,
      "surfaceIntent": "spec_driven",
      "legacy": false
    },
    {
      "id": "spov2_reflector_triplets",
      "name": "Reflector Triplets",
      "desc": "Reflector Triplets assembles three corner faces, corner cube seams, central return pits, reflector border tabs and chipped cube tips.",
      "family": "optical",
      "defaults": {},
      "defaultOpacity": 100,
      "defaultBlendMode": "normal",
      "defaultRange": 40,
      "defaultChannels": "MRC",
      "render_version": 2,
      "seed": 42,
      "surfaceIntent": "spec_driven",
      "legacy": false
    },
    {
      "id": "spov2_polar_starlets",
      "name": "Polar Starlets",
      "desc": "Polar Starlets assembles polar facet stars, radial bevel spines, etched star centers, detached facet slivers and star tip witnesses.",
      "family": "optical",
      "defaults": {},
      "defaultOpacity": 100,
      "defaultBlendMode": "normal",
      "defaultRange": 40,
      "defaultChannels": "MRC",
      "render_version": 2,
      "seed": 42,
      "surfaceIntent": "spec_driven",
      "legacy": false
    },
    {
      "id": "spov2_waveguide_meander",
      "name": "Waveguide Meander",
      "desc": "Waveguide Meander assembles meandering guide ribbons, guide turn crowns, absorbing terminations, coupling bridge ports and etched locator dots.",
      "family": "optical",
      "defaults": {},
      "defaultOpacity": 100,
      "defaultBlendMode": "normal",
      "defaultRange": 40,
      "defaultChannels": "MRC",
      "render_version": 2,
      "seed": 42,
      "surfaceIntent": "spec_driven",
      "legacy": false
    },
    {
      "id": "spov2_split_lenslets",
      "name": "Split Lenslets",
      "desc": "Split Lenslets assembles left lens half, right registered half, diagonal registration slits, lens mount shoulders and alignment witness pairs.",
      "family": "optical",
      "defaults": {},
      "defaultOpacity": 100,
      "defaultBlendMode": "normal",
      "defaultRange": 40,
      "defaultChannels": "MRC",
      "render_version": 2,
      "seed": 42,
      "surfaceIntent": "spec_driven",
      "legacy": false
    },
    {
      "id": "spov2_zone_plate_shards",
      "name": "Zone Plate Shards",
      "desc": "Zone Plate Shards assembles broken zone plate sectors, sector facet boundaries, shard edge losses, recessed focus arclets and detached plate grains.",
      "family": "optical",
      "defaults": {},
      "defaultOpacity": 100,
      "defaultBlendMode": "normal",
      "defaultRange": 40,
      "defaultChannels": "MRC",
      "render_version": 2,
      "seed": 42,
      "surfaceIntent": "spec_driven",
      "legacy": false
    },
    {
      "id": "spov2_diffractive_hatch",
      "name": "Diffractive Hatch",
      "desc": "Diffractive Hatch assembles segmented grating lands, hatch crosscuts, polished grating crests, missing grating teeth and termination fan tabs.",
      "family": "optical",
      "defaults": {},
      "defaultOpacity": 100,
      "defaultBlendMode": "normal",
      "defaultRange": 40,
      "defaultChannels": "MRC",
      "render_version": 2,
      "seed": 42,
      "surfaceIntent": "spec_driven",
      "legacy": false
    },
    {
      "id": "spov2_optic_pinwheels",
      "name": "Optic Pinwheels",
      "desc": "Optic Pinwheels assembles folded angular sails, sail fold crests, central rotor hubs, blade clearance notches and registration pinholes.",
      "family": "optical",
      "defaults": {},
      "defaultOpacity": 100,
      "defaultBlendMode": "normal",
      "defaultRange": 40,
      "defaultChannels": "MRC",
      "render_version": 2,
      "seed": 42,
      "surfaceIntent": "spec_driven",
      "legacy": false
    },
    {
      "id": "spov2_damascene_inlay",
      "name": "Damascene Inlay",
      "desc": "Damascene Inlay assembles inlaid leaf blades, scrolling inlay stems, undercut inlay channels, leaf vein burin cuts and stippling rosettes.",
      "family": "engraved",
      "defaults": {},
      "defaultOpacity": 100,
      "defaultBlendMode": "normal",
      "defaultRange": 40,
      "defaultChannels": "MRC",
      "render_version": 2,
      "seed": 42,
      "surfaceIntent": "spec_driven",
      "legacy": false
    },
    {
      "id": "spov2_engine_turn_medallions",
      "name": "Engine Turn Medallions",
      "desc": "Engine Turn Medallions assembles eccentric turning faces, nested burin arclets, medallion separation cuts, turning spindle pits and burnished border tabs.",
      "family": "engraved",
      "defaults": {},
      "defaultOpacity": 100,
      "defaultBlendMode": "normal",
      "defaultRange": 40,
      "defaultChannels": "MRC",
      "render_version": 2,
      "seed": 42,
      "surfaceIntent": "spec_driven",
      "legacy": false
    },
    {
      "id": "spov2_barleycorn_cuts",
      "name": "Barleycorn Cuts",
      "desc": "Barleycorn Cuts assembles barley grain facets, central grain keels, separating burin hollows, cross grain veins and terminal stipple beads.",
      "family": "engraved",
      "defaults": {},
      "defaultOpacity": 100,
      "defaultBlendMode": "normal",
      "defaultRange": 40,
      "defaultChannels": "MRC",
      "render_version": 2,
      "seed": 42,
      "surfaceIntent": "spec_driven",
      "legacy": false
    },
    {
      "id": "spov2_florentine_hatch",
      "name": "Florentine Hatch",
      "desc": "Florentine Hatch assembles first chisel hatching, crosscut engraving, recessed cut starts, raised chisel shoulders and crossing burr clusters.",
      "family": "engraved",
      "defaults": {},
      "defaultOpacity": 100,
      "defaultBlendMode": "normal",
      "defaultRange": 40,
      "defaultChannels": "MRC",
      "render_version": 2,
      "seed": 42,
      "surfaceIntent": "spec_driven",
      "legacy": false
    },
    {
      "id": "spov2_acanthus_scrolls",
      "name": "Acanthus Scrolls",
      "desc": "Acanthus Scrolls assembles acanthus leaf lobes, engraved leaf spines, recessed scroll eyes, lobed leaf serrations and curled leaf tips.",
      "family": "engraved",
      "defaults": {},
      "defaultOpacity": 100,
      "defaultBlendMode": "normal",
      "defaultRange": 40,
      "defaultChannels": "MRC",
      "render_version": 2,
      "seed": 42,
      "surfaceIntent": "spec_driven",
      "legacy": false
    },
    {
      "id": "spov2_celtic_triskeles",
      "name": "Celtic Triskeles",
      "desc": "Celtic Triskeles assembles three spiral bands, spiral outer bevels, interlace underpass breaks, central binding knot and engraver endpoint beads.",
      "family": "engraved",
      "defaults": {},
      "defaultOpacity": 100,
      "defaultBlendMode": "normal",
      "defaultRange": 40,
      "defaultChannels": "MRC",
      "render_version": 2,
      "seed": 42,
      "surfaceIntent": "spec_driven",
      "legacy": false
    },
    {
      "id": "spov2_seigaiha_etching",
      "name": "Seigaiha Etching",
      "desc": "Seigaiha Etching assembles nested wave arches, wave crest burin lines, engraved tide gutters, wave foot knots and crest stippling pairs.",
      "family": "engraved",
      "defaults": {},
      "defaultOpacity": 100,
      "defaultBlendMode": "normal",
      "defaultRange": 40,
      "defaultChannels": "MRC",
      "render_version": 2,
      "seed": 42,
      "surfaceIntent": "spec_driven",
      "legacy": false
    },
    {
      "id": "spov2_art_deco_fans",
      "name": "Art Deco Fans",
      "desc": "Art Deco Fans assembles sunburst fan facets, radiating fan inlays, recessed fan bases, stepped fan borders and deco corner gems.",
      "family": "engraved",
      "defaults": {},
      "defaultOpacity": 100,
      "defaultBlendMode": "normal",
      "defaultRange": 40,
      "defaultChannels": "MRC",
      "render_version": 2,
      "seed": 42,
      "surfaceIntent": "spec_driven",
      "legacy": false
    },
    {
      "id": "spov2_micro_cartouches",
      "name": "Micro Cartouches",
      "desc": "Micro Cartouches assembles engraved cartouche frames, inner burnished shields, recessed scroll tabs, central engraver flourishes and border witness beads.",
      "family": "engraved",
      "defaults": {},
      "defaultOpacity": 100,
      "defaultBlendMode": "normal",
      "defaultRange": 40,
      "defaultChannels": "MRC",
      "render_version": 2,
      "seed": 42,
      "surfaceIntent": "spec_driven",
      "legacy": false
    },
    {
      "id": "spov2_laurel_links",
      "name": "Laurel Links",
      "desc": "Laurel Links assembles paired laurel leaves, interlinked leaf stems, engraved leaf midribs, leaf base ties and laurel berry beads.",
      "family": "engraved",
      "defaults": {},
      "defaultOpacity": 100,
      "defaultBlendMode": "normal",
      "defaultRange": 40,
      "defaultChannels": "MRC",
      "render_version": 2,
      "seed": 42,
      "surfaceIntent": "spec_driven",
      "legacy": false
    },
    {
      "id": "spov2_rope_filigree",
      "name": "Rope Filigree",
      "desc": "Rope Filigree assembles twisted rope rings, rope crossing splices, filigree center openings, soldered link tabs and terminal wire curls.",
      "family": "engraved",
      "defaults": {},
      "defaultOpacity": 100,
      "defaultBlendMode": "normal",
      "defaultRange": 40,
      "defaultChannels": "MRC",
      "render_version": 2,
      "seed": 42,
      "surfaceIntent": "spec_driven",
      "legacy": false
    },
    {
      "id": "spov2_tire_sipes",
      "name": "Tire Sipes",
      "desc": "Tire Sipes assembles tread block faces, zigzag sipe cuts, polished tread shoulders, transverse drainage notches and rubber pickup nibs.",
      "family": "track",
      "defaults": {},
      "defaultOpacity": 100,
      "defaultBlendMode": "normal",
      "defaultRange": 40,
      "defaultChannels": "MRC",
      "render_version": 2,
      "seed": 42,
      "surfaceIntent": "spec_driven",
      "legacy": false
    },
    {
      "id": "spov2_brake_rotor_slots",
      "name": "Brake Rotor Slots",
      "desc": "Brake Rotor Slots assembles rotor swept lands, curved degas slots, slot chamfers, wear track arclets and drilled cooling pores.",
      "family": "track",
      "defaults": {},
      "defaultOpacity": 100,
      "defaultBlendMode": "normal",
      "defaultRange": 40,
      "defaultChannels": "MRC",
      "render_version": 2,
      "seed": 42,
      "surfaceIntent": "spec_driven",
      "legacy": false
    },
    {
      "id": "spov2_pit_crew_grip",
      "name": "Pit Crew Grip",
      "desc": "Pit Crew Grip assembles molded grip lugs, raised lug crowns, grip drain channels, lug flex notches and contact wear dimples.",
      "family": "track",
      "defaults": {},
      "defaultOpacity": 100,
      "defaultBlendMode": "normal",
      "defaultRange": 40,
      "defaultChannels": "MRC",
      "render_version": 2,
      "seed": 42,
      "surfaceIntent": "spec_driven",
      "legacy": false
    },
    {
      "id": "spov2_carbon_brake_grain",
      "name": "Carbon Brake Grain",
      "desc": "Carbon Brake Grain assembles compacted carbon grains, fractured fiber fragments, venting matrix pores, resin conversion rims and polished grain tips.",
      "family": "track",
      "defaults": {},
      "defaultOpacity": 100,
      "defaultBlendMode": "normal",
      "defaultRange": 40,
      "defaultChannels": "MRC",
      "render_version": 2,
      "seed": 42,
      "surfaceIntent": "spec_driven",
      "legacy": false
    },
    {
      "id": "spov2_checkered_microfoil",
      "name": "Checkered Microfoil",
      "desc": "Checkered Microfoil assembles checker foil squares, creased foil ridges, torn fragment borders, exposed adhesive tabs and folded checker corners.",
      "family": "track",
      "defaults": {},
      "defaultOpacity": 100,
      "defaultBlendMode": "normal",
      "defaultRange": 40,
      "defaultChannels": "MRC",
      "render_version": 2,
      "seed": 42,
      "surfaceIntent": "spec_driven",
      "legacy": false
    },
    {
      "id": "spov2_telemetry_dash",
      "name": "Telemetry Dash",
      "desc": "Telemetry Dash assembles telemetry bar packets, peak hold markers, display grid gutters, sampling clock tabs and signal trace kinks.",
      "family": "track",
      "defaults": {},
      "defaultOpacity": 100,
      "defaultBlendMode": "normal",
      "defaultRange": 40,
      "defaultChannels": "MRC",
      "render_version": 2,
      "seed": 42,
      "surfaceIntent": "spec_driven",
      "legacy": false
    },
    {
      "id": "spov2_rumble_strip_ticks",
      "name": "Rumble Strip Ticks",
      "desc": "Rumble Strip Ticks assembles kerb ramp packets, grooved strip separators, worn kerb shoulders, aggregate breakouts and tire witness ticks.",
      "family": "track",
      "defaults": {},
      "defaultOpacity": 100,
      "defaultBlendMode": "normal",
      "defaultRange": 40,
      "defaultChannels": "MRC",
      "render_version": 2,
      "seed": 42,
      "surfaceIntent": "spec_driven",
      "legacy": false
    },
    {
      "id": "spov2_grid_stencil_mesh",
      "name": "Grid Stencil Mesh",
      "desc": "Grid Stencil Mesh assembles stencil cell frames, stencil bridge tabs, recessed grid corners, registration chevrons and overspray edge grains.",
      "family": "track",
      "defaults": {},
      "defaultOpacity": 100,
      "defaultBlendMode": "normal",
      "defaultRange": 40,
      "defaultChannels": "MRC",
      "render_version": 2,
      "seed": 42,
      "surfaceIntent": "spec_driven",
      "legacy": false
    },
    {
      "id": "spov2_catch_fence_clips",
      "name": "Catch Fence Clips",
      "desc": "Catch Fence Clips assembles crossed fence strands, wrapped wire clips, clip crimp pockets, wire twist tails and galvanized contact nibs.",
      "family": "track",
      "defaults": {},
      "defaultOpacity": 100,
      "defaultBlendMode": "normal",
      "defaultRange": 40,
      "defaultChannels": "MRC",
      "render_version": 2,
      "seed": 42,
      "surfaceIntent": "spec_driven",
      "legacy": false
    },
    {
      "id": "spov2_aero_vortex_tabs",
      "name": "Aero Vortex Tabs",
      "desc": "Aero Vortex Tabs assembles paired vortex vanes, vane leading crests, mounting recesses, shear layer witness arcs and riveted vane feet.",
      "family": "track",
      "defaults": {},
      "defaultOpacity": 100,
      "defaultBlendMode": "normal",
      "defaultRange": 40,
      "defaultChannels": "MRC",
      "render_version": 2,
      "seed": 42,
      "surfaceIntent": "spec_driven",
      "legacy": false
    },
    {
      "id": "spov2_rivet_safety_wire",
      "name": "Rivet Safety Wire",
      "desc": "Rivet Safety Wire assembles rivet head discs, twisted safety wires, drilled lock holes, rivet annular lips and folded wire tails.",
      "family": "track",
      "defaults": {},
      "defaultOpacity": 100,
      "defaultBlendMode": "normal",
      "defaultRange": 40,
      "defaultChannels": "MRC",
      "render_version": 2,
      "seed": 42,
      "surfaceIntent": "spec_driven",
      "legacy": false
    },
    {
      "id": "spov2_gyroid_windows",
      "name": "Gyroid Windows",
      "desc": "Gyroid Windows assembles saddle surface lobes, gyroid neck crests, open saddle windows, junction shoulder ribs and etched saddle ticks.",
      "family": "experimental",
      "defaults": {},
      "defaultOpacity": 100,
      "defaultBlendMode": "normal",
      "defaultRange": 40,
      "defaultChannels": "MRC",
      "render_version": 2,
      "seed": 42,
      "surfaceIntent": "spec_driven",
      "legacy": false
    },
    {
      "id": "spov2_kagome_bridges",
      "name": "Kagome Bridges",
      "desc": "Kagome Bridges assembles trihexagonal ligaments, three way bond knots, recessed hex windows, bridge stress gussets and bonded corner tabs.",
      "family": "experimental",
      "defaults": {},
      "defaultOpacity": 100,
      "defaultBlendMode": "normal",
      "defaultRange": 40,
      "defaultChannels": "MRC",
      "render_version": 2,
      "seed": 42,
      "surfaceIntent": "spec_driven",
      "legacy": false
    },
    {
      "id": "spov2_voronoi_kites",
      "name": "Voronoi Kites",
      "desc": "Voronoi Kites assembles asymmetric kite faces, kite diagonal spines, interkite recesses, offset kite hinges and beveled tail chips.",
      "family": "experimental",
      "defaults": {},
      "defaultOpacity": 100,
      "defaultBlendMode": "normal",
      "defaultRange": 40,
      "defaultChannels": "MRC",
      "render_version": 2,
      "seed": 42,
      "surfaceIntent": "spec_driven",
      "legacy": false
    },
    {
      "id": "spov2_quasicrystal_fans",
      "name": "Quasicrystal Fans",
      "desc": "Quasicrystal Fans assembles five axis facet packets, quasiperiodic bond edges, deep interference nodes, fan crossing saddles and growth front islets.",
      "family": "experimental",
      "defaults": {},
      "defaultOpacity": 100,
      "defaultBlendMode": "normal",
      "defaultRange": 40,
      "defaultChannels": "MRC",
      "render_version": 2,
      "seed": 42,
      "surfaceIntent": "spec_driven",
      "legacy": false
    },
    {
      "id": "spov2_truchet_switchyard",
      "name": "Truchet Switchyard",
      "desc": "Truchet Switchyard assembles paired truchet tracks, track switch collars, recessed arc interstices, junction contact tabs and guideway index ticks.",
      "family": "experimental",
      "defaults": {},
      "defaultOpacity": 100,
      "defaultBlendMode": "normal",
      "defaultRange": 40,
      "defaultChannels": "MRC",
      "render_version": 2,
      "seed": 42,
      "surfaceIntent": "spec_driven",
      "legacy": false
    },
    {
      "id": "spov2_hilbert_relays",
      "name": "Hilbert Relays",
      "desc": "Hilbert Relays assembles space filling relay tracks, relay corner pads, insulating channel pockets, path terminal slots and bridge via collars.",
      "family": "experimental",
      "defaults": {},
      "defaultOpacity": 100,
      "defaultBlendMode": "normal",
      "defaultRange": 40,
      "defaultChannels": "MRC",
      "render_version": 2,
      "seed": 42,
      "surfaceIntent": "spec_driven",
      "legacy": false
    },
    {
      "id": "spov2_reaction_maze",
      "name": "Reaction Maze",
      "desc": "Reaction Maze assembles reaction front ribbons, branching front crests, depleted reaction pools, front collision nodes and nucleation seed pores.",
      "family": "experimental",
      "defaults": {},
      "defaultOpacity": 100,
      "defaultBlendMode": "normal",
      "defaultRange": 40,
      "defaultChannels": "MRC",
      "render_version": 2,
      "seed": 42,
      "surfaceIntent": "spec_driven",
      "legacy": false
    },
    {
      "id": "spov2_auxetic_hinges",
      "name": "Auxetic Hinges",
      "desc": "Auxetic Hinges assembles reentrant bowtie plates, rotating hinge necks, reentrant edge slots, shear relief eyelets and hinge corner bearing tabs.",
      "family": "experimental",
      "defaults": {},
      "defaultOpacity": 100,
      "defaultBlendMode": "normal",
      "defaultRange": 40,
      "defaultChannels": "MRC",
      "render_version": 2,
      "seed": 42,
      "surfaceIntent": "spec_driven",
      "legacy": false
    },
    {
      "id": "spov2_tensegrity_cells",
      "name": "Tensegrity Cells",
      "desc": "Tensegrity Cells assembles compression strut pairs, tension cable triangles, floating joint recesses, anchored strut collars and cable clamp tabs.",
      "family": "experimental",
      "defaults": {},
      "defaultOpacity": 100,
      "defaultBlendMode": "normal",
      "defaultRange": 40,
      "defaultChannels": "MRC",
      "render_version": 2,
      "seed": 42,
      "surfaceIntent": "spec_driven",
      "legacy": false
    },
    {
      "id": "spov2_fractal_seeds",
      "name": "Fractal Seeds",
      "desc": "Fractal Seeds assembles recursive triangle plates, three seed vertex nodes, central triangle voids, recursive edge notches and seed bridge witnesses.",
      "family": "experimental",
      "defaults": {},
      "defaultOpacity": 100,
      "defaultBlendMode": "normal",
      "defaultRange": 40,
      "defaultChannels": "MRC",
      "render_version": 2,
      "seed": 42,
      "surfaceIntent": "spec_driven",
      "legacy": false
    },
    {
      "id": "spov2_hyperbolic_scales",
      "name": "Hyperbolic Scales",
      "desc": "Hyperbolic Scales assembles saddle scale faces, conjugate hyperbola rims, scale waist recesses, overlap corner studs and split cusp tabs.",
      "family": "experimental",
      "defaults": {},
      "defaultOpacity": 100,
      "defaultBlendMode": "normal",
      "defaultRange": 40,
      "defaultChannels": "MRC",
      "render_version": 2,
      "seed": 42,
      "surfaceIntent": "spec_driven",
      "legacy": false
    }
  ]
};
