'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),crypto=require('node:crypto');
const root=path.resolve(__dirname,'..'), pin='_easy_claude_work/ai14h_w92_review/pinned/', integration='_easy_claude_work/ai14h_w108_candidate/';
const paths={
 pro:integration+'spb-pro-ai.js', design:integration+'spb-pro-design.js', edit:integration+'spb-pro-edit.js', materials:integration+'spb-ai-material-controls.js', guard:pin+'spb-ai-complete-instruction-guard.js', selfhelp:integration+'spb-self-help.js', receipt:integration+'spb-ai-receipt-explainer.js', operation:pin+'spb-ai-operation.js', lease:pin+'spb-ai-lease.js', intentGuard:integration+'spb-ai-instruction-intent-guard.js', oracle:integration+'fresh-oracle.json',supplement:'_easy_claude_work/ai14h_w104_review/normalization-supplement.json'
};
const src={}; for(const [k,p] of Object.entries(paths)) src[k]=fs.readFileSync(path.join(root,p),'utf8');
const sha=s=>crypto.createHash('sha256').update(s).digest('hex').toUpperCase();
const expected={pro:'56267FA3CCD5525DC83DFF1AD78EFAF8DB444A9EEBDD7B2E041AF48F1ABCC364',selfhelp:'D1A76C2A5B8616133F8226602D43245BFC7DCC2B99B6BBEDEA68AF0641A2D6BE',receipt:'3CB4CCE4513FDC1E70A54156A7FDC9F98CE35605FDB33ADE1F5C66F24F8542A9',intentGuard:'3267DC263CF85BCB34B55588997ACBA737F4A47E7BDDE490FACE4D9D6271FB60',design:'4648DE3231015497CC9FF816612A542097A1AD14038A7210753F6CDBFD88D832',edit:'7D063444021F8F4144B96130800BADFE62741CDEFC9104417F3E99AF65270767',materials:'30B18516A3F13DD7854F6EF36FDF5EB7A37985537E63C4C6405FEFA690C6BAEC',guard:'BA0AF1F9E217695ED733DDE81C8DEC1A735DD1F052E8C06B3098866D392A551C',operation:'47587A1A53A35CE7E58825BAC864BD75C2421D26C19791957F57BB199A7000C6',lease:'DE276372A763310EC051DB141FCB1D601E11DBF193843E2B21A405226F782134'};
for(const [k,h] of Object.entries(expected)) assert.equal(sha(src[k]),h,k+' pinned bytes');
function extract(source,name){const start=source.indexOf(`function ${name}(`);assert(start>=0,`function ${name} exists`);if(name==='selfHelpClaim'){const end=source.indexOf('function selfHelpResult(',start);assert(end>start);return source.slice(start,end).trim();}const brace=source.indexOf('{',start);let depth=0,q=null,line=false,block=false,esc=false;for(let i=brace;i<source.length;i++){const c=source[i],n=source[i+1];if(line){if(c==='\n')line=false;continue;}if(block){if(c==='*'&&n==='/'){block=false;i++;}continue;}if(q){if(esc){esc=false;continue;}if(c==='\\'){esc=true;continue;}if(c===q)q=null;continue;}if(c==='/'&&n==='/'){line=true;i++;continue;}if(c==='/'&&n==='*'){block=true;i++;continue;}if(c==='"'||c==="'"||c==='`'){q=c;continue;}if(c==='{')depth++;if(c==='}'&&--depth===0)return source.slice(start,i+1);}throw Error('unterminated '+name);}
function extractSend(source){const start=source.indexOf('function send(text, o)'),end=source.indexOf('function mergeMaskUndo(',start);assert(start>=0&&end>start);return source.slice(start,end).trim();}
function route(text,pro,intent,guardSrc=src.intentGuard,core=false,seededLog=[],sendOnly=false){
 const queued=[], env={palette:[{hex:'#111111',share_pct:42},{hex:'#00b8d4',share_pct:27},{hex:'#168a45',share_pct:10}],layers:[],zoneColours:[]};
 const fixtureZones=[{id:'roof-zone',name:'Roof solid green',base:'base::gloss',finish:'f_gloss',baseColorMode:'solid',baseColor:'#1f8a3b',baseColorStrength:1,baseStrength:1,regionMask:new Uint8Array(64),sourceLayers:['paint']}];
 const w={console,Promise,document:{body:{classList:{contains:()=>false}}},zones:fixtureZones,_psdLayers:[{id:'source',name:'Source image',img:{},visible:true},{id:'paint',name:'Car Paint',img:{},visible:true}],paintImageData:null,selectedZoneIndex:0,zoneSourceLayerIds:z=>z.sourceLayers||[],_spbLayerRev:0};w.window=w;w.SpbProCar={roles:()=>[],map:()=>null,missing:()=>[]};vm.createContext(w);for(const k of ['design','edit','materials','guard','selfhelp','receipt'])if(src[k])vm.runInContext(src[k],w,{filename:paths[k]});if(intent)vm.runInContext(guardSrc,w,{filename:paths.intentGuard});
 const D=w.SpbProDesign,E=w.SpbProEdit;
 const ctx={D,E,window:w,console,Promise,JSON,Object,Array,String,Number,Math,RegExp,Error,Uint8Array,Date,AI:{cached:()=>({configured:false})},_log:seededLog.slice(),_panel:null,_pendingCard:null,_busy:false,_progress:'',_progressTick:null,_skipParts:true,_absent:{},CAR:{missing:()=>[],layoutSig:()=>'',hasParts:()=>false},zones:fixtureZones,_editReg:{},_editRegPendingBefore:{},_editRegSig:'car-a',START_OVER_RE:/^\s*(?:start over|new design)\b/i,TEACH_RE:/^teach/i,QUESTION_RE:/\?\s*$/,CHECK_AGAIN_RE:/$a/,operationCurrent:t=>!!t&&t.ok===true,operationTicket:e=>e&&e._spbOperation||null,operationManager:()=>({sameDocument:t=>!!t&&t.ok===true&&!!t.document&&t.document.sourceGeneration===7}),operationRevision:()=>1,operationCanceled:()=>({cancelled:true}),operationRelease(){},operationPublish:(t,fn)=>fn(),operationTools:ts=>ts,operationRefreshDocument(){},elementRunCurrent:()=>true,elementPaintChangedResult:()=>({cancelled:true}),elemCurrentCard:()=>null,elementPaintSig:()=>'',elementRunIdentity:()=>null,elemReplyAction:()=>null,elemOwnsText:()=>false,rshotGrab(){},complaintChip:()=>false,complaintOf:()=>null,kitAsk:()=>false,supportClass:()=>null,supportSend:()=>false,offlineHowtoPeek:()=>null,editPlan:t=>E.plan(t,env),advisorOwns:()=>false,captureOriginal(){},intentSpecOnly:()=>false,editYieldsToStack:()=>false,editEnv:()=>env,advisorIntent:()=>null,offlineIdeas:()=>null,_offlineLast:null,_forcedIdeaCols:null,_reqText:'',_specOnlyReq:false,offlineCannot:()=>null,layerVisRequest:()=>null,NUM_FIX_RE:/$a/,NOT_ELEM_RE:/$a/,offlineLookAsk(){},offlineSpecAsk(){},offlinePartAsk:null,offlineElementAsk(){},offlineStartOver(){},offlineUndo(){},offlineHowto:()=>null,offlineScopeReply:()=>({offline:true,text:'Nothing was changed. Name one exact supported part.',queue:[]}),render(){},warm:()=>Promise.resolve(),markPartFollowupQueue(){},prepEnv:()=>Promise.resolve(env),resolveLook:()=>Promise.resolve(null),elementKinds:()=>[],exclTargets:()=>[],editOverlapNote:()=>'',explainPlan:p=>'test explanation',offlineHelp:(q,o)=>Promise.resolve({text:'guidance'}),partRegionKey:r=>JSON.stringify(r||{}),editKey:x=>x,editPlural:x=>x,currentPartOwnerVerifiedForRegion:()=>false,explicitCurrentPaintRequest:()=>false,unprovedCurrentPaintPartAdd:()=>false,intentGuardResult:null,finish(){},makeReport:()=>'',
 editOverlapKinds:()=>[],exclNotes:()=>[],_elemCache:null,_elemOk:{},_taughtNow:{},editReply:(text,chips,opts)=>({offline:true,text,queue:(opts&&opts.queue)||[],tools:(opts&&opts.tools)||[]}),offlineRefineAsk(){},selfHelpResult:x=>x,
 operationRefreshDocument(){},makeTools(){return [{name:'add_zone',handler(spec){queued.push({kind:'add',spec:JSON.parse(JSON.stringify(spec))});return {region_check:{share_pct:35}};}},{name:'edit_zone',handler(args){queued.push({kind:'edit',args:JSON.parse(JSON.stringify(args))});return {};}}];},queueEditZones(kind,spec,args,opts){queued.push({kind,spec,args,opts});return Promise.resolve({ok:true});},queueEdit(){queued.push({kind:'edit'});return Promise.resolve({ok:true});},scopedPartProofAt:()=>null,scopedPartProofMatches:()=>false,partOwnerCurrent:()=>false,carSig:()=>'car-a',scopedPartSourceNow:()=>null,operationDocument:()=>({ok:true}),operationAcquire:()=>({ok:true,collection:1}),operationResultCurrent:()=>true,operationRelease(){},_spbOperation:null};
 w.SpbAiLease={internal:()=>true};
 vm.createContext(ctx);const names=['partRegionKey','editKey','editPlural','hasPriorPartIdentity','currentPartZoneOwners','scopedPartProofCurrent','currentPartOwnerVerifiedForRegion','explicitCurrentPaintRequest','unprovedCurrentPaintPartAdd','relativeBodyScopePreflight','offlineRevert','selfHelpClaim','selfHelpResult','contextualHelpReply','offlineInstructionPreflight','offlineMaterialPlan','offlineMaterialAsk','offlinePartAsk','offlineCoveredPartAsk','offlineEditAsk','offlineAskCore','offlineAsk','queueEditZones'];
 if(pro.includes('function normalizeOfflineInstruction('))vm.runInContext(extract(pro,'normalizeOfflineInstruction'),ctx);else ctx.normalizeOfflineInstruction=x=>String(x||'');
 for(const n of names){try{vm.runInContext(extract(pro,n),ctx);}catch(e){if(n==='hasPriorPartIdentity'&&!pro.includes('function hasPriorPartIdentity('))continue;throw e;}}
 if(pro.includes('function send(text, o)'))vm.runInContext(extractSend(pro),ctx);
 return Promise.resolve(sendOnly?null:(core?ctx.offlineAskCore:ctx.offlineAsk)(text,{_spbOperation:{ok:true,collection:1},noAdvisor:true})).then(result=>({result,queued,ctx,D,E,window:w}));
}
(async()=>{
 const oracle=JSON.parse(src.oracle);assert.equal(oracle.case_count||oracle.caseCount||oracle.cases.length,18);const rows=[],issues=[];
 const helpIds=new Set(oracle.cases.filter(c=>c.id!=='valid-imperative-control').map(c=>c.id));
 for(const c of oracle.cases){for(const mode of ['offlineAsk','offlineAskCore']){const got=await route(c.input,src.pro,true,src.intentGuard,mode==='offlineAskCore');const text=String(got.result?.text||'');const row={id:c.id,route:mode,queue:got.queued.length,howto:!!got.result?.howto,selfHelp:got.result?.selfHelp||null,reply:text.slice(0,900)};rows.push(row);if(helpIds.has(c.id)&&got.queued.length!==0)issues.push(c.id+'/'+mode+': help request queued mutation');if(c.id==='valid-imperative-control'&&got.result?.howto)issues.push(c.id+'/'+mode+': imperative diverted to help');}}
 for(const c of oracle.cases){const sent=await route(c.input,src.pro,true,src.intentGuard,false,[],true);const finishes=[];let asks=0;sent.ctx.finish=(...args)=>finishes.push(args);sent.ctx.ask=()=>{asks++;return Promise.resolve({offline:true,text:'controlled ask'})};const direct=sent.ctx.contextualHelpReply(c.input);sent.ctx.send(c.input);await Promise.resolve();await Promise.resolve();const text=String(finishes[0]?.[0]?.text||'');rows.push({id:c.id,route:'send',queue:sent.queued.length,finishes:finishes.length,asks,contextual:!!direct,reply:text.slice(0,900)});if(helpIds.has(c.id)&&(sent.queued.length||finishes.length!==1||asks!==0))issues.push(c.id+'/send: read-only contextual help did not finish locally');if(c.id==='valid-imperative-control'&&(asks!==1||finishes.length!==1||sent.queued.length!==0))issues.push(c.id+'/send: imperative did not continue through controlled edit ask');}
 const byKey=Object.fromEntries(rows.map(r=>[r.id+'/'+r.route,r]));
 for(const routeName of ['offlineAsk','offlineAskCore']){
  for(const id of ['reopen-source-psd','keep-current-color-guidance','undo-with-later-manual-edit','simple-help-no-source','failed-save-help'])if(/^Nothing was changed\. (?:Name one exact supported part|This reads as a how-to)/.test(byKey[id+'/'+routeName]?.reply||''))issues.push(id+'/'+routeName+': contextual help was intercepted by generic preflight/scope response');
  if(/cannot find a layer called “every”/i.test(byKey['unsupported-format/'+routeName]?.reply||''))issues.push('unsupported-format/'+routeName+': universal format question was misread as a missing layer named every');
 }
 const normalizationSupplement=JSON.parse(src.supplement), normalizationRows=[];
 for(const c of normalizationSupplement.cases){
  const direct=await route(c.input,src.pro,true,src.intentGuard);const directText=String(direct.result?.text||'');
  normalizationRows.push({id:c.id,route:'offlineAsk',queue:direct.queued.length,reply:directText.slice(0,240)});
  if(direct.queued.length!==0||!/^Nothing was changed\./.test(directText))issues.push(c.id+'/offlineAsk: global no-execution preface was stripped before guard');
  const sent=await route(c.input,src.pro,true,src.intentGuard);const finishes=[];let asks=0;sent.ctx.finish=(...args)=>finishes.push(args);sent.ctx.ask=()=>{asks++;};
  await sent.ctx.send(c.input);const sendText=String(finishes[0]?.[0]?.text||finishes[0]?.[0]||'');
  normalizationRows.push({id:c.id,route:'send',queued:sent.queued.length,asks,finishes:finishes.length,reply:sendText.slice(0,240)});
  if(sent.queued.length!==0||asks!==0||finishes.length!==1||!/^Nothing was changed\./.test(sendText))issues.push(c.id+'/send: global no-execution preface was stripped before guard');
 }
 for(const routeName of ['offlineAsk','offlineAskCore']){
  const save=byKey['save-project-vs-source-psd/'+routeName]?.reply||'';if(!/does not bundle|doesn't bundle|records? (?:the )?original source|original PSD/i.test(save))issues.push('save-project distinction not clearly explained by '+routeName);
  const embedded=byKey['embedded-layers/'+routeName]?.reply||'';if(!/layer|flatten/i.test(embedded))issues.push('embedded-layer question received no useful save-format answer via '+routeName);
  const colour=byKey['current-authored-vs-source-paint/'+routeName]?.reply||'';if(!/source paint|original imported|authored|solid.color/i.test(colour))issues.push('source/current distinction missing via '+routeName);
  const keep=byKey['keep-current-color-guidance/'+routeName]?.reply||'';if(/Use source paint[^.]*preserv/i.test(keep))issues.push('current-color answer implies Source Paint preserves authored color via '+routeName);
  const fail=byKey['failed-edit-receipt/'+routeName]?.reply||'';if(/Done|successfully applied|the last change changed/i.test(fail))issues.push('failed operation answer asserts success via '+routeName);
  const draft=byKey['draft-not-applied/'+routeName]?.reply||'';if(/I (?:painted|changed|applied) the/i.test(draft))issues.push('unapplied draft presented as completed via '+routeName);
  const unsupported=byKey['unsupported-feature/'+routeName]?.reply||'';if(/Done|converted your PSD|layered SVG is ready/i.test(unsupported))issues.push('unsupported conversion claimed completed via '+routeName);
 }
 const receiptCases=[
  {id:'receipt-success-current',text:'What did the last successful paint change do?',kind:'applied',generation:7,expect:/last verified applied changes were: changed roof to blue/i},
  {id:'receipt-failure-current',text:'The last change failed. Did it actually change the paint?',kind:'failed',generation:7,expect:/last recorded attempt did not apply/i},
  {id:'receipt-stale-source',text:'What did the last change do? I just opened a different PSD.',kind:'applied',generation:6,expect:/do not have a current, verified apply receipt/i}
 ];
 for(const c of receiptCases){const note=c.kind==='failed'?['Could not apply — the target was unavailable.']:[];const lines=c.kind==='failed'?[]:['Changed roof to blue'];const seeded=[{role:'ai',request:'Make only the roof blue',lines,notes:note,_spbOperation:{ok:true,document:{sourceGeneration:c.generation},revision:1}}];for(const mode of ['offlineAsk','offlineAskCore','send']){const got=await route(c.text,src.pro,true,src.intentGuard,mode==='offlineAskCore',seeded,mode==='send');let text='';if(mode==='send'){const done=[];let asks=0;got.ctx.finish=(...args)=>done.push(args);got.ctx.ask=()=>{asks++;return Promise.resolve({})};got.ctx.send(c.text);await Promise.resolve();text=String(done[0]?.[0]?.text||'');if(done.length!==1||asks||got.queued.length)issues.push(c.id+'/'+mode+': receipt must finish locally with no queue');}else text=String(got.result?.text||'');if(!c.expect.test(text))issues.push(c.id+'/'+mode+': actual receipt explanation mismatch: '+text.slice(0,180));if(got.queued.length)issues.push(c.id+'/'+mode+': receipt question queued a paint change');rows.push({id:c.id,route:mode,queue:got.queued.length,reply:text.slice(0,300)});}}
 const clearcoatQuestion=await route('What does the clearcoat channel do?',src.pro,true,src.intentGuard);if(clearcoatQuestion.queued.length||!/B channel|clearcoat|gloss/i.test(clearcoatQuestion.result.text)||/click|select|set it|raise it/i.test(clearcoatQuestion.result.text))issues.push('clearcoat-explain: definition request got action instructions or queued work');rows.push({id:'clearcoat-explain',route:'offlineAsk',queue:clearcoatQuestion.queued.length,reply:clearcoatQuestion.result.text.slice(0,300)});
 const increaseHowto=await route('How do I increase clearcoat on the roof by 20 points?',src.pro,true,src.intentGuard);if(increaseHowto.queued.length||!increaseHowto.result.howto)issues.push('clearcoat-howto: passive question was not guidance');rows.push({id:'clearcoat-howto',route:'offlineAsk',queue:increaseHowto.queued.length,reply:String(increaseHowto.result.text).slice(0,300)});
 const result={work_item:'W108 independent contextual-help route candidate',status:issues.length?'REVIEW_GAPS':'PASS_PRIVATE_CANDIDATE',oracle:{path:paths.oracle,sha256:sha(src.oracle),cases:oracle.cases.length,frozenBeforeIntegration15Review:true},normalizationSupplement:{path:paths.supplement,sha256:sha(src.supplement),cases:normalizationSupplement.cases.length,rows:normalizationRows,readOnlyNormalizationPreserved:true},sources:{controller:pathHash(paths.pro),selfHelp:pathHash(paths.selfhelp),receiptExplainer:pathHash(paths.receipt),guard:pathHash(paths.intentGuard),projectPersistence:pathHash('js/features/spb-projects.js'),zoneConfig:pathHash('paint-booth-2-state-zones.js')},rows,issues,limitations:['Actual integration16 offlineAsk, offlineAskCore and send functions run with controlled app state, operation ticket and queue/DOM adapters. UI persistence and filesystem save results are not simulated as real app operations. Receipt attribution was tested with controlled current and stale operation-document generations; this is not a native receipt.','Source save facts were checked against buildProjectPayload/_serializeLayerState and loadSpbProject: the project stores a source path and embedded live Layer pixel data where a layer has pixels; it does not bundle the original source file. Save/Open also requires source verification.','No native, provider, file save/open, or paint application was performed. A question not matched to a precise help card may receive the generic safe scope reply; that is reported in the row text.'],counts:{utterances:oracle.cases.length,routedChecks:rows.length,receiptCases:receiptCases.length,normalizationSupplementCases:normalizationSupplement.cases.length,normalizationSupplementChecks:normalizationRows.length,reviewGaps:issues.length,providerCalls:0,nativeCalls:0,applyCalls:0}};fs.writeFileSync(path.join(root,'docs/handoff_reports/AI_HELPER_14H_CONTEXTUAL_HELP_W108_CANDIDATE_2026-10-04.json'),JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result,null,2));
})().catch(e=>{console.error(e.stack||e);process.exitCode=1;});
function pathHash(p){return sha(fs.readFileSync(path.join(root,p),'utf8'));}

