'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),crypto=require('node:crypto');
const root=path.resolve(__dirname,'..'),base='_easy_claude_work/ai14h_generation3_runtime9/js/';
const files={pro:'_easy_claude_work/ai14h_w119_contextual_conflicts/spb-pro-ai.js',selfhelp:base+'spb-self-help.js',receipt:base+'spb-ai-receipt-explainer.js',intent:base+'spb-ai-instruction-intent-guard.js'};
const source=Object.fromEntries(Object.entries(files).map(([k,p])=>[k,fs.readFileSync(path.join(root,p),'utf8')]));
const oraclePath='_easy_claude_work/ai14h_w117_review/fresh-oracle.json',oracleText=fs.readFileSync(path.join(root,oraclePath),'utf8'),oracle=JSON.parse(oracleText);
const sha=s=>crypto.createHash('sha256').update(s).digest('hex').toUpperCase();
assert.equal(sha(source.pro),'960693EBD11668FBE4966126825BB225833B7068BB9A0CD40EE22A09E564F640','immutable W116 successor pin');
assert.equal(sha(oracleText),'B823C0352FD73D21ED5DBC27914292C4B6D6B24D8C77A3F3022E1BB14B3CA79C','frozen W117 oracle pin');
function extract(s,n){const a=s.indexOf(`function ${n}(`);assert(a>=0,`${n} exists`);const b=s.indexOf('{',a);let d=0,q=null,ln=false,bl=false,esc=false;for(let i=b;i<s.length;i++){const c=s[i],x=s[i+1];if(ln){if(c==='\n')ln=false;continue;}if(bl){if(c==='*'&&x==='/'){bl=false;i++;}continue;}if(q){if(esc){esc=false;continue;}if(c==='\\'){esc=true;continue;}if(c===q)q=null;continue;}if(c==='/'&&x==='/'){ln=true;i++;continue;}if(c==='/'&&x==='*'){bl=true;i++;continue;}if(c==='"'||c==="'"||c==='`'){q=c;continue;}if(c==='{')d++;if(c==='}'&&--d===0)return s.slice(a,i+1);}throw Error(`unterminated ${n}`);}
function fixture(seedKind){
 const w={console,Promise,Date,Math,JSON,Object,Array,String,Number,RegExp,Error,document:{body:{classList:{contains:()=>false}},getElementById:()=>null},zones:[],_psdLayers:[],paintImageData:null,selectedZoneIndex:-1,zoneSourceLayerIds:()=>[],_spbLayerRev:0,SpbProCar:{roles:()=>[],map:()=>null,missing:()=>[]},SpbAI:{cached:()=>({configured:false})},SpbAiLease:{internal:()=>true}};w.window=w;vm.createContext(w);
 for(const k of ['selfhelp','receipt','intent'])vm.runInContext(source[k],w,{filename:files[k]});
 const item={role:'ai',lines:['Changed roof to blue'],notes:[],_spbOperation:{ok:true,document:{sourceGeneration:9},revision:1,collection:1}};if(seedKind==='undone')item.undone=true;
 Object.assign(w,{_log:seedKind==='none'?[]:[item],_busy:false,_ctl:null,_envMemo:null,operationCurrent:t=>!!t&&t.ok===true,operationTicket:v=>v&&v._spbOperation||null,operationManager:()=>({sameDocument:t=>!!t&&t.document&&t.document.sourceGeneration===9,ready(){},owns:()=>true}),operationRevision:()=>1,operationRelease(){},operationBind:v=>v,operationStart:()=>({ok:true,document:{sourceGeneration:9},revision:1,collection:1}),operationCanceled:()=>({cancelled:true,stale:true,queue:[]}),offlineAsk:()=>Promise.resolve({offline:true,queue:[],text:'offline route sentinel'})});
 for(const n of ['normalizeOfflineInstruction','selfHelpResult','unexecutedSuggestionReply','contextualHelpReply','offlineInstructionPreflight','ask'])vm.runInContext(extract(source.pro,n),w,{filename:files.pro});
 w.spbProAI={ask:w.ask};const calls=[];w.askForTicket=(text,opts)=>{calls.push({text,opts});return Promise.resolve({offline:true,text:'controlled downstream action handoff',queue:[]});};return{w,calls};
}
(async()=>{
 const rows=[],issues=[];
 for(const c of oracle.cases){const issueStart=issues.length,seed=c.id==='latest-change-receipt'?'applied':c.id==='last-request-status'?'undone':'none';const{w,calls}=fixture(seed);const result=await w.spbProAI.ask(c.utterance,{offline:true}),text=String(result&&result.text||''),queue=(result&&result.queue||[]).length;rows.push({id:c.id,howto:!!(result&&result.howto),queue,delegated:calls.length,topic:result&&result.selfHelp&&result.selfHelp.topic,text:text.slice(0,500)});
  if(c.family==='polite_action_control'){if(result&&result.howto||calls.length!==1||calls[0].text!==c.utterance)issues.push(`${c.id}: polite action was diverted or not handed downstream exactly once`);if(queue)issues.push(`${c.id}: test stub unexpectedly queued an edit`);continue;}
  if(!result||!result.howto||calls.length||queue)issues.push(`${c.id}: expected read-only answer with no downstream action/queue`);
  if(c.id.startsWith('coat-')){const channel=/Clearcoat/i.test(text)&&/(?:B \(blue\) channel|blue material channel)/i.test(text)&&/(?:not blue paint|not the paint color)/i.test(text);const locks=c.id==='coat-blue-channel-preserve'?/(?:roughness is the separate|roughness.*(?:stays|remain).*unchanged)/i.test(text):/Metalness and roughness are separate/i.test(text);if(!channel||!locks)issues.push(`${c.id}: did not distinguish blue material channel from paint or preserve requested channels`);}
  if(c.id.startsWith('logos-')){if(!/(?:cannot|does not|not .*reliab|not .*guarantee|inspect|check|confirm)/i.test(text)||/pick a look|tell me a colou?r|make the sponsors/i.test(text))issues.push(`${c.id}: no grounded recognition limit or unrelated sponsor action prompt`);}
  if(c.id==='latest-change-receipt'&&!/verified applied changes were: Changed roof to blue/i.test(text))issues.push(`${c.id}: did not report seeded current receipt accurately`);
  if(c.id==='last-request-status'&&!/undone|replaced|cannot determine|do not have a current/i.test(text))issues.push(`${c.id}: did not distinguish the seeded undone receipt from an applied edit`);
  if(c.id.startsWith('save-')){if(!/Save \/ Open|save .*project/i.test(text)||!/(?:pixel payload|pixel data|layer state)/i.test(text)||!/(?:original PSD|PSD bytes).*(?:not|does not)|(?:not|does not).*(?:original PSD|PSD bytes)/i.test(text))issues.push(`${c.id}: omitted save/reopen path or material source-file limitation`);}
  if(c.id.startsWith('numbers-')){if(!/(?:proposal|does not confirm|not confirmed|not confirmation|cannot confirm)/i.test(text)||!/(?:current paint|fresh|verify|check|confirm)/i.test(text))issues.push(`${c.id}: cross-paint memory was not clearly distinguished from current-paint confirmation`);}
  rows[rows.length-1].grade=issues.length>issueStart?'failure':c.family==='polite_action_control'?'action-intent-pass':'useful';
 }
 const report={work_item:'W117 independent W119 contextual-help recheck',status:issues.length?'REVIEW_GAPS':'PASS_PRIVATE_CANDIDATE',summary:{guidanceCases:10,guidancePass:rows.filter(r=>r.grade==='useful').length,guidanceFailures:rows.filter(r=>r.grade==='failure').length,actionIntentControls:rows.filter(r=>r.grade==='action-intent-pass').length},source:{candidate:files.pro,sha256:sha(source.pro),publicAskExport:/window\.spbProAI\s*=\s*\{[\s\S]*?\bask:\s*ask\s*[,}]/.test(source.pro),ancillaryModules:Object.fromEntries(['selfhelp','receipt','intent'].map(k=>[k,sha(source[k])]))},oracle:{path:oraclePath,sha256:sha(oracleText),cases:oracle.cases.length,frozenBeforeCandidateInspection:true},rows,issues,limits:['Extracted actual ask/contextualHelpReply/offlineInstructionPreflight bodies and actual self-help/receipt/intent modules; did not boot desktop IIFE. Provider, native, save, queue-apply and backend operations were not called. Action downstream was a controlled stub; these controls verify routing intent only, not successful edits.']};
 const out=path.join(root,'docs/handoff_reports/AI_HELPER_14H_CONTEXTUAL_ROUTING_W117_W119_RECHECK_2026-10-04.json');fs.writeFileSync(out,JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({status:report.status,cases:rows.length,issues,report:out},null,2));if(issues.length)process.exitCode=1;
})().catch(e=>{console.error(e);process.exitCode=1;});
