'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),crypto=require('node:crypto');
const root=path.resolve(__dirname,'..'), pin='_easy_claude_work/ai14h_w92_review/pinned/', integration='_easy_claude_work/ai14h_generation3_candidate/integration15/js/';
const paths={
 pro:integration+'spb-pro-ai.js', design:integration+'spb-pro-design.js', edit:integration+'spb-pro-edit.js', materials:pin+'spb-ai-material-controls.js', guard:pin+'spb-ai-complete-instruction-guard.js', selfhelp:integration+'spb-self-help.js', receipt:integration+'spb-ai-receipt-explainer.js', operation:pin+'spb-ai-operation.js', lease:pin+'spb-ai-lease.js', intentGuard:'_easy_claude_work/ai14h_w100_review/spb-ai-instruction-intent-guard.js', oracle:'_easy_claude_work/ai14h_w105_review/fresh-oracle.json',supplement:'_easy_claude_work/ai14h_w104_review/normalization-supplement.json'
};
const src={}; for(const [k,p] of Object.entries(paths)) src[k]=fs.readFileSync(path.join(root,p),'utf8');
const sha=s=>crypto.createHash('sha256').update(s).digest('hex').toUpperCase();
const expected={pro:'076E4A36E444157B8090346E110A06EEB1AF607F9C23775EB8FFA862486CECEA',selfhelp:'D1A76C2A5B8616133F8226602D43245BFC7DCC2B99B6BBEDEA68AF0641A2D6BE',receipt:'25ABA5EE85E9C9FB7EFE3603FCE22B140CCB09D2CBD09A9303AC6AB00530EAC3',intentGuard:'3267DC263CF85BCB34B55588997ACBA737F4A47E7BDDE490FACE4D9D6271FB60',design:'4648DE3231015497CC9FF816612A542097A1AD14038A7210753F6CDBFD88D832',edit:'7D063444021F8F4144B96130800BADFE62741CDEFC9104417F3E99AF65270767',materials:'A6F50C22C2D3A4F6F9707505D66C6C30B9D2CC0E04D78F00F0D103F38A49919D',guard:'BA0AF1F9E217695ED733DDE81C8DEC1A735DD1F052E8C06B3098866D392A551C',operation:'47587A1A53A35CE7E58825BAC864BD75C2421D26C19791957F57BB199A7000C6',lease:'DE276372A763310EC051DB141FCB1D601E11DBF193843E2B21A405226F782134'};
for(const [k,h] of Object.entries(expected)) assert.equal(sha(src[k]),h,k+' pinned bytes');
function extract(source,name){const start=source.indexOf(`function ${name}(`);assert(start>=0,`function ${name} exists`);if(name==='selfHelpClaim'){const end=source.indexOf('function selfHelpResult(',start);assert(end>start);return source.slice(start,end).trim();}const brace=source.indexOf('{',start);let depth=0,q=null,line=false,block=false,esc=false;for(let i=brace;i<source.length;i++){const c=source[i],n=source[i+1];if(line){if(c==='\n')line=false;continue;}if(block){if(c==='*'&&n==='/'){block=false;i++;}continue;}if(q){if(esc){esc=false;continue;}if(c==='\\'){esc=true;continue;}if(c===q)q=null;continue;}if(c==='/'&&n==='/'){line=true;i++;continue;}if(c==='/'&&n==='*'){block=true;i++;continue;}if(c==='"'||c==="'"||c==='`'){q=c;continue;}if(c==='{')depth++;if(c==='}'&&--depth===0)return source.slice(start,i+1);}throw Error('unterminated '+name);}
function extractSend(source){const start=source.indexOf('function send(text, o)'),end=source.indexOf('function mergeMaskUndo(',start);assert(start>=0&&end>start);return source.slice(start,end).trim();}
function route(text,pro,intent,guardSrc=src.intentGuard,core=false){
 const queued=[], env={palette:[{hex:'#111111',share_pct:42},{hex:'#00b8d4',share_pct:27},{hex:'#168a45',share_pct:10}],layers:[],zoneColours:[]};
 const fixtureZones=[{id:'roof-zone',name:'Roof solid green',base:'base::gloss',finish:'f_gloss',baseColorMode:'solid',baseColor:'#1f8a3b',baseColorStrength:1,baseStrength:1,regionMask:new Uint8Array(64),sourceLayers:['paint']}];
 const w={console,Promise,document:{body:{classList:{contains:()=>false}}},zones:fixtureZones,_psdLayers:[{id:'source',name:'Source image',img:{},visible:true},{id:'paint',name:'Car Paint',img:{},visible:true}],paintImageData:null,selectedZoneIndex:0,zoneSourceLayerIds:z=>z.sourceLayers||[],_spbLayerRev:0};w.window=w;w.SpbProCar={roles:()=>[],map:()=>null,missing:()=>[]};vm.createContext(w);for(const k of ['design','edit','materials','guard','selfhelp','receipt'])if(src[k])vm.runInContext(src[k],w,{filename:paths[k]});if(intent)vm.runInContext(guardSrc,w,{filename:paths.intentGuard});
 const D=w.SpbProDesign,E=w.SpbProEdit;
 const ctx={D,E,window:w,console,Promise,JSON,Object,Array,String,Number,Math,RegExp,Error,Uint8Array,Date,AI:{cached:()=>({configured:false})},_log:[],_panel:null,_pendingCard:null,_busy:false,_progress:'',_progressTick:null,_skipParts:true,_absent:{},CAR:{missing:()=>[],layoutSig:()=>'',hasParts:()=>false},zones:fixtureZones,_editReg:{},_editRegPendingBefore:{},_editRegSig:'car-a',START_OVER_RE:/^\s*(?:start over|new design)\b/i,TEACH_RE:/^teach/i,QUESTION_RE:/\?\s*$/,CHECK_AGAIN_RE:/$a/,operationCurrent:t=>!!t&&t.ok===true,operationCanceled:()=>({cancelled:true}),operationRelease(){},operationPublish:(t,fn)=>fn(),operationTools:ts=>ts,operationRefreshDocument(){},elementRunCurrent:()=>true,elementPaintChangedResult:()=>({cancelled:true}),elemCurrentCard:()=>null,elementPaintSig:()=>'',elementRunIdentity:()=>null,elemReplyAction:()=>null,elemOwnsText:()=>false,rshotGrab(){},complaintChip:()=>false,complaintOf:()=>null,kitAsk:()=>false,supportClass:()=>null,supportSend:()=>false,offlineHowtoPeek:()=>null,editPlan:t=>E.plan(t,env),advisorOwns:()=>false,captureOriginal(){},intentSpecOnly:()=>false,editYieldsToStack:()=>false,editEnv:()=>env,advisorIntent:()=>null,offlineIdeas:()=>null,_offlineLast:null,_forcedIdeaCols:null,_reqText:'',_specOnlyReq:false,offlineCannot:()=>null,layerVisRequest:()=>null,NUM_FIX_RE:/$a/,NOT_ELEM_RE:/$a/,offlineLookAsk(){},offlineSpecAsk(){},offlinePartAsk:null,offlineElementAsk(){},offlineStartOver(){},offlineUndo(){},offlineHowto:()=>null,offlineScopeReply:()=>({offline:true,text:'Nothing was changed. Name one exact supported part.',queue:[]}),render(){},warm:()=>Promise.resolve(),markPartFollowupQueue(){},prepEnv:()=>Promise.resolve(env),resolveLook:()=>Promise.resolve(null),elementKinds:()=>[],exclTargets:()=>[],editOverlapNote:()=>'',explainPlan:p=>'test explanation',offlineHelp:(q,o)=>Promise.resolve({text:'guidance'}),partRegionKey:r=>JSON.stringify(r||{}),editKey:x=>x,editPlural:x=>x,currentPartOwnerVerifiedForRegion:()=>false,explicitCurrentPaintRequest:()=>false,unprovedCurrentPaintPartAdd:()=>false,intentGuardResult:null,finish(){},makeReport:()=>'',
 editOverlapKinds:()=>[],exclNotes:()=>[],_elemCache:null,_elemOk:{},_taughtNow:{},editReply:(text,chips,opts)=>({offline:true,text,queue:(opts&&opts.queue)||[],tools:(opts&&opts.tools)||[]}),offlineRefineAsk(){},selfHelpResult:x=>x,
 operationRefreshDocument(){},makeTools(){return [{name:'add_zone',handler(spec){queued.push({kind:'add',spec:JSON.parse(JSON.stringify(spec))});return {region_check:{share_pct:35}};}},{name:'edit_zone',handler(args){queued.push({kind:'edit',args:JSON.parse(JSON.stringify(args))});return {};}}];},queueEditZones(kind,spec,args,opts){queued.push({kind,spec,args,opts});return Promise.resolve({ok:true});},queueEdit(){queued.push({kind:'edit'});return Promise.resolve({ok:true});},scopedPartProofAt:()=>null,scopedPartProofMatches:()=>false,partOwnerCurrent:()=>false,carSig:()=>'car-a',scopedPartSourceNow:()=>null,operationDocument:()=>({ok:true}),operationAcquire:()=>({ok:true,collection:1}),operationResultCurrent:()=>true,operationRelease(){},_spbOperation:null};
 vm.createContext(ctx);const names=['partRegionKey','editKey','editPlural','hasPriorPartIdentity','currentPartZoneOwners','scopedPartProofCurrent','currentPartOwnerVerifiedForRegion','explicitCurrentPaintRequest','unprovedCurrentPaintPartAdd','relativeBodyScopePreflight','offlineRevert','selfHelpClaim','selfHelpResult','offlineInstructionPreflight','offlineMaterialPlan','offlineMaterialAsk','offlinePartAsk','offlineCoveredPartAsk','offlineEditAsk','offlineAskCore','offlineAsk','queueEditZones'];
 if(pro.includes('function normalizeOfflineInstruction('))vm.runInContext(extract(pro,'normalizeOfflineInstruction'),ctx);else ctx.normalizeOfflineInstruction=x=>String(x||'');
 for(const n of names){try{vm.runInContext(extract(pro,n),ctx);}catch(e){if(n==='hasPriorPartIdentity'&&!pro.includes('function hasPriorPartIdentity('))continue;throw e;}}
 if(pro.includes('function send(text, o)'))vm.runInContext(extractSend(pro),ctx);
 return Promise.resolve((core?ctx.offlineAskCore:ctx.offlineAsk)(text,{_spbOperation:{ok:true,collection:1},noAdvisor:true})).then(result=>({result,queued,ctx,D,E,window:w}));
}
(async()=>{
 const oracle=JSON.parse(src.oracle);assert.equal(oracle.case_count||oracle.caseCount||oracle.cases.length,18);const rows=[],issues=[];
 const helpIds=new Set(oracle.cases.filter(c=>c.id!=='valid-imperative-control').map(c=>c.id));
 for(const c of oracle.cases){for(const mode of ['offlineAsk','offlineAskCore']){const got=await route(c.input,src.pro,true,src.intentGuard,mode==='offlineAskCore');const text=String(got.result?.text||'');const row={id:c.id,route:mode,queue:got.queued.length,howto:!!got.result?.howto,selfHelp:got.result?.selfHelp||null,reply:text.slice(0,440)};rows.push(row);if(helpIds.has(c.id)&&got.queued.length!==0)issues.push(c.id+'/'+mode+': help request queued mutation');if(c.id==='valid-imperative-control'&&got.result?.howto)issues.push(c.id+'/'+mode+': imperative diverted to help');}}
 const byKey=Object.fromEntries(rows.map(r=>[r.id+'/'+r.route,r]));
 for(const routeName of ['offlineAsk','offlineAskCore']){
  for(const id of ['reopen-source-psd','keep-current-color-guidance','undo-with-later-manual-edit','simple-help-no-source','failed-save-help'])if(/^Nothing was changed\. (?:Name one exact supported part|This reads as a how-to)/.test(byKey[id+'/'+routeName]?.reply||''))issues.push(id+'/'+routeName+': contextual help was intercepted by generic preflight/scope response');
  if(/cannot find a layer called “every”/i.test(byKey['unsupported-format/'+routeName]?.reply||''))issues.push('unsupported-format/'+routeName+': universal format question was misread as a missing layer named every');
 }
 const normalizationSupplement=JSON.parse(src.supplement), normalizationRows=[];
 for(const c of normalizationSupplement.cases){
  const direct=await route(c.input,src.pro,true,src.intentGuard);const directText=String(direct.result?.text||'');
  normalizationRows.push({id:c.id,route:'offlineAsk',queue:direct.queued.length,reply:directText.slice(0,240)});
  if(direct.queued.length!==0||!/^Nothing was changed\./.test(directText))issues.push(c.id+'/offlineAsk: global no-execution preface was stripped before guard');
  const sent=await route(c.input,src.pro,true,src.intentGuard);const finishes=[];let asks=0;sent.ctx.finish=(...args)=>finishes.push(args);sent.ctx.ask=()=>{asks++;};
  await sent.ctx.send(c.input);const sendText=String(finishes[0]?.[0]?.text||finishes[0]?.[0]||'');
  normalizationRows.push({id:c.id,route:'send',queued:sent.queued.length,asks,finishes:finishes.length,reply:sendText.slice(0,240)});
  if(sent.queued.length!==0||asks!==0||finishes.length!==1||!/^Nothing was changed\./.test(sendText))issues.push(c.id+'/send: global no-execution preface was stripped before guard');
 }
 for(const routeName of ['offlineAsk','offlineAskCore']){
  const save=byKey['save-project-vs-source-psd/'+routeName]?.reply||'';if(!/does not bundle|doesn't bundle|records? (?:the )?original source|original PSD/i.test(save))issues.push('save-project distinction not clearly explained by '+routeName);
  const embedded=byKey['embedded-layers/'+routeName]?.reply||'';if(!/layer|flatten/i.test(embedded))issues.push('embedded-layer question received no useful save-format answer via '+routeName);
  const colour=byKey['current-authored-vs-source-paint/'+routeName]?.reply||'';if(!/source paint|original imported|authored|solid.color/i.test(colour))issues.push('source/current distinction missing via '+routeName);
  const keep=byKey['keep-current-color-guidance/'+routeName]?.reply||'';if(/Use source paint[^.]*preserv/i.test(keep))issues.push('current-color answer implies Source Paint preserves authored color via '+routeName);
  const fail=byKey['failed-edit-receipt/'+routeName]?.reply||'';if(/Done|successfully applied|the last change changed/i.test(fail))issues.push('failed operation answer asserts success via '+routeName);
  const draft=byKey['draft-not-applied/'+routeName]?.reply||'';if(/I (?:painted|changed|applied) the/i.test(draft))issues.push('unapplied draft presented as completed via '+routeName);
  const unsupported=byKey['unsupported-feature/'+routeName]?.reply||'';if(/Done|converted your PSD|layered SVG is ready/i.test(unsupported))issues.push('unsupported conversion claimed completed via '+routeName);
 }
 const result={work_item:'W105 independent contextual-help acceptance',status:issues.length?'REVIEW_GAPS':'REVIEW_GAPS_WITH_W100_NORMALIZATION_FIX_VERIFIED',oracle:{path:paths.oracle,sha256:sha(src.oracle),cases:oracle.cases.length,frozenBeforeIntegration15Review:true},normalizationSupplement:{path:paths.supplement,sha256:sha(src.supplement),cases:normalizationSupplement.cases.length,rows:normalizationRows,readOnlyNormalizationPreserved:true},sources:{controller:pathHash(paths.pro),selfHelp:pathHash(paths.selfhelp),receiptExplainer:pathHash(paths.receipt),guard:pathHash(paths.intentGuard),projectPersistence:pathHash('js/features/spb-projects.js'),zoneConfig:pathHash('paint-booth-2-state-zones.js')},rows,issues,limitations:['Actual integration15 offlineAsk and offlineAskCore functions run with controlled app state, operation ticket and queue/DOM adapters. UI persistence and filesystem save results are not simulated as real app operations. The tested receipt questions do not seed a real success/failure receipt in the chat log, so receipt attribution is not claimed.','Source save facts were checked against buildProjectPayload/_serializeLayerState and loadSpbProject: the project stores a source path and embedded live Layer pixel data where a layer has pixels; it does not bundle the original source file. Save/Open also requires source verification.','No native, provider, file save/open, or paint application was performed. A question not matched to a precise help card may receive the generic safe scope reply; that is reported in the row text.'],counts:{utterances:oracle.cases.length,routedChecks:rows.length,normalizationSupplementCases:normalizationSupplement.cases.length,normalizationSupplementChecks:normalizationRows.length,reviewGaps:issues.length,providerCalls:0,nativeCalls:0,applyCalls:0}};fs.writeFileSync(path.join(root,'docs/handoff_reports/AI_HELPER_14H_CONTEXTUAL_HELP_W105_REVIEW_2026-10-04.json'),JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result,null,2));
})().catch(e=>{console.error(e.stack||e);process.exitCode=1;});
function pathHash(p){return sha(fs.readFileSync(path.join(root,p),'utf8'));}
