'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),crypto=require('node:crypto');
const digest=s=>crypto.createHash('sha256').update(s).digest('hex').toUpperCase();
const root=path.resolve(__dirname,'..'), oracle=JSON.parse(fs.readFileSync(path.join(root,'_easy_claude_work/ai14h_w74_review/fresh-oracle.json'),'utf8'));
const w66OracleBytes=fs.readFileSync(path.join(root,'_easy_claude_work/ai14h_w66_review/fresh-oracle.json'));
assert.equal(digest(w66OracleBytes),'B5635F27BA42F7EB3C47A5C3A79AFE87826931FC70216BBAEA6398A7193EB5EA','W66 frozen 12-case oracle remains unchanged');
assert.equal(JSON.parse(w66OracleBytes.toString('utf8')).cases.length,12,'retain W66 oracle cardinality');
const base='_easy_claude_work/ai14h_generation3_audit/frozen-runtime1/js/';
const frozenController='_easy_claude_work/ai14h_generation3_audit/frozen-runtime1/js/spb-pro-ai.js';
const files={controller:process.argv[2]||'_easy_claude_work/ai14h_w74_review/candidate/spb-pro-ai.js',material:base+'spb-ai-material-controls.js',helper:process.argv[3]||'_easy_claude_work/ai14h_w74_review/candidate/spb-self-help.js',knowledge:base+'spb-ai-knowledge.js'};
const src=Object.fromEntries(Object.entries(files).map(([k,p])=>[k,fs.readFileSync(path.join(root,p),'utf8')]));
const expected={controller:'51F9584E201C83F8527444CBE0DDBADDBB7BF829808BCB9B384C1B2B2518463D',helper:'A25FEBD091B6D13EE2B3AAF3713F21A2FA720C0F240A6B042CD6DEFD023CF783',material:'1A8CE44BCFF196F63404D42B0654833C660B387CC550835081E018D3B8B14F70'};
for(const k of Object.keys(expected)) if(!(process.argv[2] && k==='controller') && !(process.argv[3] && k==='helper')) assert.equal(digest(src[k]),expected[k],k+' frozen source pin');
assert.equal(digest(fs.readFileSync(path.join(root,frozenController),'utf8')),'3DA5C98B7202288979EFE0F53FE48818F31A6A5B5428BFB178CAEBA5C25E82D6','Runtime1 controller baseline remains unchanged');
assert.equal(digest(fs.readFileSync(path.join(root,'_easy_claude_work/ai14h_w53_candidate/candidate/paint-booth-3-canvas.js'),'utf8')),'159716B3150C785517BEC3A1CF1B00A7318121885E7640276B5FFAF14FC91D9A','W53 source readiness API remains pinned');
const w={console,fetch(){throw Error('provider fetch forbidden')},XMLHttpRequest:function(){throw Error('provider XHR forbidden')},Promise,Date,Math,JSON,Object,String,Number,RegExp,Array,Error,_spbLayerRev:2,zones:[{id:'roof-1',name:'Roof',base:'gloss'}],selectedZoneIndex:0,_psdLayers:[],paintImageData:{width:4,height:4},_source:{generation:2,committed:2,loading:false,path:'C:/paint/a.tga',fp:'bytes-A'},document:{body:{classList:{contains(){return false}}}}};w.window=w;
w.SPBSourceLoadTransaction={getGeneration:()=>w._source.generation,getCommittedGeneration:()=>w._source.committed,isLoading:()=>w._source.loading,isCommitted:()=>!w._source.loading&&w._source.committed===w._source.generation&&!!w._source.path&&!!w._source.fp,getCommittedPath:()=>w._source.path,getCommittedFingerprint:()=>w._source.fp};
vm.createContext(w);vm.runInContext(src.knowledge,w,{filename:files.knowledge});vm.runInContext(src.material,w,{filename:files.material});vm.runInContext(src.helper,w,{filename:files.helper});
function extract(name,next){const start=src.controller.indexOf('function '+name+'(');assert(start>=0,'missing controller '+name);const end=src.controller.indexOf('function '+next+'(',start+1);assert(end>start,'missing end marker '+next);return src.controller.slice(start,end).replace(/\s+$/,'')}
const selected={},dispatch=[];w.dispatchLog=dispatch;const normalizeCode=src.controller.includes('function normalizeOfflineInstruction(')?extract('normalizeOfflineInstruction','offlineInstructionPreflight'):'';const code=[normalizeCode,extract('selfHelpClaim','selfHelpResult'),extract('selfHelpResult','selfHelpSig'),extract('offlineMaterialPlan','offlineMaterialAsk'),extract('offlineHowto','lookEntry'),extract('offlineAskCore','mcpImages')].join('\n')+`\nthis.runAsk=offlineAskCore;this.claim=selfHelpClaim;this.debug=function(t){return {has:!!window.SpbSelfHelp,first:SH_FIRST_RE.test(t),cls:window.SpbSelfHelp.classify(t),adv:advisorIntent(t),edit:editPlan(t),c:selfHelpClaim(t)}};`;
const setup=`var window=globalThis,dispatch=window.dispatchLog,E={},K=window.SpbAIKnowledge,HOWTO_RE=/\\b(?:how|where|what|can i|steps|instructions|help|find|save|open|set up|setup|flatten|merge)\\b/i,D={offlinePartCoverage(){return null},refine(){return null},offlineIdeas(){return null},compoundPlan(){return null},lookRequest(){return null},offlineSpec(){return null},offlinePart(){return null},offlineElement(){return null},offlinePlan(){return null}},CAR=null,START_OVER_RE=/$a/,CHECK_AGAIN_RE=/$a/,NUM_FIX_RE=/\b(fix|check|improve|repair)\b[^.]{0,14}\bnumbers?\b|\bnumbers?\b[^.]{0,24}\b(readable|readability|legible|visible|stand out|hard to read|unreadable|contrast|disappear)\b|\bmake the numbers (pop|readable|visible|legible)\b/i,NOT_ELEM_RE=/$a/,SH_FIRST_RE=/^(?:how|what|where|which|can|tell me)/i,_offlineLast=null,_forcedIdeaCols=null,_advLast=null,_advRejected=[],_advDislikes=[],_reqText='',_specOnlyReq=false,_beforeImg=null,_busy=false,_progress='',_absent={},_skipParts=false,_log=[],_extra={},HIST=[],RECENT=[],_envMemo=null;
function offlineInstructionPreflight(){return null} function operationCurrent(){return window.SPBSourceLoadTransaction.isCommitted()} function operationCanceled(){return {cancelled:true}} function elementRunCurrent(){return true} function elementPaintChangedResult(){return {queue:[]}} function editPlan(t){if(/^make just the roof matte blue/i.test(t)){dispatch.push('edit');return {kind:'ops',exactPart:true,ops:[{target:{kind:'part'}}]}}return null} function advisorOwns(){return false} function captureOriginal(){} function intentSpecOnly(){return false} function offlineStartOver(){return {queue:[]}} function offlineUndo(){return {queue:[]}} function offlineRefineAsk(){return null} function offlineIdeasAsk(){return null} function offlineCannot(){return null} function layerVisRequest(){return null} function offlineLayerVisAsk(){return null} function offlineNumbersAsk(text){dispatch.push('numbers');return Promise.resolve({offline:true,text:'number readability route',queue:[],howto:true})} function offlineElemWrong(){return null} function editYieldsToStack(){return false} function offlineEditAsk(t,p){dispatch.push('edit');return Promise.resolve({offline:true,text:'edit route',queue:[],editPlan:p})} function offlineLookAsk(){return null} function offlineSpecAsk(){return null} function offlinePartAsk(){return null} function offlineElementAsk(){return null} function offlineScopeReply(){return {offline:true,text:'scope fallback',queue:[]}} function offlineMaterialAsk(t,p){dispatch.push('material');return Promise.resolve({offline:true,text:'material route',queue:[],parsed:p})} function operationPublish(ticket,fn){return fn()} function editEnv(){return {palette:[{hex:'#111111',name:'black',share_pct:50}],layers:[],zoneColours:[]}} function complaintOf(){return false} function supportClass(){return null} function advisorIntent(){return false} function offlineCanHandle(){return true} function buyerText(s){return s} function elemOwnsText(t){return NOT_ELEM_RE.test(t)} function selfHelpUnused(){}`;
vm.runInContext(setup+'\n'+code,w,{filename:'frozen-runtime1-offline-controller-slices.js'});
const rows=[];const semantic={
 'W74-01':{need:[/save|SPB Projects|Save \/ Open/i],forbid:[]},
 'W74-02':{need:[/flattened means|combined into one image/i],forbid:[/Actions|Flatten document/i]},
 'W74-03':{need:[/merge visible|combine visible layers/i,/Layers/i],forbid:[]},
 'W74-04':{need:[/clear ?coat|coat channel/i,/blue|B \/ COAT/i],forbid:[/PICK COLOR|solid color/i]},
 'W74-05':{need:[/clear ?coat|coat channel/i,/blue|B \/ COAT/i],forbid:[/wand|lasso/i]},
 'W74-06':{need:[/number layer|layer named Numbers/i,/LAYERS/i],forbid:[/recipe|body layer/i]},
 'W74-07':{need:[/readable|chrome|gloss|metal/i,/number/i],forbid:[]},
 'W74-08':{need:[/built-in helper|offline/i,/API key|no key/i],forbid:[/scope fallback|could not work out/i]},
 'W74-09':{need:[/provider|external assistant|AI settings/i,/key|setup|connect/i],forbid:[/tool options bar|magic wand/i]},
 'W74-12':{need:[/logo|image layer/i,/Move|position|drag/i],forbid:[]}
};
(async()=>{
 for(const c of oracle.cases){let result=await w.runAsk(c.request,{});const queue=result&&result.queue||[], text=String(result&&result.text||'');let ok=true, route=c.intent==='material-edit'?'material':c.intent==='design-edit'?'edit':result&&result.tools&&result.tools[0]==='manual'?'manual':result&&result.selfHelp?'self-help':'fallback';if(c.intent==='material-edit'){assert.ok(dispatch.includes('material'),c.id+' should route to material owner');assert.equal(queue.length,0,'terminal action stub intentionally prevents application');assert.equal(w.SPBSourceLoadTransaction.isCommitted(),true);}else if(c.intent==='design-edit'){assert.ok(dispatch.includes('edit'),c.id+' should route to edit owner');assert.equal(queue.length,0);}else {assert.equal(queue.length,0,c.id+' help request must not queue');const ex=semantic[c.id]||{need:[],forbid:[]};ok=!!(result&&result.howto&&ex.need.every(re=>re.test(text))&&!ex.forbid.some(re=>re.test(text)));}const cl=w.SpbSelfHelp.classify(c.request)||{};rows.push({id:c.id,intent:c.intent,pass:ok,route,helperClass:cl.w66||cl.w74||null,queue:queue.length,text:text.slice(0,220)});}
 const chatGuide=w.SpbSelfHelp.handle('How can I change only the clearcoat?',{paint:'flat',layers:[],zones:[],selected:-1,mode:'chat'});assert.match(chatGuide.text,/Full editor/i,'Chat Studio guidance needs the route to Pro controls');
 const pass=rows.filter(r=>r.pass!==false).length;console.log(JSON.stringify({status:pass===rows.length?'PASS':'FINDINGS',cases:rows.length,passed:pass,failed:rows.length-pass,dispatch,chatStudioClearcoatPrerequisite:true,sourceReady:w.SPBSourceLoadTransaction.isCommitted(),w66OracleCases:12,rows,providerCalls:0,controllerHash:digest(src.controller),baselineController:'3DA5C98B7202288979EFE0F53FE48818F31A6A5B5428BFB178CAEBA5C25E82D6',helperHash:digest(src.helper),materialHash:digest(src.material)},null,2));
})().catch(e=>{console.error(e.stack||e);process.exitCode=1});





