'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),crypto=require('node:crypto');
const root=path.resolve(__dirname,'..'), pin='_easy_claude_work/ai14h_w92_review/pinned/';
const paths={
 pro:pin+'spb-pro-ai.js', candidatePro:'_easy_claude_work/ai14h_w92_review/candidate/spb-pro-ai.js', w88Pro:pin+'spb-pro-ai-w88-candidate.js', integratedPro:pin+'spb-pro-ai-integration12.js', design:pin+'spb-pro-design.js', edit:pin+'spb-pro-edit.js', materials:pin+'spb-ai-material-controls.js', guard:pin+'spb-ai-complete-instruction-guard.js', selfhelp:pin+'spb-self-help.js', operation:pin+'spb-ai-operation.js', lease:pin+'spb-ai-lease.js', intentGuard:'_easy_claude_work/ai14h_w92_review/candidate/spb-ai-instruction-intent-guard.js', w88Guard:pin+'spb-ai-instruction-intent-guard.js', oracle:'_easy_claude_work/ai14h_w92_review/fresh_oracle.json', supplemental:'_easy_claude_work/ai14h_w92_review/supplemental_oracle.json'
};
const src={}; for(const [k,p] of Object.entries(paths)) src[k]=fs.readFileSync(path.join(root,p),'utf8');
const sha=s=>crypto.createHash('sha256').update(s).digest('hex').toUpperCase();
const expected={pro:'E28770330994FFC04364D0A48E88B98B69D25F9848E23D56CC1CEA07165DA713',integratedPro:'60AE271C62D697AB31B9F2EED47B841A6038755DB8F319507E38D03185EE3A21',design:'0533393FF5F2170236F60D4ED489C7AE52F98805E12B0764DA67A967F756F2E8',edit:'99703873013E198857D9ACEAA334821098E53DCAA9D55E14DBD1EC50E58604DE',materials:'A6F50C22C2D3A4F6F9707505D66C6C30B9D2CC0E04D78F00F0D103F38A49919D',guard:'BA0AF1F9E217695ED733DDE81C8DEC1A735DD1F052E8C06B3098866D392A551C',selfhelp:'A25FEBD091B6D13EE2B3AAF3713F21A2FA720C0F240A6B042CD6DEFD023CF783',operation:'47587A1A53A35CE7E58825BAC864BD75C2421D26C19791957F57BB199A7000C6',lease:'DE276372A763310EC051DB141FCB1D601E11DBF193843E2B21A405226F782134',candidatePro:'829EF29E481876DAA38585D601BC0D0FFA3BC825884F6EDEC180B671E75FBFC7'};
for(const [k,h] of Object.entries(expected)) assert.equal(sha(src[k]),h,k+' pinned bytes');
function extract(source,name){const start=source.indexOf(`function ${name}(`);assert(start>=0,`function ${name} exists`);if(name==='selfHelpClaim'){const end=source.indexOf('function selfHelpResult(',start);assert(end>start);return source.slice(start,end).trim();}const brace=source.indexOf('{',start);let depth=0,q=null,line=false,block=false,esc=false;for(let i=brace;i<source.length;i++){const c=source[i],n=source[i+1];if(line){if(c==='\n')line=false;continue;}if(block){if(c==='*'&&n==='/'){block=false;i++;}continue;}if(q){if(esc){esc=false;continue;}if(c==='\\'){esc=true;continue;}if(c===q)q=null;continue;}if(c==='/'&&n==='/'){line=true;i++;continue;}if(c==='/'&&n==='*'){block=true;i++;continue;}if(c==='"'||c==="'"||c==='`'){q=c;continue;}if(c==='{')depth++;if(c==='}'&&--depth===0)return source.slice(start,i+1);}throw Error('unterminated '+name);}
function extractSend(source){const start=source.indexOf('function send(text, o)'),end=source.indexOf('function mergeMaskUndo(',start);assert(start>=0&&end>start);return source.slice(start,end).trim();}
function route(text,pro,intent,guardSrc=src.intentGuard){
 const queued=[], env={palette:[{hex:'#111111',share_pct:42},{hex:'#00b8d4',share_pct:27},{hex:'#168a45',share_pct:10}],layers:[],zoneColours:[]};
 const w={console,Promise,document:{}};w.window=w;vm.createContext(w);for(const k of ['design','edit','materials','guard','selfhelp'])vm.runInContext(src[k],w,{filename:paths[k]});if(intent)vm.runInContext(guardSrc,w,{filename:guardSrc===src.w88Guard?'W88-guard':'W92-guard'});
 const D=w.SpbProDesign,E=w.SpbProEdit;
 const ctx={D,E,window:w,console,Promise,JSON,Object,Array,String,Number,Math,RegExp,Error,Uint8Array,Date,AI:{cached:()=>({configured:false})},_log:[],_panel:null,_pendingCard:null,_busy:false,_progress:'',_progressTick:null,_skipParts:true,_absent:{},CAR:{missing:()=>[],layoutSig:()=>'',hasParts:()=>false},zones:[],_editReg:{},_editRegPendingBefore:{},_editRegSig:'car-a',START_OVER_RE:/^\s*(?:start over|new design)\b/i,TEACH_RE:/^teach/i,QUESTION_RE:/\?\s*$/,CHECK_AGAIN_RE:/$a/,operationCurrent:t=>!!t&&t.ok===true,operationCanceled:()=>({cancelled:true}),operationRelease(){},operationPublish:(t,fn)=>fn(),operationTools:ts=>ts,operationRefreshDocument(){},elementRunCurrent:()=>true,elementPaintChangedResult:()=>({cancelled:true}),elemCurrentCard:()=>null,elementPaintSig:()=>'',elementRunIdentity:()=>null,elemReplyAction:()=>null,elemOwnsText:()=>false,rshotGrab(){},complaintChip:()=>false,complaintOf:()=>null,kitAsk:()=>false,supportClass:()=>null,supportSend:()=>false,offlineHowtoPeek:()=>null,editPlan:t=>E.plan(t,env),advisorOwns:()=>false,captureOriginal(){},intentSpecOnly:()=>false,editYieldsToStack:()=>false,editEnv:()=>env,advisorIntent:()=>null,offlineIdeas:()=>null,_offlineLast:null,_forcedIdeaCols:null,_reqText:'',_specOnlyReq:false,offlineCannot:()=>null,layerVisRequest:()=>null,NUM_FIX_RE:/$a/,NOT_ELEM_RE:/$a/,offlineLookAsk(){},offlineSpecAsk(){},offlinePartAsk:null,offlineElementAsk(){},offlineStartOver(){},offlineUndo(){},offlineHowto:()=>null,offlineScopeReply:()=>({offline:true,text:'Nothing was changed. Name one exact supported part.',queue:[]}),render(){},warm:()=>Promise.resolve(),markPartFollowupQueue(){},prepEnv:()=>Promise.resolve(env),resolveLook:()=>Promise.resolve(null),elementKinds:()=>[],exclTargets:()=>[],editOverlapNote:()=>'',explainPlan:p=>'test explanation',offlineHelp:(q,o)=>Promise.resolve({text:'guidance'}),partRegionKey:r=>JSON.stringify(r||{}),editKey:x=>x,editPlural:x=>x,currentPartOwnerVerifiedForRegion:()=>false,explicitCurrentPaintRequest:()=>false,unprovedCurrentPaintPartAdd:()=>false,intentGuardResult:null,finish(){},makeReport:()=>'',
 editOverlapKinds:()=>[],exclNotes:()=>[],_elemCache:null,_elemOk:{},_taughtNow:{},editReply:(text,chips,opts)=>({offline:true,text,queue:(opts&&opts.queue)||[],tools:(opts&&opts.tools)||[]}),offlineRefineAsk(){},selfHelpResult:x=>x,
 operationRefreshDocument(){},makeTools(){return [{name:'add_zone',handler(spec){queued.push({kind:'add',spec:JSON.parse(JSON.stringify(spec))});return {region_check:{share_pct:35}};}},{name:'edit_zone',handler(args){queued.push({kind:'edit',args:JSON.parse(JSON.stringify(args))});return {};}}];},queueEditZones(kind,spec,args,opts){queued.push({kind,spec,args,opts});return Promise.resolve({ok:true});},queueEdit(){queued.push({kind:'edit'});return Promise.resolve({ok:true});},scopedPartProofAt:()=>null,scopedPartProofMatches:()=>false,partOwnerCurrent:()=>false,carSig:()=>'car-a',scopedPartSourceNow:()=>null,operationDocument:()=>({ok:true}),operationAcquire:()=>({ok:true,collection:1}),operationResultCurrent:()=>true,operationRelease(){},_spbOperation:null};
 vm.createContext(ctx);const names=['partRegionKey','editKey','editPlural','hasPriorPartIdentity','currentPartOwnerVerifiedForRegion','explicitCurrentPaintRequest','unprovedCurrentPaintPartAdd','selfHelpClaim','offlineInstructionPreflight','offlineMaterialPlan','offlineMaterialAsk','offlinePartAsk','offlineCoveredPartAsk','offlineEditAsk','offlineAskCore','offlineAsk','queueEditZones'];
 if(pro.includes('function normalizeOfflineInstruction('))vm.runInContext(extract(pro,'normalizeOfflineInstruction'),ctx);else ctx.normalizeOfflineInstruction=x=>String(x||'');
 for(const n of names){try{vm.runInContext(extract(pro,n),ctx);}catch(e){if(n==='hasPriorPartIdentity'&&!pro.includes('function hasPriorPartIdentity('))continue;throw e;}}
 if(pro.includes('function send(text, o)'))vm.runInContext(extractSend(pro),ctx);
 return Promise.resolve(ctx.offlineAsk(text,{_spbOperation:{ok:true,collection:1},noAdvisor:true})).then(result=>({result,queued,ctx,D,E}));
}
(async()=>{
 const oracle=JSON.parse(src.oracle);assert.equal(oracle.cases.length,15);const rows=[];
 for(const c of oracle.cases){const base=await route(c.text,src.pro,false),got=await route(c.text,src.w88Pro,true,src.w88Guard);rows.push({id:c.id,expected:c.expected,baseQueue:base.queued.length,w88Queue:got.queued.length,region:got.queued[0]?.spec?.region||null,reply:String(got.result?.text||'').slice(0,200)});}
 const integratedRows=[];for(const c of oracle.cases){const got=await route(c.text,src.integratedPro,true);integratedRows.push({id:c.id,queue:got.queued.length,region:got.queued[0]?.spec?.region||null,reply:String(got.result?.text||'').slice(0,160)});}
 const supplement=JSON.parse(src.supplemental);assert.equal(supplement.cases.length,12);const repairedRows=[];for(const c of supplement.cases){const got=await route(c.text,src.candidatePro,true);repairedRows.push({id:c.id,expected:c.expected,queue:got.queued.length,region:got.queued[0]?.spec?.region||null,reply:String(got.result?.text||'').slice(0,180)});}
 const byId=Object.fromEntries(rows.map(x=>[x.id,x])),issues=[];
 const baselineDefects=rows.filter(x=>((['quote-exact-roof','hypothetical-if','howto-question','quoted-paraphrase','apply-wrapper-not-imperative','quoted-conflict','passive-finish-mention','passive-current-color','instruction-analysis-not-action'].includes(x.id)&&x.w88Queue!==0)||(['explicit-imperative','polite-direct','apply-wrapper','imperative-with-passive-preface'].includes(x.id)&&(x.w88Queue!==1||JSON.stringify(x.region)!==JSON.stringify({part:'roof'})))||(['targetless-preserve-conflict','compound-preserve-targetless'].includes(x.id)&&x.w88Queue!==0)));
 const intById=Object.fromEntries(integratedRows.map(x=>[x.id,x]));for(const id of ['quote-exact-roof','hypothetical-if','howto-question','quoted-paraphrase','apply-wrapper-not-imperative','quoted-conflict','passive-finish-mention','passive-current-color','instruction-analysis-not-action'])if(intById[id].queue!==0)issues.push('integration12+W92 guard '+id+': expected zero queue, got '+intById[id].queue);for(const id of ['explicit-imperative','polite-direct','apply-wrapper','imperative-with-passive-preface'])if(intById[id].queue!==1||JSON.stringify(intById[id].region)!==JSON.stringify({part:'roof'}))issues.push('integration12+W92 guard '+id+': expected one roof action, got '+JSON.stringify(intById[id]));for(const id of ['targetless-preserve-conflict','compound-preserve-targetless'])if(intById[id].queue!==0)issues.push('integration12+W92 guard '+id+': expected zero queue, got '+intById[id].queue);
 const suppById=Object.fromEntries(repairedRows.map(x=>[x.id,x]));for(const id of ['reported-note-question','customer-paraphrase-question','apply-how-question','apply-if-hypothetical','passive-only-no-command','quoted-imperative-control','unwrapped-howto-control','targetless-keep-paint-conflict'])if(suppById[id].queue!==0)issues.push('repaired '+id+': expected zero queue, got '+suppById[id].queue);for(const [id,part] of [['passive-before-imperative','roof'],['passive-before-polite-direct','trunk'],['imperative-stays-direct','spoiler'],['apply-direct-control','front bumper']])if(suppById[id].queue!==1||suppById[id].region?.part!==part)issues.push('repaired '+id+': expected one '+part+' action, got '+JSON.stringify(suppById[id]));
 const sends=[];for(const id of ['howto-question','explicit-imperative','apply-wrapper']){const c=oracle.cases.find(x=>x.id===id),p=await route(c.text,src.candidatePro,true);let finishes=[],asks=0;p.ctx._busy=false;p.ctx.finish=(r,t,k)=>finishes.push({text:String(r?.text||''),input:t,kind:k});p.ctx.ask=()=>{asks++;return Promise.resolve({queue:[]});};p.ctx.send(c.text);sends.push({id,finishes:finishes.length,asks,finishText:finishes[0]?.text||''});if(id==='howto-question'&&(asks!==0||finishes.length!==1))issues.push('typed send '+id+': expected one guidance finish and no ask');if(id!=='howto-question'&&asks!==1)issues.push('typed send '+id+': expected ask dispatch, got '+asks);}
 const summary={status:issues.length?'REJECT':'PASS',freshCases:oracle.cases.length,supplementalCases:supplement.cases.length,baselineW88DefectCount:baselineDefects.length,rows,integration12:integratedRows,repaired:repairedRows,sends,issues,sourceHashes:Object.fromEntries(Object.entries(src).filter(([k])=>k!=='oracle'&&k!=='supplemental').map(([k,v])=>[k,sha(v)])),queuedMeansCompiledOnly:true,applyCalls:0,providerCalls:0,nativeCalls:0}; console.log(JSON.stringify(summary,null,2)); assert.equal(issues.length,0,issues.join('; '));
})().catch(e=>{console.error(e.stack||e);process.exitCode=1;});
