'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),crypto=require('node:crypto');
const root=path.resolve(__dirname,'..'), pin='_easy_claude_work/ai14h_w92_review/pinned/', integration='_easy_claude_work/ai14h_generation3_candidate/integration14/js/';
const paths={
 pro:integration+'spb-pro-ai.js', design:pin+'spb-pro-design.js', edit:pin+'spb-pro-edit.js', materials:pin+'spb-ai-material-controls.js', guard:pin+'spb-ai-complete-instruction-guard.js', selfhelp:pin+'spb-self-help.js', operation:pin+'spb-ai-operation.js', lease:pin+'spb-ai-lease.js', intentGuard:'_easy_claude_work/ai14h_w100_review/spb-ai-instruction-intent-guard.js', intentGuardBase:integration+'spb-ai-instruction-intent-guard.js', oracle:'_easy_claude_work/ai14h_w100_review/fresh-oracle.json'
};
const src={}; for(const [k,p] of Object.entries(paths)) src[k]=fs.readFileSync(path.join(root,p),'utf8');
const sha=s=>crypto.createHash('sha256').update(s).digest('hex').toUpperCase();
const expected={pro:'FF90F9EB557FDE7D5011C5621431BE581A9E900EE143AD02521919165D968E0F',intentGuardBase:'89E0D9E473C13309011D7318A81037C0C286D399B854938A37EDC14DAEDEFC83',design:'0533393FF5F2170236F60D4ED489C7AE52F98805E12B0764DA67A967F756F2E8',edit:'99703873013E198857D9ACEAA334821098E53DCAA9D55E14DBD1EC50E58604DE',materials:'A6F50C22C2D3A4F6F9707505D66C6C30B9D2CC0E04D78F00F0D103F38A49919D',guard:'BA0AF1F9E217695ED733DDE81C8DEC1A735DD1F052E8C06B3098866D392A551C',selfhelp:'A25FEBD091B6D13EE2B3AAF3713F21A2FA720C0F240A6B042CD6DEFD023CF783',operation:'47587A1A53A35CE7E58825BAC864BD75C2421D26C19791957F57BB199A7000C6',lease:'DE276372A763310EC051DB141FCB1D601E11DBF193843E2B21A405226F782134'};
for(const [k,h] of Object.entries(expected)) assert.equal(sha(src[k]),h,k+' pinned bytes');
function extract(source,name){const start=source.indexOf(`function ${name}(`);assert(start>=0,`function ${name} exists`);if(name==='selfHelpClaim'){const end=source.indexOf('function selfHelpResult(',start);assert(end>start);return source.slice(start,end).trim();}const brace=source.indexOf('{',start);let depth=0,q=null,line=false,block=false,esc=false;for(let i=brace;i<source.length;i++){const c=source[i],n=source[i+1];if(line){if(c==='\n')line=false;continue;}if(block){if(c==='*'&&n==='/'){block=false;i++;}continue;}if(q){if(esc){esc=false;continue;}if(c==='\\'){esc=true;continue;}if(c===q)q=null;continue;}if(c==='/'&&n==='/'){line=true;i++;continue;}if(c==='/'&&n==='*'){block=true;i++;continue;}if(c==='"'||c==="'"||c==='`'){q=c;continue;}if(c==='{')depth++;if(c==='}'&&--depth===0)return source.slice(start,i+1);}throw Error('unterminated '+name);}
function extractSend(source){const start=source.indexOf('function send(text, o)'),end=source.indexOf('function mergeMaskUndo(',start);assert(start>=0&&end>start);return source.slice(start,end).trim();}
function route(text,pro,intent,guardSrc=src.intentGuard){
 const queued=[], env={palette:[{hex:'#111111',share_pct:42},{hex:'#00b8d4',share_pct:27},{hex:'#168a45',share_pct:10}],layers:[],zoneColours:[]};
 const w={console,Promise,document:{}};w.window=w;vm.createContext(w);for(const k of ['design','edit','materials','guard','selfhelp'])vm.runInContext(src[k],w,{filename:paths[k]});if(intent)vm.runInContext(guardSrc,w,{filename:guardSrc===src.w88Guard?'W88-guard':'W92-guard'});
 const D=w.SpbProDesign,E=w.SpbProEdit;
 const ctx={D,E,window:w,console,Promise,JSON,Object,Array,String,Number,Math,RegExp,Error,Uint8Array,Date,AI:{cached:()=>({configured:false})},_log:[],_panel:null,_pendingCard:null,_busy:false,_progress:'',_progressTick:null,_skipParts:true,_absent:{},CAR:{missing:()=>[],layoutSig:()=>'',hasParts:()=>false},zones:[],_editReg:{},_editRegPendingBefore:{},_editRegSig:'car-a',START_OVER_RE:/^\s*(?:start over|new design)\b/i,TEACH_RE:/^teach/i,QUESTION_RE:/\?\s*$/,CHECK_AGAIN_RE:/$a/,operationCurrent:t=>!!t&&t.ok===true,operationCanceled:()=>({cancelled:true}),operationRelease(){},operationPublish:(t,fn)=>fn(),operationTools:ts=>ts,operationRefreshDocument(){},elementRunCurrent:()=>true,elementPaintChangedResult:()=>({cancelled:true}),elemCurrentCard:()=>null,elementPaintSig:()=>'',elementRunIdentity:()=>null,elemReplyAction:()=>null,elemOwnsText:()=>false,rshotGrab(){},complaintChip:()=>false,complaintOf:()=>null,kitAsk:()=>false,supportClass:()=>null,supportSend:()=>false,offlineHowtoPeek:()=>null,editPlan:t=>E.plan(t,env),advisorOwns:()=>false,captureOriginal(){},intentSpecOnly:()=>false,editYieldsToStack:()=>false,editEnv:()=>env,advisorIntent:()=>null,offlineIdeas:()=>null,_offlineLast:null,_forcedIdeaCols:null,_reqText:'',_specOnlyReq:false,offlineCannot:()=>null,layerVisRequest:()=>null,NUM_FIX_RE:/$a/,NOT_ELEM_RE:/$a/,offlineLookAsk(){},offlineSpecAsk(){},offlinePartAsk:null,offlineElementAsk(){},offlineStartOver(){},offlineUndo(){},offlineHowto:()=>null,offlineScopeReply:()=>({offline:true,text:'Nothing was changed. Name one exact supported part.',queue:[]}),render(){},warm:()=>Promise.resolve(),markPartFollowupQueue(){},prepEnv:()=>Promise.resolve(env),resolveLook:()=>Promise.resolve(null),elementKinds:()=>[],exclTargets:()=>[],editOverlapNote:()=>'',explainPlan:p=>'test explanation',offlineHelp:(q,o)=>Promise.resolve({text:'guidance'}),partRegionKey:r=>JSON.stringify(r||{}),editKey:x=>x,editPlural:x=>x,currentPartOwnerVerifiedForRegion:()=>false,explicitCurrentPaintRequest:()=>false,unprovedCurrentPaintPartAdd:()=>false,intentGuardResult:null,finish(){},makeReport:()=>'',
 editOverlapKinds:()=>[],exclNotes:()=>[],_elemCache:null,_elemOk:{},_taughtNow:{},editReply:(text,chips,opts)=>({offline:true,text,queue:(opts&&opts.queue)||[],tools:(opts&&opts.tools)||[]}),offlineRefineAsk(){},selfHelpResult:x=>x,
 operationRefreshDocument(){},makeTools(){return [{name:'add_zone',handler(spec){queued.push({kind:'add',spec:JSON.parse(JSON.stringify(spec))});return {region_check:{share_pct:35}};}},{name:'edit_zone',handler(args){queued.push({kind:'edit',args:JSON.parse(JSON.stringify(args))});return {};}}];},queueEditZones(kind,spec,args,opts){queued.push({kind,spec,args,opts});return Promise.resolve({ok:true});},queueEdit(){queued.push({kind:'edit'});return Promise.resolve({ok:true});},scopedPartProofAt:()=>null,scopedPartProofMatches:()=>false,partOwnerCurrent:()=>false,carSig:()=>'car-a',scopedPartSourceNow:()=>null,operationDocument:()=>({ok:true}),operationAcquire:()=>({ok:true,collection:1}),operationResultCurrent:()=>true,operationRelease(){},_spbOperation:null};
 vm.createContext(ctx);const names=['partRegionKey','editKey','editPlural','hasPriorPartIdentity','currentPartZoneOwners','scopedPartProofCurrent','currentPartOwnerVerifiedForRegion','explicitCurrentPaintRequest','unprovedCurrentPaintPartAdd','relativeBodyScopePreflight','selfHelpClaim','offlineInstructionPreflight','offlineMaterialPlan','offlineMaterialAsk','offlinePartAsk','offlineCoveredPartAsk','offlineEditAsk','offlineAskCore','offlineAsk','queueEditZones'];
 if(pro.includes('function normalizeOfflineInstruction('))vm.runInContext(extract(pro,'normalizeOfflineInstruction'),ctx);else ctx.normalizeOfflineInstruction=x=>String(x||'');
 for(const n of names){try{vm.runInContext(extract(pro,n),ctx);}catch(e){if(n==='hasPriorPartIdentity'&&!pro.includes('function hasPriorPartIdentity('))continue;throw e;}}
 if(pro.includes('function send(text, o)'))vm.runInContext(extractSend(pro),ctx);
 return Promise.resolve(ctx.offlineAsk(text,{_spbOperation:{ok:true,collection:1},noAdvisor:true})).then(result=>({result,queued,ctx,D,E}));
}
(async()=>{
 const oracle=JSON.parse(src.oracle);assert.equal(oracle.case_count||oracle.caseCount||oracle.cases.length,9);const rows=[],issues=[];
 for(const c of oracle.cases){const got=await route(c.input,src.pro,true);const row={id:c.id,expected:c.expect,queue:got.queued.length,region:got.queued[0]?.spec?.region||null,reply:String(got.result?.text||'').slice(0,220)};rows.push(row);if(/zero queue|no edit|read-only|explanation only/i.test(c.expect)&&got.queued.length!==0)issues.push(c.id+': expected no queued mutation');if(/eligible|remains eligible|authorized actual edit/i.test(c.expect)&&got.queued.length!==1&&c.id!=='valid-scoped-command-with-constraint')issues.push(c.id+': expected one eligible edit, got '+got.queued.length);if(/no-apply|no-execute|hypothetical|read-only|quoted|paraphrase/i.test(c.id)&&!/^Nothing was changed\./.test(row.reply))issues.push(c.id+': missing truthful read-only response');if(c.id==='valid-scoped-command-with-constraint'&&got.queued.length===0&&!/clarif|cannot yet guarantee/i.test(row.reply))issues.push(c.id+': zero queue must explain unresolved hood preservation constraint');}
 const sendRows=[];for(const id of ['explain-hypothetical-no-apply','negative-after-apply-wrapper','valid-imperative']){const c=oracle.cases.find(x=>x.id===id),p=await route(c.input,src.pro,true);let finishes=[],asks=0;p.ctx._busy=false;p.ctx.finish=(r,t,k)=>finishes.push({text:String(r?.text||''),input:t,kind:k});p.ctx.ask=()=>{asks++;return Promise.resolve({queue:[]});};p.ctx.send(c.input);sendRows.push({id,finishes:finishes.length,asks,finishText:finishes[0]?.text||''});if(id!=='valid-imperative'&&(asks!==0||finishes.length!==1))issues.push('typed SEND '+id+' did not return one read-only answer before ask');if(id==='valid-imperative'&&asks!==1)issues.push('typed SEND imperative must continue to ask dispatch');}
 const wrapperText='Apply this request: make only the roof blue.',wrapper=await route(wrapperText,src.pro,true);let wrapperFinishes=[],wrapperAsks=0;wrapper.ctx._busy=false;wrapper.ctx.finish=(r,t,k)=>wrapperFinishes.push({text:String(r?.text||''),kind:k});wrapper.ctx.ask=()=>{wrapperAsks++;return Promise.resolve({queue:[]});};wrapper.ctx.send(wrapperText);sendRows.push({id:'authorized-apply-wrapper-control',queue:wrapper.queued.length,region:wrapper.queued[0]?.spec?.region||null,finishes:wrapperFinishes.length,asks:wrapperAsks});if(wrapper.queued.length!==1||wrapper.queued[0]?.spec?.region?.part!=='roof'||wrapperAsks!==1)issues.push('explicit apply wrapper should remain eligible');
 const result={work_item:'W100 private no-execution instruction guard review/repair',status:issues.length?'FAIL':'PASS_WITH_LIMITS',oracle:{path:paths.oracle,sha256:sha(src.oracle),cases:oracle.cases.length,frozenBeforeGuardInspection:true},sources:{controller:pathHash(paths.pro),guardBase:pathHash(paths.intentGuardBase),guardCandidate:pathHash(paths.intentGuard)},rows,typedSend:sendRows,issues,limitations:['The direct command with an added hood-preservation constraint receives a safe clarification from existing integration14 scope checks rather than a queued roof edit. The new intent guard does not classify it as read-only, but this route does not meet the oracle’s eligible-edit expectation; this separate scope behavior was left unchanged.','Tests use actual integration14 controller offlineAsk and SEND functions with deterministic planner/queue adapters; they do not claim native paint application.'],counts:{cases:rows.length,guardAndNoMutationChecksPassed:rows.length-issues.length,failed:issues.length,providerCalls:0,nativeCalls:0,applyCalls:0}};fs.writeFileSync(path.join(root,'docs/handoff_reports/AI_HELPER_14H_NO_EXECUTION_INTENT_W100_CANDIDATE_2026-10-04.json'),JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result,null,2));assert.equal(issues.length,0,issues.join('; '));
})().catch(e=>{console.error(e.stack||e);process.exitCode=1;});
function pathHash(p){return sha(fs.readFileSync(path.join(root,p),'utf8'));}
