'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),crypto=require('node:crypto');
const root=path.resolve(__dirname,'..');
const baselinePath=path.join(root,'_easy_claude_work/ai14h_w62_candidate/js/spb-pro-ai.js');
const useBaseline=process.env.W67_BASELINE==='1';
const proPath=useBaseline?baselinePath:path.join(root,'_easy_claude_work/ai14h_w67_candidate/js/spb-pro-ai.js');
const pro=fs.readFileSync(proPath,'utf8'); const proHash=crypto.createHash('sha256').update(pro).digest('hex').toUpperCase();
assert.equal(crypto.createHash('sha256').update(fs.readFileSync(baselinePath)).digest('hex').toUpperCase(),'3A193C10175F49841C398DD83D915061C1F25BBFCB4650F56A90588B2821FC17','W67 pinned W62 baseline remains unchanged');
assert.equal(proHash,useBaseline?'3A193C10175F49841C398DD83D915061C1F25BBFCB4650F56A90588B2821FC17':'136B437D194F389DF79EBC629EC931D6553D5DFBCC7F161531CC9F7B5954F779',useBaseline?'W67 baseline replay':'W67 isolated candidate');
const opPath=path.join(root,'js/spb-ai-operation.js'), leasePath=path.join(root,'js/spb-ai-lease.js'), sourceApiPath=path.join(root,'_easy_claude_work/ai14h_w53_candidate/candidate/paint-booth-3-canvas.js');
const sourceApi=fs.readFileSync(sourceApiPath,'utf8'); assert.equal(crypto.createHash('sha256').update(sourceApi).digest('hex').toUpperCase(),'159716B3150C785517BEC3A1CF1B00A7318121885E7640276B5FFAF14FC91D9A','W67 pinned W53 API');
const operation=require(opPath), leaseSrc=fs.readFileSync(leasePath,'utf8');
assert.equal(crypto.createHash('sha256').update(fs.readFileSync(opPath)).digest('hex').toUpperCase(),'47587A1A53A35CE7E58825BAC864BD75C2421D26C19791957F57BB199A7000C6','actual operation module pinned');
assert.equal(crypto.createHash('sha256').update(leaseSrc).digest('hex').toUpperCase(),'D765444136C8CAE6FD46C79BC0730D5B9266AD70EA832BFB08438AB77CA0AD75','actual lease module pinned');
const {cases}=require('./ai_operation_w67_controller_integration_contract.cjs');
function extract(name){const start=pro.indexOf(`function ${name}(`);assert(start>=0,`actual ${name} exists`);let i=pro.indexOf('{',start),depth=0,q=null,esc=false,line=false,block=false;for(;i<pro.length;i++){const c=pro[i],n=pro[i+1];if(line){if(c==='\n')line=false;continue;}if(block){if(c==='*'&&n==='/'){block=false;i++;}continue;}if(q){if(esc)esc=false;else if(c==='\\')esc=true;else if(c===q)q=null;continue;}if(c==='/'&&n==='/'){line=true;i++;continue;}if(c==='/'&&n==='*'){block=true;i++;continue;}if(c==='"'||c==="'"||c==='`'){q=c;continue;}if(c==='{')depth++;else if(c==='}'&&--depth===0)return pro.slice(start,i+1);}throw Error(`unterminated ${name}`)}
const worlds=[];
function world(cfg={}){
 const w={console,Promise,AbortController,Date,Uint8Array,ArrayBuffer,Math,JSON,Object,String,Number,RegExp,Error,parseInt,parseFloat,isFinite,setTimeout(fn){queueMicrotask(fn);return 1;},clearTimeout(){},
   _busy:false,_ctl:null,_progress:'',_log:[],HIST:[],RECENT:[],_extra:{cost:0,calls:0,models:{}},_serial:0,_offlineLast:null,_orig:null,_advLast:null,_advUsed:null,_advRejected:[],_gen:0,_editReg:{},_editRegPendingBefore:{},_editRegSig:'',_skipParts:false,_beforeImg:null,_pendingCard:null,
   _spbLayerRev:1,zones:[{id:'roof-1',name:'Roof',color:'blue'}],selectedZoneIndex:0,paintCanvas:{width:64,height:64},paintImageData:{width:64,height:64},_psdLayers:[],zoneUndoStack:[],_layerUndoStack:[],_undoEntries:[],providerCalls:0,askCoreCalls:0,applyCalls:0,undoWrites:0,renderCalls:0,
   source:{generation:4,committedGeneration:4,loading:false,committed:true,path:'C:/paint/car.tga',fingerprint:'sha-A'},
   hashMode:cfg.hashMode||'ok',cachedHash:'zone-A',zoneHash:'zone-A',sendDone:false,localApplyError:cfg.applyError||false};
 w.window=w; w.document={getElementById:id=>id==='paintCanvas'?w.paintCanvas:null};
 // Controlled adapter uses the exact W53 public API names/semantics and pinned source contract.
 w.SPBSourceLoadTransaction={getGeneration:()=>w.source.generation,getCommittedGeneration:()=>w.source.committedGeneration,getCommittedKind:()=> 'flat',isLoading:()=>w.source.loading,isCommitted:()=>w.source.committed&&!w.source.loading&&w.source.committedGeneration===w.source.generation&&!!w.source.path&&!!w.source.fingerprint,getCommittedPath:()=>w.source.path||'',getCommittedFingerprint:()=>w.source.fingerprint||''};
 w._getZoneConfigHashUncached=()=>{if(w.hashMode==='throw')throw Error('controlled uncached hash failure');if(w.hashMode==='empty')return '';if(w.hashMode==='missing')return '';return w.zoneHash;}; if(cfg.hashMode==='missing')delete w._getZoneConfigHashUncached;
 w.getZoneConfigHash=()=>w.cachedHash;
 w.SpbAiOperation=operation;
 vm.createContext(w); vm.runInContext(leaseSrc,w,{filename:'pinned-spb-ai-lease.js'});
 // Minimal actual controller dependencies. Provider boundary is deliberately a separate, counted stub.
 Object.assign(w,{offlineInstructionPreflight:()=>null,offlineFirst:()=>false,offlineCanHandle:()=>false,selfHelpClaim:()=>null,selfHelpResult:x=>x,AI:{cached:()=>({configured:true}),run:()=>{w.providerCalls++;throw Error('provider must not run in W67');}},panelsNeeded:()=>[],CAR:null,
   captureOriginal:()=>{},render:()=>{w.renderCalls++;},renderUndoHistoryPanel:()=>{},friendlyError:e=>String(e&&e.message||e),cost:()=>'',turnTally:()=>({}),mergeTally:(a,b)=>a||b||{},modelsLine:()=>'',parseNext:()=>{},undoDepth:()=>w._undoEntries.length,undoTrim:()=>{},undoSeal:()=>{},portableOp:q=>q,maskBudgetNote:()=>null,diagnose:()=>[],
   operationFailure:()=>{},_cloneZoneState:z=>JSON.parse(JSON.stringify(z)),_cloneZoneStateForUndo:z=>JSON.parse(JSON.stringify(z)),
   rollbackPendingPartRegistry:()=>{},partRegistryState:()=>({}),registerAppliedPartZones:()=>{},reconcilePartRegistry:()=>{},clearPartRegistryPending:()=>{},undoPushedSince:()=>[],
   zoneHashNow:()=>w.zoneHash,rshotFor:()=>null,applyLayerOps:()=>({lines:[],failed:[],undoSteps:0}),zonesForTest:()=>w.zones,
   Z:{batch(ops){w.applyCalls++; if(w.localApplyError)throw Error('controlled local apply error'); return ops.map((q,i)=>{Object.assign(w.zones[q.zone],q.spec||{});w.zoneHash='zone-'+(w.applyCalls+1);return {ok:true,applied:['updated'],index:q.zone,name:w.zones[q.zone].name};});}},
   offlineAsk:(text)=>({text:'Here is how to do that safely.',howto:true,offline:true,queue:[],usage:{cost:0},calls:0}),offlineHowtoPeek:()=>true,
   elemCurrentCard:()=>null,elementPaintSig:()=>'',elementRunIdentity:()=>'',elemReplyAction:()=>null,runElemAction:()=>false,elemOwnsText:()=>false,
   rshotGrab:()=>{},complaintChip:()=>false,complaintOf:()=>null,offlineComplaint:()=>null,kitAsk:()=>null,advisorIntent:()=>null,TEACH_RE:/^$/,CAR:null,
   selfHelpSig:()=>'',editPlan:()=>null,offlineMaterialPlan:()=>null,D:{offlinePartCoverage:()=>null,offlineSpec:()=>null,offlinePart:()=>null,offlineElement:()=>null,offlinePlan:()=>null,offlineIdeas:()=>false,lookRequest:()=>null},supportClass:()=>null,supportSend:()=>false,offlineCannot:()=>false,layerVisRequest:()=>false,NUM_FIX_RE:/^$/,START_OVER_RE:/^$/,CHECK_AGAIN_RE:/^$/,QUESTION_RE:/\?/,REVIEW:undefined,
   HOWTO_RE:/^how/i,_panel:{querySelector:()=>({value:''})},_progAI:false,_progT0:0,_progK:0,_progEnd:0,_cancelOpts:false,_offlineLast:null,_absent:{},_skipParts:false,_noCheck:false,
   offlineScopeReply:()=>({text:'Please load or select a committed paint first.'}),_undoStack:[]});
 w.askCore=(text,o)=>{w.askCoreCalls++;return Promise.resolve({text:'Done. Updated the roof.',queue:[{kind:'edit',zone:0,spec:{color:'#ff0000'}}],tools:['edit_zone'],usage:{cost:0},calls:0,model:'controlled-local-stub'});};
 const names=['operationDocument','operationRevision','operationManager','operationStart','operationCurrent','operationTicket','operationBind','operationCanceled','operationRelease','operationResultCurrent','operationPublish','operationRefreshDocument','operationFailure','applyQueue','ask','askForTicket','finish','finishCore','send'];
 // operation helpers may be declarations in broader slices; install each exact body explicitly.
 const code=names.filter(n=>n!=='send').map(extract).join('\n')+'\n'+pro.slice(pro.indexOf('function send(text, o) {'),pro.indexOf('function mergeMaskUndo(entry, list)'))+'\nvar _w67AskCoreCalls=0; function undoSnapTake(){return {zones:[]};} function zsnap(z){return JSON.parse(JSON.stringify(z));} function zoneIdx(id){return zones.findIndex(function(z){return String(z.id)===String(id)});} function renderZones(){} function triggerPreviewRender(){} function paintPx(){return null;} function elementRunCurrent(){return true;} function elementRunIdentity(){return "";} function elementRunCanceled(){return Promise.resolve({cancelled:true});} function elementPaintChangedResult(){return {error:{message:"source changed"},queue:[]};} function offlineInstructionPreflight(){return null;} function operationTools(a){return a;} function turnTally(){return {};} function undoDepth(){return _undoEntries.length;} function undoTrim(){} function undoSeal(e){_undoEntries.push(e);} function diagnose(){return [];} function parseNext(){} function cost(){return "";} function portableOp(q){return q;} function maskBudgetNote(){return null;} function mergeTally(){return {};} function modelsLine(){return "local";} function claimReply(){} function elementFinishGuard(id,read,fn){if(id!==read())return false;fn();return true;} function elementPaintSig(){return "";} function renderUndoHistoryPanel(){} function undoPushedSince(){return [];} function partRegistryState(){return {};} function registerAppliedPartZones(){} function reconcilePartRegistry(){} function clearPartRegistryPending(){} function rollbackPendingPartRegistry(){} function zoneHashNow(){return "zone-A";} function rshotFor(){return null;} function rshotWatch(){} function objectFollowup(){return null;} function onlineMeasure(){} function postCheck(e){return Promise.resolve(e);} function applyLayerOps(){return {lines:[],failed:[],undoSteps:0};} function _cloneZoneState(z){return JSON.parse(JSON.stringify(z));} function mergePartRegistryUndo(a,b){return b||a;} function mergeMaskUndo(){} function mergeZdiff(){} function finishUndo(){} function offlineGaveUp(){return false;} function logMiss(){} function gearModel(){return "local stub";} function preflightTeach(){return Promise.resolve({error:{message:"no preflight"}});} function warm(){return Promise.resolve();} function runTurn(){return Promise.resolve({text:"Done.",queue:[]});} function runTurn2(){return Promise.resolve({text:"Done.",queue:[]});} function askCore(text,o){_w67AskCoreCalls++;return Promise.resolve({text:"Done. Updated the roof.",queue:[{kind:"edit",zone:0,spec:{color:"#ff0000"}}],tools:["edit_zone"],usage:{cost:0},calls:0,model:"controlled-local-stub"});}';
 vm.runInContext('var _aiOperation=null; var _operationRevisionFailureSerial=0;\n'+code,w,{filename:'actual-w62-controller-slices.js'});
 Object.defineProperty(w,'askCoreCalls',{get:()=>w._w67AskCoreCalls}); worlds.push(w);
 return w;
}
const checks=[];async function scenario(name,fn){try{const r=await fn();checks.push({name,pass:true,...r});}catch(e){checks.push({name,pass:false,error:String(e&&e.stack||e)});}}
(async()=>{
 await scenario('uncommitted-post-draw-ask',async()=>{const w=world();w.source.committed=false;w.source.committedGeneration=3;w.source.fingerprint='';const r=await w.ask('change the roof',{});const e=await w.finish(r,'change the roof','ask');assert.equal(w.applyCalls,0);assert.equal(w.providerCalls,0);assert.ok(!e||!e.undoable);assert.ok(!e||!/\b(?:Done|Updated|Applied)\b/i.test(e.text));return {askCoreCalls:w.askCoreCalls,queueApplied:w.applyCalls,undoable:e&&e.undoable,text:e&&e.text};});
 await scenario('uncached-hash-throws',async()=>{const w=world({hashMode:'throw'});const r=await w.ask('change the roof',{});const e=await w.finish(r,'change the roof','ask');assert.equal(w.applyCalls,0,'batch applied unexpectedly; providers='+w.providerCalls);assert.equal(w.providerCalls,0);assert.equal(w._undoEntries.length,0);assert.ok(!e||!e.undoable);return {askCoreCalls:w.askCoreCalls,apply:w.applyCalls};});
 await scenario('uncached-hash-empty',async()=>{const w=world({hashMode:'empty'});const r=await w.ask('change the roof',{});const e=await w.finish(r,'change the roof','ask');assert.equal(w.applyCalls,0);assert.equal(w.providerCalls,0);return {askCoreCalls:w.askCoreCalls,apply:w.applyCalls,undoable:e&&e.undoable};});
 await scenario('uncached-hash-missing',async()=>{const w=world({hashMode:'missing'});const r=await w.ask('change the roof',{});const e=await w.finish(r,'change the roof','ask');assert.equal(w.applyCalls,0);assert.equal(w.providerCalls,0);return {askCoreCalls:w.askCoreCalls,apply:w.applyCalls,undoable:e&&e.undoable};});
 await scenario('source-pending-at-publication',async()=>{const w=world();w.source.loading=true;w.source.committed=false;const r=await w.ask('change the roof',{});const e=await w.finish(r,'change the roof','ask');assert.equal(w.applyCalls,0);assert.equal(w.providerCalls,0);return {askCoreCalls:w.askCoreCalls,apply:w.applyCalls,undoable:e&&e.undoable};});
 await scenario('retained-source-after-failed-replacement',async()=>{const w=world();w.source.generation=5;w.source.committedGeneration=5;w.source.loading=false;w.source.committed=true;w.source.path='C:/paint/car.tga';w.source.fingerprint='sha-A';const r=await w.ask('change the roof',{});const e=await w.finish(r,'change the roof','ask');assert.equal(w.applyCalls,1);assert.equal(w.providerCalls,0);assert.ok(e&&e.undoable);return {apply:w.applyCalls,undoable:e.undoable};});
 await scenario('current-source-valid-queue-and-finish',async()=>{const w=world();const r=await w.ask('change the roof',{});const e=await w.finish(r,'change the roof','ask');assert.equal(w.applyCalls,1);assert.ok(e&&e.lines.length);return {apply:w.applyCalls,text:e.text,lines:e.lines,undoable:e.undoable};});
 await scenario('refusal-releases-busy-and-lease',async()=>{const w=world();w.source.committed=false;w.source.fingerprint='';const r=await w.ask('change the roof',{});await w.finish(r,'change the roof','ask');assert.equal(w._busy,false);assert.equal(w.SpbAiLease.takeover(),true,'finish must not leave the lease held active');return {busy:w._busy,leaseCanBeTakenOver:true};});
 await scenario('passive-howto-without-source',async()=>{const w=world();w.source.committed=false;w.source.fingerprint='';w.AI.cached=()=>({configured:false});w.askCore=()=>Promise.resolve({text:'How-to guidance',howto:true,offline:true,queue:[],usage:{cost:0},calls:0});const r=await w.ask('How do I add a metallic finish?',{});const e=await w.finish(r,'How do I add a metallic finish?','ask');assert.equal(w.applyCalls,0);assert.ok(e&&e.text);return {text:e.text,apply:w.applyCalls,providerCalls:w.providerCalls};});
 await scenario('controller-apply-error',async()=>{const w=world({applyError:true});w.send('Change the roof to red');for(let i=0;i<12;i++)await Promise.resolve();assert.equal(w.applyCalls,1);assert.ok(w._log.some(e=>e.role==='err'&&/controlled local apply error/.test(e.text)));assert.ok(!w._log.some(e=>e.role==='ai'&&/\bDone\b/.test(e.text)));assert.equal(w._busy,false);assert.equal(w.SpbAiLease.takeover(),true);return {error:w._log.filter(e=>e.role==='err').map(e=>e.text),aiDone:false,busy:w._busy,leaseCanBeTakenOver:true};});
 await scenario('send-path-no-false-done-on-refusal',async()=>{const w=world();w.source.committed=false;w.source.fingerprint='';w.send('Change the roof to red');for(let i=0;i<12;i++)await Promise.resolve();assert.equal(w.applyCalls,0);assert.equal(w.providerCalls,0);assert.ok(!w._log.some(e=>e.role==='ai'&&/\b(?:Done|Updated|Applied)\b/i.test(e.text)));return {log:w._log,apply:w.applyCalls,busy:w._busy,lease:w.SpbAiLease.owner()};});
 await scenario('provider-boundary-local-stubs-only',async()=>{const w=world();w.source.committed=false;w.source.fingerprint='';const r=await w.ask('change the roof',{});await w.finish(r,'change the roof','ask');assert.equal(w.providerCalls,0,'network/provider adapter was never called');assert.equal(w.askCoreCalls,1,'the explicit local route stub was counted separately');return {providerCalls:w.providerCalls,localControllerStubs:w.askCoreCalls};});
 assert.equal(checks.length,cases.length,'all W67 frozen oracle scenarios exercised');
 const bad=checks.filter(c=>!c.pass), localStubs=worlds.reduce((n,w)=>n+w.askCoreCalls,0), providerCalls=worlds.reduce((n,w)=>n+w.providerCalls,0);console.log(`W67 actual controller integration: ${checks.length-bad.length}/${checks.length} scenarios passed (oracle ${cases.length}; ${useBaseline?'baseline':'candidate'})`);console.log(`Fixture boundaries: ${localStubs} local askCore stub calls; ${providerCalls} AI/provider adapter calls`);for(const c of checks)console.log(`${c.pass?'PASS':'FAIL'} ${c.name}${c.error?' — '+c.error:''}`);if(bad.length)process.exitCode=1;
})().catch(e=>{console.error(e);process.exitCode=1;});
