'use strict';
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const root=path.resolve(__dirname,'..'),dir=path.join(root,'_easy_claude_work/ai14h_generation3_candidate/w56_revision_proof'),manifest=JSON.parse(fs.readFileSync(path.join(dir,'source-freeze.json'),'utf8'));
const Operation=require(path.join(root,'js/spb-ai-operation.js'));
function reader(label){const bytes=fs.readFileSync(path.join(dir,'spb-pro-ai.'+label+'.js'));assert.equal(crypto.createHash('sha256').update(bytes).digest('hex'),manifest[label+'SHA256']);const s=bytes.toString('utf8'),a=s.indexOf('    function operationRevision() {'),b=s.indexOf('    function operationManager()',a);assert(a>=0&&b>a);const w={window:{_spbLayerRev:0},now:'A',cached:'A'};w.getZoneConfigHash=()=>w.cached;w._getZoneConfigHashUncached=()=>w.now;vm.createContext(w);vm.runInContext(s.slice(a,b),w);return {w,m:Operation.create(()=>({sourceGeneration:2}),w.operationRevision)};}
const before=reader('before'),a=before.m.start();before.w.now='manual B';assert.equal(before.m.current(a),true,'baseline falsely trusts TTL after manual change');before.w.cached='manual B';assert.equal(before.m.current(a),false,'baseline changes ownership only when TTL catches up');
const after=reader('after'),b=after.m.start();after.w.now='manual B';assert.equal(after.m.current(b),false,'fresh actual helper immediately refuses manual revision');
const positive=reader('after'),c=positive.m.start();positive.m.publish(c,()=>positive.w.now='owned B');assert.equal(positive.m.current(c),true,'owned synchronous publication remains current immediately');positive.w.cached='owned B';assert.equal(positive.m.current(c),true,'later display cache refresh cannot invalidate its owned publication');
const fallback=reader('after');delete fallback.w._getZoneConfigHashUncached;const d=fallback.m.start();assert(fallback.m.current(d),'legacy helper environments retain cached fallback');
const report={status:'PASS',scope:'Actual controller operationRevision before/after with actual operation manager; controlled memo cache. Baseline defect reproduced, four positive/rejection invariants pass.',sourceHashes:manifest,providerCalls:0,nativeMutations:0,nativeReadTiming:{uncached10Ms:4.8,cached10Ms:0.3},findings:['Cached zone revision can temporarily authorize a manual edit and later invalidate an owned publication.','Use uncached revision for AI ownership; keep display TTL intact.']};fs.writeFileSync(path.join(root,'docs/handoff_reports/AI_HELPER_14H_FRESH_REVISION_W56_2026-10-04.json'),JSON.stringify(report,null,2)+'\n');console.log('PASS: reproduced cached-revision drift; fresh ownership manual/owned/fallback controls');
