'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),crypto=require('node:crypto');
const root=path.resolve(__dirname,'..'),base='_easy_claude_work/ai14h_generation3_runtime9/js/',pro='_easy_claude_work/ai14h_w116_successor/spb-pro-ai.js',oraclePath='_easy_claude_work/ai14h_w116_help_scope/fresh-oracle.json';
const files={pro,selfhelp:base+'spb-self-help.js',receipt:base+'spb-ai-receipt-explainer.js',intent:base+'spb-ai-instruction-intent-guard.js'};
const src=Object.fromEntries(Object.entries(files).map(([k,p])=>[k,fs.readFileSync(path.join(root,p),'utf8')])),oracleText=fs.readFileSync(path.join(root,oraclePath),'utf8'),oracle=JSON.parse(oracleText);
const sha=s=>crypto.createHash('sha256').update(s).digest('hex').toUpperCase(),proSha=sha(src.pro),oracleSha=sha(oracleText);
assert.equal(proSha,'AEA057CB2965B714700304CA598C0E59AB25E02FFFB5575D5D29FC36CCD5FF76','frozen final successor pin');
assert.equal(oracleSha,'AE770A758B813261D52CBF157FBEACA41B33B2A05122FC388974AAF066B8FD8E','frozen W116c oracle pin');
function extract(s,n){const a=s.indexOf(`function ${n}(`);assert(a>=0,n+' exists');const b=s.indexOf('{',a);let d=0,q=null,ln=false,bl=false,esc=false;for(let i=b;i<s.length;i++){const c=s[i],x=s[i+1];if(ln){if(c==='\n')ln=false;continue;}if(bl){if(c==='*'&&x==='/'){bl=false;i++;}continue;}if(q){if(esc){esc=false;continue;}if(c==='\\'){esc=true;continue;}if(c===q)q=null;continue;}if(c==='/'&&x==='/'){ln=true;i++;continue;}if(c==='/'&&x==='*'){bl=true;i++;continue;}if(c==='"'||c==="'"||c==='`'){q=c;continue;}if(c==='{')d++;if(c==='}'&&--d===0)return s.slice(a,i+1);}throw Error('unterminated '+n);}
function fixture(state='empty'){const layers=state==='psd'?[{id:'paint',name:'Car Paint',img:{width:2048,height:2048},visible:true},{id:'sponsors',name:'Sponsors',img:{width:2048,height:2048},visible:false}]:[];const w={console,Promise,Date,Math,JSON,Object,Array,String,Number,RegExp,Error,document:{body:{classList:{contains:()=>false}},getElementById:()=>null},zones:[],_psdLayers:layers,paintImageData:state==='flat'?{width:2048,height:2048,data:new Uint8Array(4)}:null,selectedZoneIndex:-1,zoneSourceLayerIds:()=>[],_spbLayerRev:0,SpbProCar:{roles:()=>[],map:()=>null,missing:()=>[]},SpbAI:{cached:()=>({configured:false})},SpbAiLease:{internal:()=>true}};w.window=w;vm.createContext(w);for(const k of ['selfhelp','receipt','intent'])vm.runInContext(src[k],w,{filename:files[k]});Object.assign(w,{_log:[],_busy:false,_ctl:null,_envMemo:null,operationCurrent:t=>!!t&&t.ok===true,operationTicket:v=>v&&v._spbOperation||null,operationManager:()=>({sameDocument:t=>!!t&&t.document&&t.document.sourceGeneration===9,ready(){},owns:()=>true}),operationRevision:()=>1,operationRelease(){},operationBind:v=>v,operationStart:()=>({ok:true,document:{sourceGeneration:9},revision:1,collection:1}),operationCanceled:()=>({cancelled:true,stale:true,queue:[]}),offlineAsk:()=>Promise.resolve({offline:true,queue:[],text:'offline route sentinel'})});for(const n of ['normalizeOfflineInstruction','selfHelpResult','unexecutedSuggestionReply','contextualHelpReply','offlineInstructionPreflight','ask'])vm.runInContext(extract(src.pro,n),w,{filename:files.pro});w.spbProAI={ask:w.ask};const calls=[];w.askForTicket=(text,options)=>{calls.push({text,options});return Promise.resolve({offline:true,text:'controlled offline action handoff',queue:[]});};return{w,calls};}
const checks={
 'flat-vs-layered':[/flat/i,/layer/i,/psd|layered/i], 'load-psd':[/psd/i,/load|source paint|button|layers/i],
 'material-file-vs-source':[/spec|material|channel/i,/source paint|paint file|material|channel/i],
 'missing-source':[/source|paint|load|project/i], 'cross-car-limits':[/other car|another car|current (?:car|layout|source)|cannot|not (?:safe|confirmed|transfer)/i],
 'logo-review':[/inspect|confirm|check|candidate/i,/cannot|not guarantee|not proof|before/i], 'number-review':[/current paint|current source|inspect|confirm|check/i],
 'layer-state':[/layer/i,/visible|visibility|select|lock|editable|paint source|panel/i],
 'save-vs-source':[/project|save/i,/original psd/i], 'undo-redo':[/undo|redo/i,/mask|manual|conflict|refus|preserv/i],
 'bridge-setup':[/bridge|assistant|claude/i,/setting|install|connect|panel|toggle/i], 'bridge-error':[/bridge|connection|connect|setting|server|assistant/i],
 'offline-cost':[/without|no provider|offline|locally/i,/provider|paid|charge|cost/i]
};
(async()=>{const rows=[],issues=[];for(const c of oracle.cases){const state=c.topic==='flat-vs-layered'?'flat':/layer/i.test(c.topic)?'psd':/logo|number|cross-car/.test(c.topic)?'flat':'empty';const {w,calls}=fixture(state),r=await w.spbProAI.ask(c.input,{offline:true}),t=String(r&&r.text||'');rows.push({id:c.id,topic:c.topic,fixtureState:state,howto:!!(r&&r.howto),delegated:calls.length,queue:(r&&r.queue||[]).length,topicResult:r&&r.selfHelp&&r.selfHelp.topic,text:t.slice(0,650)});if(c.topic==='action-control'){if(r&&r.howto||calls.length!==1||calls[0].text!==c.input)issues.push(c.id+': did not remain action-eligible');continue;}if(!r||!r.howto||calls.length||(r.queue||[]).length)issues.push(c.id+': expected read-only local guidance');if(c.topic==='no-execution'&&/do it|apply this request/i.test(t))issues.push(c.id+': answer risks executing hypothetical request');for(const re of checks[c.topic]||[])if(!re.test(t))issues.push(c.id+': missing grounded topic cue '+re);if(c.topic==='logo-review'&&/recolor sponsors|pick a look|tell me a colour/i.test(t))issues.push(c.id+': diverts into sponsor recolor instead of identification review');if(c.topic==='cross-car-limits'&&/safe to reuse|will transfer|guarantee/i.test(t)&&!/cannot|not (?:safe|guaranteed|confirmed)/i.test(t))issues.push(c.id+': overclaims cross-car transfer');if(c.topic==='save-vs-source'&&/save project.*overwrite/i.test(t))issues.push(c.id+': conflates project save with writing source PSD');if(c.id==='spec-tga-import-destination'&&!(/cannot confirm|not sure|spec (?:map|file).*import|import.*spec/i.test(t)))issues.push(c.id+': confuses Source Paint color mode with a spec-map file-import destination');if(c.topic==='save-vs-source'&&!/(?:original PSD bytes are not embedded|does not bundle the original PSD|does not embed the original PSD)/i.test(t))issues.push(c.id+': omits that original PSD bytes are not embedded');}
const report={work_item:'W116c public offline help scope: files, layers, undo and bridge',status:issues.length?'REVIEW_GAPS':'PASS_PRIVATE_REPLAY',source:{path:pro,sha256:proSha,runtime9Base:'_easy_claude_work/ai14h_generation3_runtime9/js/spb-pro-ai.js',publicAskExport:/window\.spbProAI\s*=\s*\{[\s\S]*?\bask:\s*ask\s*[,}]/.test(src.pro)},oracle:{path:oraclePath,sha256:oracleSha,frozenBeforeReplay:true,cases:oracle.cases.length},rows,issues,counts:{cases:rows.length,readOnlyCases:oracle.cases.filter(x=>!['action-control'].includes(x.topic)).length,actionControls:oracle.cases.filter(x=>x.topic==='action-control').length,failed:issues.length,providerCalls:0,nativeCalls:0,queueApplications:0},limits:['The harness executes exact extracted public ask(), contextualHelpReply(), offlineInstructionPreflight() bodies and the actual self-help/receipt/intent modules. The desktop IIFE is not booted. No provider, server, browser, native app, save, or paint application is called; action controls are captured by a controlled offline handoff sentinel.']};fs.writeFileSync(path.join(root,'docs/handoff_reports/AI_HELPER_14H_PUBLIC_HELP_SCOPE_W116C_2026-10-04.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report,null,2));if(issues.length)process.exitCode=1;})().catch(e=>{console.error(e.stack||e);process.exitCode=1;});
