'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),crypto=require('node:crypto');
const root=path.resolve(__dirname,'..'),oraclePath='_easy_claude_work/ai14h_w112_polite_review/fresh-oracle.json',candidatePath='_easy_claude_work/ai14h_w112_polite_candidate/spb-pro-ai.js';
const ob=fs.readFileSync(path.join(root,oraclePath)),oracle=JSON.parse(ob),source=fs.readFileSync(path.join(root,candidatePath),'utf8'),sha=b=>crypto.createHash('sha256').update(b).digest('hex').toUpperCase();
assert.equal(sha(ob),'7577C73D70A0788383021C4AB6CD2C008DA7656D2A4FAC61C78B5880DB7EA78B');assert.equal(sha(Buffer.from(source)),'0597E031C3460CAE65F114243687B9A204DD4A0D170A3570D4A5F7D85E4EACFA');
function slice(startMark,endMark){const a=source.indexOf(startMark),b=source.indexOf(endMark,a+1);assert(a>=0&&b>a,`missing bounded anchors ${startMark}`);return source.slice(a,b);}
const helper=slice('    function pendingNamedPartWarmTarget(text) {','    function offlineAsk(text, o) {');
const ask=slice('    function offlineAsk(text, o) {','    function offlineAskCore(text, o) {');
const pre=slice('    function offlineInstructionPreflight(text) {','    // W90 route-review:');
function answer(text){
 let warms=0,hydrates=0,downstream=0,proof=false; const zones=[{_spbAIPartMemoryPending:{provenance:{r:'{"island":"roof","layers":["Car Paint"]}'}}}],ticket={};
 const ctx={Promise,console,zones,window:null,_partMemoryWarmAttemptTicket:null,_envMemo:null,_busy:false,_advLast:null,_offlineLast:null,_reqText:'',_specOnlyReq:false,_beforeImg:null,_skipParts:false,_absent:{},START_OVER_RE:/^start over\b/i,SpbAIInstructionIntentGuard:null,SpbAICompleteGuard:null,
 normalizeOfflineInstruction:t=>String(t||''),operationCurrent:()=>true,operationCanceled:()=>({route:'cancelled',queue:[]}),elementRunCurrent:()=>true,elementPaintChangedResult:()=>({route:'cancelled',queue:[]}),relativeBodyScopePreflight:()=>null,
 warm:()=>{warms++;return Promise.resolve({});},hydratePartMemory:()=>{hydrates++;proof=true;zones.forEach(z=>delete z._spbAIPartMemoryPending);},
 D:{offlinePartCoverage:()=>null,compoundPlan:()=>null,refine:()=>null},E:{},
 editPlan:t=>{if(/\b(?:upper|lower)\s+roof\b/i.test(t))return {kind:'ask',text:'Name a supported whole part.',queue:[]};if(/\b(?:roof\s+and\s+hood|hood\s+and\s+roof)\b/i.test(t))return {kind:'ask',text:'Name one part at a time.',queue:[]};if(/\b(?:explain|list)\b/i.test(t))return {kind:'describe',text:'Satin is a finish.'};if(/\b(?:could|would|can)\s+you\s+make\b/i.test(t)&&/\broof\b/i.test(t))return {kind:'ops',exactPart:true,ops:[{target:{kind:'part',part:'roof'}}]};return {kind:'ask',text:'Name a supported part.',queue:[]};},
 editYieldsToStack:()=>false,advisorOwns:()=>false,offlineMaterialPlan:()=>null,offlineMaterialAsk:()=>null,offlineCoveredPartAsk:()=>null,
 offlineEditAsk:(t,ed)=>{downstream++;if(ed.kind==='ask'||!proof)return Promise.resolve({route:'refusal',text:'Nothing was changed.',queue:[]});return Promise.resolve({route:'edit',queue:[{kind:'finish-only',part:'roof'}]});},offlineAskCore:()=>Promise.resolve({route:'core',queue:[]}),operationPublish:(t,fn)=>fn(),operationRelease(){},operationTicket:()=>ticket,captureOriginal(){},intentSpecOnly:()=>false,render(){},editReply:text=>({route:'refusal',text,queue:[]}),selfHelpResult:x=>x};
 ctx.window=ctx;vm.createContext(ctx);vm.runInContext(pre+helper+ask+'this.go=offlineAsk;',ctx,{filename:'actual-w112-polite-offlineAsk'});
 return ctx.go(text,{_spbOperation:ticket}).then(r=>({warms,hydrates,downstream,result:r}));
}
(async()=>{const rows=[];for(const c of oracle.cases){const a=await answer(c.text);let expectedWarm=c.id.startsWith('POL-0')&&Number(c.id.slice(-2))<=4;const pass=expectedWarm?(a.warms===1&&a.hydrates===1&&a.result.route==='edit'&&a.result.queue.length===1):(a.warms===0&&a.hydrates===0&&a.result.queue.length===0&&a.result.route!=='edit');rows.push({id:c.id,pass,expectedWarm,warms:a.warms,hydrates:a.hydrates,downstream:a.downstream,route:a.result.route,queued:a.result.queue.length,text:a.result.text||null});}const info=await answer('Could you make a list of satin finishes for the roof?');rows.push({id:'POL-X1',pass:info.warms===0&&info.hydrates===0&&info.result.queue.length===0,expectedWarm:false,warms:info.warms,hydrates:info.hydrates,downstream:info.downstream,route:info.result.route,queued:info.result.queue.length,classification:'post-freeze informational supplement'});const out={oracleSha256:sha(ob),candidateSha256:sha(Buffer.from(source)),counts:{cases:rows.length,passed:rows.filter(x=>x.pass).length,failed:rows.filter(x=>!x.pass).length},rows,effects:{providerCalls:0,nativeCalls:0,paintApplications:0},limits:['Actual pendingNamedPartWarmTarget, offlineAsk, offlineInstructionPreflight are evaluated from pinned candidate. editPlan and downstream proof/apply are controlled route stubs; no claim of paint or production owner-proof acceptance.']};console.log(JSON.stringify(out,null,2));if(out.counts.failed)process.exitCode=1;})().catch(e=>{console.error(e.stack||e);process.exitCode=1;});
