'use strict';
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const root=path.resolve(__dirname,'..'),dir=path.join(root,'_easy_claude_work/ai14h_generation3_runtime1');
const manifest=JSON.parse(fs.readFileSync(path.join(dir,'source-freeze.json'),'utf8'));
for(const [file,hash] of Object.entries(manifest.hashes))assert.equal(crypto.createHash('sha256').update(fs.readFileSync(path.join(dir,file))).digest('hex'),hash,file+' immutable source');
const ai=fs.readFileSync(path.join(dir,'js/spb-pro-ai.js'),'utf8'),state=fs.readFileSync(path.join(dir,'paint-booth-2-state-zones.js'),'utf8');
function slice(s,a,b){let x=s.indexOf(a),y=s.indexOf(b,x+a.length);assert(x>=0&&y>x,a);return s.slice(x,y);}
function hash(m){let h=2166136261;for(const v of m)h=Math.imul(h^(v&255),16777619);return m.length+':'+(h>>>0).toString(36);}
function world(){
 const mask=new Uint8Array(4096);mask.fill(255,0,128);
 const w={console,Uint8Array,Math,JSON,Object,Array,String,Number,Promise,Date,source:{generation:4,path:'C:/cars/fixture.psd',fingerprint:'fp-A',width:64,height:64},kind:'file',loading:false,committed:true,layout:'layout-A',element:'',_editReg:{},_editRegSig:'shape-A',_editRegPendingBefore:{},_partMemoryRuntime:null,
  zones:[],_psdLayers:[{id:'body',name:'Car Paint',visible:true,opacity:100,locked:false}],selectedZoneIndex:0,nextLinkGroupId:1,activeSpecChannel:'all'};
 w.window=w;w.CAR={signature:()=> 'shape-A',layoutSig:()=>w.layout,maskFor:()=>w.partMask?{mask:w.partMask}:null};w.partMask=mask;
 w.SpbProElements={sig:()=>w.element};w.Z={findLayer:v=>w._psdLayers.find(l=>l.id===v||l.name===v)};
 w.zoneSourceLayerIds=z=>(z.sourceLayers||[]).map(v=>w.Z.findLayer(v)?.id).filter(Boolean);
 w.getCurrentSourcePaintFile=()=>w.kind==='browser-file'?'C:/old/engine-target.png':w.source.path;
 w.SPBSourceLoadTransaction={getGeneration:()=>w.source.generation,getCommittedGeneration:()=>w.source.generation,getCommittedPath:()=>w.source.path,getCommittedFingerprint:()=>w.source.fingerprint,getCommittedKind:()=>w.kind,isLoading:()=>w.loading,isCommitted:()=>w.committed&&!w.loading};
 w.document={getElementById:id=>id==='paintCanvas'?{width:w.source.width,height:w.source.height}:{value:'',checked:false}};
 const noop=()=>{};Object.assign(w,{_savedMaskCanvasSize:()=>({w:64,h:64}),_savedMaskExpectedSize:()=>({w:64,h:64}),_getActiveImportedSpecMapPath:()=>'',_newZoneId:()=> 'new-id',_encodeSavedMask:m=>m?{width:64,height:64,data:[...m]}:null,_decodeSavedMask:m=>m?.data?new Uint8Array(m.data):null,_cloneUint8ArrayLike:x=>x,updateWearDisplay:noop,toggleNightBoostSlider:noop,updateOutputPath:noop,_sanitizeZonesInPlace:noop,renderZones:noop,renderZoneDetail:noop});
 w.SPBSourceLayerLinks={snapshotBindings:()=>({})};
 vm.createContext(w);for(const f of ['spb-ai-part-memory.js','spb-ai-part-memory-project.js'])vm.runInContext(fs.readFileSync(path.join(dir,'js',f),'utf8'),w);
 vm.runInContext(slice(ai,'function carSig()','function memNotes()')+slice(ai,'function scopedPartSourceNow()','function scopedPartProofCurrent(')+slice(ai,'function partMemoryHash(','function queueEditZones('),w);
 const z={id:'zone-roof',name:'Roof helper',base:'base::chrome',baseColorMode:'solid',baseColor:'#cc0000',useRegion:true,muted:false,regionMask:new Uint8Array(mask),sourceLayers:['body']};
 const bind={...w.source},r={island:'roof',layers:['Car Paint']};
 z._aiPartSource=bind;z._aiPartProv={r:JSON.stringify(r),z:hash(z.regionMask),p:hash(mask),l:w.layout,e:'',s:bind,car:'shape-A',layers:['body'],layerState:[{id:'body',visible:true,locked:false,opacity:100}]};
 w.zones=[z];w._editReg[w.editKey(r)]=z.name;w.ensurePartMemoryRuntime();
 vm.runInContext(slice(state,'function getConfig() {','function getSessionConfig()')+slice(state,'function loadConfigFromObj(cfg) {','// SHOKK / templates: session round-trip'),w);
 return w;
}
const results=[];
function test(id,fn){try{fn();results.push({id,pass:true});}catch(e){results.push({id,pass:false,error:e.stack});}}
function savedWorld(){const w=world(),cfg=w.getConfig();assert(cfg.zones[0].spbAIPartMemory,'actual save callback captured current owner');assert(!JSON.stringify(cfg.zones[0].spbAIPartMemory).includes('generation'));w.source={...w.source,generation:9};w.loadConfigFromObj(cfg);assert.equal(w.zones[0]._aiPartProv,undefined,'actual load grants no ownership');return {w,cfg};}
test('actual-save-load-fresh-generation-exact-owner',()=>{let{w}=savedWorld();let r=w.SpbAIPartMemoryRuntime.rebindAfterCommit(w.zones);assert.equal(r.rebound,1);let z=w.zones[0];assert.equal(z._aiPartProv.s.generation,9);assert.equal(z._aiPartProv.e,'');assert.equal(w._editReg[w.editKey(JSON.parse(z._aiPartProv.r))],z.name);assert(w.partOwnerCurrent(z,w.editKey(JSON.parse(z._aiPartProv.r))));});
for(const [id,change] of [
 ['fingerprint-replacement',w=>w.source.fingerprint='fp-B'],['path-replacement',w=>w.source.path='C:/cars/different.psd'],['canvas-size',w=>w.source.width=128],['pending-source',w=>w.loading=true],['unknown-source-bytes',w=>w.committed=false],['manual-mask',w=>w.zones[0].regionMask[0]=0],['changed-layout',w=>w.layout='layout-B'],['changed-element',w=>w.element='element-B'],['hidden-layer',w=>w._psdLayers[0].visible=false],['locked-layer',w=>w._psdLayers[0].locked=true],['missing-part-mask',w=>w.partMask=null],['duplicate-pending-selector',w=>w.zones.push({...w.zones[0],id:'other'})],['duplicate-id',w=>w.zones.push({...w.zones[0],muted:true})]
])test(id,()=>{let{w}=savedWorld();change(w);const r=w.SpbAIPartMemoryRuntime.rebindAfterCommit(w.zones);assert.equal(r.rebound,0);assert(w.zones.every(z=>!z._aiPartProv),'rejected records stay inert');});
test('save-does-not-adopt-current-source-for-stale-owner',()=>{const w=world();w.source={...w.source,generation:5};assert.equal(w.getConfig().zones[0].spbAIPartMemory,null);});
test('browser-selected-identity-ignores-legacy-engine-target',()=>{const w=world();w.kind='browser-file';w.source.path='browser-file:roof-car.png';const src=w.scopedPartSourceNow();assert.equal(src.path,w.source.path);});
const report={status:results.every(x=>x.pass)?'PASS':'FINDINGS',scope:'Actual integrated controller callbacks plus actual getConfig/loadConfig functions in VM; geometry and DOM services are controlled. No native/provider effects.',sourceHashes:manifest.hashes,results,providerCalls:0};
// W51 fresh ownership probes. These are additional to, not replacements for,
// the unchanged 16-case root oracle above.
test('W51-malformed-pending-record-stays-inert',()=>{const {w}=savedWorld();const z=w.zones[0];z._spbAIPartMemoryPending={v:99,r:'{}',p:'forged'};const r=w.SpbAIPartMemoryRuntime.rebindAfterCommit(w.zones);assert.equal(r.rebound,0);assert.equal(r.rejected,1);assert.equal(z._aiPartProv,undefined);assert.equal(z._aiPartSource,undefined);});
test('W51-duplicate-active-uuid-never-acquires-part-ownership',()=>{const {w}=savedWorld(),clone={...w.zones[0],muted:false,_aiPartProv:undefined,_aiPartSource:undefined};w.zones.push(clone);const r=w.SpbAIPartMemoryRuntime.rebindAfterCommit(w.zones);assert.equal(r.rebound,0);assert(w.zones.every(z=>z._aiPartProv===undefined));});
test('W51-missing-owner-proof-fails-closed',()=>{const {w}=savedWorld();w.partOwnerCurrent=()=>false;const r=w.SpbAIPartMemoryRuntime.rebindAfterCommit(w.zones);assert.equal(r.rebound,0);assert.equal(w.zones[0]._aiPartProv,undefined);});
test('W51-ambiguous-current-layer-name-rejected',()=>{const {w}=savedWorld();w._psdLayers.push({id:'body-duplicate',name:'Car Paint',visible:true,opacity:100,locked:false});const r=w.SpbAIPartMemoryRuntime.rebindAfterCommit(w.zones);assert.equal(r.rebound,0);assert.equal(w.zones[0]._aiPartProv,undefined);});
test('W51-source-generation-change-during-registration-rejected-without-owner-write',()=>{const {w}=savedWorld(),z=w.zones[0], old=w.CAR.maskFor, writes={prov:0,source:0}, priorEditReg=JSON.stringify(w._editReg);const tracked=new Proxy(z,{set(o,k,v){if(k==='_aiPartProv')writes.prov++;if(k==='_aiPartSource')writes.source++;return Reflect.set(o,k,v);}});w.zones=[tracked];
 let changed=false;w.CAR.maskFor=function(){const v=old();if(!changed){changed=true;w.source.generation++;}return v;};
 const r=w.SpbAIPartMemoryRuntime.rebindAfterCommit(w.zones);assert.equal(r.rebound,0);assert.equal(r.rejected,1);assert.equal(changed,true);assert.deepEqual(writes,{prov:0,source:0});assert.equal(JSON.stringify(w._editReg),priorEditReg);});
test('W51-no-provenance-write-before-invalid-current-proof',()=>{const {w}=savedWorld(),z=w.zones[0],writes={prov:0,source:0},priorEditReg=JSON.stringify(w._editReg);const tracked=new Proxy(z,{set(o,k,v){if(k==='_aiPartProv')writes.prov++;if(k==='_aiPartSource')writes.source++;return Reflect.set(o,k,v);}});w.zones=[tracked];w.CAR.maskFor=()=>null;const r=w.SpbAIPartMemoryRuntime.rebindAfterCommit(w.zones);assert.equal(r.rebound,0);assert.deepEqual(writes,{prov:0,source:0});assert.equal(JSON.stringify(w._editReg),priorEditReg);});
test('W51-owner-and-source-binding-write-only-after-all-proof-passes',()=>{const {w}=savedWorld(),z=w.zones[0],writes={prov:0,source:0},tracked=new Proxy(z,{set(o,k,v){if(k==='_aiPartProv')writes.prov++;if(k==='_aiPartSource')writes.source++;return Reflect.set(o,k,v);}});w.zones=[tracked];const r=w.SpbAIPartMemoryRuntime.rebindAfterCommit(w.zones);assert.equal(r.rebound,1);assert.deepEqual(writes,{prov:1,source:1});assert.equal(tracked._aiPartProv.s.generation,9);});

// Execute the frozen operation helpers and delayed callback bodies with fake
// promises/effects. This checks controller fencing, not native rendering.
function callbackWorld(){
 const w={console,Uint8Array,Math,JSON,Object,Array,String,Number,Promise,Date,source:{generation:2,path:'C:/fixture.psd',fingerprint:'fp',width:64,height:64},_spbLayerRev:4,_psdLayers:[{id:'l1'}],paintCanvas:{width:64,height:64},document:{getElementById:()=>({width:64,height:64})},_log:[],_rshots:[],zones:[],getZoneConfigHash:()=>String(w.manualHash||'base')};
 w.window=w;w.SPBSourceLoadTransaction={getGeneration:()=>w.source.generation,getCommittedPath:()=>w.source.path,getCommittedFingerprint:()=>w.source.fingerprint,isLoading:()=>false};w.SpbAiOperation=require(path.join(dir,'js/spb-ai-operation.js'));
 w.zoneHashNow=()=> 'zone';w.rshotGrab=()=>{w.grabs=(w.grabs||0)+1;return {h:'after',px:new Uint8Array(64)};};w.paintPx=()=>null;w.render=()=>{w.renders=(w.renders||0)+1;};w.Z={whenSettled:()=>w.settled};w.operationFixture=0;
 vm.createContext(w);const helpers=slice(ai,'var _aiOperation = null;','// End W10 operation helpers.');const watch=slice(ai,'function rshotWatch(entry)','function pxD2(');const measure=slice(ai,'var UNTOUCHED_RE =','    // ROUTER2 item 5:');vm.runInContext(helpers+watch+measure,w);return w;
}
function deferred(){let resolve;const promise=new Promise(r=>resolve=r);return {promise,resolve};}
async function asyncTest(id,fn){try{await fn();results.push({id,pass:true});}catch(e){results.push({id,pass:false,error:e.stack});}}
(async()=>{
 await asyncTest('W51-rshotWatch-stale-after-document-replacement-has-no-capture',async()=>{const w=callbackWorld(),d=deferred();w.settled=d.promise;const t=w.operationStart(),entry=w.operationBind({zdiff:{hb:'before'}},t);w.rshotWatch(entry);w.source={...w.source,generation:3,path:'C:/replacement.psd'};d.resolve();await new Promise(r=>setImmediate(r));assert.equal(w.grabs||0,0);assert.equal(entry.zdiff.ha,'zone');});
 await asyncTest('W51-onlineMeasure-stale-manual-revision-has-no-post-await-preview-or-note',async()=>{const w=callbackWorld(),d=deferred();w.settled=d.promise;const t=w.operationStart(),entry=w.operationBind({text:'Numbers were left alone.',notes:[],zdiff:{edited:[],added:[],pb:{px:new Uint8Array(64)},hb:'before'}},t);w.rshotFor=()=>({h:'before',px:new Uint8Array(64)});w.onlineMeasure(entry,entry.text);assert.equal(entry._measured,true);w._spbLayerRev++;d.resolve();await new Promise(r=>setImmediate(r));assert.equal(w.grabs||0,0);assert.deepEqual(entry.notes,[]);});
 await asyncTest('W51-onlineMeasure-current-operation-keeps-post-settle-check',async()=>{const w=callbackWorld(),d=deferred();w.settled=d.promise;const t=w.operationStart(),entry=w.operationBind({text:'Numbers were left alone.',notes:[],zdiff:{edited:[],added:[],pb:{px:new Uint8Array(64)},hb:'before'}},t);w.rshotFor=()=>({h:'before',px:new Uint8Array(64)});w.onlineMeasure(entry,entry.text);d.resolve();await new Promise(r=>setImmediate(r));assert.equal(w.grabs,1);});
 const start=ai.indexOf('afterApply: function (entry) {');assert(start>=0);let brace=ai.indexOf('{',start),depth=0,end=-1;for(let i=brace;i<ai.length;i++){if(ai[i]==='{')depth++;else if(ai[i]==='}'&&!--depth){end=i+1;break;}}assert(end>0,'afterApply function body extracted');
 const afterSrc='function(entry)'+ai.slice(brace,end); 
 await asyncTest('W51-afterApply-stale-source-does-not-capture-preview-or-mutate-entry',async()=>{const w=callbackWorld(),d=deferred();w.settled=d.promise;Object.assign(w,{hit0:[0],before0:{px:new Uint8Array(64)},sphs:[],what:'paint',place:'',plural:false,req:'undo'});vm.runInContext('var afterApplyProbe='+afterSrc+';',w);const t=w.operationStart(),entry=w.operationBind({notes:[]},t);w.afterApplyProbe(entry);w.source={...w.source,generation:5};d.resolve();await new Promise(r=>setImmediate(r));assert.equal(w.grabs||0,0);assert.deepEqual(entry.notes,[]);});
 const fallback=slice(ai,'function offlineComplaintSel(text, cp, entsOver, quiet) {','    // "Undo the whole last change"');
 test('W51-offline-selection-fallback-is-synchronous-no-delayed-closure',()=>{assert(!/\.then\s*\(|\bawait\b/.test(fallback));assert(/offlineComplaintSel\(/.test(ai.slice(ai.indexOf('function offlineComplaint(text, cp)'),ai.indexOf('function cap1(s)'))));});
 report.status=results.every(x=>x.pass)?'PASS':'FINDINGS';report.scope='Unchanged integrated 16-case actual serializer/load/controller oracle plus W51 fresh malformed/duplicate-owner/current-layer/source-race/no-write tests and actual delayed ROUTER2 callback bodies in a controlled VM. Native/provider/server effects zero; selection fallback assessed for synchronous-only execution.';report.providerCalls=0;report.nativeCalls=0;report.serverCalls=0;report.dynamicDelayedCallbackCases=4;report.staticFallbackCase=1;
 report.reviewFindings={partMemory:{actualSerializerAndLoad:'Actual frozen getConfig/loadConfigFromObj functions save sanitized spbAIPartMemory and stage it inert; W51 positive rebind only writes current _aiPartProv/_aiPartSource after source, mask, selector, owner uniqueness and layer proof.',freshResults:'11 additional W51 ownership cases pass, including source generation changed during CAR.maskFor registration, two active rows with same UUID, malformed staged record, missing owner proof, ambiguous Car Paint layer-name lookup, and Proxy-observed zero writes on failed proofs.',limitations:'Fixture controlled; it tests actual root modules and extracted actual state callbacks, not native PSD reload or user project file I/O. Freeze manifest says installed:false.'},delayedCallbacks:{rshotWatch:'Actual callback refuses stale ticket after Z.whenSettled; dynamically verified a source generation/path replacement prevents rshotGrab.',onlineMeasure:'Actual callback refuses stale ticket after settle; dynamically verified a manual layer-revision increment prevents preview capture and notes. Stable-ticket control still executes preview capture.',afterApply:'Actual closure refuses stale operation after settle; dynamically verified source replacement prevents preview capture and entry-note mutation.',offlineComplaintSel:'This selection fallback is synchronous and has no then/await closure in its body; no delayed callback exists to race. This is static classification, not an interactive selection test.'},excludedKnownIssue:'W49 mark_elements behavior explicitly excluded by parent and not asserted.',confidence:'Dynamic checks cover frozen source functions with fake promises and controlled effect stubs only; no actual app/native/provider behavior is certified.'};
 fs.writeFileSync(path.join(root,'docs/handoff_reports/AI_HELPER_14H_PART_MEMORY_W51_REVIEW_2026-10-04.json'),JSON.stringify(report,null,2)+'\n');
 console.log(JSON.stringify({status:report.status,passed:results.filter(x=>x.pass).length,total:results.length,failures:results.filter(x=>!x.pass)}));if(report.status!=='PASS')process.exitCode=1;
})();
