'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),crypto=require('node:crypto');
const root=path.resolve(__dirname,'..'),base='_easy_claude_work/ai14h_generation3_audit/frozen-runtime11/js/';
const files={pro:'_easy_claude_work/ai14h_w118_semantic_successor/spb-pro-ai.js',selfhelp:base+'spb-self-help.js',receipt:base+'spb-ai-receipt-explainer.js',intent:base+'spb-ai-instruction-intent-guard.js'};
const artifact='integrations/spb-mcp/data/artifacts/39ca28ad5076/result-528e9d22d085.json',oraclePath='_easy_claude_work/ai14h_w116_help_scope/fresh-oracle.json';
const src=Object.fromEntries(Object.entries(files).map(([k,p])=>[k,fs.readFileSync(path.join(root,p),'utf8')])),artifactText=fs.readFileSync(path.join(root,artifact),'utf8'),data=JSON.parse(artifactText),oracleText=fs.readFileSync(path.join(root,oraclePath),'utf8'),oracle=JSON.parse(oracleText),sha=s=>crypto.createHash('sha256').update(s).digest('hex').toUpperCase();
assert.equal(sha(src.pro),'DA0D6C31D73826BCE952CE5020E3E85F1B90F59E3C371E361D77294B38EBCFA4','immutable W118 candidate pin');
assert.equal(sha(src.selfhelp),'E230A121127FC6B32C451C630028D3D2D10461B67819BF50F2B148195DB8DF4D','Runtime11 self-help pin');
assert.equal(sha(src.receipt),'25ABA5EE85E9C9FB7EFE3603FCE22B140CCB09D2CBD09A9303AC6AB00530EAC3','Runtime11 receipt pin');
assert.equal(sha(src.intent),'3267DC263CF85BCB34B55588997ACBA737F4A47E7BDDE490FACE4D9D6271FB60','Runtime11 intent pin');
assert.equal(sha(oracleText),'AE770A758B813261D52CBF157FBEACA41B33B2A05122FC388974AAF066B8FD8E','unchanged W116c oracle pin');
assert.equal(data.rows.length,30,'native artifact row count');
function extract(s,n){const a=s.indexOf(`function ${n}(`);assert(a>=0,`${n} exists`);const b=s.indexOf('{',a);let d=0,q=null,ln=false,bl=false,esc=false;for(let i=b;i<s.length;i++){const c=s[i],x=s[i+1];if(ln){if(c==='\n')ln=false;continue;}if(bl){if(c==='*'&&x==='/'){bl=false;i++;}continue;}if(q){if(esc){esc=false;continue;}if(c==='\\'){esc=true;continue;}if(c===q)q=null;continue;}if(c==='/'&&x==='/'){ln=true;i++;continue;}if(c==='/'&&x==='*'){bl=true;i++;continue;}if(c==='"'||c==="'"||c==='`'){q=c;continue;}if(c==='{')d++;if(c==='}'&&--d===0)return s.slice(a,i+1);}throw Error(`unterminated ${n}`);}
function fixture(state='empty',seedKind='none'){
 const layers=state==='psd'?[{id:'paint',name:'Car Paint',img:{width:2048,height:2048},visible:true},{id:'sponsors',name:'Sponsors',img:{width:2048,height:2048},visible:false}]:[];
 const w={console,Promise,Date,Math,JSON,Object,Array,String,Number,RegExp,Error,document:{body:{classList:{contains:()=>false}},getElementById:()=>null},zones:[],_psdLayers:layers,paintImageData:state==='flat'?{width:2048,height:2048,data:new Uint8Array(4)}:null,selectedZoneIndex:-1,zoneSourceLayerIds:()=>[],_spbLayerRev:0,SpbProCar:{roles:()=>[],map:()=>null,missing:()=>[]},SpbAI:{cached:()=>({configured:false})},SpbAiLease:{internal:()=>true}};w.window=w;vm.createContext(w);
 for(const k of ['selfhelp','receipt','intent'])vm.runInContext(src[k],w,{filename:files[k]});
 const log=[];if(seedKind==='applied'||seedKind==='undone'){const e={role:'ai',lines:['Changed roof to blue'],notes:[],_spbOperation:{ok:true,document:{sourceGeneration:9},revision:1,collection:1}};if(seedKind==='undone')e.undone=true;log.push(e);}
 Object.assign(w,{_log:log,_busy:false,_ctl:null,_envMemo:null,operationCurrent:t=>!!t&&t.ok===true,operationTicket:v=>v&&v._spbOperation||null,operationManager:()=>({sameDocument:t=>!!t&&t.document&&t.document.sourceGeneration===9,ready(){},owns:()=>true}),operationRevision:()=>1,operationRelease(){},operationBind:v=>v,operationStart:()=>({ok:true,document:{sourceGeneration:9},revision:1,collection:1}),operationCanceled:()=>({cancelled:true,stale:true,queue:[]}),offlineAsk:()=>Promise.resolve({offline:true,queue:[],text:'offline route sentinel'})});
 for(const n of ['normalizeOfflineInstruction','selfHelpResult','unexecutedSuggestionReply','contextualHelpReply','offlineInstructionPreflight','ask'])vm.runInContext(extract(src.pro,n),w,{filename:files.pro});
 w.spbProAI={ask:w.ask};const calls=[];w.askForTicket=(text,options)=>{calls.push({text,options});return Promise.resolve({offline:true,text:'controlled offline action handoff',queue:[]});};return{w,calls};
}
function stateFor(text){return /tga|flatten|flat image|spec-map/i.test(text)?'flat':/psd|layer/i.test(text)?'psd':'empty';}
const cases=[...data.rows.map(r=>({id:'native:'+r.id,input:r.request,expected:'W82/W117 native meaning; grade from actual response',topic:r.id,_source:'native'})),...oracle.cases.map(c=>({id:'W116c:'+c.id,input:c.input,expected:c.expect,topic:c.topic,_source:'w116c'}))];
(async()=>{const rows=[],issues=[];for(const c of cases){const st=stateFor(c.input),seed=c.id==='native:latest-receipt-after-undo'?'undone':'none',{w,calls}=fixture(st,seed),r=await w.spbProAI.ask(c.input,{offline:true}),text=String(r&&r.text||''),queue=(r&&r.queue||[]).length,delegated=calls.length;rows.push({id:c.id,input:c.input,expected:c.expected,state:st,howto:!!(r&&r.howto),topic:r&&r.selfHelp&&r.selfHelp.topic||'',queue,delegated,text:text.slice(0,1800)});
 if(c._source==='native'){if(!r||!r.howto||delegated||queue)issues.push(c.id+': expected read-only help with no queue/delegation');}
 else if(c.topic==='action-control'){if(!r||r.howto||delegated!==1||calls[0].text!==c.input||queue)issues.push(c.id+': direct imperative did not delegate once to controlled offline action adapter');}
 else if(c.topic==='no-execution'){if(!r||!r.howto||delegated||queue)issues.push(c.id+': explicit no-execute was not read-only');}
 else if(!r||!r.howto||delegated||queue)issues.push(c.id+': expected read-only help with no queue/delegation');
 }
 const findings=[
  {id:'W116c:redo-after-manual-edit',grade:'failure',note:'The user asks whether Redo can restore an AI edit after hand-editing a layer; the route answers with generic PSD layer editability, not Redo conflict/current-state safeguards.'},
  {id:'W116c:no-execute-control',grade:'failure',note:'The user asks hypothetically what hiding Wireframe would do and explicitly says not to change anything; the route returns imperative how-to steps for turning template layers off and rendering. Queue/delegation stay zero, but the answer ignores the read-only intent and gives unrelated action instructions.'}
 ];
 rows.forEach(r=>{r.grade=r.id==='W116c:action-control-finish'?'action-intent-pass':findings.some(f=>f.id===r.id)?'failure':'useful';});
 const report={work_item:'Independent replay of Runtime11 native 30 + unchanged W116c 20 on W118 successor',status:issues.length?'ROUTE_GATE_GAPS':findings.length?'SEMANTIC_REVIEW_GAPS':'PASS_PRIVATE_REPLAY',source:{candidate:files.pro,sha256:sha(src.pro),runtime11SelfHelp:sha(src.selfhelp),runtime11Receipt:sha(src.receipt),runtime11Intent:sha(src.intent)},artifacts:[{path:artifact,sha256:sha(artifactText),cases:data.rows.length},{path:oraclePath,sha256:sha(oracleText),frozen:true,cases:oracle.cases.length}],counts:{cases:rows.length,nativeCases:data.rows.length,w116cCases:oracle.cases.length,useful:rows.filter(r=>r.grade==='useful').length,semanticFailures:findings.length,actionIntentPasses:rows.filter(r=>r.grade==='action-intent-pass').length,routeIssues:issues.length,providerCalls:0,nativeCalls:0,paintApplications:0},rows,issues,semanticFindings:findings,limits:['Calls exact extracted public ask(), context-help and preflight bodies plus Runtime11 self-help/receipt/intent modules. Does not boot the desktop IIFE or exercise real offline planner/application, providers, native UI, save, or paint. W116c imperative control is routed once to a controlled offline action stub; this proves intent routing only. State fixture is controlled (layered PSD metadata, flat composite metadata, or no source) and does not assert production loader behavior.']};const out='docs/handoff_reports/AI_HELPER_14H_RUNTIME11_NATIVE30_W116C_W118_RECHECK_2026-10-04.json';fs.writeFileSync(path.join(root,out),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({status:report.status,cases:rows.length,semanticFindings:findings,report:out},null,2));if(issues.length||findings.length)process.exitCode=1;})().catch(e=>{console.error(e.stack||e);process.exitCode=1;});
