'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),crypto=require('node:crypto');
const root=path.resolve(__dirname,'..'),base='_easy_claude_work/ai14h_stack_completeness_successor',dPath=base+'/candidate/spb-pro-design.js',cPath=base+'/candidate/spb-pro-ai.js',runtime='_easy_claude_work/ai14h_generation3_runtime11',guardPath='_easy_claude_work/ai14h_final_source_identity_candidate/browser-file-v2/spb-pro-ai.js',oraclePath='_easy_claude_work/ai14h_solid_color_conflict_successor/fresh-oracle.json';
const read=p=>fs.readFileSync(path.join(root,p),'utf8'),sha=s=>crypto.createHash('sha256').update(s).digest('hex');
const design=read(dPath),controller=read(cPath),guard=read(guardPath),oracleBytes=read(oraclePath),oracle=JSON.parse(oracleBytes),supplementPath='_easy_claude_work/ai14h_solid_color_conflict_successor/supplement-colors.json',supplementBytes=read(supplementPath),supplement=JSON.parse(supplementBytes);
assert.equal(sha(oracleBytes),'b2c382721629e01d8a5a4544953cc704cb928a680910e8d6a4ffe3f115f21e78','frozen pre-edit color oracle');
assert.equal(sha(supplementBytes),'a7e6472d8e3eb899ca8a11158e111fb88105f524a86b745ccb325bdaba74f1db','frozen adversarial clause supplement');
assert.equal(sha(guard),'fb63f5906e1c9fc9d49150f571d64fde640e0a4630319c418fe4f9c2e7e5413a','strict source guard pin');
function extract(source,name){const start=source.indexOf(`function ${name}(`);assert(start>=0,`missing ${name}`);const brace=source.indexOf('{',start);let depth=0,q='',esc=false,line=false,block=false;for(let i=brace;i<source.length;i++){const c=source[i],n=source[i+1];if(line){if(c==='\n')line=false;continue;}if(block){if(c==='*'&&n==='/'){block=false;i++;}continue;}if(q){if(esc){esc=false;continue;}if(c==='\\'){esc=true;continue;}if(c===q)q='';continue;}if(c==='/'&&n==='/'){line=true;i++;continue;}if(c==='/'&&n==='*'){block=true;i++;continue;}if(c==='"'||c==="'"||c==='`'){q=c;continue;}if(c==='{')depth++;else if(c==='}'&&--depth===0)return source.slice(start,i+1);}throw Error('unterminated '+name);}
function harness(){
 const w={console,Promise,Date,Math,JSON,Object,Array,String,Number,RegExp,Error,Set,Map,parseInt,parseFloat,document:{body:{classList:{contains:()=>false}},getElementById:()=>null},zones:[],_psdLayers:[],paintImageData:null,selectedZoneIndex:-1,zoneSourceLayerIds:()=>[],_spbLayerRev:0,_spbOperationRevision:1,SpbProCar:{roles:()=>[],map:()=>null,missing:()=>[]},SpbAiLease:{internal:()=>true},SpbAI:{cached:()=>({configured:false})}};w.window=w;vm.createContext(w);const load=p=>vm.runInContext(read(p),w,{filename:p});load(runtime+'/js/spb-ai-instruction-intent-guard.js');load(runtime+'/js/spb-ai-complete-instruction-guard.js');
 w.D=(()=>{let dw={};vm.runInNewContext(design,{window:dw,console});return dw.SpbProDesign;})();w.E=null;w.AI=w.SpbAI;w.CAR=null;w._skipParts=false;w._absent={};w._offlineLast=null;w._advLast=null;w._advRejected=[];w._advDislikes=[];w._advUsed=null;w._busy=false;w._log=[];w._serial=0;w._forcedIdeaCols=null;w._envMemo=null;w._partMemoryWarmAttemptTicket=null;w.START_OVER_RE=/^start over$/i;w.NUM_FIX_RE=/^\s*$/;w.NOT_ELEM_RE=/$a/;let ticket={ok:true,id:1};const sinks=[];
 Object.assign(w,{normalizeOfflineInstruction:null,offlineInstructionPreflight:null,relativeBodyScopePreflight:null,operationCurrent:t=>!!t&&t.ok===true,operationCanceled:()=>({offline:true,queue:[],cancelled:true}),operationStart:()=>ticket,operationRelease(){},operationBind:r=>r,operationManager:()=>({ready(){},sameDocument:()=>true}),operationPublish:(_t,fn)=>fn(),operationTicket:()=>null,operationTools:()=>[],operationRevision:()=>1,elementRunCurrent:()=>true,contextualHelpReply:()=>null,selfHelpClaim:()=>null,selfHelpResult:r=>({offline:true,queue:[],howto:true,text:r.text}),advisorOwns:()=>false,advisorIntent:()=>null,editReply:text=>({offline:true,queue:[],route:'conflict-ask',text}),offlineCannot:()=>null,offlineMaterialPlan:()=>null,editPlan:()=>null,editYieldsToStack:()=>false,pendingNamedPartWarmTarget:()=>null,warm:()=>Promise.resolve(),hydratePartMemory(){},captureOriginal(){},render(){},intentSpecOnly:()=>false,offlineCoveredPartAsk:(text,proof)=>{sinks.push({kind:'covered',text,proof});return Promise.resolve({offline:true,queue:[],route:'covered',proof});},offlineLookAsk:(text,look)=>{sinks.push({kind:'look',text,look});return Promise.resolve({offline:true,queue:[],route:'look-clarification',text:'Please clarify.'});},offlinePartAsk:(text,plan)=>{sinks.push({kind:'part',text,plan});return Promise.resolve({offline:true,queue:[],route:'part',plan});},offlineSpecAsk:(text,plan)=>{sinks.push({kind:'spec',text,plan});return Promise.resolve({offline:true,queue:[],route:'spec',plan});},offlineElementAsk:(text,plan)=>{sinks.push({kind:'element',text,plan});return Promise.resolve({offline:true,queue:[],route:'element',plan});},offlineIdeasAsk:()=>null,layerVisRequest:()=>null,offlineNumbersAsk:()=>null,offlineElemWrong:()=>null,offlineRefineAsk:()=>null,offlineStartOver:()=>({offline:true,queue:[]}),offlineUndo:()=>({offline:true,queue:[]}),offlineScopeReply:()=>({offline:true,queue:[],route:'scope-ask'}),preflightTeach:()=>({offline:true,queue:[],route:'teach-ask'}),offlineHowto:()=>null,operationFailure:()=>({offline:true,queue:[]}),offlineGaveUp:()=>true,offlineCanHandle:()=>true,logMiss(){},askCore:()=>Promise.resolve({offline:true,queue:[]})});
 w.normalizeOfflineInstruction=vm.runInContext('('+extract(controller,'normalizeOfflineInstruction')+')',w);w.offlineInstructionPreflight=vm.runInContext('('+extract(guard,'offlineInstructionPreflight')+')',w);w.relativeBodyScopePreflight=vm.runInContext('('+extract(guard,'relativeBodyScopePreflight')+')',w);for(const n of ['offlineAsk','offlineAskCore','askForTicket','ask'])vm.runInContext(extract(controller,n),w,{filename:'private:'+n});return{w,sinks};
}
(async()=>{
 const rows=[],issues=[];
 for(const c of oracle.cases){const {w,sinks}=harness(),r=await w.ask(c.request,{offline:true}),sink=sinks.at(-1)||null,plans=sink?.proof?.zones||sink?.plan?.zones||[],direct=w.D.compoundPlan(c.request),status=w.D.partColorConflict(c.request),row={id:c.id,expected:c.expected,route:r.route||sink?.kind||'guard-or-other',queue:(r.queue||[]).length,sinks:sinks.length,zones:plans.map(z=>({part:z.region?.part||'body',color:z.color,finish:z.finish})),directZones:direct?.zones?.map(z=>({part:z.region?.part||'body',color:z.color,finish:z.finish}))||[],status,text:String(r.text||'').slice(0,220)};rows.push(row);
  if(row.queue)issues.push(c.id+': queue must remain empty in this route harness');
  if(c.expected.startsWith('clarify-color-q0')){if(status?.kind!=='color-conflict'||row.route!=='conflict-ask'||sink||direct||row.zones.length||!/which color/i.test(row.text)||!/nothing was changed/i.test(row.text))issues.push(c.id+': expected color-specific zero-plan clarification; '+JSON.stringify(row));}
  if(c.expected==='not-conflicting-colors; complete-safe-or-clarify'){if(status?.kind==='color-conflict')issues.push(c.id+': repeated same color falsely conflicted');}
  if(c.expected==='one-roof-red-change-no-conflict'){if(status||row.route==='conflict-ask'||row.zones.some(z=>z.part==='body'))issues.push(c.id+': explicit replacement was treated as conflict or widened');}
  if(c.expected==='retain-distinct-part-colors-no-body-expansion'){if(status||row.zones.some(z=>z.part==='body')||(!row.zones.some(z=>z.part==='roof')&&!row.zones.some(z=>z.part==='hood')))issues.push(c.id+': different-part colors conflicted or widened to body');}
  if(c.expected.startsWith('do-not-classify-as-flat-color-conflict')){if(status?.kind==='color-conflict'||row.route==='conflict-ask')issues.push(c.id+': intentional multicolor design falsely treated as flat-color conflict');}
  if(c.expected==='one-roof-red-matte-or-safe-clarification-no-body'){if(status||row.zones.some(z=>z.part==='body'))issues.push(c.id+': one color plus finish falsely conflicted or widened');}
  if(c.expected==='information-only-q0-no-edit'){if(direct||row.route==='conflict-ask'||row.queue||row.zones.length)issues.push(c.id+': quoted information request entered an executable edit path');}
  if(c.expected==='no-op-q0'){if(direct||row.zones.length||row.queue)issues.push(c.id+': prohibited request produced an executable plan');}
 }
 const supplementaryRows=[];for(const c of supplement.cases){const {w,sinks}=harness(),r=await w.ask(c.request,{offline:true}),sink=sinks.at(-1)||null,plan=sink?.proof||sink?.plan||null,plans=plan?.zones||[],status=w.D.partColorConflict(c.request),direct=w.D.compoundPlan(c.request),row={id:c.id,expected:c.expected,route:r.route||sink?.kind||'guard-or-other',queue:(r.queue||[]).length,status,zones:plans.map(z=>({part:z.region?.part||'body',color:z.color})),directZones:direct?.zones?.map(z=>({part:z.region?.part||'body',color:z.color}))||[]};supplementaryRows.push(row);if(c.expected.startsWith('distinct-')){var wantsBody=c.id==='body-then-part-color';if(status||wantsBody!==row.zones.some(z=>z.part==='body')||!row.zones.some(z=>z.part==='roof')||(!wantsBody&&!row.zones.some(z=>z.part==='hood')))issues.push(c.id+': intended separate target clauses were not retained');}if(c.expected==='roof-conflict-still-wins-before-next-part'&&(status?.kind!=='color-conflict'||direct||row.queue||sink))issues.push(c.id+': bare adjacent second color escaped same-part conflict guard');}
 const core=[];for(const input of ['Make the roof blue and the roof red.','Make the roof blue and red, and the hood gold.']){const {w,sinks}=harness(),r=await w.offlineAskCore(input,{offline:true,_spbOperation:{ok:true,id:3}}),row={input,route:r.route||'guard-or-other',queue:(r.queue||[]).length,sinks:sinks.length,text:String(r.text||'')};core.push(row);if(row.queue||row.sinks||!/which color/i.test(row.text)||!/nothing was changed/i.test(row.text))issues.push('offlineAskCore did not stop same-part color conflict: '+input);}
 const report={status:issues.length?'FAIL_PRIVATE':'PASS_PRIVATE_WITH_LIMITS',oracle:{path:oraclePath,sha256:sha(oracleBytes),cases:oracle.cases.length},supplement:{path:supplementPath,sha256:sha(supplementBytes),cases:supplement.cases.length,rows:supplementaryRows},pins:{designPath:dPath,designSha256:sha(design),controllerPath:cPath,controllerSha256:sha(controller),guardPath,guardSha256:sha(guard)},counts:{cases:rows.length,supplementCases:supplementaryRows.length,coreCases:core.length,colorConflicts:rows.filter(x=>x.expected.startsWith('clarify-color-q0')).length,providerCalls:0,nativeCalls:0,applyCalls:0},rows,core,supplementaryRows,issues,limits:['Evaluated pinned Design.compoundPlan()/partColorConflict() and controller ask()/offlineAskCore() with edit sinks stubbed. This verifies routes, plans, and zero-queue clarification; no native apply, pixel result, or provider behavior was exercised.']};
 const out=path.join(root,base,'color-regression.json');fs.writeFileSync(out,JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report,null,2));if(issues.length)process.exitCode=1;
})().catch(e=>{console.error(e.stack||e);process.exitCode=1;});



