'use strict';
// W64 independent replay: actual W53 public transaction API slice + pinned W59 helper.
const assert=require('node:assert/strict'),crypto=require('node:crypto'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),cp=require('node:child_process');
const root=path.resolve(__dirname,'..'), candidateDir=path.join(root,'_easy_claude_work/ai14h_w59_candidate/js');
const helperPath=path.join(candidateDir,'spb-self-help.js'), knowledgePath=path.join(candidateDir,'spb-ai-knowledge.js');
const w53Path=path.join(root,'_easy_claude_work/ai14h_w53_candidate/candidate/paint-booth-3-canvas.js');
const w59ReportPath=path.join(root,'docs/handoff_reports/AI_HELPER_14H_SELF_HELP_W59_CANDIDATE_2026-10-04.json');
const w59Report=JSON.parse(fs.readFileSync(w59ReportPath,'utf8'));
const hashes={helper:crypto.createHash('sha256').update(fs.readFileSync(helperPath)).digest('hex').toUpperCase(),knowledge:crypto.createHash('sha256').update(fs.readFileSync(knowledgePath)).digest('hex').toUpperCase(),w53:crypto.createHash('sha256').update(fs.readFileSync(w53Path)).digest('hex').toUpperCase(),audit:crypto.createHash('sha256').update(fs.readFileSync(path.join(root,w59Report.frozen_inputs.audit_manifest.path))).digest('hex').toUpperCase()};
assert.equal(hashes.helper,w59Report.candidate.sha256);assert.equal(hashes.w53,w59Report.frozen_inputs.source_api_candidate.sha256);assert.equal(hashes.audit,w59Report.frozen_inputs.audit_manifest.sha256);
const fresh=Object.freeze([
 {id:'W64-F01',case:'old action offered before load of a different source',expect:'refuse while pending and stale old offer after failed load'},
 {id:'W64-F02',case:'offer action after actual API begins load',expect:'no mutation while isCommitted=false'},
 {id:'W64-F03',case:'failed replacement retains source A with fresh committed generation',expect:'old chip refuses; fresh diagnosis on retained A may act'},
 {id:'W64-F04',case:'same path is loaded with different committed bytes',expect:'old chip refuses on generation/fingerprint change'},
 {id:'W64-F05',case:'hood geometry changes after action offer',expect:'stale target refuses'},
 {id:'W64-F06',case:'current hood is cloned by Undo with same stable ID and target stamp',expect:'safe current clone resolves'},
 {id:'W64-F07',case:'zone order changes in place while hood object remains stable',expect:'action follows the same target identity'},
 {id:'W64-F08',case:'duplicate hood ID is added',expect:'ambiguous action refuses'},
 {id:'W64-F09',case:'hood stable ID is removed',expect:'action refuses'},
 {id:'W64-F10',case:'layer lock or presentation state changes after offer',expect:'stale layer-state action refuses'},
 {id:'W64-F11',case:'no paint source, zones or layers are present',expect:'passive guidance remains available'},
 {id:'W64-F12',case:'same source and target remain valid, controller rejects action',expect:'do not report completion when controller fails'}
]);
const oracle={review:'W64 fresh actual-source-API lifecycle oracle',frozen_before_execution:true,cases:fresh};
const oraclePath=path.join(root,'_easy_claude_work/ai14h_w64_review/oracle.json');fs.mkdirSync(path.dirname(oraclePath),{recursive:true});fs.writeFileSync(oraclePath,JSON.stringify(oracle,null,2)+'\n');
const oracleSha=crypto.createHash('sha256').update(fs.readFileSync(oraclePath)).digest('hex').toUpperCase();
const source=fs.readFileSync(w53Path,'utf8');
const apiStart=source.indexOf('var _spbSourceLoadGeneration = 0;');const apiEnd=source.indexOf('async function loadPaintPreviewFromServer(tgaPath)',apiStart);
assert(apiStart>=0&&apiEnd>apiStart,'W53 source transaction implementation block exists');
const apiBlock="var _psdPath='';\n"+source.slice(apiStart,apiEnd)+"\nwindow.__w64SetIdentity=function(p,f){_spbCommittedSourcePath=String(p||'');_spbCommittedSourceFingerprint=String(f||'');};\n";
function load(){
 const w={console,Promise,Date,_spbLayerRev:1,selectedZoneIndex:1,_psdLayers:[],paintImageData:{width:8,height:8},document:{body:{classList:{contains:()=>false}}},
  zones:[{id:'body-id',name:'Body',base:'gloss'},{id:'hood-id',name:'Hood',base:'gloss',muted:true,region:{x:1,y:2,w:3,h:4}}],calls:{mute:[],select:[],refresh:[]}};w.window=w;
 vm.createContext(w);vm.runInContext(apiBlock,w,{filename:'actual-W53-source-transaction-slice'});
 const txApi=w.SPBSourceLoadTransaction;const initial=txApi.begin('C:/paint/car.tga','flat');w.__w64SetIdentity('C:/paint/car.tga','sha-a');txApi.result(initial,true,{committedPath:'C:/paint/car.tga',fingerprint:'sha-a',sourceKind:'flat'});assert.equal(txApi.isCommitted(),true);
 w.SpbProCar={map:()=>({}),missing:()=>[],signature:()=>`layout-${w._spbLayerRev}`};
 w.selectZone=i=>{w.calls.select.push(i);w.selectedZoneIndex=i;};w.toggleZoneMute=i=>{w.calls.mute.push(i);w.zones[i].muted=!w.zones[i].muted;};w.triggerPreviewRender=()=>{w.calls.refresh.push(1);};
 for(const f of ['spb-ai-knowledge.js','spb-self-help.js'])vm.runInContext(fs.readFileSync(path.join(candidateDir,f),'utf8'),w,{filename:f});return w;
}
function action(w){const a=w.SpbSelfHelp.answer('Why is my hood not changing colour?');assert.equal(a&&a.doIt&&a.doIt.act,'unmute_zone');return a.doIt.label;}
function ok(name,fn){try{fn();return{name,pass:true};}catch(e){return{name,pass:false,error:String(e&&e.message||e)};}}
const results=[];
results.push(ok('actual W53 transaction reports fresh readiness through the exact installed public methods',()=>{const w=load(),t=w.SPBSourceLoadTransaction;assert.equal(t.getGeneration(),t.getCommittedGeneration());assert.equal(t.isLoading(),false);assert.equal(t.isCommitted(),true);assert.equal(t.getCommittedPath(),'C:/paint/car.tga');assert.equal(t.getCommittedFingerprint(),'sha-a');}));
results.push(ok(fresh[0].case,()=>{const w=load(),label=action(w),tx=w.SPBSourceLoadTransaction.begin('C:/paint/other.tga','flat');assert.equal(w.SPBSourceLoadTransaction.isCommitted(),false);const during=w.SpbSelfHelp.runDoIt(label);assert.equal(during&&during.done,false);assert.deepEqual(w.calls.mute,[]);w.SPBSourceLoadTransaction.result(tx,false,{error:'decode failed'});assert.equal(w.SPBSourceLoadTransaction.isCommitted(),true);assert.equal(w.SPBSourceLoadTransaction.getCommittedPath(),'C:/paint/car.tga');assert.equal(w.SPBSourceLoadTransaction.getCommittedGeneration(),tx.generation);const freshLabel=action(w),freshResult=w.SpbSelfHelp.runDoIt(freshLabel);assert.equal(freshResult.done,true);assert.deepEqual(w.calls.mute,[1]);}));
results.push(ok(fresh[1].case,()=>{const w=load(),tx=w.SPBSourceLoadTransaction.begin('C:/paint/pending.tga','flat'),label=action(w);assert.equal(w.SPBSourceLoadTransaction.isLoading(),true);assert.equal(w.SpbSelfHelp.runDoIt(label).done,false);assert.deepEqual(w.calls.mute,[]);w.SPBSourceLoadTransaction.result(tx,false,{error:'read failed'});}));
results.push(ok(fresh[2].case,()=>{const w=load(),old=action(w),tx=w.SPBSourceLoadTransaction.begin('C:/paint/bad.tga','flat');w.SPBSourceLoadTransaction.result(tx,false,{error:'failed replacement'});assert.equal(w.SPBSourceLoadTransaction.isCommitted(),true);assert.equal(w.SPBSourceLoadTransaction.getCommittedPath(),'C:/paint/car.tga');assert.equal(w.SpbSelfHelp.runDoIt(old).done,false);const current=action(w),r=w.SpbSelfHelp.runDoIt(current);assert.equal(r.done,true);assert.deepEqual(w.calls.mute,[1]);}));
results.push(ok(fresh[3].case,()=>{const w=load(),label=action(w),tx=w.SPBSourceLoadTransaction.begin('C:/paint/car.tga','flat');w.__w64SetIdentity('C:/paint/car.tga','sha-b');w.SPBSourceLoadTransaction.result(tx,true,{committedPath:'C:/paint/car.tga',fingerprint:'sha-b'});assert.equal(w.SPBSourceLoadTransaction.isCommitted(),true);assert.equal(w.SpbSelfHelp.runDoIt(label).done,false);assert.deepEqual(w.calls.mute,[]);}));
results.push(ok(fresh[4].case,()=>{const w=load(),label=action(w);w.zones[1].region.x=99;assert.equal(w.SpbSelfHelp.runDoIt(label).done,false);assert.deepEqual(w.calls.mute,[]);}));
results.push(ok(fresh[5].case,()=>{const w=load(),label=action(w);w.zones[1]={...w.zones[1]};assert.equal(w.SpbSelfHelp.runDoIt(label).done,true);assert.deepEqual(w.calls.mute,[1]);}));
results.push(ok(fresh[6].case,()=>{const w=load(),label=action(w),hood=w.zones[1];w.zones.reverse();assert.equal(w.SpbSelfHelp.runDoIt(label).done,true);assert.equal(hood.muted,false);assert.deepEqual(w.calls.mute,[0]);}));
results.push(ok(fresh[7].case,()=>{const w=load(),label=action(w);w.zones[0].id='hood-id';assert.equal(w.SpbSelfHelp.runDoIt(label).done,false);assert.deepEqual(w.calls.mute,[]);}));
results.push(ok(fresh[8].case,()=>{const w=load(),label=action(w);delete w.zones[1].id;assert.equal(w.SpbSelfHelp.runDoIt(label).done,false);assert.deepEqual(w.calls.mute,[]);}));
results.push(ok(fresh[9].case,()=>{const w=load();w._psdLayers=[{id:'body',name:'Body',img:{},visible:true,locked:false}];const label=action(w);w._psdLayers[0].locked=true;assert.equal(w.SpbSelfHelp.runDoIt(label).done,false);assert.deepEqual(w.calls.mute,[]);}));
results.push(ok(fresh[10].case,()=>{const w=load();w.paintImageData=null;w.zones=[];w._psdLayers=[];assert.equal(w.SpbSelfHelp.state().paint,'none');const a=w.SpbSelfHelp.answer('How do I add a metallic finish?');assert.ok(a&&a.text&&a.text.length>0&&a.steps.length>0);}));
results.push(ok(fresh[11].case,()=>{const w=load(),label=action(w);w.toggleZoneMute=()=>{throw Error('controller denied');};const r=w.SpbSelfHelp.runDoIt(label);assert.equal(r.done,false);assert.match(r.text,/could not do that one myself/i);}));
function runWithCandidate(testName){const testPath=path.join(root,'tests',testName),target=path.join(root,'js/spb-self-help.js');const bootstrap=`const fs=require('node:fs'),path=require('node:path');const original=fs.readFileSync.bind(fs),candidate=original(${JSON.stringify(helperPath)});const target=path.resolve(${JSON.stringify(target)});fs.readFileSync=function(p,...a){if(path.resolve(String(p))===target)return candidate;return original(p,...a)};require(${JSON.stringify(testPath)});`;return cp.execFileSync(process.execPath,['-e',bootstrap],{cwd:root,encoding:'utf8'});}
function runW59(){return cp.execFileSync(process.execPath,[path.join(root,'tests/ai_self_help_w59_review_contract.cjs')],{cwd:root,encoding:'utf8'});}
const compat={};for(const [key,file] of [['w59','W59 frozen helper:'],['w3','independent W3 review cases:'],['w4','W4 independent semantic review:']]){try{const out=key==='w59'?runW59():runWithCandidate(key==='w3'?'ai_help_action_w3_review_contract.cjs':'ai_self_help_w4_review_contract.cjs');compat[key]={ok:true,output:out.trim().split(/\r?\n/).filter(x=>x.startsWith(key==='w59'?'W59 frozen helper:':key==='w3'?'PASS independent W3 review cases:':'PASS W4 independent semantic review:')).slice(0,2)};}catch(e){compat[key]={ok:false,error:String(e.stderr||e.stdout||e.message).slice(-3000)};}}
const failures=results.filter(x=>!x.pass),report={review:'W64 self-help action with actual W53 source transaction API',date:'2026-10-04',status:failures.length||Object.values(compat).some(x=>!x.ok)?'BLOCKED':'PASS',oracle:{path:'_easy_claude_work/ai14h_w64_review/oracle.json',sha256:oracleSha,cases:fresh},sourceHashes:{w59CandidateHelper:hashes.helper,w59CandidateKnowledge:hashes.knowledge,w53CandidateCanvas:hashes.w53,w59AuditManifest:hashes.audit},retainedOracles:{w59:{path:'tests/ai_self_help_w59_review_contract.cjs',result:compat.w59},w3:{path:'tests/ai_help_action_w3_review_contract.cjs',result:compat.w3},w4:{path:'tests/ai_self_help_w4_review_contract.cjs',result:compat.w4}},counts:{freshCases:results.length,freshPassed:results.filter(x=>x.pass).length,freshFailed:failures.length},results,limits:['Actual W53 `_spbBeginSourceLoad`, `_spbIsCurrentSourceLoad`, `_spbSourceLoadResult`, and registered `SPBSourceLoadTransaction` object are extracted from the pinned candidate and executed; a narrow test seam sets the source path/fingerprint at the point where a mocked loader would publish bytes. The surrounding canvas loaders and UI are not run.','Self-help controller operations are mocked and zero provider, browser, native, render, or save calls are made.','W59/W3/W4 prior oracles are compatibility replays on the pinned helper; W3/W4 runners substitute only the frozen W59 helper bytes for the active file.']};
const reportPath=path.join(root,'docs/handoff_reports/AI_HELPER_14H_SELF_HELP_W64_SOURCE_API_REVIEW_2026-10-04.json');fs.writeFileSync(reportPath,JSON.stringify(report,null,2)+'\n');
console.log(JSON.stringify({status:report.status,counts:report.counts,retainedOracles:compat,failures},null,2));if(report.status!=='PASS')process.exitCode=2;
