'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),crypto=require('node:crypto');
const oldTest=fs.readFileSync('tests/ai_source_bytes_part_memory_w76_review_contract.cjs','utf8'),start=oldTest.indexOf('function extractFunction('),end=oldTest.indexOf('\nconst canvas=',start);
const extract=vm.runInNewContext(oldTest.slice(start,end)+'\nextractFunction',{assert});
const file=process.argv[2]||'_easy_claude_work/ai14h_generation3_candidate/w81_source_chain/paint-booth-3-canvas.js',source=fs.readFileSync(file,'utf8');
const declarations=['function _spbBeginSourceLoad(','function _spbIsCurrentSourceLoad(','function _spbSourceLoadResult(','function _spbLayeredSourceFingerprint(','async function _doPSDImport('].map(s=>extract(source,s)).join('\n');
const A='a'.repeat(64),B='b'.repeat(64),rows=[];
async function run(id,strong,rasterDigest,expectedStage,status=200){
 let requests=[],staged=0;const rasterLayers={};Object.defineProperty(rasterLayers,'one',{get(){staged++;throw Error('CONTROL: reached layer pixel staging');}});
 const data={success:true,width:4,height:4,layers:[],composite:'data:mock'};if(strong)data.sourceBytesSha256=A;
 const raster={success:true,layers:rasterLayers};if(rasterDigest!==undefined)raster.sourceBytesSha256=rasterDigest;
 const c=vm.createContext({Object,JSON,Array,Number,Math,String,Error,Promise,console:{log(){},error(){}},fetch:async(url,options)=>{requests.push({url,body:JSON.parse(options.body)});return {ok:url.includes('rasterize')?status===200:true,status:url.includes('rasterize')?status:200,json:async()=>url.includes('rasterize')?raster:data};}});
 vm.runInContext(`var window=this,_spbSourceLoadGeneration=1,_spbCommittedSourceGeneration=1,_spbCommittedSourcePath='A.psd',_spbCommittedSourceFingerprint='file-sha256:${B}',_spbSourceLoadPending=false,_spbCommittedSourceKind='layered',_psdPath='A.psd';window.SPBRenderReadiness={refresh:function(){}};window.SPBPSDImportSafety={flattenLayerTree:function(){return [{name:'one',rasterKey:'one',path:'one'}];},assessComposite:function(){throw Error('commit stage must not be reached');}};window.SPBDocumentCapability={chooseInitialLayer:function(){return null;}};async function _decodePSDSourceComposite(){return {canvas:{width:4,height:4},imageData:{width:4,height:4}};}async function _spbFingerprintText(){return '${'c'.repeat(64)}';}\n${declarations}\nthis.run=function(){return _doPSDImport('B.psd');};this.source=function(){return {path:_spbCommittedSourcePath,fingerprint:_spbCommittedSourceFingerprint,generation:_spbSourceLoadGeneration,committedGeneration:_spbCommittedSourceGeneration,loading:_spbSourceLoadPending,inFlight:window._spbPsdImportInFlight};};`,c);
 const before=c.source(),result=await c.run(),after=c.source();assert.equal(staged>0,expectedStage,id);assert.equal(after.path,before.path,id);assert.equal(after.fingerprint,before.fingerprint,id);assert.equal(after.loading,false,id);assert.equal(after.inFlight,false,id);assert.equal(result.ok,false,id);
 assert.equal(requests.length,2,id);assert.equal(requests[1].body.sourceBytesSha256,strong?A:undefined,id);
 if(!expectedStage)assert.match(result.error,status===200?/did not match the source byte fingerprint/:/HTTP 409/,id);
 rows.push({id,result:'PASS',strong,expectedDigestSent:requests[1].body.sourceBytesSha256||null,layerPixelStageReached:staged>0,priorSourceRetained:true,error:result.error});
}
(async()=>{await run('matching-strong-receipt-positive',true,A,true);await run('missing-receipt-refused',true,undefined,false);await run('different-receipt-refused',true,B,false);await run('empty-receipt-refused',true,'',false);await run('uppercase-receipt-refused',true,A.toUpperCase(),false);await run('backend-conflict-refused',true,undefined,false,409);await run('legacy-weak-backend-load-path-remains',false,undefined,true);assert.equal(rows.length,7);console.log(JSON.stringify({status:'PASS_WITH_LIMITS',cases:rows.length,source:file,sha256:crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex'),rows,limits:['Actual _doPSDImport and source transaction closures against controlled response/decode stubs.','Positive controls stop at layer pixel staging; not a completed import or native output claim.','No file/paint/provider writes.']},null,2));})().catch(e=>{console.error(e.stack||e);process.exitCode=1;});
