'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),crypto=require('node:crypto');
const root=path.resolve(__dirname,'..'), dPath='_easy_claude_work/ai14h_solid_conflict_successor/candidate/spb-pro-design.js', cPath='_easy_claude_work/ai14h_solid_conflict_successor/candidate/spb-pro-ai.js', runtime='_easy_claude_work/ai14h_generation3_runtime11', guardPath='_easy_claude_work/ai14h_final_source_identity_candidate/browser-file-v2/spb-pro-ai.js', oraclePath='_easy_claude_work/ai14h_solid_conflict_successor/fresh-oracle.json';
const read=p=>fs.readFileSync(path.join(root,p),'utf8'), sha=s=>crypto.createHash('sha256').update(s).digest('hex');
const design=read(dPath), controller=read(cPath), guard=read(guardPath), oracleBytes=read(oraclePath), oracle=JSON.parse(oracleBytes);
const supplementPath='_easy_claude_work/ai14h_solid_conflict_successor/supplement-oracle.json', supplementBytes=read(supplementPath), supplement=JSON.parse(supplementBytes);
assert.equal(sha(oracleBytes),'0fe5cb16c6701bea83ecb5b865de4e370538de419c0b4c6af501092376bc584d','frozen fresh oracle');
assert.equal(sha(supplementBytes),'ae8e5bafb113303edbc63df7d06e65bfc20a455cadea53a9ca87f6fcbbfec6f5','frozen supplement oracle');
assert.equal(sha(guard),'fb63f5906e1c9fc9d49150f571d64fde640e0a4630319c418fe4f9c2e7e5413a','strict source guard pin');
function extract(source,name){const start=source.indexOf(`function ${name}(`);assert(start>=0,`missing ${name}`);const brace=source.indexOf('{',start);let depth=0,q='',esc=false,line=false,block=false;for(let i=brace;i<source.length;i++){const c=source[i],n=source[i+1];if(line){if(c==='\n')line=false;continue;}if(block){if(c==='*'&&n==='/'){block=false;i++;}continue;}if(q){if(esc){esc=false;continue;}if(c==='\\'){esc=true;continue;}if(c===q)q='';continue;}if(c==='/'&&n==='/'){line=true;i++;continue;}if(c==='/'&&n==='*'){block=true;i++;continue;}if(c==='"'||c==="'"||c==='`'){q=c;continue;}if(c==='{')depth++;else if(c==='}'&&--depth===0)return source.slice(start,i+1);}throw Error('unterminated '+name);}
function loadD(){let w={};vm.runInNewContext(design,{window:w,console});return w.SpbProDesign;}
function harness(){
 const w={console,Promise,Date,Math,JSON,Object,Array,String,Number,RegExp,Error,Set,Map,parseInt,parseFloat,document:{body:{classList:{contains:()=>false}},getElementById:()=>null},zones:[],_psdLayers:[],paintImageData:null,selectedZoneIndex:-1,zoneSourceLayerIds:()=>[],_spbLayerRev:0,_spbOperationRevision:1,SpbProCar:{roles:()=>[],map:()=>null,missing:()=>[]},SpbAiLease:{internal:()=>true},SpbAI:{cached:()=>({configured:false})}};w.window=w;vm.createContext(w);const load=p=>vm.runInContext(read(p),w,{filename:p});load(runtime+'/js/spb-ai-instruction-intent-guard.js');load(runtime+'/js/spb-ai-complete-instruction-guard.js');
 w.D=loadD();w.E=null;w.AI=w.SpbAI;w.CAR=null;w._skipParts=false;w._absent={};w._offlineLast=null;w._advLast=null;w._advRejected=[];w._advDislikes=[];w._advUsed=null;w._busy=false;w._log=[];w._serial=0;w._forcedIdeaCols=null;w._envMemo=null;w._partMemoryWarmAttemptTicket=null;w.START_OVER_RE=/^start over$/i;w.NUM_FIX_RE=/^\s*$/;w.NOT_ELEM_RE=/$a/;let ticket={ok:true,id:1};const sinks=[];
 Object.assign(w,{normalizeOfflineInstruction:null,offlineInstructionPreflight:null,relativeBodyScopePreflight:null,operationCurrent:t=>!!t&&t.ok===true,operationCanceled:()=>({offline:true,queue:[],cancelled:true}),operationStart:()=>ticket,operationRelease(){},operationBind:r=>r,operationManager:()=>({ready(){},sameDocument:()=>true}),operationPublish:(_t,fn)=>fn(),operationTicket:()=>null,operationTools:()=>[],operationRevision:()=>1,elementRunCurrent:()=>true,contextualHelpReply:()=>null,selfHelpClaim:()=>null,selfHelpResult:r=>({offline:true,queue:[],howto:true,text:r.text}),advisorOwns:()=>false,advisorIntent:()=>null,editReply:(text)=>({offline:true,queue:[],route:"conflict-ask",text}),offlineMaterialPlan:()=>null,editPlan:()=>null,editYieldsToStack:()=>false,pendingNamedPartWarmTarget:()=>null,warm:()=>Promise.resolve(),hydratePartMemory(){},captureOriginal(){},render(){},intentSpecOnly:()=>false,offlineCoveredPartAsk:(text,proof)=>{sinks.push({kind:'covered',text,proof});return Promise.resolve({offline:true,queue:[],route:'covered',proof});},offlineLookAsk:(text,look)=>{sinks.push({kind:'look',text,look});return Promise.resolve({offline:true,queue:[],route:'look-clarification',text:'Please clarify the requested finish.'});},offlinePartAsk:(text,plan)=>{sinks.push({kind:'part',text,plan});return Promise.resolve({offline:true,queue:[],route:'part',plan});},offlineSpecAsk:(text,plan)=>{sinks.push({kind:'spec',text,plan});return Promise.resolve({offline:true,queue:[],route:'spec',plan});},offlineElementAsk:(text,plan)=>{sinks.push({kind:'element',text,plan});return Promise.resolve({offline:true,queue:[],route:'element',plan});},offlineIdeasAsk:()=>null,offlineCannot:()=>null,layerVisRequest:()=>null,offlineNumbersAsk:()=>null,offlineElemWrong:()=>null,offlineRefineAsk:()=>null,offlineStartOver:()=>({offline:true,queue:[]}),offlineUndo:()=>({offline:true,queue:[]}),offlineScopeReply:()=>({offline:true,queue:[],route:'scope-ask'}),preflightTeach:()=>({offline:true,queue:[],route:'teach-ask'}),offlineHowto:()=>null,operationFailure:()=>({offline:true,queue:[]}),offlineGaveUp:()=>true,offlineCanHandle:()=>true,logMiss(){},askCore:()=>Promise.resolve({offline:true,queue:[]})});
 w.normalizeOfflineInstruction=vm.runInContext('('+extract(controller,'normalizeOfflineInstruction')+')',w);w.offlineInstructionPreflight=vm.runInContext('('+extract(guard,'offlineInstructionPreflight')+')',w);w.relativeBodyScopePreflight=vm.runInContext('('+extract(guard,'relativeBodyScopePreflight')+')',w);for(const n of ['offlineAsk','offlineAskCore','askForTicket','ask'])vm.runInContext(extract(controller,n),w,{filename:'private:'+n});return{w,sinks};
}
(async()=>{const rows=[],issues=[];for(const c of oracle.cases){const {w,sinks}=harness(),D=w.D,result=await w.ask(c.request,{offline:true}),sink=sinks.at(-1)||null,plans=sink?.proof?.zones||sink?.plan?.zones||[],norm=plans.map(z=>({part:z.region?.part||'body',finish:z.finish,color:z.color,finishExplicit:z._meta?.finishExplicit})),row={id:c.id,expected:c.expected,route:result.route||sink?.kind||'guard-or-other',queue:(result.queue||[]).length,plans:norm,text:String(result.text||'').slice(0,220),sinks:sinks.length,directCompound:D.compoundPlan(c.request)};rows.push(row);
 if((result.queue||[]).length)issues.push(c.id+': queue nonempty');
 if(c.expected==='clarify-zero-plan'&&c.id!=='unknown-look-and-known-finish'){if(row.route!=='conflict-ask'||sinks.length||row.plans.length||!/(conflict|conflicting|which part)/i.test(row.text)||!/nothing was changed/i.test(row.text))issues.push(c.id+': should return truthful zero-plan clarification; '+JSON.stringify(row));if(row.directCompound)issues.push(c.id+': direct compound planner retained executable plan');}
 if(c.id==='unknown-look-and-known-finish'&&(row.queue||row.plans.length||!['look-clarification','guard-or-other'].includes(row.route)))issues.push(c.id+': unknown look must remain a no-queue clarification');
 if(c.expected==='actionable-distinct-parts'){if(!sink||!['covered','element','part','spec'].includes(sink.kind)||norm.length!==2||!norm.some(z=>z.part==='roof'&&z.finish==='base::f_soft_matte')||!norm.some(z=>z.part==='hood'&&z.finish==='base::f_chrome'))issues.push(c.id+': distinct-part finish assignments were lost or refused');}
 if(c.expected==='roof-color-only-keep-finish-and-hood-matte'){const cov=D.offlinePartCoverage(c.request);if(!sink||!['covered','element','part','spec'].includes(sink.kind)||norm.length!==2||!norm.some(z=>z.part==='roof'&&z.color==='#c8102e')||!norm.some(z=>z.part==='hood'&&z.color==='#1450b4'&&z.finish==='base::matte')||!cov||cov.finishExplicitByPart.roof!==false||cov.finishExplicitByPart.hood!==true)issues.push(c.id+': per-clause solid modifier/explicit finish semantics failed');}
 if(c.expected==='actionable-distinct-part-ops'){if(!sink||!['covered','element','part','spec'].includes(sink.kind)||norm.length<2||!norm.some(z=>z.part==='roof'&&z.finish==='base::f_clear_satin')||!norm.some(z=>z.part==='hood'&&z.color==='#c8102e'))issues.push(c.id+': distinct roof finish and hood paint no longer route safely');}
 if(c.expected==='read-only-help-zero-plan'){if(sink&&['covered','element','part','spec'].includes(sink.kind)||row.plans.length)issues.push(c.id+': quoted request entered executable plan');}
 if(c.expected==='no-change-zero-plan'){if(sink||row.plans.length||row.queue||!/will not make that change/i.test(row.text)||!/nothing was changed/i.test(row.text))issues.push(c.id+': prohibited request must be an explicit no-op');}
 }
 const supplementRows=[];
 for(const c of supplement.cases){const {w,sinks}=harness(),D=w.D,result=await w.ask(c.request,{offline:true}),sink=sinks.at(-1)||null,plans=sink?.proof?.zones||sink?.plan?.zones||[],norm=plans.map(z=>({part:z.region?.part||'body',finish:z.finish})),direct=D.compoundPlan(c.request),status=D.partFinishConflict(c.request),row={id:c.id,expected:c.expected,route:result.route||sink?.kind||'guard-or-other',queue:(result.queue||[]).length,zones:norm,text:String(result.text||'').slice(0,180),status:status&&status.kind,directZones:direct&&direct.zones.map(z=>({part:z.region?.part||'body',finish:z.finish}))};supplementRows.push(row);
  if(c.expected==='clarify-zero-plan'&&(!status||status.kind!=='conflict'||row.route!=='conflict-ask'||row.queue||sink||direct||!/nothing was changed/i.test(row.text)))issues.push(c.id+': long same-part conflict did not stop atomically');
  if(c.expected==='distinct-part-and-body-plan'&&status&&status.kind!=='explicit-body-part')issues.push(c.id+': explicit separate body and named part falsely flagged as conflict');
  if(c.expected==='distinct-part-and-body-plan'&&c.id==='explicit-body-plus-roof'&&(!direct||!direct.zones.some(z=>z.region.everything||z.region.paintable)&&!direct.zones.some(z=>z.region.part==='roof')))issues.push(c.id+': explicit whole-car plus roof request lost a requested scope');
  if(c.expected==='same-family-not-conflict'&&(status&&status.kind==='conflict'||row.queue||norm.some(z=>z.part==='body')))issues.push(c.id+': equivalent finish words caused conflict or body widening');
  if(c.expected==='read-only-zero-plan'&&(status&&status.kind!=='quoted'||row.queue||sink&&['covered','element','part','spec'].includes(sink.kind)))issues.push(c.id+': quoted query reached mutation');
  if(c.expected==='no-change-zero-plan'&&(status?.kind!=='prohibited'||row.queue||sink||direct||!/nothing was changed/i.test(row.text)))issues.push(c.id+': prohibition did not remain no-op');
 }
 const coreRows=[];
 for(const input of ['Make the roof matte and chrome.','Make only the roof chrome and matte.','Set the hood to satin, then mirror chrome.']){const {w,sinks}=harness(),r=await w.offlineAskCore(input,{offline:true,_spbOperation:{ok:true,id:2}}),row={input,route:r.route||'guard-or-other',queue:(r.queue||[]).length,sinks:sinks.length,text:r.text};coreRows.push(row);if(r.queue?.length||sinks.length||!/(conflict|conflicting)/i.test(String(r.text||''))||!/nothing was changed/i.test(String(r.text||'')))issues.push('offlineAskCore bypassed conflict clarification: '+input);}
 const conflicts=rows.filter(x=>x.expected==='clarify-zero-plan'), positives=rows.filter(x=>x.expected.startsWith('actionable')||x.expected==='roof-color-only-keep-finish-and-hood-matte');
 const report={status:issues.length?'FAIL_PRIVATE':'PASS_PRIVATE_WITH_LIMITS',oracle:{path:oraclePath,sha256:sha(oracleBytes),cases:oracle.cases.length},supplement:{path:supplementPath,sha256:sha(supplementBytes),cases:supplement.cases.length,rows:supplementRows},coreRouteChecks:coreRows,pins:{designPath:dPath,designSha256:sha(design),controllerPath:cPath,controllerSha256:sha(controller),guardPath,guardSha256:sha(guard)},counts:{cases:rows.length,supplementCases:supplementRows.length,coreCases:coreRows.length,conflictOrAmbiguousExpected:conflicts.length,conflictClarifications:conflicts.filter(r=>!r.sinks&&r.plans.length===0&&/(conflict|conflicting)/i.test(r.text)).length,positiveScopeControls:positives.length,providerCalls:0,nativeCalls:0,applyCalls:0},rows,issues,limits:['Evaluated actual pinned Design.compoundPlan(), partFinishConflict(), exported ask()/offlineAsk()/offlineAskCore() in a VM with offline edit sinks stubbed. The suite confirms routing, plans, copy and zero-queue guarantees, not applying pixels or live owner-proof behavior. Guard, source and oracle are read-only; private candidate only.']};const out=path.join(root,'_easy_claude_work/ai14h_solid_conflict_successor/route-review.json');fs.writeFileSync(out,JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report,null,2));if(issues.length)process.exitCode=1;
})().catch(e=>{console.error(e.stack||e);process.exitCode=1;});
