'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),vm=require('node:vm');
const root=path.resolve(__dirname,'..'),file=path.join(root,'_easy_claude_work/ai14h_w10_candidate/js/spb-pro-ai.before.js');
const EXPECTED='7986424F203A303172B19EABC1D4F5FD52DBC2E25DE6D87C444BADD1434261B2';
const ORACLE=Object.freeze([
 {id:'undo-beyond-capped-history',want:'exact per-entry snapshot works even when capped app history length does not grow'},
 {id:'restore-zone-id-order-selection-and-masks',want:'undo restores IDs/order/selected zone/region and spatial masks'},
 {id:'preserve-unrelated-later-zone-layer-edits',want:'later unrelated zone and layer metadata survive selective undo'},
 {id:'same-zone-later-manual-edit',want:'same-zone manual change is refused or preserved, not silently discarded'},
 {id:'undo-layer-pixel-buffer-edit',want:'layer pixel buffer changes have an exact inverse'},
 {id:'redo-refuses-manual-document-change',want:'redo guard notices subsequent zone change'},
 {id:'redo-refuses-source-change',want:'source-only identity change invalidates redo'},
 {id:'old-document-undo-redo-refused',want:'old-document entry cannot mutate a replacement document'},
 {id:'noop-entry-no-destructive-undo',want:'non-undoable/no-op entry cannot mutate state'},
 {id:'two-sequential-ai-edits-undo-lifo',want:'two message snapshots undo in last-in-first-out order'},
 {id:'partial-batch-undo-scope',want:'undo restores successful portion of partially applied batch'},
 {id:'exact-flag-source-guard-does-not-bypass-inverse',want:'exact snapshot path does not skip required layer pixel inverse'}
]);
assert.equal(crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex').toUpperCase(),EXPECTED,'frozen W10 source changed');
function extractFunction(src,name){const at=src.indexOf('function '+name+'(');assert(at>=0,name+' exists');const open=src.indexOf('{',at);let d=0,q=null,esc=false,line=false,block=false;for(let i=open;i<src.length;i++){const c=src[i],n=src[i+1];if(line){if(c==='\n')line=false;continue;}if(block){if(c==='*'&&n==='/'){block=false;i++;}continue;}if(q){if(esc)esc=false;else if(c==='\\')esc=true;else if(c===q)q=null;continue;}if(c==='/'&&n==='/'){line=true;i++;continue;}if(c==='/'&&n==='*'){block=true;i++;continue;}if(c==='"'||c==="'"||c==='`'){q=c;continue;}if(c==='{')d++;else if(c==='}'&&--d===0)return src.slice(at,i+1);}throw Error('unterminated '+name);}
const source=fs.readFileSync(file,'utf8');
const names=['ukOf','ukSet','maskPack','maskUnpack','maskSig','zoneSig','layerState','layerSame','applyLayerOps','undoSnapTake','undoSigNow','undoSeal','undoSameZones','undoZoneFrom','undoPushedSince','undoDropPushed','undoSameLayers','undoApply','undoRestore','redoLast','undoTrim','doUndo'];
const declarations=names.map(n=>extractFunction(source,n)).join('\n');
function makeApp(initial){
 const app={zones:initial.zones.map(copyZone),selectedZoneIndex:initial.selected||0,_psdLayers:(initial.layers||[]).map(x=>({...x,data:x.data?new Uint8Array(x.data):undefined})),zoneUndoStack:[],_layerUndoStack:[],undoHistoryPointer:0,_log:[],RECENT:[],_busy:false,_gen:0,_snapGen:0,_activeId:null,_ukSerial:0,sourceId:initial.sourceId||'doc-A',undoLayerCalls:0,undoZoneCalls:0,renderCalls:0};
 function copyZone(z){const o={...z};for(const k of ['regionMask','spatialMask','patternStrengthMap'])if(z[k])o[k]=new z[k].constructor(z[k]);return o;}
 const context={...app,console,ArrayBuffer,DataView,Uint8Array,Uint32Array,Math,JSON,Object,String,Number,isFinite,
   _cloneZoneState:(z)=>copyZone(z),renderZones:()=>{app.renderCalls++;},triggerPreviewRender:()=>{},_finishLayerVisibilityChange:()=>{},renderUndoHistoryPanel:()=>{},
   restorePartRegistryUndo:()=>{},undoLayerEdit:()=>{app.undoLayerCalls++;return true;},undoZoneChange:()=>{app.undoZoneCalls++;return true;},
   window:{pushZoneUndo:()=>{app.zoneUndoStack.push({app:true});}},render:()=>{},
   get zones(){return app.zones},set zones(v){app.zones=v},get selectedZoneIndex(){return app.selectedZoneIndex},set selectedZoneIndex(v){app.selectedZoneIndex=v},
   get _psdLayers(){return app._psdLayers},set _psdLayers(v){app._psdLayers=v},get zoneUndoStack(){return app.zoneUndoStack},set zoneUndoStack(v){app.zoneUndoStack=v},get _layerUndoStack(){return app._layerUndoStack},set _layerUndoStack(v){app._layerUndoStack=v},
   get undoHistoryPointer(){return app.undoHistoryPointer},set undoHistoryPointer(v){app.undoHistoryPointer=v},get _log(){return app._log},set _log(v){app._log=v},get RECENT(){return app.RECENT},set RECENT(v){app.RECENT=v},get _busy(){return app._busy},set _busy(v){app._busy=v},get _gen(){return app._gen},set _gen(v){app._gen=v},get _snapGen(){return app._snapGen},set _snapGen(v){app._snapGen=v},get _activeId(){return app._activeId},set _activeId(v){app._activeId=v}};
 vm.createContext(context);vm.runInContext(declarations+'\nthis.api={undoSnapTake:undoSnapTake,undoSeal:undoSeal,doUndo:doUndo,redoLast:redoLast,undoSigNow:undoSigNow,undoSameZones:undoSameZones,applyLayerOps:applyLayerOps};',context);
 app.ctx=context;app.api=context.api;return app;
}
function record(id,fn){try{const detail=fn();return{id,ok:true,...detail};}catch(e){return{id,ok:false,error:String(e&&e.stack||e).slice(0,700)};}}
function entry(app,request,before){const e={role:'ai',id:app._log.length+1,request,undoable:true,undone:false,undoSnap:before};app._log.push(e);app.api.undoSeal(e);return e;}
const findings=[];
findings.push(record('undo-beyond-capped-history',()=>{const a=makeApp({zones:[{id:'z1',name:'A',color:'blue',regionMask:new Uint8Array([1,0,1])}]});a.zoneUndoStack=Array.from({length:15},(_,i)=>({n:i}));const b=a.api.undoSnapTake();a.zones[0].color='red';a.zoneUndoStack.push({n:15});a.zoneUndoStack.shift();const e=entry(a,'red',b);a.api.doUndo(e);return{restored:a.zones[0].color==='blue',beforeDepth:15,afterDepth:a.zoneUndoStack.length,ownSnapshot:!!e.redoSnap};}));
findings.push(record('restore-zone-id-order-selection-and-masks',()=>{const a=makeApp({zones:[{id:'a',name:'A',color:'blue',regionMask:new Uint8Array([1,0]),spatialMask:new Uint8Array([0,1])},{id:'b',name:'B',color:'white',regionMask:new Uint8Array([0,1])}],selected:1});const b=a.api.undoSnapTake();a.zones.reverse();a.zones[0].regionMask[0]=1;a.zones[0].id='changed';a.selectedZoneIndex=0;const e=entry(a,'change',b);a.api.doUndo(e);return{ids:a.zones.map(z=>z.id),order:a.zones.map(z=>z.name),selected:a.zones[a.selectedZoneIndex].id,masks:Array.from(a.zones[0].regionMask),spatial:Array.from(a.zones[0].spatialMask)};}));
findings.push(record('preserve-unrelated-later-zone-layer-edits',()=>{const a=makeApp({zones:[{id:'a',name:'A',color:'blue'}],layers:[{id:'body',visible:true,opacity:255,blendMode:'source-over'}]});const b=a.api.undoSnapTake();a.zones[0].color='red';const e=entry(a,'red',b);a.zones.push({id:'manual',name:'Manual',color:'green'});a._psdLayers[0].visible=false;a.api.doUndo(e);return{aiColor:a.zones.find(z=>z.id==='a').color,manualZone:a.zones.some(z=>z.id==='manual'),manualLayerVisibility:a._psdLayers[0].visible};}));
findings.push(record('same-zone-later-manual-edit',()=>{const a=makeApp({zones:[{id:'a',name:'A',color:'blue',finish:'matte'}]});const b=a.api.undoSnapTake();a.zones[0].color='red';const e=entry(a,'red',b);a.zones[0].finish='chrome';a.api.doUndo(e);return{color:a.zones[0].color,finish:a.zones[0].finish,laterFinishPreserved:a.zones[0].finish==='chrome',aiRepaintUndone:a.zones[0].color==='blue',refused:!e.undone};}));
findings.push(record('undo-layer-pixel-buffer-edit',()=>{const a=makeApp({zones:[{id:'a',name:'A',color:'blue'}],layers:[{id:'raster',visible:true,opacity:255,blendMode:'source-over',data:new Uint8Array([1,2,3,4])}]});const b=a.api.undoSnapTake();a._layerUndoStack.push({pixelInverse:'oldbytes'});a._psdLayers[0].data[0]=99;const e=entry(a,'paint pixels',b);e.layerUndo=1;e._lPushed=[a._layerUndoStack[0]];a.api.doUndo(e);return{pixel:a._psdLayers[0].data[0],expected:1,appUndoCalls:a.undoLayerCalls,layerStackAfter:a._layerUndoStack.length,undoExact:e.undoFull};}));
findings.push(record('redo-refuses-manual-document-change',()=>{const a=makeApp({zones:[{id:'a',name:'A',color:'blue'}]});const b=a.api.undoSnapTake();a.zones[0].color='red';const e=entry(a,'red',b);a.api.doUndo(e);a.zones[0].finish='manual';const r=a.api.redoLast();return{redoRefused:r===null,finish:a.zones[0].finish};}));
findings.push(record('redo-refuses-source-change',()=>{const a=makeApp({zones:[{id:'a',name:'A',color:'blue'}],sourceId:'doc-A'});const b=a.api.undoSnapTake();a.zones[0].color='red';const e=entry(a,'red',b);a.api.doUndo(e);a.sourceId='doc-B';const r=a.api.redoLast();return{redoApplied:r!==null,sourceIdAfter:a.sourceId,color:a.zones[0].color,guardContainsSource:false};}));
findings.push(record('old-document-undo-redo-refused',()=>{const a=makeApp({zones:[{id:'same-id',name:'Zone',color:'blue'}],sourceId:'doc-A'});const b=a.api.undoSnapTake();a.zones[0].color='red';const e=entry(a,'AI edit',b);a.sourceId='doc-B';a.zones[0].color='green';a.api.doUndo(e);return{sourceId:a.sourceId,color:a.zones[0].color,entryMarkedUndone:e.undone,sourceIdentityInSnapshot:Object.prototype.hasOwnProperty.call(b,'source')};}));
findings.push(record('noop-entry-no-destructive-undo',()=>{const a=makeApp({zones:[{id:'a',name:'A',color:'blue'}]});const e={role:'ai',undoable:false,undone:false};a._log.push(e);const before=a.api.undoSnapTake();a.api.doUndo(e);return{unchanged:a.api.undoSameZones({zones:before.zones.map(s=>({k:s.k,sig:s.sig}))},a.api.undoSigNow()),undoable:e.undoable,undone:e.undone};}));
findings.push(record('two-sequential-ai-edits-undo-lifo',()=>{const a=makeApp({zones:[{id:'a',name:'A',color:'blue',finish:'matte'}]});let b=a.api.undoSnapTake();a.zones[0].color='red';const e1=entry(a,'red',b);b=a.api.undoSnapTake();a.zones[0].finish='chrome';const e2=entry(a,'chrome',b);a.api.doUndo(e2);const after2={color:a.zones[0].color,finish:a.zones[0].finish};a.api.doUndo(e1);return{afterSecondUndo:after2,final:{color:a.zones[0].color,finish:a.zones[0].finish}};}));
findings.push(record('partial-batch-undo-scope',()=>{const a=makeApp({zones:[{id:'a',name:'A',color:'blue'},{id:'b',name:'B',color:'white'}]});const b=a.api.undoSnapTake();a.zones[0].color='red';const e=entry(a,'partial batch',b);a.api.doUndo(e);return{firstRestored:a.zones[0].color==='blue',untouchedSecond:a.zones[1].color==='white',oneMessageStep:e.undone};}));
findings.push(record('exact-flag-source-guard-does-not-bypass-inverse',()=>{const a=makeApp({zones:[{id:'a',name:'A',color:'blue'}],layers:[{id:'r',visible:true,opacity:255,blendMode:'source-over',data:new Uint8Array([7])}]});const b=a.api.undoSnapTake();a._psdLayers[0].data[0]=8;const e=entry(a,'pixels',b);a.api.doUndo(e);return{exactRestoration:e.undoFull,pixelRestored:a._psdLayers[0].data[0]===7,exactPathBypassedLegacyLayerUndo:a.undoLayerCalls===0};}));
const layerApp=makeApp({zones:[{id:'a',name:'A',color:'blue'}],layers:[{id:'body',name:'Body',visible:true,opacity:255,blendMode:'source-over'}]});
layerApp.ctx.Z={quiet:fn=>fn(),findLayer:name=>layerApp._psdLayers.find(l=>l.name===name)};
layerApp.ctx.toggleLayerVisible=id=>{const l=layerApp._psdLayers.find(x=>x.id===id);if(l){l.visible=!l.visible;layerApp._layerUndoStack.push({kind:'visible',id});}};
layerApp.ctx.setLayerOpacity=(id,value)=>{const l=layerApp._psdLayers.find(x=>x.id===id);if(l){l.opacity=value;layerApp._layerUndoStack.push({kind:'opacity',id});}};
layerApp.ctx.setLayerBlendMode=(id,value)=>{const l=layerApp._psdLayers.find(x=>x.id===id);if(l){l.blendMode=value;layerApp._layerUndoStack.push({kind:'blend',id});}};
findings.push(record('actual-ai-layer-metadata-operation',()=>{const before=layerApp.api.undoSnapTake();const applied=layerApp.api.applyLayerOps([{layer:'Body',name:'Body',visible:false,opacity:120}]);const e=entry(layerApp,'hide and dim layer',before);e.layerUndo=applied.undoSteps;e._lPushed=layerApp._layerUndoStack.slice();layerApp.api.doUndo(e);return{appliedLines:applied.lines,metadataRestored:layerApp._psdLayers[0].visible===true&&layerApp._psdLayers[0].opacity===255,appHistoryPopped:layerApp._layerUndoStack.length===0,undoLayerFallbackCalls:layerApp.undoLayerCalls};}));
for(const f of findings)assert.equal(f.ok,true,`harness execution failed for ${f.id}: ${f.error}`);
console.log(JSON.stringify({status:'FINDINGS',frozenSourceSha256:EXPECTED,oracleCount:ORACLE.length,observations:findings,providerCalls:0,nativeCalls:0,browserCalls:0},null,2));
