'use strict';
// W48 candidate contract replays the frozen W41 Undo invariants plus three-way cases.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),vm=require('node:vm');
const root=path.resolve(__dirname,'..'),frozenFile=path.join(root,'_easy_claude_work/ai14h_w10_phase6_sources/js/spb-pro-ai.js'),file=path.join(root,'_easy_claude_work/ai14h_w48_candidate/candidate/js/spb-pro-ai.js');
const EXPECTED='5ECB313E66BA26B91020367C148D11227DA1385925E144A41DDEBD6940EA53EB';
const sourceBytes=fs.readFileSync(file),source=sourceBytes.toString('utf8'),sha=crypto.createHash('sha256').update(sourceBytes).digest('hex').toUpperCase();
assert.equal(crypto.createHash('sha256').update(fs.readFileSync(frozenFile)).digest('hex').toUpperCase(),EXPECTED,'pinned W10 source changed');
const ORACLE=Object.freeze([
 {id:'unchanged-fast-exact-undo',want:'unchanged AI after-state uses exact full restoration including IDs/order/selection and masks'},
 {id:'same-zone-manual-other-property-preserved',want:'AI repaint is undone while later manual finish on same zone survives'},
 {id:'same-zone-manual-same-property-preserved',want:'a later user value on the same AI-touched property is preserved, and partial result is explicit'},
 {id:'unrelated-zone-and-layer-change-preserved',want:'unrelated later zone and layer metadata remain untouched'},
 {id:'added-zone-unchanged-removed',want:'AI-added zone with no later edits is removed on undo'},
 {id:'added-zone-manually-modified-retained',want:'AI-added zone modified manually after the answer is retained'},
 {id:'deleted-zone-restored-without-id-collision',want:'AI-deleted zone returns at prior order only when its stable identity can be restored without duplicate IDs'},
 {id:'mask-three-way-signature-preservation',want:'AI mask change reverts only if current mask still matches sealed AI-after signature; later mask edit survives'},
 {id:'layer-visible-opacity-blend-three-way',want:'AI layer properties revert individually only while current value still equals sealed AI-after value'},
 {id:'partial-undo-honest-copy',want:'partial selective undo reports later manual edits kept, not blanket paint restored'},
 {id:'redo-after-partial-undo',want:'redo preserves the captured manual edits and existing exact two-step redo/undo behavior'},
 {id:'source-guard-and-no-extra-after-mask-copy',want:'operationEntryDocumentCurrent still refuses old document; after-state stores compact metadata/signatures, no second raw mask copy'}
]);
const frozenIds=ORACLE.map(x=>x.id);
assert.equal(ORACLE.length,12);
const W41_ORACLE=Object.freeze(['undo-beyond-capped-history','restore-zone-id-order-selection-and-masks','preserve-unrelated-later-zone-layer-edits','same-zone-later-manual-edit','undo-layer-pixel-buffer-edit','redo-refuses-manual-document-change','redo-refuses-source-change','old-document-undo-redo-refused','noop-entry-no-destructive-undo','two-sequential-ai-edits-undo-lifo','partial-batch-undo-scope','exact-flag-source-guard-does-not-bypass-inverse']);
function extractFunction(src,name){const at=src.indexOf('function '+name+'(');assert(at>=0,name+' exists');const open=src.indexOf('{',at);let d=0,q=null,esc=false,line=false,block=false;for(let i=open;i<src.length;i++){const c=src[i],n=src[i+1];if(line){if(c==='\n')line=false;continue;}if(block){if(c==='*'&&n==='/'){block=false;i++;}continue;}if(q){if(esc)esc=false;else if(c==='\\')esc=true;else if(c===q)q=null;continue;}if(c==='/'&&n==='/'){line=true;i++;continue;}if(c==='/'&&n==='*'){block=true;i++;continue;}if(c==='"'||c==="'"||c==='`'){q=c;continue;}if(c==='{')d++;else if(c==='}'&&--d===0)return src.slice(at,i+1);}throw Error('unterminated '+name);}
const names=['ukOf','ukSet','maskPack','maskUnpack','maskSig','undoMaskProof','zoneSig','layerState','layerSame','undoValueCopy','undoValueSame','undoSnapTake','undoSigNow','undoSeal','undoSameZones','undoZoneFrom','undoPushedSince','undoDropPushed','undoSameLayers','undoApply','undoRestore','redoLast','undoTrim','doUndo','offlineUndo'];
const declarations=names.map(n=>extractFunction(source,n)).join('\n');
function cloneValue(v){if(v==null||typeof v!=='object')return v;if(ArrayBuffer.isView(v))return new v.constructor(v);if(v instanceof ArrayBuffer)return v.slice(0);if(Array.isArray(v))return v.map(cloneValue);const o={};Object.keys(v).forEach(k=>o[k]=cloneValue(v[k]));return o;}
function makeApp(initial){
 const app={zones:(initial.zones||[]).map(cloneValue),selectedZoneIndex:initial.selected||0,_psdLayers:(initial.layers||[]).map(cloneValue),zoneUndoStack:[],_layerUndoStack:[],undoHistoryPointer:0,_log:[],RECENT:[],_busy:false,_gen:0,_snapGen:0,_activeId:null,_ukSerial:0,sourceId:'doc-A',current:true,_offlineLast:null,undoLayerCalls:0,undoZoneCalls:0,renderCalls:0};
 const context={...app,console,ArrayBuffer,DataView,Uint8Array,Uint32Array,Math,JSON,Object,String,Number,isFinite,operationEntryDocumentCurrent:e=>app.current,operationTicket:()=>({}),operationManager:()=>({sameDocument:()=>app.current}),
   _cloneZoneState:(z)=>cloneValue(z),renderZones:()=>{app.renderCalls++;},triggerPreviewRender:()=>{},_finishLayerVisibilityChange:()=>{},renderUndoHistoryPanel:()=>{},restorePartRegistryUndo:()=>{},undoLayerEdit:()=>{app.undoLayerCalls++;return true;},undoZoneChange:()=>{app.undoZoneCalls++;return true;},window:{pushZoneUndo:()=>app.zoneUndoStack.push({app:true})},render:()=>{},
   get zones(){return app.zones},set zones(v){app.zones=v},get selectedZoneIndex(){return app.selectedZoneIndex},set selectedZoneIndex(v){app.selectedZoneIndex=v},get _psdLayers(){return app._psdLayers},set _psdLayers(v){app._psdLayers=v},get zoneUndoStack(){return app.zoneUndoStack},set zoneUndoStack(v){app.zoneUndoStack=v},get _layerUndoStack(){return app._layerUndoStack},set _layerUndoStack(v){app._layerUndoStack=v},get undoHistoryPointer(){return app.undoHistoryPointer},set undoHistoryPointer(v){app.undoHistoryPointer=v},get _log(){return app._log},set _log(v){app._log=v},get RECENT(){return app.RECENT},set RECENT(v){app.RECENT=v},get _busy(){return app._busy},set _busy(v){app._busy=v},get _gen(){return app._gen},set _gen(v){app._gen=v},get _snapGen(){return app._snapGen},set _snapGen(v){app._snapGen=v},get _activeId(){return app._activeId},set _activeId(v){app._activeId=v}};
 vm.createContext(context);vm.runInContext(declarations+'\nthis.api={undoSnapTake:undoSnapTake,undoSeal:undoSeal,doUndo:doUndo,redoLast:redoLast,undoSigNow:undoSigNow,undoSameZones:undoSameZones,undoApply:undoApply,offlineUndo:offlineUndo};',context);app.ctx=context;app.api=context.api;return app;
}
function entry(app,request,before){const e={role:'ai',id:app._log.length+1,request,undoable:true,undone:false,undoSnap:before};app._log.push(e);app.api.undoSeal(e);return e;}
const observations=[];function record(id,fn){const result=fn();observations.push({id,...result});}
record('exact-fast-restore-order-selection-masks',()=>{const a=makeApp({zones:[{id:'a',name:'A',color:'blue',regionMask:new Uint8Array([1,0]),spatialMask:new Uint8Array([0,1])},{id:'b',name:'B',color:'white'}],selected:1});const b=a.api.undoSnapTake();a.zones[0].color='red';const e=entry(a,'red',b);a.api.doUndo(e);assert.deepEqual(a.zones.map(z=>z.id),['a','b']);assert.equal(a.zones[a.selectedZoneIndex].id,'b');assert.deepEqual(Array.from(a.zones[0].regionMask),[1,0]);assert.deepEqual(Array.from(a.zones[0].spatialMask),[0,1]);assert.equal(e.undoFull,true);return{passed:true,undoFull:e.undoFull};});
record('same-zone-manual-other-property-preserved',()=>{const a=makeApp({zones:[{id:'a',name:'A',color:'blue',finish:'matte'}]});const b=a.api.undoSnapTake();a.zones[0].color='red';const e=entry(a,'red',b);a.zones[0].finish='chrome';a.api.doUndo(e);assert.equal(a.zones[0].color,'blue');assert.equal(a.zones[0].finish,'chrome');assert.equal(e.undoPartial,true);return{passed:true,partial:e.undoPartial};});
record('same-zone-manual-same-property-preserved',()=>{const a=makeApp({zones:[{id:'a',name:'A',color:'blue'}]});const b=a.api.undoSnapTake();a.zones[0].color='red';const e=entry(a,'red',b);a.zones[0].color='green';a.api.doUndo(e);assert.equal(a.zones[0].color,'green');assert.equal(e.undoPartial,true);return{passed:true,color:a.zones[0].color,partial:e.undoPartial};});
record('unrelated-zone-and-layer-survive',()=>{const a=makeApp({zones:[{id:'a',color:'blue'}],layers:[{id:'L',visible:true,opacity:255,blendMode:'source-over'}]});const b=a.api.undoSnapTake();a.zones[0].color='red';const e=entry(a,'red',b);a.zones.push({id:'manual',color:'green'});a._psdLayers[0].visible=false;a.api.doUndo(e);assert.equal(a.zones[0].color,'blue');assert(a.zones.some(z=>z.id==='manual'));assert.equal(a._psdLayers[0].visible,false);return{passed:true};});
record('added-zone-unchanged-removed',()=>{const a=makeApp({zones:[{id:'a',color:'blue'}]});const b=a.api.undoSnapTake();a.zones.push({id:'new',color:'red'});const e=entry(a,'add',b);a.api.doUndo(e);assert.equal(a.zones.length,1);return{passed:true};});
record('added-zone-manual-modification-retained',()=>{const a=makeApp({zones:[{id:'a',color:'blue'}]});const b=a.api.undoSnapTake();a.zones.push({id:'new',color:'red'});const e=entry(a,'add',b);a.zones[1].finish='manual';a.api.doUndo(e);assert.equal(a.zones.length,2);assert.equal(a.zones[1].finish,'manual');assert.equal(e.undoPartial,true);return{passed:true,partial:e.undoPartial};});
record('deleted-zone-restored-without-id-collision',()=>{const a=makeApp({zones:[{id:'same',name:'old',color:'blue'},{id:'other',color:'white'}]});const b=a.api.undoSnapTake();a.zones.shift();const e=entry(a,'delete',b);a.zones.unshift({id:'same',name:'manual',color:'green'});a.api.doUndo(e);assert.equal(a.zones.filter(z=>z.id==='same').length,1);assert.equal(a.zones[0].name,'manual');assert.equal(e.undoPartial,true);return{passed:true,ids:a.zones.map(z=>z.id)};});
record('mask-three-way-manual-signature-preserved',()=>{const a=makeApp({zones:[{id:'a',color:'blue',regionMask:new Uint8Array([1,0,0])}]});const b=a.api.undoSnapTake();a.zones[0].color='red';a.zones[0].regionMask=new Uint8Array([1,1,0]);const e=entry(a,'mask',b);a.zones[0].regionMask[2]=1; // A later manual edit occurs after the AI-after seal.
 a.api.doUndo(e);assert.equal(a.zones[0].color,'blue');assert.deepEqual(Array.from(a.zones[0].regionMask),[1,1,1]);assert.equal(e.undoPartial,true);return{passed:true,mask:Array.from(a.zones[0].regionMask)};});
record('full-mask-proof-catches-unsampled-later-pixel',()=>{const prior=new Uint8Array(300001),a=makeApp({zones:[{id:'a',color:'blue',regionMask:prior}]});const b=a.api.undoSnapTake();a.zones[0].color='red';a.zones[0].regionMask[7]=1;const e=entry(a,'large mask',b);a.zones[0].regionMask[8]=1;assert.equal(a.api.undoSameZones(e.undoAfter,a.api.undoSigNow()),false);a.api.doUndo(e);assert.equal(a.zones[0].color,'blue');assert.equal(a.zones[0].regionMask[7],1);assert.equal(a.zones[0].regionMask[8],1);assert.equal(e.undoPartial,true);return{passed:true,keptLaterPixel:8,aiMaskRetainedConservatively:7};});
record('layer-properties-three-way',()=>{const a=makeApp({zones:[{id:'a',color:'blue'}],layers:[{id:'L',visible:true,opacity:255,blendMode:'source-over'}]});const b=a.api.undoSnapTake();a._psdLayers[0].visible=false;a._psdLayers[0].opacity=120;const e=entry(a,'layer',b);a._psdLayers[0].opacity=80;a._psdLayers[0].blendMode='multiply';a.api.doUndo(e);assert.equal(a._psdLayers[0].visible,true);assert.equal(a._psdLayers[0].opacity,80);assert.equal(a._psdLayers[0].blendMode,'multiply');assert.equal(e.undoPartial,true);return{passed:true,visible:a._psdLayers[0].visible,opacity:a._psdLayers[0].opacity,blend:a._psdLayers[0].blendMode};});
record('partial-undo-copy-honest',()=>{const a=makeApp({zones:[{id:'a',color:'blue',finish:'matte'}]});const b=a.api.undoSnapTake();a.zones[0].color='red';const e=entry(a,'red',b);a.zones[0].finish='chrome';const r=a.api.offlineUndo();assert(e.undoPartial);assert(r.text.includes('later manual edits'));return{passed:true,copy:r.text};});
record('redo-after-partial-retains-manual',()=>{const a=makeApp({zones:[{id:'a',color:'blue',finish:'matte'}]});const b=a.api.undoSnapTake();a.zones[0].color='red';const e=entry(a,'red',b);a.zones[0].finish='chrome';a.api.doUndo(e);const partial={color:a.zones[0].color,finish:a.zones[0].finish};assert.equal(a.api.redoLast(),'red');assert.equal(a.zones[0].color,'red');assert.equal(a.zones[0].finish,'chrome');assert.equal(e.undoPartial,false);return{passed:true,afterUndo:partial,afterRedo:{color:a.zones[0].color,finish:a.zones[0].finish}};});
record('old-document-source-guard',()=>{const a=makeApp({zones:[{id:'a',color:'blue'}]});const b=a.api.undoSnapTake();a.zones[0].color='red';const e=entry(a,'red',b);a.current=false;const ok=a.api.doUndo(e);assert.equal(ok,false);assert.equal(a.zones[0].color,'red');assert.equal(e.undone,false);assert(extractFunction(source,'doUndo').includes('operationEntryDocumentCurrent(entry)'));return{passed:true,refused:true};});
record('after-state-has-no-raw-mask-copy',()=>{const a=makeApp({zones:[{id:'a',color:'blue',regionMask:new Uint8Array([1,0])}]});const b=a.api.undoSnapTake();a.zones[0].color='red';const e=entry(a,'red',b);const z=e.undoAfter.zones[0];assert.equal(typeof z.masks.regionMask,'string');assert.equal(z.masks.spatialMask,'-');assert.equal(z.masks.patternStrengthMap,'-');assert.equal(Object.hasOwn(z,'regionMask'),false);return{passed:true,maskSigOnly:true};});
record('layer-change-normal-and-two-step-undo',()=>{const a=makeApp({zones:[{id:'a',color:'blue',finish:'matte'}]});let b=a.api.undoSnapTake();a.zones[0].color='red';const e1=entry(a,'red',b);b=a.api.undoSnapTake();a.zones[0].finish='chrome';const e2=entry(a,'chrome',b);a.api.doUndo(e2);assert.equal(a.zones[0].finish,'matte');a.api.doUndo(e1);assert.equal(a.zones[0].color,'blue');assert.equal(a.zones[0].finish,'matte');return{passed:true};});
record('W41-capped-history-invariant',()=>{const a=makeApp({zones:[{id:'a',color:'blue'}]});a.zoneUndoStack=Array.from({length:15},(_,i)=>({i}));const b=a.api.undoSnapTake();a.zones[0].color='red';const e=entry(a,'red',b);a.zoneUndoStack.push({i:15});a.zoneUndoStack.shift();a.api.doUndo(e);assert.equal(a.zones[0].color,'blue');assert.equal(a.zoneUndoStack.length,15);assert(e.redoSnap);return{passed:true};});
record('W41-redo-refuses-manual-and-source-changes',()=>{const a=makeApp({zones:[{id:'a',color:'blue'}]});const b=a.api.undoSnapTake();a.zones[0].color='red';const e=entry(a,'red',b);a.api.doUndo(e);a.zones[0].finish='manual';assert.equal(a.api.redoLast(),null);const c=makeApp({zones:[{id:'b',color:'white'}]});const cb=c.api.undoSnapTake();c.zones[0].color='green';entry(c,'green',cb);c.api.doUndo(c._log[0]);c.current=false;assert.equal(c.api.redoLast(),null);return{passed:true};});
record('W41-noop-entry-does-not-mutate',()=>{const a=makeApp({zones:[{id:'a',color:'blue'}]});const e={role:'ai',undoable:false,undone:false};a._log.push(e);assert.equal(a.api.doUndo(e),false);assert.equal(a.zones[0].color,'blue');return{passed:true};});
record('W41-partial-batch-restores-only-ai-zone',()=>{const a=makeApp({zones:[{id:'a',color:'blue'},{id:'b',color:'white'}]});const b=a.api.undoSnapTake();a.zones[0].color='red';const e=entry(a,'partial',b);a.api.doUndo(e);assert.equal(a.zones[0].color,'blue');assert.equal(a.zones[1].color,'white');return{passed:true};});
assert.equal(observations.length,19);assert.equal(frozenIds.length,12);assert.equal(W41_ORACLE.length,12);
const report={status:'CANDIDATE_PASS',utc:new Date().toISOString(),frozenSource:{path:'_easy_claude_work/ai14h_w10_phase6_sources/js/spb-pro-ai.js',sha256:EXPECTED},candidate:{path:file,sha256:sha,installed:false},frozenW48Oracle:{count:frozenIds.length,ids:frozenIds},w41Oracle:{count:W41_ORACLE.length,ids:W41_ORACLE,layerPixelCases:'counterfactual only: the exercised AI layer route applies visibility/opacity/blend metadata; no AI pixel-buffer operation is claimed'},observations,counts:{passed:observations.length,total:observations.length,providerCalls:0,nativeCalls:0},limits:['Actual Undo helpers run in an isolated VM with mocked application arrays and render callbacks.','Three-way mask proofs scan all mask values into compact dual rolling signatures; signatures add O(total mask size) work at snapshot/seal/undo checks. Browser-scale latency was not measured.','Native canvas/zone renderer, browser UI, and pixel-layer painting were not run; layer pixel edits remain outside the exercised AI metadata-change route.']};
fs.writeFileSync(path.join(root,'docs/handoff_reports/AI_HELPER_14H_UNDO_W48_THREE_WAY_CANDIDATE_2026-10-03.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({status:report.status,passed:observations.length,total:observations.length,sha256:sha,observations:observations.map(x=>({id:x.id,passed:x.passed}))},null,2));










