'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),crypto=require('node:crypto');
const root=path.resolve(__dirname,'..'), pin='_easy_claude_work/ai14h_w113_candidate/', integration='_easy_claude_work/ai14h_w113_candidate/';
const paths={
 pro:integration+'spb-pro-ai.js', design:integration+'spb-pro-design.js', edit:integration+'spb-pro-edit.js', materials:integration+'spb-ai-material-controls.js', guard:pin+'spb-ai-complete-instruction-guard.js', selfhelp:integration+'spb-self-help.js', receipt:integration+'spb-ai-receipt-explainer.js', operation:pin+'spb-ai-operation.js', lease:pin+'spb-ai-lease.js', intentGuard:integration+'spb-ai-instruction-intent-guard.js', oracle:'_easy_claude_work/ai14h_w114_review/fresh-oracle.json'
};
const src={}; for(const [k,p] of Object.entries(paths)) src[k]=fs.readFileSync(path.join(root,p),'utf8');
const sha=s=>crypto.createHash('sha256').update(s).digest('hex').toUpperCase();
const expected={pro:'9B05B98526687D18E2D6FB9E06A8FB7B5CE686ED5E98FE9B7EED14C687C90DB4',selfhelp:'D1A76C2A5B8616133F8226602D43245BFC7DCC2B99B6BBEDEA68AF0641A2D6BE',receipt:'3CB4CCE4513FDC1E70A54156A7FDC9F98CE35605FDB33ADE1F5C66F24F8542A9',intentGuard:'3267DC263CF85BCB34B55588997ACBA737F4A47E7BDDE490FACE4D9D6271FB60',design:'4648DE3231015497CC9FF816612A542097A1AD14038A7210753F6CDBFD88D832',edit:'7D063444021F8F4144B96130800BADFE62741CDEFC9104417F3E99AF65270767',materials:'30B18516A3F13DD7854F6EF36FDF5EB7A37985537E63C4C6405FEFA690C6BAEC',guard:'BA0AF1F9E217695ED733DDE81C8DEC1A735DD1F052E8C06B3098866D392A551C',operation:'47587A1A53A35CE7E58825BAC864BD75C2421D26C19791957F57BB199A7000C6',lease:'DE276372A763310EC051DB141FCB1D601E11DBF193843E2B21A405226F782134'};
for(const [k,h] of Object.entries(expected)) assert.equal(sha(src[k]),h,k+' pinned bytes');
function extract(source,name){const start=source.indexOf(`function ${name}(`);assert(start>=0,`function ${name} exists`);if(name==='selfHelpClaim'){const end=source.indexOf('function selfHelpResult(',start);assert(end>start);return source.slice(start,end).trim();}const brace=source.indexOf('{',start);let depth=0,q=null,line=false,block=false,esc=false;for(let i=brace;i<source.length;i++){const c=source[i],n=source[i+1];if(line){if(c==='\n')line=false;continue;}if(block){if(c==='*'&&n==='/'){block=false;i++;}continue;}if(q){if(esc){esc=false;continue;}if(c==='\\'){esc=true;continue;}if(c===q)q=null;continue;}if(c==='/'&&n==='/'){line=true;i++;continue;}if(c==='/'&&n==='*'){block=true;i++;continue;}if(c==='"'||c==="'"||c==='`'){q=c;continue;}if(c==='{')depth++;if(c==='}'&&--depth===0)return source.slice(start,i+1);}throw Error('unterminated '+name);}
function extractSend(source){const start=source.indexOf('function send(text, o)'),end=source.indexOf('function mergeMaskUndo(',start);assert(start>=0&&end>start);return source.slice(start,end).trim();}
function route(text,pro,intent,guardSrc=src.intentGuard,core=false,sourceLess=false){
 const queued=[], env={palette:[{hex:'#111111',share_pct:42},{hex:'#00b8d4',share_pct:27},{hex:'#168a45',share_pct:10}],layers:[],zoneColours:[]};
 const fixtureZones=sourceLess?[]:[{id:'roof-zone',name:'Roof solid green',base:'base::gloss',finish:'f_gloss',baseColorMode:'solid',baseColor:'#1f8a3b',baseColorStrength:1,baseStrength:1,regionMask:new Uint8Array(64),sourceLayers:['paint']}];
 const w={console,Promise,document:{body:{classList:{contains:()=>false}}},zones:fixtureZones,_psdLayers:sourceLess?[]:[{id:'source',name:'Source image',img:{},visible:true},{id:'paint',name:'Car Paint',img:{},visible:true}],paintImageData:null,selectedZoneIndex:0,zoneSourceLayerIds:z=>z.sourceLayers||[],_spbLayerRev:0};if(sourceLess)w.SPBSourceLoadTransaction={isLoading:()=>false,isCommitted:()=>false,getGeneration:()=>4,getCommittedGeneration:()=>3,getCommittedPath:()=>'',getCommittedFingerprint:()=>''};w.window=w;w.SpbProCar={roles:()=>[],map:()=>null,missing:()=>[]};vm.createContext(w);for(const k of ['design','edit','materials','guard','selfhelp','receipt'])if(src[k])vm.runInContext(src[k],w,{filename:paths[k]});if(intent)vm.runInContext(guardSrc,w,{filename:paths.intentGuard});
 const D=w.SpbProDesign,E=w.SpbProEdit;
 const ctx={D,E,window:w,console,Promise,JSON,Object,Array,String,Number,Math,RegExp,Error,Uint8Array,Date,AI:{cached:()=>({configured:false})},_log:[],_panel:null,_pendingCard:null,_busy:false,_progress:'',_progressTick:null,_skipParts:true,_absent:{},CAR:{missing:()=>[],layoutSig:()=>'',hasParts:()=>!sourceLess},zones:fixtureZones,_editReg:{},_editRegPendingBefore:{},_editRegSig:'car-a',START_OVER_RE:/^\s*(?:start over|new design)\b/i,TEACH_RE:/^teach/i,QUESTION_RE:/\?\s*$/,CHECK_AGAIN_RE:/$a/,operationCurrent:t=>!!t&&t.ok===true,operationCanceled:()=>({cancelled:true}),operationRelease(){},operationPublish:(t,fn)=>fn(),operationTools:ts=>ts,operationRefreshDocument(){},elementRunCurrent:()=>true,elementPaintChangedResult:()=>({cancelled:true}),elemCurrentCard:()=>null,elementPaintSig:()=>'',elementRunIdentity:()=>null,elemReplyAction:()=>null,elemOwnsText:()=>false,rshotGrab(){},complaintChip:()=>false,complaintOf:()=>null,kitAsk:()=>false,supportClass:()=>null,supportSend:()=>false,offlineHowtoPeek:()=>null,editPlan:t=>E.plan(t,env),advisorOwns:()=>false,captureOriginal(){},intentSpecOnly:()=>false,editYieldsToStack:()=>false,editEnv:()=>env,advisorIntent:()=>null,offlineIdeas:()=>null,_offlineLast:null,_forcedIdeaCols:null,_reqText:'',_specOnlyReq:false,offlineCannot:()=>null,layerVisRequest:()=>null,NUM_FIX_RE:/$a/,NOT_ELEM_RE:/$a/,offlineLookAsk(){},offlineSpecAsk(){},offlinePartAsk:null,offlineElementAsk(){},offlineStartOver(){},offlineUndo(){},offlineHowto:()=>null,offlineScopeReply:()=>({offline:true,text:'Nothing was changed. Name one exact supported part.',queue:[]}),render(){},warm:()=>Promise.resolve(),markPartFollowupQueue(){},prepEnv:()=>Promise.resolve(env),resolveLook:()=>Promise.resolve(null),elementKinds:()=>[],exclTargets:()=>[],editOverlapNote:()=>'',explainPlan:p=>'test explanation',offlineHelp:(q,o)=>Promise.resolve({text:'guidance'}),partRegionKey:r=>JSON.stringify(r||{}),editKey:x=>x,editPlural:x=>x,currentPartOwnerVerifiedForRegion:()=>false,explicitCurrentPaintRequest:()=>false,unprovedCurrentPaintPartAdd:()=>false,intentGuardResult:null,finish(){},makeReport:()=>'',
 editOverlapKinds:()=>[],exclNotes:()=>[],_elemCache:null,_elemOk:{},_taughtNow:{},editReply:(text,chips,opts)=>({offline:true,text,queue:(opts&&opts.queue)||[],tools:(opts&&opts.tools)||[]}),offlineRefineAsk(){},selfHelpResult:x=>x,
 operationRefreshDocument(){},makeTools(){return [{name:'add_zone',handler(spec){queued.push({kind:'add',spec:JSON.parse(JSON.stringify(spec))});return {region_check:{share_pct:35}};}},{name:'edit_zone',handler(args){queued.push({kind:'edit',args:JSON.parse(JSON.stringify(args))});return {};}}];},queueEditZones(kind,spec,args,opts){queued.push({kind,spec,args,opts});return Promise.resolve({ok:true});},queueEdit(){queued.push({kind:'edit'});return Promise.resolve({ok:true});},scopedPartProofAt:()=>null,scopedPartProofMatches:()=>false,partOwnerCurrent:()=>false,carSig:()=>'car-a',scopedPartSourceNow:()=>null,operationDocument:()=>({ok:true}),operationAcquire:()=>({ok:true,collection:1}),operationResultCurrent:()=>true,operationRelease(){},_spbOperation:null};
 vm.createContext(ctx);const names=['partRegionKey','editKey','editPlural','hasPriorPartIdentity','currentPartZoneOwners','scopedPartProofCurrent','currentPartOwnerVerifiedForRegion','explicitCurrentPaintRequest','unprovedCurrentPaintPartAdd','relativeBodyScopePreflight','offlineRevert','selfHelpClaim','selfHelpResult','unexecutedSuggestionReply','contextualHelpReply','offlineInstructionPreflight','offlineMaterialPlan','offlineMaterialAsk','offlinePartAsk','offlineCoveredPartAsk','offlineEditAsk','offlineAskCore','offlineAsk','queueEditZones'];
 if(pro.includes('function normalizeOfflineInstruction('))vm.runInContext(extract(pro,'normalizeOfflineInstruction'),ctx);else ctx.normalizeOfflineInstruction=x=>String(x||'');
 for(const n of names){try{vm.runInContext(extract(pro,n),ctx);}catch(e){if(n==='hasPriorPartIdentity'&&!pro.includes('function hasPriorPartIdentity('))continue;throw e;}}
 if(pro.includes('function send(text, o)'))vm.runInContext(extractSend(pro),ctx);
 return Promise.resolve((core?ctx.offlineAskCore:ctx.offlineAsk)(text,{_spbOperation:{ok:true,collection:1},noAdvisor:true})).then(result=>({result,queued,ctx,D,E,window:w}));
}
(async()=>{
 const oracle=JSON.parse(src.oracle);assert.equal(oracle.case_count||oracle.caseCount||oracle.cases.length,12);const rows=[],issues=[];
 const directIds=new Set(['polite-can-make','polite-could-make','polite-would-make','direct-imperative-control']);
 for(const c of oracle.cases){
  for(const mode of ['offlineAsk','offlineAskCore']){
   const got=await route(c.input,src.pro,true,src.intentGuard,mode==='offlineAskCore');const text=String(got.result?.text||'');
   rows.push({id:c.id,route:mode,queue:got.queued.length,howto:!!got.result?.howto,selfHelp:got.result?.selfHelp||null,reply:text.slice(0,440)});
   if(!directIds.has(c.id)&&got.queued.length!==0)issues.push(c.id+'/'+mode+': informational request queued mutation');
   if(directIds.has(c.id)&&c.id!=='polite-can-make'&&got.queued.length===0)issues.push(c.id+'/'+mode+': direct imperative was not routed to a queue');
   if(c.id==='polite-can-make'&&(got.result?.howto||got.result?.selfHelp))issues.push(c.id+'/'+mode+': direct polite request was diverted into help');
  }
  const sent=await route(c.input,src.pro,true,src.intentGuard);const finishes=[];let asks=0;
  sent.ctx.finish=(...args)=>finishes.push(args);sent.ctx.ask=(text,opts)=>{asks++;return sent.ctx.offlineAsk(text,opts||{noAdvisor:true});};
  await sent.ctx.send(c.input);const sendText=String(finishes[0]?.[0]?.text||finishes[0]?.[0]||'');
  rows.push({id:c.id,route:'send',queue:sent.queued.length,asks,finishes:finishes.length,reply:sendText.slice(0,440)});
  if(!directIds.has(c.id)&&sent.queued.length!==0)issues.push(c.id+'/send: informational request queued mutation');
  if(directIds.has(c.id)&&c.id!=='polite-can-make'&&sent.queued.length===0)issues.push(c.id+'/send: direct imperative did not reach explicit action path');
  if(c.id==='polite-can-make'&&sent.result?.howto)issues.push(c.id+'/send: direct polite request was diverted into help');
 }
 const noSourceText='How do I save my paint project and reopen it later';
 const noSourceAsk=await route(noSourceText,src.pro,true,src.intentGuard,false,true), noSourceAskText=String(noSourceAsk.result?.text||'');
 if(noSourceAsk.queued.length||!/Save \/ Open/i.test(noSourceAskText))issues.push('source-less/offlineAsk: setup guidance unavailable or queued mutation');
 const noSourceCore=await route(noSourceText,src.pro,true,src.intentGuard,true,true), noSourceCoreText=String(noSourceCore.result?.text||'');
 if(noSourceCore.queued.length||!/Save \/ Open/i.test(noSourceCoreText))issues.push('source-less/offlineAskCore: setup guidance unavailable or queued mutation');
 const noSourceSend=await route(noSourceText,src.pro,true,src.intentGuard,false,true), noSourceFinishes=[];let noSourceAsks=0;
 noSourceSend.ctx.finish=(...args)=>noSourceFinishes.push(args);noSourceSend.ctx.ask=()=>{noSourceAsks++;return Promise.resolve({offline:true,text:'unexpected ask',queue:[]});};await noSourceSend.ctx.send(noSourceText);
 if(noSourceSend.queued.length||noSourceAsks!==0||noSourceFinishes.length!==1)issues.push('source-less/send: setup guidance did not finish safely without an ask or mutation');
 const sourceLess={offlineAsk:{queue:noSourceAsk.queued.length,hasSaveGuidance:/Save \/ Open/i.test(noSourceAskText),reply:noSourceAskText.slice(0,320)},offlineAskCore:{queue:noSourceCore.queued.length,hasSaveGuidance:/Save \/ Open/i.test(noSourceCoreText),reply:noSourceCoreText.slice(0,320)},send:{queue:noSourceSend.queued.length,asks:noSourceAsks,finishes:noSourceFinishes.length,uncommittedSource:true}};
 const byKey=Object.fromEntries(rows.map(r=>[r.id+'/'+r.route,r]));
 for(const mode of ['offlineAsk','offlineAskCore']){
  const pixels=byKey['what-saved/'+mode]?.reply||'';if(!/pixel payload|pixel data|pixels/i.test(pixels))issues.push('what-saved/'+mode+': answer omits whether current layer pixels are embedded');
  if(/bundle the original PSD/i.test(pixels)&&!/does not bundle/i.test(pixels))issues.push('what-saved/'+mode+': answer may imply the original PSD is bundled');
  const applied=byKey['can-i-see-applied/'+mode]?.reply||'';if(!/verified apply receipt|applied-change entry/i.test(applied))issues.push('can-i-see-applied/'+mode+': no current-receipt guidance supplied');
  const undo=byKey['where-undo/'+mode]?.reply||'';if(!/Ctrl\+Z|Undo button|Undo History/i.test(undo)||/do not see a current verified apply receipt/i.test(undo))issues.push('where-undo/'+mode+': Undo location question is misclassified as receipt status');
  const keep=byKey['how-keep-paint/'+mode]?.reply||'';if(!/original imported paint image|does not retain an authored solid-color hex/i.test(keep))issues.push('how-keep-paint/'+mode+': guidance does not distinguish Source Paint from current authored color');
  const draft=byKey['voice-howto-current/'+mode]?.reply||'';if(!/suggestion or preview is not proof|current verified receipt matching/i.test(draft))issues.push('voice-howto-current/'+mode+': no target/look-bound draft-versus-applied caveat');
  const suggestion=byKey['repeat-suggestion/'+mode]?.reply||'';if(/was applied|has been applied/i.test(suggestion)&&!/cannot determine whether .* was applied/i.test(suggestion))issues.push('repeat-suggestion/'+mode+': prior suggestion described as applied without receipt');
 }
 const result={work_item:'W114 independent W113 voice-help routing review',status:issues.length?'REVIEW_GAPS':'PASS_WITH_LIMITS',candidateReviewCompleted:true,oracle:{path:paths.oracle,sha256:sha(src.oracle),cases:oracle.cases.length,frozenBeforeW113ImplementationRead:true},sources:{controller:pathHash(paths.pro),selfHelp:pathHash(paths.selfhelp),receiptExplainer:pathHash(paths.receipt),guard:pathHash(paths.intentGuard),design:pathHash(paths.design),edit:pathHash(paths.edit)},rows,sourceLessEvidence:sourceLess,reviewFindings:issues,semanticObservations:{savedProjectPixels:Object.fromEntries(['offlineAsk','offlineAskCore','send'].map(r=>[r,byKey['what-saved/'+r]?.reply||''])),appliedState:Object.fromEntries(['offlineAsk','offlineAskCore','send'].map(r=>[r,byKey['can-i-see-applied/'+r]?.reply||''])),undoLocation:Object.fromEntries(['offlineAsk','offlineAskCore','send'].map(r=>[r,byKey['where-undo/'+r]?.reply||'']))},limitations:['Reviewed the immutable isolated W113 controller snapshot; no live source changes. The candidate provides accurate project/source pixel distinctions, target-bound suggestion receipt language, and the current Solid-versus-Source guidance.','A source-less operation fixture (empty zones/layers; transaction uncommitted) confirmed Save/Open setup guidance on offlineAsk/offlineAskCore and no ask/paint queue through send. This is controller-level guidance, not a native UI or save/open test.','The VM exercises candidate offlineAsk/offlineAskCore/send with controlled operation and queue adapters. It stubs offlineLookAsk, so the polite roof-solid-blue queue outcome cannot be proven here; polite hood-chrome and roof-matte-black controls queue successfully. No app save/open/paint application was performed.','Receipt questions ran without seeded production receipt history; verification covers honest “no current receipt” messaging, not operation IDs or actual recent-history lookup. The test finish adapter records sends but does not emulate the complete UI renderer. Native renderer, browser, providers, and external services were not used.'],counts:{utterances:oracle.cases.length,routedChecks:rows.length+3,reviewFindings:issues.length,providerCalls:0,nativeCalls:0,applyCalls:0}};
 fs.writeFileSync(path.join(root,'docs/handoff_reports/AI_HELPER_14H_VOICE_HELP_W114_REVIEW_2026-10-04.json'),JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result,null,2));
})().catch(e=>{console.error(e.stack||e);process.exitCode=1;});
function pathHash(p){return sha(fs.readFileSync(path.join(root,p),'utf8'));}
