'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const root=path.resolve(__dirname,'..'),candidate='_easy_claude_work/ai14h_material_grammar_w111_successor/candidate/spb-ai-material-controls.js',oraclePath='_easy_claude_work/ai14h_w111_independent_review/own-oracle.json';
const controls=require(path.join(root,candidate)),oracleText=fs.readFileSync(path.join(root,oraclePath),'utf8'),oracle=JSON.parse(oracleText),sha=b=>crypto.createHash('sha256').update(b).digest('hex').toUpperCase(),candidateSha=sha(fs.readFileSync(path.join(root,candidate)));
assert.equal(candidateSha,'797D3B845DD1C1BFC714BD4A4327CF5271820B8DED298A000ECFC153603D87D8');assert.equal(sha(oracleText),'86CF1149CD3E03DD8F1D13C80EA29F5513B2F745A4DAA88FF7453BC452AD639C');
const expectedNoop=new Set(['zero-delta']); const expectedClamp=new Set(['over-range']);
const intendedEdit=new Set(['polite-roof-down-12','natural-hood-reduce-blue-coat','left-side-raise','trunk-down-five','roof-coat-decrease','keep-roughness-alone','keep-paint-color-alone']);
const rows=[],issues=[];
for(const c of oracle.cases){const parsed=controls.parse(c.input),wantEdit=intendedEdit.has(c.id);let built=null,tuplePreserved=null,immutable=null;
 if(wantEdit&&parsed.kind==='edit'){
  const z={id:'z-'+c.id,name:'existing '+c.expected.target,specShiftR:13,specShiftG:27,specShiftB:31,baseColor:'#1450b4',base:'base::satin',regionMask:new Uint8Array([1,0,1])};
  const before={id:z.id,name:z.name,specShiftR:z.specShiftR,specShiftG:z.specShiftG,specShiftB:z.specShiftB,baseColor:z.baseColor,base:z.base,regionMask:Array.from(z.regionMask)};
  built=controls.buildEdit(z,parsed);tuplePreserved=!!built&&built.kind==='edit'&&built.zone_id===z.id&&built.spec_shift&&built.spec_shift.metal===13&&built.spec_shift.rough===27&&built.spec_shift.clearcoat===Math.max(-127,Math.min(127,31+parsed.delta));immutable=JSON.stringify(before)===JSON.stringify({...z,regionMask:Array.from(z.regionMask)});
  if(parsed.part!==c.expected.target||parsed.channel!=='clearcoat'||parsed.delta!==c.expected.delta||!tuplePreserved||!immutable)issues.push(c.id+': parser/builder target/channel/amount/tuple/immutability mismatch');
 } else if(wantEdit) issues.push(c.id+': expected one exact clearcoat edit, parsed '+parsed.kind+' ('+(parsed.reason||'')+')');
 else if(expectedNoop.has(c.id)&&parsed.kind==='edit'){const z={id:'noop-'+c.id,specShiftR:13,specShiftG:27,specShiftB:31};built=controls.buildEdit(z,parsed);if(!built||built.kind!=='noop')issues.push(c.id+': zero adjustment did not become a builder noop');}
 else if(expectedClamp.has(c.id)&&parsed.kind==='edit'){const z={id:'range-'+c.id,specShiftR:13,specShiftG:22,specShiftB:0};built=controls.buildEdit(z,parsed);if(built&&built.kind==='edit'&&built.spec_shift.clearcoat!==-140)issues.push(c.id+': builder clamps requested -140 points to '+built.spec_shift.clearcoat+' at baseline channel 0');}
 else if(parsed.kind==='edit') issues.push(c.id+': unsafe executable parse for read-only/ambiguous/compound case');
 rows.push({id:c.id,input:c.input,expected:c.expected,parsed,builder:built&&{kind:built.kind,zone_id:built.zone_id,spec_shift:built.spec_shift},tuplePreserved,immutable});
}
const report={workItem:'Independent W111 clearcoat grammar and builder review',status:issues.length?'CANDIDATE_HAS_GAPS':'PASS_PRIVATE_REVIEW',pins:{candidate,candidateSha256:candidateSha,oracle:oraclePath,oracleSha256:sha(oracleText),producerOracle:'_easy_claude_work/ai14h_material_grammar_w111_successor/fresh-oracle.json',producerOracleSha256:'1F3A5511CAB1BE5C6C508264CEB48B19178D5D2A59D78F7BE16F7D53C7BFE335'},counts:{cases:rows.length,expectedEdits:rows.filter(x=>intendedEdit.has(x.id)).length,parsedEdits:rows.filter(x=>x.parsed.kind==='edit').length,builderExecuted:rows.filter(x=>x.builder).length,builderChannelPreserved:rows.filter(x=>x.tuplePreserved).length,issues:issues.length,providerCalls:0,nativeCalls:0},rows,issues,limits:['Directly invokes the candidate module actual parse/buildEdit APIs; no controller route, current-owner validation, provider, native UI, or paint application.','The seven positive phrases deliberately include polite/natural variants outside the producer’s exact target-first grammar; failures show parser coverage boundaries and should not be read as action dispatch effects.','Builder fixture is synthetic and verifies full spec tuple, base color, finish, mask immutability only. It does not prove a current real zone or render behavior.']};
const out='docs/handoff_reports/AI_HELPER_14H_W111_CLEARCOAT_INDEPENDENT_REVIEW_2026-10-04.json';fs.writeFileSync(path.join(root,out),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({status:report.status,counts:report.counts,issues},null,2));
