'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),crypto=require('node:crypto'),cp=require('node:child_process');
const root=path.resolve(__dirname,'..'),candidate='_easy_claude_work/ai14h_w118_solid_color_modifier/candidate/spb-pro-design.js',baseline='_easy_claude_work/ai14h_generation3_audit/frozen-runtime11/js/spb-pro-design.js',oraclePath='_easy_claude_work/ai14h_w118_solid_color_modifier_review/fresh-oracle.json';
const read=p=>fs.readFileSync(path.join(root,p)),sha=b=>crypto.createHash('sha256').update(b).digest('hex').toUpperCase(),candBytes=read(candidate),baseBytes=read(baseline),oracleBytes=read(oraclePath),oracle=JSON.parse(oracleBytes);
assert.equal(sha(candBytes),'13E8C48134B4E3649D914EA1D1C1AAECC92D1728DA2A8C80C5826386DC14357C');assert.equal(sha(baseBytes),'4648DE3231015497CC9FF816612A542097A1AD14038A7210753F6CDBFD88D832');assert.equal(sha(oracleBytes),'337743318F206F4A9843233B9B45A8D2E5C2BEA20295CEB44F99E29ECC988D48');
function load(bytes){const w={};vm.runInNewContext(String(bytes),{window:w,console});assert(w.SpbProDesign);return w.SpbProDesign;}
const D=load(candBytes),B=load(baseBytes),rows=[],issues=[];
function compact(plan){return plan&&Array.isArray(plan.zones)?plan.zones.map(z=>({part:z.region&&z.region.part,color:z.color,finish:z.finish})):null;}
for(const c of oracle.cases){const row={id:c.id,input:c.input},look=D.lookRequest(c.input),coverage=D.offlinePartCoverage(c.input),part=D.offlinePart(c.input),spec=D.offlineSpec(c.input),element=D.offlineElement(c.input);row.look=look;row.coverage=coverage&&{complete:coverage.complete,parts:coverage.parts,zones:compact(coverage),canonicalText:coverage.canonicalText};row.part=compact(part);row.spec=compact(spec);row.element=compact(element);row.baselineLook=B.lookRequest(c.input);rows.push(row);
 if(c.id==='solid-known-part-color') {assert.equal(look,null);assert(coverage&&coverage.complete);assert.deepEqual(Array.from(coverage.parts),['hood']);assert.equal(coverage.zones[0].color,'#7a3fc4');}
 if(c.id==='quoted-solid-red-explanation'){assert.equal(look,null);assert.equal(coverage,null);assert.equal(element,null);}
 if(c.id==='matte-flat-preservation-tail'){if(!((element&&element.zones.length===1&&element.zones[0].region.part==='hood'&&element.zones[0].finish==='base::matte'&&element.zones[0].color==='#c8102e')||(coverage&&coverage.zones.length===1&&coverage.zones[0].region.part==='hood'&&coverage.zones[0].finish==='base::matte'&&coverage.zones[0].color==='#c8102e')))issues.push(c.id+': no complete hood-only matte-red representation');}
 if(c.id==='source-paint-color-retain'){if(!(spec&&spec.zones.length===1&&spec.zones[0].region.part==='roof'&&spec.zones[0].color==='source'&&spec.zones[0].finish==='base::f_soft_matte'&&coverage===null))issues.push(c.id+': current source-paint finish-only plan was not retained');}
 if(c.id==='mixed-two-part-different-finishes'){
   const zones=row.coverage&&row.coverage.zones;
   if(!zones||zones.length!==2||!zones.some(z=>z.part==='roof'&&z.color==='#c8102e'&&z.finish==='base::gloss')||!zones.some(z=>z.part==='hood'&&z.color==='#1450b4'&&z.finish==='base::matte'))issues.push(c.id+': candidate accepts an incomplete/semantically wrong per-part finish plan');
 }
 if(c.id==='solid-unknown-look-token'&&look===null&&part&&part.zones.length)issues.push(c.id+': lookRequest suppresses clarification while permissive offlinePart produces a black roof plan');
 if(c.id==='solid-ambiguous-part-scope'&&look===null&&part&&part.zones.length)issues.push(c.id+': lookRequest suppresses clarification while offlinePart expands “roof or hood” into both parts');
 if(c.id==='unknown-solid-word'&&coverage)issues.push(c.id+': unsupported color/look unexpectedly has coverage');
}
const run=(file,opts={})=>cp.execFileSync(process.execPath,[path.join(root,file)],{cwd:root,encoding:'utf8',env:{...process.env,...opts.env}}).trim();
const five=run('tests/ai_w118_solid_color_modifier_contract.cjs'),e17=run('_easy_claude_work/ai14h_w118_solid_color_modifier_review/edit_req_candidate.cjs'),d477=run('_easy_claude_work/ai14h_w118_solid_color_modifier_review/edit_corpus_candidate.cjs'),compound=run('_easy_claude_work/design_compound_test.js',{env:{DESIGN_FILE:candidate}});
assert(/PASS_PRIVATE_E_CLASSIFIER/.test(five));assert(/17 requests, 0 mismatches/.test(e17));assert(/477 phrases, 0 mismatches/.test(d477));assert(/compound 50\/50 \| guards 22\/22/.test(compound));
const report={work_item:'Independent W118 Solid color modifier candidate review',status:issues.length?'REJECT_PRIVATE_REVIEW':'PASS_PRIVATE_REVIEW',decision:'REJECT_FOR_INTEGRATION_PENDING_FALSE_ACCEPTANCE_FIX',pins:{candidate:{path:candidate,sha256:sha(candBytes)},baseline:{path:baseline,sha256:sha(baseBytes)},frozenOracle:{path:oraclePath,sha256:sha(oracleBytes),cases:oracle.cases.length},producerOracle:{path:'_easy_claude_work/ai14h_w118_solid_color_modifier/fresh-oracle.json',sha256:'E8D00ACDA0FDCC114B028FF25586EFCBE2D6859F9893E552315DF60C09FB2E8D',cases:5}},regressions:{producer5Case:five.split('\n')[0],editRequest17:e17,editCorpus477:d477,compound50andGuards22:compound},counts:{freshCases:rows.length,confirmedFalseAcceptances:issues.length,providerCalls:0,nativeCalls:0,paintApplications:0},rows,issues,findings:[{severity:'P1',finding:'Mixed per-part instructions are represented as a complete but wrong plan: the red “solid” roof is assigned matte because offlinePartCoverage applies the request-wide matte finish from the separate hood clause.'},{severity:'P1',finding:'For malformed/ambiguous solid-color requests, the changed lookRequest returns null even though offlinePartCoverage rejects; the downstream offlinePart classifier still emits a partial or guessed action (black roof for “Black Ice Nebula”; both hood and roof for “roof or hood”). Frozen baseline lookRequest returned a look query for these examples, intercepting the fallback path.'}],limits:['This review loads the exact real SpbProDesign module API in a VM and invokes actual lookRequest/offlineSpec/offlinePart/offlineElement/offlinePartCoverage/compoundPlan classifiers. It does not load public SpbProAI dispatcher or owner/source proof, and does not claim an applied route. The observed fallback hazard is classifier-level and must be replayed in the eventual controller before integration acceptance. No providers, native app, browser, or paint application.']};const out='docs/handoff_reports/AI_HELPER_14H_SOLID_COLOR_MODIFIER_W118_REVIEW_2026-10-04.json';fs.writeFileSync(path.join(root,out),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({status:report.status,decision:report.decision,counts:report.counts,regressions:report.regressions,issues,report:out},null,2));if(issues.length)process.exitCode=1;
