'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),crypto=require('node:crypto');
const root=path.resolve(__dirname,'..'),base='_easy_claude_work/ai14h_generation3_runtime11/js/';
const files={pro:'_easy_claude_work/ai14h_w121_guidance_successor/candidate/spb-pro-ai.js',selfhelp:'_easy_claude_work/ai14h_w121_guidance_successor/candidate/spb-self-help.js',receipt:base+'spb-ai-receipt-explainer.js',intent:base+'spb-ai-instruction-intent-guard.js',complete:base+'spb-ai-complete-instruction-guard.js',strict:'_easy_claude_work/ai14h_final_source_identity_candidate/browser-file-v2/spb-pro-ai.js',oracle:'_easy_claude_work/ai14h_w121_guidance_successor/supplemental-oracle.json'};
const src=Object.fromEntries(Object.entries(files).map(([k,p])=>[k,fs.readFileSync(path.join(root,p),'utf8')]));
const sha=s=>crypto.createHash('sha256').update(s).digest('hex').toUpperCase(),oracle=JSON.parse(src.oracle);
const frozen24Text=fs.readFileSync(path.join(root,'_easy_claude_work/ai14h_w121_guidance_review/fresh-oracle.json'),'utf8'),frozen24=JSON.parse(frozen24Text);
assert.equal(sha(src.pro),'AC170B8E9DAB44F8C61B044C16A14A98974412CC403601D06196B471FF574535','candidate pin');
assert.equal(sha(src.selfhelp),'E230A121127FC6B32C451C630028D3D2D10461B67819BF50F2B148195DB8DF4D');
assert.equal(sha(src.oracle),'DC6EA9441B98C832FD8FD4100D36E0A5C1C53CDD00817BE55970862D2617056B');
assert.equal(sha(frozen24Text),'7A190A0F670A0BDE395334B426A653DD7486B9355B642F06795BD1B575478099');
assert.equal(oracle.cases.length,8);
function extract(s,n){const a=s.indexOf(`function ${n}(`);assert(a>=0,`missing ${n}`);const b=s.indexOf('{',a);let d=0,q=null,ln=false,bl=false,esc=false;for(let i=b;i<s.length;i++){const c=s[i],x=s[i+1];if(ln){if(c==='\n')ln=false;continue;}if(bl){if(c==='*'&&x==='/'){bl=false;i++;}continue;}if(q){if(esc){esc=false;continue;}if(c==='\\'){esc=true;continue;}if(c===q)q=null;continue;}if(c==='/'&&x==='/'){ln=true;i++;continue;}if(c==='/'&&x==='*'){bl=true;i++;continue;}if(c==='"'||c==="'"||c==='`'){q=c;continue;}if(c==='{')d++;else if(c==='}'&&--d===0)return s.slice(a,i+1);}throw Error('unterminated '+n);}
for(const n of ['normalizeOfflineInstruction','offlineInstructionPreflight'])assert.equal(extract(src.pro,n),extract(src.strict,n),n+' still matches strict identity baseline');
function fixture(configured){const gen=23,w={console,Promise,Date,Math,JSON,Object,Array,String,Number,RegExp,Error,Uint8Array,document:{body:{classList:{contains:()=>false}},getElementById:()=>null,querySelector:()=>null,querySelectorAll:()=>[]},zones:[],_psdLayers:[{id:'paint',name:'Car Paint',visible:true,img:{width:2048,height:2048}},{id:'nested',name:'Body',visible:true,children:[{id:'hidden',name:'Hidden Decal',visible:false}]}],paintImageData:null,_psdPath:'C:/fixture/selected.psd',selectedZoneIndex:-1,zoneSourceLayerIds:()=>[],_spbLayerRev:0,SpbProCar:{roles:()=>[],map:()=>null,missing:()=>[]},SpbAI:{cached:()=>({configured:!!configured,provider:configured?'test-provider':'',model:configured?'blocked':''})},SpbAiLease:{internal:()=>true},SPBSourceLoadTransaction:{getGeneration:()=>gen,getCommittedGeneration:()=>gen,getCommittedKind:()=> 'layered',getCommittedPath:()=> 'C:/fixture/selected.psd',getCommittedFingerprint:()=> 'file-sha256:'+String(gen).padStart(64,'0'),isLoading:()=>false,isCommitted:()=>true},fetch:undefined};w.window=w;vm.createContext(w);for(const k of ['selfhelp','receipt','intent','complete'])vm.runInContext(src[k],w,{filename:files[k]});Object.assign(w,{_log:[],_busy:false,_ctl:null,_envMemo:null,_partMemoryWarmAttemptTicket:null,_absent:{},_skipParts:false,operationCurrent:t=>!!t&&t.ok===true&&(!t.document||t.document.sourceGeneration===gen),operationTicket:v=>v&&v._spbOperation||null,operationManager:()=>({sameDocument:t=>!!t&&t.document&&t.document.sourceGeneration===gen,ready(){},owns:()=>true,owner:()=>null}),operationRevision:()=>1,operationRelease(){},operationBind:v=>v,operationStart:()=>({ok:true,document:{sourceGeneration:gen},revision:1,collection:1}),operationCanceled:()=>({cancelled:true,stale:true,queue:[]}),offlineAsk:()=>Promise.resolve({offline:true,queue:[],text:'controlled local route; no paint applied',howto:true}),editPlan:()=>null,advisorIntent:()=>null,advisorOwns:()=>false,layerVisRequest:()=>null,offlineMaterialPlan:()=>null,offlinePartAsk:()=>Promise.resolve({offline:true,queue:[],text:'controlled local action route'})});for(const n of ['normalizeOfflineInstruction','selfHelpResult','unexecutedSuggestionReply','w121PsdTgaHelp','contextualHelpReply','offlineInstructionPreflight','ask'])vm.runInContext(extract(src.pro,n),w,{filename:files.pro+':'+n});w.spbProAI={ask:w.ask};let providers=0,tickets=0;w.askCore=()=>{providers++;throw Error('blocked provider path')};w.askForTicket=(text,opts)=>{tickets++;return Promise.resolve({offline:true,text:'controlled downstream action adapter',queue:[],calls:0,usage:{cost:0}})};return{w,counts:()=>({providers,tickets})};}
const required={
 'flat-tga-vs-original-psd':[/flat TGA/i,/cannot provide.*original PSD/i,/editable layer groups/i],
 'inspect-hidden-imported-group':[/current Layers panel/i,/actually listed/i,/cannot infer.*fidelity/i],
 'bridge-vs-paid-provider-local':[/connection or transport/i,/charge depends on the connected provider/i,/built-in local helper/i,/without provider credits/i],
 'actual-verification-scope':[/guarded target/i,/receipt/i,/not an exhaustive comparison/i,/every requested pixel/i],
 'pending-target-after-source-switch':[/source switch invalidates/i,/identify and verify.*current source/i],
 'flat-preview-uv-boundary':[/does not guarantee the exact UV boundary/i,/visible selection mask/i],
 'unknown-finish-real-picker':[/finish picker\/catalog/i,/names actually listed/i,/No finish was changed/i],
 'project-save-original-psd':[/does not overwrite the imported PSD/i,/no changes/i],
 'online-vs-offline':[/Online AI requests/i,/built-in local helper/i,/without provider credits/i],
 'hidden-psd-layers':[/current Layers panel/i,/cannot infer hidden or nested group fidelity/i],
 'nested-psd-groups':[/current Layers panel/i,/cannot infer hidden or nested group fidelity/i],
 'stale-receipt-retry':[/source switch invalidates the old request target/i,/must not be applied to the replacement paint/i],
 'unknown-finish-name':[/cannot verify that named finish/i,/finish picker\/catalog/i,/will not invent/i],
 'unknown-finish-apply':[/finish picker\/catalog/i,/unverified finish/i,/No finish was changed/i],
 'source-original-modification':[/does not overwrite the imported PSD or TGA source file/i,/no changes/i],
 'automatic-verification':[/guarded target/i,/apply receipt/i,/not an exhaustive comparison/i]
};
(async()=>{const rows=[],issues=[];const cases=oracle.cases.concat(frozen24.cases.filter(c=>required[c.id]));for(const c of cases)for(const configured of [false,true]){const f=fixture(configured),r=await f.w.spbProAI.ask(c.request||c.input,{offline:true}),text=String(r&&r.text||''),howto=!!(r&&r.howto),q=(r&&r.queue||[]).length,count=f.counts(),topic=r&&r.selfHelp&&r.selfHelp.topic||'';const row={id:c.id,configured,howto,topic,queue:q,downstream:count.tickets,providers:count.providers,text:text.slice(0,500)};rows.push(row);if(!howto||q||count.providers||count.tickets)issues.push(c.id+': information query escaped local read-only route');for(const re of required[c.id]||[])if(!re.test(text))issues.push(c.id+': missing semantic requirement '+re);for(const claim of c.mustNotClaim||[])if(/every requested pixel|exactly recover|recover original|all hidden groups|overwrites the imported PSD|flat preview.*exact UV/i.test(claim)&&new RegExp(claim.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),'i').test(text))issues.push(c.id+': forbidden claim '+claim);if(c.id==='actual-verification-scope'&&/verifies every requested pixel and material/i.test(text))issues.push(c.id+': exhaustive verification claim');}
for(const request of ['Make only the roof satin.','Make the hood red.']){const f=fixture(false),r=await f.w.spbProAI.ask(request,{offline:true}),n=f.counts();rows.push({id:'action-control',request,howto:!!(r&&r.howto),queue:(r&&r.queue||[]).length,downstream:n.tickets,providers:n.providers,text:String(r&&r.text||'').slice(0,300)});if(r&&r.howto||n.providers||n.tickets!==1)issues.push('action control was intercepted or escaped controlled local handoff: '+request);}
const report={workItem:'W121 narrow guidance successor supplemental review',status:issues.length?'GAPS':'PASS_PRIVATE_SUPPLEMENT',pins:{controller:files.pro,controllerSha256:sha(src.pro),E230:files.selfhelp,E230Sha256:sha(src.selfhelp),strictFb63:files.strict,strictSha256:sha(src.strict),oracle:files.oracle,oracleSha256:sha(src.oracle)},counts:{supplementalCases:oracle.cases.length,informationExecutions:rows.filter(r=>r.id!=='action-control').length,actionControls:rows.filter(r=>r.id==='action-control').length,readOnlyInformation:rows.filter(r=>r.id!=='action-control'&&r.howto&&!r.queue&&!r.downstream&&!r.providers).length,queued:rows.reduce((n,r)=>n+(r.queue||0),0),downstreamInformation:rows.filter(r=>r.id!=='action-control').reduce((n,r)=>n+(r.downstream||0),0),actionHandoffs:rows.filter(r=>r.id==='action-control').reduce((n,r)=>n+r.downstream,0),providerAttempts:rows.reduce((n,r)=>n+(r.providers||0),0),issues:issues.length},rows,issues,limits:['Calls the actual public ask() and extracted contextual-help/preflight path in a VM; provider/downstream action effects are controlled stubs and no paint is applied. Source, layers, and receipts are metadata fixtures only.','The app save/import routes were inspected separately; no PSD/TGA bytes, Photoshop round-trip, UI, native app, browser, server, or real provider were exercised.']};const out=path.join(root,'_easy_claude_work/ai14h_w121_guidance_successor/supplemental-review.json');fs.writeFileSync(out,JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({status:report.status,pins:report.pins,counts:report.counts,issues,report:out,rows},null,2));assert.equal(issues.length,0);})().catch(e=>{console.error(e.stack||e);process.exitCode=1;});
