'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),crypto=require('node:crypto');
const root=path.resolve(__dirname,'..'),base='_easy_claude_work/ai14h_generation3_runtime9/js/',pro='_easy_claude_work/ai14h_w121_guidance_successor/candidate/spb-pro-ai.js';
const oracles=['_easy_claude_work/ai14h_w118_semantic_successor/fresh-oracle.json','_easy_claude_work/ai14h_w118_semantic_successor/supplied-oracle.json','_easy_claude_work/ai14h_w116_help_scope/fresh-oracle.json','_easy_claude_work/ai14h_w119_contextual_conflicts/fresh-oracle.json'];
const files={pro,selfhelp:base+'spb-self-help.js',receipt:base+'spb-ai-receipt-explainer.js',intent:base+'spb-ai-instruction-intent-guard.js'};
const src=Object.fromEntries(Object.entries(files).map(([k,p])=>[k,fs.readFileSync(path.join(root,p),'utf8')])),oracleTexts=oracles.map(p=>fs.readFileSync(path.join(root,p),'utf8')),sha=s=>crypto.createHash('sha256').update(s).digest('hex').toUpperCase(),proSha=sha(src.pro);
assert.equal(proSha,'AC170B8E9DAB44F8C61B044C16A14A98974412CC403601D06196B471FF574535','immutable W119 candidate pin');
const frozenBaseline='DA0D6C31D73826BCE952CE5020E3E85F1B90F59E3C371E361D77294B38EBCFA4';
const parsed=oracleTexts.map(JSON.parse);assert.equal(sha(oracleTexts[0]),'EEBF7B31C7EF8989C1336F97BE7E116C3829E663F32303C7B3C450E1D9632F9A');assert.equal(sha(oracleTexts[1]),'C5CE418FE079EF874DFF9A6512027BCC56992C52D9403EEFEE5F4F28A130C2BE');assert.equal(sha(oracleTexts[2]),'AE770A758B813261D52CBF157FBEACA41B33B2A05122FC388974AAF066B8FD8E');assert.equal(sha(oracleTexts[3]),'CC214A8F5F31802C39422A379A4174B1E81DDA3072F3C4A380FDE91D9F5B7B92');
function extract(s,n){const a=s.indexOf(`function ${n}(`);assert(a>=0,n+' exists');const b=s.indexOf('{',a);let d=0,q=null,ln=false,bl=false,esc=false;for(let i=b;i<s.length;i++){const c=s[i],x=s[i+1];if(ln){if(c==='\n')ln=false;continue;}if(bl){if(c==='*'&&x==='/'){bl=false;i++;}continue;}if(q){if(esc){esc=false;continue;}if(c==='\\'){esc=true;continue;}if(c===q)q=null;continue;}if(c==='/'&&x==='/'){ln=true;i++;continue;}if(c==='/'&&x==='*'){bl=true;i++;continue;}if(c==='"'||c==="'"||c==='`'){q=c;continue;}if(c==='{')d++;if(c==='}'&&--d===0)return s.slice(a,i+1);}throw Error('unterminated '+n);}
function fixture(state='empty'){const layers=state==='psd'?[{id:'paint',name:'Car Paint',img:{width:2048,height:2048},visible:true},{id:'sponsors',name:'Sponsors',img:{width:2048,height:2048},visible:false}]:[];const w={console,Promise,Date,Math,JSON,Object,Array,String,Number,RegExp,Error,document:{body:{classList:{contains:()=>false}},getElementById:()=>null},zones:[],_psdLayers:layers,paintImageData:state==='flat'?{width:2048,height:2048,data:new Uint8Array(4)}:null,selectedZoneIndex:-1,zoneSourceLayerIds:()=>[],_spbLayerRev:0,SpbProCar:{roles:()=>[],map:()=>null,missing:()=>[]},SpbAI:{cached:()=>({configured:false})},SpbAiLease:{internal:()=>true}};w.window=w;vm.createContext(w);for(const k of ['selfhelp','receipt','intent'])vm.runInContext(src[k],w,{filename:files[k]});Object.assign(w,{_log:[],_busy:false,_ctl:null,_envMemo:null,operationCurrent:t=>!!t&&t.ok===true,operationTicket:v=>v&&v._spbOperation||null,operationManager:()=>({sameDocument:t=>!!t&&t.document&&t.document.sourceGeneration===9,ready(){},owns:()=>true}),operationRevision:()=>1,operationRelease(){},operationBind:v=>v,operationStart:()=>({ok:true,document:{sourceGeneration:9},revision:1,collection:1}),operationCanceled:()=>({cancelled:true,stale:true,queue:[]}),offlineAsk:()=>Promise.resolve({offline:true,queue:[],text:'offline route sentinel'})});for(const n of ['normalizeOfflineInstruction','selfHelpResult','unexecutedSuggestionReply','w121PsdTgaHelp','contextualHelpReply','offlineInstructionPreflight','ask'])vm.runInContext(extract(src.pro,n),w,{filename:files.pro});w.spbProAI={ask:w.ask};const calls=[];w.askForTicket=(text,options)=>{calls.push({text,options});return Promise.resolve({offline:true,text:'controlled offline action handoff',queue:[]});};return{w,calls};}
const all=parsed.flatMap((o,i)=>o.cases.map(c=>({...c,_oracle:i}))),rows=[],issues=[];
const semantic={
 'inspect_target_before_edit':[/selected zone/i,/mask/i,/no changes/i], 'offline_capabilities':[/built-in helper/i,/local/i,/provider credits/i],
 'hypothetical_finish_effect':[/Nothing was changed/i,/Matte means|Chrome means/i,/paint color/i], 'hypothetical_color_effect':[/Nothing was changed/i,/roof color/i,/verified roof target/i],
 'flat_image_has_no_layers':[/flat TGA/i,/no separate.*layer/i,/layered PSD/i], 'spec_map_tga_import':[/spec-map TGA/i,/not replacement Source Paint/i,/R is metalness.*G is roughness.*B is clearcoat/i],
 'source_identity_unavailable':[/cannot report a current source path/i,/recorded source path/i], 'source_required_for_edit':[/loaded source/i,/current target/i],
 'cross_car_scope_not_transferable':[/not proof for this car/i,/current loaded paint/i,/not transfer/i], 'number_location_current_paint':[/remembered number location/i,/current paint/i,/confirm/i],
 'layer_editability_limits':[/Layers panel/i,/flattened layer/i,/adjustment-layer|adjustment-layer content/i], 'bridge_connection_checks':[/settings gear/i,/installed and running/i,/cannot see or change/i],
 'clearcoat_channel':[/Clearcoat/i,/B/i,/roughness/i], 'recent_change_receipt':[/receipt|cannot tell|cannot infer/i]
};
(async()=>{for(const c of all){const state=/flat|sponsor|tga/i.test(c.id+c.topic)?'flat':/layer|psd/i.test(c.id+c.topic)?'psd':'empty';const {w,calls}=fixture(state),r=await w.spbProAI.ask(c.input,{offline:true}),t=String(r&&r.text||''),topic=(r&&r.selfHelp&&r.selfHelp.topic)||'';rows.push({oracle:oracles[c._oracle],id:c.id,input:c.input,expected:c.expect||'',state,topic,howto:!!(r&&r.howto),delegated:calls.length,queue:(r&&r.queue||[]).length,text:t.slice(0,500)});
if(c.topic==='action-control'||c.id==='action-control-matte'||c.id==='action-control-finish'||c.id==='redo-action-control'||c.id==='hide-wireframe-action-control'||c.id==='roof-action-control'){if(r&&r.howto||calls.length!==1||calls[0].text!==c.input)issues.push(c.id+': action control was intercepted');continue;}
if(!r||!r.howto||calls.length||(r.queue||[]).length)issues.push(c.id+': expected local read-only answer');
const req=(map)=>{for(const re of map||[])if(!re.test(t))issues.push(c.id+': answer lacks '+re);};
if(/area|land before|wants? to paint|preview|hard to identify|choose the right area/i.test(c.input))req([/selected zone|current part|scope/i,/mask|marked target|identify/i,/made no changes/i]);
if(/offline|provider|credits|paying/i.test(c.input))req([/local|built-in/i,/provider/i,/no .*require|without|do not require/i]);
if(/matte|chrome|satin|gloss|metallic/i.test(c.input)&&/what|if|explain|does it/i.test(c.input))req([/matte|chrome|reflective|glossy/i,/paint color|color/i,/made no changes|Nothing was changed/i]);
if(/roof blue|made .* blue/i.test(c.input))req([/Nothing was changed|made no changes/i,/verified roof|current.*mask|scope/i]);
if(/flat|flattened/i.test(c.input)&&/tga|sponsor|layer/i.test(c.input))req([/flat|one raster/i,/no separate.*layer/i,/layered/i]);
if(/spec-map TGA|spec.map TGA/i.test(c.input))req([/spec-map TGA/i,/not replacement Source Paint/i,/metalness.*roughness.*clearcoat/i]);
if(/source path|before loading|before load|without loading|no paint loaded/i.test(c.input))req([/source/i,/loaded|load|recorded/i]);
if(/another car|other car|different car|truck/i.test(c.input))req([/not proof for this car/i,/current loaded paint/i,/not transfer/i]);
if(/number/i.test(c.input)&&/last time|near the|previous|remember|confirm/i.test(c.input))req([/remembered number location/i,/current paint/i,/confirm/i]);
if(/editable|editability/i.test(c.input)&&/PSD|layer|adjustment/i.test(c.input))req([/Layers panel/i,/flattened layer/i,/adjustment-layer/i]);
if(/bridge|connector|assistant connection/i.test(c.input))req([/bridge|assistant/i,/gear|connection option|Install in Claude/i,/restart|installed and running/i]);
if(c.id==='redo-after-manual-layer')req([/Redo checks/i,/conflicting change/i,/does not restore layer pixel buffers/i,/changed nothing/i]);
if(c.id==='wireframe-hypothetical')req([/Nothing was changed/i,/Wire template layer/i,/Mask guide|zone mask/i,/paint pixels/i]);
if(c.id==='mask-is-not-wireframe')req([/Nothing was changed/i,/PSD Mask layer/i,/zone.s separate region mask/i,/paint pixels/i]);
}
const actionIds=['action-control','action-control-matte','action-control-finish','redo-action-control','hide-wireframe-action-control','roof-action-control'];const report={work_item:'W121 candidate retained W119 contextual routing regression replay',status:issues.length?'REVIEW_GAPS':'PASS_PRIVATE_REPLAY',source:{path:pro,sha256:proSha,baseline:frozenBaseline},oracles:oracles.map((p,i)=>({path:p,sha256:sha(oracleTexts[i]),frozen:true,cases:parsed[i].cases.length})),counts:{cases:rows.length,readOnly:rows.filter(x=>!actionIds.includes(x.id)).length,actionControls:rows.filter(x=>actionIds.includes(x.id)).length,issues:issues.length,providerCalls:0,nativeCalls:0,paintApplications:0},rows,issues,limits:['The harness invokes extracted real public ask(), contextualHelpReply(), and offline preflight functions with actual frozen self-help, receipt, and intent modules. Controlled action handoff replaces provider/native effects. No desktop IIFE, browser, provider, native app, save, paint, or application side effect was run. This is private semantic coverage, not native acceptance.']};const out='_easy_claude_work/ai14h_w121_guidance_successor/ai_w121_guidance_successor_53_contract_report.json';fs.writeFileSync(path.join(root,out),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report,null,2));if(issues.length)process.exitCode=1;})().catch(e=>{console.error(e.stack||e);process.exitCode=1;});






