"""SPB-WILDS contract tests for the 2026-08-23 BLOOM/PETRI rebuild.

Owner verdict: "Too much redundancy way too similar looks. Must be VERY
UNIQUE. And must have the 'Fractured' color flipping stuff."
"""

from __future__ import annotations

import cv2
import numpy as np
import pytest

from engine.expansions import fractured_bloom_2026 as bloom
from engine.expansions import fractured_petri_2026 as petri
from engine.expansions import fractured_wilds_microkit_2026 as microkit
from scripts.spb_wilds_bloom_petri_audit import (
    _chroma_layout_descriptor,
    _chroma_layout_similarity,
    _material_hue_separation,
    _tier_count,
)


BLOOM_IDS = (
    "fbl_magenta_whorl", "fbl_leafvine_drape", "fbl_butter_pollen",
    "fbl_pink_rose", "fbl_coral_cluster", "fbl_butter_mosaic",
    "fbl_pink_pollen", "fbl_white_whorl", "fbl_coral_stamen",
    "fbl_lilac_rose", "fbl_coral_vine", "fbl_lilac_stamen",
    "fbl_magenta_mosaic", "fbl_leaf_whorl", "fbl_white_pollen",
    "fbl_pink_stamen", "fbl_blush_rose", "fbl_lilac_vine",
    "fbl_butter_whorl", "fbl_magenta_pollen",
)

PETRI_IDS = (
    "fpe_magenta_bloom", "fpe_cyan_membrane", "fpe_lime_culture",
    "fpe_amber_agar", "fpe_violet_garden", "fpe_lime_diatom",
    "fpe_magenta_mosaic", "fpe_cyan_spineball", "fpe_amber_moldring",
    "fpe_violet_chains", "fpe_cyan_colony", "fpe_lime_mold",
    "fpe_amber_diatom", "fpe_magenta_radiolaria", "fpe_cyan_mold",
    "fpe_amber_plankton", "fpe_violet_membrane", "fpe_lime_chains",
    "fpe_violet_frustule", "fpe_magenta_plankton",
)

_RENDERED = {}


def test_all_forty_ids_and_profiles_are_preserved():
    assert tuple(bloom.ALL) == BLOOM_IDS
    assert tuple(petri.ALL) == PETRI_IDS
    assert {bloom.ALL[fid]["wild_variant"] for fid in BLOOM_IDS} == set(range(20))
    assert {petri.ALL[fid]["wild_variant"] for fid in PETRI_IDS} == set(range(20, 40))


@pytest.mark.parametrize(
    ("kit", "fid"),
    [(bloom.KIT, fid) for fid in BLOOM_IDS] + [(petri.KIT, fid) for fid in PETRI_IDS],
    ids=BLOOM_IDS + PETRI_IDS,
)
def test_renderer_contract_channels_determinism_and_opponent_hue(kit, fid):
    # 256 is a contract probe only.  Native 2048 timing/crops are generated by
    # scripts/spb_wilds_bloom_petri_audit.py and retained as review evidence.
    size = 256
    yy, xx = np.mgrid[:size, :size].astype(np.float32)
    source = np.stack((0.08 + xx / size * 0.12,
                       0.10 + yy / size * 0.10,
                       np.full_like(xx, 0.14)), axis=2).astype(np.float32)
    full = np.ones((size, size), np.float32)
    empty = np.zeros_like(full)
    spec_fn, paint_fn = kit.mk(fid)

    spec = spec_fn((size, size), full, 913, 1.0)
    paint = paint_fn(source, (size, size), full, 913, 1.0, None)
    assert spec.shape == (size, size, 4) and spec.dtype == np.uint8
    assert paint.shape == source.shape and paint.dtype == np.float32
    assert np.isfinite(paint).all() and 0.0 <= float(paint.min()) <= float(paint.max()) <= 1.0

    # Deterministic registry output and canonical neutral/off semantics.
    assert np.array_equal(spec, spec_fn((size, size), full, 913, 1.0))
    assert np.array_equal(paint, paint_fn(source, (size, size), full, 913, 1.0, None))
    assert np.array_equal(spec_fn((size, size), full, 913, 0.0)[:, :, :3],
                          np.broadcast_to(np.uint8([4, 120, 16]), (size, size, 3)))
    assert np.array_equal(spec_fn((size, size), empty, 913, 1.0)[:, :, :3],
                          np.broadcast_to(np.uint8([4, 120, 16]), (size, size, 3)))
    assert np.array_equal(paint_fn(source, (size, size), full, 913, 0.0, None), source)
    assert np.array_equal(paint_fn(source, (size, size), empty, 913, 1.0, None), source)

    partial = np.zeros_like(full)
    partial[64:192, 64:192] = 1.0
    partial_spec = spec_fn((size, size), partial, 913, 1.0)
    partial_paint = paint_fn(source, (size, size), partial, 913, 1.0, None)
    assert np.array_equal(partial_spec[:40, :40, :3],
                          np.broadcast_to(np.uint8([4, 120, 16]), (40, 40, 3)))
    assert np.array_equal(partial_paint[:40, :40], source[:40, :40])

    channels = spec[:, :, :3]
    authored_levels = (microkit._M_LEVELS, microkit._R_LEVELS,
                       microkit._C_LEVELS)
    for channel in range(3):
        data = channels[:, :, channel]
        assert float(data.std()) >= 20.0
        assert int(data.max()) - int(data.min()) >= 150
        assert _tier_count(data, authored_levels[channel]) == 8

    # The three authored phase ladders are not copies of one another.
    assert all(len(np.unique(levels)) == 8 for levels in
               (microkit._M_LEVELS, microkit._R_LEVELS, microkit._C_LEVELS))
    flat = channels.reshape(-1, 3).astype(np.float32)
    correlations = np.corrcoef(flat, rowvar=False)
    assert max(abs(float(correlations[0, 1])),
               abs(float(correlations[0, 2])),
               abs(float(correlations[1, 2]))) < 0.75

    # Saturation-weighted phase hue excludes a white-only highlight.  Each
    # finish must expose a genuine opponent hue between its clear- and
    # metal-led material populations.
    material = _material_hue_separation((paint * 255.0).astype(np.uint8), channels)
    assert material["opponentHueTravelDegrees"] >= 55.0
    assert material["whiteHighlightProofScore"] >= 30.0
    _RENDERED[fid] = (paint * 255.0).astype(np.uint8)


def test_six_fine_mark_families_are_present_and_distinct():
    fields = bloom.KIT.signature_cached(BLOOM_IDS[0])
    fam = fields[2]
    assert fam.shape == (6, bloom.KIT.GEN, bloom.KIT.GEN)
    # No two mark alphabets may collapse to the same mask.
    resized = [cv2.resize(x, (96, 96), interpolation=cv2.INTER_AREA).ravel()
               for x in fam]
    for i in range(6):
        for j in range(i + 1, 6):
            assert not np.allclose(resized[i], resized[j], atol=1e-3)


def test_every_dominant_mark_box_is_8_to_32_pixels_at_native_2048():
    # Primitive support is at least 0.55 of its cell and never exceeds it.
    # Query the exact pitch function used by the renderer for all profiles.
    scale = 2048.0 / bloom.KIT.GEN
    pitches = [pitch for profile in range(20)
               for pitch in microkit._cell_pitches(profile)]
    assert min(pitches) * 0.55 * scale >= 8.0
    assert max(pitches) * scale <= 32.0


@pytest.mark.parametrize(
    ("kit", "fid"),
    [(bloom.KIT, fid) for fid in BLOOM_IDS] + [(petri.KIT, fid) for fid in PETRI_IDS],
    ids=[f"scale-{fid}" for fid in BLOOM_IDS + PETRI_IDS],
)
def test_every_visible_role_zone_p95_is_at_most_32_native_pixels(kit, fid):
    """Equal-density color/glyph routes count as visible owner-eye features.

    This intentionally tests the stricter physical scale, not merely the small
    glyph boxes: a continuous lead/counter role zone may not hide an 80-250 px
    macro band made from compliant dots.  SPB-WILDS owner-eye gate 2026-08-23.
    """
    d = kit.ALL[fid]
    variant = int(d.get("wild_variant", d["wild_profile"]))
    organization = microkit._hue_composition(
        kit.GEN, int(d["seed"]), variant,
    )[1]
    route = organization >= 0.5
    native_scale = 2048.0 / kit.GEN
    p95_thickness = []
    for region in (route, ~route):
        distance = cv2.distanceTransform(region.astype(np.uint8), cv2.DIST_L2, 5)
        p95_thickness.append(
            float(np.percentile(distance[region], 95.0)) * 2.0 * native_scale
        )
    assert max(p95_thickness) <= 32.01


def test_forty_semantic_recipes_select_six_distinct_glyphs():
    assert len(microkit._SEMANTIC_RECIPES) == 40
    assert len({name for name, _, _ in microkit._SEMANTIC_RECIPES}) == 40
    for name, selected, mode in microkit._SEMANTIC_RECIPES:
        assert name
        assert len(selected) == len(set(selected)) == 6
        assert all(0 <= glyph < 24 for glyph in selected)
        assert 0 <= mode < 8


def test_all_forty_actual_outputs_pass_pairwise_chroma_uniqueness():
    descriptors = {}
    for kit, ids in ((bloom.KIT, BLOOM_IDS), (petri.KIT, PETRI_IDS)):
        for fid in ids:
            paint = _RENDERED.get(fid)
            if paint is None:
                size = 256
                source = np.full((size, size, 3), 0.12, np.float32)
                mask = np.ones((size, size), np.float32)
                _, paint_fn = kit.mk(fid)
                paint = (paint_fn(source, (size, size), mask, 913, 1.0, None) * 255).astype(np.uint8)
            descriptors[fid] = _chroma_layout_descriptor(paint)
    nearest = []
    for fid, desc in descriptors.items():
        nearest.append(max(_chroma_layout_similarity(desc, other_desc)
                           for other, other_desc in descriptors.items() if other != fid))
    assert len(nearest) == 40
    assert max(nearest) < 72.0
