const assert=require('node:assert/strict');
const api=require('../js/canvas/zone/material-instance-masters.js');
const model=require('../js/canvas/zone/material-instance-model.js');
const unlink=require('../js/canvas/zone/material-instance-commands.js');
(async()=>{
 const rect={x1:10,y1:20,x2:30,y2:40};
 const a={version:2,id:'a',sourceBbox:rect,renderSourceBbox:{...rect},instanceBbox:{x1:50,y1:60,x2:60,y2:70},documentWidth:200,documentHeight:200,rotation:30};
 const b={...structuredClone(a),id:'b',instanceBbox:{x1:100,y1:100,x2:120,y2:120},rotation:90};
 const unrelated={...structuredClone(a),id:'other',sourceBbox:{x1:0,y1:0,x2:4,y2:4}};
 const zone={patternInstances:[a,b,unrelated]},state={target:'zone_instance:a'};
 const before=structuredClone(zone),history=[],snapshot={format:'spb-zone-material/1',width:20,height:20,data:'master'};
 let refresh=0;
 const options={capture:async()=>snapshot,isCurrent:()=>true,pushUndo:()=>history.push(structuredClone(zone)),newId:()=> 'source',finish(){},notify(){},refresh(){refresh++;}};
 await api.promote(zone,state,options);
 assert.deepEqual(history,[before]);assert.equal(zone.patternInstances.length,4);
 assert.equal(a.masterId,'a');assert.equal(b.masterId,'a');assert.equal(a.frozenMaterial,snapshot);
 assert.deepEqual(a.instanceBbox,before.patternInstances[0].instanceBbox);assert.equal(a.rotation,30);
 assert.deepEqual(b.instanceBbox,before.patternInstances[1].instanceBbox);assert.equal(b.rotation,90);
 assert.deepEqual(unrelated,before.patternInstances[2]);
 const source=zone.patternInstances.find(r=>r.isSource);assert.deepEqual(source.instanceBbox,rect);assert.equal(source.masterId,'a');
 assert.equal(api.group(zone,{target:'base',subRect:rect}).master,a);
 const duplicate=model.duplicate(zone,b,'duplicate');assert.equal(duplicate.masterId,'a');assert.equal(duplicate.rotation,90);assert(!api.same(duplicate.instanceBbox,b.instanceBbox));
 assert(api.sync(zone,state,options));assert.equal(history.length,1,'already-linked Sync makes no history');assert.equal(refresh,1);
 b.frozenMaterial={...snapshot,data:'custom'};
 api.sync(zone,{target:'zone_instance:b'},options);assert.equal(b.frozenMaterial,undefined);assert.equal(a.frozenMaterial,snapshot);assert.equal(history.length,2);
 b.frozenMaterial={...snapshot,data:'other-custom'};
 api.sync(zone,state,{...options,label:'Re-apply Zone material master'});assert.equal(b.frozenMaterial,undefined);assert.equal(history.length,3);
 await unlink.detach(zone,a,options);
 assert(a.detached);assert.equal(b.masterId,b.id);assert.equal(source.masterId,b.id);assert.equal(b.frozenMaterial,snapshot);
 assert.equal(history.length,4,'break promoted master is one transaction');
 const original=structuredClone(zone);
 await assert.rejects(api.promote(zone,{target:'zone_instance:source'},{...options,capture:async()=>null}),/not ready/);
 assert.deepEqual(zone,original);assert.equal(history.length,4);
 console.log('Zone masters: native geometry preserved, source membership, actual override Sync/Re-apply, no-op history, duplication and unlink-master handoff pass.');
})().catch(error=>{console.error(error);process.exitCode=1;});
