const assert=require('node:assert/strict');
const api=require('../js/canvas/zone/material-instance-commands.js');
(async()=>{
 const record={version:2,id:'a',instanceBbox:{x1:1,y1:2,x2:3,y2:4}},other={version:2,id:'b'};
 const zone={patternInstances:[record,other]},before=JSON.parse(JSON.stringify(zone)),history=[];
 const snapshot={format:'spb-zone-material/1',width:2,height:2,data:'test'};
 let finishes=0;
 const options={capture:async()=>snapshot,isCurrent:()=>true,pushUndo:()=>history.push(JSON.parse(JSON.stringify(zone))),finish:()=>finishes++};
 assert(await api.detach(zone,record,options));assert.deepEqual(history,[before]);
 assert.equal(zone.patternInstances.length,2);assert.deepEqual(other,before.patternInstances[1]);
 assert.deepEqual(record.instanceBbox,before.patternInstances[0].instanceBbox);
 assert.equal(record.frozenMaterial,snapshot);assert(record.detached);assert.equal(finishes,1);
 assert.equal(await api.detach(zone,record,options),false);assert.equal(history.length,1);
 const pendingRecord={version:2,id:'c'},pendingZone={patternInstances:[pendingRecord]};
 let release;const wait=new Promise(resolve=>release=resolve);
 const pending=api.detach(pendingZone,pendingRecord,{...options,capture:()=>wait});
 assert.equal(await api.detach(pendingZone,pendingRecord,options),false,'duplicate invocation ignored');
 pendingRecord.rotation=30;release(snapshot);
 await assert.rejects(pending,/selected copy changed/);assert.equal(history.length,1);
 await assert.rejects(api.detach(pendingZone,pendingRecord,{...options,capture:async()=>null}),/not ready/);
 assert.equal(pendingRecord.detached,undefined);assert.equal(history.length,1);
 const group=[{version:2,id:'d'},{version:2,id:'e'}],groupZone={patternInstances:group};
 const groupHistory=[];let captures=0;
 await assert.rejects(api.detach(groupZone,group,{...options,capture:async()=>++captures===1?snapshot:null,pushUndo:()=>groupHistory.push(1)}),/not ready/);
 assert.equal(groupHistory.length,0);assert(group.every(r=>!r.detached),'group capture failure must be atomic');
 await api.detach(groupZone,group,{...options,pushUndo:()=>groupHistory.push(JSON.parse(JSON.stringify(group))),applyFrame:()=>group[0].rotation=30});
 assert.equal(groupHistory.length,1);assert.equal(groupHistory[0][0].rotation,undefined);assert.equal(group[0].rotation,30);
 assert(group.every(r=>r.detached));
 console.log('Material unlink: retained content/frame/sibling, one pre-mutation history, duplicate/stale/failed capture safety pass.');
})().catch(error=>{console.error(error);process.exitCode=1;});
