const assert=require('node:assert/strict'),fs=require('node:fs');
const model=require('../js/canvas/zone/material-instance-model.js');
const payload=require('../js/canvas/zone/material-instance-payload.js');
const src={x1:10,y1:10,x2:30,y2:40},zone={patternInstances:[]};
const first=model.create(zone,src,100,100,'base','a');
assert.deepEqual(first.instanceBbox,{x1:46,y1:10,x2:66,y2:40});
assert.equal(first.version,2);assert.equal(first.sourcePixelSnapshot,undefined);
zone.patternInstances.push(first);
const second=model.create(zone,src,100,100,'base','b');
assert.notDeepEqual(second.instanceBbox,first.instanceBbox);
assert.notDeepEqual(second.instanceBbox,src);
first.renderSourceBbox.x1=9;assert.equal(first.sourceBbox.x1,10);assert.equal(src.x1,10);
assert.equal(model.create({}, {x1:0,y1:0,x2:100,y2:100},100,100,'base','c'),null);
assert.equal(model.create({}, {x1:-1,y1:0,x2:10,y2:10},100,100,'base','c'),null);
const out={};first.sourcePixelSnapshot='wrong paint bytes';
payload.apply(out,{patternInstances:[first,{version:1,sourcePixelSnapshot:'legacy'}, {...second,muted:true}]});
assert.equal(out.material_instances.length,1);assert.equal(out.material_instances[0].sourcePixelSnapshot,undefined);
const hiddenSource={};payload.apply(hiddenSource,{patternInstances:[{...second,isSource:true,muted:true}]});
assert.equal(hiddenSource.material_instances.length,1,'hidden source retains footprint ownership metadata');
assert.equal(hiddenSource.material_instances[0].muted,true);
first.sourceBbox.x1=0;assert.equal(out.material_instances[0].sourceBbox.x1,10);
assert.deepEqual((()=>{let p={};payload.apply(p,{patternInstances:[]});return p;})(),{});
const api=fs.readFileSync('paint-booth-5-api-render.js','utf8'),canvas=fs.readFileSync('paint-booth-3-canvas.js','utf8');
assert.equal(api.split('SPBZoneMaterialInstancePayload?.apply(zoneObj, z)').length-1,3);
assert.equal(canvas.split('SPBZoneMaterialInstancePayload?.apply(zoneObj, z)').length-1,1);
assert(!canvas.includes('zoneObj.spec_pattern_instance_snapshots ='));
console.log('Zone material copies: separate placement, no-room rejection, immutable geometry, v2-only payload and all four builder hooks pass.');
