#!/usr/bin/env node
/* Shokker Paint Booth — MCP server (SPB-AI 2026-09-30)
 *
 * Lets Claude Desktop / Claude Code or Codex use the buyer's own assistant plan to design iRacing paints.
 * Pure Node, ZERO dependencies: a minimal MCP implementation (JSON-RPC 2.0 over stdio, newline-delimited).
 *
 *   Claude / Codex <--stdio MCP--> this process --HTTP 127.0.0.1:59876/api/mcp/call (pairing token)--> Shokker server --long-poll--> app page
 *
 * The app must be open (Pro mode) with "Let an AI assistant (Claude or ChatGPT/Codex) control Shokker Paint Booth" switched ON in the AI panel settings.
 * Env: SPB_PORT (default 59876), SPB_MCP_TOKEN_FILE (default %APPDATA%/ShokkerPaintBooth/mcp/token.txt).
 */
'use strict';
const http = require('http');
const fs = require('fs');
const os = require('os');
const path = require('path');

const VERSION = '1.0.0';
const PORT = Number(process.env.SPB_PORT) || 59876;
const SUPPORTED = ['2025-06-18', '2025-03-26', '2024-11-05'];
function log(...a) { try { process.stderr.write('[spb-mcp] ' + a.join(' ') + '\n'); } catch (e) { /* ignore */ } }

// ------------------------------------------------------------------ tools (descriptions + schemas come from the app itself: tools.json is generated by scripts/build_mcpb.py)
const SERVER_DIR = __dirname;
let GENERATED = [];
try { GENERATED = JSON.parse(fs.readFileSync(path.join(SERVER_DIR, 'tools.json'), 'utf8')); } catch (e) { log('tools.json missing: using the built-in minimal tool list'); }

const READ_ONLY = new Set(['spb_status', 'spb_get_state', 'spb_get_zones', 'spb_get_car_map', 'spb_preview', 'spb_design_recipes', 'spb_find_finishes', 'spb_suggest_finishes', 'spb_finish_details', 'spb_compare_finishes',
  'spb_browse_catalog', 'spb_find_patterns', 'spb_find_spec_patterns', 'spb_manual', 'spb_check_setup', 'spb_describe_paint', 'spb_look_at_paint']);
const NAME_MAP = { // MCP tool name -> app tool name
  spb_status: 'status', spb_get_state: 'get_state', spb_get_zones: 'zones', spb_get_car_map: 'get_car_map', spb_preview: 'preview', spb_request_parts: 'request_parts',
  spb_design_recipes: 'design_recipes', spb_apply_scheme: 'apply_scheme', spb_add_zone: 'add_zone', spb_edit_zone: 'edit_zone', spb_duplicate_zone: 'duplicate_zone', spb_edit_layer: 'edit_layer',
  spb_undo: 'undo', spb_suggest_finishes: 'suggest_finishes', spb_find_finishes: 'find_finishes', spb_finish_details: 'finish_details', spb_compare_finishes: 'compare_finishes', spb_browse_catalog: 'browse_catalog',
  spb_find_patterns: 'find_patterns', spb_find_spec_patterns: 'find_spec_patterns', spb_manual: 'get_help', spb_check_setup: 'check_setup', spb_add_graphic: 'add_graphic', spb_describe_paint: 'describe_paint', spb_refinish: 'refinish', spb_look_at_paint: 'look_at_paint', spb_mark_elements: 'mark_elements',
};
const STATIC_TOOLS = [
  { name: 'spb_status', description: 'FIRST CALL. Is Shokker Paint Booth connected? Returns the recognised car, the NAMED PARTS known on it (left side, right side, hood, roof, trunk, bumpers, spoiler with their position, front end and roof-line edge), key_parts_missing, the PSD layers and how many zones exist.', inputSchema: { type: 'object', properties: {} } },
  { name: 'spb_get_zones', description: 'Every zone with what it covers, how much of the paint it really wins (visible_pct) and its look. LOWER index = higher priority (wins overlaps).', inputSchema: { type: 'object', properties: {} } },
  { name: 'spb_preview', description: 'The live preview of the paint (a flat unwrapped car sheet) as an image, plus measured colour shares. spec=true adds the spec map picture (red = metal, teal = matte, black = gloss); parts=false skips the labelled parts map. LOOK at it after every change.', inputSchema: { type: 'object', properties: { spec: { type: 'boolean' }, parts: { type: 'boolean' } } } },
  { name: 'spb_request_parts', description: 'Ask the BUYER to show Shokker the parts of their car (drag a box around each part in the Shokker AI panel; once per car). Use when key_parts_missing is not empty. Returns immediately: tell the buyer to do it, then call spb_get_car_map again.', inputSchema: { type: 'object', properties: { parts: { type: 'array', items: { type: 'string' }, description: 'e.g. ["left side","right side","hood","roof"]' } } } },
  { name: 'spb_undo', description: 'Undo the last change(s) made through this bridge or the in-app copilot. steps = how many (default 1).', inputSchema: { type: 'object', properties: { steps: { type: 'number' } } } },
];
function allTools() {
  const seen = new Set(), out = [];
  for (const t of STATIC_TOOLS.concat(GENERATED)) { if (seen.has(t.name)) continue; seen.add(t.name); out.push({ name: t.name, description: t.description, inputSchema: t.inputSchema || { type: 'object', properties: {} }, annotations: { readOnlyHint: READ_ONLY.has(t.name), destructiveHint: false, openWorldHint: false } }); }
  return out;
}

const INSTRUCTIONS = [
  'You are driving Shokker Paint Booth (SPB), an app that designs iRacing car paints, through the spb_* tools.',
  'The paint is ONE flat 2048x2048 picture of the whole car cut open: two side panels, hood, roof, trunk, bumpers and spoiler lie flat. Place everything on NAMED PARTS (region {part:"left side"}), never on grid boxes; boxes over ~12% of the sheet are refused.',
  'Workflow: (1) spb_status. If key_parts_missing is not empty, call spb_request_parts and tell the buyer to show the parts in the Shokker panel, then re-check. (2) For liveries call spb_design_recipes, then spb_apply_scheme (one call lays out the whole scheme with exact bands; the first zone is the base colour). Use spb_add_zone / spb_edit_zone for tweaks, finishes and spec work. (3) After EVERY change look at the returned preview image and the problems_found_by_app list (measured: hidden zones, colours not showing) and fix them. (4) Report only what the tool results show; if something failed, say so.',
  'Band geometry: height = measured from the ROOF-LINE (0) down to the ROCKER (1) of a side panel; length = from the FRONT (0) to the REAR (1). Lower zone index = higher priority.',
  'Numbers, sponsors and logos stay untouched: the app limits whole-car looks to the body paint layers. Spec-only requests ("only the shine / metal", "keep the colours"): use a FOUNDATION finish (base::f_chrome for mirror chrome, base::f_satin_chrome, base::f_metallic, base::f_pearl, base::f_brushed, base::f_soft_matte, base::f_clear_satin, base::f_soft_gloss ...) on the zones that ALREADY cover the area (spb_edit_zone with the finish and NO color: their colour stays). color "source" shows the ORIGINAL template art, not the scheme you composed, so use it only on a bare template; on a part painted by lower zones give the colour showing there. ALWAYS check the returned preview and problems_found_by_app: if a colour changed, spb_undo. NEVER base::chrome / base::metallic / base::candy for that: they repaint the car. Never change colour, gradient or pattern.',
  'The catalogue has ~4,800 real finishes. To CHOOSE finishes call spb_suggest_finishes FIRST (part, goal, ask = the painter\'s own words; like + mods for "something like X but calmer / darker / glossier"; leave_out for what they do NOT want; exclude or page for more options): it ranks the whole catalogue for THIS car and returns look, why, loudness and an apply hint for every row. Use spb_find_finishes to search by meaning and spb_finish_details for a finish card (never invent finish keys). Spec maps: R = metal, G = roughness, B = clearcoat (16 = max gloss).',
  'CHANGING WHAT THE CAR ALREADY SHOWS (the usual job: the buyer loaded a finished livery and says "make the black matte", "the numbers purple and metallic", "the yellow powder coat looking", "make the white pearl"): call spb_describe_paint (the colours the paint really has, in words, plus the numbers / sponsors / stripes layers), then spb_refinish with target = a colour that is ON the car (or numbers / sponsors / stripes / a part), look = matte | satin | gloss | wet look | powder coat | plasti dip | cerakote | chrome | metallic | pearl | candy | brushed ..., colour = a NEW colour only if they want it repainted. A look alone changes only the finish; the paint colours stay exactly. Do NOT use spb_add_zone with everything / remaining for this: it hides the livery. NUMBERS / SPONSORS / STRIPES on a FLAT paint (no layers): the app\'s own finder is only proven on truck sheets, so call spb_look_at_paint (the flat paint with a 0.1 ruler + the app\'s guess), read where the numbers / logos / stripes really are (many paints have NO number drawn: say so), give them to spb_mark_elements as loose boxes [x0,y0,x1,y1] in fractions of the sheet, check the returned image, then spb_refinish target "numbers".',
  'Every change shows in the Shokker AI panel with an Undo button; use spb_undo to take back your last change.',
  'Prefer spb_edit_zone with zone_id from spb_get_zones, or an exact unique zone_name. When using an index, also pass expect_name and re-read zones if the guard fails. An editing lease prevents the in-app copilot from interleaving; the buyer may explicitly take over in SPB. If busy, wait rather than retrying writes blindly.',
  'Preview results include MCP image blocks. Describe a picture only if your client actually delivered it to you; otherwise use colour_shares_percent and zone visibility measurements and disclose that limitation.',
].join('\n');

const PROMPTS = [
  { name: 'design_livery', description: 'Design a paint scheme for the car open in Shokker Paint Booth.', arguments: [{ name: 'brief', description: 'What you want, e.g. "old-school Pepsi look, flat finish with chrome trim"', required: true }],
    text: (a) => 'Using Shokker Paint Booth, design this for my car: ' + (a.brief || 'a clean retro livery') + '\nFollow the Shokker workflow: spb_status, spb_request_parts if parts are missing, spb_design_recipes, spb_apply_scheme, then check the preview and fix any problems before you tell me it is done.' },
  { name: 'spec_only', description: 'Change only the shine / metal / roughness, never the paint colours.', arguments: [{ name: 'brief', description: 'e.g. "make the hood mirror chrome"', required: true }],
    text: (a) => 'Using Shokker Paint Booth, change ONLY the spec map (shine / metal / roughness), keep every paint colour exactly as it is: ' + (a.brief || '') + '\nUse a Foundation finish (base::f_chrome for mirror chrome, base::f_soft_matte for matte, base::f_clear_satin for satin ...) on the zones that already cover the part (edit them, leave color out so their colour stays; color "source" only on a bare template). Check spb_preview with spec=true afterwards and undo if any colour changed.' },
];

// ------------------------------------------------------------------ bridge call
function tokenFile() { return process.env.SPB_MCP_TOKEN_FILE || path.join(process.env.APPDATA || path.join(os.homedir(), 'AppData', 'Roaming'), 'ShokkerPaintBooth', 'mcp', 'token.txt'); }
function readToken() { try { return fs.readFileSync(tokenFile(), 'utf8').trim(); } catch (e) { return ''; } }
function httpJson(method, p, body, timeoutMs) {
  return new Promise((resolve, reject) => {
    const data = body ? Buffer.from(JSON.stringify(body)) : null;
    const req = http.request({ host: '127.0.0.1', port: PORT, path: p, method, headers: Object.assign({ 'X-SPB-MCP-Token': readToken() }, data ? { 'Content-Type': 'application/json', 'Content-Length': data.length } : {}) }, (res) => {
      const chunks = []; res.on('data', (c) => chunks.push(c));
      res.on('end', () => { const txt = Buffer.concat(chunks).toString('utf8'); let j = null; try { j = JSON.parse(txt); } catch (e) { /* not json */ } resolve({ status: res.statusCode, json: j, text: txt }); });
    });
    req.on('error', reject);
    req.setTimeout(timeoutMs || 130000, () => { req.destroy(new Error('timeout')); });
    if (data) req.write(data);
    req.end();
  });
}
function timeoutFor(app) { return ({ apply_scheme: 170, preview: 90, add_zone: 150, edit_zone: 150, duplicate_zone: 150, edit_layer: 90, undo: 90 })[app] || 60; }
function friendly(r) {
  const j = r.json || {};
  if (r.status === 401) return 'Shokker could not verify this connection (pairing token). In Shokker Paint Booth open the AI panel settings, switch ON "Let an AI assistant (Claude or ChatGPT/Codex) control Shokker Paint Booth", then restart your AI assistant (Claude or Codex).';
  if (r.status === 503 && j.error === 'disabled') return 'The AI bridge is switched OFF in Shokker Paint Booth. Ask the buyer to open the AI panel (settings gear) and switch on "Let an AI assistant (Claude or ChatGPT/Codex) control Shokker Paint Booth".';
  if (r.status === 503) return 'Shokker Paint Booth is not ready: open the app in Pro mode (the AI panel must be loaded) and try again.';
  if (r.status === 504) return j.message || 'Shokker did not answer in time.';
  return j.message || j.error || ('Shokker returned HTTP ' + r.status);
}
// a response over the size cap keeps VALID JSON: the longest lists are cut (60% at a time) and the cut is reported in _truncated
function fitJson(value, limit) {
  let text = JSON.stringify(value, null, 1) || '';
  if (text.length <= limit) return text;
  let clone; try { clone = JSON.parse(JSON.stringify(value)); } catch (e) { return text.slice(0, limit) + '\n...(truncated)'; }
  const cut = [];
  for (let guard = 0; guard < 80 && JSON.stringify(clone, null, 1).length > limit; guard++) {
    let best = null, bestLen = 0;
    (function walk(o, path) { if (Array.isArray(o)) { const l = JSON.stringify(o).length; if (o.length > 1 && l > bestLen) { best = { o, path }; bestLen = l; } o.forEach((x, i) => walk(x, path + '[' + i + ']')); } else if (o && typeof o === 'object') Object.keys(o).forEach(k => walk(o[k], path + '.' + k)); })(clone, '$');
    if (!best) break;
    const keep = Math.max(1, Math.floor(best.o.length * 0.6)); cut.push({ path: best.path, kept: keep, of: best.o.length }); best.o.length = keep;
  }
  const out = (clone && typeof clone === 'object' && !Array.isArray(clone)) ? Object.assign({}, clone, { _truncated: cut.slice(-6), _truncated_note: 'the response was too large: the lists above were cut to fit; ask again with narrower filters (or a page / exclude) to see the rest' }) : clone;
  let t2 = JSON.stringify(out, null, 1); if (t2.length > limit) t2 = t2.slice(0, limit) + '\n...(truncated)';
  return t2;
}
function toContent(res) {
  const content = []; let images = [];
  if (res && res.result && Array.isArray(res.result.images)) { images = res.result.images; res = Object.assign({}, res, { result: Object.assign({}, res.result, { images: undefined }) }); }
  const text = fitJson(res.result === undefined ? res : res.result, 24000);
  content.push({ type: 'text', text });
  for (const im of images) {
    const m = /^data:(image\/[a-z+.-]+);base64,(.*)$/i.exec(String(im.data_url || ''));
    if (m) { content.push({ type: 'text', text: 'image: ' + (im.name || 'picture') }); content.push({ type: 'image', data: m[2], mimeType: m[1] }); }
  }
  return content;
}
// ------------------------------------------------------------------ blind clients (WP8, 2026-10-03): ChatGPT connectors and some SDKs drop MCP image blocks
// SPB_MCP_BLIND_CLIENT = true | false | auto (default auto; or put the word in <token dir>/blind_client.txt). auto = the client's name (initialize clientInfo) is not in the allow-list.
const SIGHTED_CLIENTS = ['claude-code', 'claude-desktop', 'claude-ai', 'codex']; // claude-ai is what Claude Desktop / claude.ai report; codex matches codex-mcp-client etc. (prefix match)
const BLIND_TOOLS = new Set(['spb_look_at_paint', 'spb_mark_elements', 'spb_preview']);
let CLIENT = { name: '', version: '' };
function blindMode() {
  let v = String(process.env.SPB_MCP_BLIND_CLIENT || '').trim().toLowerCase();
  if (!v) { try { v = fs.readFileSync(path.join(path.dirname(tokenFile()), 'blind_client.txt'), 'utf8').trim().toLowerCase(); } catch (e) { v = ''; } }
  if (v === 'true' || v === '1' || v === 'yes' || v === 'on') return 'true';
  if (v === 'false' || v === '0' || v === 'no' || v === 'off') return 'false';
  return 'auto';
}
function isBlindClient() {
  const m = blindMode(); if (m === 'true') return true; if (m === 'false') return false;
  const n = String(CLIENT.name || '').toLowerCase();
  return !SIGHTED_CLIENTS.some((a) => n === a || n.startsWith(a));
}
const UNVERIFIED = 'UNVERIFIED: this client cannot see the paint; confirm in the app. Do not claim you saw the picture: say what the text below measured and ask the buyer to check Shokker Paint Booth.';
// the text stand-in for the pictures: describe_paint summary + the app's own finder guess (when the result carries one)
async function blindText(name, result) {
  const part = { notice: UNVERIFIED, tool: name };
  try {
    const r = await httpJson('POST', '/api/mcp/call', { tool: 'describe_paint', args: {}, timeout: 20 }, 35000);
    if (r.json && r.json.ok !== false && r.json.result !== undefined) part.describe_paint_summary = r.json.result;
  } catch (e) { part.describe_paint_summary = 'unavailable (' + (e && e.message) + ')'; }
  if (result && typeof result === 'object') {
    if (result.app_guess !== undefined) part.app_finder_guess = result.app_guess;
    else if (result.candidates !== undefined || result.kind !== undefined) part.app_finder_guess = { kind: result.kind, candidates: result.candidates, maybe_more: result.maybe_more };
    if (result.colour_shares_percent !== undefined) part.colour_shares_percent = result.colour_shares_percent;
  }
  return fitJson(part, 6000);
}
async function callTool(name, args) {
  const app = NAME_MAP[name];
  if (!app) return { isError: true, content: [{ type: 'text', text: 'Unknown tool ' + name }] };
  let r;
  try { r = await httpJson('POST', '/api/mcp/call', { tool: app, args: args || {}, timeout: timeoutFor(app) }, (timeoutFor(app) + 15) * 1000); }
  catch (e) { return { isError: true, content: [{ type: 'text', text: 'Could not reach Shokker Paint Booth on 127.0.0.1:' + PORT + ' (' + (e && e.message) + '). Is the app running?' }] }; }
  if (!r.json || r.status >= 400 || r.json.ok === false) return { isError: true, content: [{ type: 'text', text: friendly(r) }] };
  const content = toContent({ result: r.json.result });
  if (BLIND_TOOLS.has(name) && isBlindClient()) {
    content.push({ type: 'text', text: await blindText(name, r.json.result) });
    if (blindMode() === 'true') return { content: content.filter((c) => c.type !== 'image' && !/^image: /.test(c.text || '')) };
  }
  return { content };
}

// ------------------------------------------------------------------ MCP over stdio
function send(obj) { process.stdout.write(JSON.stringify(obj) + '\n'); }
function reply(id, result) { send({ jsonrpc: '2.0', id, result }); }
function fail(id, code, message) { send({ jsonrpc: '2.0', id, error: { code, message } }); }
async function handle(msg) {
  const { id, method, params } = msg;
  const isReq = id !== undefined && id !== null;
  try {
    switch (method) {
      case 'initialize': {
        const ci = (params && params.clientInfo) || {}; CLIENT = { name: String(ci.name || ''), version: String(ci.version || '') };
        log('client', JSON.stringify({ name: CLIENT.name, version: CLIENT.version }), 'blind_mode=' + blindMode(), 'blind=' + isBlindClient());
        const want = params && params.protocolVersion; const v = SUPPORTED.includes(want) ? want : SUPPORTED[0];
        return reply(id, { protocolVersion: v, capabilities: { tools: { listChanged: false }, prompts: { listChanged: false } }, serverInfo: { name: 'shokker-paint-booth', title: 'Shokker Paint Booth', version: VERSION }, instructions: INSTRUCTIONS });
      }
      case 'notifications/initialized': case 'notifications/cancelled': return;
      case 'ping': return reply(id, {});
      case 'tools/list': return reply(id, { tools: allTools() });
      case 'tools/call': { const out = await callTool(params && params.name, params && params.arguments); return reply(id, out); }
      case 'prompts/list': return reply(id, { prompts: PROMPTS.map((p) => ({ name: p.name, description: p.description, arguments: p.arguments })) });
      case 'prompts/get': {
        const p = PROMPTS.find((x) => x.name === (params && params.name)); if (!p) return fail(id, -32602, 'Unknown prompt');
        return reply(id, { description: p.description, messages: [{ role: 'user', content: { type: 'text', text: p.text((params && params.arguments) || {}) } }] });
      }
      case 'resources/list': return reply(id, { resources: [] });
      case 'resources/templates/list': return reply(id, { resourceTemplates: [] });
      default: if (isReq) return fail(id, -32601, 'Method not found: ' + method);
    }
  } catch (e) { if (isReq) fail(id, -32603, String(e && e.message || e)); else log('error', String(e && e.message || e)); }
}
let buf = '';
process.stdin.setEncoding('utf8');
process.stdin.on('data', (chunk) => {
  buf += chunk; let i;
  while ((i = buf.indexOf('\n')) >= 0) {
    const line = buf.slice(0, i).trim(); buf = buf.slice(i + 1); if (!line) continue;
    let msg; try { msg = JSON.parse(line); } catch (e) { log('bad json'); continue; }
    if (Array.isArray(msg)) msg.forEach((m) => handle(m)); else handle(msg);
  }
});
process.stdin.on('end', () => process.exit(0));
log('ready, bridge port', PORT);
