"""ASTRA R2 catalogue: names, lanes, published copy and identity contracts.

SPB-105 / ASTRA-R2 2026-09-27 (Claude). Owner: the R1 rebuild was "surprisingly
AWFUL" - rebuild every ASTRA finish so it is UNIQUE, JUMPS OFF THE SCREEN, is
as intricate as possible and does what its name says. Stable ids and names are
kept; every construction was replaced. Constructions live in the five lane
modules (originals / color_shoxx / surfs_up / mad_scientist / future_shoxx),
all built on kit.py. R1 sources are archived in _astra_claude_work/r1_backup/.

`adopt(module_name, fid)` turns one of the fifty stable per-finish modules into
a live finish: FID/NAME/LANE/DESCRIPTION/SWATCH/IDENTITY_CONTRACT plus build(),
paint() and spec() bound through common.bind (one authored seed, one native
2048 build shared by paint and spec).
"""
import sys
import importlib
import cv2
import numpy as np
from .common import bind, contract

W = 'https://en.wikipedia.org/wiki/'
O, C, S, M, F = 'ASTRA ORIGINALS', 'COLOR SHOXX', 'SURFS UP', 'MAD SCIENTIST', 'FUTURE SHOXX'

# key: (lane module, name, lane, published description, construction grammar,
#       spec grammar, marks [(name, role)], neighbours [(fid, difference)], source)
TABLE = {
'event_horizon': ('originals', 'Event Horizon', O,
    'A field of tiny black holes: absorbing shadows, chrome photon rings, Doppler-bright accretion discs and polar jets over a lensed starfield.',
    'Voronoi-placed black holes; inclined turbulent discs with Doppler beaming; lensed far-disc halo; gravitationally displaced starfield',
    'shadow M0/R255/Cc255 void; photon ring M255/R16/Cc16; disc foil M170-255/R24-94; nebula pearl M30-240 by density',
    [('event_shadow', 'absorbing matte void inside every hole'), ('photon_ring', 'one-pixel chrome ring at the shadow edge'),
     ('accretion_disc', 'Doppler-beamed turbulent orbit streaks'), ('lensed_halo', 'far-side disc image hugging the shadow'),
     ('polar_jet', 'rare thin relativistic jets'), ('lensed_stars', 'starfield displaced around every mass')],
    [('astra_velvet_supernova', 'remnant shells on velvet, not discs on space')], W + 'Black_hole#Photon_sphere'),
'quasicrystal_crown': ('originals', 'Quasicrystal Crown', O,
    'Five-fold quasicrystal interference drawn as gold contour filigree over royal enamel, with ten-fold gold crowns and cabochon gems.',
    'Sum of five plane waves at 72 degrees per polycrystal grain; iso-contour filigree; crowns at maxima; gems at minima; seven-fold engraving',
    'enamel M25-110/R22-58/Cc16-38; filigree M255/R20/Cc220; crowns M250/R18-58; gems M110/R16/Cc16',
    [('contour_filigree', 'gold iso-lines of the quasiperiodic field'), ('ten_fold_crown', 'domed gold at interference maxima'),
     ('cabochon_gem', 'ruby/aqua/amber gems at minima'), ('royal_enamel', 'sapphire enamel graded by level'),
     ('grain_seam', 'chrome seams between crystal grains'), ('micro_engraving', 'seven-fold wave engraving on crowns')],
    [('astra_chronograph_gold', 'guilloche panels, not quasiperiodic contours')], W + 'Quasicrystal'),
'gravity_loom': ('originals', 'Gravity Loom', O,
    'A 2/2 twill of metallic silk pulled into gravity wells: threads bend, redshift and sink toward tiny stars ringed by Einstein rings.',
    'Twill weave in coordinates displaced by a field of point masses; cylindrical thread shading; Einstein rings; star cores',
    'warp silk M185-255/R34-114; weft satin M25-70/R110-190/Cc16-42; wells duller; rings and stars M255/R16/Cc16',
    [('warp_thread', 'jade metallic silk running one way'), ('weft_thread', 'midnight satin crossing under/over'),
     ('gold_thread', 'rare mirror-gold warps'), ('gravity_well', 'sinking redshifted weave around masses'),
     ('einstein_ring', 'bright lensing ring around each mass'), ('star_core', 'tiny glowing mass at each well')],
    [('astra_polarity_lace', 'field-line lace, not a woven twill')], W + 'Gravitational_lens'),
'phoenix_ceramic': ('originals', 'Phoenix Ceramic', O,
    'Raku kintsugi: smoke-stained crackle inside a coarse fracture net, raised gold repair seams and copper-luster flame tongues.',
    'Two-scale Voronoi craquelure; gold seams on the coarse net; domain-warped fire field with iso-contour feather tongues; pinholes',
    'glaze M5-23/R20-34/Cc16; crackle R190/Cc206; luster M110-223; feather edges M250/R18; gold seams M255/R18-52',
    [('crackle_glaze', 'fine smoke-stained crackle cells'), ('gold_seam', 'raised kintsugi repair lines'),
     ('copper_luster', 'iridescent fire-flash zones'), ('feather_tongue', 'contour tongues rising in the flame'),
     ('glaze_pinhole', 'dark firing pinholes'), ('ivory_glaze', 'celadon-to-ivory glaze body')],
    [('astra_volcanic_break', 'glowing basalt joints, not glazed ceramic')], W + 'Kintsugi'),
'sovereign_nacre': ('originals', 'Sovereign Nacre', O,
    'Paua nacre: swirling interference colour, growth-line terraces every few pixels, a shimmering tablet mosaic and blister pearls.',
    'Domain-warped growth height; cosine interference colour; iso-line terraces; 9 px aragonite tablets; dome pearls',
    'tablets M95-250/R16-58 by tier; growth lines R96/Cc56; pearls M80-140/R16/Cc16',
    [('growth_terrace', 'terraced growth bands'), ('growth_line', 'dark iso-lines between terraces'),
     ('aragonite_tablet', '9 px shimmering tablet cells'), ('interference_flash', 'bright interference flashes'),
     ('blister_pearl', 'domed pearls with specular highlights')],
    [('astra_bismuth_delirium', 'stepped hopper crystals, not nacre terraces')], W + 'Nacre'),
'magnetic_regalia': ('originals', 'Magnetic Regalia', O,
    'Ferrofluid under magnets: black-chrome Rosensweig spike crowns rise at the poles, gold iron-filing dashes trace every field line.',
    'Dipole stream function iso-lines as dashed filings; hex spike lattices per domain where field density is high; gold crown rims',
    'fluid M70/R26/Cc16; spikes M255/R16-60; filings M230/R90/Cc230',
    [('rosensweig_spike', 'hex lattice of chrome spikes'), ('iron_filing', 'dashed gold field-line filings'),
     ('crown_rim', 'gold rim where the spike field begins'), ('wet_fluid', 'glossy black ferrofluid'),
     ('spike_tip', 'white glints on spike tips'), ('lattice_domain', 'domains with rotated spike lattices')],
    [('astra_polarity_lace', 'coloured field+equipotential lace, not spikes and filings')], W + 'Ferrofluid'),
'meteorite_royal': ('originals', 'Meteorite Royal', O,
    'An etched iron meteorite: Widmanstaetten lamellae in three directions etched gold, royal blue and violet, each its own material, with taenite rims and plessite fill.',
    'Three octahedral lamella directions per parent crystal with random widths/gaps; per-direction reflectance; Neumann lines',
    'gold lamellae matte M30-52/R120-190; blue lamellae polished M238-260/R16-90; violet lamellae M150-172/R60-140; taenite M255/R16; plessite M160-190/R170-210',
    [('kamacite_lamella', 'broad etched metal bands'), ('taenite_rim', 'bright thin band borders'),
     ('plessite_fill', 'dark speckled triangles'), ('neumann_line', 'fine shock lines'),
     ('royal_tint', 'gold/royal-blue/violet heat tint per direction')],
    [('astra_cobalt_guillotine', 'coloured slats in cut shards, not lamellae')], W + 'Widmanst%C3%A4tten_pattern'),
'cryogenic_bloom': ('originals', 'Cryogenic Bloom', O,
    'Six-fold ice dendrites bloom from hundreds of nuclei over crystalline rime, glassy ice against frost with cold violet plasma.',
    'Fern-branched hexagonal dendrites drawn per nucleus; micro-facet rime Voronoi; blurred cold halos; plasma selector',
    'rime M30-90/R110-170/Cc150-200; halo lower R; dendrites M150/R16/Cc16',
    [('ice_dendrite', 'six-fold fern-branched crystals'), ('side_branch', 'secondary fern branches'),
     ('frost_rime', '7 px crystalline micro-facets'), ('cold_halo', 'blue glow around crystals'),
     ('cryo_plasma', 'violet glow in hidden regions')],
    [('astra_neuron_carnival', 'coloured neurons, not ice dendrites')], W + 'Dendrite_(crystal)'),
'chronograph_gold': ('originals', 'Chronograph Gold', O,
    'Watchmaker gold: panels engine-turned in six guilloche patterns, polished chamfers, ruby jewels in chatons and toothed wheels.',
    'Voronoi dial panels; per-panel sunburst/concentric/clous de Paris/rosette/flinque/perlage; bevels; jewels; gear rims',
    'gold M245-255/R16-100 by groove; lacquered panels Cc16; rubies M0/R16/Cc16; wheels R16',
    [('guilloche_groove', 'engine-turned grooves per panel'), ('polished_chamfer', 'bright bevels between panels'),
     ('ruby_jewel', 'domed ruby bearings'), ('gold_chaton', 'rings holding the jewels'),
     ('toothed_wheel', 'gear rims around some jewels'), ('perlage', 'overlapping circular graining')],
    [('astra_quasicrystal_crown', 'quasiperiodic filigree, not turned panels')], W + 'Guilloch%C3%A9'),
'velvet_supernova': ('originals', 'Velvet Supernova', O,
    'Plum panne velvet strewn with supernova remnants: knotty filament shells, synchrotron cores and diffraction-spiked neutron stars.',
    'Nap-angle sheen velvet; Voronoi-placed remnants with fbm-knotted shells (some bipolar); inner glow; star spikes',
    'velvet M4-14/R150-250/Cc225-255; shells M185-240/R25-55; cores M140/R90; stars M255/R16/Cc16',
    [('panne_velvet', 'nap-angle sheen with crease lines'), ('shock_shell', 'knotty filament shell'),
     ('inner_shell', 'second inner filament'), ('synchrotron_core', 'blue inner glow'),
     ('neutron_star', 'diffraction-spiked glint'), ('pile_star', 'tiny star speckle')],
    [('astra_event_horizon', 'black holes with discs, not remnants on velvet')], W + 'Supernova_remnant'),
'janus_blades': ('color_shoxx', 'Janus Blades', C,
    'Dense sheaves of two-faced blades on a flow: a scarlet matte-lacquer face and a cobalt brushed-metal face split by a chrome spine.',
    'Thousands of leaf blades stamped along a flow field; spine split offset by a hidden field; heel collars; gunmetal gaps',
    'lacquer face M0-22/R160-215; metal face M238-255/R26-74; spine M255/R16/Cc16; gaps M40/R34',
    [('lacquer_face', 'scarlet matte face'), ('metal_face', 'cobalt brushed face'), ('chrome_spine', 'split line down each blade'),
     ('heel_collar', 'dark collar at the blade heel'), ('sheaf_gap', 'gunmetal gaps between blades')],
    [('astra_tachyon_feather', 'iridescent feathers, not split blades')], W + 'Janus'),
'scarlet_undertow': ('color_shoxx', 'Chromatic Undertow', C,
    'Rip-current bands curl into hooks around hundreds of vortices, turquoise metal against vermilion enamel with pale eddy lips.',
    'Stream function of drift plus point vortices; banded duty cycle set by a hidden field; ink separators; vortex lips',
    'enamel M0-18/R140-230; metal M232-255/R30-110; ink R235; lips M255/R16',
    [('turquoise_current', 'metal bands'), ('vermilion_current', 'enamel bands'), ('ink_line', 'band separators'),
     ('eddy_lip', 'pale rings at vortex cores'), ('undertow_field', 'hidden duty-cycle regions')],
    [('astra_pipeline_royale', 'breaking wave rows, not marbled currents')], W + 'Rip_current'),
'cobalt_guillotine': ('color_shoxx', 'Spectrum Guillotine', C,
    'Shutter slats sliced by guillotine cuts into shards knocked to new angles, lime lacquer and amethyst metal, every cut burning a spectrum.',
    'Arrangement of 38 straight cuts; per-shard slat angle/period/offset; duty cycle field; spectral cut lines with shadow',
    'lacquer M0-24/R150-244; metal M230-255/R22-100; cuts M255/R16/Cc16',
    [('lime_slat', 'lacquer slats'), ('amethyst_slat', 'metal slats'), ('guillotine_cut', 'spectral cut lines'),
     ('cut_shadow', 'shadow along each cut'), ('shard', 'polygon regions with their own slat angle')],
    [('astra_meteorite_royal', 'etched lamellae, not coloured slats')], W + 'Guillotine'),
'chromatic_switchyard': ('color_shoxx', 'Chromatic Switchyard', C,
    'A switchyard drawn as a transit map: yellow-lacquer and cobalt-metal lanes with sleepers, 45-degree crossovers and white roundels.',
    'Voronoi yards with their own heading; parallel lanes; crossover ramps; sleepers; stations',
    'lacquer lanes M0-18/R24-150; metal lanes M235-255/R26-130; ballast R225; roundels M0/R16',
    [('yellow_lane', 'lacquer track lanes'), ('cobalt_lane', 'metal track lanes'), ('crossover', '45-degree switches'),
     ('sleeper', 'fine ties across each lane'), ('station_roundel', 'white stations with black rings')],
    [('astra_klein_circuit', 'PCB buses, not transit lanes')], W + 'Rail_yard'),
'ruby_blue_cyclone': ('color_shoxx', 'Bipolar Cyclone', C,
    'A weather map of small cyclones spinning both ways: ruby-lacquer and ice-metal spiral arms, chrome eyes and dark shear wakes.',
    'Voronoi storms; log-spiral arms whose sign sets ruby/ice lead; wakes at storm borders; eyes',
    'ruby M0-20/R150-245; ice M236-255/R24-110; wakes R230; eyes M255/R16',
    [('ruby_arm', 'lacquer spiral arms'), ('ice_arm', 'metal spiral arms'), ('storm_eye', 'chrome eye and ring'),
     ('shear_wake', 'dark borders between storms'), ('spin_sign', 'clockwise vs counter-clockwise storms')],
    [('astra_chromatic_centrifuge', 'rotors with tubes, not spiral storms')], W + 'Cyclone'),
'prism_rebellion': ('color_shoxx', 'Prism Rebellion', C,
    'A shattered prism wall: warped triangular shards, some split finer, amber glass against violet metal, every edge dispersed into RGB.',
    'Warped triangular lattice with rebel subdivision; per-shard graded light; hidden violet share; RGB-split edges',
    'amber M0-26/R130-260; violet M225-255/R20-130; fringes M255/R16; edges R220',
    [('amber_shard', 'glass shards'), ('violet_shard', 'metal shards'), ('rebel_split', 'finer subdivided shards'),
     ('rgb_fringe', 'dispersed edge fringes'), ('shard_gradient', 'light graded across each shard')],
    [('astra_causal_origami', 'fold tessellation, not shards')], W + 'Dispersive_prism'),
'redshift_rivets': ('color_shoxx', 'Dichroic Rivets', C,
    'Studded dichroic armour: hex-packed domed rivet heads shifting rose to gold to turquoise with slope, washers and empty sockets.',
    'Hex-packed domes on a warped row flow; slope-driven dichroic colour; hidden rose/turquoise populations; washers; sockets',
    'rose heads M10-40/R30-110; turquoise heads M235-255/R18-90; plate M170/R150; washers M250/R60',
    [('rose_head', 'lacquer dichroic domes'), ('turquoise_head', 'metal dichroic domes'), ('washer', 'polished washer rings'),
     ('empty_socket', 'dark empty rivet holes'), ('gunmetal_plate', 'dark plate between heads')],
    [('astra_temporal_braille', 'braille pins, not armour studs')], W + 'Dichroic_glass'),
'blueblood_chevron': ('color_shoxx', 'Switchblade Chevron', C,
    'Chevron parquet in bands of random height, cobalt metal against gold lacquer, switchblade columns flipped open on chrome pins.',
    'Random-height bands; chevron stripes with duty field; flipped columns; bolster edges; pivot pins',
    'gold M0-18/R150-241; cobalt M240-255/R28-108; bolsters M255/R120; pins M255/R16',
    [('gold_chevron', 'lacquer V stripes'), ('cobalt_chevron', 'metal V stripes'), ('switch_column', 'columns flipped the other way'),
     ('pivot_pin', 'chrome pins on flipped columns'), ('band_bolster', 'polished band edges')],
    [('astra_duality_scales', 'imbricated scales, not chevrons')], W + 'Chevron_(insignia)'),
'duality_scales': ('color_shoxx', 'Duality Scales', C,
    'Imbricated scales on curving rows, each with a lime-lacquer tip and a plum-metal root, a hidden field dithering which leads.',
    'Overlapping scale rows in warped coordinates; per-scale split; dithered lead flip; rims and keels',
    'lime M0-22/R150-255; plum M228-255/R22-110; rims M255/R16/Cc40',
    [('lime_tip', 'lacquer half of each scale'), ('plum_root', 'metal half of each scale'), ('scale_rim', 'polished free edge'),
     ('scale_keel', 'centre keel line'), ('lead_dither', 'regions leaning lime or plum')],
    [('astra_blueblood_chevron', 'chevron parquet, not scales')], W + 'Scale_(anatomy)'),
'polarity_lace': ('color_shoxx', 'Polarity Lace', C,
    'Lace woven from electrostatics: coral field-line threads and jade equipotential threads crossing in gold knots over navy openwork.',
    'Hundreds of +/- charges; field lines via cos(m psi); equipotential iso-lines; medallions where lines crowd; knots',
    'coral M0-16/R60-110; jade M225-255/R30-70; openwork R235; knots M255/R16',
    [('field_thread', 'coral field-line threads'), ('equipotential_thread', 'jade equipotential threads'),
     ('lace_knot', 'gold knots at crossings'), ('charge_medallion', 'ringed medallions at charges'),
     ('openwork', 'navy gaps between threads')],
    [('astra_magnetic_regalia', 'ferrofluid spikes and filings, not two-colour lace')], W + 'Field_line'),
'pipeline_royale': ('surfs_up', 'Pipeline Royale', S,
    'Rows of peeling surf barrels: navy trough to glassy green lip, white foam and spray, dark tubes opening under the throw.',
    'Swell rows with peeling crest lines; face gradient; lips; spray; barrel tubes; ripple facets',
    'water M60-150/R18-52/Cc16; foam M0/R215/Cc230; tube M20/R60',
    [('wave_face', 'turquoise face gradient'), ('foam_lip', 'white lip on every crest'), ('barrel_tube', 'dark tube under the lip'),
     ('spray', 'white spray above the lip'), ('ripple_facet', 'fine ripple facets')],
    [('astra_scarlet_undertow', 'marbled currents, not breaking waves')], W + 'Tube_riding'),
'reef_cathedral': ('surfs_up', 'Reef Cathedral', S,
    'Brain-coral naves from a reaction-diffusion labyrinth, coral ridges over teal grooves, star polyps and sunlit caustics.',
    'Activator/inhibitor labyrinth; rounded ridges with relief; star polyps on ridges; caustic net',
    'ridges M10/R50-130/Cc40; grooves R210/Cc220; polyps M40/R30; caustics M50/R40',
    [('coral_ridge', 'meandering ridges'), ('coral_groove', 'teal shadow grooves'), ('star_polyp', 'eight-armed polyps'),
     ('polyp_core', 'bright polyp centres'), ('caustic_net', 'sunlight caustics')],
    [('astra_quantum_petri', 'colonies, not brain coral')], W + 'Brain_coral'),
'tidal_lace': ('surfs_up', 'Tidal Lacework', S,
    'The lace a retreating wave leaves: a thick white foam net torn open in patches over orange-gold sand and water that deepens from aqua to cobalt-indigo.',
    'Two-scale Voronoi foam walls modulated by a dissipation field; depth colour; caustics',
    'polished water M190-230/R16-70/Cc16-56; matte sand M10/R200/Cc230; matte foam M0/R170-210/Cc215',
    [('foam_wall', 'bubble walls'), ('fine_foam', 'small bubble net'), ('shallow_water', 'turquoise shallows'),
     ('wet_sand', 'golden sand patches'), ('caustic_light', 'bright caustics')],
    [('astra_sea_glass_confessional', 'leaded glass cells, not foam')], W + 'Sea_foam'),
'surf_wax_ritual': ('surfs_up', 'Surf Wax Ritual', S,
    'Fresh wax on a board: domed wax beads rubbed up in circles over a glowing tropical basecoat, comb crosshatch and sand grains.',
    'Voronoi wax beads with dome shading; basecoat in valleys; combed crosshatch patches; sand',
    'wax M0-10/R115-225/Cc185-235; basecoat valleys M20/R22/Cc16; sand M200/R50',
    [('wax_bead', 'domed wax bumps'), ('basecoat', 'tropical colour in the valleys'), ('comb_groove', 'crosshatch gouges'),
     ('sand_grain', 'metallic sand specks'), ('rub_swirl', 'circular rub marks')],
    [('astra_cytokinesis_candy', 'candy cells, not wax beads')], W + 'Surf_wax'),
'wipeout_paisley': ('surfs_up', 'Wipeout Paisley', S,
    'Psychedelic surf paisley: packed curled boteh at every size and angle, echo bands, beaded borders and inner eyes on a dot print.',
    'Boteh outlines filled as id polygons; distance-to-edge echo bands; beads; eyes; micro-dot ground',
    'bands M40-240 by colour/R170-40 by brightness; outlines R235; ground R130-210',
    [('boteh', 'curled teardrop motifs'), ('echo_band', 'nested colour bands'), ('bead_border', 'white beads on the border'),
     ('boteh_eye', 'dark eye with a gold pupil'), ('dot_ground', 'micro-dot print ground')],
    [('astra_quantum_petri', 'round colonies, not paisley')], W + 'Paisley_(design)'),
'kelp_couture': ('surfs_up', 'Kelp Couture', S,
    'A kelp forest cut as couture: three depths of translucent ruffled ribbons with gold midribs, float pearls and sequin glints.',
    'Three layers of flow-following ribbon polygons; edge-distance shading and veins; midribs; floats; sequins',
    'blades M20-60/R40-100/Cc16-56; midribs M220/R30; floats M90/R16; sequins M255/R16',
    [('kelp_ribbon', 'ruffled blade'), ('gold_midrib', 'gold centre rib'), ('blade_vein', 'fine parallel veins'),
     ('float_pearl', 'gas float bulbs'), ('sequin_glint', 'sparse glints')],
    [('astra_tachyon_feather', 'feathers, not kelp ribbons')], W + 'Kelp_forest'),
'boardwalk_pinlines': ('surfs_up', 'Boardwalk Pinlines', S,
    'A painted boardwalk: every plank a faded beach-hut colour with grain, wear-through and nails, coach-lined in its complement colour with cream clothoid sign-painter flourishes.',
    'Plank grid with grain iso-lines; coachlines inset from every plank edge; mirrored clothoid flourishes',
    'warm planks matte M0-10/R150-215/Cc225-235; cool planks pearl M150-180/R100-160/Cc110-130; metallic pinlines and flourishes M235/R40/Cc50; nails M220',
    [('plank', 'bleached boards'), ('plank_gap', 'dark gaps'), ('coachline', 'double pinline per plank'),
     ('clothoid_flourish', 'mirrored pinstripe scrolls'), ('nail_head', 'nail heads at plank ends')],
    [('astra_orbitless_navigation', 'rhumb lines on a chart, not planks')], W + 'Pinstriping'),
'volcanic_break': ('surfs_up', 'Volcanic Break', S,
    'A surf break over basalt: hexagonal column tops, lava glowing through hidden joints, teal tide in the low columns, foam at the waterline.',
    'Near-hex Voronoi columns with per-column height; lava joints in a selector; tide below a water level; shoreline foam',
    'basalt M60-100/R110-230; water M40/R20/Cc16; foam R200; lava M230/R26',
    [('basalt_column', 'bevelled column tops'), ('lava_joint', 'glowing joints'), ('tide_pool', 'teal water in low columns'),
     ('shore_foam', 'white foam at the waterline'), ('column_crack', 'fine fractures')],
    [('astra_phoenix_ceramic', 'glazed crackle, not basalt')], W + 'Columnar_jointing'),
'abyssal_lanterns': ('surfs_up', 'Abyssal Lanterns', S,
    'The deep lit only by its animals: amber, magenta and coral jellies with trailing tentacles, light chains and plankton sparks in polished indigo water.',
    'Voronoi-placed jellies with ribbed bells, rims and tentacles; blurred glow; random-walk light chains; plankton',
    'polished water M225-255/R22-62/Cc16-56; matte-gel animals M0-8/R150-200/Cc200-250 (spec is the colour-opposite of the paint)',
    [('jelly_bell', 'ribbed glowing bell'), ('bell_rim', 'bright rim'), ('tentacle', 'trailing glow lines'),
     ('light_chain', 'siphonophore chains'), ('plankton_spark', 'bioluminescent specks')],
    [('astra_neuron_carnival', 'neurons, not jellies')], W + 'Bioluminescence'),
'sea_glass_confessional': ('surfs_up', 'Sea Glass Confessional', S,
    'A backlit confessional window of sea glass: saturated frosted pebbles in strong regional colour families (kelly, cobalt, amber, aqua), dark leading and a lattice screen shadow.',
    'Voronoi pebbles inset from lead; frosted rounded rims; sea-glass palette frequencies; lattice shadow',
    'warm glass matte M10-35/R150-240/Cc225; cool glass polished M212-242/R25-115/Cc40-100; lead M200/R16',
    [('sea_glass_pebble', 'frosted pebble'), ('lead_came', 'dark leading'), ('frost_rim', 'glowing rounded rim'),
     ('pitting', 'frost pitting'), ('lattice_shadow', 'confessional screen shadow')],
    [('astra_tidal_lace', 'foam net, not glass')], W + 'Sea_glass'),
'cytokinesis_candy': ('mad_scientist', 'Cytokinesis Candy', M,
    'A tissue of hard-candy cells mid-mitosis: resting cells with speckled nuclei, dividing peanuts with two nuclei and glowing spindles.',
    'Voronoi cells as circles or smooth-min peanuts; nuclei; spindle fibres; candy highlights; jelly',
    'candy R30-200 by depth; nuclei M120/R60; spindles M255/R16; jelly Cc216',
    [('candy_cell', 'glossy cell'), ('cleavage_furrow', 'pinched dividing cell'), ('daughter_nucleus', 'speckled nucleus'),
     ('spindle_fibre', 'glowing fibres'), ('matrix_jelly', 'dark extracellular jelly')],
    [('astra_xenobot_orchard', 'Pac-Man bots in rows, not dividing cells')], W + 'Cytokinesis'),
'quantum_petri': ('mad_scientist', 'Quantum Petri Carnival', M,
    'Bacterial colonies on amber agar: quantised growth rings, pinwheel cores, fractal fingering rims and clear inhibition zones.',
    'Voronoi colonies with fbm-fingered radius; quantised rings; pinwheels; inhibition zones; satellites',
    'colonies M60-180 by tier, R follows brightness; agar R by brightness; edges R200',
    [('growth_ring', 'quantised colony rings'), ('pinwheel_core', 'angular stripes at the core'), ('fingered_rim', 'fractal colony edge'),
     ('inhibition_zone', 'clear halo'), ('satellite_colony', 'tiny colonies')],
    [('astra_wipeout_paisley', 'paisley, not colonies')], W + 'Bacterial_colony'),
'chromosome_riot': ('mad_scientist', 'Chromosome Riot', M,
    'A spectral karyotype rioting: X chromosomes at every angle, pinched centromeres, fluorescent hues, G-bands and telomere caps.',
    'Four capsule arms per chromosome stamped by id; per-arm banding along length; centromere; telomeres',
    'arms M90-240/R30-170 across; bands R+60; telomeres M255/R16; ground R200',
    [('chromatid_arm', 'rounded arm'), ('g_band', 'dark bands along arms'), ('centromere', 'pinched centre'),
     ('telomere_cap', 'white tips'), ('dapi_ground', 'blue darkness with haze')],
    [('astra_janus_blades', 'split blades, not chromosomes')], W + 'Karyotype'),
'plasma_sutures': ('mad_scientist', 'Plasma Sutures', M,
    'Incisions in an iridescent membrane stitched shut with violet-white plasma cross-stitches, Lichtenberg arcs and cauterised edges.',
    'Flow-field streamline incisions; cross-stitches per segment; random-walk arcs; blurred glow; thin-film membrane',
    'membrane M150-230/R follows brightness; cuts R250; glow M220/R30; stitches M255/R16',
    [('incision', 'dark cut lines'), ('plasma_stitch', 'glowing cross-stitches'), ('lichtenberg_arc', 'branching discharges'),
     ('cautery_burn', 'burned edges'), ('iridescent_membrane', 'thin-film skin')],
    [('astra_fermion_foundry', 'particle tracks, not stitches')], W + 'Lichtenberg_figure'),
'bismuth_delirium': ('mad_scientist', 'Bismuth Delirium', M,
    'An aggregate of bismuth hopper crystals: square stair-stepped spirals sinking to hollow centres in shifting oxide colours.',
    'Voronoi crystals; Chebyshev terraces with optional spiral; thin-film oxide by height; metal lips',
    'metal M235-255; R follows oxide brightness 20-150; lips M255/R16',
    [('hopper_terrace', 'square step'), ('spiral_stair', 'spiralling steps'), ('oxide_film', 'interference colours'),
     ('metal_lip', 'bright step edge'), ('crystal_boundary', 'dark joins')],
    [('astra_sovereign_nacre', 'nacre swirls, not hoppers')], W + 'Bismuth#Characteristics'),
'strange_attractor': ('mad_scientist', 'Strange Attractor', M,
    'Specimens of chaos: real Clifford and de Jong attractors iterated into glowing filament galaxies, rotated across a phase-space grid.',
    'Six attractors iterated ~450k points each; density and orbit-speed maps; rotated/mirrored specimens; grid',
    'filaments M40-250/R20-170/Cc20-200 by density',
    [('filament_density', 'bright visit density'), ('orbit_speed_hue', 'colour by orbit speed'), ('specimen', 'rotated attractor copies'),
     ('phase_grid', 'faint grid'), ('glow_halo', 'soft glow')],
    [('astra_neuron_carnival', 'branching neurons, not attractors')], W + 'Attractor#Strange_attractor'),
'neuron_carnival': ('mad_scientist', 'Neuron Carnival', M,
    'A Brainbow tangle: hundreds of neurons each its own fluorescent colour, glowing somata, three-level dendrites and bouton-studded axons.',
    'Recursive random-walk dendrites; long axons with boutons; per-neuron hue; glow',
    'neuropil M40-140/R60-180; processes M230/R20; somata M255/R16',
    [('soma', 'glowing cell body'), ('dendrite', 'branching processes'), ('axon', 'long fibre'), ('bouton', 'synaptic beads'),
     ('brainbow_hue', 'per-neuron colour')],
    [('astra_cryogenic_bloom', 'ice dendrites, not neurons')], W + 'Brainbow'),
'xenobot_orchard': ('mad_scientist', 'Xenobot Orchard', M,
    'An orchard of xenobots: lime, cyan and hot-pink frog-cell spheres with Pac-Man mouths and cilia fringes on oxblood soil, with gold cell piles for their offspring.',
    'Orchard grid with drift; per-bot radius and mouth; Voronoi cell texture; cilia; piles',
    'pearl-metal bots M120-190/R40-130; cilia M210/R30; piles M240/R30; matte soil M12/R205/Cc230',
    [('xenobot_body', 'multicellular sphere'), ('pacman_mouth', 'open wedge'), ('cilia_fringe', 'beating hairs'),
     ('cell_pile', 'gathered cells'), ('orchard_row', 'drifting rows')],
    [('astra_cytokinesis_candy', 'dividing candy cells, not bots')], W + 'Xenobot'),
'fermion_foundry': ('mad_scientist', 'Fermion Foundry', M,
    'A bubble chamber in a furnace: orange-gold and cyan tracks colour-coded by momentum curl into tightening spirals over glowing oxblood iron.',
    'Collision vertices; tracks with growing curvature (energy loss spirals); V decays; fiducial crosses; bubbles',
    'matte furnace ground M12-37/R140-200/Cc200-230; polished tracks M255/R16/Cc16; glow M200/R60; bubbles M0/R16',
    [('positive_track', 'gold spirals'), ('negative_track', 'cyan spirals'), ('v_decay', 'forked decay tracks'),
     ('fiducial_cross', 'reference crosses'), ('chamber_bubble', 'bubble speckle')],
    [('astra_plasma_sutures', 'stitches, not tracks')], W + 'Bubble_chamber'),
'chromatic_centrifuge': ('mad_scientist', 'Chromatic Centrifuge', M,
    'Lathe-turned rotors carrying rings of sample tubes spun into density-gradient colour bands, pellets at the rim, polished hubs.',
    'Voronoi rotors; lathe rings; radial tube sectors; banded gradient colour; pellets; smear spirals; hubs',
    'rotor M200-240/R30-80; tubes M20-60/R20-50/Cc16; hubs M255/R16',
    [('rotor_disc', 'turned metal disc'), ('sample_tube', 'radial tube'), ('gradient_band', 'density colour band'),
     ('pellet', 'dark rim pellet'), ('polished_hub', 'bright hub')],
    [('astra_ruby_blue_cyclone', 'spiral storms, not rotors')], W + 'Density_gradient_centrifugation'),
'causal_origami': ('future_shoxx', 'Causal Origami', F,
    'Miura-ori folded foil: alternating hot-magenta and teal fold columns in flowing regions, chrome mountain creases, a causal fold wave across the car.',
    'Miura-ori zigzag lattice in warped coordinates; facet normals from fold parity and a fold-depth field; creases',
    'magenta columns matte M20-50/R follows brightness/Cc170-230; teal columns polished M230-250/Cc30-150; mountains M255/R16; valleys R220',
    [('miura_facet', 'parallelogram facet'), ('mountain_crease', 'bright fold'), ('valley_crease', 'dark fold'),
     ('fold_wave', 'hidden fold-depth field'), ('complement_column', 'alternating magenta and teal fold columns')],
    [('astra_prism_rebellion', 'shards, not folds')], W + 'Miura_fold'),
'photonic_switchboard': ('future_shoxx', 'Photonic Switchboard', F,
    'A silicon photonics wafer: 45-degree waveguides carrying coloured laser light, ring resonators, grating combs and die streets.',
    'Random Manhattan/45 routes; glowing cores; rings; grating combs; die street grid; wafer film',
    'wafer M150-210/R30-60/Cc16; guides M20/R120; gratings M255/R20',
    [('waveguide', 'glowing routes'), ('ring_resonator', 'coupled rings'), ('grating_comb', 'coupler combs'),
     ('die_street', 'dicing grid'), ('wafer_sheen', 'interference sheen')],
    [('astra_klein_circuit', 'copper buses, not light guides')], W + 'Silicon_photonics'),
'negative_space_engine': ('future_shoxx', 'Negative Space Engine', F,
    'Blue-violet anodised titanium over a live engine: hole size traces hidden gear trains, copper light glowing and spilling through every perforation.',
    'Hex perforation lattice; hole radius from gear silhouettes; turned copper core; rims',
    'polished plate M228-253/R24-90/Cc16-56; matte copper holes M12/R145-205/Cc228; chrome rims M255/R20',
    [('perforation', 'hex holes'), ('gear_silhouette', 'hidden gears in hole size'), ('copper_core', 'turned glowing core'),
     ('hole_rim', 'bright rims'), ('titanium_plate', 'brushed plate')],
    [('astra_redshift_rivets', 'domed rivets, not perforations')], W + 'Perforated_metal'),
'temporal_braille': ('future_shoxx', 'Temporal Braille', F,
    'A refreshable braille display the size of the car: six-dot pins spell text, each pin the complement of the backlit blue-to-violet-to-red panel beneath it.',
    'Lines of 2x3 braille cells with random bits; domed pins; sockets; age field; cursors',
    'matte panel M12/R198-218/Cc230; polished pins M245/R20-50/Cc16; sockets M60/R235',
    [('braille_pin', 'domed lit pin'), ('pin_socket', 'empty socket'), ('backlit_panel', 'backlit panel drifting blue to red'),
     ('guide_line', 'baseline'), ('cursor_bar', 'bright cursor')],
    [('astra_redshift_rivets', 'armour studs, not text')], W + 'Refreshable_braille_display'),
'klein_circuit': ('future_shoxx', 'Klein Circuit', F,
    'A circuit that loops back through itself: 45-degree gold buses on black mask, a lilac inner layer, vias, pads and Klein bridges.',
    'Random 8-direction bus routes with parallel traces; inner layer; vias; pads; bridges',
    'mask M10/R40-70; traces M255/R50/Cc200; pads R200; vias M255/R16',
    [('gold_bus', 'parallel traces'), ('inner_layer', 'lilac traces beneath'), ('via', 'ring vias'),
     ('component_pad', 'dark packages'), ('klein_bridge', 'self-crossing bridges')],
    [('astra_photonic_switchboard', 'light guides, not copper')], W + 'Klein_bottle'),
'auxetic_exoskin': ('future_shoxx', 'Auxetic Exoskin', F,
    'A rotating-squares auxetic skin: bevelled gunmetal plates hinged corner to corner, a strain field opening glowing ember gaps.',
    'Square lattice with alternating rotation set by a strain field; inscribed squares; bevels; hinge pins; ember gaps',
    'plates M230-250/R follows brightness; gaps M20/R200; pins M255/R16',
    [('rotating_plate', 'bevelled square'), ('ember_gap', 'glowing diamond gap'), ('hinge_pin', 'corner pins'),
     ('strain_field', 'hidden opening field'), ('plate_bevel', 'faceted bevel')],
    [('astra_programmable_matter', 'voxels, not hinged squares')], W + 'Auxetics'),
'memory_metal_zipper': ('future_shoxx', 'Memory Metal Zipper', F,
    'Zippers on an exact conformal flow: heat-tinted nitinol teeth interlocking copper and silver on woven tape, some runs sprung open.',
    'Complex potential flow past dipoles; streamline tracks; alternating teeth along the potential; open field; tape weave',
    'teeth M235-255/R20-70; tape M20/R160-200/Cc240',
    [('nitinol_tooth', 'interlocking teeth'), ('zipper_tape', 'woven tape'), ('open_run', 'sprung-open sections'),
     ('heat_tint', 'copper heat colours'), ('tape_edge', 'dark tape edge')],
    [('astra_chromatic_switchyard', 'transit lanes, not zippers')], W + 'Nickel_titanium'),
'orbitless_navigation': ('future_shoxx', 'Orbitless Navigation', F,
    'A portolan chart with no orbits: hidden wind roses shoot 32 rhumb lines across a dark sea chart in gold, green and red.',
    'Wind roses at hidden sites; 32 full-length rhumb lines each; colour by wind class; graticule; gilt stars',
    'chart M10-30/R200-220/Cc220; principal rhumbs M240/R40; minor rhumbs M30/R60; stars M255/R20',
    [('rhumb_line', 'straight wind lines'), ('wind_rose', 'gilt compass star'), ('graticule', 'chart grid'),
     ('sea_vellum', 'dark chart ground'), ('wind_class', 'gold/green/red code')],
    [('astra_boardwalk_pinlines', 'planks, not chart lines')], W + 'Portolan_chart'),
'tachyon_feather': ('future_shoxx', 'Tachyon Feather', F,
    'Plumage faster than light: overlapping contour feathers with bright rachises and iridescent barbs, Cherenkov-blue tip streaks.',
    'Flow-aligned feather vanes stamped by id; barb pattern; thin-film colour; rachis; tip streaks',
    'barbs M150-240/R20-90; rachis M255/R16; ground R200',
    [('feather_vane', 'overlapping feather'), ('rachis', 'bright shaft'), ('iridescent_barb', 'structural colour barbs'),
     ('cherenkov_streak', 'blue tip streaks'), ('plumage_flow', 'swept arrangement')],
    [('astra_janus_blades', 'split blades, not feathers')], W + 'Structural_coloration'),
'programmable_matter': ('future_shoxx', 'Programmable Matter', F,
    'An isometric field of voxel modules, faces lit three ways, colour-coded in programmed data tiles, empty slots and LED edges.',
    'Axial hex lattice as isometric cubes; three face shades; block-coded states; empty slots; LED edges',
    'voxels M60-220/R40-140; LEDs M255/R16; empty M20/R230',
    [('voxel_top', 'lit top face'), ('voxel_side', 'shaded side faces'), ('state_tile', 'programmed colour blocks'),
     ('empty_slot', 'missing modules'), ('led_edge', 'glowing edges')],
    [('astra_auxetic_exoskin', 'hinged squares, not voxels')], W + 'Programmable_matter'),
}

SWATCH = {
    'astra_abyssal_lanterns': '#3252a3',
    'astra_auxetic_exoskin': '#d05e2c',
    'astra_bismuth_delirium': '#867467',
    'astra_blueblood_chevron': '#826e4d',
    'astra_boardwalk_pinlines': '#af9768',
    'astra_causal_origami': '#28c7c7',
    'astra_chromatic_centrifuge': '#88809f',
    'astra_chromatic_switchyard': '#225191',
    'astra_chromosome_riot': '#4c5289',
    'astra_chronograph_gold': '#b49553',
    'astra_cobalt_guillotine': '#879a49',
    'astra_cryogenic_bloom': '#194574',
    'astra_cytokinesis_candy': '#707fa5',
    'astra_duality_scales': '#a2be4f',
    'astra_event_horizon': '#2c2a5b',
    'astra_fermion_foundry': '#9a6632',
    'astra_gravity_loom': '#2c7970',
    'astra_janus_blades': '#87465f',
    'astra_kelp_couture': '#b19733',
    'astra_klein_circuit': '#ccaa51',
    'astra_magnetic_regalia': '#423e3f',
    'astra_memory_metal_zipper': '#50a93a',
    'astra_meteorite_royal': '#9560eb',
    'astra_negative_space_engine': '#dab788',
    'astra_neuron_carnival': '#4a4e5f',
    'astra_orbitless_navigation': '#1d5752',
    'astra_phoenix_ceramic': '#b17d58',
    'astra_photonic_switchboard': '#a07056',
    'astra_pipeline_royale': '#1090a2',
    'astra_plasma_sutures': '#785a96',
    'astra_polarity_lace': '#195748',
    'astra_prism_rebellion': '#cf782b',
    'astra_programmable_matter': '#986853',
    'astra_quantum_petri': '#b18535',
    'astra_quasicrystal_crown': '#4e6fc2',
    'astra_redshift_rivets': '#5e6d83',
    'astra_reef_cathedral': '#a85a32',
    'astra_ruby_blue_cyclone': '#bc526a',
    'astra_scarlet_undertow': '#a48563',
    'astra_sea_glass_confessional': '#49a36d',
    'astra_sovereign_nacre': '#2c44a6',
    'astra_strange_attractor': '#47c3ab',
    'astra_surf_wax_ritual': '#d2ae91',
    'astra_tachyon_feather': '#4a9e45',
    'astra_temporal_braille': '#411353',
    'astra_tidal_lace': '#23aacf',
    'astra_velvet_supernova': '#711e52',
    'astra_volcanic_break': '#7e7453',
    'astra_wipeout_paisley': '#9c904c',
    'astra_xenobot_orchard': '#678862',
}   # signature colour of each actual 2048 render (_astra_claude_work/tools/shelf.py)

LANES = ('originals', 'color_shoxx', 'surfs_up', 'mad_scientist', 'future_shoxx')


def _builder(key):
    lane = TABLE[key][0]
    return getattr(importlib.import_module(__name__.rsplit('.', 1)[0] + '.' + lane), key)


def adopt(module_name, key):
    """Populate a stable per-finish module from the R2 table."""
    mod = sys.modules[module_name]
    lane, name, lane_title, desc, grammar, spec, marks, neigh, src = TABLE[key]
    fn = _builder(key)
    fid = 'astra_' + key

    def build(shape, seed):
        p, s = fn(seed)
        h, w = int(shape[0]), int(shape[1])
        if p.shape[:2] != (h, w):
            interp = cv2.INTER_AREA if h * w < p.shape[0] * p.shape[1] else cv2.INTER_LINEAR
            p = cv2.resize(p, (w, h), interpolation=interp)
            s = cv2.resize(s, (w, h), interpolation=interp)
        return p, s

    mod.FID, mod.NAME, mod.LANE, mod.DESCRIPTION = fid, name, lane_title, desc
    mod.SWATCH = SWATCH.get(fid, '#808080')
    neigh = list(neigh)
    sib = [k for k in TABLE if TABLE[k][0] == lane and k != key]
    have = {n[0] for n in neigh}
    start = sorted(TABLE).index(key) % len(sib)
    other = next(k for k in sib[start:] + sib[:start] if 'astra_' + k not in have)
    if len(neigh) < 2:
        neigh.append(('astra_' + other, 'same lane, different construction: ' + TABLE[other][4].split(';')[0]))
    mod.IDENTITY_CONTRACT = contract(fid, name, desc, grammar, marks, spec, neigh, src)
    mod.build = build
    mod.paint, mod.spec = bind(mod)
    pkg = __name__.rsplit('.', 1)[0]
    for f in (mod.paint, mod.spec):
        f._spb_picker_dependency_modules += (__name__, pkg + '.kit', pkg + '.' + lane)
    return mod
