"""Spectral Satin — FRACTURED SHOKK — reviewed construction, motion verdict pending."""
from engine.expansions.fractured_shokk_2026 import make_pair
IDENTITY_CONTRACT = {'schema': 'spb-finish-identity/1', 'finish_id': 'fsh_spectral_satin', 'display_name': 'Spectral Satin — FRACTURED SHOKK', 'promise': 'Fine three-over-one interlaced optical tapes reveal saturated metallic reflections as illumination changes.', 'carrier_grammar': 'three-over-one interlaced optical tapes with five separate geometric feature masks and eight local material tiers.', 'spec_grammar': 'Each three-over-one interlaced optical tapes feature owns a metallic/rough/coat response tied to its visible boundaries.', 'reference_physics': {'mechanism': 'Fixed pigments tint metallic reflections; roughness shapes lobes and clearcoat controls the white overlay. This approximates spectral light play, not physical wavelength diffraction.', 'sources': ['SPB_WIKI.html#spec_guide', 'https://support.iracing.com/support/solutions/articles/31000168823-2023-season-1-release-notes-2022-12-06-01-']}, 'native_scale_px': [8, 32], 'mark_types': [{'name': 'warp', 'role': 'warp defines one distinct material-bearing feature'}, {'name': 'weft', 'role': 'weft defines one distinct material-bearing feature'}, {'name': 'crossover', 'role': 'crossover defines one distinct material-bearing feature'}, {'name': 'fiber channel', 'role': 'fiber channel defines one distinct material-bearing feature'}, {'name': 'selvedge', 'role': 'selvedge defines one distinct material-bearing feature'}], 'material_binding': {'M': ['warp', 'weft', 'crossover', 'fiber channel', 'selvedge'], 'R': ['warp', 'weft', 'crossover', 'fiber channel', 'selvedge'], 'Cc': ['warp', 'weft', 'crossover', 'fiber channel', 'selvedge']}, 'material_tiers': [0.18, 0.28, 0.38, 0.48, 0.58, 0.68, 0.78, 0.92], 'nearest_neighbors': [{'finish_id': 'xlab_hologram_metal', 'difference': 'Original three-over-one interlaced optical tapes instead of rotated square plates.'}, {'finish_id': 'hou_veiled_skull', 'difference': 'All-over optical surface rather than a concealed skull silhouette.'}], 'name_truth': {'hidden_title_verdict': 'pass', 'visible_evidence': ['fine interlaced tapes', 'regular over-under crossovers', 'directional fiber channels'], 'evidence_scope': 'Agent structural recognition at native crop and whole sheet,2026-09-18; no owner acceptance or in-sim motion verdict implied.'}, 'construction_key': 'fsh20:spectral_satin:three-over-one interlaced optical tapes', 'spec_key': 'fsh20:spectral_satin:feature-bound-eight-tier-PBR', 'review_asset_sha256': {'paint': '1e3c3751dafa06d2167e390f58fb3ace5962f1a85cce5d231e106726393fd968', 'spec': '83b7303bc44643d52d61a0b4bc9cb17eef3417b92e33c3cbe8f02873e2e88857'}}
spec_fn, paint_fn = make_pair('fsh_spectral_satin')

# SPB-105 / FSH-R2 reset: owner rejects effect; earlier M7 is historical.
OWNER_REJECTION_R1 = {'verdict': 'reject', 'date': '2026-09-18', 'reason': 'Owner rejected 2026-09-18: does not reproduce the moving spectral highlight in the reference. Full design reset; not an accepted finish.', 'quote': 'These are not at ALL doing what the car in his example was doing.'}
IDENTITY_CONTRACT['owner_review'] = OWNER_REJECTION_R1
IDENTITY_CONTRACT['name_truth']['previous_internal_verdict'] = IDENTITY_CONTRACT['name_truth']['hidden_title_verdict']
IDENTITY_CONTRACT['name_truth']['hidden_title_verdict'] = 'fail'
IDENTITY_CONTRACT['name_truth']['rejection_scope'] = 'Promised light behavior failed owner review; texture recognition alone was insufficient.'
