"""SPB-105 / FSH-R3-COLOR; broader hues, same fine construction.
Owner requests yellow/orange/pink/purple/seafoam. M7 pending -> pending.
"""
from engine.expansions.fractured_shokk_2026 import make_pair
IDENTITY_CONTRACT = {'schema': 'spb-finish-identity/1',
 'finish_id': 'fsh_opal_fault',
 'display_name': 'Opal Bloom — FRACTURED SHOKK prototype',
 'promise': 'Irregular overlapping irregular mineral blooms reveal localized spectral highlights without '
            'repeated rainbow bands.',
 'carrier_grammar': 'overlapping irregular mineral blooms with five overlapping purpose-built material '
                    'features and nonperiodic chromatic gradients.',
 'spec_grammar': 'Each named overlapping irregular mineral blooms feature has a separate eight-tier response '
                 'near the actual-game spectral-metal window.',
 'reference_physics': {'mechanism': 'Fixed saturated pigment tints metallic reflections. Roughness and '
                                    'clearcoat determine highlight response. Actual-game calibration '
                                    'anchor255/40/218; no physical wavelength diffraction or animated paint '
                                    'claimed.',
                       'sources': ['R2_MECHANISM/DAYLIGHT_BREAKTHROUGH.md']},
 'native_scale_px': [8, 32],
 'mark_types': [{'name': 'mineral pool',
                 'role': 'mineral pool owns a visible material-bearing part of this construction'},
                {'name': 'growth lip',
                 'role': 'growth lip owns a visible material-bearing part of this construction'},
                {'name': 'inclusion',
                 'role': 'inclusion owns a visible material-bearing part of this construction'},
                {'name': 'fracture',
                 'role': 'fracture owns a visible material-bearing part of this construction'},
                {'name': 'pearl nodule',
                 'role': 'pearl nodule owns a visible material-bearing part of this construction'}],
 'material_binding': {'M': ['mineral pool', 'growth lip', 'inclusion', 'fracture', 'pearl nodule'],
                      'R': ['mineral pool', 'growth lip', 'inclusion', 'fracture', 'pearl nodule'],
                      'Cc': ['mineral pool', 'growth lip', 'inclusion', 'fracture', 'pearl nodule']},
 'material_tiers': [0.18, 0.28, 0.38, 0.48, 0.58, 0.68, 0.78, 0.92],
 'nearest_neighbors': [{'finish_id': 'fsh_r3_prism_shards',
                        'difference': 'overlapping irregular mineral blooms versus irregular angular prism '
                                      'chips'},
                       {'finish_id': 'fsh_r3_brushed_spectrum',
                        'difference': 'overlapping irregular mineral blooms versus layered short paintbrush '
                                      'strokes'},
                       {'finish_id': 'fsh_r3_chromatic_grunge',
                        'difference': 'overlapping irregular mineral blooms versus pitted and abraded '
                                      'multicolor metal'}],
 'name_truth': {'hidden_title_verdict': 'pending',
                'visible_evidence': ['overlapping irregular mineral blooms',
                                     'mineral pool',
                                     'growth lip',
                                     'inclusion',
                                     'fracture',
                                     'pearl nodule']},
 'owner_review': {'verdict': 'pending', 'instruction': 'NO BANDS; prisms, gradients, grunge, brushwork'},
 'construction_key': 'fsh:r3:opal_bloom',
 'spec_key': 'fsh:r3:opal_bloom:five-bound-feature-populations',
 'development_status': 'R3 nonband proof; actual-game validation and owner review pending',
 'previous_revision': {'id': 'R1',
                       'verdict': 'reject',
                       'reason': 'Owner rejected the promised light response'},
 'qualification_errors': ["name_truth.hidden_title_verdict must be 'pass'"],
 'review_asset_sha256': {'paint': '8c3f370c130b392b07f5de017774dee00be500f5081eff03be466db0c17f126e',
                         'spec': 'e9d57de46dd0884056989cee713eb56b58355d8ff0742eb874b40b4efdbd15a5'},
 'palette_revision': {'date': '2026-09-18',
                      'owner_request': 'whole rainbow; yellow orange pink purple seafoam and shades within '
                                       'families',
                      'anchors': [['scarlet', 0, 0.96],
                                  ['ruby', 350, 0.92],
                                  ['coral', 12, 0.68],
                                  ['vermillion', 20, 0.95],
                                  ['orange', 30, 0.96],
                                  ['amber', 42, 0.91],
                                  ['gold', 51, 0.95],
                                  ['lemon', 61, 0.86],
                                  ['chartreuse', 79, 0.86],
                                  ['lime', 95, 0.92],
                                  ['leaf green', 115, 0.85],
                                  ['emerald', 140, 0.91],
                                  ['jade', 155, 0.72],
                                  ['seafoam', 162, 0.48],
                                  ['mint', 147, 0.38],
                                  ['turquoise', 176, 0.81],
                                  ['cyan', 188, 0.93],
                                  ['azure', 206, 0.91],
                                  ['cobalt', 228, 0.93],
                                  ['periwinkle', 245, 0.58],
                                  ['violet', 266, 0.89],
                                  ['lavender', 280, 0.48],
                                  ['purple', 291, 0.87],
                                  ['orchid', 309, 0.63],
                                  ['fuchsia', 324, 0.93],
                                  ['rose', 339, 0.55],
                                  ['pink', 350, 0.42],
                                  ['salmon', 9, 0.5]],
                      'measured_coverage': {'hue_30_degree_percent': [14.515,
                                                                      13.682,
                                                                      7.789,
                                                                      6.801,
                                                                      8.199,
                                                                      9.276,
                                                                      8.121,
                                                                      4.448,
                                                                      4.333,
                                                                      5.608,
                                                                      6.387,
                                                                      10.842],
                                            'seafoam_mint_percent': 6.467,
                                            'soft_pink_percent': 10.43,
                                            'lavender_percent': 3.78,
                                            'saturation_range': [0.275, 0.649, 0.929]},
                      'spec_pixels_unchanged': True}}
spec_fn, paint_fn = make_pair('fsh_opal_fault')
