"""Isobar Chrome — FRACTURED SHOKK — reviewed construction, motion verdict pending."""
from engine.expansions.fractured_shokk_2026 import make_pair
IDENTITY_CONTRACT = {'schema': 'spb-finish-identity/1', 'finish_id': 'fsh_isobar_chrome', 'display_name': 'Isobar Chrome — FRACTURED SHOKK', 'promise': 'Fine labyrinthine broken contour terraces reveal saturated metallic reflections as illumination changes.', 'carrier_grammar': 'labyrinthine broken contour terraces with five separate geometric feature masks and eight local material tiers.', 'spec_grammar': 'Each labyrinthine broken contour terraces feature owns a metallic/rough/coat response tied to its visible boundaries.', 'reference_physics': {'mechanism': 'Fixed pigments tint metallic reflections; roughness shapes lobes and clearcoat controls the white overlay. This approximates spectral light play, not physical wavelength diffraction.', 'sources': ['SPB_WIKI.html#spec_guide', 'https://support.iracing.com/support/solutions/articles/31000168823-2023-season-1-release-notes-2022-12-06-01-']}, 'native_scale_px': [8, 32], 'mark_types': [{'name': 'terrace', 'role': 'terrace defines one distinct material-bearing feature'}, {'name': 'contour', 'role': 'contour defines one distinct material-bearing feature'}, {'name': 'saddle', 'role': 'saddle defines one distinct material-bearing feature'}, {'name': 'crest', 'role': 'crest defines one distinct material-bearing feature'}, {'name': 'cut bank', 'role': 'cut bank defines one distinct material-bearing feature'}], 'material_binding': {'M': ['terrace', 'contour', 'saddle', 'crest', 'cut bank'], 'R': ['terrace', 'contour', 'saddle', 'crest', 'cut bank'], 'Cc': ['terrace', 'contour', 'saddle', 'crest', 'cut bank']}, 'material_tiers': [0.18, 0.28, 0.38, 0.48, 0.58, 0.68, 0.78, 0.92], 'nearest_neighbors': [{'finish_id': 'xlab_hologram_metal', 'difference': 'Original labyrinthine broken contour terraces instead of rotated square plates.'}, {'finish_id': 'hou_veiled_skull', 'difference': 'All-over optical surface rather than a concealed skull silhouette.'}], 'name_truth': {'hidden_title_verdict': 'pass', 'visible_evidence': ['concentric contour terraces', 'saddles joining contours', 'sharply separated contour banks'], 'evidence_scope': 'Agent structural recognition at native crop and whole sheet,2026-09-18; no owner acceptance or in-sim motion verdict implied.'}, 'construction_key': 'fsh20:isobar_chrome:labyrinthine broken contour terraces', 'spec_key': 'fsh20:isobar_chrome:feature-bound-eight-tier-PBR', 'review_asset_sha256': {'paint': 'a2a875dca5f56d8914a578180bb91ff4195b5133bf43f07ec036443e4d5b38fc', 'spec': '63261fc9af84f62e36d65a72bba71c13b95901df1d189900c7094063d1f682bc'}}
spec_fn, paint_fn = make_pair('fsh_isobar_chrome')

# SPB-105 / FSH-R2 reset: owner rejects effect; earlier M7 is historical.
OWNER_REJECTION_R1 = {'verdict': 'reject', 'date': '2026-09-18', 'reason': 'Owner rejected 2026-09-18: does not reproduce the moving spectral highlight in the reference. Full design reset; not an accepted finish.', 'quote': 'These are not at ALL doing what the car in his example was doing.'}
IDENTITY_CONTRACT['owner_review'] = OWNER_REJECTION_R1
IDENTITY_CONTRACT['name_truth']['previous_internal_verdict'] = IDENTITY_CONTRACT['name_truth']['hidden_title_verdict']
IDENTITY_CONTRACT['name_truth']['hidden_title_verdict'] = 'fail'
IDENTITY_CONTRACT['name_truth']['rejection_scope'] = 'Promised light behavior failed owner review; texture recognition alone was insufficient.'
