"""Diamond Fold — FRACTURED SHOKK — reviewed construction, motion verdict pending."""
from engine.expansions.fractured_shokk_2026 import make_pair
IDENTITY_CONTRACT = {'schema': 'spb-finish-identity/1', 'finish_id': 'fsh_diamond_fold', 'display_name': 'Diamond Fold — FRACTURED SHOKK', 'promise': 'Fine opposed concave diamond foil folds reveal saturated metallic reflections as illumination changes.', 'carrier_grammar': 'opposed concave diamond foil folds with five separate geometric feature masks and eight local material tiers.', 'spec_grammar': 'Each opposed concave diamond foil folds feature owns a metallic/rough/coat response tied to its visible boundaries.', 'reference_physics': {'mechanism': 'Fixed pigments tint metallic reflections; roughness shapes lobes and clearcoat controls the white overlay. This approximates spectral light play, not physical wavelength diffraction.', 'sources': ['SPB_WIKI.html#spec_guide', 'https://support.iracing.com/support/solutions/articles/31000168823-2023-season-1-release-notes-2022-12-06-01-']}, 'native_scale_px': [8, 32], 'mark_types': [{'name': 'fold face', 'role': 'fold face defines one distinct material-bearing feature'}, {'name': 'ridge', 'role': 'ridge defines one distinct material-bearing feature'}, {'name': 'valley', 'role': 'valley defines one distinct material-bearing feature'}, {'name': 'crease point', 'role': 'crease point defines one distinct material-bearing feature'}, {'name': 'foil shoulder', 'role': 'foil shoulder defines one distinct material-bearing feature'}], 'material_binding': {'M': ['fold face', 'ridge', 'valley', 'crease point', 'foil shoulder'], 'R': ['fold face', 'ridge', 'valley', 'crease point', 'foil shoulder'], 'Cc': ['fold face', 'ridge', 'valley', 'crease point', 'foil shoulder']}, 'material_tiers': [0.18, 0.28, 0.38, 0.48, 0.58, 0.68, 0.78, 0.92], 'nearest_neighbors': [{'finish_id': 'xlab_hologram_metal', 'difference': 'Original opposed concave diamond foil folds instead of rotated square plates.'}, {'finish_id': 'hou_veiled_skull', 'difference': 'All-over optical surface rather than a concealed skull silhouette.'}], 'name_truth': {'hidden_title_verdict': 'pass', 'visible_evidence': ['opposed diamond planes', 'central creases', 'alternating valley and ridge faces'], 'evidence_scope': 'Agent structural recognition at native crop and whole sheet,2026-09-18; no owner acceptance or in-sim motion verdict implied.'}, 'construction_key': 'fsh20:diamond_fold:opposed concave diamond foil folds', 'spec_key': 'fsh20:diamond_fold:feature-bound-eight-tier-PBR', 'review_asset_sha256': {'paint': '36388b1cf0e9b664c739b85e94c5a6850f0dd9c1cf8223d436e7e6d45c626324', 'spec': 'a357188bfdb4547d2b5f82c93652f3f44cc3d1101897d172ceec441ae8f1651c'}}
spec_fn, paint_fn = make_pair('fsh_diamond_fold')

# SPB-105 / FSH-R2 reset: owner rejects effect; earlier M7 is historical.
OWNER_REJECTION_R1 = {'verdict': 'reject', 'date': '2026-09-18', 'reason': 'Owner rejected 2026-09-18: does not reproduce the moving spectral highlight in the reference. Full design reset; not an accepted finish.', 'quote': 'These are not at ALL doing what the car in his example was doing.'}
IDENTITY_CONTRACT['owner_review'] = OWNER_REJECTION_R1
IDENTITY_CONTRACT['name_truth']['previous_internal_verdict'] = IDENTITY_CONTRACT['name_truth']['hidden_title_verdict']
IDENTITY_CONTRACT['name_truth']['hidden_title_verdict'] = 'fail'
IDENTITY_CONTRACT['name_truth']['rejection_scope'] = 'Promised light behavior failed owner review; texture recognition alone was insufficient.'
