"""Caustic Lens — FRACTURED SHOKK — reviewed construction, motion verdict pending."""
from engine.expansions.fractured_shokk_2026 import make_pair
IDENTITY_CONTRACT = {'schema': 'spb-finish-identity/1', 'finish_id': 'fsh_caustic_lens', 'display_name': 'Caustic Lens — FRACTURED SHOKK', 'promise': 'Fine offset asymmetric elliptical lenslets reveal saturated metallic reflections as illumination changes.', 'carrier_grammar': 'offset asymmetric elliptical lenslets with five separate geometric feature masks and eight local material tiers.', 'spec_grammar': 'Each offset asymmetric elliptical lenslets feature owns a metallic/rough/coat response tied to its visible boundaries.', 'reference_physics': {'mechanism': 'Fixed pigments tint metallic reflections; roughness shapes lobes and clearcoat controls the white overlay. This approximates spectral light play, not physical wavelength diffraction.', 'sources': ['SPB_WIKI.html#spec_guide', 'https://support.iracing.com/support/solutions/articles/31000168823-2023-season-1-release-notes-2022-12-06-01-']}, 'native_scale_px': [8, 32], 'mark_types': [{'name': 'lens well', 'role': 'lens well defines one distinct material-bearing feature'}, {'name': 'inner caustic', 'role': 'inner caustic defines one distinct material-bearing feature'}, {'name': 'outer rim', 'role': 'outer rim defines one distinct material-bearing feature'}, {'name': 'focus', 'role': 'focus defines one distinct material-bearing feature'}, {'name': 'lens gap', 'role': 'lens gap defines one distinct material-bearing feature'}], 'material_binding': {'M': ['lens well', 'inner caustic', 'outer rim', 'focus', 'lens gap'], 'R': ['lens well', 'inner caustic', 'outer rim', 'focus', 'lens gap'], 'Cc': ['lens well', 'inner caustic', 'outer rim', 'focus', 'lens gap']}, 'material_tiers': [0.18, 0.28, 0.38, 0.48, 0.58, 0.68, 0.78, 0.92], 'nearest_neighbors': [{'finish_id': 'xlab_hologram_metal', 'difference': 'Original offset asymmetric elliptical lenslets instead of rotated square plates.'}, {'finish_id': 'hou_veiled_skull', 'difference': 'All-over optical surface rather than a concealed skull silhouette.'}], 'name_truth': {'hidden_title_verdict': 'pass', 'visible_evidence': ['elliptical lens bowls', 'nested colored caustic rims', 'offset focus glints'], 'evidence_scope': 'Agent structural recognition at native crop and whole sheet,2026-09-18; no owner acceptance or in-sim motion verdict implied.'}, 'construction_key': 'fsh20:caustic_lens:offset asymmetric elliptical lenslets', 'spec_key': 'fsh20:caustic_lens:feature-bound-eight-tier-PBR', 'review_asset_sha256': {'paint': 'e56c19084dc8cf9b8d75da6430b8aa5d8a3483acf46a3403c0dc2acae408d332', 'spec': '2cead5f93d4b52c951831637d89968367d34a770b79e5928ee89234aa0a27207'}}
spec_fn, paint_fn = make_pair('fsh_caustic_lens')

# SPB-105 / FSH-R2 reset: owner rejects effect; earlier M7 is historical.
OWNER_REJECTION_R1 = {'verdict': 'reject', 'date': '2026-09-18', 'reason': 'Owner rejected 2026-09-18: does not reproduce the moving spectral highlight in the reference. Full design reset; not an accepted finish.', 'quote': 'These are not at ALL doing what the car in his example was doing.'}
IDENTITY_CONTRACT['owner_review'] = OWNER_REJECTION_R1
IDENTITY_CONTRACT['name_truth']['previous_internal_verdict'] = IDENTITY_CONTRACT['name_truth']['hidden_title_verdict']
IDENTITY_CONTRACT['name_truth']['hidden_title_verdict'] = 'fail'
IDENTITY_CONTRACT['name_truth']['rejection_scope'] = 'Promised light behavior failed owner review; texture recognition alone was insufficient.'
