"""Crystal Needle — FRACTURED SHOKK — reviewed construction, motion verdict pending."""
from engine.expansions.fractured_shokk_2026 import make_pair
IDENTITY_CONTRACT = {'schema': 'spb-finish-identity/1', 'finish_id': 'fsh_crystal_needle', 'display_name': 'Crystal Needle — FRACTURED SHOKK', 'promise': 'Fine crossed acicular crystal bundles reveal saturated metallic reflections as illumination changes.', 'carrier_grammar': 'crossed acicular crystal bundles with five separate geometric feature masks and eight local material tiers.', 'spec_grammar': 'Each crossed acicular crystal bundles feature owns a metallic/rough/coat response tied to its visible boundaries.', 'reference_physics': {'mechanism': 'Fixed pigments tint metallic reflections; roughness shapes lobes and clearcoat controls the white overlay. This approximates spectral light play, not physical wavelength diffraction.', 'sources': ['SPB_WIKI.html#spec_guide', 'https://support.iracing.com/support/solutions/articles/31000168823-2023-season-1-release-notes-2022-12-06-01-']}, 'native_scale_px': [8, 32], 'mark_types': [{'name': 'needle body', 'role': 'needle body defines one distinct material-bearing feature'}, {'name': 'cleavage', 'role': 'cleavage defines one distinct material-bearing feature'}, {'name': 'needle tip', 'role': 'needle tip defines one distinct material-bearing feature'}, {'name': 'crossing', 'role': 'crossing defines one distinct material-bearing feature'}, {'name': 'matrix', 'role': 'matrix defines one distinct material-bearing feature'}], 'material_binding': {'M': ['needle body', 'cleavage', 'needle tip', 'crossing', 'matrix'], 'R': ['needle body', 'cleavage', 'needle tip', 'crossing', 'matrix'], 'Cc': ['needle body', 'cleavage', 'needle tip', 'crossing', 'matrix']}, 'material_tiers': [0.18, 0.28, 0.38, 0.48, 0.58, 0.68, 0.78, 0.92], 'nearest_neighbors': [{'finish_id': 'xlab_hologram_metal', 'difference': 'Original crossed acicular crystal bundles instead of rotated square plates.'}, {'finish_id': 'hou_veiled_skull', 'difference': 'All-over optical surface rather than a concealed skull silhouette.'}], 'name_truth': {'hidden_title_verdict': 'pass', 'visible_evidence': ['crossing long narrow needles', 'diagonal cleavage lines', 'crystal tips within a matrix'], 'evidence_scope': 'Agent structural recognition at native crop and whole sheet,2026-09-18; no owner acceptance or in-sim motion verdict implied.'}, 'construction_key': 'fsh20:crystal_needle:crossed acicular crystal bundles', 'spec_key': 'fsh20:crystal_needle:feature-bound-eight-tier-PBR', 'review_asset_sha256': {'paint': '0e179947332c9c343786ccc18e7ea3dded0509034adc6323735bf306c6a08f55', 'spec': '74e9ca3b8cca7257c6eb77341b732fa0124a07b3a2789d7fc133f0d813dda007'}}
spec_fn, paint_fn = make_pair('fsh_crystal_needle')

# SPB-105 / FSH-R2 reset: owner rejects effect; earlier M7 is historical.
OWNER_REJECTION_R1 = {'verdict': 'reject', 'date': '2026-09-18', 'reason': 'Owner rejected 2026-09-18: does not reproduce the moving spectral highlight in the reference. Full design reset; not an accepted finish.', 'quote': 'These are not at ALL doing what the car in his example was doing.'}
IDENTITY_CONTRACT['owner_review'] = OWNER_REJECTION_R1
IDENTITY_CONTRACT['name_truth']['previous_internal_verdict'] = IDENTITY_CONTRACT['name_truth']['hidden_title_verdict']
IDENTITY_CONTRACT['name_truth']['hidden_title_verdict'] = 'fail'
IDENTITY_CONTRACT['name_truth']['rejection_scope'] = 'Promised light behavior failed owner review; texture recognition alone was insufficient.'
