"""Bubble Spectrum — FRACTURED SHOKK — reviewed construction, motion verdict pending."""
from engine.expansions.fractured_shokk_2026 import make_pair
IDENTITY_CONTRACT = {'schema': 'spb-finish-identity/1', 'finish_id': 'fsh_bubble_spectrum', 'display_name': 'Bubble Spectrum — FRACTURED SHOKK', 'promise': 'Fine polydisperse concentric film bubbles reveal saturated metallic reflections as illumination changes.', 'carrier_grammar': 'polydisperse concentric film bubbles with five separate geometric feature masks and eight local material tiers.', 'spec_grammar': 'Each polydisperse concentric film bubbles feature owns a metallic/rough/coat response tied to its visible boundaries.', 'reference_physics': {'mechanism': 'Fixed pigments tint metallic reflections; roughness shapes lobes and clearcoat controls the white overlay. This approximates spectral light play, not physical wavelength diffraction.', 'sources': ['SPB_WIKI.html#spec_guide', 'https://support.iracing.com/support/solutions/articles/31000168823-2023-season-1-release-notes-2022-12-06-01-']}, 'native_scale_px': [8, 32], 'mark_types': [{'name': 'film bowl', 'role': 'film bowl defines one distinct material-bearing feature'}, {'name': 'film rim', 'role': 'film rim defines one distinct material-bearing feature'}, {'name': 'inner ring', 'role': 'inner ring defines one distinct material-bearing feature'}, {'name': 'contact glint', 'role': 'contact glint defines one distinct material-bearing feature'}, {'name': 'interstitial film', 'role': 'interstitial film defines one distinct material-bearing feature'}], 'material_binding': {'M': ['film bowl', 'film rim', 'inner ring', 'contact glint', 'interstitial film'], 'R': ['film bowl', 'film rim', 'inner ring', 'contact glint', 'interstitial film'], 'Cc': ['film bowl', 'film rim', 'inner ring', 'contact glint', 'interstitial film']}, 'material_tiers': [0.18, 0.28, 0.38, 0.48, 0.58, 0.68, 0.78, 0.92], 'nearest_neighbors': [{'finish_id': 'xlab_hologram_metal', 'difference': 'Original polydisperse concentric film bubbles instead of rotated square plates.'}, {'finish_id': 'hou_veiled_skull', 'difference': 'All-over optical surface rather than a concealed skull silhouette.'}], 'name_truth': {'hidden_title_verdict': 'pass', 'visible_evidence': ['bubbles of varying diameter', 'inner film rings', 'isolated contact glints'], 'evidence_scope': 'Agent structural recognition at native crop and whole sheet,2026-09-18; no owner acceptance or in-sim motion verdict implied.'}, 'construction_key': 'fsh20:bubble_spectrum:polydisperse concentric film bubbles', 'spec_key': 'fsh20:bubble_spectrum:feature-bound-eight-tier-PBR', 'review_asset_sha256': {'paint': '3f42953e2717fc0664f80c4f8f6386ce0d0fa5b42e67e554742da3373d089400', 'spec': '75de7a441ce242621c564026f0f8fc9735c397589eff3d44da1b1268e30cb121'}}
spec_fn, paint_fn = make_pair('fsh_bubble_spectrum')

# SPB-105 / FSH-R2 reset: owner rejects effect; earlier M7 is historical.
OWNER_REJECTION_R1 = {'verdict': 'reject', 'date': '2026-09-18', 'reason': 'Owner rejected 2026-09-18: does not reproduce the moving spectral highlight in the reference. Full design reset; not an accepted finish.', 'quote': 'These are not at ALL doing what the car in his example was doing.'}
IDENTITY_CONTRACT['owner_review'] = OWNER_REJECTION_R1
IDENTITY_CONTRACT['name_truth']['previous_internal_verdict'] = IDENTITY_CONTRACT['name_truth']['hidden_title_verdict']
IDENTITY_CONTRACT['name_truth']['hidden_title_verdict'] = 'fail'
IDENTITY_CONTRACT['name_truth']['rejection_scope'] = 'Promised light behavior failed owner review; texture recognition alone was insufficient.'
