"""Chromatic Comb — FRACTURED SHOKK — reviewed construction, motion verdict pending."""
from engine.expansions.fractured_shokk_2026 import make_pair
IDENTITY_CONTRACT = {'schema': 'spb-finish-identity/1', 'finish_id': 'fsh_chromatic_comb', 'display_name': 'Chromatic Comb — FRACTURED SHOKK', 'promise': 'Fine interdigitated offset comb teeth reveal saturated metallic reflections as illumination changes.', 'carrier_grammar': 'interdigitated offset comb teeth with five separate geometric feature masks and eight local material tiers.', 'spec_grammar': 'Each interdigitated offset comb teeth feature owns a metallic/rough/coat response tied to its visible boundaries.', 'reference_physics': {'mechanism': 'Fixed pigments tint metallic reflections; roughness shapes lobes and clearcoat controls the white overlay. This approximates spectral light play, not physical wavelength diffraction.', 'sources': ['SPB_WIKI.html#spec_guide', 'https://support.iracing.com/support/solutions/articles/31000168823-2023-season-1-release-notes-2022-12-06-01-']}, 'native_scale_px': [8, 32], 'mark_types': [{'name': 'comb spine', 'role': 'comb spine defines one distinct material-bearing feature'}, {'name': 'long tooth', 'role': 'long tooth defines one distinct material-bearing feature'}, {'name': 'short tooth', 'role': 'short tooth defines one distinct material-bearing feature'}, {'name': 'tooth root', 'role': 'tooth root defines one distinct material-bearing feature'}, {'name': 'groove bed', 'role': 'groove bed defines one distinct material-bearing feature'}], 'material_binding': {'M': ['comb spine', 'long tooth', 'short tooth', 'tooth root', 'groove bed'], 'R': ['comb spine', 'long tooth', 'short tooth', 'tooth root', 'groove bed'], 'Cc': ['comb spine', 'long tooth', 'short tooth', 'tooth root', 'groove bed']}, 'material_tiers': [0.18, 0.28, 0.38, 0.48, 0.58, 0.68, 0.78, 0.92], 'nearest_neighbors': [{'finish_id': 'xlab_hologram_metal', 'difference': 'Original interdigitated offset comb teeth instead of rotated square plates.'}, {'finish_id': 'hou_veiled_skull', 'difference': 'All-over optical surface rather than a concealed skull silhouette.'}], 'name_truth': {'hidden_title_verdict': 'pass', 'visible_evidence': ['interdigitated vertical teeth', 'crossing horizontal spines', 'recessed comb gaps'], 'evidence_scope': 'Agent structural recognition at native crop and whole sheet,2026-09-18; no owner acceptance or in-sim motion verdict implied.'}, 'construction_key': 'fsh20:chromatic_comb:interdigitated offset comb teeth', 'spec_key': 'fsh20:chromatic_comb:feature-bound-eight-tier-PBR', 'review_asset_sha256': {'paint': 'c8fc87b4ab1c55e3558fa4a11d2c5317626389311aa13bd1ab8e44cc6ea0bf02', 'spec': 'e11bf270f207008508f25d068dd8014882530565b74143d9a2434c19dafb6b04'}}
spec_fn, paint_fn = make_pair('fsh_chromatic_comb')

# SPB-105 / FSH-R2 reset: owner rejects effect; earlier M7 is historical.
OWNER_REJECTION_R1 = {'verdict': 'reject', 'date': '2026-09-18', 'reason': 'Owner rejected 2026-09-18: does not reproduce the moving spectral highlight in the reference. Full design reset; not an accepted finish.', 'quote': 'These are not at ALL doing what the car in his example was doing.'}
IDENTITY_CONTRACT['owner_review'] = OWNER_REJECTION_R1
IDENTITY_CONTRACT['name_truth']['previous_internal_verdict'] = IDENTITY_CONTRACT['name_truth']['hidden_title_verdict']
IDENTITY_CONTRACT['name_truth']['hidden_title_verdict'] = 'fail'
IDENTITY_CONTRACT['name_truth']['rejection_scope'] = 'Promised light behavior failed owner review; texture recognition alone was insufficient.'
