"""Rosette Engine — FRACTURED SHOKK — reviewed construction, motion verdict pending."""
from engine.expansions.fractured_shokk_2026 import make_pair
IDENTITY_CONTRACT = {'schema': 'spb-finish-identity/1', 'finish_id': 'fsh_rosette_engine', 'display_name': 'Rosette Engine — FRACTURED SHOKK', 'promise': 'Fine eight-lobed engraved rosettes reveal saturated metallic reflections as illumination changes.', 'carrier_grammar': 'eight-lobed engraved rosettes with five separate geometric feature masks and eight local material tiers.', 'spec_grammar': 'Each eight-lobed engraved rosettes feature owns a metallic/rough/coat response tied to its visible boundaries.', 'reference_physics': {'mechanism': 'Fixed pigments tint metallic reflections; roughness shapes lobes and clearcoat controls the white overlay. This approximates spectral light play, not physical wavelength diffraction.', 'sources': ['SPB_WIKI.html#spec_guide', 'https://support.iracing.com/support/solutions/articles/31000168823-2023-season-1-release-notes-2022-12-06-01-']}, 'native_scale_px': [8, 32], 'mark_types': [{'name': 'petal crest', 'role': 'petal crest defines one distinct material-bearing feature'}, {'name': 'petal trough', 'role': 'petal trough defines one distinct material-bearing feature'}, {'name': 'medallion', 'role': 'medallion defines one distinct material-bearing feature'}, {'name': 'radial notch', 'role': 'radial notch defines one distinct material-bearing feature'}, {'name': 'interstice', 'role': 'interstice defines one distinct material-bearing feature'}], 'material_binding': {'M': ['petal crest', 'petal trough', 'medallion', 'radial notch', 'interstice'], 'R': ['petal crest', 'petal trough', 'medallion', 'radial notch', 'interstice'], 'Cc': ['petal crest', 'petal trough', 'medallion', 'radial notch', 'interstice']}, 'material_tiers': [0.18, 0.28, 0.38, 0.48, 0.58, 0.68, 0.78, 0.92], 'nearest_neighbors': [{'finish_id': 'xlab_hologram_metal', 'difference': 'Original eight-lobed engraved rosettes instead of rotated square plates.'}, {'finish_id': 'hou_veiled_skull', 'difference': 'All-over optical surface rather than a concealed skull silhouette.'}], 'name_truth': {'hidden_title_verdict': 'pass', 'visible_evidence': ['eight-lobed rosettes', 'central medallions', 'staggered engraved floral rings'], 'evidence_scope': 'Agent structural recognition at native crop and whole sheet,2026-09-18; no owner acceptance or in-sim motion verdict implied.'}, 'construction_key': 'fsh20:rosette_engine:eight-lobed engraved rosettes', 'spec_key': 'fsh20:rosette_engine:feature-bound-eight-tier-PBR', 'review_asset_sha256': {'paint': '69ce8609846f9e1d772992647c167bbcd41e15cf2f832f339b59351778749bfd', 'spec': '12509a7f2f961d119c6b79c40dc53fa6637815c7e8f968ed782a7940982cc599'}}
spec_fn, paint_fn = make_pair('fsh_rosette_engine')

# SPB-105 / FSH-R2 reset: owner rejects effect; earlier M7 is historical.
OWNER_REJECTION_R1 = {'verdict': 'reject', 'date': '2026-09-18', 'reason': 'Owner rejected 2026-09-18: does not reproduce the moving spectral highlight in the reference. Full design reset; not an accepted finish.', 'quote': 'These are not at ALL doing what the car in his example was doing.'}
IDENTITY_CONTRACT['owner_review'] = OWNER_REJECTION_R1
IDENTITY_CONTRACT['name_truth']['previous_internal_verdict'] = IDENTITY_CONTRACT['name_truth']['hidden_title_verdict']
IDENTITY_CONTRACT['name_truth']['hidden_title_verdict'] = 'fail'
IDENTITY_CONTRACT['name_truth']['rejection_scope'] = 'Promised light behavior failed owner review; texture recognition alone was insufficient.'
