"""SPB-105 / FSH-R3-COLOR; broader hues, same fine construction.
Owner requests yellow/orange/pink/purple/seafoam. M7 pending -> pending.
"""
from engine.expansions.fractured_shokk_2026 import make_pair
IDENTITY_CONTRACT = {'schema': 'spb-finish-identity/1',
 'finish_id': 'fsh_frost_voltage',
 'display_name': 'Chromatic Grunge — FRACTURED SHOKK prototype',
 'promise': 'Irregular pitted and abraded multicolor metal reveal localized spectral highlights without '
            'repeated rainbow bands.',
 'carrier_grammar': 'pitted and abraded multicolor metal with five overlapping purpose-built material '
                    'features and nonperiodic chromatic gradients.',
 'spec_grammar': 'Each named pitted and abraded multicolor metal feature has a separate eight-tier response '
                 'near the actual-game spectral-metal window.',
 'reference_physics': {'mechanism': 'Fixed saturated pigment tints metallic reflections. Roughness and '
                                    'clearcoat determine highlight response. Actual-game calibration '
                                    'anchor255/40/218; no physical wavelength diffraction or animated paint '
                                    'claimed.',
                       'sources': ['R2_MECHANISM/DAYLIGHT_BREAKTHROUGH.md']},
 'native_scale_px': [8, 32],
 'mark_types': [{'name': 'pit bowl',
                 'role': 'pit bowl owns a visible material-bearing part of this construction'},
                {'name': 'scuffed rim',
                 'role': 'scuffed rim owns a visible material-bearing part of this construction'},
                {'name': 'abrasion',
                 'role': 'abrasion owns a visible material-bearing part of this construction'},
                {'name': 'oxide fleck',
                 'role': 'oxide fleck owns a visible material-bearing part of this construction'},
                {'name': 'polished island',
                 'role': 'polished island owns a visible material-bearing part of this construction'}],
 'material_binding': {'M': ['pit bowl', 'scuffed rim', 'abrasion', 'oxide fleck', 'polished island'],
                      'R': ['pit bowl', 'scuffed rim', 'abrasion', 'oxide fleck', 'polished island'],
                      'Cc': ['pit bowl', 'scuffed rim', 'abrasion', 'oxide fleck', 'polished island']},
 'material_tiers': [0.18, 0.28, 0.38, 0.48, 0.58, 0.68, 0.78, 0.92],
 'nearest_neighbors': [{'finish_id': 'fsh_r3_prism_shards',
                        'difference': 'pitted and abraded multicolor metal versus irregular angular prism '
                                      'chips'},
                       {'finish_id': 'fsh_r3_brushed_spectrum',
                        'difference': 'pitted and abraded multicolor metal versus layered short paintbrush '
                                      'strokes'},
                       {'finish_id': 'fsh_r3_opal_bloom',
                        'difference': 'pitted and abraded multicolor metal versus overlapping irregular '
                                      'mineral blooms'}],
 'name_truth': {'hidden_title_verdict': 'pending',
                'visible_evidence': ['pitted and abraded multicolor metal',
                                     'pit bowl',
                                     'scuffed rim',
                                     'abrasion',
                                     'oxide fleck',
                                     'polished island']},
 'owner_review': {'verdict': 'pending', 'instruction': 'NO BANDS; prisms, gradients, grunge, brushwork'},
 'construction_key': 'fsh:r3:chromatic_grunge',
 'spec_key': 'fsh:r3:chromatic_grunge:five-bound-feature-populations',
 'development_status': 'R3 nonband proof; actual-game validation and owner review pending',
 'previous_revision': {'id': 'R1',
                       'verdict': 'reject',
                       'reason': 'Owner rejected the promised light response'},
 'qualification_errors': ["name_truth.hidden_title_verdict must be 'pass'"],
 'review_asset_sha256': {'paint': 'f74c02504a67e53c0c4c4666e8a0041452b029875b52a03595f2627a3fa6a489',
                         'spec': 'c7a642c0a4449c5bef960b3bc805fa02083b3d4d6cfaa70e62bea286cce2ca99'},
 'palette_revision': {'date': '2026-09-18',
                      'owner_request': 'whole rainbow; yellow orange pink purple seafoam and shades within '
                                       'families',
                      'anchors': [['scarlet', 0, 0.96],
                                  ['ruby', 350, 0.92],
                                  ['coral', 12, 0.68],
                                  ['vermillion', 20, 0.95],
                                  ['orange', 30, 0.96],
                                  ['amber', 42, 0.91],
                                  ['gold', 51, 0.95],
                                  ['lemon', 61, 0.86],
                                  ['chartreuse', 79, 0.86],
                                  ['lime', 95, 0.92],
                                  ['leaf green', 115, 0.85],
                                  ['emerald', 140, 0.91],
                                  ['jade', 155, 0.72],
                                  ['seafoam', 162, 0.48],
                                  ['mint', 147, 0.38],
                                  ['turquoise', 176, 0.81],
                                  ['cyan', 188, 0.93],
                                  ['azure', 206, 0.91],
                                  ['cobalt', 228, 0.93],
                                  ['periwinkle', 245, 0.58],
                                  ['violet', 266, 0.89],
                                  ['lavender', 280, 0.48],
                                  ['purple', 291, 0.87],
                                  ['orchid', 309, 0.63],
                                  ['fuchsia', 324, 0.93],
                                  ['rose', 339, 0.55],
                                  ['pink', 350, 0.42],
                                  ['salmon', 9, 0.5]],
                      'measured_coverage': {'hue_30_degree_percent': [14.616,
                                                                      12.038,
                                                                      6.97,
                                                                      7.038,
                                                                      7.537,
                                                                      8.102,
                                                                      5.142,
                                                                      4.932,
                                                                      5.863,
                                                                      7.25,
                                                                      7.951,
                                                                      12.56],
                                            'seafoam_mint_percent': 5.537,
                                            'soft_pink_percent': 11.633,
                                            'lavender_percent': 5.127,
                                            'saturation_range': [0.274, 0.661, 0.929]},
                      'spec_pixels_unchanged': True}}
spec_fn, paint_fn = make_pair('fsh_frost_voltage')
