"""Hex Resonance — FRACTURED SHOKK — reviewed construction, motion verdict pending."""
from engine.expansions.fractured_shokk_2026 import make_pair
IDENTITY_CONTRACT = {'schema': 'spb-finish-identity/1', 'finish_id': 'fsh_hex_resonance', 'display_name': 'Hex Resonance — FRACTURED SHOKK', 'promise': 'Fine offset hexagonal resonators with split centers reveal saturated metallic reflections as illumination changes.', 'carrier_grammar': 'offset hexagonal resonators with split centers with five separate geometric feature masks and eight local material tiers.', 'spec_grammar': 'Each offset hexagonal resonators with split centers feature owns a metallic/rough/coat response tied to its visible boundaries.', 'reference_physics': {'mechanism': 'Fixed pigments tint metallic reflections; roughness shapes lobes and clearcoat controls the white overlay. This approximates spectral light play, not physical wavelength diffraction.', 'sources': ['SPB_WIKI.html#spec_guide', 'https://support.iracing.com/support/solutions/articles/31000168823-2023-season-1-release-notes-2022-12-06-01-']}, 'native_scale_px': [8, 32], 'mark_types': [{'name': 'hex wall', 'role': 'hex wall defines one distinct material-bearing feature'}, {'name': 'resonator bowl', 'role': 'resonator bowl defines one distinct material-bearing feature'}, {'name': 'split center', 'role': 'split center defines one distinct material-bearing feature'}, {'name': 'vertex', 'role': 'vertex defines one distinct material-bearing feature'}, {'name': 'outer gasket', 'role': 'outer gasket defines one distinct material-bearing feature'}], 'material_binding': {'M': ['hex wall', 'resonator bowl', 'split center', 'vertex', 'outer gasket'], 'R': ['hex wall', 'resonator bowl', 'split center', 'vertex', 'outer gasket'], 'Cc': ['hex wall', 'resonator bowl', 'split center', 'vertex', 'outer gasket']}, 'material_tiers': [0.18, 0.28, 0.38, 0.48, 0.58, 0.68, 0.78, 0.92], 'nearest_neighbors': [{'finish_id': 'xlab_hologram_metal', 'difference': 'Original offset hexagonal resonators with split centers instead of rotated square plates.'}, {'finish_id': 'hou_veiled_skull', 'difference': 'All-over optical surface rather than a concealed skull silhouette.'}], 'name_truth': {'hidden_title_verdict': 'pass', 'visible_evidence': ['hexagonal bowls', 'split resonator centers', 'contrasting outer gaskets'], 'evidence_scope': 'Agent structural recognition at native crop and whole sheet,2026-09-18; no owner acceptance or in-sim motion verdict implied.'}, 'construction_key': 'fsh20:hex_resonance:offset hexagonal resonators with split centers', 'spec_key': 'fsh20:hex_resonance:feature-bound-eight-tier-PBR', 'review_asset_sha256': {'paint': '4d55ca0a966ede3dea77098ed2254a38fa2fed4cab90c54d886fd35edc57c230', 'spec': '449b4229fab34510c680357ea39357c19b0274de5ea9366a9e19034041947046'}}
spec_fn, paint_fn = make_pair('fsh_hex_resonance')

# SPB-105 / FSH-R2 reset: owner rejects effect; earlier M7 is historical.
OWNER_REJECTION_R1 = {'verdict': 'reject', 'date': '2026-09-18', 'reason': 'Owner rejected 2026-09-18: does not reproduce the moving spectral highlight in the reference. Full design reset; not an accepted finish.', 'quote': 'These are not at ALL doing what the car in his example was doing.'}
IDENTITY_CONTRACT['owner_review'] = OWNER_REJECTION_R1
IDENTITY_CONTRACT['name_truth']['previous_internal_verdict'] = IDENTITY_CONTRACT['name_truth']['hidden_title_verdict']
IDENTITY_CONTRACT['name_truth']['hidden_title_verdict'] = 'fail'
IDENTITY_CONTRACT['name_truth']['rejection_scope'] = 'Promised light behavior failed owner review; texture recognition alone was insufficient.'
