"""Photon Circuit — FRACTURED SHOKK — reviewed construction, motion verdict pending."""
from engine.expansions.fractured_shokk_2026 import make_pair
IDENTITY_CONTRACT = {'schema': 'spb-finish-identity/1', 'finish_id': 'fsh_photon_circuit', 'display_name': 'Photon Circuit — FRACTURED SHOKK', 'promise': 'Fine alternating right-angle optical traces reveal saturated metallic reflections as illumination changes.', 'carrier_grammar': 'alternating right-angle optical traces with five separate geometric feature masks and eight local material tiers.', 'spec_grammar': 'Each alternating right-angle optical traces feature owns a metallic/rough/coat response tied to its visible boundaries.', 'reference_physics': {'mechanism': 'Fixed pigments tint metallic reflections; roughness shapes lobes and clearcoat controls the white overlay. This approximates spectral light play, not physical wavelength diffraction.', 'sources': ['SPB_WIKI.html#spec_guide', 'https://support.iracing.com/support/solutions/articles/31000168823-2023-season-1-release-notes-2022-12-06-01-']}, 'native_scale_px': [8, 32], 'mark_types': [{'name': 'trace', 'role': 'trace defines one distinct material-bearing feature'}, {'name': 'elbow', 'role': 'elbow defines one distinct material-bearing feature'}, {'name': 'terminal', 'role': 'terminal defines one distinct material-bearing feature'}, {'name': 'contact pad', 'role': 'contact pad defines one distinct material-bearing feature'}, {'name': 'insulator', 'role': 'insulator defines one distinct material-bearing feature'}], 'material_binding': {'M': ['trace', 'elbow', 'terminal', 'contact pad', 'insulator'], 'R': ['trace', 'elbow', 'terminal', 'contact pad', 'insulator'], 'Cc': ['trace', 'elbow', 'terminal', 'contact pad', 'insulator']}, 'material_tiers': [0.18, 0.28, 0.38, 0.48, 0.58, 0.68, 0.78, 0.92], 'nearest_neighbors': [{'finish_id': 'xlab_hologram_metal', 'difference': 'Original alternating right-angle optical traces instead of rotated square plates.'}, {'finish_id': 'hou_veiled_skull', 'difference': 'All-over optical surface rather than a concealed skull silhouette.'}], 'name_truth': {'hidden_title_verdict': 'pass', 'visible_evidence': ['right-angle traces', 'contrasting contact pads', 'dark insulating pockets'], 'evidence_scope': 'Agent structural recognition at native crop and whole sheet,2026-09-18; no owner acceptance or in-sim motion verdict implied.'}, 'construction_key': 'fsh20:photon_circuit:alternating right-angle optical traces', 'spec_key': 'fsh20:photon_circuit:feature-bound-eight-tier-PBR', 'review_asset_sha256': {'paint': 'd2489246ad21681e3722226b79e674c4d3aec64e76c2951d883e3e823bf608b4', 'spec': 'd195dc1a90aeef4eb32c4d2970a1f197ba6ccb253e11d71dda92e0b320fca413'}}
spec_fn, paint_fn = make_pair('fsh_photon_circuit')

# SPB-105 / FSH-R2 reset: owner rejects effect; earlier M7 is historical.
OWNER_REJECTION_R1 = {'verdict': 'reject', 'date': '2026-09-18', 'reason': 'Owner rejected 2026-09-18: does not reproduce the moving spectral highlight in the reference. Full design reset; not an accepted finish.', 'quote': 'These are not at ALL doing what the car in his example was doing.'}
IDENTITY_CONTRACT['owner_review'] = OWNER_REJECTION_R1
IDENTITY_CONTRACT['name_truth']['previous_internal_verdict'] = IDENTITY_CONTRACT['name_truth']['hidden_title_verdict']
IDENTITY_CONTRACT['name_truth']['hidden_title_verdict'] = 'fail'
IDENTITY_CONTRACT['name_truth']['rejection_scope'] = 'Promised light behavior failed owner review; texture recognition alone was insufficient.'
