"""SPB-105 / FSH-R3-COLOR; broader hues, same fine construction.
Owner requests yellow/orange/pink/purple/seafoam. M7 pending -> pending.
"""
from engine.expansions.fractured_shokk_2026 import make_pair
IDENTITY_CONTRACT = {'schema': 'spb-finish-identity/1',
 'finish_id': 'fsh_spectral_silver',
 'display_name': 'Prism Shards — FRACTURED SHOKK prototype',
 'promise': 'Irregular irregular angular prism chips reveal localized spectral highlights without repeated '
            'rainbow bands.',
 'carrier_grammar': 'irregular angular prism chips with five overlapping purpose-built material features and '
                    'nonperiodic chromatic gradients.',
 'spec_grammar': 'Each named irregular angular prism chips feature has a separate eight-tier response near '
                 'the actual-game spectral-metal window.',
 'reference_physics': {'mechanism': 'Fixed saturated pigment tints metallic reflections. Roughness and '
                                    'clearcoat determine highlight response. Actual-game calibration '
                                    'anchor255/40/218; no physical wavelength diffraction or animated paint '
                                    'claimed.',
                       'sources': ['R2_MECHANISM/DAYLIGHT_BREAKTHROUGH.md']},
 'native_scale_px': [8, 32],
 'mark_types': [{'name': 'prism face',
                 'role': 'prism face owns a visible material-bearing part of this construction'},
                {'name': 'cut shoulder',
                 'role': 'cut shoulder owns a visible material-bearing part of this construction'},
                {'name': 'split face',
                 'role': 'split face owns a visible material-bearing part of this construction'},
                {'name': 'buried chip',
                 'role': 'buried chip owns a visible material-bearing part of this construction'},
                {'name': 'point glint',
                 'role': 'point glint owns a visible material-bearing part of this construction'}],
 'material_binding': {'M': ['prism face', 'cut shoulder', 'split face', 'buried chip', 'point glint'],
                      'R': ['prism face', 'cut shoulder', 'split face', 'buried chip', 'point glint'],
                      'Cc': ['prism face', 'cut shoulder', 'split face', 'buried chip', 'point glint']},
 'material_tiers': [0.18, 0.28, 0.38, 0.48, 0.58, 0.68, 0.78, 0.92],
 'nearest_neighbors': [{'finish_id': 'fsh_r3_brushed_spectrum',
                        'difference': 'irregular angular prism chips versus layered short paintbrush '
                                      'strokes'},
                       {'finish_id': 'fsh_r3_chromatic_grunge',
                        'difference': 'irregular angular prism chips versus pitted and abraded multicolor '
                                      'metal'},
                       {'finish_id': 'fsh_r3_opal_bloom',
                        'difference': 'irregular angular prism chips versus overlapping irregular mineral '
                                      'blooms'}],
 'name_truth': {'hidden_title_verdict': 'pending',
                'visible_evidence': ['irregular angular prism chips',
                                     'prism face',
                                     'cut shoulder',
                                     'split face',
                                     'buried chip',
                                     'point glint']},
 'owner_review': {'verdict': 'pending', 'instruction': 'NO BANDS; prisms, gradients, grunge, brushwork'},
 'construction_key': 'fsh:r3:prism_shards',
 'spec_key': 'fsh:r3:prism_shards:five-bound-feature-populations',
 'development_status': 'R3 nonband proof; actual-game validation and owner review pending',
 'previous_revision': {'id': 'R1',
                       'verdict': 'reject',
                       'reason': 'Owner rejected the promised light response'},
 'qualification_errors': ["name_truth.hidden_title_verdict must be 'pass'"],
 'review_asset_sha256': {'paint': '9e7c8f1ce24836c86a3184b6ff0c766e5a2155b08b38fdfd5f2302261174e53b',
                         'spec': '6533e5abbd3593bafff9f695e874762b92c38c1951197e1a4b895067a054c7b3'},
 'palette_revision': {'date': '2026-09-18',
                      'owner_request': 'whole rainbow; yellow orange pink purple seafoam and shades within '
                                       'families',
                      'anchors': [['scarlet', 0, 0.96],
                                  ['ruby', 350, 0.92],
                                  ['coral', 12, 0.68],
                                  ['vermillion', 20, 0.95],
                                  ['orange', 30, 0.96],
                                  ['amber', 42, 0.91],
                                  ['gold', 51, 0.95],
                                  ['lemon', 61, 0.86],
                                  ['chartreuse', 79, 0.86],
                                  ['lime', 95, 0.92],
                                  ['leaf green', 115, 0.85],
                                  ['emerald', 140, 0.91],
                                  ['jade', 155, 0.72],
                                  ['seafoam', 162, 0.48],
                                  ['mint', 147, 0.38],
                                  ['turquoise', 176, 0.81],
                                  ['cyan', 188, 0.93],
                                  ['azure', 206, 0.91],
                                  ['cobalt', 228, 0.93],
                                  ['periwinkle', 245, 0.58],
                                  ['violet', 266, 0.89],
                                  ['lavender', 280, 0.48],
                                  ['purple', 291, 0.87],
                                  ['orchid', 309, 0.63],
                                  ['fuchsia', 324, 0.93],
                                  ['rose', 339, 0.55],
                                  ['pink', 350, 0.42],
                                  ['salmon', 9, 0.5]],
                      'measured_coverage': {'hue_30_degree_percent': [15.328,
                                                                      10.475,
                                                                      6.823,
                                                                      6.695,
                                                                      7.211,
                                                                      10.239,
                                                                      7.353,
                                                                      4.447,
                                                                      6.383,
                                                                      5.496,
                                                                      8.37,
                                                                      11.18],
                                            'seafoam_mint_percent': 6.071,
                                            'soft_pink_percent': 10.502,
                                            'lavender_percent': 4.741,
                                            'saturation_range': [0.269, 0.673, 0.932]},
                      'spec_pixels_unchanged': True}}
spec_fn, paint_fn = make_pair('fsh_spectral_silver')
