"""Nacre Cascade — FRACTURED SHOKK — reviewed construction, motion verdict pending."""
from engine.expansions.fractured_shokk_2026 import make_pair
IDENTITY_CONTRACT = {'schema': 'spb-finish-identity/1', 'finish_id': 'fsh_nacre_cascade', 'display_name': 'Nacre Cascade — FRACTURED SHOKK', 'promise': 'Fine staggered nested shell fans reveal saturated metallic reflections as illumination changes.', 'carrier_grammar': 'staggered nested shell fans with five separate geometric feature masks and eight local material tiers.', 'spec_grammar': 'Each staggered nested shell fans feature owns a metallic/rough/coat response tied to its visible boundaries.', 'reference_physics': {'mechanism': 'Fixed pigments tint metallic reflections; roughness shapes lobes and clearcoat controls the white overlay. This approximates spectral light play, not physical wavelength diffraction.', 'sources': ['SPB_WIKI.html#spec_guide', 'https://support.iracing.com/support/solutions/articles/31000168823-2023-season-1-release-notes-2022-12-06-01-']}, 'native_scale_px': [8, 32], 'mark_types': [{'name': 'shell lip', 'role': 'shell lip defines one distinct material-bearing feature'}, {'name': 'shell bowl', 'role': 'shell bowl defines one distinct material-bearing feature'}, {'name': 'growth ring', 'role': 'growth ring defines one distinct material-bearing feature'}, {'name': 'hinge', 'role': 'hinge defines one distinct material-bearing feature'}, {'name': 'overlap shadow', 'role': 'overlap shadow defines one distinct material-bearing feature'}], 'material_binding': {'M': ['shell lip', 'shell bowl', 'growth ring', 'hinge', 'overlap shadow'], 'R': ['shell lip', 'shell bowl', 'growth ring', 'hinge', 'overlap shadow'], 'Cc': ['shell lip', 'shell bowl', 'growth ring', 'hinge', 'overlap shadow']}, 'material_tiers': [0.18, 0.28, 0.38, 0.48, 0.58, 0.68, 0.78, 0.92], 'nearest_neighbors': [{'finish_id': 'xlab_hologram_metal', 'difference': 'Original staggered nested shell fans instead of rotated square plates.'}, {'finish_id': 'hou_veiled_skull', 'difference': 'All-over optical surface rather than a concealed skull silhouette.'}], 'name_truth': {'hidden_title_verdict': 'pass', 'visible_evidence': ['overlapping shell fans', 'nested growth arcs', 'small dark hinge bowls'], 'evidence_scope': 'Agent structural recognition at native crop and whole sheet,2026-09-18; no owner acceptance or in-sim motion verdict implied.'}, 'construction_key': 'fsh20:nacre_cascade:staggered nested shell fans', 'spec_key': 'fsh20:nacre_cascade:feature-bound-eight-tier-PBR', 'review_asset_sha256': {'paint': '0fe4faf582e3255cddcc6eb44bc9d74d5970bfd5247637d121a43382353d3a1a', 'spec': '7e96658a479a10f1635972bc9ad03fd944d6c37e3a1908bae67bb9f30a4e25af'}}
spec_fn, paint_fn = make_pair('fsh_nacre_cascade')

# SPB-105 / FSH-R2 reset: owner rejects effect; earlier M7 is historical.
OWNER_REJECTION_R1 = {'verdict': 'reject', 'date': '2026-09-18', 'reason': 'Owner rejected 2026-09-18: does not reproduce the moving spectral highlight in the reference. Full design reset; not an accepted finish.', 'quote': 'These are not at ALL doing what the car in his example was doing.'}
IDENTITY_CONTRACT['owner_review'] = OWNER_REJECTION_R1
IDENTITY_CONTRACT['name_truth']['previous_internal_verdict'] = IDENTITY_CONTRACT['name_truth']['hidden_title_verdict']
IDENTITY_CONTRACT['name_truth']['hidden_title_verdict'] = 'fail'
IDENTITY_CONTRACT['name_truth']['rejection_scope'] = 'Promised light behavior failed owner review; texture recognition alone was insufficient.'
