"""Ferro Crown — FRACTURED SHOKK — reviewed construction, motion verdict pending."""
from engine.expansions.fractured_shokk_2026 import make_pair
IDENTITY_CONTRACT = {'schema': 'spb-finish-identity/1', 'finish_id': 'fsh_ferro_crown', 'display_name': 'Ferro Crown — FRACTURED SHOKK', 'promise': 'Fine five-point fluid crowns with rounded basins reveal saturated metallic reflections as illumination changes.', 'carrier_grammar': 'five-point fluid crowns with rounded basins with five separate geometric feature masks and eight local material tiers.', 'spec_grammar': 'Each five-point fluid crowns with rounded basins feature owns a metallic/rough/coat response tied to its visible boundaries.', 'reference_physics': {'mechanism': 'Fixed pigments tint metallic reflections; roughness shapes lobes and clearcoat controls the white overlay. This approximates spectral light play, not physical wavelength diffraction.', 'sources': ['SPB_WIKI.html#spec_guide', 'https://support.iracing.com/support/solutions/articles/31000168823-2023-season-1-release-notes-2022-12-06-01-']}, 'native_scale_px': [8, 32], 'mark_types': [{'name': 'spike', 'role': 'spike defines one distinct material-bearing feature'}, {'name': 'basin', 'role': 'basin defines one distinct material-bearing feature'}, {'name': 'crown lip', 'role': 'crown lip defines one distinct material-bearing feature'}, {'name': 'central bead', 'role': 'central bead defines one distinct material-bearing feature'}, {'name': 'magnetic saddle', 'role': 'magnetic saddle defines one distinct material-bearing feature'}], 'material_binding': {'M': ['spike', 'basin', 'crown lip', 'central bead', 'magnetic saddle'], 'R': ['spike', 'basin', 'crown lip', 'central bead', 'magnetic saddle'], 'Cc': ['spike', 'basin', 'crown lip', 'central bead', 'magnetic saddle']}, 'material_tiers': [0.18, 0.28, 0.38, 0.48, 0.58, 0.68, 0.78, 0.92], 'nearest_neighbors': [{'finish_id': 'xlab_hologram_metal', 'difference': 'Original five-point fluid crowns with rounded basins instead of rotated square plates.'}, {'finish_id': 'hou_veiled_skull', 'difference': 'All-over optical surface rather than a concealed skull silhouette.'}], 'name_truth': {'hidden_title_verdict': 'pass', 'visible_evidence': ['five-point fluid crowns', 'rounded central basins', 'contrasting crown lips'], 'evidence_scope': 'Agent structural recognition at native crop and whole sheet,2026-09-18; no owner acceptance or in-sim motion verdict implied.'}, 'construction_key': 'fsh20:ferro_crown:five-point fluid crowns with rounded basins', 'spec_key': 'fsh20:ferro_crown:feature-bound-eight-tier-PBR', 'review_asset_sha256': {'paint': 'bd6425c6bfeae038cbd748cef814ddb19a1c5f128b55c49bf5ecbd1c2b1462df', 'spec': 'dc696593dd49eb3e222253a22d7a49f9f8ee84d74425dd1cb649f856807f5667'}}
spec_fn, paint_fn = make_pair('fsh_ferro_crown')

# SPB-105 / FSH-R2 reset: owner rejects effect; earlier M7 is historical.
OWNER_REJECTION_R1 = {'verdict': 'reject', 'date': '2026-09-18', 'reason': 'Owner rejected 2026-09-18: does not reproduce the moving spectral highlight in the reference. Full design reset; not an accepted finish.', 'quote': 'These are not at ALL doing what the car in his example was doing.'}
IDENTITY_CONTRACT['owner_review'] = OWNER_REJECTION_R1
IDENTITY_CONTRACT['name_truth']['previous_internal_verdict'] = IDENTITY_CONTRACT['name_truth']['hidden_title_verdict']
IDENTITY_CONTRACT['name_truth']['hidden_title_verdict'] = 'fail'
IDENTITY_CONTRACT['name_truth']['rejection_scope'] = 'Promised light behavior failed owner review; texture recognition alone was insufficient.'
