"""SPB-105 / FSH-R3-COLOR; broader hues, same fine construction.
Owner requests yellow/orange/pink/purple/seafoam. M7 pending -> pending.
"""
from engine.expansions.fractured_shokk_2026 import make_pair
IDENTITY_CONTRACT = {'schema': 'spb-finish-identity/1',
 'finish_id': 'fsh_ribbon_refraction',
 'display_name': 'Brushed Spectrum — FRACTURED SHOKK prototype',
 'promise': 'Irregular layered short paintbrush strokes reveal localized spectral highlights without '
            'repeated rainbow bands.',
 'carrier_grammar': 'layered short paintbrush strokes with five overlapping purpose-built material features '
                    'and nonperiodic chromatic gradients.',
 'spec_grammar': 'Each named layered short paintbrush strokes feature has a separate eight-tier response '
                 'near the actual-game spectral-metal window.',
 'reference_physics': {'mechanism': 'Fixed saturated pigment tints metallic reflections. Roughness and '
                                    'clearcoat determine highlight response. Actual-game calibration '
                                    'anchor255/40/218; no physical wavelength diffraction or animated paint '
                                    'claimed.',
                       'sources': ['R2_MECHANISM/DAYLIGHT_BREAKTHROUGH.md']},
 'native_scale_px': [8, 32],
 'mark_types': [{'name': 'stroke belly',
                 'role': 'stroke belly owns a visible material-bearing part of this construction'},
                {'name': 'dry bristle',
                 'role': 'dry bristle owns a visible material-bearing part of this construction'},
                {'name': 'loaded tip',
                 'role': 'loaded tip owns a visible material-bearing part of this construction'},
                {'name': 'cross stroke',
                 'role': 'cross stroke owns a visible material-bearing part of this construction'},
                {'name': 'feathered end',
                 'role': 'feathered end owns a visible material-bearing part of this construction'}],
 'material_binding': {'M': ['stroke belly', 'dry bristle', 'loaded tip', 'cross stroke', 'feathered end'],
                      'R': ['stroke belly', 'dry bristle', 'loaded tip', 'cross stroke', 'feathered end'],
                      'Cc': ['stroke belly', 'dry bristle', 'loaded tip', 'cross stroke', 'feathered end']},
 'material_tiers': [0.18, 0.28, 0.38, 0.48, 0.58, 0.68, 0.78, 0.92],
 'nearest_neighbors': [{'finish_id': 'fsh_r3_prism_shards',
                        'difference': 'layered short paintbrush strokes versus irregular angular prism '
                                      'chips'},
                       {'finish_id': 'fsh_r3_chromatic_grunge',
                        'difference': 'layered short paintbrush strokes versus pitted and abraded multicolor '
                                      'metal'},
                       {'finish_id': 'fsh_r3_opal_bloom',
                        'difference': 'layered short paintbrush strokes versus overlapping irregular mineral '
                                      'blooms'}],
 'name_truth': {'hidden_title_verdict': 'pending',
                'visible_evidence': ['layered short paintbrush strokes',
                                     'stroke belly',
                                     'dry bristle',
                                     'loaded tip',
                                     'cross stroke',
                                     'feathered end']},
 'owner_review': {'verdict': 'pending', 'instruction': 'NO BANDS; prisms, gradients, grunge, brushwork'},
 'construction_key': 'fsh:r3:brushed_spectrum',
 'spec_key': 'fsh:r3:brushed_spectrum:five-bound-feature-populations',
 'development_status': 'R3 nonband proof; actual-game validation and owner review pending',
 'previous_revision': {'id': 'R1',
                       'verdict': 'reject',
                       'reason': 'Owner rejected the promised light response'},
 'qualification_errors': ["name_truth.hidden_title_verdict must be 'pass'"],
 'review_asset_sha256': {'paint': '769b2f393412d1d331e97a71a0f70b35cf5eb6b3f4f8bc1ef2e41a1ea1f4c8f5',
                         'spec': 'c571f9b9a201de0bae1b6e64d8838d0c870b76c617f9df67840a88380f58a9f6'},
 'palette_revision': {'date': '2026-09-18',
                      'owner_request': 'whole rainbow; yellow orange pink purple seafoam and shades within '
                                       'families',
                      'anchors': [['scarlet', 0, 0.96],
                                  ['ruby', 350, 0.92],
                                  ['coral', 12, 0.68],
                                  ['vermillion', 20, 0.95],
                                  ['orange', 30, 0.96],
                                  ['amber', 42, 0.91],
                                  ['gold', 51, 0.95],
                                  ['lemon', 61, 0.86],
                                  ['chartreuse', 79, 0.86],
                                  ['lime', 95, 0.92],
                                  ['leaf green', 115, 0.85],
                                  ['emerald', 140, 0.91],
                                  ['jade', 155, 0.72],
                                  ['seafoam', 162, 0.48],
                                  ['mint', 147, 0.38],
                                  ['turquoise', 176, 0.81],
                                  ['cyan', 188, 0.93],
                                  ['azure', 206, 0.91],
                                  ['cobalt', 228, 0.93],
                                  ['periwinkle', 245, 0.58],
                                  ['violet', 266, 0.89],
                                  ['lavender', 280, 0.48],
                                  ['purple', 291, 0.87],
                                  ['orchid', 309, 0.63],
                                  ['fuchsia', 324, 0.93],
                                  ['rose', 339, 0.55],
                                  ['pink', 350, 0.42],
                                  ['salmon', 9, 0.5]],
                      'measured_coverage': {'hue_30_degree_percent': [15.461,
                                                                      14.413,
                                                                      7.734,
                                                                      7.12,
                                                                      6.976,
                                                                      8.136,
                                                                      6.133,
                                                                      4.861,
                                                                      5.19,
                                                                      5.559,
                                                                      7.106,
                                                                      11.311],
                                            'seafoam_mint_percent': 5.118,
                                            'soft_pink_percent': 10.379,
                                            'lavender_percent': 3.926,
                                            'saturation_range': [0.274, 0.667, 0.929]},
                      'spec_pixels_unchanged': True}}
spec_fn, paint_fn = make_pair('fsh_ribbon_refraction')
