"""Iris Turbine — FRACTURED SHOKK — reviewed construction, motion verdict pending."""
from engine.expansions.fractured_shokk_2026 import make_pair
IDENTITY_CONTRACT = {'schema': 'spb-finish-identity/1', 'finish_id': 'fsh_iris_turbine', 'display_name': 'Iris Turbine — FRACTURED SHOKK', 'promise': 'Fine curved seven-blade micro turbines reveal saturated metallic reflections as illumination changes.', 'carrier_grammar': 'curved seven-blade micro turbines with five separate geometric feature masks and eight local material tiers.', 'spec_grammar': 'Each curved seven-blade micro turbines feature owns a metallic/rough/coat response tied to its visible boundaries.', 'reference_physics': {'mechanism': 'Fixed pigments tint metallic reflections; roughness shapes lobes and clearcoat controls the white overlay. This approximates spectral light play, not physical wavelength diffraction.', 'sources': ['SPB_WIKI.html#spec_guide', 'https://support.iracing.com/support/solutions/articles/31000168823-2023-season-1-release-notes-2022-12-06-01-']}, 'native_scale_px': [8, 32], 'mark_types': [{'name': 'blade', 'role': 'blade defines one distinct material-bearing feature'}, {'name': 'blade edge', 'role': 'blade edge defines one distinct material-bearing feature'}, {'name': 'hub', 'role': 'hub defines one distinct material-bearing feature'}, {'name': 'sweep groove', 'role': 'sweep groove defines one distinct material-bearing feature'}, {'name': 'interblade pocket', 'role': 'interblade pocket defines one distinct material-bearing feature'}], 'material_binding': {'M': ['blade', 'blade edge', 'hub', 'sweep groove', 'interblade pocket'], 'R': ['blade', 'blade edge', 'hub', 'sweep groove', 'interblade pocket'], 'Cc': ['blade', 'blade edge', 'hub', 'sweep groove', 'interblade pocket']}, 'material_tiers': [0.18, 0.28, 0.38, 0.48, 0.58, 0.68, 0.78, 0.92], 'nearest_neighbors': [{'finish_id': 'xlab_hologram_metal', 'difference': 'Original curved seven-blade micro turbines instead of rotated square plates.'}, {'finish_id': 'hou_veiled_skull', 'difference': 'All-over optical surface rather than a concealed skull silhouette.'}], 'name_truth': {'hidden_title_verdict': 'pass', 'visible_evidence': ['seven curved turbine blades', 'round central hubs', 'spiral interblade channels'], 'evidence_scope': 'Agent structural recognition at native crop and whole sheet,2026-09-18; no owner acceptance or in-sim motion verdict implied.'}, 'construction_key': 'fsh20:iris_turbine:curved seven-blade micro turbines', 'spec_key': 'fsh20:iris_turbine:feature-bound-eight-tier-PBR', 'review_asset_sha256': {'paint': '5f507ea9689fbdcdfa141ab0c79ff20c3071263cadba831457f284b26aea50a2', 'spec': 'c98fb477f06c0419be366555074e545ec30a56f31dd94cd2633e86a932b71334'}}
spec_fn, paint_fn = make_pair('fsh_iris_turbine')

# SPB-105 / FSH-R2 reset: owner rejects effect; earlier M7 is historical.
OWNER_REJECTION_R1 = {'verdict': 'reject', 'date': '2026-09-18', 'reason': 'Owner rejected 2026-09-18: does not reproduce the moving spectral highlight in the reference. Full design reset; not an accepted finish.', 'quote': 'These are not at ALL doing what the car in his example was doing.'}
IDENTITY_CONTRACT['owner_review'] = OWNER_REJECTION_R1
IDENTITY_CONTRACT['name_truth']['previous_internal_verdict'] = IDENTITY_CONTRACT['name_truth']['hidden_title_verdict']
IDENTITY_CONTRACT['name_truth']['hidden_title_verdict'] = 'fail'
IDENTITY_CONTRACT['name_truth']['rejection_scope'] = 'Promised light behavior failed owner review; texture recognition alone was insufficient.'
