"""Herringbone Flash — FRACTURED SHOKK — reviewed construction, motion verdict pending."""
from engine.expansions.fractured_shokk_2026 import make_pair
IDENTITY_CONTRACT = {'schema': 'spb-finish-identity/1', 'finish_id': 'fsh_herringbone_flash', 'display_name': 'Herringbone Flash — FRACTURED SHOKK', 'promise': 'Fine interlocked angular optical parquet reveal saturated metallic reflections as illumination changes.', 'carrier_grammar': 'interlocked angular optical parquet with five separate geometric feature masks and eight local material tiers.', 'spec_grammar': 'Each interlocked angular optical parquet feature owns a metallic/rough/coat response tied to its visible boundaries.', 'reference_physics': {'mechanism': 'Fixed pigments tint metallic reflections; roughness shapes lobes and clearcoat controls the white overlay. This approximates spectral light play, not physical wavelength diffraction.', 'sources': ['SPB_WIKI.html#spec_guide', 'https://support.iracing.com/support/solutions/articles/31000168823-2023-season-1-release-notes-2022-12-06-01-']}, 'native_scale_px': [8, 32], 'mark_types': [{'name': 'left plank', 'role': 'left plank defines one distinct material-bearing feature'}, {'name': 'right plank', 'role': 'right plank defines one distinct material-bearing feature'}, {'name': 'bevel', 'role': 'bevel defines one distinct material-bearing feature'}, {'name': 'end grain', 'role': 'end grain defines one distinct material-bearing feature'}, {'name': 'joint', 'role': 'joint defines one distinct material-bearing feature'}], 'material_binding': {'M': ['left plank', 'right plank', 'bevel', 'end grain', 'joint'], 'R': ['left plank', 'right plank', 'bevel', 'end grain', 'joint'], 'Cc': ['left plank', 'right plank', 'bevel', 'end grain', 'joint']}, 'material_tiers': [0.18, 0.28, 0.38, 0.48, 0.58, 0.68, 0.78, 0.92], 'nearest_neighbors': [{'finish_id': 'xlab_hologram_metal', 'difference': 'Original interlocked angular optical parquet instead of rotated square plates.'}, {'finish_id': 'hou_veiled_skull', 'difference': 'All-over optical surface rather than a concealed skull silhouette.'}], 'name_truth': {'hidden_title_verdict': 'pass', 'visible_evidence': ['interlocked short planks', 'zigzag herringbone joints', 'opposed plank directions'], 'evidence_scope': 'Agent structural recognition at native crop and whole sheet,2026-09-18; no owner acceptance or in-sim motion verdict implied.'}, 'construction_key': 'fsh20:herringbone_flash:interlocked angular optical parquet', 'spec_key': 'fsh20:herringbone_flash:feature-bound-eight-tier-PBR', 'review_asset_sha256': {'paint': '0c10465e38dc8c8ef492dafbfb8257a2012ff7c3a0df9358c571429d489b16b4', 'spec': '4ceff4531f7d97d9b016f5ae636e0c870776a749904961e261627302da78830f'}}
spec_fn, paint_fn = make_pair('fsh_herringbone_flash')

# SPB-105 / FSH-R2 reset: owner rejects effect; earlier M7 is historical.
OWNER_REJECTION_R1 = {'verdict': 'reject', 'date': '2026-09-18', 'reason': 'Owner rejected 2026-09-18: does not reproduce the moving spectral highlight in the reference. Full design reset; not an accepted finish.', 'quote': 'These are not at ALL doing what the car in his example was doing.'}
IDENTITY_CONTRACT['owner_review'] = OWNER_REJECTION_R1
IDENTITY_CONTRACT['name_truth']['previous_internal_verdict'] = IDENTITY_CONTRACT['name_truth']['hidden_title_verdict']
IDENTITY_CONTRACT['name_truth']['hidden_title_verdict'] = 'fail'
IDENTITY_CONTRACT['name_truth']['rejection_scope'] = 'Promised light behavior failed owner review; texture recognition alone was insufficient.'
