"""Meteor Wake — FRACTURED SHOKK — reviewed construction, motion verdict pending."""
from engine.expansions.fractured_shokk_2026 import make_pair
IDENTITY_CONTRACT = {'schema': 'spb-finish-identity/1', 'finish_id': 'fsh_meteor_wake', 'display_name': 'Meteor Wake — FRACTURED SHOKK', 'promise': 'Fine staggered tapered comet wakes reveal saturated metallic reflections as illumination changes.', 'carrier_grammar': 'staggered tapered comet wakes with five separate geometric feature masks and eight local material tiers.', 'spec_grammar': 'Each staggered tapered comet wakes feature owns a metallic/rough/coat response tied to its visible boundaries.', 'reference_physics': {'mechanism': 'Fixed pigments tint metallic reflections; roughness shapes lobes and clearcoat controls the white overlay. This approximates spectral light play, not physical wavelength diffraction.', 'sources': ['SPB_WIKI.html#spec_guide', 'https://support.iracing.com/support/solutions/articles/31000168823-2023-season-1-release-notes-2022-12-06-01-']}, 'native_scale_px': [8, 32], 'mark_types': [{'name': 'meteor head', 'role': 'meteor head defines one distinct material-bearing feature'}, {'name': 'split tail', 'role': 'split tail defines one distinct material-bearing feature'}, {'name': 'wake', 'role': 'wake defines one distinct material-bearing feature'}, {'name': 'shoulder', 'role': 'shoulder defines one distinct material-bearing feature'}, {'name': 'dark pocket', 'role': 'dark pocket defines one distinct material-bearing feature'}], 'material_binding': {'M': ['meteor head', 'split tail', 'wake', 'shoulder', 'dark pocket'], 'R': ['meteor head', 'split tail', 'wake', 'shoulder', 'dark pocket'], 'Cc': ['meteor head', 'split tail', 'wake', 'shoulder', 'dark pocket']}, 'material_tiers': [0.18, 0.28, 0.38, 0.48, 0.58, 0.68, 0.78, 0.92], 'nearest_neighbors': [{'finish_id': 'xlab_hologram_metal', 'difference': 'Original staggered tapered comet wakes instead of rotated square plates.'}, {'finish_id': 'hou_veiled_skull', 'difference': 'All-over optical surface rather than a concealed skull silhouette.'}], 'name_truth': {'hidden_title_verdict': 'pass', 'visible_evidence': ['tapering wake triangles', 'rounded leading regions', 'split trailing channels'], 'evidence_scope': 'Agent structural recognition at native crop and whole sheet,2026-09-18; no owner acceptance or in-sim motion verdict implied.'}, 'construction_key': 'fsh20:meteor_wake:staggered tapered comet wakes', 'spec_key': 'fsh20:meteor_wake:feature-bound-eight-tier-PBR', 'review_asset_sha256': {'paint': '990277e4b5d2e48616c96e6cfd53a308c6eeee37e0c02480e029763eca12b051', 'spec': 'c44647bc855bec1fd5d447ef1a393d93f4f146c91309604d3e9f05efece8d8b5'}}
spec_fn, paint_fn = make_pair('fsh_meteor_wake')

# SPB-105 / FSH-R2 reset: owner rejects effect; earlier M7 is historical.
OWNER_REJECTION_R1 = {'verdict': 'reject', 'date': '2026-09-18', 'reason': 'Owner rejected 2026-09-18: does not reproduce the moving spectral highlight in the reference. Full design reset; not an accepted finish.', 'quote': 'These are not at ALL doing what the car in his example was doing.'}
IDENTITY_CONTRACT['owner_review'] = OWNER_REJECTION_R1
IDENTITY_CONTRACT['name_truth']['previous_internal_verdict'] = IDENTITY_CONTRACT['name_truth']['hidden_title_verdict']
IDENTITY_CONTRACT['name_truth']['hidden_title_verdict'] = 'fail'
IDENTITY_CONTRACT['name_truth']['rejection_scope'] = 'Promised light behavior failed owner review; texture recognition alone was insufficient.'
