"""Quasicrystal Fire — FRACTURED SHOKK — reviewed construction, motion verdict pending."""
from engine.expansions.fractured_shokk_2026 import make_pair
IDENTITY_CONTRACT = {'schema': 'spb-finish-identity/1', 'finish_id': 'fsh_quasicrystal_fire', 'display_name': 'Quasicrystal Fire — FRACTURED SHOKK', 'promise': 'Fine five-axis aperiodic interference crystals reveal saturated metallic reflections as illumination changes.', 'carrier_grammar': 'five-axis aperiodic interference crystals with five separate geometric feature masks and eight local material tiers.', 'spec_grammar': 'Each five-axis aperiodic interference crystals feature owns a metallic/rough/coat response tied to its visible boundaries.', 'reference_physics': {'mechanism': 'Fixed pigments tint metallic reflections; roughness shapes lobes and clearcoat controls the white overlay. This approximates spectral light play, not physical wavelength diffraction.', 'sources': ['SPB_WIKI.html#spec_guide', 'https://support.iracing.com/support/solutions/articles/31000168823-2023-season-1-release-notes-2022-12-06-01-']}, 'native_scale_px': [8, 32], 'mark_types': [{'name': 'crystal island', 'role': 'crystal island defines one distinct material-bearing feature'}, {'name': 'node', 'role': 'node defines one distinct material-bearing feature'}, {'name': 'crossing', 'role': 'crossing defines one distinct material-bearing feature'}, {'name': 'low saddle', 'role': 'low saddle defines one distinct material-bearing feature'}, {'name': 'crystal rim', 'role': 'crystal rim defines one distinct material-bearing feature'}], 'material_binding': {'M': ['crystal island', 'node', 'crossing', 'low saddle', 'crystal rim'], 'R': ['crystal island', 'node', 'crossing', 'low saddle', 'crystal rim'], 'Cc': ['crystal island', 'node', 'crossing', 'low saddle', 'crystal rim']}, 'material_tiers': [0.18, 0.28, 0.38, 0.48, 0.58, 0.68, 0.78, 0.92], 'nearest_neighbors': [{'finish_id': 'xlab_hologram_metal', 'difference': 'Original five-axis aperiodic interference crystals instead of rotated square plates.'}, {'finish_id': 'hou_veiled_skull', 'difference': 'All-over optical surface rather than a concealed skull silhouette.'}], 'name_truth': {'hidden_title_verdict': 'pass', 'visible_evidence': ['aperiodic crystal islands', 'five-direction crossings', 'curved interlocking rims'], 'evidence_scope': 'Agent structural recognition at native crop and whole sheet,2026-09-18; no owner acceptance or in-sim motion verdict implied.'}, 'construction_key': 'fsh20:quasicrystal_fire:five-axis aperiodic interference crystals', 'spec_key': 'fsh20:quasicrystal_fire:feature-bound-eight-tier-PBR', 'review_asset_sha256': {'paint': 'b7d3213949d488fe4f4a14486ece2fe350c08e5b9f0b437156f0c40fbf4ffb22', 'spec': '3cb7695a1e0352f0284bcaea52b9b0e724e6d7c440ecd16e5983b7838d715503'}}
spec_fn, paint_fn = make_pair('fsh_quasicrystal_fire')

# SPB-105 / FSH-R2 reset: owner rejects effect; earlier M7 is historical.
OWNER_REJECTION_R1 = {'verdict': 'reject', 'date': '2026-09-18', 'reason': 'Owner rejected 2026-09-18: does not reproduce the moving spectral highlight in the reference. Full design reset; not an accepted finish.', 'quote': 'These are not at ALL doing what the car in his example was doing.'}
IDENTITY_CONTRACT['owner_review'] = OWNER_REJECTION_R1
IDENTITY_CONTRACT['name_truth']['previous_internal_verdict'] = IDENTITY_CONTRACT['name_truth']['hidden_title_verdict']
IDENTITY_CONTRACT['name_truth']['hidden_title_verdict'] = 'fail'
IDENTITY_CONTRACT['name_truth']['rejection_scope'] = 'Promised light behavior failed owner review; texture recognition alone was insufficient.'
