#!/usr/bin/env python
"""Build js/spb-ai-knowledge.js — the AI copilot's help library (SPB-AI 2026-09-30).

Sources (edit these, then re-run this script; never hand-edit the .js):
  docs/ai_knowledge/*.md   hand-written cards for the copilot (how Pro works, spec, recipes, limits)
  tutorials/*.md           the shipped tutorial series (how-to for the buyer)
Each `## Heading` becomes one searchable chunk. The runtime API is window.SpbAIKnowledge.search(query, maxChars).
Usage:  python scripts/build_ai_knowledge.py
"""
import glob
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, 'scripts', 'ai_atlas'))
import enc_hidden as EH   # owner rule 2026-10-04: hidden features (list: scripts/ai_atlas/enc_hidden_features.json) never reach the AI knowledge library
SKIP_HEADINGS = re.compile(r'^(next up|try it yourself|what you.ll learn|prerequisite|estimated time|troubleshooting\s*$)', re.I)
MAX_BODY = 1500


def clean(body):
    body = re.sub(r'!\[[^\]]*\]\([^)]*\)', '', body)            # images
    body = re.sub(r'\[([^\]]+)\]\([^)]*\)', r'\1', body)        # links -> text
    body = re.sub(r'`{3}[^\n]*\n', '', body)
    body = re.sub(r'\n{3,}', '\n\n', body)
    body = re.sub(r'[ \t]+\n', '\n', body).strip()
    return body


def chunks_of(path, kind):
    text = EH.scrub_md(open(path, encoding='utf-8').read().replace('\r\n', '\n'))   # drops hidden how-tos / sentences, renumbers steps
    m = re.match(r'#\s+(.+)', text)
    doc = re.sub(r'\s*\(AI knowledge card\)\s*', '', m.group(1)).strip() if m else os.path.basename(path)
    out = []
    parts = re.split(r'\n(?=## )', text)
    for p in parts:
        if not p.startswith('## '):
            continue
        head, _, body = p.partition('\n')
        head = head[3:].strip()
        head = re.sub(r'^Step \d+\s*[—-]\s*', '', head)
        if SKIP_HEADINGS.match(head):
            continue
        body = clean(body)
        if len(body) < 40:
            continue
        if len(body) > MAX_BODY:
            cut = body.rfind('\n', 0, MAX_BODY)
            body = body[:cut if cut > MAX_BODY // 2 else MAX_BODY].rstrip() + ' ...'
        if kind == 'tutorial': body = '(Tutorial text: menu paths such as File / View / Layer -> ... come from an older layout and may not exist; name buttons only as in the WHERE THINGS ARE card.) ' + body
        ch = {'t': doc + ' > ' + head, 'k': kind, 'b': body}
        if re.search(r'`?(File|View|Layer|Edit|Window)\s*(→|->)', body) or 'Ctrl+S' in body and kind == 'tutorial': ch['x'] = 1      # menu paths the current UI does not have
        out.append(ch)
    return out


def main():
    chunks = []
    for f in sorted(glob.glob(os.path.join(ROOT, 'docs', 'ai_knowledge', '*.md'))):
        chunks += chunks_of(f, 'card')
    for f in sorted(glob.glob(os.path.join(ROOT, 'tutorials', '[0-9]*.md'))):
        chunks += chunks_of(f, 'tutorial')
    payload = json.dumps(chunks, ensure_ascii=True, separators=(',', ':'))
    js = '''/* GENERATED by scripts/build_ai_knowledge.py from docs/ai_knowledge/*.md + tutorials/*.md — do not edit by hand. (SPB-AI 2026-09-30) */
(function () {
    'use strict';
    var CHUNKS = %s;
    var STOP = {a:1,an:1,the:1,and:1,or:1,of:1,to:1,in:1,on:1,is:1,it:1,for:1,with:1,i:1,my:1,me:1,do:1,how:1,can:1,what:1,you:1,this:1,that:1,be:1,are:1,so:1,at:1,as:1,make:1,want:1,would:1,like:1,some:1,type:1};
    var SYN = {shiny:'gloss',glossy:'gloss',mirror:'chrome',reflective:'chrome',holo:'holographic',rainbow:'holographic',iridescent:'holographic',prismatic:'holographic',sparkle:'flake',glitter:'flake',metallic:'metal',fade:'gradient',blend:'gradient',transition:'gradient',stripe:'accent',stripes:'accent',trim:'accent',deploy:'export',folder:'export',undo:'undo',wrong:'flat',broken:'flat',hidden:'priority',covered:'priority',order:'priority'};
    function stem(w) { return w.length > 4 ? w.replace(/(ing|ed|es|s)$/, '') : w.replace(/s$/, ''); }
    function toks(s) {
        var out = [], w = String(s || '').toLowerCase().split(/[^a-z0-9]+/);
        for (var i = 0; i < w.length; i++) { if (w[i].length < 2 || STOP[w[i]]) continue; out.push(stem(SYN[w[i]] || w[i])); }
        return out;
    }
    var PREP = CHUNKS.map(function (c) { return { c: c, tt: toks(c.t), bt: toks(c.b) }; });
    // search(query, maxChars): best chunks first, cards ranked above tutorials on ties; returns [{title, text}]
    function search(q, maxChars) {
        var qt = toks(q); if (!qt.length) return [];
        var scored = [];
        PREP.forEach(function (p) {
            var s = 0;
            qt.forEach(function (t) {
                if (p.tt.indexOf(t) !== -1) s += 5;
                var n = 0; for (var i = 0; i < p.bt.length; i++) if (p.bt[i] === t) n++;
                s += Math.min(n, 4);
            });
            if (s > 0) scored.push({ s: s + (p.c.k === 'card' ? 3 : 0) - (p.c.x ? 6 : 0), c: p.c });
        });
        scored.sort(function (a, b) { return b.s - a.s; });
        var out = [], used = 0, limit = maxChars || 3000;
        for (var i = 0; i < scored.length && out.length < 4; i++) {
            var c = scored[i].c;
            if (out.length && used + c.b.length > limit) continue;
            out.push({ title: c.t, text: c.b }); used += c.b.length;
        }
        return out;
    }
    // searchScored(q, maxChars): same ranking as search(), but every hit carries its score and how many DISTINCT query words it matched (2026-10-02: the support helper only answers when the match is real)
    function searchScored(q, maxChars) {
        var qt = toks(q); if (!qt.length) return { nq: 0, hits: [] };
        var uq = qt.filter(function (t, i) { return qt.indexOf(t) === i; }), scored = [];
        PREP.forEach(function (p) {
            var s = 0, m = 0;
            uq.forEach(function (t) {
                var inT = p.tt.indexOf(t) !== -1, n = 0; if (inT) s += 5;
                for (var i = 0; i < p.bt.length; i++) if (p.bt[i] === t) n++;
                s += Math.min(n, 4); if (inT || n) m++;
            });
            if (s > 0) scored.push({ s: s + (p.c.k === 'card' ? 3 : 0) - (p.c.x ? 6 : 0), m: m, c: p.c });
        });
        scored.sort(function (a, b) { return b.s - a.s; });
        var out = [], used = 0, limit = maxChars || 3000;
        for (var i = 0; i < scored.length && out.length < 4; i++) {
            var c = scored[i].c;
            if (out.length && used + c.b.length > limit) continue;
            out.push({ title: c.t, text: c.b, score: scored[i].s, matched: scored[i].m }); used += c.b.length;
        }
        return { nq: uq.length, hits: out };
    }
    window.SpbAIKnowledge = { search: search, searchScored: searchScored, count: CHUNKS.length, titles: function () { return CHUNKS.map(function (c) { return c.t; }); } };
})();
''' % payload
    dst = os.path.join(ROOT, 'js', 'spb-ai-knowledge.js')
    tmp = dst + '.tmp'
    with open(tmp, 'w', encoding='utf-8', newline='\n') as fh:
        fh.write(js)
    os.replace(tmp, dst)
    print('chunks:', len(chunks), 'bytes:', os.path.getsize(dst))


if __name__ == '__main__':
    sys.exit(main())
