"""Rate portal definitions — living queue review lanes for finish categories."""
from __future__ import annotations

PORTALS: dict[str, dict] = {
    "light_optics": {
        "title": "Fusion Lab — Light & Optics",
        "group_name": "Light & Optics",
        "registry": "monolithic",
        "html": "SPB_RATE_LIGHT_OPTICS.html",
        "rate_json": "SPB_RATE_LIGHT_OPTICS.json",
        "thumb_dir": "_rate_light_optics_thumbs",
        "loop_state": "light_optics_loop_state.json",
        "failure_reasons": [
            "Reads flat / weak — no optical punch at 2048²",
            "Macro waves or bands (violates 8–32 px fine-detail rule)",
            "Spec channels too flat (M/R/CC indistinguishable)",
            "Not enough spec coloring / shades in the spec map",
            "Sparkle/halo/spectral effect weak or absent",
            "Wrong light behavior for name (wave vs halo vs spectral)",
            "Same as sibling in group (clone)",
            "Boring / lazy finish — no character",
            "Performance too slow (>3 s at 2048²)",
        ],
    },
    "prizm": {
        "title": "Color Science — Prizm",
        "group_name": "Prizm",
        "registry": "monolithic",
        "html": "SPB_RATE_PRIZM.html",
        "rate_json": "SPB_RATE_PRIZM.json",
        "thumb_dir": "_rate_prizm_thumbs",
        "loop_state": "prizm_loop_state.json",
        "failure_reasons": [
            "Color shift too weak — doesn't read as Prizm",
            "Macro bands / wallpaper (violates fine-detail rule)",
            "Spec channels too flat",
            "Not enough distinct spec shades",
            "Doesn't match its name identity",
            "Clone of another Prizm in group",
            "Boring / lazy finish",
            "Performance too slow (>3 s at 2048²)",
        ],
    },
    "chameleon": {
        "title": "Color Science — Chameleon",
        "group_name": "Chameleon",
        "registry": "monolithic",
        "html": "SPB_RATE_CHAMELEON.html",
        "rate_json": "SPB_RATE_CHAMELEON.json",
        "thumb_dir": "_rate_chameleon_thumbs",
        "loop_state": "chameleon_loop_state.json",
        "failure_reasons": [
            "Hue walk too weak — not enough flip",
            "Wrong color family for name",
            "Macro stripes / panel bands",
            "Spec too flat — no angle-dependent read",
            "Not enough spec coloring",
            "Reads plastic not flip-paint",
            "Clone sibling",
            "Boring / lazy",
            "Performance too slow",
        ],
    },
    "colorshoxx": {
        "title": "SHOKKER — COLORSHOXX",
        "group_name": "★ COLORSHOXX",
        "registry": "base",
        "html": "SPB_RATE_COLORSHOXX.html",
        "rate_json": "SPB_RATE_COLORSHOXX.json",
        "thumb_dir": "_rate_colorshoxx_thumbs",
        "loop_state": "colorshoxx_loop_state.json",
        "failure_reasons": [
            "Colors don't match catalog description / name",
            "Dual/tri/quad zones don't read at car scale",
            "Weak flip — doesn't sell the COLORSHOXX promise",
            "Macro features too big for 2048² car",
            "Spec channels flat or muddy",
            "Not enough distinct spec shades",
            "Same as another COLORSHOXX (clone)",
            "Boring / safe — not experimental enough",
            "Performance too slow (>3 s at 2048²)",
        ],
    },
    "forbidden_dragon": {
        "title": "Cultural — FORBIDDEN DRAGON",
        "group_name": "FORBIDDEN DRAGON",
        "registry": "monolithic",
        "html": "SPB_RATE_FORBIDDEN_DRAGON.html",
        "rate_json": "SPB_RATE_FORBIDDEN_DRAGON.json",
        "thumb_dir": "_rate_forbidden_dragon_thumbs",
        "loop_state": "forbidden_dragon_loop_state.json",
        "bakeoff_mode": True,
        "failure_reasons": [
            "Reads flat on car — pattern too small/large for the body UV",
            "Spec doesn't trace the art (gold not metal, no scale/flame relief)",
            "Spec channels flat (M/R/CC don't fight — no shimmer)",
            "Not enough spec coloring / shades (looks one-material)",
            "Color story muddy / doesn't match the dragon name",
            "Fire/pearl/scales don't 'breathe' under angle",
            "Too sparse — large flat areas, not edge-to-edge dense",
            "Clone of another dragon in the set",
            "Performance too slow (>3 s at 2048²)",
        ],
    },
    "money_shokk": {
        "title": "SHOKKER — MONEY SHOKK Bake-Off",
        "group_name": "★ MONEY SHOKK",
        "registry": "base",
        "html": "SPB_RATE_MONEY_SHOKK.html",
        "rate_json": "SPB_RATE_MONEY_SHOKK.json",
        "thumb_dir": "_rate_money_shokk_thumbs",
        "loop_state": "money_shokk_loop_state.json",
        "bakeoff_mode": True,
        "failure_reasons": [
            "No real color change — only brightness shift, same hue",
            "Second color weak — doesn't pop on hood/curves at car scale",
            "Thumbnail looks good but won't flip in iRacing (spec-gated fail)",
            "Base color dead / gray — no chroma energy for reveal",
            "Spec overlay too coarse — panel-scale blobs not micro-gates",
            "Spec channels flat (M/R/CC don't fight each other)",
            "Predicted A→B colors don't match description",
            "Clone of another entry in the bake-off",
            "Too similar to Canary Coffin accident (no new recipe)",
            "Performance too slow (>3 s at 2048²)",
        ],
    },
}

# Overnight worker processes portals in this order, then loops.
OVERNIGHT_PORTAL_ORDER = ["light_optics", "prizm", "chameleon", "colorshoxx"]
