"""Make the current ASTRA app review point at R1, retaining old review bytes."""
from pathlib import Path
import json,shutil
from PIL import Image
ROOT=Path(__file__).resolve().parents[1];OUT=ROOT/'_astra_rebuild_20260922_work'


def main():
    rows=json.loads((OUT/'inventory.json').read_text());native=json.loads((OUT/'native_report.json').read_text())
    for r in rows:
        fid=r['FID'];r['lane']=native[fid]['lane'];r['seconds']=native[fid]['seconds']
        r['contract']=json.loads((OUT/fid/'identity_contract.json').read_text())
        for kind in ['paint','spec']:
            with Image.open(OUT/fid/(kind+'.png')) as im:im.resize((256,256),Image.Resampling.BOX).save(OUT/fid/(kind+'_256.png'))
    template='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>ASTRA R1 — 50 rebuilt finishes</title><style>
*{box-sizing:border-box}body{margin:0;background:#10151d;color:#e7edf4;font:15px system-ui}header{padding:26px max(22px,4vw);border-bottom:1px solid #334053;background:#17202c}h1{margin:0 0 10px;font-size:30px}p{max-width:1050px;line-height:1.6;color:#b9c8d6}a{color:#91cbea}nav{display:flex;flex-wrap:wrap;gap:8px;margin:20px 0 12px}button,input,select{background:#223244;border:1px solid #4b6074;color:#eef5fc;padding:10px 13px;border-radius:6px;font:inherit}button{cursor:pointer}button.active{background:#446476}input{width:270px}main{padding:22px 4vw;display:grid;grid-template-columns:repeat(auto-fill,minmax(260px,1fr));gap:20px}.card{background:#1b2531;border:1px solid #344557;border-radius:8px;overflow:hidden}.card h2{font-size:18px;margin:15px 14px 5px}.lane{color:#9cafc1;margin:0 14px 12px;font-size:12px;letter-spacing:.08em}.pair{display:grid;grid-template-columns:1fr 1fr;gap:2px}.pair img{width:100%;display:block;cursor:zoom-in}.labels{display:flex;justify-content:space-around;font-size:12px;padding:7px;color:#a7bbc9}.before{width:100%;display:block}.details{padding:0 14px 14px;font-size:13px;line-height:1.45;color:#adbfcd}summary{cursor:pointer;padding:10px 0}.details button{width:100%;margin:10px 0 0}dialog{width:min(1400px,96vw);height:94vh;background:#111923;color:white;border:1px solid #5b7285;padding:15px}dialog::backdrop{background:#000b}.toolbar{display:flex;gap:10px;align-items:center;flex-wrap:wrap}.viewport{overflow:auto;height:calc(100% - 65px);margin-top:12px;text-align:center}.viewport img.fit{max-width:100%;max-height:100%;object-fit:contain}.viewport img.native{max-width:none;width:2048px}.notice{padding:6px 10px;border-left:3px solid #76bac7}small{color:#a6bac7}</style>
<header><h1>ASTRA R1 · the entire library rebuilt</h1><p>50 new constructions and feature-specific materials, kept under the original finish IDs. Compare the previous app picker with the rebuilt paint and physical spec maps. Open a finish to inspect the full texture or actual 1:1 detail.</p><p class="notice">Installed for owner iteration. These are actual authored maps, not a simulated car-lighting preview. Legacy M7 is diagnostic; on-car appearance and owner verdict remain the next review.</p><nav id="lanes"></nav><input id="search" placeholder="Find a finish or feature…" aria-label="Search finishes"> <span id="count"></span> · <a href="paint-booth-v2.html">Open Paint Booth</a></header><main id="grid"></main>
<dialog id="viewer"><div class="toolbar"><b id="title"></b><button id="paint">Paint</button><button id="spec">Physical spec</button><button id="scale">Show 1:1 pixels</button><button id="close">Close</button></div><div class="viewport"><img id="large" class="fit" alt="Full native finish"></div></dialog>
<script>const rows=__DATA__;const root='_astra_rebuild_20260922_work/';let lane='All',current=null,kind='paint',native=false;const $=id=>document.getElementById(id);const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function draw(){const q=$('search').value.toLowerCase();const selected=rows.filter(r=>(lane==='All'||r.lane===lane)&&(r.NAME+' '+r.contract.carrier_grammar+' '+r.contract.mark_types.map(m=>m.name).join(' ')).toLowerCase().includes(q));$('count').textContent=selected.length+' / 50 finishes';$('grid').innerHTML=selected.map(r=>`<article class="card"><h2>${esc(r.NAME)}</h2><div class="lane">${esc(r.lane)}</div><div class="pair"><img loading="lazy" src="${root+r.FID}/paint_256.png" alt="${esc(r.NAME)} rebuilt paint" data-id="${r.FID}" data-kind="paint"><img loading="lazy" src="${root+r.FID}/spec_256.png" alt="${esc(r.NAME)} rebuilt physical spec" data-id="${r.FID}" data-kind="spec"></div><div class="labels"><span>REBUILT PAINT</span><span>M · ROUGH · CC</span></div><div class="details"><details><summary>Previous app picker</summary><img class="before" loading="lazy" src="docs/finish_audits/intent_2026-09-22/live_base_pairs/${r.FID}.png" alt="Previous paint and spec picker"></details><details><summary>Construction and material roles</summary>${esc(r.contract.carrier_grammar)}<p>${esc(r.contract.mark_types.map(m=>m.name.replaceAll('_',' ')).join(' · '))}</p><small>Native generation: ${r.seconds}s. Owner verdict pending.</small></details><button data-id="${r.FID}" data-kind="paint">Inspect native detail</button></div></article>`).join('');document.querySelectorAll('[data-id]').forEach(el=>el.onclick=()=>open(el.dataset.id,el.dataset.kind));}
function update(){ $('title').textContent=current.NAME;$('large').src=root+current.FID+'/'+kind+'.png';$('large').className=native?'native':'fit';$('scale').textContent=native?'Fit whole texture':'Show 1:1 pixels';}
function open(id,k){current=rows.find(r=>r.FID===id);kind=k;native=false;update();$('viewer').showModal();}
['All',...new Set(rows.map(r=>r.lane))].forEach(l=>{const b=document.createElement('button');b.textContent=l;b.className=l===lane?'active':'';b.onclick=()=>{lane=l;document.querySelectorAll('#lanes button').forEach(x=>x.classList.toggle('active',x===b));draw()};$('lanes').append(b)});$('search').oninput=draw;$('paint').onclick=()=>{kind='paint';update()};$('spec').onclick=()=>{kind='spec';update()};$('scale').onclick=()=>{native=!native;update()};$('close').onclick=()=>$('viewer').close();draw();</script></html>'''
    page=ROOT/'SPB_AUDIT_astra.html';before=OUT/'before/SPB_AUDIT_astra.html'
    if page.exists() and not before.exists():shutil.copy2(page,before)
    page.write_text(template.replace('__DATA__',json.dumps(rows).replace('</','<\\/')),encoding='utf-8')
    shutil.copy2(page,ROOT/'electron-app/server/SPB_AUDIT_astra.html')
    print('Current ASTRA review: 50 rebuilt cards, old picker comparisons, native paint/spec viewer')


if __name__=='__main__':main()
