#!/usr/bin/env node

const fs = require('fs');
const path = require('path');
const { countFileLines } = require('./spb_line_count');

// [2026-09-05 owner: "Raise ceiling. fix everything."] Five ceilings raised to current size + ~5 % for the
// 10.0.1 beta (canvas 25400->37200, state-zones 19200->21700, easy-mode 6500->7000, engine_v2 19400->24750,
// v2.css 11850->14350, ui-modernization-20260509 2900->3230, -20260510 1900->2000, ui-fixes-20260511 700->785, plus look-live-polish.css 320->340, zone-overlay-spec-fix.css 140->200, spec_patterns.py 15100->38860, base-material-controls.js 300->320, zone-config-zone-map-controls.js 475->520, swatch-popup-open-controls.js 125->150, server.py 9200->14680, finish_catalog_routes.py 260->280, psd_import_routes.py 260->280, psd_import_tree.py 150->180, render_file_routes.py 220->380, file_picker_routes.py 210->620, paint_upload_routes.py 235->300, server_bootstrap.py 190->230, swatch_routes.py 450->770, compose.py 5600->7200, mechanical.py 380->1160, weather_track.py 380->980, artistic.py 520->940, abstract_art.py 1400->2910). They were exceeded by growth that predates this gate; targets are unchanged and
// remain the refactor goals. Any further growth past these numbers fails the release again on purpose.
// [2026-09-09 10.0.2 hotfix] pattern-transform-controls.js ceiling 340->380 (file grew 18 lines with the hotfixes; owner's 09-05 raise-ceilings directive).
const budgets = [
  { file: 'paint-booth-3-canvas.js', target: 12000, ceiling: 37200, owner: 'canvas/tools' },
  { file: 'paint-booth-2-state-zones.js', target: 12000, ceiling: 21700, owner: 'zones/ui' },
  { file: 'js/spb-easy-mode.js', target: 4200, ceiling: 7000, owner: 'easy-mode' },
  { file: 'js/features/spb-projects.js', target: 900, ceiling: 1100, owner: 'projects' },
  { file: 'js/canvas/layer/psd-import-safety.js', target: 180, ceiling: 240, owner: 'layers/import' },
  { file: 'js/canvas/layer/clipping-mask.js', target: 250, ceiling: 340, owner: 'layers/compositor' },
  { file: 'shokker_engine_v2.py', target: 12000, ceiling: 24750, owner: 'engine/orchestration' },
  { file: 'paint-booth-v2.css', target: 10000, ceiling: 14350, owner: 'css/ui' },
  { file: 'css/look-theme-prelude.css', target: 1100, ceiling: 1200, owner: 'css/look-theme' },
  { file: 'css/ui-modernization-20260508.css', target: 2300, ceiling: 2400, owner: 'css/ui-modernization' },
  { file: 'css/ui-modernization-20260509.css', target: 2800, ceiling: 3230, owner: 'css/ui-modernization' },
  { file: 'css/ui-modernization-20260510-early.css', target: 750, ceiling: 850, owner: 'css/ui-modernization' },
  { file: 'css/ui-modernization-20260510.css', target: 1800, ceiling: 2000, owner: 'css/ui-modernization' },
  { file: 'css/ui-fixes-20260511.css', target: 600, ceiling: 785, owner: 'css/ui-fixes' },
  { file: 'css/ui-fixes-20260512-13.css', target: 300, ceiling: 400, owner: 'css/ui-fixes' },
  { file: 'css/look-theme-cycle-11-15.css', target: 700, ceiling: 850, owner: 'css/look-theme' },
  { file: 'css/look-overdrive-base.css', target: 500, ceiling: 700, owner: 'css/look-overdrive' },
  { file: 'css/look-overdrive.css', target: 900, ceiling: 1200, owner: 'css/look-overdrive' },
  { file: 'css/look-live-polish.css', target: 220, ceiling: 340, owner: 'css/look-polish' },
  { file: 'css/look-ux-polish-2.css', target: 180, ceiling: 260, owner: 'css/look-polish' },
  { file: 'css/zone-overlay-spec-fix.css', target: 90, ceiling: 200, owner: 'css/zone-ui' },
  { file: 'paint-booth-0-catalog-scorecard.js', target: 8000, ceiling: 39325, owner: 'generated/catalog' },
  { file: 'engine/spec_patterns.py', target: 8000, ceiling: 38860, owner: 'spec/patterns' },
  { file: 'js/zones/base-material-controls.js', target: 270, ceiling: 320, owner: 'zones/ui' },
  { file: 'js/zones/zone-base-color-controls.js', target: 330, ceiling: 380, owner: 'zones/ui' },
  { file: 'js/zones/zone-base-overlay-state-controls.js', target: 165, ceiling: 205, owner: 'zones/ui' },
  { file: 'js/zones/zone-material-assignment-controls.js', target: 170, ceiling: 220, owner: 'zones/ui' },
  { file: 'js/zones/base-overlay-controls.js', target: 560, ceiling: 620, owner: 'zones/ui' },
  { file: 'js/zones/zone-base-overlay-hsb-controls.js', target: 95, ceiling: 125, owner: 'zones/ui' },
  { file: 'js/zones/zone-placement-controls.js', target: 430, ceiling: 500, owner: 'zones/ui' },
  { file: 'js/zones/zone-intensity-controls.js', target: 230, ceiling: 280, owner: 'zones/ui' },
  { file: 'js/zones/legacy-zone-controls.js', target: 90, ceiling: 120, owner: 'zones/ui' },
  { file: 'js/zones/pattern-transform-controls.js', target: 300, ceiling: 380, owner: 'zones/ui' },
  { file: 'js/zones/spec-map-controls.js', target: 210, ceiling: 250, owner: 'zones/ui' },
  { file: 'js/zones/productivity-controls.js', target: 520, ceiling: 580, owner: 'zones/ui' },
  { file: 'js/zones/diagnostic-workflow-controls.js', target: 220, ceiling: 260, owner: 'zones/ui' },
  { file: 'js/zones/workflow-controls.js', target: 520, ceiling: 580, owner: 'zones/ui' },
  { file: 'js/zones/advanced-workflow-controls.js', target: 320, ceiling: 380, owner: 'zones/ui' },
  { file: 'js/zones/catalog-workflow-controls.js', target: 410, ceiling: 460, owner: 'zones/ui' },
  { file: 'js/zones/export-script-controls.js', target: 150, ceiling: 190, owner: 'zones/ui' },
  { file: 'js/zones/strength-map-controls.js', target: 220, ceiling: 260, owner: 'zones/ui' },
  { file: 'js/zones/fine-tuning-controls.js', target: 190, ceiling: 230, owner: 'zones/ui' },
  { file: 'js/zones/finish-dna-controls.js', target: 390, ceiling: 430, owner: 'zones/ui' },
  { file: 'js/zones/finish-mixer-controls.js', target: 610, ceiling: 660, owner: 'zones/ui' },
  { file: 'js/zones/zone-data-repair-controls.js', target: 170, ceiling: 210, owner: 'zones/ui' },
  { file: 'js/zones/zone-keyboard-controls.js', target: 90, ceiling: 120, owner: 'zones/ui' },
  { file: 'js/zones/zone-undo-history-controls.js', target: 240, ceiling: 280, owner: 'zones/ui' },
  { file: 'js/zones/zone-detail-polish-controls.js', target: 280, ceiling: 330, owner: 'zones/ui' },
  { file: 'js/zones/zone-quick-view-source-controls.js', target: 170, ceiling: 210, owner: 'zones/ui' },
  { file: 'js/zones/zone-list-action-controls.js', target: 300, ceiling: 340, owner: 'zones/ui' },
  { file: 'js/zones/zone-default-restore-controls.js', target: 95, ceiling: 130, owner: 'zones/ui' },
  { file: 'js/zones/zone-swatch-identity-controls.js', target: 80, ceiling: 110, owner: 'zones/ui' },
  { file: 'js/zones/zone-create-duplicate-controls.js', target: 330, ceiling: 380, owner: 'zones/ui' },
  { file: 'js/zones/zone-card-render-controls.js', target: 240, ceiling: 280, owner: 'zones/ui' },
  { file: 'js/zones/zone-multi-color-controls.js', target: 220, ceiling: 260, owner: 'zones/ui' },
  { file: 'js/zones/zone-link-controls.js', target: 130, ceiling: 165, owner: 'zones/ui' },
  { file: 'js/zones/zone-thumbnail-controls.js', target: 75, ceiling: 110, owner: 'zones/ui' },
  { file: 'js/zones/zone-ui-mode-controls.js', target: 100, ceiling: 140, owner: 'zones/ui' },
  { file: 'js/zones/zone-overlay-special-picker-controls.js', target: 60, ceiling: 90, owner: 'zones/ui' },
  { file: 'js/zones/zone-render-chrome-controls.js', target: 70, ceiling: 100, owner: 'zones/ui' },
  { file: 'js/zones/zone-state-shape-controls.js', target: 170, ceiling: 210, owner: 'zones/ui' },
  { file: 'js/zones/zone-toast-notification-controls.js', target: 160, ceiling: 210, owner: 'zones/ui' },
  { file: 'js/zones/zone-finish-assignment-controls.js', target: 230, ceiling: 280, owner: 'zones/ui' },
  { file: 'js/zones/zone-autosave-controls.js', target: 120, ceiling: 170, owner: 'zones/ui' },
  { file: 'js/zones/zone-config-zone-map-controls.js', target: 430, ceiling: 520, owner: 'zones/ui' },
  { file: 'js/zones/zone-config-dom-controls.js', target: 150, ceiling: 190, owner: 'zones/ui' },
  { file: 'js/zones/zone-config-preset-controls.js', target: 330, ceiling: 390, owner: 'zones/ui' },
  { file: 'js/zones/zone-preset-gallery-controls.js', target: 120, ceiling: 165, owner: 'zones/ui' },
  { file: 'js/zones/zone-auto-restore-controls.js', target: 210, ceiling: 260, owner: 'zones/ui' },
  { file: 'js/zones/preview-controls.js', target: 330, ceiling: 380, owner: 'zones/ui' },
  { file: 'js/zones/source-color-apply-controls.js', target: 480, ceiling: 540, owner: 'zones/ui' },
  { file: 'js/zones/finish-library-enhancement-controls.js', target: 360, ceiling: 400, owner: 'zones/ui' },
  { file: 'js/zones/finish-library-state-controls.js', target: 220, ceiling: 260, owner: 'zones/ui' },
  { file: 'js/zones/finish-library-search-controls.js', target: 115, ceiling: 145, owner: 'zones/ui' },
  { file: 'js/zones/finish-library-guided-catalog-controls.js', target: 210, ceiling: 250, owner: 'zones/ui' },
  { file: 'js/zones/finish-library-render-flow-controls.js', target: 125, ceiling: 155, owner: 'zones/ui' },
  { file: 'js/zones/finish-library-panel-controls.js', target: 230, ceiling: 270, owner: 'zones/ui' },
  { file: 'js/zones/finish-library-render-item-controls.js', target: 190, ceiling: 230, owner: 'zones/ui' },
  { file: 'js/zones/finish-library-filter-controls.js', target: 165, ceiling: 210, owner: 'zones/ui' },
  { file: 'js/zones/finish-library-shell-controls.js', target: 210, ceiling: 250, owner: 'zones/ui' },
  { file: 'js/zones/swatch-popup-render-controls.js', target: 220, ceiling: 260, owner: 'zones/ui' },
  { file: 'js/zones/swatch-popup-ranking-controls.js', target: 560, ceiling: 620, owner: 'zones/ui' },
  { file: 'js/zones/swatch-popup-review-controls.js', target: 360, ceiling: 430, owner: 'zones/ui' },
  { file: 'js/zones/swatch-popup-category-strategy-controls.js', target: 400, ceiling: 460, owner: 'zones/ui' },
  { file: 'js/zones/swatch-popup-action-controls.js', target: 220, ceiling: 270, owner: 'zones/ui' },
  { file: 'js/zones/swatch-popup-preview-controls.js', target: 220, ceiling: 260, owner: 'zones/ui' },
  { file: 'js/zones/swatch-popup-lane-controls.js', target: 140, ceiling: 175, owner: 'zones/ui' },
  { file: 'js/zones/swatch-popup-health-controls.js', target: 125, ceiling: 160, owner: 'zones/ui' },
  { file: 'js/zones/swatch-popup-status-controls.js', target: 220, ceiling: 260, owner: 'zones/ui' },
  { file: 'js/zones/swatch-popup-group-controls.js', target: 95, ceiling: 130, owner: 'zones/ui' },
  { file: 'js/zones/swatch-popup-selection-controls.js', target: 100, ceiling: 135, owner: 'zones/ui' },
  { file: 'js/zones/swatch-popup-current-selection-controls.js', target: 80, ceiling: 110, owner: 'zones/ui' },
  { file: 'js/zones/swatch-popup-grid-builder-controls.js', target: 245, ceiling: 285, owner: 'zones/ui' },
  { file: 'js/zones/swatch-popup-open-controls.js', target: 105, ceiling: 150, owner: 'zones/ui' },
  { file: 'js/zones/swatch-popup-lifecycle-controls.js', target: 95, ceiling: 125, owner: 'zones/ui' },
  { file: 'js/zones/swatch-popup-filter-controls.js', target: 175, ceiling: 210, owner: 'zones/ui' },
  { file: 'server.py', target: 8000, ceiling: 14680, owner: 'server/routes' },
  { file: 'server_routes/asset_routes.py', target: 50, ceiling: 80, owner: 'server/routes' },
  { file: 'server_routes/finish_catalog_routes.py', target: 220, ceiling: 280, owner: 'server/routes' },
  { file: 'server_routes/finish_lookup_routes.py', target: 60, ceiling: 90, owner: 'server/routes' },
  { file: 'server_routes/license_routes.py', target: 80, ceiling: 120, owner: 'server/routes' },
  { file: 'server_routes/default_asset_routes.py', target: 90, ceiling: 120, owner: 'server/routes' },
  { file: 'server_routes/photoshop_export_routes.py', target: 300, ceiling: 340, owner: 'server/routes' },
  { file: 'server_routes/photoshop_import_routes.py', target: 170, ceiling: 220, owner: 'server/routes' },
  { file: 'server_routes/spec_channel_export_routes.py', target: 170, ceiling: 210, owner: 'server/routes' },
  { file: 'server_routes/psd_layer_export_routes.py', target: 360, ceiling: 420, owner: 'server/routes' },
  { file: 'server_routes/psd_import_routes.py', target: 220, ceiling: 280, owner: 'server/routes' },
  { file: 'server_routes/psd_import_tree.py', target: 110, ceiling: 180, owner: 'server/routes' },
  { file: 'server_routes/dual_shift_routes.py', target: 170, ceiling: 210, owner: 'server/routes' },
  { file: 'server_routes/legacy_apply_finish_routes.py', target: 70, ceiling: 95, owner: 'server/routes' },
  { file: 'server_routes/paint_recolor_support.py', target: 100, ceiling: 130, owner: 'server/routes' },
  { file: 'server_routes/render_file_routes.py', target: 170, ceiling: 380, owner: 'server/routes' },
  { file: 'server_routes/file_picker_routes.py', target: 160, ceiling: 620, owner: 'server/routes' },
  { file: 'server_routes/paint_upload_routes.py', target: 200, ceiling: 300, owner: 'server/routes' },
  { file: 'server_routes/iracing_utility_routes.py', target: 190, ceiling: 215, owner: 'server/routes' },
  { file: 'server_routes/validation_routes.py', target: 120, ceiling: 160, owner: 'server/routes' },
  { file: 'server_routes/pattern_layer_routes.py', target: 105, ceiling: 125, owner: 'server/routes' },
  { file: 'server_routes/cache_admin_routes.py', target: 170, ceiling: 215, owner: 'server/routes' },
  { file: 'server_routes/swatch_review_routes.py', target: 80, ceiling: 110, owner: 'server/routes' },
  { file: 'server_routes/job_cleanup.py', target: 120, ceiling: 140, owner: 'server/routes' },
  { file: 'server_routes/server_bootstrap.py', target: 160, ceiling: 230, owner: 'server/bootstrap' },
  { file: 'server_routes/spec_result_support.py', target: 115, ceiling: 140, owner: 'server/support' },
  { file: 'server_routes/swatch_routes.py', target: 400, ceiling: 770, owner: 'server/routes' },
  { file: 'server_routes/observability.py', target: 390, ceiling: 400, owner: 'server/security' },
  { file: 'server_routes/v5_entrypoint_security.py', target: 160, ceiling: 220, owner: 'server/security' },
  { file: 'server_routes/runtime_identity.py', target: 130, ceiling: 170, owner: 'server/security' },
  { file: 'server_routes/request_security.py', target: 70, ceiling: 100, owner: 'server/security' },
  { file: 'server_routes/write_security.py', target: 50, ceiling: 75, owner: 'server/security' },
  { file: 'server_routes/shokk_routes.py', target: 360, ceiling: 390, owner: 'server/routes' },
  { file: 'server_routes/custom_finish_routes.py', target: 110, ceiling: 130, owner: 'server/routes' },
  { file: 'server_routes/custom_finish_mixer_routes.py', target: 195, ceiling: 230, owner: 'server/routes' },
  { file: 'server_routes/finish_viewer_render_routes.py', target: 280, ceiling: 330, owner: 'server/routes' },
  { file: 'server_routes/finish_viewer_recent_routes.py', target: 175, ceiling: 220, owner: 'server/routes' },
  { file: 'scripts/spb_smoke_server_routes.py', target: 185, ceiling: 250, owner: 'server/tests' },
  { file: 'scripts/spb_probe_catalog_drift.py', target: 75, ceiling: 90, owner: 'tooling/usage' },
  { file: 'scripts/spb_watch_catalog_files.py', target: 95, ceiling: 110, owner: 'tooling/usage' },
  { file: 'scripts/spb_line_count.js', target: 15, ceiling: 25, owner: 'tooling/usage' },
  { file: 'scripts/spb_guard_line_count.js', target: 25, ceiling: 40, owner: 'tooling/usage' },
  { file: 'scripts/spb_scorecard_drift_summary.py', target: 80, ceiling: 100, owner: 'tooling/usage' },
  { file: 'scripts/spb_release_gate_status.js', target: 45, ceiling: 60, owner: 'tooling/usage' },
  { file: 'scripts/spb_generated_drift_guard.js', target: 75, ceiling: 90, owner: 'tooling/usage' },
  { file: 'scripts/spb_guard_spec_controls.js', target: 45, ceiling: 70, owner: 'tooling/release-guards' },
  { file: 'scripts/spb_guard_base_color_scale.js', target: 95, ceiling: 110, owner: 'tooling/release-guards' },
  { file: 'scripts/spb_guard_server_cache_admin_routes.js', target: 85, ceiling: 115, owner: 'tooling/release-guards' },
  { file: 'scripts/spb_guard_server_swatch_review_routes.js', target: 70, ceiling: 95, owner: 'tooling/release-guards' },
  { file: 'scripts/spb_guard_server_swatch_routes.js', target: 60, ceiling: 85, owner: 'tooling/release-guards' },
  { file: 'scripts/spb_guard_server_photoshop_export_routes.js', target: 75, ceiling: 95, owner: 'tooling/release-guards' },
  { file: 'scripts/spb_guard_server_spec_channel_export_routes.js', target: 70, ceiling: 95, owner: 'tooling/release-guards' },
  { file: 'scripts/spb_guard_server_psd_layer_export_routes.js', target: 75, ceiling: 105, owner: 'tooling/release-guards' },
  { file: 'scripts/spb_guard_server_job_cleanup.js', target: 60, ceiling: 65, owner: 'tooling/release-guards' },
  { file: 'scripts/spb_guard_server_bootstrap.js', target: 45, ceiling: 70, owner: 'tooling/release-guards' },
  { file: 'scripts/spb_guard_server_spec_result_support.js', target: 45, ceiling: 65, owner: 'tooling/release-guards' },
  { file: 'scripts/spb_guard_server_shokk_routes.js', target: 85, ceiling: 115, owner: 'tooling/release-guards' },
  { file: 'scripts/spb_guard_server_custom_finish_routes.js', target: 95, ceiling: 125, owner: 'tooling/release-guards' },
  { file: 'scripts/spb_guard_server_finish_viewer_recent_routes.js', target: 90, ceiling: 120, owner: 'tooling/release-guards' },
  { file: 'scripts/spb_guard_server_iracing_utility_routes.js', target: 80, ceiling: 105, owner: 'tooling/release-guards' },
  { file: 'scripts/spb_guard_server_psd_import_routes.js', target: 80, ceiling: 110, owner: 'tooling/release-guards' },
  { file: 'scripts/spb_guard_server_dual_shift_routes.js', target: 70, ceiling: 100, owner: 'tooling/release-guards' },
  { file: 'scripts/spb_guard_server_legacy_apply_finish_routes.js', target: 70, ceiling: 100, owner: 'tooling/release-guards' },
  { file: 'scripts/spb_guard_server_paint_recolor_support.js', target: 70, ceiling: 105, owner: 'tooling/release-guards' },
  { file: 'scripts/spb_guard_server_paint_upload_routes.js', target: 70, ceiling: 105, owner: 'tooling/release-guards' },
  { file: 'scripts/spb_guard_server_pattern_layer_routes.js', target: 60, ceiling: 90, owner: 'tooling/release-guards' },
  { file: 'scripts/spb_guard_server_finish_viewer_render_routes.js', target: 70, ceiling: 110, owner: 'tooling/release-guards' },
  { file: 'scripts/spb_guard_zone_base_overlay.js', target: 95, ceiling: 110, owner: 'tooling/release-guards' },
  { file: 'scripts/spb_guard_zone_base_overlay_state_controls.js', target: 75, ceiling: 100, owner: 'tooling/release-guards' },
  { file: 'scripts/spb_guard_zone_material_assignment_controls.js', target: 80, ceiling: 110, owner: 'tooling/release-guards' },
  { file: 'scripts/spb_guard_zone_placement_controls.js', target: 105, ceiling: 135, owner: 'tooling/release-guards' },
  { file: 'scripts/spb_guard_zone_intensity_controls.js', target: 95, ceiling: 125, owner: 'tooling/release-guards' },
  { file: 'scripts/spb_guard_zone_legacy_controls.js', target: 45, ceiling: 70, owner: 'tooling/release-guards' },
  { file: 'scripts/spb_guard_zone_pattern_transform.js', target: 55, ceiling: 80, owner: 'tooling/release-guards' },
  { file: 'scripts/spb_guard_zone_spec_map_controls.js', target: 55, ceiling: 80, owner: 'tooling/release-guards' },
  { file: 'scripts/spb_guard_zone_productivity_controls.js', target: 75, ceiling: 100, owner: 'tooling/release-guards' },
  { file: 'scripts/spb_guard_zone_diagnostic_workflow_controls.js', target: 75, ceiling: 100, owner: 'tooling/release-guards' },
  { file: 'scripts/spb_guard_zone_workflow_controls.js', target: 75, ceiling: 100, owner: 'tooling/release-guards' },
  { file: 'scripts/spb_guard_zone_advanced_workflow_controls.js', target: 75, ceiling: 100, owner: 'tooling/release-guards' },
  { file: 'scripts/spb_guard_zone_catalog_workflow_controls.js', target: 75, ceiling: 100, owner: 'tooling/release-guards' },
  { file: 'scripts/spb_guard_zone_export_script_controls.js', target: 75, ceiling: 100, owner: 'tooling/release-guards' },
  { file: 'scripts/spb_guard_zone_strength_map_controls.js', target: 75, ceiling: 100, owner: 'tooling/release-guards' },
  { file: 'scripts/spb_guard_zone_fine_tuning_controls.js', target: 75, ceiling: 100, owner: 'tooling/release-guards' },
  { file: 'scripts/spb_guard_zone_finish_dna_controls.js', target: 80, ceiling: 105, owner: 'tooling/release-guards' },
  { file: 'scripts/spb_guard_zone_finish_mixer_controls.js', target: 95, ceiling: 120, owner: 'tooling/release-guards' },
  { file: 'scripts/spb_guard_zone_data_repair_controls.js', target: 75, ceiling: 100, owner: 'tooling/release-guards' },
  { file: 'scripts/spb_guard_zone_keyboard_controls.js', target: 70, ceiling: 95, owner: 'tooling/release-guards' },
  { file: 'scripts/spb_guard_zone_undo_history_controls.js', target: 95, ceiling: 125, owner: 'tooling/release-guards' },
  { file: 'scripts/spb_guard_zone_detail_polish_controls.js', target: 110, ceiling: 135, owner: 'tooling/release-guards' },
  { file: 'scripts/spb_guard_zone_quick_view_source_controls.js', target: 90, ceiling: 115, owner: 'tooling/release-guards' },
  { file: 'scripts/spb_guard_zone_list_action_controls.js', target: 100, ceiling: 130, owner: 'tooling/release-guards' },
  { file: 'scripts/spb_guard_zone_default_restore_controls.js', target: 90, ceiling: 120, owner: 'tooling/release-guards' },
  { file: 'scripts/spb_guard_zone_create_duplicate_controls.js', target: 100, ceiling: 130, owner: 'tooling/release-guards' },
  { file: 'scripts/spb_guard_zone_card_render_controls.js', target: 95, ceiling: 125, owner: 'tooling/release-guards' },
  { file: 'scripts/spb_guard_zone_multi_color_controls.js', target: 85, ceiling: 115, owner: 'tooling/release-guards' },
  { file: 'scripts/spb_guard_zone_link_controls.js', target: 90, ceiling: 120, owner: 'tooling/release-guards' },
  { file: 'scripts/spb_guard_zone_thumbnail_controls.js', target: 65, ceiling: 95, owner: 'tooling/release-guards' },
  { file: 'scripts/spb_guard_zone_ui_mode_controls.js', target: 65, ceiling: 95, owner: 'tooling/release-guards' },
  { file: 'scripts/spb_guard_zone_overlay_special_picker_controls.js', target: 65, ceiling: 95, owner: 'tooling/release-guards' },
  { file: 'scripts/spb_guard_zone_render_chrome_controls.js', target: 65, ceiling: 95, owner: 'tooling/release-guards' },
  { file: 'scripts/spb_guard_zone_state_shape_controls.js', target: 70, ceiling: 100, owner: 'tooling/release-guards' },
  { file: 'scripts/spb_guard_zone_toast_notification_controls.js', target: 70, ceiling: 105, owner: 'tooling/release-guards' },
  { file: 'scripts/spb_guard_zone_finish_assignment_controls.js', target: 85, ceiling: 120, owner: 'tooling/release-guards' },
  { file: 'scripts/spb_guard_zone_autosave_controls.js', target: 65, ceiling: 100, owner: 'tooling/release-guards' },
  { file: 'scripts/spb_guard_zone_config_zone_map_controls.js', target: 75, ceiling: 115, owner: 'tooling/release-guards' },
  { file: 'scripts/spb_guard_zone_config_dom_controls.js', target: 75, ceiling: 115, owner: 'tooling/release-guards' },
  { file: 'scripts/spb_guard_zone_config_preset_controls.js', target: 95, ceiling: 125, owner: 'tooling/release-guards' },
  { file: 'scripts/spb_guard_zone_preset_gallery_controls.js', target: 75, ceiling: 115, owner: 'tooling/release-guards' },
  { file: 'scripts/spb_guard_zone_auto_restore_controls.js', target: 90, ceiling: 120, owner: 'tooling/release-guards' },
  { file: 'scripts/spb_guard_zone_preview_controls.js', target: 90, ceiling: 120, owner: 'tooling/release-guards' },
  { file: 'scripts/spb_guard_zone_source_color_apply_controls.js', target: 95, ceiling: 125, owner: 'tooling/release-guards' },
  { file: 'scripts/spb_guard_zone_finish_library_enhancement_controls.js', target: 85, ceiling: 110, owner: 'tooling/release-guards' },
  { file: 'scripts/spb_guard_zone_finish_library_state_controls.js', target: 85, ceiling: 110, owner: 'tooling/release-guards' },
  { file: 'scripts/spb_guard_zone_finish_library_search_controls.js', target: 65, ceiling: 90, owner: 'tooling/release-guards' },
  { file: 'scripts/spb_guard_zone_finish_library_guided_catalog_controls.js', target: 105, ceiling: 135, owner: 'tooling/release-guards' },
  { file: 'scripts/spb_guard_zone_finish_library_render_flow_controls.js', target: 75, ceiling: 100, owner: 'tooling/release-guards' },
  { file: 'scripts/spb_guard_zone_finish_library_panel_controls.js', target: 75, ceiling: 100, owner: 'tooling/release-guards' },
  { file: 'scripts/spb_guard_zone_finish_library_render_item_controls.js', target: 85, ceiling: 110, owner: 'tooling/release-guards' },
  { file: 'scripts/spb_guard_zone_finish_library_filter_controls.js', target: 95, ceiling: 120, owner: 'tooling/release-guards' },
  { file: 'scripts/spb_guard_zone_finish_library_shell_controls.js', target: 85, ceiling: 115, owner: 'tooling/release-guards' },
  { file: 'scripts/spb_guard_zone_finish_library_dead_legacy_prune.js', target: 40, ceiling: 65, owner: 'tooling/release-guards' },
  { file: 'scripts/spb_guard_swatch_popup_render_controls.js', target: 100, ceiling: 120, owner: 'tooling/release-guards' },
  { file: 'scripts/spb_guard_swatch_popup_ranking_controls.js', target: 90, ceiling: 115, owner: 'tooling/release-guards' },
  { file: 'scripts/spb_guard_swatch_popup_review_controls.js', target: 90, ceiling: 115, owner: 'tooling/release-guards' },
  { file: 'scripts/spb_guard_swatch_popup_category_strategy_controls.js', target: 95, ceiling: 120, owner: 'tooling/release-guards' },
  { file: 'scripts/spb_guard_swatch_popup_action_controls.js', target: 90, ceiling: 115, owner: 'tooling/release-guards' },
  { file: 'scripts/spb_guard_swatch_popup_preview_controls.js', target: 95, ceiling: 120, owner: 'tooling/release-guards' },
  { file: 'scripts/spb_guard_swatch_popup_lane_controls.js', target: 80, ceiling: 105, owner: 'tooling/release-guards' },
  { file: 'scripts/spb_guard_swatch_popup_health_controls.js', target: 75, ceiling: 100, owner: 'tooling/release-guards' },
  { file: 'scripts/spb_guard_swatch_popup_status_controls.js', target: 90, ceiling: 115, owner: 'tooling/release-guards' },
  { file: 'scripts/spb_guard_swatch_popup_group_controls.js', target: 75, ceiling: 100, owner: 'tooling/release-guards' },
  { file: 'scripts/spb_guard_swatch_popup_selection_controls.js', target: 95, ceiling: 125, owner: 'tooling/release-guards' },
  { file: 'scripts/spb_guard_swatch_popup_current_selection_controls.js', target: 75, ceiling: 100, owner: 'tooling/release-guards' },
  { file: 'scripts/spb_guard_swatch_popup_grid_builder_controls.js', target: 95, ceiling: 125, owner: 'tooling/release-guards' },
  { file: 'scripts/spb_guard_swatch_popup_open_controls.js', target: 75, ceiling: 100, owner: 'tooling/release-guards' },
  { file: 'scripts/spb_guard_swatch_popup_lifecycle_controls.js', target: 75, ceiling: 100, owner: 'tooling/release-guards' },
  { file: 'scripts/spb_guard_swatch_popup_filter_controls.js', target: 80, ceiling: 105, owner: 'tooling/release-guards' },
  { file: 'scripts/spb_guard_zone_extracted_boot_contract.js', target: 190, ceiling: 210, owner: 'tooling/release-guards' },
  { file: 'scripts/spb_smoke_zone_boot_http.js', target: 105, ceiling: 135, owner: 'tooling/release-guards' },
  { file: 'scripts/spb_context_target_lint.js', target: 60, ceiling: 80, owner: 'tooling/release' },
  { file: 'scripts/spb_current_state.js', target: 140, ceiling: 170, owner: 'tooling/release' },
  { file: 'scripts/spb_easy_featured_audit.js', target: 120, ceiling: 150, owner: 'tooling/release' },
  { file: 'scripts/spb_release_preflight.js', target: 50, ceiling: 70, owner: 'tooling/release' },
  { file: 'scripts/spb_release_fixture_audit.py', target: 75, ceiling: 100, owner: 'tooling/release' },
  { file: 'scripts/spb_isolated_verify.js', target: 340, ceiling: 400, owner: 'tooling/release' },
  { file: 'scripts/spb_run_isolated_server.py', target: 40, ceiling: 60, owner: 'tooling/release' },
  { file: 'scripts/spb_runtime_identity.js', target: 55, ceiling: 75, owner: 'tooling/release' },
  { file: 'scripts/spb_release_evidence_gate.js', target: 110, ceiling: 145, owner: 'tooling/release' },
  { file: 'scripts/spb_release_contract.js', target: 120, ceiling: 150, owner: 'tooling/release' },
  { file: 'scripts/spb_release_r2_publish.py', target: 90, ceiling: 120, owner: 'tooling/release' },
  { file: 'deploy_r2.py', target: 325, ceiling: 380, owner: 'tooling/release' },
  { file: 'spb_release.ps1', target: 520, ceiling: 575, owner: 'tooling/release' },
  { file: 'tests/test_release_r2_integrity.py', target: 170, ceiling: 210, owner: 'tooling/release-tests' },
  { file: 'finish-viewer.html', target: 5000, ceiling: 10000, owner: 'finish-viewer' },
  { file: 'paint-booth-4-pattern-renderer.js', target: 5000, ceiling: 8125, owner: 'patterns/ui' },
  { file: 'engine/compose.py', target: 5000, ceiling: 7200, owner: 'engine/compose' },
  { file: 'engine/spec_pattern_families/mechanical.py', target: 320, ceiling: 1160, owner: 'spec/patterns' },
  { file: 'engine/spec_pattern_families/weather_track.py', target: 320, ceiling: 980, owner: 'spec/patterns' },
  { file: 'engine/spec_pattern_families/artistic.py', target: 460, ceiling: 940, owner: 'spec/patterns' },
  { file: 'engine/spec_pattern_families/abstract_art.py', target: 1250, ceiling: 2910, owner: 'spec/patterns' },
];

const args = new Set(process.argv.slice(2));
const enforce = args.has('--enforce');
const asJson = args.has('--json');

const root = process.cwd();
const rows = budgets.map((budget) => {
  const fullPath = path.join(root, budget.file);
  if (!fs.existsSync(fullPath)) {
    return { ...budget, lines: null, status: 'MISSING' };
  }
  const lines = countFileLines(fullPath);
  let status = 'OK';
  if (lines > budget.ceiling) status = 'OVER_CEILING';
  else if (lines > budget.target) status = 'OVER_TARGET';
  return { ...budget, lines, status };
});

if (asJson) {
  console.log(JSON.stringify(rows, null, 2));
} else {
  console.log('SPB file budget');
  console.log('Use --enforce to fail on files over ceiling. Targets are refactor goals; ceilings prevent new bloat.');
  console.log('');
  console.log('status        lines   target  ceiling  file');
  for (const row of rows) {
    const lines = row.lines == null ? 'n/a' : String(row.lines);
    console.log(
      `${row.status.padEnd(13)} ${lines.padStart(6)} ${String(row.target).padStart(8)} ${String(row.ceiling).padStart(8)}  ${row.file} (${row.owner})`
    );
  }
}

const failures = rows.filter((row) => row.status === 'MISSING' || row.status === 'OVER_CEILING');
if (enforce && failures.length) {
  console.error('');
  console.error('File budget enforcement failed:');
  for (const row of failures) {
    console.error(`- ${row.file}: ${row.status}${row.lines == null ? '' : ` (${row.lines}/${row.ceiling})`}`);
  }
  process.exit(1);
}
