"""Process-specific briefs written before rendering the Discharge designs."""
NOAA='https://www.nssl.noaa.gov/education/svrwx101/lightning/types/'
REVIEW='https://arxiv.org/abs/1002.0070'

def entry(name,desc,carrier,spec,marks,neighbors,source=NOAA):
    return ('discharge',name,'Discharge',desc,carrier,spec,marks,source,neighbors)

TABLE={
'lsk_return_stroke':entry('Return Stroke',
 'Stepped silver return channels race through ink-blue lacquer: narrow bright cores, copper ion collars, leader forks and etched shock bands.',
 'Connected nonparallel stochastic return channels advance in fine 8–24px steps; short rooted leader forks, concentric conductor/copper/char zones and etched shock scars follow the actual discharge mesh.',
 'Main core is polished conductor, ion collars graded copper, shock scars dry dielectric, leader tips coated pearl; every material follows its named channel or collar.',
 [('return_core','continuous polished main discharge channel'),('ion_collar','copper deposit immediately outside the core'),('leader_fork','short stepped leader connected to its main channel'),('shock_band','etched band next to the channel'),('dielectric_grain','fine unburned lacquer grain'),('leader_tip','small terminal metal deposit')],
 [('lsk_lichtenberg','radiating fractal forest rather than continuous stepped main channels'),('lsk_bead','interrupted beaded decay rather than a continuous return core')]),
'lsk_spider_crawl':entry('Spider Crawl',
 'Fine horizontal crawler fans braid through midnight turquoise: hooked side branches, conductive knots, matte scorch cuffs and tiny copper bridges.',
 'Independent lateral crawler fans form a dense nonperiodic hooked mesh; short side branches bend back toward neighbouring paths, rooted crossing knots and copper near-channel bridges replace every fixed row and cross-stitch grid.',
 'Crawler paths polish, char cuffs roughen, copper bridges use eight metal tiers, branch roots retain coat and terminal dust is subdued dielectric.',
 [('crawler_path','wandering lateral discharge path'),('hooked_branch','short hooked side branch'),('crossing_knot','conductor node at a crossing'),('char_cuff','matte cuff beside a path'),('copper_bridge','fine metallic cross-stitch between paths'),('terminal_dust','faint charge deposits at branch ends')],
 [('lsk_lichtenberg','radial branching rather than lateral hooked braids'),('lsk_return_stroke','stepped main channels rather than side-crawling fans')]),
'lsk_st_elmo':entry("St Elmo's Fire",
 'Point-discharge brushwork over violet enamel: silver needle apices, cobalt corona ribs, copper guard collars and graded pearlescent discharge skirts.',
 'A complete fine irregular faceted electrode surface; sharp facet apices feed individually bent corona brush fans, seated copper guards and dark inter-facet roots; facet-owned etching and pearl planes fill the entire canvas.',
 'Needles are exposed polished metal; brush ribs are pearl pigment; collars are copper; enamel and skirt differ by coating depth; dark electrode roots are rough.',
 [('electrode_cone','fine sharp metal point'),('brush_rib','corona brush emerging from the tip'),('guard_collar','copper deposit around a point'),('discharge_skirt','pearlescent spread below the brush'),('electrode_root','dark seated root of a point'),('enamel_grain','fine continuous enamel substrate')],
 [('lsk_corona_ring','continuous streamer fringe rather than sharp point brushes'),('lsk_sprite','tendrils below a jellyfish cap rather than tip discharge')]),
'lsk_plasma_globe':entry('Plasma Globe',
 'A densely tessellated glass plasma lens: winding inner filaments meet pink rim flashes, polished nuclei and fine etched lens sectors.',
 'Individually warped 20–30px glass chambers; curved radial filaments connect nuclei to chamber rims; angular sectors bend inside convex lens faces and never continue through chamber edges.',
 'Convex glass faces carry graded dielectric coat, inner filaments pearl-metal tiers, rim contacts polish, etched lens rulings roughen, and nucleus contacts expose conductor.',
 [('glass_chamber','convex micro lens face'),('inner_filament','curved discharge path inside one lens'),('rim_contact','filament contact at a chamber rim'),('nucleus_contact','small conductor at lens centre'),('lens_ruling','etched sector inside the convex glass'),('glass_grain','fine dust trapped within the glass')],
 [('wrap_microbubble','trapped smooth air domes without internal filaments'),('bth_fisheye','open concave craters rather than convex closed chambers')]),
'lsk_jacobs_ladder':entry("Jacob's Ladder",
 'Copper rails carry dense ascending arc rungs through jade-black enamel, with white contact shoes, heat-tarnished slots and tiny etched climb marks.',
 'Pairs of continuous fine wavy rails frame independently curved ascending rungs; clipped climbing marks, contact shoes and heat collars prove an arc climbing between electrodes.',
 'Copper rails use graded metal states, arc rungs pearl conductor, contact shoes polish, heat slots roughen, enamel stays dielectric with subordinate fine grain.',
 [('paired_rail','two continuous fine copper electrodes'),('arc_rung','curved ascending connection between rails'),('contact_shoe','bright seated arc contact on a rail'),('heat_slot','tarnished slot beside each rung'),('climb_mark','short etched climbing registration'),('enamel_grain','fine jade-black enamel between electrodes')],
 [('mul_wireframe','projected polygon mesh rather than paired electrodes'),('lsk_return_stroke','free stepped discharge rather than climbing framed rungs')]),
'lsk_arc_weld':entry('Arc Weld Mosaic',
 'Overlapping molten weld dimes in heat-coloured titanium: rolled crescent rims, dark fusion roots, puddle pores and fine flying spatter.',
 'Irregular staggered weld tracks composed of overlapping 12–25px molten dimes; directional crescent ripples and heat oxidation travel along each weld, with rooted pores and nearby spatter.',
 'Molten dime faces and rolled rims have separate metal/polish tiers; fused roots and pores roughen, oxide collars suppress metal, spatter is polished deposited alloy.',
 [('molten_dime','overlapping small weld puddle'),('rolled_crescent','raised advancing edge of a puddle'),('fusion_root','dark fused seam between weld tracks'),('oxide_collar','heat-coloured oxidised alloy'),('puddle_pore','small pore in a cooled puddle'),('weld_spatter','small adjacent deposited alloy grains')],
 [('slt_sunbeam_iris','keratin lance scales rather than overlapping circular molten puddles'),('bth_sag_curtain','flowing paint curtains rather than welded alloy')],REVIEW),
'lsk_sprite':entry('Sprite Tendrils',
 'Microscopic copper-red sprite caps hang over violet branched tendrils: pearl columns, dark root forks and tiny misted termination points.',
 'Asymmetric jellyfish-like upper caps feed several independently bent fine descending filaments; column segments, branch forks and termination clusters remain subordinate to the cap-and-tendril anatomy.',
 'Caps use copper-pearl tiers, columns polish, root forks and cap trenches roughen; termination mist is pearlescent pigment embedded in dielectric lacquer.',
 [('sprite_cap','asymmetric upper discharge canopy'),('descending_column','fine descending filament from the cap'),('root_fork','dark split between filament roots'),('cap_trench','etched crease around the upper cap'),('termination_mist','small clustered terminal pigment grains'),('column_segment','individually polished section of a descending filament')],
 [('lsk_st_elmo','brush from a sharp electrode rather than hanging cap/tendrils'),('astra_abyssal_lanterns','marine bioluminescent structures rather than electrical columns')]),
'lsk_static_creep':entry('Static Creep',
 'Connected charge creeps around fine crazed enamel islands: doubled metal tracks, frosted insulating ridges, trapped pin sparks and copper junctions.',
 'Thresholded fine percolation contours create an irregular connected insulating maze; doubled surface-creep tracks flank the maze, with separately rooted pin sparks and junction deposits.',
 'Creep tracks are exposed polished conductor, insulating ridges frosted dielectric, junctions graded copper, enamel islands retain graded coat and sparks use fine deposited metal tiers.',
 [('enamel_island','fine connected intact enamel region'),('creep_track','surface charge path following an island edge'),('paired_track','secondary deposited track next to the first'),('frosted_ridge','insulating ridge beside the charge path'),('pin_spark','small trapped conductor at a contour extremum'),('junction_deposit','copper deposit at a contour junction')],
 [('wrap_craze_net','fractured coating net rather than doubled conductive creep tracks'),('lsk_carbon_track','contaminant-directed carbon channels rather than insulating maze contours')],REVIEW)
}

TABLE.update({
'lsk_carbon_track':entry('Carbon Tracking',
 'Ragged graphite charge ropes creep through pearlescent porcelain: braided char veins, fused glass shoulders, copper contamination and tiny burn-through pores.',
 'Anisotropic contaminant ropes composed of irregular short charcoal fibres; discontinuous paired fused-glass shoulders flank carbon channels, with local contaminant bridges and ablated pores.',
 'Carbon is rough nonmetal, copper contamination graded metal, fused glass is glossy dielectric, exposed pore floors matte and intact porcelain retains fine pearl grain.',
 [('carbon_rope','irregular braided char charge path'),('fused_shoulder','glassy shoulder alongside a char rope'),('contaminant_bridge','small copper bridge into the char channel'),('burnthrough_pore','fine ablated hole rooted in a rope'),('porcelain_grain','intact fine pearl dielectric'),('char_fibre','short longitudinal carbon strand')],
 [('lsk_static_creep','paired conductor around enamel islands rather than ragged char ropes'),('lsk_lichtenberg','radiating burn trees rather than contaminant-directed tracking')],REVIEW),
'lsk_bead':entry('Beaded Lightning',
 'A fading channel breaks into oblique pearl droplets: bright bead heads, copper tails, charcoal necks and tiny residual charge hairs over indigo lacquer.',
 'Meandering decaying channels are segmented into unequal 8–24px elongated droplets; offset tail streaks, disappearing necks and independent residual side hairs prove interrupted decay.',
 'Pearl heads and exposed bead rims polish; copper tails use graded metal; extinguished necks and residual scars roughen; intact lacquer remains dielectric.',
 [('pearl_head','bright leading half of a decaying bead'),('copper_tail','long deposited trailing half'),('dark_neck','extinguished channel between two beads'),('bead_rim','narrow polished edge of a bead'),('residual_hair','fine residual side discharge'),('lacquer_grain','intact indigo lacquer between decayed channels')],
 [('lsk_return_stroke','continuous core rather than interrupted decay'),('wrap_microbubble','unconnected convex domes rather than elongated beads along a fading channel')]),
'lsk_streamer_front':entry('Streamer Front',
 'Fine comb-shaped discharge fronts overlap through amber glass: advancing pearl tips, copper precursor hooks, dark return trenches and graded charge skirts.',
 'Independently bent fine advancing fronts carry unequal comb filaments clipped to their own front; short precursor hooks, returned side branches and charge skirts interlock between fronts.',
 'Advancing tips polish, precursor hooks graded copper, return trenches rough nonmetal, charge skirts coated pearl and glass retains fine dielectric tiers.',
 [('advancing_front','small bent advancing discharge face'),('comb_filament','fine independently ended front filament'),('precursor_hook','copper hook ahead of the front'),('return_trench','etched nonconductive rear branch'),('charge_skirt','graded pearlescent skirt behind the front'),('tip_contact','small polished front-end contact')],
 [('lsk_st_elmo','rooted sharp-point brushes rather than advancing comb fronts'),('lsk_spider_crawl','lateral hooked networks rather than advancing feathered fronts')],REVIEW),
'lsk_fulgurite':entry('Fulgurite Glass',
 'Lightning-fused sand becomes an intricate amber tube lace: vitreous walls, dark hollow bores, sintered silica grains, melt striae and trapped pearly bubbles.',
 'Fine meandering hollow vitreous tubes change thickness around sintered 8–16px silica granules; clipped longitudinal melt striae and tiny trapped bubbles live in tube walls rather than a generic crater field.',
 'Tube glass is glossy dielectric, sintered silica rough pearl, bore interiors matte and dark, melt striae coated, trapped bubble rims use thin pearlescent tiers.',
 [('vitreous_wall','fused fine glass tube wall'),('hollow_bore','dark interior of a tube'),('silica_granule','small sintered sand grain embedded in a wall'),('melt_stria','longitudinal fine flow inside tube glass'),('trapped_bubble','fine bubble trapped in a vitreous wall'),('fusion_collar','pearlescent sand-to-glass transition')],
 [('bth_fisheye','open retreat craters rather than connected hollow glass tubes'),('lsk_carbon_track','charred contaminant ropes rather than fused sand tubes')],REVIEW),
'lsk_spark_gap':entry('Spark Gap Array',
 'Opposing microscopic silver contacts punctuate burnt-orange ceramic: fractured gap arcs, copper contact shoulders, black ablation pits and fine guard engraving.',
 'Unequal opposing contacts separated by open fine gaps; each gap has a differently kinked bridge, tiny ablation pits and clipped ceramic guard cuts; contacts vary independently in seating and width.',
 'Contact faces high metal, shoulder copper graded, gap arcs polished pearl-metal, ablated ceramic rough nonmetal and guard engraving suppresses coat.',
 [('opposed_contact','unequal opposing seated electrode'),('gap_arc','fine kinked bridge across an open gap'),('copper_shoulder','tiered contact-side copper deposit'),('ablation_pit','small rough crater at a gap contact'),('guard_engraving','fine ceramic guard cut around contact'),('ceramic_seat','coated dielectric contact substrate')],
 [('lsk_jacobs_ladder','continuous paired rails rather than independent opposing contacts'),('mul_edge_chamfer','optical false bevels rather than actual material gaps')],REVIEW),
'lsk_tesla_streamer':entry('Tesla Streamer',
 'Microscopic winding coils launch curled pearl streamers through burgundy lacquer: exposed coil turns, hooked terminals, dark insulation and copper feed vias.',
 'Individually connected fine square copper windings terminate in separate feed vias and kinked external discharge hooks; dark insulation collars, local conductor polish tiers and terminal deposits trace each physical coil.',
 'Exposed windings graded copper, insulation rough dielectric, streamer terminals polished pearl, feed vias exposed metal, and lacquer coat varies only within its owned regions.',
 [('coil_turn','fine continuous wound copper conductor'),('streamer_hook','curved discharge leaving a coil'),('insulation_window','exposed window in coil insulation'),('feed_via','fine seated conductor feed'),('terminal_tip','polished hooked terminal point'),('lacquer_field','burgundy dielectric between coils')],
 [('wrap_spiral_burnish','polymer polish scores rather than wound conductor plus insulation/vias'),('lsk_plasma_globe','chamber-clipped filaments rather than exposed winding coils')],REVIEW),
'lsk_corona_ring':entry('Corona Ring Lace',
 'Interlocking fine copper coronas fringe a cyan ceramic lace: asymmetric oval guards, radial pearl streamlets, shield apertures and dark seated torus roots.',
 'Irregular overlapping 12–30px oval guard rings carry short unequal outward corona fringe; shield apertures, recessed seats and fine torus ruling define an interlocked conductor lace.',
 'Guard rings use eight metal/polish tiers; outward fringe pearl-metal; recessed seats rough nonmetal; apertures reveal ceramic; torus ruling roughens only the ring.',
 [('guard_ring','asymmetric fine oval conductor'),('corona_fringe','short uneven outward discharge fringe'),('shield_aperture','small window inside the guard'),('torus_root','dark recessed ring seat'),('torus_ruling','fine engraving inside the conductor'),('ceramic_lace','fine connecting dielectric between guards')],
 [('lsk_st_elmo','point-emerging brushes rather than guard-ring fringe'),('wrap_holographic','foil security rosettes rather than seated conductor rings')],REVIEW)
})
