"""Living Armor: anatomy-specific contracts, not recolours of one scale kit."""
REF='https://www.nature.com/articles/srep23539'
SIDE='https://arxiv.org/abs/2505.24827'
BELLY='https://arxiv.org/abs/1305.4705'

def entry(name,desc,carrier,spec,marks,neighbors,source=REF):
    return ('armor',name,'Living Armor',desc,carrier,spec,marks,source,neighbors)

TABLE={
'slt_reticulated':entry('Reticulated Python',
 'A continuous pale copper net holds dark irregular armour blocks, each packed with fine keratin crescents, root pores and differently coated facets.',
 'Warped pinched reticulation cells form a connected pale net; dark blocks have independently oriented clipped crescent microdermatoglyphs and recessed root pores; net crossings thicken into fine collar joints.',
 'Net is graded copper-pearl, dark blocks coated keratin, crescents locally rough, root pores nonmetal and collar joints polished; no common scale carrier is reused.',
 [('pale_net','continuous pinched reticulation border'),('dark_block','dark armour inside the net'),('keratin_crescent','fine clipped crescent inside a block'),('root_pore','small recessed scale root'),('collar_joint','thickened net crossing'),('block_facet','differently coated keratin plane')],
 [('slt_diamondback','regular pointed rhombs over keels rather than irregular reticulation blocks'),('slt_shed_ecdysis','open papery membranes rather than solid dark blocks')]),
'slt_keeled_viper':entry('Keeled Viper',
 'Dense overlapping asymmetric spear scales form a complete copper-green skin; raised keels divide independently polished faces, with lapped edges, dry root shoulders, hooked tips, crossed dermal cuts and elongated pores.',
 'Occlusion-ordered 14–29px asymmetric five-sided spear scales overlap in wandering staggered rows; visible half-face slopes, axial keels, hooked tips, lap seats and dermal pores belong to their actual rasterized scale. Fine density replaces bare backing without larger motifs.',
 'Keel crests polished metal-pearl; cool left faces graded high-metal foil with lower roughness and stronger coat reflection, warm right faces rougher pigmented material with independent metal/coat tiers. Lapped seats and roots matte, tips polished, dermal cuts rough and pores dry dielectric. All spec masks trace this dense scale stack.',
 [('axial_keel','raised longitudinal scale ridge'),('left_slope','first asymmetric keel face'),('right_slope','second asymmetric keel face'),('lap_seat','occluded edge of an overlapping scale'),('root_shoulder','dry recessed scale root'),('hooked_tip','short exposed trailing scale point'),('dermal_cut','fine crossed ruling inside a scale'),('elongated_pore','fine dry slot in the keratin face')],
 [('slt_sunbeam_iris','short smooth interference lances rather than raised axial spears'),('slt_diamondback','pigmented rhomb borders rather than continuous keel relief')]),
'slt_cycloid_gloss':entry('Sea Snake Gloss',
 'Overlapping wet cycloid shells show fan striae, bright meniscus lips, dark basal pockets and pin-sized trapped droplets through blue-gold pearl.',
 'Staggered overlapping round cycloid shells with directional fan striae and narrow wet overlap lips; basal pockets and trapped droplets are anatomically clipped inside shell surfaces.',
 'Wet shells glossy dielectric-pearl, lips polished, basal pockets rough and subdued, fan striae vary coat, droplets retain strong clearcoat with low metal.',
 [('cycloid_shell','overlapping smooth rounded scale'),('fan_stria','radial dermal fan inside a shell'),('wet_lip','narrow polished overlap meniscus'),('basal_pocket','dark recessed scale root'),('trapped_droplet','small wet bead rooted on a shell'),('shell_plane','locally tiered smooth wet face')],
 [('slt_sunbeam_iris','asymmetric lance rows rather than rounded fan shells'),('wrap_microbubble','isolated trapped air rather than overlapping wet scales')]),
'slt_ventral_scute':entry('Ventral Scute',
 'Wide transverse belly plates interlock through narrow side hinges: amber pearl faces, fine friction ribs, cream seam lips and rooted skin pores.',
 'Fine transverse scutes have asymmetrical interlocking side hinges and flexible wavy rear seams; friction ribs terminate inside each broad plate and pores sit in their hinge roots.',
 'Plate faces coated pearl, friction ribs graded rough keratin, seam lips polished, hinge skin matte and root pores coat-reflection-minimized nonmetal.',
 [('transverse_plate','wide fine belly scute'),('side_hinge','interlocking lateral plate hinge'),('rear_seam','flexible wavy rear overlap'),('friction_rib','fine clipped longitudinal wear rib'),('seam_lip','narrow polished plate edge'),('hinge_pore','small dry pore in a hinge root')],
 [('slt_keeled_viper','axial spear scales rather than transverse scutes'),('wrap_panel_seam','manufactured stepped panels rather than flexible biological hinges')],BELLY),
'slt_boa_saddle':entry('Boa Saddlework',
 'Pinched dark saddles sit within copper-ivory hide, with scalloped keratin tesserae, cream saddle rims, dry waist trenches and minute basal freckles.',
 'Opposed curved saddle lobes pinch at each waist; scalloped fine tesserae turn around the saddle contour, while basal freckles and waist trenches remain inside the anatomical saddle field.',
 'Saddle hide dry coated dielectric, pale rims pearl-metal, tesserae vary local coat, waist trenches rough and freckles subdued keratin.',
 [('saddle_lobe','dark pinched saddle marking'),('pale_saddle_rim','cream outline around a saddle'),('waist_trench','dark narrow pinch between saddle lobes'),('keratin_tessera','fine scalloped hide tile'),('basal_freckle','small recessed pigment freckle'),('hide_plane','intact individually tiered hide')],
 [('slt_gaboon_geometric','razor hourglasses rather than curved pinched saddles'),('slt_anaconda_oval','staggered oval marks rather than paired saddle lobes')]),
'slt_sidewinder_micro':entry('Sidewinder Micro',
 'Sand-adapted diamond granules have asymmetric windward polish, fine erosion pits, dry lee ridges and silica caught between small ochre-violet scales.',
 'Irregular oblique diamond granules have one polished windward slope and a broken lee ridge; fine erosion pits and interstitial silica clusters follow directional sand abrasion.',
 'Windward faces polished pearl, lee ridges rough keratin, trapped silica matte with pearl tiers, erosion pits nonmetal and intact faces coated subtly.',
 [('diamond_granule','small oblique desert scale'),('windward_slope','abraded polished front face'),('lee_ridge','dry broken trailing ridge'),('erosion_pit','fine abrasive pore in a scale'),('trapped_silica','sand grains between scales'),('keratin_face','intact tiered desert scale face')],
 [('slt_wart_tubercle','rounded raised tubercles rather than directionally eroded diamonds'),('slt_diamondback','pigment rhombs rather than sand abrasion anatomy')],SIDE),
'slt_gaboon_geometric':entry('Gaboon Geometric',
 'Razor hourglasses and triangular flank marks tessellate through bronze-plum hide, divided by pale bevels, fine leaf-vein cuts and dry black root creases.',
 'Paired narrow-waisted hourglass planes alternate with triangular flank wedges; leaf-vein cuts are clipped independently inside each shape, with pale bevels and recessed root creases.',
 'Hourglass and flank planes have different coated pearl/metal tiers; pale bevels polish, root creases roughen and leaf cuts suppress coat only inside their parent plane.',
 [('hourglass_plane','razor-bounded narrow-waisted marking'),('flank_triangle','triangular biological flank mark'),('pale_bevel','fine pale marking border'),('leaf_cut','clipped fine vein-like scale cut'),('root_crease','dry black root boundary'),('pigment_grain','fine pigment within intact hide')],
 [('slt_boa_saddle','curved saddle lobes rather than razor hourglasses'),('astra_blueblood_chevron','manufactured parquet chevrons rather than narrow-waisted biological planes')]),
'slt_milk_band':entry('Milk Snake Band',
 'Ordered scarlet-black-ivory rings bend around fine transverse skin, with scalloped band seams, lacquered red ribs, dry black keratin and minute cream root pearls.',
 'Strict red-black-cream-black band order is carried by fine flexible transverse riblets; scalloped seams, differently pitched cream grain and red plate cuts make construction identifiable without hue.',
 'Red lacquer glossy coated dielectric, black keratin matte, cream pearl partly metallic, band seams rough and root pearls polished; material bands follow actual riblet anatomy.',
 [('scarlet_riblet','fine lacquered scarlet skin rib'),('black_keratin','dry narrow black biological band'),('ivory_grain','fine cream pigment plate'),('band_seam','scalloped anatomical band boundary'),('red_plate_cut','fine cut inside a red riblet'),('root_pearl','small cream scale root')],
 [('slt_corn_blotch','outlined saddles rather than strict ordered bands'),('wrap_print_band','printer passes rather than anatomical riblets')]),
'slt_corn_blotch':entry('Corn Snake Blotch',
 'Unbroken dark outlines enclose burnt-scarlet saddles over fine orange belly checks, with pearled rims, tiny pigment pores and individually cut keratin tiles.',
 'Rounded angular blotches have an unbroken narrow dark ring; the surrounding skin is a fine staggered checker tessellation with clipped keratin cuts, rim pearls and interior pigment pores.',
 'Blotch lacquer coated dielectric, dark outlines matte nonmetal, pale rims graded pearl, belly checks have separate material tiers and pore floors suppress coat.',
 [('scarlet_blotch','outlined rounded angular pigment saddle'),('unbroken_outline','continuous dark biological blotch border'),('belly_check','fine staggered checker skin tile'),('rim_pearl','pale polished edge of a blotch'),('keratin_cut','fine cut clipped inside a tile'),('pigment_pore','small recessed interior pore')],
 [('slt_boa_saddle','opposed curved saddles rather than enclosed outlined blotches'),('slt_milk_band','ordered transverse bands rather than checker-backed blotches')]),
'slt_shed_ecdysis':entry('Shed Skin Lace',
 'Papery translucent scale ghosts form a dense ivory-violet lace: curled membrane lips, missing windows, dry wrinkle cuts and fine basal root rings.',
 'Irregular stretched membrane cells have torn windows and individually curled overlap lips; fine wrinkles turn around each membrane, with dry root rings and translucent intact keratin.',
 'Papery keratin stays primarily nonmetal and rough; membrane lips carry sparse pearl polish, exposed windows reveal dry substrate, wrinkles roughen and translucent faces vary coat deliberately.',
 [('membrane_face','translucent shed keratin'),('torn_window','small missing membrane aperture'),('curled_lip','fine curled papery overlap edge'),('wrinkle_cut','fine dry fold within a membrane'),('basal_ring','old rooted scale ghost'),('intact_keratin','subordinate intact translucent face')],
 [('slt_albino_translucent','living pigmentless skin rather than detached dry membranes'),('slt_reticulated','solid dark blocks rather than open translucent lace')]),
'slt_cobra_hood':entry('Cobra Hood Weave',
 'Splayed hood ribs pull fine scales wide through cobalt-bronze silk, with paired vein seams, polished shoulder lips and dark flexible hinge roots.',
 'Alternating splayed shoulder fans stretch wide scale plates around curved hood ribs; paired vein seams, hinge roots and clipped transverse microcuts express lateral stretch rather than a hood icon.',
 'Stretched plate faces coated pearl, raised hood ribs graded metal, hinge roots dry nonmetal, shoulders polish and microcuts locally reduce coat.',
 [('splayed_plate','laterally stretched fine hood scale'),('hood_rib','curved raised fan rib'),('paired_vein','fine paired vein seam within a fan'),('hinge_root','dark flexible scale hinge'),('shoulder_lip','polished stretched shoulder'),('transverse_cut','fine clipped cut across a stretched plate')],
 [('slt_ventral_scute','transverse belly plates rather than splayed shoulder fans'),('slt_keeled_viper','axial spears rather than stretched lateral hood ribs')]),
'slt_wart_tubercle':entry('Wart Snake Hide',
 'Crowded irregular tubercles rise from violet hide, with copper worn crowns, dry granular collars, pearly satellite warts and tiny asymmetric skin fissures.',
 'Crowded unequal elongated tubercles have offset worn crowns and irregular satellite bumps; granular collars and rooted skin fissures connect their bases across a continuous hide.',
 'Dry tubercle faces rough pearl-dielectric, worn crowns polished metal-pearl, satellite bumps separately coated, collars matte and basal fissures nonmetal.',
 [('tubercle_face','unequal raised granular wart'),('worn_crown','offset polished tubercle top'),('granular_collar','dry granular wart root'),('satellite_wart','small adjacent raised bump'),('skin_fissure','asymmetric rooted basal crease'),('hide_grain','fine intact skin between tubercles')],
 [('slt_sidewinder_micro','eroded diamonds rather than rounded tubercles'),('bth_fisheye','concave retreat craters rather than raised warts')]),
'slt_diamondback':entry('Diamondback Armor',
 'Pale bordered rhombs traverse a fine raised keel field: charcoal diamond centres, copper axial ribs, cream pointed collars and individually scarred scale faces.',
 'Pointed rhomb markings sit on a crossed field of small raised axial keels; incomplete collar facets, scarred half-faces and dry root notches change the structure from a simple diamond grid.',
 'Dark rhomb centres subdued keratin, pale borders pearl metal, keels polished, half-face scars rough and root notches suppress coating; pigment and relief have distinct owned states.',
 [('rhomb_centre','dark pointed diamond marking'),('pale_border','fine pale rhomb outline'),('axial_rib','raised keel within the rhomb field'),('collar_facet','pointed border facet at a rhomb corner'),('face_scar','fine scale-face abrasion'),('root_notch','small recessed scale notch')],
 [('slt_reticulated','irregular reticulation blocks rather than pointed rhombs and keels'),('slt_keeled_viper','unmarked spear anatomy rather than bordered rhomb pigmentation')]),
'slt_anaconda_oval':entry('Anaconda Oval',
 'Staggered dark oval markings hold pale olive hearts across fine emerald hide, with offset eyelid rims, pore constellations and hooked keratin creases.',
 'Unequal staggered oval pigment regions have offset pale hearts and open eyelid rims; fine hooked keratin creases and pore constellations turn around each marking rather than a circular dome carrier.',
 'Dark oval pigment matte dielectric, olive hearts coated pearl, eyelid rims polished, hooked creases rough and pore constellations mostly nonmetal with sparse pearl grains.',
 [('dark_oval','unequal staggered dark marking'),('pale_heart','offset olive heart inside a marking'),('eyelid_rim','open polished marking edge'),('hooked_crease','fine keratin crease turning around a mark'),('pore_constellation','small anatomically rooted pores'),('emerald_hide','intact fine coated skin')],
 [('slt_boa_saddle','pinched saddle lobes rather than staggered ovals'),('wrap_microbubble','convex trapped domes rather than flat pigment and keratin anatomy')]),
'slt_albino_translucent':entry('Albino Translucence',
 'Living ivory-pink skin keeps its fine pigmentless scale ghosts, with translucent keratin veils, rose capillary roots, polished pearl lips and faint dry dermal cuts.',
 'Fine unequal translucent teardrop veils overlap a rose capillary scaffold; ghost markings survive as relief, with sparse pearled lips and dry clipped dermal cuts; the skin remains living rather than shed.',
 'Pigmentless skin primarily dielectric, pearl lips selectively polish, capillary roots subdued matte, translucent veils carry graded coat and dermal cuts roughen; restrained chroma is intentional.',
 [('keratin_veil','fine translucent living scale'),('rose_capillary','subordinate rose root scaffold'),('ghost_mark','pigmentless relief marking'),('pearl_lip','selectively polished scale edge'),('dermal_cut','faint clipped dry cut'),('living_skin','intact ivory-pink dielectric')],
 [('slt_shed_ecdysis','detached dry torn membranes rather than living overlapped skin'),('slt_sunbeam_iris','strong interference colour rather than pigmentless translucent keratin')])
}
