"""Paint-process anatomy and material ownership, declared before rendering."""
PPG='https://www.ppg.com/en-US/refinish/support/user-guides-and-manuals/common-paint-defects-guide'
POP='https://www.ppg.com/en-AE/automotive-refinish/solvent-popping'

def entry(name,desc,carrier,spec,marks,neighbors,chapter='Paint Alchemy',source=PPG):
    return ('alchemy',name,chapter,desc,carrier,spec,marks,source,neighbors)

TABLE={
'bth_solvent_pop':entry('Solvent Pop Lacquer',
 'Ruptured fine solvent blisters tear copper-red lacquer into angular vent mouths, curled shell fragments, dark pinholes and pearled release collars.',
 'Unequal angular ruptured blister shells have split vent cuts, curled shell lips and separate pinhole mouths; fine pigment remains in intact lacquer and small broken flakes trail each vent.',
 'Intact lacquer coated pearl, vent mouths rough exposed substrate, shell lips polished, split cuts coat-reflection-minimized, and release collars use graded metal/coat tiers.',
 [('ruptured_shell','raised angular solvent blister shell'),('vent_mouth','small open solvent release'),('split_cut','fine tear leading from the mouth'),('curled_lip','polished shell fragment edge'),('release_collar','tiered vent-side deposit'),('pigment_flake','fine intact lacquer pigment')],
 [('bth_fisheye','paint retreat craters rather than ruptured raised shells'),('wrap_microbubble','intact trapped-air domes rather than open solvent vents')],source=POP),
'bth_sag_curtain':entry('Sag Curtain Flow',
 'Fine overloaded lacquer runs into branching gravity curtains: bulbous run toes, polished advancing lips, folded wet shoulders and dry separation trenches.',
 'Continuous descending gravity curtains split and rejoin through fine variable-width run necks; unequal hanging toes and folded side shoulders are rooted in each actual curtain.',
 'Wet runs glossy coated dielectric-pearl, shoulders partly metallic pigment, advancing lips polished, separation trenches rough and hanging toes strongly coated.',
 [('gravity_curtain','connected descending wet paint run'),('run_neck','fine constriction in an overloaded run'),('hanging_toe','small bulbous end of a run'),('wet_shoulder','folded wet side of a curtain'),('advancing_lip','narrow polished run edge'),('separation_trench','dry trench between adjacent runs')],
 [('bth_tiger_stripe','spray pass bands rather than descending split runs'),('wrap_flow_wrapline','manufactured film flow rather than overloaded gravity curtains')]),
'bth_dry_spray':entry('Dry Spray Velvet',
 'Half-cured fine droplets form a dense velvet aggregate: granular pigment crowns, unflowed necks, dry island rims, sparse wet binder and tiny trapped pores.',
 'Crowded unequal dry splats merge only at short necks; raised pigment crowns, dry rims and occasional wet binder windows distinguish granular spray from a smooth droplet sheet.',
 'Dry droplets mostly rough nonmetal-pearl, wet binder locally coated, pigment crowns separately tiered, pores coat-reflection-minimized and unflowed necks dry.',
 [('dry_splat','half-cured fine spray droplet'),('pigment_crown','raised pigment aggregate on a splat'),('unflowed_neck','short unfused droplet connection'),('dry_rim','rough island edge'),('wet_binder','small surviving wet binder window'),('trapped_pore','fine air gap in dry aggregate')],
 [('bth_blush','moisture whitening inside film rather than granular unflowed spray'),('mul_foam_clad','closed-cell protective foam rather than dry pigment aggregates')]),
'bth_mottling':entry('Mottled Metallic',
 'Clumped metallic pigment drifts into fine copper-blue islands: differently tilted flake fans, pale binder seams, dark pigment knots and small polished grain tips.',
 'Fine anisotropic flake fans accumulate into irregular interlocking pigment islands; tilted flake faces, binder seams and crowded knots follow deposition rather than a generic cellular mosaic.',
 'Flake faces graded metal with angle-dependent polish tiers, binder seams dielectric, pigment knots rough, grain tips polished and intact binder coated.',
 [('flake_fan','fine directed metallic pigment accumulation'),('pigment_island','interlocked clump of deposited flakes'),('binder_seam','fine binder region between deposits'),('pigment_knot','crowded rough flake junction'),('grain_tip','small polished exposed flake end'),('tilted_face','individually coated flake plane')],
 [('bth_dry_spray','unflowed polymer droplets rather than tilted metal flake fans'),('lsk_arc_weld','molten alloy puddles rather than accumulated pigment')]),
'bth_tiger_stripe':entry('Tiger Stripe Spray',
 'Fine gun-pass bands overlap through amber-violet metallic paint, with feathered overspray teeth, polished pass cores, dark overlap seams and individually tilted flakes.',
 'Unequal fine spray passes have separately feathered boundaries and displaced overlap seams; pass cores, overspray teeth and tilted flake cuts follow the actual gun-pass direction.',
 'Pass cores coated metallic pigment, overspray teeth rougher, overlap seams subdued, flake cuts graded metal and pale register lips polished.',
 [('pass_core','fine metallic gun-pass centre'),('overspray_tooth','small feathered spray fringe'),('overlap_seam','dark displaced pass overlap'),('tilted_flake','fine pigment flake aligned to a pass'),('register_lip','narrow pale pass edge'),('binder_band','intact coated paint between pass cores')],
 [('slt_milk_band','strict biological tricolour order rather than uneven spray deposition'),('wrap_print_band','mechanical print-pass registration rather than feathered gun spray')]),
'bth_die_back':entry('Die-Back Patina',
 'Gloss sinks through fine wrinkled lacquer islands: matte collapsed faces, surviving pearl lips, dry crease roots, polished pigment witnesses and subtle coat-density ghosts.',
 'Connected fine shrinkage wrinkles divide collapsed coat islands; narrow surviving lips and pigment witnesses remain on their actual coat shoulders, with dry roots and subdued density ghosts.',
 'Collapsed coat rough with weak clearcoat, surviving lips smoother, pigment witnesses partly metallic, dry roots nonmetal; quiet paint and uneven material response are intentional.',
 [('collapsed_face','fine dull collapsed clearcoat area'),('shrink_wrinkle','connected fine drying wrinkle'),('surviving_lip','narrow remaining smooth coat edge'),('dry_root','rough crease bottom'),('pigment_witness','small exposed pearlescent pigment'),('density_ghost','subtle intact coat-density variation')],
 [('bth_lifting','buckled attacked undercoat rather than gloss sinking after cure'),('wrap_craze_net','fractured coating rather than collapsed unbroken lacquer')]),
'bth_blush':entry('Blushed Clearcoat',
 'Moisture whitens rose-violet lacquer into fine milky veils, with binder pockets, condensation stringers, small trapped droplets and surviving polished pigment.',
 'Fine condensed moisture veils spread inside a continuous binder; short stringers, trapped droplets and incomplete meniscus rims stay rooted within the actual whitening regions.',
 'Whitened film rougher with weaker coat, intact binder glossy dielectric, surviving pigment partly metallic, droplets strongly coated and dry menisci subdued.',
 [('milky_veil','fine moisture-whitened film'),('binder_pocket','intact clear binder between veils'),('condensation_stringer','short moisture-linked pigment strand'),('trapped_droplet','small condensed moisture lens'),('dry_meniscus','incomplete whitened droplet rim'),('pigment_witness','fine surviving polished pigment')],
 [('wrap_wet_apply','water under an applied film rather than moisture inside lacquer'),('bth_dry_spray','dry granular droplets rather than internal whitening')]),
'bth_lifting':entry('Lifted Lacquer',
 'Attacked undercoat buckles into fine peeled ribbons: curled film tongues, exposed primer windows, dark hinge roots, flaked edges and polished swollen shoulders.',
 'Connected buckled coating ribbons have unequal peeled tongues and exposed primer windows; hinge roots, curled lips and detached flakes follow solvent attack from below.',
 'Lifted film coated pearl, exposed primer matte nonmetal, swollen shoulders partly metallic, curled lips polished, hinge roots rough and detached flakes dry.',
 [('buckled_ribbon','connected lifted coating strip'),('peeled_tongue','small uneven detached film tongue'),('primer_window','exposed undercoat through a lift'),('hinge_root','dark attached root of a peeled tongue'),('curled_lip','polished turning film edge'),('detached_flake','small dry broken coating fragment')],
 [('wrap_lift_curl','applied film adhesive lifting rather than solvent-attacked paint'),('bth_die_back','collapsed continuous coat rather than peeled undercoat')]),
'bth_sand_scratch':entry('Sand Scratch Alloy',
 'Fine crossed grit cuts telegraph through blue-bronze alloy paint: scored grooves, raised burr lips, short polishing arcs, grit pores and exposed pigment filings.',
 'Dense independently drawn 8–28px sanding strokes cross at varied grit angles; burr lips flank real grooves, short arcs interrupt straight scoring, and grit pores/filings occupy stroke roots.',
 'Grooves rough exposed substrate, burr lips polished metal, intact paint coated pearl, grit pores dry nonmetal and filings graded metal.',
 [('grit_groove','fine crossed sanding score'),('burr_lip','raised narrow edge of a score'),('short_arc','fine curved sanding interruption'),('grit_pore','small rooted grit depression'),('pigment_filing','fine exposed alloy particle'),('intact_paint','continuous coated paint above sanding')],
 [('bth_buff_hologram','rotary micro arcs rather than crossed grit scoring'),('wrap_brushed_film','regular brushing rather than varied crossed sanding strokes')]),
'bth_dirt_nib':entry('Dirt Nib Lacquer',
 'Angular dust tents wet lacquer into fine raised peaks, with stretched menisci, dark rooted grit, pearl stress cuts and small trapped binder beads.',
 'Unequal angular contaminant nuclei raise asymmetric lacquer tents; stretched menisci, rooted grit, fine radial stress cuts and separate binder beads follow each actual particle.',
 'Dust nuclei rough nonmetal, lacquer tents coated pearl, stretched lips polished, stress cuts rough, binder beads glossy dielectric and exposed grit floors dry.',
 [('contaminant_peak','fine angular dust particle under paint'),('lacquer_tent','raised asymmetric coating over a particle'),('stretched_meniscus','polished tent shoulder'),('rooted_grit','dark seated contaminant floor'),('stress_cut','fine radial tension incision'),('binder_bead','small intact wet binder bead')],
 [('slt_wart_tubercle','biological granular tubercles rather than angular dust tents'),('bth_solvent_pop','ruptured shells rather than intact contamination peaks')]),
'bth_edge_map':entry('Repair Edge Map',
 'Fine repaired coating contours reappear as nested gloss witnesses: exposed alloy, primer rings, colour film steps, ghost edge lips and small sanding notches.',
 'Nested irregular fine repair contours expose a distinct substrate/primer/colour/coat stack; narrow gloss witness lips and sanding notches follow the actual repair boundary rather than a decorative topographic overlay.',
 'Exposed alloy high metal, primer rough nonmetal, colour film coated pearl, witness lips polished and sanding notches dry; each nested layer has its own material tiers.',
 [('alloy_floor','exposed repair substrate'),('primer_ring','fine rough primer layer'),('colour_step','fine applied colour-film boundary'),('coat_ghost','subtle topcoat witness outline'),('gloss_lip','narrow polished repair edge'),('sand_notch','small dry sanding cut at an edge')],
 [('bth_mask_bleed','capillary leakage under tape rather than nested repair layers'),('wrap_layered_cut','pierced applied foil sheets rather than buried coating repair')]),
'bth_buff_hologram':entry('Rotary Buff Hologram',
 'Tiny rotary arcs overlap through polished cobalt alloy: hooked pigtails, bright arc lips, compound grains, burnished flats and short residual haze bands.',
 'Dense independent fine 8–24px rotary arc clusters have changing sweep angle and broken endings; hooked pigtails, compound grains and burnished flats remain rooted in their polish tracks.',
 'Arc scores locally rough, bright lips polished metal, compound grains matte, burnished flats strongly coated and residual haze weakens coat along its own sweep.',
 [('rotary_arc','fine curved polishing score'),('pigtail_hook','short hooked rotary end'),('bright_arc_lip','narrow polished score edge'),('compound_grain','small rooted abrasive compound'),('burnished_flat','local intact polished alloy'),('residual_haze','short dry polish haze aligned to arcs')],
 [('bth_sand_scratch','crossed straight grit scoring rather than rotary arc clusters'),('wrap_holographic','etched foil rosettes rather than directional polishing marks')],chapter='Filmcraft'),
'bth_mask_bleed':entry('Mask Bleed Lace',
 'Fine colour fingers wick beneath cut masks into pale primer: branched capillary tongues, pinned dye beads, sharp mask edges and differently coated bleed menisci.',
 'Connected fine mask boundaries feed unequal branched capillary fingers; sharp cut edges, pinned dye beads and primer pockets show actual leakage from one side of a mask.',
 'Bleed pigment coated dielectric-pearl, primer matte, cut mask edges polished, pinned beads strongly coated and dry finger tips rougher; material states follow actual wicking.',
 [('capillary_finger','fine dye tongue under a mask'),('cut_mask_edge','sharp boundary feeding the bleed'),('pinned_dye_bead','small wet bead on a finger'),('primer_pocket','exposed primer between fingers'),('bleed_meniscus','fine wet pigment edge'),('dry_finger_tip','rough terminal end of a capillary tongue')],
 [('wrap_air_release','manufactured air channels rather than irregular pigment wicking'),('bth_edge_map','nested buried repair stack rather than capillary leakage')],chapter='Filmcraft'),
'bth_tape_ridge':entry('Cured Tape Ridge',
 'Fine cured paint shelves rise around pulled mask cuts: stepped colour plateaus, polished ridge walls, ragged tear teeth, primer slivers and trapped edge pigment.',
 'Nested offset mask cuts leave fine stepped coating plateaus and raised ridge walls; tear teeth, exposed primer slivers and trapped pigment stay attached to the pulled-mask edge, not removable cloth tape.',
 'Cured plateau coated pearl, ridge wall graded metal-pigment, primer slivers rough nonmetal, tear teeth dry, ridge crowns polish and trapped pigment separately coated.',
 [('colour_plateau','fine cured paint build shelf'),('ridge_wall','raised wall at a pulled mask'),('ridge_crown','polished narrow build edge'),('tear_tooth','small ragged coating tear'),('primer_sliver','fine exposed primer below a ridge'),('trapped_pigment','small deposited grain at an edge')],
 [('mul_tape_seam','removable crossing cloth tape rather than cured paint build'),('wrap_panel_seam','applied panel step rather than a pulled-mask coating wall')],chapter='Filmcraft'),
'bth_water_spot':entry('Mineral Water Spot',
 'Drying hard water leaves fine broken mineral rims through lacquer: salt fans, clear lens hearts, etched stain floors and small copper-pearl residue grains.',
 'Unequal drying droplets leave incomplete coffee-ring mineral arcs and inward salt fans; clear hearts, etched floors and small residue grains stay clipped to actual drying pools.',
 'Mineral salt rough dielectric, intact hearts glossy coat, etched floors subdued, residue grains graded pearl-metal and incomplete wet rims separately coated.',
 [('mineral_rim','broken hard-water drying ring'),('salt_fan','fine inward mineral crystallisation'),('clear_heart','intact clear droplet centre'),('etched_floor','subdued dried stain area'),('residue_grain','small deposited mineral pigment'),('wet_rim','remaining incomplete smooth meniscus')],
 [('bth_fisheye','paint retreat craters rather than dried mineral residue'),('wrap_wet_apply','water still under film rather than hard-water drying rings')])
}
