"""Film topology declared before rendering. SPB-105 / CORE-WORKS 2026-09-30."""
FILM='https://multimedia.3m.com/mws/media/2419562O/application-vehicle-color-change-ra-pdf.pdf'
DATA={
'wrap_panel_seam':('Panel Step Inlay','Filmcraft','Irregular fine trapezoidal film panels meet through offset stair joints, exposed adhesive lands and tiny keyed corners.','Panel roofs coated pearl, riser walls graded metal, adhesive lands rough dielectric; corners polished and registration cuts coat-reflection-minimized.','panel_roof riser_wall adhesive_land corner_key polished_edge register_notch','bth_tape_ridge','pulled-mask coating walls rather than separate applied panels','mul_shutline_fake','printed impossible seams rather than material steps'),
'wrap_squeegee':('Squeegee Witness','Filmcraft','Unequal dense fine diagonal installer passes overlap at changing angles; rolled pressure toes, dragged adhesive ribs, dark rear roots and recovering shoulders belong to each actual pass.','Compressed film smoother with stronger coat, ribs rougher, pressure toes polished pigment, adhesive traces matte and dust cuts dry.','pressure_pass pressure_toe adhesive_rib recovering_shoulder dust_cut compression_root','wrap_brushed_film','metal brush grain rather than polymer compression','bth_sand_scratch','abrasive cuts rather than pressure passes'),
'wrap_microbubble':('Microbubble Emboss','Paint Alchemy','Asymmetric fine four-lobed trapped-air pillows join through continuous sealing webs, with pinch roots and tiny satellite vents.','Caps glossy dielectric-pearl, pinch roots rough, webs subdued coated polymer, vents coat-reflection-minimized and cap shoulders separately tiered.','air_pillow cap_roof pinch_root sealing_web cap_shoulder satellite_vent','bth_solvent_pop','ruptured shells rather than intact film caps','mul_bubble_clad','regular packaging quilt rather than irregular trapped air'),
'wrap_laminate':('Laminate Parallax','Optical Deception','Two independently engraved fine plies have offset angular windows, separate projected rulings, double cut edges and adhesive moire.','Top ply coated dielectric, lower foil graded metal, adhesive matte, double edges polished and print grooves rough; no extra transparency shader.','top_ply lower_window double_edge top_ruling lower_ruling adhesive_moire','wrap_layered_cut','pierced continuous foil lace rather than angular ply windows','mul_moire_defeat','print interference rather than physical layer parallax'),
'wrap_brushed_film':('Brushed Satin Alloy','Filmcraft','Unequal directed bundles contain five to nine short 8–28px brush filaments with tapered starts, broken ends, crossgrain cuts and displaced burrs.','Metal filaments graded roughness, burrs polished high metal, crossgrain cuts rough and dry; satin restraint has abundant fine construction.','brush_filament tapered_start broken_end crossgrain_cut polished_burr satin_land','bth_sand_scratch','independent crossed grit rather than directed brush bundles','wrap_squeegee','polymer compression rather than metal satin grain'),
'wrap_print_band':('Print Register Prism','Optical Deception','Unequal fine oblique print-pass bars carry three displaced ink registrations, dark overlap traps, clipped halftone dots and small foil slots.','Ink registrations dielectric, overlaps rougher, exposed foil high metal, dots individually coated and registration lips smooth.','print_pass cyan_register rose_register overlap_trap halftone_dot foil_slot','bth_tiger_stripe','feathered spray rather than displaced ink','mul_pixel_break','partition pixels rather than registered print strips'),
'wrap_perf_window':('Perforated Window Film','Optical Deception','Fine short rounded oblique slots have staggered lengths and alternating punch angles; thin web bridges, recessed backing and asymmetric burrs establish actual perforation.','Film faces coated pearl, cut lips polished foil, dark backing rough dielectric, bridges coated polymer and burrs exposed metal.','punched_slot cut_lip optical_backing web_bridge punch_burr face_print','wrap_air_release','hidden adhesive channels rather than open slots','wrap_lens_array','closed lenses rather than perforations'),
'wrap_knife_edge':('Knife Cut Suture','Filmcraft','A fine nonperiodic angular cut network has displaced one-sided flaps, exposed backing, interrupted uncut bridges and pointed turn burrs.','Backing rough nonmetal, flap roof coated pearl, knife walls metallic polish, bridges retain coat and torn tips dry.','knife_suture cut_flap backing_gap uncut_bridge turn_burr flap_root','wrap_craze_net','brittle fracture rather than deliberate bridged incisions','wrap_layered_cut','two pierced sheets rather than a scored single film'),
'wrap_air_release':('Air Release Manifold','Filmcraft','Fine curving adhesive spines feed staggered oblique blind vents; unequal collector pockets, narrowed throats, paired channel walls and film roof ribs trace manufactured air routing without box-grid intersections.','Adhesive valleys and collector pockets rough dielectric, walls smooth coated pearl, throats separately roughened, blind vent caps dry and film ribs moderately coated.','curved_spine blind_feeder collector_pocket vent_throat channel_wall blind_cap roof_rib','mul_pixel_break','curved open manifolds and blind oblique vents rather than closed square printed pixel plates','wrap_perf_window','hidden adhesive passages rather than open punched slots'),
'wrap_heat_gun':('Heat Glazed Print','Paint Alchemy','Fine displaced halftone inks soften inside unequal thermal dwell patches; glazed film, stretched recovery streaks, melted pigment pools and rooted witness lips trace the heated print.','Cold print rougher dielectric, hot film strongly glossy, recovery streaks rougher, pigment pools separately coated and witness lips polished pigment. No thermal emission is claimed.','printed_halftone softened_ink thermal_glaze recovery_streak pigment_pool gloss_witness','wrap_print_band','mechanical registration strips rather than thermally softened dots','bth_blush','moisture whitening rather than heat-softened print'),
'wrap_lift_curl':('Lifted Film Edges','Filmcraft','Unequal fine polygonal shingles lift at selected boundaries, exposing curled undersides, amber adhesive lands, dark hinges and directional roof creases.','Roofs coated pearl, undersides metal, tack lands matte, hinges dry and curl lips polished.','film_shingle curled_underside adhesive_land hinge_root roof_crease curl_lip','bth_lifting','continuous attacked paint rather than adhesive shingles','slt_shed_ecdysis','papery biological membrane rather than applied film'),
'wrap_wet_apply':('Wet Apply Meniscus','Paint Alchemy','Unequal fine elongated liquid lenses connect by capillary drainage paths; dry contact islands, pale menisci and particle wakes show liquid under film.','Liquid glossy dielectric, dry contacts subdued, capillary necks strongly coated, particles rough and film shoulders pearl.','liquid_lens capillary_neck dry_contact meniscus_lip particle_wake film_shoulder','bth_water_spot','dry residue rather than trapped liquid','wrap_microbubble','air pillows rather than draining liquid lenses'),
'wrap_creases':('Crease Fold Prism','Filmcraft','Unequal fine triangular fan folds have alternating front/back planes, short discontinuous hinges, crumpled junctions and sharp crease roots.','Faces separately tiered coated film, valleys rough, crowns polished pigment, shadow pockets dry and hinges subdued.','fold_plane crease_valley fold_crown shadow_pocket crumple_junction hinge_line','slt_diamondback','biological rhombs rather than asymmetric film fans','mul_false_shadow','printed shadows rather than material folds'),
'wrap_roll_memory':('Roll Memory Scroll','Filmcraft','Opposing incomplete fine spiral turns alternate handedness and unequal pitch, with open seams, compressed ribs and thin turning lips.','Curl roofs coated polymer, ribs rougher, turning lips metallic pigment, seams dry and crease witnesses subdued.','stored_curl compression_rib opening_seam scroll_lip crease_witness relaxed_land','wrap_spiral_burnish','radial pleats rather than storage curls','lsk_tesla_streamer','electrode windings rather than polymer roll memory'),
'wrap_ceramic_coat':('Ceramic Levelled Glaze','Paint Alchemy','Intact continuous blue-grey glaze carries fine unequal levelling tongues, short fluid contact necks, attached glass beads, cured menisci, local wipe striae and rare pigment witnesses. Small fluid anatomy owns the image; quiet paint is intentional.','Glass coating and beads mostly dielectric and glossy; levelling striae and contact necks locally rougher, menisci polished, sparse artistic pigment witnesses partly metallic. Material variation traces local fluid features without a metallic house template.','glass_coat levelling_tongue contact_neck attached_bead cured_meniscus wipe_stria pigment_witness','wrap_craze_net','intact fluid levelling tongues and beads rather than a brittle fracture forest','bth_blush','individual fluid contacts rather than moisture clouding and condensation voids'),
'wrap_hex_ppf':('Hex PPF Veil','Filmcraft','Fine engineered polymer cells partition elastic protective film: recovered roofs, narrow adhesive seats, short stress ribs, healing witnesses and small pigment traces.','Elastic film and seats remain mostly nonmetal; recovered roofs glossy, stress ribs rougher, adhesive matte and tiny artistic pigment traces partly metallic. No actual shader self-healing is claimed.','hex_cell elastic_roof adhesive_seat stress_rib healing_witness pigment_trace','mul_edge_chamfer','printed impossible bevels rather than protective polymer cells','wrap_ceramic_coat','hard coating rather than applied elastic film'),
'wrap_twill_film':('Twill Surge Foil','Filmcraft','Fine curved unequal warp/weft ribbons obey two-over-one twill occlusion, with underpasses, pressed crowns, parallel edge filaments and split ends.','Warp high metal, printed weft coated pearl, underpasses rough, crowns polished and split ends dry.','warp_ribbon weft_ribbon underpass pressed_crown edge_filament split_end','wrap_truchet_knurl','quarter-turn paths rather than twill crossings','mul_matte_cover','dry cloth rather than metal foil twill'),
'wrap_truchet_knurl':('Truchet Facet Knurl','Filmcraft','Binary diagonal folds join opposed triangular foil facets into an irregular knurl network; fine engraved grip cuts, blind adhesive windows, clinched corner bosses and keyed fold tabs belong to their own facet.','Opposed foil faces use independent local metal/polish tiers; engraved grips roughen only one face, adhesive windows stay dielectric and dry, fold trenches expose backing, and corner bosses and tab lips polish separately.','triangular_foil_facet diagonal_fold engraved_grip adhesive_window clinched_boss keyed_fold_tab foil_hem','ff_truchet_glass','original triangular Truchet grammar and cut foil faces, not the existing quarter-circle glass routes','wrap_twill_film','binary diagonal facets rather than a woven over-under filament lattice'),
'wrap_craze_net':('Craze Fracture Lacquer','Paint Alchemy','Fine unequal angular brittle fissures branch through film, with stopped tips, asymmetrically lifted lips, rooted secondary cracks and flaked junctions.','Intact coat glossy pearl, fissures rough coat-reflection-minimized, lips polished pigment, flakes dry and tips subdued.','primary_fissure secondary_crack stopped_tip lifted_lip flaked_junction intact_face','wrap_knife_edge','deliberate bridged incisions rather than brittle fractures','bth_die_back','wrinkled unbroken coat rather than open cracks'),
'wrap_lens_array':('Lenticular Lens Field','Optical Deception','Unequal fine short cylindrical lenticules stagger in direction and carry paired opposing print lanes, barrel crowns, recessed roots and polished cap ends.','Caps glossy dielectric, print lanes coated pearl, roots rough, split seams subdued and small backing reveals metal.','cylindrical_lens opposing_print barrel_crown split_image lens_root cap_end','mul_retro_patch','spherical beads rather than cylindrical lenses','wrap_perf_window','open holes rather than closed lens caps'),
'wrap_flow_wrapline':('Flow Streamlet Inlay','Filmcraft','Dense short curving foil streamlets follow a rotating grain field; independently crowned ribbons split into twin tails over recessed ink beds, with one polished rail, transverse braking cuts, leading prism lips and blind tension ports. No continuous lamella or broad common background carries the design.','Ribbon roofs graded metal and polish, rails brighter exposed foil, ink beds dry dielectric, braking cuts roughened foil, leading lips independently polished and tension ports dry backing. Local feature tiers own colour and all three spec channels.','foil_streamlet crowned_ribbon split_tail recessed_ink_bed polished_rail braking_cut prism_lip tension_port','wrap_hex_ppf','short open curved split ribbons rather than closed polymer cell roofs','wrap_laminate','worked individual foil streamlets rather than offset engraved sheet windows'),
'wrap_spiral_burnish':('Spiral Burnish Film','Filmcraft','Dense fine eccentric spiral polish scores connect through short dragged tails in a continuous clear film, with score lips, compound grains and unbroken smooth recovery lands.','Clear film mostly dielectric-pearl; scores rougher with weaker coat, lips polished pigment, compound matte, drag tails separately coated and recovery lands glossy.','spiral_score dragged_tail score_lip compound_grain recovery_land cross_shear','bth_buff_hologram','fragmented rotary arc clusters in alloy rather than complete eccentric spirals in clear film','wrap_roll_memory','elastic storage curls rather than surface polishing scores'),
'wrap_overlap_ghost':('Overlap Ghost Register','Filmcraft','Two independent fine angular film-island fields overlap, showing doubled buried silhouettes, paired menisci, clipped lower print edges and trapped adhesive pockets.','Single ply coated pearl, overlap stronger coat with subdued roughness, buried ink rough, menisci polished and adhesive pockets matte.','single_ply overlap_zone buried_silhouette double_meniscus buried_print adhesive_pocket','wrap_laminate','engraved ply windows rather than doubled island ghosts','wrap_layered_cut','pierced opaque foil rather than buried silhouettes')
}
DETAILED={'wrap_hex_ppf','wrap_twill_film','wrap_truchet_knurl','wrap_craze_net','wrap_lens_array','wrap_flow_wrapline','wrap_spiral_burnish','wrap_overlap_ghost'}
TABLE={fid:('detailed_film' if fid in DETAILED else 'filmcraft',name,chapter,carrier,carrier,spec,
 [(m,m.replace('_',' ')+' rooted in '+name) for m in marks.split()],FILM,
 [(n1,d1),(n2,d2)]) for fid,(name,chapter,carrier,spec,marks,n1,d1,n2,d2) in DATA.items()}
TABLE['wrap_ceramic_coat']=TABLE['wrap_ceramic_coat'][:7]+('https://www.carpro.global/product/dquartz/',)+TABLE['wrap_ceramic_coat'][8:]
TABLE['wrap_truchet_knurl']=TABLE['wrap_truchet_knurl'][:7]+('https://archive.bridgesmathart.org/2011/bridges2011-311.html',)+TABLE['wrap_truchet_knurl'][8:]
